### ISSUE TITLE
Ctrl+Shift+Z is redo command on Linux but on Synfig it's Zoom to Fit 

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1005]
**Synfig version & platform**:
1.3.11

**Issue description**:
On Linux the keyboard combination Ctrl+Shift+Z is for redo action.

Got used to redo-ing previous undo actions using that keyboard shortcut after using a GNOME Linux distro *(Some GNOME apps register only Ctrl+Shift+Z as the redo command and not Ctrl+Y)*
This shortcut works on XFCE desktop too.

Don't you think Synfig Zoom to Fit keyboard shortcut is conflicting with the Linux standard redo shortcut key?

**Comment by morevnaproject** [comment]
Good idea.  ^__^
What shortcut should we bind to "Zoom to Fit" then?
`Ctrl+0`? (Ctrl+zero)

**Comment by rodolforg** [comment]
Hmm... I think `ctrl 0` should mean Zoom to 100%

**Comment by morevnaproject** [comment]
I actually expected `Ctrl+1` for Zoom to 100% ^__^

**Comment by Jose-Moreno** [comment]
`Ctrl + 0` is common for `Fit To Screen` (_usually the **width** of the canvas is fit to the view boundaries against panels_) and I agree that `Ctrl + 1` is common for setting the Zoom to  `100%`

**Comment by rodolforg** [comment]
Firefox and Opera browsers use `ctrl + 0` for Zoom to `100%` :)

**Comment by Jose-Moreno** [comment]
@rodolforg That's correct. I was thinking of animation software, not browsers though, however I made a mistake in my previous comment.

I meant to say `Reset to default zoom` instead of `Fit to Screen`, so apologies for the confusion. In that sense you are correct to say that `Ctrl + 0` resets to 100% as this is often the **default** Zoom factor.

On Flash / Animate CC however `Ctrl + 1` is used to bring the Zoom factor to 100%, which is what i referenced on the second part of my comment.
![image](https://user-images.githubusercontent.com/4912907/69000223-38412280-089a-11ea-84c4-f530ad285a80.png)

That said I think `Ctrl + 0` should be used to default to 100% and then `Ctrl + 1` _could_ be `Fit to Screen` :+1:

**Comment by hellocatfood** [comment]
In Inkscape when no object is selected the number keys (1 - 0) control zoom levels https://wiki.synfig.org/Keyboard_Shortcuts:

1 | zoom 1:1
2 | zoom 1:2
3 | zoom to selection
4 | zoom to drawing
5 | zoom to page
6 | zoom to page width

If this was used it wouldn't overwrite any existing shortcuts, meaning ctrl+shift+z can be used for redo.

**Comment by Keyikedalube** [comment]
@hellocatfood I tried those keys on Inkscape. It works even with the object selected also (if you mean transform tool or path tool)

Uh... create a new feature request for this?

**Comment by Keyikedalube** [comment]
Anyway, @morevnaproject @rodolforg @Jose-Moreno Don't you guys think Inkscape style is easier than holding key combinations?

**Comment by rodolforg** [comment]
Whoa! I just checked the Inkscape shortcuts for tools... they aren't number keys anymore!!! 

So they are simple one-key shortcut, just like Gimp. Nice.

**Comment by Keyikedalube** [comment]
The solution I have in mind is using the `#if` directive.

**Comment by Keyikedalube** [comment]
Easy issue for Hacktoberfest :)

**Comment by morevnaproject** [comment]
Is this okay to close because off #1769? ^__^

**Comment by Keyikedalube** [comment]
Not yet...

I tested that PR and found out we need to explicitly set the redo shortcut key to `Ctrl+Shift+Z` otherwise the key doesn't respond.

We've to use the `#if` directive to let compiler decide the shortcut key for redo depending on the platform synfig is being compiled on.
- `Ctrl+r` for other platforms
- `Ctrl+Shift+Z` for Linux

**Comment by ice0** [comment]
On Windows `Ctrl+Y` is standard redo shortcut.

**Comment by Keyikedalube** [comment]
I'm making a PR for this issue.

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
