### ISSUE TITLE
Finish spline with double-click

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1009]
Continuing the topic brought up in #1008, when using Spline Tool (or Polygon Tool) it would be nice to finish spline (and polygon) creation by double-click. ^__^

@rodolforg what do you think about this?

**Comment by rodolforg** [comment]
Where user should double-click on to finish spline/polygon creation?

**Comment by morevnaproject** [comment]
On empty space.

Double clicking on empty space of workarea should set a point at this place and finish spline/polygon creation.

This is a common approach for vector editors (for example in Inkscape).
