### ISSUE TITLE
Wrong Width Points result

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#1014]
**Synfig version & platform**:
Master
Linux

**Issue description**:
The influence of the width points from advanced outlines have an offset in closed shapes.

[I show you the problem here.](https://youtu.be/mdiBtnrqQxc)

**Comment by morevnaproject** [comment]
@blackwarthog Can you take a look at this, please?

**Comment by ebarranco** [comment]
Thanks @blackwarthog this works well now. I did find a new problem with these handlers, I'll make a new report. ( #1027 )
