### ISSUE TITLE
Can't find lottie export option in developer snapshot windows

### ISSUE THREAD

**Issue by upendra-web** [synfig/synfig#1017]
**Synfig version & platform**:
Version - Synfig Studio 1.3.11 Development Snapshot
Platform - Windows 10

**Issue description**:
Recently I downloaded the synfig studio development snapshot from fosshub. After installation, I can't find the lottie export option. Can you tell me where I can find this option? Thanks in advance.

![Screenshot (2)](https://user-images.githubusercontent.com/43108965/69490013-0b4acc00-0ea7-11ea-886b-eb1001d17b96.png)
![Screenshot (3)](https://user-images.githubusercontent.com/43108965/69490014-0b4acc00-0ea7-11ea-8a73-d045d428f6b7.png)

**Comment by ankit-kumar-dwivedi** [comment]
Hi @upendra-web yes, it's not there in 1.3.11.
You need to build the latest master branch on synfig for trying the lottie export option. We will be soon releasing a new version with all the new features. :)
Closing this now!

**Comment by upendra-web** [comment]
Cool, thanks for the info

**Comment by upendra-web** [comment]
Just one more question is there any roadmap for synfig releases? Because I really liked the lottie feature and can't wait to get it in an official release.

**Comment by morevnaproject** [comment]
@upendra-web Lottie will be shipped with 1.3.12 (development version)  and 1.4.0 (stable version).

**Comment by upendra-web** [comment]
Thank you so much, can't wait for the update
