### ISSUE TITLE
Bug in "filesystemtemporary.cpp"?

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1020]
Hi! I was looking at code of `filesystemtemporary.cpp` and found a weird thing  at line 378 - 

https://github.com/synfig/synfig/blob/79febec2722b8bb6600e3ef6c4f1d5291d3bf12a/synfig-core/src/synfig/filesystemtemporary.cpp#L370-L384

Should it be `if (remove_files)` instead of `if (!remove_files)`?

@blackwarthog, please check. ^__^

**Comment by morevnaproject** [comment]
This is probably the reason why some temporary files not deleted after "Save As" operation.

**Comment by blackwarthog** [comment]
> Should it be if (remove_files) instead of if (!remove_files)?

yes, it's a bug

**Comment by morevnaproject** [comment]
Thanks! ^__^
