### ISSUE TITLE
These are suggestion for feature improvement in Synfig

### ISSUE THREAD

**Issue by Nampoina-Eddy** [synfig/synfig#1043]
Hello Everyone! So I use since v1.0, i like it but I miss some features from other software.
First, selection. in incscape there are two selections mode:
- object. This mode can move, rotate, scale the entire object
- spline. this mode controle point, spline
![Object_selection](https://user-images.githubusercontent.com/58734923/70532921-48c28100-1b58-11ea-93e5-1d1435868267.png)

![Spline-selection](https://user-images.githubusercontent.com/58734923/70533001-70194e00-1b58-11ea-998b-5a57c0041ef5.png)

Seconde thing, the ability to trim layer, like in video editing. in after effect, we can, and so we can also slide the layer along the timline, and bring all keyframe in it
![Trim_layer_move](https://user-images.githubusercontent.com/58734923/70533047-87583b80-1b58-11ea-9ae0-73caebae3bbe.PNG)

Finaly, Spline editor to manipulate keyframe. I know synfig has it but it a little difficulte to use
![real_spline_editor](https://user-images.githubusercontent.com/58734923/70533523-968bb900-1b59-11ea-87cc-27770600e395.png)

Thanks for considering these request.

**Comment by ice0** [comment]
Thank you!

**Comment by hellocatfood** [comment]
Shouldn't these be separate bug reports/feature requests?

**Comment by morevnaproject** [comment]
Absolutely agree. @Nampoina-Eddy can you please submit your feature requests as separate issues?
