### ISSUE TITLE
Cannot build Linux AppImage via morevna-builds (Debian 7)

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1044]
Commit id: 333dbe6770ad0d083ebd636d06e1b7e694e34702

Linux 64bit build gives the following error:

```
echo " File \"images\\interpolation_type_ease_icon.png\"" >>./images.nsh
echo " Delete \"\$INSTDIR\\share\\pixmaps\\interpolation_type_ease_icon.png\"" >>./unimages.nsh
echo "  File \"images\\layer_other_skeleton_icon.png\"" >>./images.nsh
echo "  Delete \"\$INSTDIR\\share\\pixmaps\\layer_other_skeleton_icon.png\"" >>./unimages.nsh
echo " File \"images\\layer_other_importimage_icon.png\"" >>./images.nsh
echo " Delete \"\$INSTDIR\\share\\pixmaps\\layer_other_importimage_icon.png\"" >>./unimages.nsh
echo " File \"images\\canvas_icon.png\"" >>./images.nsh
echo " Delete \"\$INSTDIR\\share\\pixmaps\\canvas_icon.png\"" >>./unimages.nsh
synfig(15584) [14:32:20] warning: Curve subdivision somehow ran out of space while tessellating!
make[2]: *** [valuenode_icon.png] Segmentation fault (core dumped)
make[2]: Leaving directory `/build/packet/linux-64/synfigstudio-master/build/synfig/synfig-studio/images'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/build/packet/linux-64/synfigstudio-master/build/synfig/synfig-studio'
make: *** [all] Error 2
```

Any help is appreciated. ^__^

**Comment by blackwarthog** [comment]
fixed

https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.11-testing-19.12.15-linux32-6b411.appimage
https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.11-testing-19.12.15-linux64-6b411.appimage
https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.11-testing-19.12.15-win32-6b411.exe
https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.11-testing-19.12.15-win32-6b411.zip
https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.11-testing-19.12.15-win64-6b411.exe
https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.11-testing-19.12.15-win64-6b411.zip

**Comment by morevnaproject** [comment]
Thank you so much! ^__^
