### ISSUE TITLE
Synfig Studio hangs on exit

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1047]
Latest windows build. Tested on Windows 7.

**Comment by rodolforg** [comment]
Probably it's something related to threads :/
It happened sometimes even before those changes.

**Comment by ice0** [comment]
It hangs because ReadFile https://github.com/synfig/synfig/blob/0001b32dbdf4b4f6745ffbe3b4966e677bab2e45/synfig-studio/src/gui/ipc.cpp#L134 is waiting for input, and we are wating until thread is finished https://github.com/synfig/synfig/blob/0001b32dbdf4b4f6745ffbe3b4966e677bab2e45/synfig-studio/src/gui/ipc.cpp#L222

I currently have a workaround, but I'm looking for a better solution.

**Comment by rodolforg** [comment]
Maybe uncomment the parameter PIPE_NOWAIT of CreateNamePipe`A`:
https://github.com/synfig/synfig/blob/0001b32dbdf4b4f6745ffbe3b4966e677bab2e45/synfig-studio/src/gui/ipc.cpp#L108
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createnamedpipea

Or try to peek pipe buffer before blocking to read its contents:
https://docs.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-peeknamedpipe

**Comment by morevnaproject** [comment]
Should we merge a solution from "debug" branch? - https://github.com/synfig/synfig/commits/debug

**Comment by ice0** [comment]
@morevnaproject no, it doesn't work. I am working on solution.

**Comment by rodolforg** [comment]
It is fixed by #1098
