### ISSUE TITLE
Add python3-lxml to Windows installer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1050]
Required by Lottie exporter.

**Comment by omgitsraven** [comment]
Is there any known workaround for this in the meantime? I installed lxml manually, but it seems like Synfig still can't see it, I guess because it has its own installation of Python?

**Comment by morevnaproject** [comment]
On Windows and OSX Synfig has its own installation of Python.

**Comment by omgitsraven** [comment]
Is there any way to access it, in order to manually install lxml into it?

**Comment by morevnaproject** [comment]
Please let me know your OS.

**Comment by omgitsraven** [comment]
Ah, sorry! Windows 10.

**Comment by morevnaproject** [comment]
Please check a "python" directory in Synfig's installation path.

**Comment by omgitsraven** [comment]
so in order to easily install lxml, I'm trying to install pip, but this is giving me errors in some of the files that come with Synfig's python installation:

```
PS C:\Program Files\Synfig\python> ./python --version
Python 3.2.5
PS C:\Program Files\Synfig\python> curl https://bootstrap.pypa.io/3.2/get-pip.py -o get-pip.py
PS C:\Program Files\Synfig\python> ./python get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 17574, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 119, in bootstrap
    import setuptools  # noqa
  File "C:\Program Files\Synfig\python\lib\site-packages\setuptools\__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "C:\Program Files\Synfig\python\lib\site-packages\setuptools\extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "C:\Program Files\Synfig\python\lib\site-packages\setuptools\dist.py", line 103
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
PS C:\Program Files\Synfig\python>  
```

This seems to mean there's a problem in the setuptools installation, but I can't find any way to replace that without using pip……

**Comment by morevnaproject** [comment]
@omgitsraven Yes, the version of Python bundled with Synfig is very outdated. You can replace content of "python" directory with any other python installation (i.e. you can copy contents of your system python installation with lxml).

**Comment by morevnaproject** [comment]
@omgitsraven You can try to replace "python" dir with contents of this archive - https://www.synfig.org/files/python-3.6.4.zip (it already has pip installed).

**Comment by morevnaproject** [comment]
Implemented via https://github.com/morevnaproject/morevna-builds/commit/72e1c53f48338486413dcf5d5ba4618cb7a7fc8c

**Comment by omgitsraven** [comment]
That worked, thank you so much!!
