### ISSUE TITLE
"unsafe srcdir value" error trying to build ETL

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1058]
**Synfig version & platform**:
Synfig master (47d5d4c)
Windows 10 Pro 64-bit, MINGW64_NT-10.0-18363

**Issue description**:
On my machine the directory path to my home contains a space.
(in my case the home directory is called "Postazione 2")

This issue does not happen on my Linux machine where there isn't any space in the path.

Following the steps for building this is what happens:
1) Execute 1-setup-windows-msys2.sh and it works fine (64452ec).
2) Execute 2-build-production.sh and the script reports this error:
"unsafe srcdir value: path_with_blank_space"

Looking at the code the issue happens because the relative path contains a blank space, indeed executing ./configure while locating inside /synfig/ETL does not cause the error.

If we could change the script to execute ./configure while it is located in /synfig/ETL the relative path does not include the home directory which is causing the issue with the blank space. Is that a big issue?

**Comment by FirasH** [comment]
With cmake I could compile the master branch easily, so this issue could be resolved.

Only problem I noticed is that some icons are missing around the gui and the starting splash screen does not have an image.

@ice0, @AYESDIE do you know if this issue is already known?
I checked the issue tracked and found #1511 where seems resolved. In my case I just compiled with cmake and nothing else, this is my build:
![cmake_build](https://user-images.githubusercontent.com/6705690/91710772-185ac100-eb85-11ea-865d-4d8f6cb1f8d9.png)

**Comment by ice0** [comment]
It looks like the missing icons are standard GTK icons.
Please check if you have `mingw-w64-x86_64-adwaita-icon-theme` installed.

I'm missing a splash screen too, @AYESDIE, can you check it?

**Comment by ice0** [comment]
ok, found the problem: splash_screen is in './share/synfig/icons/classic/' but should be in './share/synfig/images/' directory.

**Comment by FirasH** [comment]
@ice0 
> It looks like the missing icons are standard GTK icons.
> Please check if you have `mingw-w64-x86_64-adwaita-icon-theme` installed.

`mingw-w64-x86_64-adwaita-icon-theme-3.36.0-1` was already installed before running the compilation.

**Comment by AYESDIE** [comment]
Okay, I think it's because those icons are not being moved to the right place either. I'll take a look at that and push those changes soon.

**Comment by ice0** [comment]
@FirasH Did it prints something interesting in console when you run Synfig Studio?

**Comment by ice0** [comment]
Linked [issue ](https://github.com/synfig/synfig/issues/1687) (GTK problems)

**Comment by rodolforg** [comment]
The big problem here is automake itself :/
You can workarounf configure problem by removing the two AM_xxxx lines in configure.ac .
But automake generates a Makefile with unescaped path/targets.

**Comment by FirasH** [comment]
With 88e56d2 icons and splash screen are visible 👍

**Comment by FirasH** [comment]
With CMake it should build regardless of spaces in paths.
Closing.
