### ISSUE TITLE
Inconsistent Synfig UI on GNOME desktop

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1061]
**Synfig version & platform**:
Building from master branch
Debian sid

**Issue description**:
On GNOME desktop Synfig UI and native UI looks quite inconsistent. Below is an example screenshot taken for *About program's window*:
![Screenshot from 2019-12-31 22-22-12](https://user-images.githubusercontent.com/24214509/71628269-2edb0200-2c1d-11ea-9a45-c35e7f4306a1.png)
![Screenshot from 2019-12-31 22-26-12](https://user-images.githubusercontent.com/24214509/71628270-2edb0200-2c1d-11ea-89bb-8c1acd92fa3c.png)
Notice how the sizes of header buttons **About | Credits | Licence** for Synfig Studio doesn't match with the GNOME Terminal one
BTW the second screenshot is how all GTK apps look normally on GNOME desktop

Same is observed for file open dialog box:
![Screenshot from 2019-12-31 22-21-58](https://user-images.githubusercontent.com/24214509/71628495-364edb00-2c1e-11ea-9dca-c09396c2e0a2.png)
![Screenshot from 2019-12-31 22-44-16](https://user-images.githubusercontent.com/24214509/71628704-57fc9200-2c1f-11ea-9bca-f87d26a825f9.png)

**Comment by rodolforg** [comment]
Reason is here:

App::apply_gtk_settings()  (in synfig-studio/src/gui/app.cpp)

**Comment by Keyikedalube** [comment]
You mean the custom CSS that fixed the below issue?
https://github.com/synfig/synfig/blob/87e7ffa55e48d43323df3751576a685cc19010fb/synfig-studio/src/gui/app.cpp#L2337

**Comment by rodolforg** [comment]
yes.
but I commented out this part of code and... voilà.
I didn't see those toolbars and rulers that thick.
Anyway, maybe those toolbars should have specific CSS styles, and Synfig should not change the general ones

**Comment by Keyikedalube** [comment]
I'm working on this issue :)
