### ISSUE TITLE
Missing synfig app icon on Wayland session

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1063]
**Synfig version & platform**:
Building from master branch
Fedora 32 (GNOME Wayland)

**Issue description**:
Synfig app icon is not displayed on top bar as well as on dock panel

*Top bar*
![Screenshot from 2020-01-03 08-23-31](https://user-images.githubusercontent.com/24214509/71704799-766eb300-2e02-11ea-8b0e-6b20492dfed3.png)

*Dock panel*
![Screenshot from 2020-01-02 20-51-02](https://user-images.githubusercontent.com/24214509/71704858-b766c780-2e02-11ea-8a18-7d56889a1a58.png)

**Comment by Keyikedalube** [comment]
Previously I uninstalled the distribution maintained version of synfigstudio on Debian due to this [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941633)
That's when the app icon missing issue was reported

Then I installed it again (a few days ago) since the bug was fixed. And the icon is back... Looks like the development version loads the icon from the installed version.

Irrelevant issue? Since this relates to packaging synfig for production deployment. And not for everyday use.

**Comment by rodolforg** [comment]
did you install the custom build or just built and ran it?

**Comment by Keyikedalube** [comment]
Just built and ran it.

**Comment by Keyikedalube** [comment]
### A possible solution

On the synfig's main window implementation  *synfig-studio/src/gui/mainwindow.cpp* file add this statement:

`Gtk::Window::set_default_icon(<icon-file-identifier>)`

The identifier could be either synfig icon file or a resource file.

Right now I'm working on my personal gtkmm project. I prefer using resource file since it allows me to link the image file as binary during build process + the added bonus of not having to worry about managing end user's folder.

For building resource file I use [GCR_CMake](https://github.com/Makman2/GCR_CMake). I don't know about autoconf because it's new to me :(

**Comment by FirasH** [comment]
The same happens on Windows 10 when I add to the lower toolbar as favourite:
![added_to_toolbar](https://user-images.githubusercontent.com/6705690/77150153-87d76b00-6a93-11ea-8cb1-5a0afe845f1d.png)

when it's not added as favourite, the icon is visible:
![not_added_to_toolbar](https://user-images.githubusercontent.com/6705690/77150316-ec92c580-6a93-11ea-871f-fd12a77f56a4.png)

**Comment by Keyikedalube** [comment]
Installed Fedora 32 today and tested synfig on Wayland session
Instead of blank icon shown in the first screenshot above, Fedora 32 now shows executable icon as a placeholder for synfig
![Screenshot from 2020-05-05 09-34-46](https://user-images.githubusercontent.com/24214509/81034315-5cc6a080-8eb4-11ea-8dba-64176986e30a.png)
I suspected this is wayland issue because I have set the window default icon on a personal gtkmm project of mine and encountered the same problem when running on wayland.
Switched to X11 and the icon was displayed...

So did the same for synfig on Fedora 32 by switching to X11 and we have this:
![Screenshot from 2020-05-05 09-33-41](https://user-images.githubusercontent.com/24214509/81034429-c777dc00-8eb4-11ea-992a-680fe39437d4.png)
 
I think this is an irrelevant issue for synfig (on Linux) since this relates to Wayland protocol

However, for Windows... I have no idea what could be causing it :(

**Comment by rodolforg** [comment]
On wayland, maybe this can help

https://github.com/nextcloud/desktop/issues/1435

**Comment by Keyikedalube** [comment]
Inquired about wayland issue on GTK irc channel.

Chat history: [My question](https://matrix.to/#/!aUhETchlgthwWVQzhi:matrix.org/$158882881364548qsgWF:matrix.org?via=gnome.org&via=matrix.org&via=breadpirates.chat)
Chat history: [Solution](https://matrix.to/#/!aUhETchlgthwWVQzhi:matrix.org/$158882978444934GJoJi:gnome.org?via=gnome.org&via=matrix.org&via=breadpirates.chat)

In summary, here's the quoted answer I got
> \*set the icon name\*
> wayland does not have a concept of pixel data for icon

Investigating...

**Comment by Keyikedalube** [comment]
GTK programs usually scan all the standard icons directory (both **system** _starting from the root_ and **user** _home directory_)

Strangely, setting the `set_icon_name()` or `set_default_icon_name()` on synfig doesn't seem to fix this issue.
For instance, I tried sudo cp _production/build/share/icons/hicolor directory to my /usr/share/icons/hicolor and based on [rodolforg's](https://github.com/synfig/synfig/issues/1063#issuecomment-623854239) comment above, renamed all synfig_icon.png to org.synfig.SynfigStudio.png, and inserted this statement in synfig-studio/src/gui/mainwindow.cpp MainWindow constructor
`set_default_icon_name("org.synfig.SynfigStudio");`

Also, tried installing the icons on my $HOME/.icons directory.
Didn't help either

Maybe, this is because of the isolated synfig installation structure

And just out of curiosity, I tried setting the icon name to the one that already came pre-installed on my gnome system ie., org.gnome.Calculator
Still got executable icon as replacement

**Comment by Keyikedalube** [comment]
Further investigation made today on [StackOverflow](https://stackoverflow.com/questions/61795889/gtkwindow-icon-set-with-set-icon-name-doesnt-work-on-wayland/)

In conclusion, this issue is irrelevant for **developers building from source** because this relates to production deployment ie., shipping synfig to end user's computer with .desktop file and corresponding icon files on /usr/share/ directory

Closing this issue this weekend
If someone would love to investigate it further... let me know and I'll leave it open :)

**Comment by ice0** [comment]
I will take a look later.

**Comment by Keyikedalube** [comment]
The best alternative solution would be generating a similar `org.synfig.synfigstudio-development.desktop` file and installing it in ~/.local/share/applications/ directory

We could do the same strategy like gnome development/nightly apps do
![Screenshot from 2020-06-25 04-22-04](https://user-images.githubusercontent.com/24214509/85635455-87a2c900-b69b-11ea-88cf-83c340194078.png)

**Comment by Keyikedalube** [comment]
So here's a Mac guy who encountered this same issue: https://discourse.gnome.org/t/window-icon-on-macos/9302

From https://github.com/synfig/synfig/issues/1063#issuecomment-628600799:
> In conclusion, this issue is irrelevant for developers building from source because this relates to production deployment ie., shipping synfig to end user's computer with .desktop file and corresponding icon files on /usr/share/ directory

Also the guy from GNOME discourse confirmed that this is wayland behavior by design:
> On wayland, there is no way to specify the window icon other than the .desktop file.

Closing it again LOL
