### ISSUE TITLE
Windows version crashes when calling any plugin

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1064]
Try to run any plugin on Windows -> It closes file, and then crashes when trying to re-open.

**Comment by morevnaproject** [comment]
It looks like that python script executes properly - when I try to run Lottie Exporter plugin the resulting file appears. So, crash seems to happen when Synfig tries to re-open file.

**Comment by morevnaproject** [comment]
Looks like this doesn't happen when plugin is called on newly created file. If you try to open existing file and then run a plugin - it crashes. Can someone confirm that? @rodolforg @ice0

**Comment by rodolforg** [comment]
I don't know if it is related to this issue, but I found a problem https://github.com/synfig/synfig/pull/1091

**Comment by morevnaproject** [comment]
@rodolforg Thank you for this! ^__^ Unfortunately, the problem persists after this.

**Comment by morevnaproject** [comment]
I have started Synfig via debugger and got this call stack after crash:
```
etl::handle<synfig::Canvas>::handle (this=0x23d868, x=0x2c2db280) at /d/synfig/ETL/ETL/_handle.h:159
etl::loose_handle<synfig::Canvas>::operator etl::handle<synfig::Canvas> (this=0x2c2d38b0) at /d/synfig/ETL/ETL/_handle.h:746
synfig::CanvasParser::parse_from_file_as (this=0x23d750, identifier=@0x23dac0: {file_system = {obj = 0x297d9660}, filename = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x23dad8 \"#project.sifz\"}, _M_string_length = 13, {_M_local_buf = \"#project.sifz\\000\\000\", _M_allocated_capacity = 8386658438904705059}}}, as=@0x23d940: {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2b7b1c60 \"C:\\\\temp\\\\Synfig Animation 1.sifz\"}, _M_string_length = 31, {_M_local_buf = \"\\037\\000\\000\\000\\000\\000\\000\\000c\\000\\000P\\000\\000\\000\", _M_allocated_capacity = 31}}, errors=@0x23d8e0: {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x23d8f0 \"\"}, _M_string_length = 0, {_M_local_buf = \"\\000\\037|+\\000\\000\\000\\000p\\000\\000\\000\\000\\000\\000\", _M_allocated_capacity = 729554688}}) at /d/synfig/synfig-core/src/synfig/loadcanvas.cpp:3508
synfig::open_canvas_as (identifier=@0x23dac0: {file_system = {obj = 0x297d9660}, filename = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x23dad8 \"#project.sifz\"}, _M_string_length = 13, {_M_local_buf = \"#project.sifz\\000\\000\", _M_allocated_capacity = 8386658438904705059}}}, as=@0x23d940: {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2b7b1c60 \"C:\\\\temp\\\\Synfig Animation 1.sifz\"}, _M_string_length = 31, {_M_local_buf = \"\\037\\000\\000\\000\\000\\000\\000\\000c\\000\\000P\\000\\000\\000\", _M_allocated_capacity = 31}}, errors=@0x23d8e0: {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x23d8f0 \"\"}, _M_string_length = 0, {_M_local_buf = \"\\000\\037|+\\000\\000\\000\\000p\\000\\000\\000\\000\\000\\000\", _M_allocated_capacity = 729554688}}, warnings=@0x23d900: {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x23d910 \"\"}, _M_string_length = 0, {_M_local_buf = \"\\000\\000\\004\\\\\\000\\000\\000\\000\\000\\205\\300-\\000\\000\\000\", _M_allocated_capacity = 1543766016}}) at /d/synfig/synfig-core/src/synfig/loadcanvas.cpp:174
studio::App::open_from_temporary_filesystem (temporary_filename={static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2dc05220 \"C:\\\\msys64\\\\home\\\\Admin/Synfig/tmp/synfig_instance_ED33647C5F06BF794D3ED6AE079F3218\"}, _M_string_length = 80, {_M_local_buf = \"P\\000\\000\\000\\000\\000\\000\\000C$G\\016\\000\\000\\000\", _M_allocated_capacity = 80}}) at /d/synfig/synfig-studio/src/gui/app.cpp:3894
studio::Instance::run_plugin (this=0x2c280330, plugin_path={static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2b754020 \"D:/synfig/_debug/build/share\\\\synfig\\\\plugins/lottie-exporter/lottie-exporter.py\"}, _M_string_length = 78, {_M_local_buf = \"N\\000\\000\\000\\000\\000\\000\\000\\020\\355#\\000\\000\\000\\000\", _M_allocated_capacity = 78}}) at /d/synfig/synfig-studio/src/gui/instance.cpp:406
sigc::bound_mem_functor1<void, studio::Instance, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator() (this=0x2dc083a0, _A_a1=@0x2dc083c0: {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2dc08410 \"@\\374\\271<\\372\\a\"}, _M_string_length = 78, {_M_local_buf = \"N\\000\\000\\000\\000\\000\\000\\000\\r\\360\\255\\272\", <incomplete sequence \\360\\255\\272>, _M_allocated_capacity = 78}}) at /mingw64/include/sigc++-2.0/sigc++/functors/mem_fun.h:2066
sigc::adaptor_functor<sigc::bound_mem_functor1<void, studio::Instance, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::operator()<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (this=0x2dc08398, _A_arg1=@0x2dc083c0: {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2dc08410 \"@\\374\\271<\\372\\a\"}, _M_string_length = 78, {_M_local_buf = \"N\\000\\000\\000\\000\\000\\000\\000\\r\\360\\255\\272\", <incomplete sequence \\360\\255\\272>, _M_allocated_capacity = 78}}) at /mingw64/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:89
sigc::bind_functor<-1, sigc::bound_mem_functor1<void, studio::Instance, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::operator() (this=0x2dc08390) at /mingw64/include/sigc++-2.0/sigc++/adaptors/bind.h:1124
sigc::internal::slot_call0<sigc::bind_functor<-1, sigc::bound_mem_functor1<void, studio::Instance, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>, void>::call_it (rep=0x2dc08360) at /mingw64/include/sigc++-2.0/sigc++/functors/slot.h:136
?? () at null:
...
?? () at null:
?? () at null:
main (argc=0, argv=0x1b732470) at /d/synfig/synfig-studio/src/gui/main.cpp:125
```

**Comment by morevnaproject** [comment]
What I did before it crashed with this call stack:
1. Opened file C:\temp\Synfig Animation 1.sifz
2. From menu selected "Plugins" -> "Export to Lottie"
3. Got a crash.

@blackwarthog Any ideas?

**Comment by morevnaproject** [comment]
Forgot to mention commit id. It is a3eb06b5c7516bc

**Comment by rodolforg** [comment]
How can I put python and its libxml in _debug build?

**Comment by ice0** [comment]
@rodolforg you can copy python folder and libxml to _debug/build from this archive:

https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.12-testing-2020.01.22-win64-b3d8b.zip

**Comment by rodolforg** [comment]
Interesting enough, I don't get a crash in my debug build with none of the 3 plugins. But I got a traceback report for Lottie.
If I use the snapshot you posted, it crashes.

**Comment by morevnaproject** [comment]
From debugger's call stack I can see that it is calling `studio::App::open_from_temporary_filesystem()` with the following argument:
```
C:\\\\msys64\\\\home\\\\Admin/Synfig/tmp/synfig_instance_ED33647C5F06BF794D3ED6AE079F3218
```
Note the wrong slashes. Could that be the problem?

**Comment by ice0** [comment]
> Interesting enough, I don't get a crash in my debug build...
> If I use the (whole) snapshot you posted, it crashes.

Same for me.

I can't reproduce it on latest master (https://github.com/synfig/synfig/commit/102e8f1fc6f2c838b43e11b68e4366b0f59cccd5), so @morevnaproject can you please check if this crush happens on my file?

[Synfig Animation 1.zip](https://github.com/synfig/synfig/files/4101952/Synfig.Animation.1.zip)

**Comment by ice0** [comment]
Ok, got it. Crash happens if you try to export a file without animations. Btw, @morevnaproject please check my file to be sure.

**Comment by morevnaproject** [comment]
> Note the wrong slashes. Could that be the problem?

Hmm, no. The problem is not related to that. I just had a few successful plugin runs with those slashes and it didn't crashed.

**Comment by morevnaproject** [comment]
@ice0 I will check the file.

I have a debug build at one commit earlier than 102e8f1 - b3d8bd046468526d1540e5908337f007cd2302f1. It still crashing. :(

**Comment by morevnaproject** [comment]
It crashes at this point. It looks like after closing canvas it is still present in `open_canvas_map`...
![screenshot_001](https://user-images.githubusercontent.com/332868/72971988-34cb9980-3dfd-11ea-95a8-638f7d835b9e.png)

**Comment by morevnaproject** [comment]
@ice0 I have tested your file. It is still crashing. Here is a video showing the process - https://www.youtube.com/watch?v=BbZBmhlNy9c

**Comment by ice0** [comment]
Ok. In your video i noticed what you open file from another drive. I don't know why you not mention this :)

To reproduce, i attached local directory as drive:
```
subst x: c:\mount\
```

and voila, the error is reproduced.

**Comment by morevnaproject** [comment]
@ice0 No, I can reproduce the same crash when file is opened from `C:\` ^__^
https://www.youtube.com/watch?v=Npg6r7GdrkU

**Comment by morevnaproject** [comment]
Okay, I have some progress.

1. I have edited function `CanvasParser::parse_from_file_as()` in `loadcanvas.cpp`, commented the following line:
```
return get_open_canvas_map()[etl::absolute_path(as)];
```
and added this line instead:
```
synfig::info("Canvas is already opened! ");
```

![screenshot_003](https://user-images.githubusercontent.com/332868/73057889-1b8e2000-3ec5-11ea-8640-303f8b3d9921.png)

Re-compiled the source and after that the crash is not happens anymore.

Of course, this is not a solution.
It is clear, that for some reason, when we close instance and removing `canvas` object it is not deleted from `open_canvas_map`.

The question is - why?

Here is a part of code that is related to `open_canvas_map`:

https://github.com/synfig/synfig/blob/102e8f1fc6f2c838b43e11b68e4366b0f59cccd5/synfig-core/src/synfig/loadcanvas.cpp#L124-L133

And here is a `_remove_from_open_canvas_map()` function attached to canvas deletion:

https://github.com/synfig/synfig/blob/102e8f1fc6f2c838b43e11b68e4366b0f59cccd5/synfig-core/src/synfig/loadcanvas.cpp#L3475-L3480

2. Here comes one more interesting thing - I have found that Synfig **always** crashes when I open file using "File" -> "Open" command. But it is **not always** crashes if I open file using "File" -> "Open Recent".

@ice0 @rodolforg Could that be the reason why you wasn't able to reproduce crash?

Also, when I looked at menu entries in "Open Recent", I found this -
![screenshot_004](https://user-images.githubusercontent.com/332868/73058878-2053d380-3ec7-11ea-977f-4d7d8a104523.png)

Duplicated entries!

Then I have opened `recentfiles` file, located in `C:\Users\USERNAME\Synfig\` (or in `C:\msys64\USERNAME\Synfig\` if you run Synfig from MSYS2 shell).

Here's what I found:

![screenshot_005](https://user-images.githubusercontent.com/332868/73059079-82acd400-3ec7-11ea-8450-6bd96a5ddeee.png)

Nice, eh? Different slashes!

So, I think the problem is because Synfig stores file path in `open_canvas_map`  with one type of slash ("\"), and when it requests to delete it, then it passes a filename with other type of slash ("/").
So, it doesn't finds entry in `open_canvas_map` and canvas remains registered (even when object is not valid anymore).

If you look at `Canvas::set_file_name()` function in `canvas.cpp` (which is used when "File" - "Save As..." called) -

https://github.com/synfig/synfig/blob/102e8f1fc6f2c838b43e11b68e4366b0f59cccd5/synfig-core/src/synfig/canvas.cpp#L1140-L1166

.. you will notice it calls `FileSystem::fix_slashes()`. 
This is why plugins not crashing when we do the following sequence:
* Open file using "File" -> "Open"
* Save it under different name using "File" - "Save As..."
* Run any plugin -> no crash.

**Comment by morevnaproject** [comment]
So, I suggest the following:

1. Modify `_remove_from_open_canvas_map()` function to verify if removed entry really exists in `open_canvas_map`. Throw error if it isn't exists.

2. Add `FileSystem::fix_slashes()` when file opened.

**Comment by ice0** [comment]
Easy way to reproduce the bug: open file, close and open it again :)
Btw, i am already fixed it just need to do some checks before commit.

**Comment by morevnaproject** [comment]
About #1112:

I think it is better to apply `FileSystem::fix_slashes()` function on file open instead of doing modification `cleanup_path()` function.

OR 

Do modification of `cleanup_path()` function and remove all traces of `FileSystem::fix_slashes()`, as it does basically the same thing - 

https://github.com/synfig/synfig/blob/102e8f1fc6f2c838b43e11b68e4366b0f59cccd5/synfig-core/src/synfig/filesystem.cpp#L184-L191
