### ISSUE TITLE
Feature Request: Show/Hide rulers

### ISSUE THREAD

**Issue by hellocatfood** [synfig/synfig#1077]
**Synfig version & platform**:
Synfig version 1.3.11 on Ubuntu 19.10

**Issue description**:
Can an option be added to show or hide the rulers? It would save a bit of vertical and horizontal space.

I would suggest that it go in the View menu under the options for Guides and Ctrl + Shift + R as a keyboard shortcut.

(this was discussed in for the forum in [2010](https://forums.synfig.org/t/52-notes/837) and [2014](https://forums.synfig.org/t/konstantins-weekly-report-48/3041)

**Comment by rodolforg** [comment]
@morevnaproject  in order to implement this, should the "arrow" menu-button be moved to the main workarea toolbar?
I was already thinking about implement a "[feature-discovery](https://materializecss.com/feature-discovery.html)"-like effect when user hides the main-menu to show from where you can access main-menu back.
Something could be done in this case also.

**Comment by morevnaproject** [comment]
I think it is okay to hide "arrow" menu-button, because user can access the same menu by right-clicking on empty space of workarea.

"feature-discovery" effect is cool.

**Comment by hellocatfood** [comment]
By feature discovery do you mean something like this?

![hide_rulers](https://user-images.githubusercontent.com/151947/72450160-cad64300-37b1-11ea-9bc8-17d6c6b2c088.gif)

Looks cool but I think having the rulers (or main menu) animate when they're hidden doesn't give any clues how to unhide it.

In the example link you gave the animation shows where a menu originated from and where a user has to click/press to reveal it again. If the rulers are hidden in the same way it doesn't disappear to a "tap target" that can be clicked/tapped on to reveal them again.

**Comment by rodolforg** [comment]
@hellocatfood the link shows a demonstration :) The pop-up (labeled) circle could appear on any event

**Comment by hellocatfood** [comment]
Ah, I see. This is starting to go off track so I'll make a new feature request, but instead of the feature-discovery idea you shard perhaps a Status Bar would be better. There's lots of examples of implementation in GIMP, Inkscape, and Blender

**Comment by mohamedAdhamc** [comment]
Hey guys, would it also be of any use to allow for hiding the vertical and horizontal rulers separately? I believe they should both be hidden together but just making sure.

**Comment by mohamedAdhamc** [comment]
@ice0 can this be safely closed now ?
