### ISSUE TITLE
ETL_VERSION not declared build error

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1088]
**Synfig version & platform**:
Building from source
Commit e30f368

**Issue description**:
Building synfigstudio from source exits with ETL_VERSION not declared error
![Screenshot from 2020-01-14 09-16-27](https://user-images.githubusercontent.com/24214509/72312591-9168df00-36ae-11ea-974c-84879dfe8204.png)

**Comment by ice0** [comment]
Which OS you are using?

**Comment by Keyikedalube** [comment]
Debian testing

**Comment by ice0** [comment]
Looks like it can't find ETL, but in that case it must stop at configure step.
I am trying to reproduce in my test container, but everything builds fine.
Can you try a clean build in a new folder?

**Comment by Keyikedalube** [comment]
`./2-build-production.sh all clean`

Hope that cleans out all previous build files and configurations

Then executed `./2-build-production.sh` and encountered the same error :(

Will try building in a new folder (delete synfig folder and clone it fresh) this time...

**Comment by Keyikedalube** [comment]
Removed synfig folder and cloned the project fresh this morning.

Build is successful!
*Next time build fails, might keep this trick handy :)*

Thanks @ice0 for looking into this issue.
Have a great day ahead!
