### ISSUE TITLE
Feature request: cancel button for the render progress bar.

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#1099]
**Synfig Studio 3.1.1**:

**Issue description**:

Hello friends of synfig studio. A happy 2020 for everyone.. I think it would be very useful if there was a button to cancel the rendering in the render progress bar.

Thank you very much for the excellent work and effort.

**Comment by rodolforg** [comment]
I think that red-circle button in the top-right corner of workarea does the job.

**Comment by Gilraiser** [comment]
OK sorry. I had not seen it. Many thanks.
