### ISSUE TITLE
"Remove Item (Smart)" crashes Synfig consistently

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1102]
**Synfig version & platform**:
Development version, revision e30f36

**Issue description**:
Steps:
0) Create a new synfig file
1) Add a new Skeleton: Layer > New Layer > Other > Skeleton
2) Create a Child Bone: right-click > Create Child Bone
3) Go to the Parameters panel and delete the child bone: right-click > Remove Item (Smart)

Synfig crashes consistently

**Comment by rodolforg** [comment]
Obs: Step 3 should be actually "Go to the Parameters panel and delete the child bone: left-click to select child bone -> right-click > Remove Item (Smart)"
If you don't select it, it works fine.
(But the app still crashes on exit)

**Comment by morevnaproject** [comment]
Is this a duplicate of #375?

**Comment by rodolforg** [comment]
I don't know, but this specific issue is fixed by #1104 .

**Comment by FirasH** [comment]
Fixed in `master` f806eb
