### ISSUE TITLE
Please add a progress bar

### ISSUE THREAD

**Issue by RezaSh13** [synfig/synfig#1106]
![image](https://user-images.githubusercontent.com/22277992/72896711-99bbbc80-3d35-11ea-96d0-55e2efcd5e53.png)

**Comment by rodolforg** [comment]
As for version 1.3.11, there's a Render Progress Bar in Info dock. `Menu Window > Info`

**Comment by RezaSh13** [comment]
When is the new version coming?

**Comment by rodolforg** [comment]
1.3.11 is already released. In the default workspace layout, it's in the top right corner dock.
Next version (1.3.12) seems to available soon.

**Comment by ankit-kumar-dwivedi** [comment]
Closing as this is not an issue.
