### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1111]

**Comment by morevnaproject** [comment]
That's true. The license is mentioned in README file ([ETL](https://github.com/synfig/synfig/blob/master/ETL/README), [core](https://github.com/synfig/synfig/blob/master/synfig-core/README), [studio](https://github.com/synfig/synfig/blob/master/synfig-studio/README)), but thre are no separate file exists. I think it would be nice to add one. ^__^

Interesting: when you build Synfig using Autotools, a COPYING file (with License text) appears at each directory (ETL, synfig-core and synfig-studio).

**Comment by morevnaproject** [comment]
It looks like COPYING file is created by `autoreconf --install`:

https://sourceware.org/autobook/autobook/autobook_25.html
http://manpages.org/autoreconf

https://github.com/synfig/synfig/blob/429c586b5bb399b5f10bf6b51b3b34a6841a560e/ETL/bootstrap.sh#L14-L15

**Comment by rodolforg** [comment]
It is created if `automake` is run with `--add-missing` flag. Probably `autoreconf`calls `automake` this way. [See manual](https://www.gnu.org/software/automake/manual/html_node/Gnits.html#Gnits)

You can provide your own `COPYING` (the license), though. You can even provide it with another filename, but you must change configure.ac to include `foreign` option to automake:
`AM_INIT_AUTOMAKE([-Wall -Werror foreign])`
[See manual](https://www.gnu.org/software/automake/manual/html_node/amhello_0027s-configure_002eac-Setup-Explained.html#amhello_0027s-configure_002eac-Setup-Explained)

**Comment by morevnaproject** [comment]
Related to #1168
