### ISSUE TITLE
PACKAGE_NAME not declared error building on netbeans

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1118]
**Synfig version & platform**:
master branch
commit e33a998

Debian unstable

**Issue description**:
I followed setting [NetBeans environment for synfig](https://synfig-docs-dev.readthedocs.io/en/latest/common/Setting%20up%20netbeans%20IDE.html) and did my first build.
Below was the error.

> /home/keyikedalube/Source/synfig/synfig-studio/src/gui/dialogs/about.cpp:83:19: error: ‘PACKAGE_NAME’ was not declared in this scope
>    83 |  set_program_name(PACKAGE_NAME);
>       |                   ^~~~~~~~~~~~
> make[2]: *** [synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/build.make:557: synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/dialogs/about.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1501: synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

I tried building from a clean folder on second try. Got the same error.

**Comment by Keyikedalube** [comment]
PACKAGE_NAME macro is missing in the MACROS header.

https://github.com/synfig/synfig/blob/024eac72aece88e4fd5b1a4c7809662854490c04/synfig-studio/src/gui/dialogs/about.cpp#L60-L74

Do I name PACKAGE_NAME as **"SynfigStudio"**?
Implemented the macro and tried building on my computer. Netbeans builds synfig successfully.

**Comment by rodolforg** [comment]
The current autotools build system files use "Synfig Studio" and "Synfig Core".

**Comment by Keyikedalube** [comment]
I made a very drastic mistake of building synfig with the build tool icon on NetBeans toolbar. Still, PACKAGE_NAME macro is needed (I think) because of GTK about dialog API ie., set_program_name and set_version are mandatory.

Anyway, back to building issue the final synfigstudio was generated on my synfig-studio/src/gui directory and not on the usual _debug/... directory.

But in my defense I read and followed the [instructions](https://synfig-docs-dev.readthedocs.io/en/latest/common/Setting%20up%20netbeans%20IDE.html#) correctly. The documenter didn't mention changing the values for **Clean Command** and **Build Command**
> - Click next and skip the Pre Build Action(do not check any option).
> - Under Build Action uncheck the clean and build after finish and click next:

I proceeded after unchecking the clean and build after finish and completely failed to notice the modified values for Clean and Build command in the screenshot. Originally, the values were something like `{Makefile} ...` (I don't correctly remember what came after that) But the screenshot displays `echo clean` and `echo build`

Now I know the purpose of setting up NetBeans for synfig was to code on a powerful text editor and build the project using the terminal toolbar.

However, I could do a PR with the PACKAGE_NAME macro set as "Synfig Studio" and close this issue. What's your opinion?

**Comment by ice0** [comment]
Sure, will be nice if you do PR.

**Comment by Keyikedalube** [comment]
@ice0 Made the PR #1133

**Comment by Keyikedalube** [comment]
Closing this issue since the PR's already merged.
