### ISSUE TITLE
Opening file via IPC on Windows makes synfig freeze

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1124]
**Synfig version & platform**:
1.3.11 and latest build from master (7fbaaab8c27a3c8290a11a7925292e8de502a159)

**Issue description**:
Steps to reproduce:
* Launch Synfig-studio
* Double-click any Synfig file in Explorer (make sure it contains only latin characters, otherwise you will hit another bug - #680)
-> Synfig hangs.

**Comment by ice0** [comment]
Duplicates https://github.com/synfig/synfig/issues/291

**Comment by morevnaproject** [comment]
Oh, right ^__^
