### ISSUE TITLE
Add "Scale to fit canvas" checkbox to image import dialog.

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1126]
Currently, "Scale to fit canvas" is an option in preferences -
![screenshot_002](https://user-images.githubusercontent.com/332868/73193280-e4d23700-415c-11ea-960b-aa9cfd90e9fa.png)

I think it is logical to place in Import Image dialog (appears after "File" - "Import"), so user can decide if he wants to fit canvas or not right during import -
![screenshot_003](https://user-images.githubusercontent.com/332868/73193430-2531b500-415d-11ea-9f4f-60a395a48666.png)

**Comment by UltimateGamer07** [comment]
I'll take this up.

**Comment by morevnaproject** [comment]
Great, it is yours now! ^__^

**Comment by morevnaproject** [comment]
/remind me about this in 5 days

**Comment by UltimateGamer07** [comment]
@morevnaproject This is my first time on a big project so im struggling a little bit. I was trying to understand the code structure by going through the code as well as read the docs, i was wondering if you could point out to me where the setting page's code is exactly

**Comment by ankit-kumar-dwivedi** [comment]
Hi @UltimateGamer07 the GUI related code lives in synfig-studio/src/gui/ and as you're looking for a dialog it's inside /dialogs subdirectory. 

> Currently, "Scale to fit canvas" is an option in preferences -
> ![screenshot_002](https://user-images.githubusercontent.com/332868/73193280-e4d23700-415c-11ea-960b-aa9cfd90e9fa.png)
> 
This file lives here -> https://github.com/synfig/synfig/blob/a4bbdd72e57be5b449874eab8a6b47425af8d4fb/synfig-studio/src/gui/dialogs/dialog_setup.cpp

You can always use **grep "whatever you want to search"** to find something like I used ;)

**Comment by rodolforg** [comment]
or... `git grep` ;)

**Comment by UltimateGamer07** [comment]
I know I should have already finished it but got caught up in some other stuff over the weekend. Will finish it in a day.

**Comment by UltimateGamer07** [comment]
The toggle is implemented in the settings dialog using a gtk switch that's defined in dialog_setup.h.
This header file is included in app.cpp as well but when trying to use that variable in app.cpp it says the variable isn't defined in the scope despite being the same declaration in the same header file.

**Comment by rodolforg** [comment]
@UltimateGamer07 did you check if you use proper namespace?

**Comment by UltimateGamer07** [comment]
yeah i even tried copy pasting the same exact lines

**Comment by rodolforg** [comment]
Well, I'll need to see the code to help you then

**Comment by UltimateGamer07** [comment]
Its fine im trying something different right now.

**Comment by AnishGG** [comment]
@UltimateGamer07 
It is better to upload the work done/code on your fork and paste links here for reference and better understanding of what you are trying to do. ^__^

**Comment by harshagrwl** [comment]
I will be taking up this issue

**Comment by harshagrwl** [comment]
@ankit-kumar-dwivedi I am getting these errors when trying to build the project locally. Please have a look. 
![Screenshot from 2020-03-01 19-56-47](https://user-images.githubusercontent.com/43218240/75627528-f47aea80-5bf6-11ea-8c52-78d715f45c0c.png)

**Comment by ankit-kumar-dwivedi** [comment]
This seems to be related to https://github.com/synfig/synfig/issues/744 and https://github.com/synfig/synfig/issues/945
@blackwarthog @morevnaproject any workaround for now??

**Comment by ankit-kumar-dwivedi** [comment]
@harshagrwl which distro/version are you using?

**Comment by harshagrwl** [comment]
> @harshagrwl which distro/version are you using?

I am using Ubuntu 18.04 LTS

**Comment by ankit-kumar-dwivedi** [comment]
And you are using using 2-build-debug.sh ? This seems to be a linking issue with libpng you linked against an older version but have a newer version in the runtime path of loadable libraries.

**Comment by morevnaproject** [comment]
Yes, it looks like you have two versions of libpng installed?

**Comment by harshagrwl** [comment]
@morevnaproject @ankit-kumar-dwivedi I tried uninstalling libpng and then ran 2-build-debug.sh again but it is giving the same error.

**Comment by ice0** [comment]
The `build_images` stage is not required, so you can continue by run `_debug/build/bin/synfigstudio`.
But to resolve this issue please show output of:
`apt search libpng`

**Comment by harshagrwl** [comment]
The `_debug/build/bin` directory does not include the `synfigstudio` file.
![Screenshot from 2020-03-02 16-21-02](https://user-images.githubusercontent.com/43218240/75670026-06659780-5ca2-11ea-8d17-034e4c2c722a.png)

The output of `apt search libpng` is:
![Screenshot from 2020-03-02 16-16-01](https://user-images.githubusercontent.com/43218240/75670080-21380c00-5ca2-11ea-81fb-fc506796b47d.png)

**Comment by ice0** [comment]
Ok, please show output of:
`pkg-config --cflags --libs libpng`

**Comment by harshagrwl** [comment]
Here's the output:
![Screenshot from 2020-03-02 16-54-30](https://user-images.githubusercontent.com/43218240/75672332-91e12780-5ca6-11ea-9f22-91532bcadfaf.png)

**Comment by ice0** [comment]
ok, now show output of:
`dpkg -S /usr/local/include/libpng12`

**Comment by harshagrwl** [comment]
> ok, now show output of:
> `dpkg -S /usr/local/include/libpng12`
![Screenshot from 2020-03-02 17-03-19](https://user-images.githubusercontent.com/43218240/75672896-bdb0dd00-5ca7-11ea-9bf9-ddef46679ca4.png)

**Comment by ice0** [comment]
Ok, looks like this is manually built library.
Show output of:
`pkg-config --list-all | grep png`

**Comment by harshagrwl** [comment]
> Ok, looks like this is manually built library.
> Show output of:
> `pkg-config --list-all | grep png`

![Screenshot from 2020-03-02 17-09-05](https://user-images.githubusercontent.com/43218240/75673262-8e4ea000-5ca8-11ea-801d-cc04daa5753b.png)

**Comment by ice0** [comment]
Please show output of this commands:
```
pkg-config --cflags --libs libpng16
pkg-config --cflags --libs libpng12
pkg-config --cflags --libs libpng
```

**Comment by harshagrwl** [comment]
> Please show output of this commands:
> 
> ```
> pkg-config --cflags --libs libpng16
> pkg-config --cflags --libs libpng12
> pkg-config --cflags --libs libpng
> ```
![Screenshot from 2020-03-02 17-52-43](https://user-images.githubusercontent.com/43218240/75676140-aaedd680-5cae-11ea-94d9-72f112529543.png)

**Comment by ice0** [comment]
Ok. Let's try to run synfig manually:
`synfig /home/harsh/Desktop/GSoC/synfig/synfig-studio/images/synfig_icon.sif -o test.png -t png`

It must fail as before.
Now change the libraries search path:
`export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH`
and try to run synfig again:
`synfig /home/harsh/Desktop/GSoC/synfig/synfig-studio/images/synfig_icon.sif -o test.png -t png`

**Comment by harshagrwl** [comment]
It worked fine. But I am still not able to execute synfig from the `_debug/build/bin/synfigstudio`
![Screenshot from 2020-03-02 18-55-08](https://user-images.githubusercontent.com/43218240/75680435-9e21b080-5cb7-11ea-9f7f-c85625486a55.png)

**Comment by ice0** [comment]
This is because you need to run `2-build-debug.sh` again and wait until it completed.

**Comment by harshagrwl** [comment]
@ice0 `2-build-debug.sh` still fails with the same error.

**Comment by ice0** [comment]
Edit `2-build-debug.sh`, and add:

`export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH` right after

```
export TYPE="_debug"
export DEBUG=1
```

so you must get:
```
export TYPE="_debug"
export DEBUG=1
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
```

and try to run it again.

**Comment by harshagrwl** [comment]
> Edit `2-build-debug.sh`, and add:
> 
> `export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH` right after
> 
> ```
> export TYPE="_debug"
> export DEBUG=1
> ```
> 
> so you must get:
> 
> ```
> export TYPE="_debug"
> export DEBUG=1
> export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
> ```
> 
> and try to run it again.

Getting similar error at a later point in running `2-build-debug.sh`
![Screenshot from 2020-03-03 01-22-33](https://user-images.githubusercontent.com/43218240/75712250-a98fce80-5ced-11ea-8b5c-b4f3d8d189e0.png)

**Comment by harshagrwl** [comment]
> > Edit `2-build-debug.sh`, and add:
> > `export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH` right after
> > ```
> > export TYPE="_debug"
> > export DEBUG=1
> > ```
> > 
> > 
> > so you must get:
> > ```
> > export TYPE="_debug"
> > export DEBUG=1
> > export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
> > ```
> > 
> > 
> > and try to run it again.
> 
> Getting similar error at a later point in running `2-build-debug.sh`
> ![Screenshot from 2020-03-03 01-22-33](https://user-images.githubusercontent.com/43218240/75712250-a98fce80-5ced-11ea-8b5c-b4f3d8d189e0.png)
@ankit-kumar-dwivedi @ice0

**Comment by ice0** [comment]
As a temporary solution can you uninstall libpng16?

**Comment by ice0** [comment]
Well, I reproduced your problem, I will write when I fix it.

**Comment by rodolforg** [comment]
Maybe I screw up something here? https://github.com/synfig/synfig/pull/1081/commits/1cd17f88803798ff9fef1aecffb23875a35b3c01

**Comment by harshagrwl** [comment]
> As a temporary solution can you uninstall libpng16?

@ice0 I tried uninstalling libpng16. In the process, some of its associated packages like libcairo2 were also removed.
Now the complete GUI of Ubuntu is gone. I am seeing this on startup:
![IMG_20200303_201058_1](https://user-images.githubusercontent.com/43218240/75786516-71d76400-5d8b-11ea-9723-6eb1a1e708ba.jpg)
Please Help

**Comment by rodolforg** [comment]
You still can login in "terminal mode".

Login and read the log of apt/aptitude (something like `tail /var/log/apt/????`) 

But check this out too: https://unix.stackexchange.com/questions/79050/can-i-rollback-an-apt-get-upgrade-if-something-goes-wrong

**Comment by ice0** [comment]
@harshagrwl Do you remember you deleted libpng-dev or libpng? How many packages have been removed?

**Comment by harshagrwl** [comment]
> @harshagrwl Do you remember you deleted libpng-dev or libpng? How many packages have been removed?

When I was trying to remove libpng16 and libpng16-dev I was getting an error saying that the package doesn't exist. I deleted libpng16-16. And the package libcairo2-dev was removed

**Comment by harshagrwl** [comment]
I even did apt-get --fix broken install and it completed without any errors but still this problem persists

**Comment by ice0** [comment]
ok. login to terminal shell and do this commands:
1.
```
cat /var/log/dpkg.log
```
you must get logged information about your packages.
```
cat /var/log/dpkg.log | grep remove
```
must show only removed packages
```
cat /var/log/dpkg.log | grep remove | grep 03-03
```
must show packages removed today (03-03). If you have another date format - use it.

if all is ok, then type next command:
```
cat /var/log/dpkg.log | grep remove | grep 03-03 | cut -d":" -f3 | cut -c 11-
```
this command must cut only package names.
After that save it to file:
```
cat /var/log/dpkg.log | grep remove | grep 03-03 | cut -d":" -f3 | cut -c 11- >removed.txt
```
and edit them. You need to remove word "packages remove" manually.
You can use nano for example:
```
nano removed.txt
```

After that run:
```
sudo apt-get install $(cat removed.txt)
```
This must install back all removed packages.

**Comment by harshagrwl** [comment]
> ok. login to terminal shell and do this commands:
> 1)
> 
> ```
> cat /var/log/dpkg.log
> ```
> 
> you must get logged information about your packages.
> 
> 
> ```
> cat /var/log/dpkg.log | grep remove
> ```
> 
> must show only removed packages
> 
> 
> ```
> cat /var/log/dpkg.log | grep remove | grep 03-03
> ```
> 
> must show packages removed today (03-03). If you have another date format - use it.
> 
> if all is ok, then type next command:
> 
> 
> ```
> cat /var/log/dpkg.log | grep remove | grep 03-03 | cut -d":" -f3 | cut -c 11-
> ```
> 
> this command must cut only package names.
> After that save it to file:
> 
> 
> ```
> cat /var/log/dpkg.log | grep remove | grep 03-03 | cut -d":" -f3 | cut -c 11- >removed.txt
> ```
> 
> and edit them. You need to remove word "packages remove" manually.
> You can use nano for example:
> 
> 
> ```
> nano removed.txt
> ```
> 
> 
> After that run:
> 
> ```
> sudo apt-get install $(cat removed.txt)
> ```
> 
> This must install back all removed packages.

It worked. Thanks a lot @ice0 !

**Comment by ice0** [comment]
> Maybe I screw up something here? 1cd17f8
@rodolforg No, as i can see ImageMagick includes both libpng1.2 and libpng1.6 headers if they installed. So i am looking how to fix that.

**Comment by ice0** [comment]
Temporary solution:

 `autobuild/build.sh` (line 275)

Add `--without-images` to the end of line, to get
```
--enable-warnings=max $DEBUG --without-images
```
so it doesn't build images.

**Comment by harshagrwl** [comment]
I was able to finally build it using the temporary solution.
As I was going through the GUI code, I found that adding a checkbox for the "Scale to fit canvas" option in the import image dialog would be better than adding the widget. 
What are your views on this @ice0 @ankit-kumar-dwivedi ?

**Comment by ice0** [comment]
I think @morevnaproject was thinking of a checkbox or something like it when he wrote "widget". So in my opinion it will be good enough.

**Comment by morevnaproject** [comment]
Yes, I was talking about checkbox widget. ^__^

**Comment by harshagrwl** [comment]
I am following the GNOME documentation for gtkmm (https://developer.gnome.org/gtkmm-tutorial/stable/sec-checkboxes.html.en). I was trying to apply a similar logic as described in the documentation to the app.cpp file (https://github.com/synfig/synfig/blob/a4bbdd72e57be5b449874eab8a6b47425af8d4fb/synfig-studio/src/gui/app.cpp) where the code for Import Dialog resides.
I was able to replicate the problem with the use of simple buttons but was facing compilation errors if i was trying to use checkbox. Since I am new to gtkmm, can you please guide me what dependencies to import and are there any other files where I need to make changes.

**Comment by ankit-kumar-dwivedi** [comment]
@harshagrwl I suggest you push your code on your branch. So we can help you better. 

And the find out the code for ![](https://user-images.githubusercontent.com/332868/73193280-e4d23700-415c-11ea-960b-aa9cfd90e9fa.png)

look here -> https://github.com/synfig/synfig/blob/b4b6a752214c5f56f51788b78f3b71fcfdec2492/synfig-studio/src/gui/dialogs/dialog_setup.cpp

you need to pass a checkbox to gtkfilechooser and create a new dialog. For existing code see https://github.com/synfig/synfig/blob/a4bbdd72e57be5b449874eab8a6b47425af8d4fb/synfig-studio/src/gui/app.cpp#L4031

**Comment by harshagrwl** [comment]
@ankit-kumar-dwivedi @ice0 I have pushed my code to the new branch (https://github.com/synfig/synfig/compare/master...harshagrwl:harsh_vectorization?expand=1). You can go through. This is the very first primitive version of changes that I made. I am still in the process of learning about gtkmm. Please help me out with this and point out what all changes should be done here.

**Comment by ankit-kumar-dwivedi** [comment]
@harshagrwl I could not understand your changes. Why have you added https://github.com/harshagrwl/synfig/blob/d8332c83d85c20e0934ae1c5ae9440a7e1d22980/synfig-studio/src/gui/app.cpp#L1413?

**Comment by harshagrwl** [comment]
Because the `toggle_resize_imported_images` function is being declared in the class inherited from the Dialog_Setup class

**Comment by ankit-kumar-dwivedi** [comment]
You can do that in the following way
```
void you_fun(bool value)
{
       //set this according to checkbox value
	App::resize_imported_images       = tvalue;
}
```
no need to do 
> [/harshagrwl/synfig/blob/d8332c83d85c20e0934ae1c5ae9440a7e1d22980/synfig-studio/src/gui/app.cpp#L1413](https://github.com/harshagrwl/synfig/blob/d8332c83d85c20e0934ae1c5ae9440a7e1d22980/synfig-studio/src/gui/app.cpp#L1413)?

also, see my last comment regarding gtkfilechooser there is a method **add_action_widget()** which you can use to add checkbox to filechooserdialog.

**Comment by ankit-kumar-dwivedi** [comment]
@harshagrwl any progress on this?

**Comment by harshagrwl** [comment]
> @harshagrwl any progress on this?

I am reading the documentation of GTK, but no substantial progress on the issue till now.

**Comment by ankit-kumar-dwivedi** [comment]
Okay. let us know if you are stuck

**Comment by rodolforg** [comment]
Maybe you can use `gtk_dialog_add_action_widget()`.

**Comment by ankit-kumar-dwivedi** [comment]
@harshagrwl any progress?

**Comment by FirasH** [comment]
I tried to fix this issue and here is the current result:
![mockup-1126](https://user-images.githubusercontent.com/6705690/85212953-6028c500-b358-11ea-9931-fd1c815d06a6.png)

Still, no idea how to connect signals to change the value of `App::resize_imported_images` when `Gtk::Switch` is toggled... Need to read some docs to understand how it works.
If anyone has an idea it would save a lot of time :grin:

**Comment by FirasH** [comment]
Now it's connected and appears to work consistently... Let me know if it's correct :+1:

**Comment by morevnaproject** [comment]
I tested and  it works perfectly!
