### ISSUE TITLE
PNG image linked to Skeleton layer does not respect specified rotation pivot

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1127]
**Synfig version & platform**:
Synfig 1.3.12, git revision: 922097

**Issue description**:
Bone rotation results in linked png image wrong rotation displacement.
To reproduce the issue I have prepared [bone_rotation_problem.zip](https://github.com/synfig/synfig/files/4119727/bone_rotation_problem.zip)

1) Open the attached file at: bone_rotation_problem > Animation > actor_V4_linked.sifz
As you can see here, this is the starting scenario:
![bone_before_rotation](https://user-images.githubusercontent.com/6705690/73221251-aa6a9900-4160-11ea-81f6-65d52794f70b.png)

2) Rotate the child bone with the blue handle (right arm of the drawn actor)

The rotation of the arm does not happen around the origin of the child bone neither on the origin of the imported image (they are almost coincident). The point is explicitly marked with a green "+" and should be our pivot point for the rotation.
![bone_after_rotation](https://user-images.githubusercontent.com/6705690/73221230-a0e13100-4160-11ea-813b-f63d73bc9017.png)

The expected result should be that the green "+" of the two png images (actor_busto and actor_braccio_dx) stay aligned for any rotation.

I have looked in the documentation but I cannot get it to work as how I understood it should work...

**Comment by morevnaproject** [comment]
I didn't looked at the file yet, but I strongly suspect that skeleton and linked object are in different groups with different transformations. So, they are in different coordinates.

**Comment by FirasH** [comment]
@morevnaproject in the forum I was told that I had to link the object to the bone only selecting the green handle. Doing that the rotation is correctly applied around the pivot point.

If you want close the issue, I'll probably add a note in the bone tutorial because I have seen a few users in the forum that happened to encounter this problem.
