### ISSUE TITLE
[CMake] Fix the build_images cmake target.

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1132]
Generate images same as autotools script does.
Depends on https://github.com/synfig/synfig/issues/1131, https://github.com/synfig/synfig/issues/1225

**Comment by ice0** [comment]
When you try to run:
`make build_images` you will face 3 problems:
1. `synfig` binary not found. 
CMake command depends on the assumption what binary can be found in your path environment. So if it is not already installed the target will fail. But we do not need it to be installed, because CMake allows to use another targets in `add_custom_command` function. Need to fix `synfig-studio/images/CMakeLists.txt`
2. Images placed in the wrong folder. They must be located in `share/pixmaps/synfigstudio/`.
You can see the correct location after running `./2-build-debug.sh` in the `_debug` folder.
3. `build_images` target always rebuilds images even if they already built. But it’s better to fix it in a separate issue/PR.

**Comment by AYESDIE** [comment]
So we plan to use `${SYNFIG_BUILD_ROOT}/bin/synfig` for the purpose of `build_images`? But we can only run that command on the assumption we have built `synfig`.

**Comment by ice0** [comment]
> So we plan to use `${SYNFIG_BUILD_ROOT}/bin/synfig` for the purpose of `build_images`? 

Yes and no. 
Yes - because this binary will be running to do the job. 
No - becase you do not need to write "/path/to/bin/synfig", CMake have a better solution. Please look here: https://cmake.org/cmake/help/v3.0/command/add_custom_command.html

> But we can only run that command on the assumption we have built `synfig`.

Yes. This is required dependency.

**Comment by AYESDIE** [comment]
@ice0 

> They must be located in `share/pixmaps/synfigstudio/`.
You can see the correct location after running `./2-build-debug.sh` in the `_debug` folder.

`sif_icon.png` and `synfig_icon.png` are build in `_debug/build/share/pixmaps`, so those 2 needs to be placed in `output/share/pixmaps` for CMake one too, right?

I'm almost ready with a PR for this one, except for the doubt I had.

**Comment by AYESDIE** [comment]
I don't think it needs to be there. It shows no error on logs when I run it by placing everything inside `output/share/pixmaps/synfigstudio` considering the changes made in #1230. Except for #1229, I think it's ready. I'll be making a PR.
