### ISSUE TITLE
Detect duplicated frames when importing image sequence

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1138]
Currently when doing "File" -> "Import sequence", Synfig imports every frame and creates a waypoint for each of them.

It would be nice to add an option to detect duplicated frames. So, instead of this -
![untitled-1](https://user-images.githubusercontent.com/332868/73590911-d4cea480-451a-11ea-9f77-2860c0ef60c5.png)
.. we get this (duplicated frames are not imported and no waypoints for them) -
![untitled-2](https://user-images.githubusercontent.com/332868/73590920-e2842a00-451a-11ea-9d6e-0093197f33ad.png)

For detecting duplicated frames we can use imagemagick - https://imagemagick.org/script/compare.php

**Comment by Aa20475** [comment]
Hey! I'd like to work on this! 😃  Can I proceed? @morevnaproject
