### ISSUE TITLE
Ghost dockers

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#1143]
**Synfig version & platform**:
Synfig studio 1.3.12 production build. archlinux 64x with openbox

**Issue description**:

Hello everyone, the problem occurs when I change my work area. Empty dockers seem to close them. however, when I change the work area, they reappear.

Sometimes, when I open the file again, the following warning appears.
![BUG-dockers](https://user-images.githubusercontent.com/45057390/73613097-2bda8500-45c0-11ea-9268-f7c324e00364.png)
I attach a video of the bug.
https://www.youtube.com/watch?v=sOAVPRr--IU

I hope the information is helpful. Thank you very much for the excellent work.

**Comment by ice0** [comment]
@Gilraiser Can you check if this PR fixes your problem?

**Comment by morevnaproject** [comment]
.Ghost dockers are not appear for me with PR #1190
