### ISSUE TITLE
Disable thumbnail preview on wayland session

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1144]
**Synfig version & platform**:
Building from source
Debian sid (Wayland GNOME)

**Issue description**:
![Screenshot from 2020-02-03 19-34-22](https://user-images.githubusercontent.com/24214509/73662040-244ed500-46c1-11ea-86c0-13494c3ef962.png)

When preview thumbnail is displayed synfig window goes out of focus. I cannot use **Ctrl+.** or **Ctrl+,** to move the time cursor. I'd love if synfig provides a togglable option for thumbnail preview in its *Preferences*

I like to use either the main canvas workspace or preview dialog to view my draft animation. I rarely rely on thumbnail since they are too small for some of my lip-sync animation and particle effect animation.

UPDATE: This issue is noticeable if synfig runs under Wayland (GNOME)
On X11 thumbnail doesn't block keyboard input :)

**Comment by Keyikedalube** [comment]
Plus, the thumbnail placement is not consistent for X11 and Wayland.

# On X11
![Screenshot_2020-05-05_11-05-31](https://user-images.githubusercontent.com/24214509/81037660-33f8d800-8ec1-11ea-8f78-c7ba435b7577.png)

# On Wayland
![Screenshot from 2020-05-05 10-48-38](https://user-images.githubusercontent.com/24214509/81037679-4246f400-8ec1-11ea-87e8-7ccf5a6497ce.png)

**Comment by rodolforg** [comment]
Here is the thumbnail code, if trying to fix the incorrect positioning on wayland:
https://github.com/synfig/synfig/blob/9ad7d22d857c42b49bde109af298c77d661a68b4/synfig-studio/src/gui/widgets/widget_canvastimeslider.cpp#L98

**Comment by Keyikedalube** [comment]
I'm working on this issue. You can assign it to me :)

**Comment by Keyikedalube** [comment]
I'm placing the togglable option in **Editing** section since it has more space for content
![Screenshot from 2020-05-15 21-38-18](https://user-images.githubusercontent.com/24214509/82072202-ef591200-96f4-11ea-8cf2-28fde689cd87.png)

Is setting a tooltip really a must? I can see almost all switches have tooltip set.
But I'm thinking the label is already self-explanatory itself

**Comment by morevnaproject** [comment]
> Is setting a tooltip really a must? I can see almost all switches have tooltip set.
But I'm thinking the label is already self-explanatory itself

The tooltip can be:
"Do not display thumbnail preview when hovering cursor on timeline."

**Comment by Keyikedalube** [comment]
Disabling thumbnail preview will also benefit sway users.

Encountered this nasty issue today...
[recording.mp4.zip](https://github.com/synfig/synfig/files/4666077/recording.mp4.zip)
