### ISSUE TITLE
Add extra time track space at start and end

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1145]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
It's tedious to position my mouse at the starting keyframe (and ending keyframe too) to bring up the right-click context menu or drag it while animating.
![Screenshot from 2020-02-03 20-15-16](https://user-images.githubusercontent.com/24214509/73705337-a9ff6e80-471b-11ea-820c-74fa83062dfa.png)
It would be nice if more empty space is added for these two so that keyframes and waypoints icon appear fully visible and not half.

**Comment by morevnaproject** [comment]
Great idea

**Comment by Keyikedalube** [comment]
Does the second timeline code on_draw() mean **Update (re-draw) the time line**?
https://github.com/synfig/synfig/blob/478b0db1fb5dac27a64b36eaff120b60cc92f49c/synfig-studio/src/gui/widgets/widget_timeslider.cpp#L232-L240
https://github.com/synfig/synfig/blob/478b0db1fb5dac27a64b36eaff120b60cc92f49c/synfig-studio/src/gui/widgets/widget_timeslider.cpp#L299-L305
Both saying *//Draw the timeline* is quite misleading because the first one actually drew the timeline while the latter does the updating part.

Want me to update the comment to "Re-draw the timeline"? Or keep it as it is.

**Comment by Keyikedalube** [comment]
### Start time 00:00:00.00
Figured how to push the first keyframe using canvas manipulation and successfully did it!

![Screenshot from 2020-03-05 17-25-09](https://user-images.githubusercontent.com/24214509/75979352-4d53c700-5f06-11ea-90b5-920c551acb3c.png)

### End time 00:00:05.00
Since the actual drawing has been set to 16px from x (by default 0) the last keyframe gets drawn behind the vertical scrollbar

![Screenshot from 2020-03-05 17-28-24](https://user-images.githubusercontent.com/24214509/75979565-c5ba8800-5f06-11ea-972d-f8bf4d424b89.png)

- I've tried increasing both the keyframe & canvas width
Doesn't help :(
- Tried set_margin_end() property
Works but doesn't solve keyframe and waypoints showing half

I'm suspecting its the time range value; lower & upper bound, that determines how much is displayed on the dock time track widget.

Manipulating the upper bound time value (though this trick kind of works) is tedious because I can't figure out how to keep the space consistent with the first keyframe.

*Pointers. Advice. Solution... greatly appreciated*

**Comment by ice0** [comment]
@rodolforg can you comment here?

**Comment by Keyikedalube** [comment]
New update!

Minimizing the delta time pixel count per second gives enough extra space for end time
So now we have consistent 16px start space and 16px end space
Here's a screenshot of how the time track looks now

![Screenshot from 2020-03-06 20-23-23](https://user-images.githubusercontent.com/24214509/76134526-f56faa00-6044-11ea-975e-38352117af79.png)

Visual work is done!

The only task left to do is aligning mouse click event correctly for keyframes and waypoints

**Comment by morevnaproject** [comment]
I have made experiment - edited canvas properties and added 5 frames at the start and 5 frames at the end. This makes timetrack to be drawn like this:
![screenshot_004](https://user-images.githubusercontent.com/332868/77082583-dbfc3400-6a2e-11ea-9b5c-72b84fc72b57.png)

So, here is an idea to alternative solution: maybe just pass different frame range to Timetrack (and other Panels)? I.e. add 5 frames at the start and at the end and ask Timetrack to display this range.

**Comment by Keyikedalube** [comment]
I don't understand...
> added 5 frames at the start

and I see -5 but your time slider screenshot shows timeline cursor still at 0

While on mine start time -5f gives this output
![Screenshot from 2020-03-20 07-38-05](https://user-images.githubusercontent.com/24214509/77130474-1f31c380-6a7e-11ea-8e4f-df58fb9692c3.png)

And adding 5f at the start actually pushes the timeline cursor to 5f
![Screenshot from 2020-03-20 07-48-04](https://user-images.githubusercontent.com/24214509/77130751-2dccaa80-6a7f-11ea-9495-cecc39c5a6e7.png)

**Comment by Keyikedalube** [comment]
> So, here is an idea to alternative solution: maybe just pass different frame range to Timetrack (and other Panels)? I.e. add 5 frames at the start and at the end and ask Timetrack to display this range.

Yes that works too

but...

Initially, when I first figured how to push the starting keyframe 16px forward, I had no idea how to add extra space at the end keyframe.
At one time I did try using time manipulation without actually changing the end time recorded on the canvas properties dialog.
Then I realized adding extra 1s is too much

That's when I used frames... :)
Here are the problems with frame manipulation
- I normally use 30fps on all my animation files so changing one of my animation files to 60fps gave this
![60f](https://user-images.githubusercontent.com/24214509/77131836-36bf7b00-6a83-11ea-9823-24bf45859f36.png)
- Then I tried changing the end time from 5s to 10s 
![10s](https://user-images.githubusercontent.com/24214509/77131970-b9483a80-6a83-11ea-8042-06734954f8b8.png)
- And down to 3s
![3s](https://user-images.githubusercontent.com/24214509/77131995-d1b85500-6a83-11ea-9009-36443e31e38c.png)

The extra space at start and end became inconsistent

Now if you use frame manipulation for both start and end you'll get the same padding space
At the cost of losing fixed pixel consistency

So if a user has 5s animation clip, her time slider might be 16px padded at start and end
Then she changes her duration to 10s, now her time slider might be 32 px padded
And so on

That's why I used canvas manipulation at the end:
1. It's easy
2. Guaranteed consistency irrespective of time and frame values
3. Yes, it [breaks](https://github.com/synfig/synfig/pull/1200#discussion_r389965728) synfig

Overall, I'm not against this alternative frame solution
Maybe there is a way to have a reference fixed padding value so that using frames to add extra space can give the same effect as canvas does - fixed consistency

I think I should close the PR linked here. What do you say?

**Comment by rodolforg** [comment]
I think all padding should be exclusively done in TimePlotData class.
Maybe only current TimeTrack will need to be adapted, because it is a
TreeView.

My PR for the new TimeTrack, however, uses TimePlotData too and it would
work fine.

**Comment by morevnaproject** [comment]
@Keyikedalube Thank you for clarification. Yes, the solution with adding frames looks hackish. Besides the issues you explained, there will be different padding depending on zoom of timeline.

As @rodolforg says, the situation can be completely different after new TimeTrack panel will be merged. I suggest to wait for the merge and make a second attempt.

Yes, linked PR is ok to close, but please keep the branch - it might help for second attempt.

**Comment by Keyikedalube** [comment]
> Besides the issues you explained, there will be different padding depending on zoom of timeline.

True

> Yes, linked PR is ok to close, but please keep the branch

I'll keep the branch so someone who wants to attempt this issue can reference how the first solution was approached

**First PR:** #1200

Sad news though I might not be able to continue with this issue
I have other priorities on my shoulder

I wish the best of luck to whoever picks this issue && thanks in advance for the fix too! :1st_place_medal:

**Comment by rodolforg** [comment]
GIMP solved this by using wide handles of Gtk::Paned…
