### ISSUE TITLE
Renaming a set can break other sets' name

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#1146]
**Synfig version & platform**:
1.3.11

**Issue description**:
When renaming a set, if there are other sets that start with the renamed set's former name, text-replacement occurs ; example :
- create set A
- create set AB, AC...
- rename A to D
- AB, AC... are now renamed DB, DC...

**Comment by rodolforg** [comment]
Here is what is causing this problem:
https://github.com/synfig/synfig/blob/6c234ce5d078f6cd44be71da6c68f0a5e7ffd5cd/synfig-core/src/synfig/canvas.cpp#L1606-L1631

Specifically here:
`		for(++iter;iter!=group_db_.end() && iter->first.find(old_name)==0;iter=group_db_.find(old_name),++iter)
`
I don't know why it searches for more groups beyond the first one found, as `group_db` is a `std::map`, so it is impossible to have more than one entry with same key (group name).
In this iteration, it doesn't search for the (old) group name, but for any group that begins with same name (`iter->first.find(old_name)==0`).

Maybe for imported canvas?

**Comment by rodolforg** [comment]
Ok. It's due to nested sets.
https://wiki.synfig.org/Sets_Panel#Sets_can_be_nested
I'll fix it.
