### ISSUE TITLE
[Lottie exporter] Exported animation does not work with react native

### ISSUE THREAD

**Issue by jackburridge** [synfig/synfig#1147]
**Synfig version & platform**:
Version: 1.3.12
Platform: OS X
**Issue description**:
Lottie export does not display when used with react native. 
This is my animation
https://gist.github.com/jackburridge/1b1c219cadc2dc13566b717960f53202

**Comment by AnishGG** [comment]
Hello @jackburridge 
Currently I am out of station and travelling. Will be able to review this after 10th.

**Comment by AnishGG** [comment]
I tested this file on a simple web browser and it works fine.
I have no experience with react native and hence might not be able to help you here :( .
Perhaps [lottie's react native](https://github.com/react-native-community/lottie-react-native) developers might be able to help you here?

Or does anyone else here has experience with react native? @morevnaproject

**Comment by jackburridge** [comment]
Hi @AnishGG 
I don't really understand the Lottie file format, but it appears to be something to do with the colour, I should be able to attach a quick demo some time tomorrow.

**Comment by jackburridge** [comment]
Sorry for the delay @AnishGG 
I've managed to do a few minimal examples, a simple circle animation:
[circle.zip](https://github.com/synfig/synfig/files/4230549/circle.zip)
The color is wrong.
![circle](https://user-images.githubusercontent.com/7405892/74931635-f1525400-53d7-11ea-969b-6b01a3f4c4c6.gif)
I have another where the color is animated:
[circle_color.zip](https://github.com/synfig/synfig/files/4230556/circle_color.zip)
Again the color is wrong, so I'm assuming the same issue
![circle_color](https://user-images.githubusercontent.com/7405892/74931738-2bbbf100-53d8-11ea-8ef1-2b0353b29e01.gif)
And on a hunch I tried grouping the circle in an animation, this did not displacy at all.
[circle_group.zip](https://github.com/synfig/synfig/files/4230572/circle_group.zip)

**Comment by AnishGG** [comment]
Have my semester exams going on. Will look at this in some time 🙂

**Comment by AnishGG** [comment]
@jackburridge, This is happening because of introduction of a new feature in Synfig that is variable `gamma correction`. I have created an issue regarding this: https://github.com/synfig/synfig/issues/1174
There should be a fix soon.

**Comment by AnishGG** [comment]
@jackburridge This issue should be closed by #1179 
Can you confirm this.

**Comment by AnishGG** [comment]
Closing this now. ^__^
