### ISSUE TITLE
App::restore_default_settings() doesn't resets all settings

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1154]
Some settings are not restored to default values when user clicks "Restore Defaults" button in "Preferences dialog.

![screenshot_001](https://user-images.githubusercontent.com/332868/74144514-75b21380-4c2f-11ea-9dc1-e963633a0c3a.png)

For example, "Dark UI theme" option is not restored.

So, we need to review contents of `App::restore_default_settings()` function and compare it with keys listed in `Preferences` class:

https://github.com/synfig/synfig/blob/2d453f288a651a1142d46f2f45d13850db428e5e/synfig-studio/src/gui/app.cpp#L862-L896

**Comment by sourabhdharpure** [comment]
I would like to work on this isssue

**Comment by ice0** [comment]
No problem, now it's yours :)

**Comment by sourabhdharpure** [comment]
@morevnaproject How to find the default values for
1) time_format
2) file_history.size
3) use_dark_theme
4) show_file_toolbar
5) brushes_path
I am not able to find them, please help me regarding the same

**Comment by morevnaproject** [comment]
@sourabhdharpure All those values are defined in `synfig-studio/src/gui/app.cpp`

**Comment by morevnaproject** [comment]
@sourabhdharpure Hi! Are there any progress with this issue?

**Comment by morevnaproject** [comment]
/remind me about this in 2 days

**Comment by FirasH** [comment]
I can work on this one

**Comment by ankit-kumar-dwivedi** [comment]
Well it's been a month and due to no response, I am removing @sourabhdharpure from this one.

@FirasH please go ahead this is yours now :)

**Comment by FirasH** [comment]
I have looked at the code and noticed that the function:
App::restore_default_settings()
is used basically to set the values to assign, but that does not always mean that the setting is getting applied.

In fact the Preferences dialog once "Restore Defaults" is clicked, the values are changed but it is like "Apply" is not clicked (Dialog_Setup::on_apply_pressed()) while the dialog is hidden.

I think that after pressing "Restore Defaults" the dialog should not be hidden automatically. What do you think?

**Comment by FirasH** [comment]
I have added the missing parts required to reset all the settings.

With the commit over reported now the preferences dialog is not closed as "Restore Defaults" is clicked.

For this reason I had to apply minor changes to:
Dialog_Setup::refresh()
in order to refresh all the values.

The only problem (which was also present before) is that the Gdk::RGBA "colored" buttons, used to select the background and preview colors, are not updated as:
App::restore_default_settings()
is invoked, but only after restarting Synfig Studio.

If someone has an idea on how to update it that would be very helpful!
I'll probably take a look at it tomorrow or in the next days.
Thank you!

**Comment by ice0** [comment]
> I think that after pressing "Restore Defaults" the dialog should not be hidden automatically. What do you think?

I agree.

> The only problem (which was also present before) is that the Gdk::RGBA "colored" buttons, used to select the background and preview colors, are not updated as:
App::restore_default_settings()
is invoked, but only after restarting Synfig Studio.

I think they re-read the values only after a restart. So you can find the code that does this and call it when you click Apply.

**Comment by FirasH** [comment]
I pushed a new commit which updates correctly the buttons.
Now everything is supposed to be restored on click.

**Comment by FirasH** [comment]
The theme was not updated, now it does with the last commit.
At this point I think the merge request is ready.
