### ISSUE TITLE
Unable to run Synfig 1.3.12 on Os X 10.11

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1156]
User reported that he cannot run Synfig on Mac Os X El Capitan 10.11.6

**Comment by morevnaproject** [comment]
Screenshot of error -
![70A0Dfm-OW8](https://user-images.githubusercontent.com/332868/74154324-0b0bd280-4c45-11ea-94da-e7d9201fdb4f.jpg)

(source - https://vk.com/synfig?w=wall-34459196_1269_r1270)

**Comment by morevnaproject** [comment]
Can anyone check version 1.3.12 on OSX 10.11? @ankit-kumar-dwivedi ?

**Comment by ankit-kumar-dwivedi** [comment]
Sure on my home will let you know soon

**Comment by ankit-kumar-dwivedi** [comment]
PS- just saw this again and realized I have updated my mac to Catalina 10.15

**Comment by ice0** [comment]
Checked it now.
The same error occurred on 10.11 only once, when I clicked the Synfig icon again and again, like crazy at the first start. After that I can’t reproduce it. Synfig is working fine.

**Comment by ankit-kumar-dwivedi** [comment]
I was not able to make it work on my mac.
![Screenshot 2020-02-10 at 9 56 14 PM](https://user-images.githubusercontent.com/37617951/74168818-4eb80980-4c50-11ea-9f18-46bab0389879.png)

**Comment by ankit-kumar-dwivedi** [comment]
Okay it works after allowing from system preferences :)

**Comment by ice0** [comment]
You can just Ctrl+click on a file and choose "Open" from dropdown menu :)

**Comment by morevnaproject** [comment]
Thanks to everyone for checking! ^__^
