### ISSUE TITLE
Some strings are not translatable in the .po files

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1158]
There are some strings that cannot be translated because they are missing in the .po translation files.

In this Issue I will report the strings that need to be reviewed in the code:
- The dialog at: File > Preview...
- The dialog at: Canvas > Options...
- The dialog at: Layer > Convert to Vector (when a raster image is selected)
- The dialog at: Window > Workspace > Edit workspaces...
- From File > Preferences... > Editing, open the dialog "Choose..." to select the external Image Editor (#1159, fixed)
- The tooltip at: File > Preferences... > Editing, hover the mouse pointer above "Choose..." button (#1159, fixed)

If I find new strings I'll report them here.
I took a look at the code and from what I understood we need to add an underscore "_" to make the string available in the .po files, is that correct?

**Comment by ice0** [comment]
> we need to add an underscore "_" to make the string available in the .po files, is that correct?
Exactly!

**Comment by rodolforg** [comment]
Those dialogs use .ui files, so they need to be include in .pot file
generation

**Comment by FirasH** [comment]
Created another merge request #1162 which includes other ones.

**Comment by rodolforg** [comment]
> Those dialogs use .ui files, so they need to be include in .pot file generation

Fixed by https://github.com/synfig/synfig/commit/a98351568cfe8bd1403b4dfcf6d817f680b05ae9 .
Now it's time to push POT file to transifex @morevnaproject  :)

**Comment by FirasH** [comment]
@morevnaproject if you are going to push an updated POT file to transifex I can update #1162 and remove the problematic strings so that we have some other issues solved in the meantime that the strings included in REGISTER_VALUENODE are fixed.
