### ISSUE TITLE
Some PNG files not displaying correctly

### ISSUE THREAD

**Issue by 1noober** [synfig/synfig#1160]
**Synfig version & platform**:  Synfig 1.3.12 Windows 7 x64
(we're more likely to help if you're using latest development builds)

**Issue description**:
Some PNG files not displaying correctly. Some parts of this file display correctly (yellow section) and some parts do not (dark section).
![SRTest](https://user-images.githubusercontent.com/60995306/74396861-1affef80-4dc8-11ea-8bc9-9a42b98952d6.png)

**Comment by ice0** [comment]
Same problem on Ubuntu and Manjaro.

**Comment by morevnaproject** [comment]
Is this an indexed PNG?

**Comment by ice0** [comment]
This is PNG info:
```
width=448
height=731
bitDepth=16
Comment=Created with GIMP
```

**Comment by ice0** [comment]
By the way, this image is opened without any problems using the sample program from libpng, so I think that Synfig somehow corrupts the image data.

**Comment by morevnaproject** [comment]
> bitDepth=16

Does converting to 8-bit color solves the issue?

**Comment by 1noober** [comment]
No.

**Comment by morevnaproject** [comment]
>>> bitDepth=16
>>
>> Does converting to 8-bit color solves the issue?
>
> No.

I have opened image in Krita and converted it into 8-bit PNG. After that it loads correctly in Synfig.
Here is a converted 8-bit file -  [8bit.png](https://user-images.githubusercontent.com/332868/80114048-4283ed00-85ad-11ea-8643-f391d906b3e4.png)

![screenshot_001](https://user-images.githubusercontent.com/332868/80114099-57608080-85ad-11ea-8034-4e0d1fcc2ccd.png)
