### ISSUE TITLE
2-build-cmake.sh Mlt.h include error

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1164]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
*Currently on Debian, build-cmake fails with old libmng not having pkg-config tool https://github.com/synfig/synfig/issues/928#issuecomment-554159232*
*So what I did was comment out the **pkg_check_modules** for libmng and proceeded with building*
 
Here's the build error I get about not finding Mlt.h
![Screenshot from 2020-02-19 10-52-14](https://user-images.githubusercontent.com/24214509/74804752-25aa0f80-5307-11ea-8419-66883ed4da4a.png)

**Comment by ice0** [comment]
Must be fixed in #1167 
Can you check it please?

**Comment by Keyikedalube** [comment]
Yup, it's fixed :)
Build success

**Comment by ice0** [comment]
Thank you!
