### ISSUE TITLE
[Lottie exporter] Add support for variable gamma correction

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#1174]
**Synfig version & platform**:
https://github.com/synfig/synfig/commit/cf1df92b252699989e3c36ce4406259a1e40ddd3

**Issue description**:
Old version of Lottie export is using a default value of `2.2` for gamma correction. This needs to made variable depening upon gamma correction value used in the canvas.

**Comment by saurabh-ramola** [comment]
@AnishGG can I take this up?

**Comment by AnishGG** [comment]
Sure, assigning this to you!

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
