### ISSUE TITLE
Suggestion for new synfig UI

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1175]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I love Synfig, i find it amazing and very useful, with many abilities and potentials . <br>But i think Synfig needs a new and modern UI.<br>Thanks for your efforts.</p>&mdash; Maisam Hosaini (@maisam_hosaini) <a href="https://twitter.com/maisam_hosaini/status/1210892500682117121?ref_src=twsrc%5Etfw">December 28, 2019</a></blockquote>

Below attached zip is my rough basic idea for new synfig user interface design:

[Concept from Builder.zip](https://github.com/synfig/synfig/files/4241431/Concept.from.Builder.zip)

Header bar implementation is the main focus since it makes the GTK app look modern and saves more space for content. Moreover, Cinnamon, KDE, and XFCE are already on board with GTK3 so header bar will appear consistent on all major desktop environments.
Below is a screenshot of gedit (with header bar) on KDE Neon:
![Screenshot_20200223_184021](https://user-images.githubusercontent.com/24214509/75114358-524d8680-567b-11ea-8dd4-a76be5750e4d.png)

The only drawback would be deprecating traditional menu bar, reorganizing preferences, headache from implementers ;P and other documentation related stuff (because new UI equals new guides, tutorials, instructions,...)

**Comment by rodolforg** [comment]
Accidentally closed by a mistaken commit message.

**Comment by Keyikedalube** [comment]
Uh... I think this issue should be closed. You guys have discourse forum.

Discussions could be done there. I bet there are users there that would be interested in providing their opinions :)

BTW, my suggested rough concept idea is too difficult-ish to me LOL. I suspect that concept would be possible in Synfig 2.0 or later. Anyway, I wanted the header bar to contain render options and buttons instead of presenting dialogs to users for all actions. And maybe use header bar as progress bar when render begins IDK if that's possible though but if that was possible we have an animation program that's more simple and user friendly ;)

Closing this issue tomorrow... Let me know if you feel otherwise and I'll leave it open.

**Comment by ice0** [comment]
I suggest to leave it open. I want back to this issue, when we done with CSS and other stuff.

Another drawback for me can be common UI style for Windows/MacOS. 
Also header bars looks good for simple applications like video players or book readers/calendars but I am not sure about complex apps.

**Comment by Keyikedalube** [comment]
> but I am not sure about complex apps.

The screencast linked in the description above is GNOME Builder app. That's... complex app

**Comment by ice0** [comment]
Yeah, and the previous version looks better to me :)

**Comment by Keyikedalube** [comment]
After musing a bit about this I feel the current UI is already good enough.
Also, found out single window mode was one of the big UI improvement made in [v1.0](https://www.synfig.org/1.0/overview/).

I understand there would definitely be backlash from users not familiar with GTK header bar feature. And most importantly some user wants native UI features over GTK ones. This issue's suggestion is completely headed in the opposite direction because every UI elements would comply most favorably to GNOME users disregarding other platforms.

Instead there are many pending improvements left to do; dark theme, native open/save dialog, etc Effort spent on those issues are worthwile and rewarding and manageable :)

However, if anyone wants to go bold and head the other way ie., innovate with cool modern GTK features, forking Synfig repo is a great way to do that.
