### ISSUE TITLE
Waypoint Editor should show TCB options only if it is a TCB point

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#1178]
Currently when you open a Waypoint editor dialog*, it always shows the TCB parameter values/controls even when it uses an interpolation method other than TCB.

This dialog should only show Tension, Continuity, Bias and Temporal Tension only if its input or output interpolation is TCB.

* You can view this dialog by double clicking a waypoint in timetrack or via its context menu.

**Comment by rodolforg** [comment]
@Keyikedalube would you give it a try?

**Comment by Keyikedalube** [comment]
Here's how I understand, remove/disable TCB parameters in waypoint dialog for all other types of waypoints except for waypoints that look like below (2nd waypoint and 3rd keyframe)
![Screenshot from 2020-02-26 07-34-43](https://user-images.githubusercontent.com/24214509/75305005-d7e35900-586a-11ea-8f5e-ed33847ae733.png)
I don't animate professionally, only simple cut-out animation where I know what the starting frame and ending frame should be not what they waypoint type is. That means if I understood this issue wrong... probably not for me.

**Comment by rodolforg** [comment]
I'm talking about this dialog:
![Captura de tela de 2020-02-25 23-26-36](https://user-images.githubusercontent.com/1323987/75306025-97fa8280-5826-11ea-9f26-cf68dd35bbd9.png)
In this case, both interpolations (in and out) are set to `Clamped`. None is `TCB`. Therefore, why does the dialog show the section inside the green rect outline?

You can open this dialog double-clicking on one of the waypoints shown in your picture.

**Comment by Keyikedalube** [comment]
Got you. I think I can fix this. I'm taking on this issue.

**Comment by rodolforg** [comment]
This issue is fixed in v1.4.1.
