### ISSUE TITLE
[Vectorization] Enhance BezierToOutline function

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#1184]
**Issue description**:
Lot of redundant work is done inside the function BezierToOutline
https://github.com/synfig/synfig/blob/6b433d2503ed81bd6577c17748d2ae59ce0573c6/synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp#L87-L154

this can be rewritten in a better way that can reduce LOC.

**Comment by ARYA-BHARDWAJ** [comment]
Hi I want to work on this issue

**Comment by ice0** [comment]
@ARYA-BHARDWAJ it's yours now :)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject can you approve linked PR? thanks
