### ISSUE TITLE
Allow to choose render engine from console

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1187]
Allow to choose render engine from console, in the same way as we choose render engine in GUI -
![screenshot_006](https://user-images.githubusercontent.com/332868/75607531-a8fb0a80-5b2a-11ea-87d9-c68d58767803.png)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi I remember you have successfully added Preview rendering mode to workarea. Can you please take a look at this issue too? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
will surely look into it.
PS: I guess this is not urgent as I have exams this week. Will update on this by next week
/remind me about this in 5 days

**Comment by morevnaproject** [comment]
Yeah, it's not urgent. Thank you! ^__^

**Comment by Baytars** [comment]
How many render engines that Synfig supports are there?

**Comment by ice0** [comment]
@Baytars 

```
  safe - Cobra (safe) - very slow
  software - Cobra (software)
  software-draft - Cobra Draft (software)
  software-low16 - Cobra LowRes (software) x16
  software-low2 - Cobra LowRes (software) x2
  software-low4 - Cobra LowRes (software) x4
  software-low8 - Cobra LowRes (software) x8
  software-preview - Cobra Preview (software)
```

**Comment by Baytars** [comment]
@ice0 Thank you! The 2D render engine seems a bit different from 3D render engine. lol

**Comment by ankit-kumar-dwivedi** [comment]
@ice0 where can I get list of all commands for synfig commandline?

**Comment by ice0** [comment]
@ankit-kumar-dwivedi they are here: https://github.com/synfig/synfig/blob/6d8904e6c38161574c5c77e40745edc09be9a400/synfig-core/src/tool/optionsprocessor.cpp#L154-L160

**Comment by veermetri05** [comment]
Hey @ice0, if no one is working on this, I would like to work on this issue, I am completely noob at Synfig development, please let me know which files should I look into and give me a basic context for where should I make the changes.

**Comment by ice0** [comment]
@veermetri05 
Hi! You can split this issue on two tasks:
1) add comman-line option handling (please check `optionsprocessor.cpp`)
2) add the ability to switch renderer. I haven't dug in this direction, but you can start with `Task::RunParams::RunParams(const Renderer::Handle &renderer)` and check how it is called.

**Comment by veermetri05** [comment]
Thank you for the guidance. I will carefully look at them and reach out if I have any difficulty understanding them.

**Comment by veermetri05** [comment]
So before I implement this, I would like to describe how I am going to solve it.
As suggested by @ice0,
First step would be to add command-line option handling in optionprocessor.cpp
To do that first need to declare a new field called `set_renderer`, add a option called `renderer`. 

Like:
`add_option(og_set, "renderer", ' ', set_renderer, _("Specify which renderer to use"), "string");`

So I would add it before
https://github.com/synfig/synfig/blob/be84b8e8e27aa0c75a611148b003ba0eddf5bc61/synfig-core/src/tool/optionsprocessor.cpp#L155
This will allow to accept `renderer` option from command line.

And then check whether the supplied value for `renderer` is correct, need to check the value of `set_renderer` with available renderers.
I will do it same as in:
https://github.com/synfig/synfig/blob/be84b8e8e27aa0c75a611148b003ba0eddf5bc61/synfig-studio/src/player/main.cpp#L145-L152
_( I guess I need to copy paste the required code from above)_

> 2\. but you can start with `Task::RunParams::RunParams(const Renderer::Handle &renderer)` and check how it is called.

Unfortunately, it seems like we don't need to deal with anything related to it.
Next step would be, then need to add new field to struct `Job` called `render_engine`, then within [joblistprocessor.cpp](https://github.com/synfig/synfig/blob/be84b8e8e27aa0c75a611148b003ba0eddf5bc61/synfig-core/src/tool/joblistprocessor.cpp), set the render engine by casting the target. as done in
https://github.com/synfig/synfig/blob/be84b8e8e27aa0c75a611148b003ba0eddf5bc61/synfig-core/src/tool/joblistprocessor.cpp#L218

Will add `Target_Scanline::Handle::cast_dynamic(job.target)->set_engine(job.render_engine);`

P.S.: I did all these and it works, (haven't committed the code yet) but the thing I am concered about is that to check the render engine parameter from available render engines. I need to copy paste that code, and wondering if there is a better way to do it.
I am still learning C++, so please guide me wherever required.

**Comment by ice0** [comment]
> And then check whether the supplied value for renderer is correct, need to check the value of set_renderer with available renderers.
I will do it same as in:
...
( I guess I need to copy paste the required code from above)

It's best not to copy/paste code if possible. Better extract the piece of code into a method and use it in both places.

Also you should notice one important UX thing. How should the user know what renderers are available?
I think we need to add one more command line option, something like `--renderers` similar to the options we already have:
```
--modules                       Print out the list of loaded modules
--targets                       Print out the list of available targets
```
After that, you should notice that this code is already written and needs to be extracted too:
https://github.com/synfig/synfig/blob/be84b8e8e27aa0c75a611148b003ba0eddf5bc61/synfig-studio/src/player/main.cpp#L65-L70

> I am concered about is that to check the render engine parameter from available render engines.

Can you explain this part in more detail?

**Comment by veermetri05** [comment]
> Can you explain this part in more detail?

I meant the copy pasting of code (which I shouldn't do), to check the accepted render engine. 

> I think we need to add one more command line option, something like `--renderers` similar to the options we already have:

Sure, I will take a look this.


> Better extract the piece of code into a method and use it in both places.

I will try to do it. 
Will create a new method to check renderer, which will accept a String value (i.e. name of render engine), check if a render engine exists with that name, and returns boolean. Let's call this method `check_engine` ? So should I add this method to Renderer class at [renderer.h](https://github.com/synfig/synfig/blob/be84b8e8e27aa0c75a611148b003ba0eddf5bc61/synfig-core/src/synfig/rendering/renderer.h)
Should I also extract `print_renderers` method to this class ?
