### ISSUE TITLE
Conflicting mnemonic initials on Waypoint Editor

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1189]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
I don't use mnemonic keys a lot but I noticed this dialog has the same mnemonic initials when I press Alt key
![Screenshot from 2020-03-01 06-36-08](https://user-images.githubusercontent.com/24214509/75617820-48031f00-5b8a-11ea-9f9a-9af21b753e2f.png)

The only time I'd use mnemonic is for buttons such as OK and Cancel which usually are standard O and C for all types of desktop applications
I tried to cancel my edit on the above dialog and it refused to close. Looking closely I found out there are two Cs and Continuity got the focus.

**Comment by Keyikedalube** [comment]
Here's my suggestion:
- Modify Continuity mnemonic from **C** to **y**
That way Close button gets the default focus
- Modify Out interpolation from **O** to **u**
and OK button gets the default focus

Thus making it easier and accessible for keyboard lovers to easily confirm or cancel any changes made on the Waypoint Editor.

**Comment by rodolforg** [comment]
I agree.

**Comment by rodolforg** [comment]
This issue is fixed in v1.4.1.
