### ISSUE TITLE
[CMake] Animation playback is not smooth anymore

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1196]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
Pulled and merged updates from master branch today and encountered the problem.
Playback lags gradually from start time and gets slower as timeline cursor progresses toward the end.
[Screencast from 05-03-20 01:31:30 PM IST.zip](https://github.com/synfig/synfig/files/4291673/Screencast.from.05-03-20.01.31.30.PM.IST.zip)

**Comment by Keyikedalube** [comment]
This issue is noticeable even on an empty canvas workspace.

**Comment by rodolforg** [comment]
Do you know last version it doesn't lag like that?

If so, could you try to git bisect to investigate which commit did it?

**Comment by Keyikedalube** [comment]
On my old but recent synfig folder where I haven't rebased from upstream, the working commit id is
6b433d2503ed81bd6577c17748d2ae59ce0573c6

**Comment by rodolforg** [comment]
Is it the last working commit or First not working one?

Em qui, 5 de mar de 2020 10:28, Keyikedalube Ndang <notifications@github.com>
escreveu:

**Comment by Keyikedalube** [comment]
Last working commit. I'm checking out other commits with git bisect. 
*Sorry for the delay... was away during the build*

**Comment by Keyikedalube** [comment]
Did git bisect and no luck catching the commit that's causing the issue.
Same laggy playback
*BTW, at the time I reported this issue I used CMake build script to build synfig*

This is a bug from synfig's CMake build script

Just to make sure, I tried building using build-production script and animation playback is smooth

**Comment by ice0** [comment]
@Keyikedalube confirmed. I can take a look on the next week. Thanks for pointing this out.

**Comment by rodolforg** [comment]
I can't reproduce it on Linux + autotools.

**Comment by ice0** [comment]
@rodolforg this is CMake only related problem. The interesting part of this is that there some code which works very slow without defines which CMake did not set.

**Comment by ice0** [comment]
I also noticed that autotools version skips frames, but CMake is not (need to check this again). So problem maybe deeper, and we have rendering slowdown on longer animations.

**Comment by Keyikedalube** [comment]
@ice0 Will this issue be fixed during GSoC 2020? I'm noticing new PRs improving synfig CMake script.
*Just curious*

**Comment by ice0** [comment]
@Keyikedalube can you check if problem is resolved?

**Comment by Keyikedalube** [comment]
@ice0 I did yesterday. Problem is resolved :)

**Comment by ice0** [comment]
@Keyikedalube Awesome! Thank you!
