### ISSUE TITLE
Wrong file name on the alert dialog box when using plugins

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#1204]
**Synfig version & platform**:
https://github.com/synfig/synfig/commit/a98351568cfe8bd1403b4dfcf6d817f680b05ae9
Platform: Ubuntu 18.04.4 LTS

**Issue description**:
When I open a new file in Synfig and try to use any plugin on it(say `export to Lottie`), the name of the file on the alert dialog box is different than the selected file.
I am attaching a `.gif` describing this issue. The file I opened is `circle.sif`, but the name on the alert dialog box is `Synfig animation 1`.
![Synfig_peek](https://user-images.githubusercontent.com/30872212/76150441-a2dbcf80-60d0-11ea-8e8d-bd68839db003.gif)
P.S. Please click on the gif to view this error properly

**Comment by saurabh-ramola** [comment]
I am attaching a .gif describing the result of the changes made.

![circle](https://user-images.githubusercontent.com/31828811/76176584-55965580-61d7-11ea-9842-1c74e95fb758.gif)
