### ISSUE TITLE
Fix year in About dialog

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1205]
About dialog still shows 2019 now :)

**Comment by ARYA-BHARDWAJ** [comment]
May I have look on this issue

**Comment by ARYA-BHARDWAJ** [comment]
May I solve this issue ??

**Comment by ice0** [comment]
Sure!

**Comment by ice0** [comment]
Fixed in https://github.com/synfig/synfig/commit/053841be1bb8b6c75a1dd098c40948d74c22bd46
