### ISSUE TITLE
Widget_Vector should reacts to TAB key press

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#1208]
When editing value of vector parameters, eg layer `Origin`, user types `x` value first, press `Enter` (to activate/confirm edition) and then focus moves to `Y` value text field.

On the other hand, `TAB` (and `shift`+`TAB`)  is a common navigation key among form fields and this editor widget ignores it.

**Comment by AnshitaVishwa** [comment]
@rodolforg my approach to solve this issue is using the "key-press-event", which uses callback that will check if the pressed key is a TAB key then the focus is changed. Is this a right approach to this problem ?

**Comment by rodolforg** [comment]
@AnshitaVishwa Yes. Look at synfig-studio/widgets/widget_vector.h/cpp to check exactly where and how you would use it

**Comment by SushantAA** [comment]
I want to work on this issue
pls assign me

**Comment by rodolforg** [comment]
@AnshitaVishwa  Any progress?

**Comment by DhairyaBahl** [comment]
@rodolforg If no one is working on this issue currently , then I would love to work on this issue for better understanding of the project. 

Regards

**Comment by riya1606** [comment]
@rodolforg If no one is working on this issue currently, I would love to work on it! I am confident that I can solve it. Thank you! :)

**Comment by rodolforg** [comment]
Any progress? Need any help?

**Comment by ankit-kumar-dwivedi** [comment]
@riya1606 

> Any progress? Need any help?

**Comment by ankit-kumar-dwivedi** [comment]
> @rodolforg If no one is working on this issue currently, I would love to work on it! I am confident that I can solve it. Thank you! :)

@riya1606 are you working not his one? let us know if you need any help/hint
