### ISSUE TITLE
Copyright for Vectorization code

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1214]
The vectorization code uses algorithms from OpenToonz. 

We need to add proper copyright lines to each `.cpp` file here - https://github.com/synfig/synfig/tree/master/synfig-studio/src/synfigapp/vectorizer

**Comment by morevnaproject** [comment]
Hi @ankit-kumar-dwivedi! Can you please take care about this? We need that done before 1.4.0 release. ^_^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject on it!

**Comment by ankit-kumar-dwivedi** [comment]
```
**  Vectorization feature is ported from OpenToonz(https://github.com/opentoonz/opentoonz)
**  OpenToonz is an Open Source Program licensed under Modified BSD license is developed from Toonz, 
**  a software originally created by Digital Video, S.p.A., Rome Italy
```
@morevnaproject looks good?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Can you please create a list of all files from OpenToonz repo that responsible for vectorization?

I have noticed some files in OT repo has mention of authors, like this one - https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/ObjectTracker.cpp
We need to reference them too.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject the following files are used for vectorization feature

- [ opentoonz/toonz/sources/include/toonz/tcenterlinevectorizer.h ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/include/toonz/tcenterlinevectorizer.h)
- [ opentoonz/toonz/sources/toonzlib/tcenterlinevectorizer.cpp ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzlib/tcenterlinevectorizer.cpp)
- [ opentoonz/toonz/sources/toonzlib/tcenterlinetostrokes.cpp ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzlib/tcenterlinetostrokes.cpp)
- [ opentoonz/toonz/sources/toonzlib/tcenterlineskeletonizer.cpp ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzlib/tcenterlineskeletonizer.cpp) 
- [ opentoonz/toonz/sources/toonzlib/tcenterlinevectP.h ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzlib/tcenterlinevectP.h) 
- [ opentoonz/toonz/sources/toonzlib/tcenterlinepolygonizer.cpp ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzlib/tcenterlinepolygonizer.cpp) 
- [ opentoonz/toonz/sources/toonzlib/tcenterlinecolors.cpp ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzlib/tcenterlinecolors.cpp)

None of them has a reference like you mentioned. Also, we are not using any other files as we have our own implementation for raster, vector, pixel, methods etc..

> I have noticed some files in OT repo has mention of authors, like this one - https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/ObjectTracker.cpp
> We need to reference them too.

**Comment by morevnaproject** [comment]
> None of them has a reference like you mentioned.

You right. But I noticed GitHub shows contributors for each file -
![screenshot_002](https://user-images.githubusercontent.com/332868/77855350-124d6680-721a-11ea-89f9-132380782967.png)

We have to reference them.

Also, there is a note at the bottom of [Readme.md](https://github.com/opentoonz/opentoonz/blob/master/README.md#special-thanks):

> This Open Source Program is developed from Toonz, a software originally created by Digital Video, S.p.A., Rome Italy

..and in [LICENSE.txt](https://github.com/opentoonz/opentoonz/blob/bc544591ac96cdaa5cd57649687c716341c415cb/LICENSE.txt#L9-L11):

> All contributions by DWANGO:
> Copyright (c) 2016 - 2018, DWANGO Co., Ltd.
> All rights reserved.
>
> All other contributions:
> Copyright (c) 2016 - 2018, the respective contributors.
> All rights reserved.
>
> Each contributor holds copyright over their respective contributions.
> The project versioning (Git) records all such contribution source information.

and in same LICENSE.txt:

> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
>
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

**Comment by morevnaproject** [comment]
There are also interesting note - https://opensource.stackexchange.com/a/305

Quoting here:

> If the BSD license in question is the two- or three-clause variant (i.e. without the advertising clause), I think you're technically allowed to do it, but you couldn't really enforce it: anyone who obtained a copy of the code you're distributing could re-use the BSD-licensed code under the provisions of the BSD license only, and the GPL wouldn't apply. (The GPL would apply to anything you hold the copyright for, and to the agregate; i.e. resulting binaries would be GPL. But for that to be meaningful you'd have to add code of your own...)
> 
> What Microsoft and Apple are doing is complying with the BSD license.
>
>>  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> If they don't redistribute source code then that doesn't apply. (Nothing forces them to redistribute source code; that's why the BSD license is called a permissive license.)
>
>>    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
>
> You'll find that Microsoft and Apple products which incorporate BSD code do satisfy this, either in the documentation, or typically in the "About" box.
>
>>   The name of the author may not be used to endorse or promote products derived from this software without specific prior written permission.
>
> Somehow I doubt Microsoft or Apple would be interested in doing this anyway.
>
> The final clause is the lack of warranty, which everyone disclaims anyway, so there's no change there either.

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi  So, in my opinion what we should do to comply with BSD license:

1. Create a list of all people who contributed to files you listed above. List in the following form:

> Copyright (c) YEAR(s) Contributor_Name - github_link

i.e.:

> Copyright (c) 2016 Toshihiro Shimizu - https://github.com/meso

Note, that you can find a year of contribution by clicking "Blame" button on GitHub and then hovering the commit name - it shows date of commit.

![screenshot_004](https://user-images.githubusercontent.com/332868/77855894-ad940b00-721d-11ea-991f-f32d0ab82921.png)

![screenshot_003](https://user-images.githubusercontent.com/332868/77855891-a8cf5700-721d-11ea-9767-3fb5e2ac1226.png)

2. Add following text to all files in https://github.com/synfig/synfig/tree/master/synfig-studio/src/synfigapp/vectorizer:

```
/* === S Y N F I G ========================================================= */
/*!	\file filename.cpp
**	\brief writeme
**
**	$Id$
**
**	\legal
**	This file uses code from OpenToonz open-source animation software  (https://github.com/opentoonz/opentoonz/), which is developed from Toonz, a software originally created by Digital Video, S.p.A., Rome Italy Digital Video, S.p.A., Rome Italy.
**
**	Copyright (c) 2016 - 2019, DWANGO Co., Ltd.
**	--PUT LIST OF CONTRIBUTORS FROM STEP1 HERE--
**	Copyright (c) 2019 - 2020, Ankit Kumar Dwivedi - https://github.com/ankit-kumar-dwivedi
**
**	LICENSE
** 
**	BSD 3-Clause "New" or "Revised" License
** 
**	Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
**
**	1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
**
**	2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
**
**	3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
**
**	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**	\endlegal
*/
/* ========================================================================= */
```

3. We need a similar text to be visible somewhere in GUI. I guess best place for it in About dialog (in Credits section). The text I suggest to be like this:

```
-- VECTORIZER FEATURE CREDITS  --

Vectorizer feature is ported from OpenToonz open-source animation software  (https://github.com/opentoonz/opentoonz/), which is developed from Toonz, a software originally created by Digital Video, S.p.A., Rome Italy Digital Video, S.p.A., Rome Italy.

Copyright (c) 2016 - 2019, DWANGO Co., Ltd.
--PUT LIST OF CONTRIBUTORS FROM STEP1 HERE--
Copyright (c) 2019 - 2020, Ankit Kumar Dwivedi - https://github.com/ankit-kumar-dwivedi

Vectorizer feature code is licensed under BSD 3-Clause "New" or "Revised" License

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-- VECTORIZER FUNCTION CREDITS END --
```

**Comment by ankit-kumar-dwivedi** [comment]
Okay @ankit-kumar-dwivedi

**Comment by ankit-kumar-dwivedi** [comment]
>     1. We need a similar text to be visible somewhere in GUI. I guess best place for it in About dialog (in Credits section). The text I suggest to be like this:

I guess there is already much information, also as we use built-in about dialog from gtk we can't do much with it.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject have added the PR without about dialog edit.

**Comment by morevnaproject** [comment]
> I guess there is already much information, also as we use built-in about dialog from gtk we can't do much with it.

This is requirement of license - to make this text visible when distributing in binary form.
Please see in my previous https://github.com/synfig/synfig/issues/1214#issuecomment-605669958:

>> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
>
> You'll find that Microsoft and Apple products which incorporate BSD code do satisfy this, either in the documentation, or typically in the "About" box.

So we are obligated to do that. ^__^

> as we use built-in about dialog from gtk we can't do much with it.

We can edit this information in `synfig-studio/src/gui/dialogs/about.cpp`. ^__^

> have added the PR without about dialog edit.

Awesome, thank you!
The PR for About dialog can be a separate one. ^__^

**Comment by morevnaproject** [comment]
> We can edit this information in synfig-studio/src/gui/dialogs/about.cpp. ^__^

@ankit-kumar-dwivedi Can you please add copyright information to About dialog? ^__^

**Comment by rodolforg** [comment]
@ankit-kumar-dwivedi  , maybe you can create a new section:
```c++
void Gtk::AboutDialog::add_credit_section(const Glib::ustring & section_name, const std::vector< Glib::ustring > &  people)```

and/or append the license in the License section with a preamble like : "\n\nLicense for Vectorization".

**Comment by morevnaproject** [comment]
I plan to release 1.3.14 next week and this issue is blocking. Can anyone take care on it? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject my apologies for the delay. Will take care of this before
Monday.

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Thank you! ^__^
