### ISSUE TITLE
[SynfigPlayer] Add option to playback animation in realtime

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1215]
Add option to playback animation in realtime for `synfigplayer` - https://github.com/synfig/synfig/tree/master/synfig-studio/src/player

Currently `synfigplayer` just renders every frame one-by-one, without syncing. And this is good for testing rendering speed. It would be nice to have an option to play animation in realtime, though. ^__^

**Comment by Aa20475** [comment]
Hey @morevnaproject ! I'd like to work on this issue.

**Comment by morevnaproject** [comment]
Great! Assigned to you ^__^

**Comment by Aa20475** [comment]
I think we can close this issue?

**Comment by morevnaproject** [comment]
Yes, thank you! ^__^
