### ISSUE TITLE
Waypoint types list is not consistent across Synfig Studio

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1216]
**Synfig version & platform**:
Master: 4f6e09

**Issue description**:
In Synfig Studio there are various places where the user can choose the type of waypoint to use.

I have noticed that those lists are not always consistent.

For example in the timeline we have:
![order_timeline](https://user-images.githubusercontent.com/6705690/76308984-2ad9f900-62cc-11ea-8b7e-6c893fe4df58.png)

While editing a specific waypoint the order is different:
![order_waypoint](https://user-images.githubusercontent.com/6705690/76309019-3b8a6f00-62cc-11ea-9b19-68e709d60436.png)

Probably there are other places where this order is not consistent. It would be nice to have it consistent across all Synfig Studio.

**Comment by FirasH** [comment]
I can work on this.

I think we could order them using alphabetical ordering i.e.
Clamped / Constant / Ease In/Out / Linear / TCB
but this will be true for sure only for English.

Alternatively the order could follow the likelihood of using a type of interpolation, but still that depends on the animation project.

What would you suggest?

**Comment by UltimateGamer07** [comment]
if its not already done, i'll work on this

**Comment by ice0** [comment]
@UltimateGamer07 @FirasH already done it #1245 (just waiting for review)

**Comment by morevnaproject** [comment]
I like the order done by @FirasH: Clamped, TCB, Constant, Ease, Linear
