### ISSUE TITLE
[Lottie exporter] Export outlines without variable widths

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1217]
Add an option to export outlines without variable widths.

That way we get native Lottie outlines and will make animation playback much faster.

**Comment by saurabh-ramola** [comment]
@morevnaproject , I discussed this with @AnishGG and we found a way that will allow us to not animate the animation frame by frame and this method leads to a huge decrease in `.json` file size as well leading to faster playback 😃 . The only limitations are that : 
1. Width will be the same in the outline, though it can be animated.
2. The ends of the outline(tip) cannot be animated in this method.

**Comment by AnishGG** [comment]
@saurabh-ramola please mention the points that were discussed regarding the use of first vertex as the common width. This way we can ensure that we are all on the same page and then you can start with the implementation. ^__^

**Comment by saurabh-ramola** [comment]
> @saurabh-ramola please mention the points that were discussed regarding the use of first vertex as the common width. This way we can ensure that we are all on the same page and then you can start with the implementation. ^__^

Yes, I forgot to mention the options for width :
1. We could use the width of the first vertex as the common width.
2. We could take the average width of the three vertices but this would be problematic to implement in Lottie.

Personally I'm in favour of first option.

**Comment by AnishGG** [comment]
> 2\. three vertices

I think you meant all vertices :D

+1 in favour of using the width of first vertex as the common width.

**Comment by morevnaproject** [comment]
I think we should use value in Outline Width parameter (1), as the widthpoints (2) are just define relative scale for that value ^__^ -
![screenshot_001](https://user-images.githubusercontent.com/332868/90643098-6276a500-e25d-11ea-8b8e-aa6c2e328122.png)

**Comment by AnishGG** [comment]
> I think we should use value in Outline Width parameter (1), as the widthpoints (2) are just define relative scale for that value ^__^ -
> ![screenshot_001](https://user-images.githubusercontent.com/332868/90643098-6276a500-e25d-11ea-8b8e-aa6c2e328122.png)

Oh yes, this is much better!
@saurabh-ramola please make a note. ^__^

**Comment by AnishGG** [comment]
Linking the PR here: https://github.com/synfig/synfig/pull/1647
