### ISSUE TITLE
[Lottie exporter] Use "File" -> "Export for web" menu comand to call "Lottie Exporter"

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1218]
Currently Lottie Exporter is implemented as a Synfig Plugin.
This puts some limitation at its functionality.

For example:
- It is not possible to set output filename
- It is not possible to set additional parameters (for example #1217)
- After calling plugin Synfig file is closed and re-opened every time. That takes time and also clears undo history.

Considering all above, I suggest to re-organize Lottie Exporter from plugin to native menu command.

I mean modify Synfig C++ code in the following way:
1.  Add "File" -> "Export for web" menu command.
2. This command will open a dialog similar to "Save As..." dialog.
3. When user choosing location and filename, he clicks "Export/Save" and C++ code is saving a temporary copy of current document and executes a python script which does actual conversion. At this point we can pass additional parameters to python script, which come from options of dialog at step 2.

**Comment by morevnaproject** [comment]
@AnishGG Please take a look. ^__^

**Comment by AnishGG** [comment]
Sure!

**Comment by AnishGG** [comment]
@morevnaproject 
For this, I will have to create a new dialog(just like https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/dialogs/canvasoptions.cpp), right?
P.S. I am new to gtkmm, will need a little bit help here.

**Comment by AnishGG** [comment]
I was trying to go through the code and implement this. I will need some clarifications. :P
Here is the branch I am committing the code to https://github.com/AnishGG/synfig/tree/export_for_web_ui
For now, I have just copied the `canvas_options` for most of the parts.
I am trying to call the `lottie exporter` plugin from within the `dialog_exportforweb.cpp`, but I am failing to do so here: https://github.com/AnishGG/synfig/blob/e0ea6945624b8bfca9cee2b7e49ff6420010d167/synfig-studio/src/gui/dialogs/dialog_exportforweb.cpp#L214

@ice0 @morevnaproject any suggestions from your side please. ^__^

**Comment by ice0** [comment]
@AnishGG this is because you need to get an instance of the active `CanvasView`, and not just run the method from the `Instance` class. So in your example, it will be something like:
```
canvas_view_->get_instance()->run_plugin(this->plugin_path);
```
