### ISSUE TITLE
[CMake] modules.cfg and *.glade files

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1225]
We need to add /etc/modules.cfg and /share/synfig/*.glade files to do synfigstudio runnable.

**Comment by ice0** [comment]
If you try to run `./synfig` from `output/bin/ ` directory - all works fine.
But if you try to run `./synfigstudio` - it exits with error 
```
synfig(766) [10:51:23] error: FileError: Failed to open file 
“share/synfig/ui/canvas_options.glade”: No such file or directory
```
We need to copy *.glade files from `synfig-studio/ui` directory to `$SYNFIG_BUILD_ROOT/share/synfig/ui/`

**Comment by ice0** [comment]
After what it still cannot find the files (we need to change a path searching logic), but as a temporary solution we can set environment variable:
```
SYNFIG_ROOT=/path/ti/output/dir ./synfigstudio
```
and `./synfigstudio`  should start with broken images.

**Comment by ice0** [comment]
Also we need to write `modules.cfg` file generated by `synfig-core/src/modules/CMakeLists.txt` to `$SYNFIG_BUILD_ROOT/etc`

**Comment by AYESDIE** [comment]
I worked out on it. Should I open a PR for it?

**Comment by ice0** [comment]
Assigned to you. Just do PR when you will be ready.
