### ISSUE TITLE
SynfigStudio can't find *.glade files inside build root

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1230]
Need to fix search logic in synfigstudio. 

If no SYNFIG_ROOT is defined, assume it is parent of folder from where binary is located.

For example:
current build output is located in 'output/bin/synfigstudio', so we assume what `SYNFIG_ROOT=output/`

**Comment by AYESDIE** [comment]
I was brainstorming it a little bit and was checking the code as well. I think we can update `synfig-studio/src/gui/resourcehelper.cpp` to implement a new logic in case `SYNFIG_ROOT` is undefined.

**Comment by ice0** [comment]
I agree. I think this will be good enough.
