### ISSUE TITLE
Setting environment dependencies on openSUSE leads to conflicting commands

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1231]
**Synfig version & platform**:
Master: c3054c4
openSUSE Leap 15.1

**Issue description**:
If you want to setup a freshly installed openSUSE machine using the provided script:
"1-setup-linux-native.sh"

The command:
"if command -v apt-get >/dev/null; then"

which includes apt-get is detected by the OS and thus the part needed to set openSUSE using zypper is not chosen:
"elif which zypper >/dev/null; then"

Currently I have simply removed all the code before the code for zypper and it works correctly. Probably the order should be from the most specific package manager (e.g zypper or yum) to the most generic like apt-get.

**Comment by morevnaproject** [comment]
We can improve script in the following way: it can read contents of `/etc/os-release` and use values from there. ^__^

Can you please post output of this command - `cat /etc/os-release`?

**Comment by FirasH** [comment]
This is the output of my openSUSE 15.1:
~> `cat /etc/os-release`
NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
