### ISSUE TITLE
[Lottie Exporter] Lottie Export Fails after importing sifz file into project

### ISSUE THREAD

**Issue by RandomGHUser** [synfig/synfig#1242]
Synfig 1.3.12 (Portable) / Windows 10

Problem Recreation: 
1) Create and save an sifz file with a circle in it.
2) Import sifz file into a new project.
3) Export to Lottie format

I receive these errors:

![error](https://user-images.githubusercontent.com/40616218/76664112-75fc4200-6540-11ea-8d6e-5b7978df059b.PNG)

**Comment by AnishGG** [comment]
Yes, This is expected behavior. `use-def`s are yet to be implemented.
I have created an issue regarding the same.
#1243
