### ISSUE TITLE
[Lottie Exporter] Implement use-def's

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#1243]
use-def is needed when you import Synfig files to another file.

**Comment by AnishGG** [comment]
Where can I find all the possibilities of how `use-def` is used?
For instance, I saw all these:
```
<param name="canvas" use="circle.sifz#"/>
<param name="segment_list" use="Shape"/>
<param name="canvas" use=":"/>
<param name="gradient" use=":RedGreenBlue"/>
```
@ice0

**Comment by ice0** [comment]
I hink we need @morevnaproject here :)

**Comment by AnishGG** [comment]
@morevnaproject any insights here. ^__^
