### ISSUE TITLE
[CMake] Set definitions and compile flags based on CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1249]
Currently if you set CMAKE_BUILD_TYPE you must get different binaries with different splash screens, different About dialog, etc.

So we need to set some defines based on build type.
For example:
```
(for debug builds)
_DEBUG 
SHOW_EXTRA_INFO # Show extra info in the about dialog

compile_options: -fno-inline-functions -fno-inline -g -O0 -Wall
```

Here is a good article explaining some moments.
https://blog.kitware.com/cmake-and-the-default-build-type/

* Also need to set default build type to Debug.
* Need to add CMake message with Build type

**Comment by ice0** [comment]
For Debug build:
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=undefined  -fsanitize=address  -fno-omit-frame-pointer")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=undefined  -fsanitize=address -fno-omit-frame-pointer")
```

**Comment by AYESDIE** [comment]
I had a couple of question.

Where is the bash script for *release* build located?
Do we need to work on all the build types `Debug`, `Release`, `RelWithDebInfo` and `MinSizeRel`, or just the two `Debug` and `Release`.

**Comment by ice0** [comment]
> Where is the bash script for release build located?
Here is the script: https://github.com/synfig/synfig/blob/master/2-build-production.sh

Also you may need to check autotools script, it have logic for chooses different splash screens. Maybe need to set some flag for that.

> Do we need to work on all the build types Debug, Release, RelWithDebInfo and MinSizeRel, or just the two Debug and Release.

Currently we need a possibility to change flags for Debug and Release only,

**Comment by AYESDIE** [comment]
I found the autotools logic for all those, but are there other things that need to be looked at other than splash screen, about section and compiler flags?

**Comment by ice0** [comment]
I think that will be enough. In any case, we can add other options later.
