### ISSUE TITLE
Items in Plugins menu ignore language set in preference

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1252]
**Synfig version & platform**:
1.3.13, Linux

**Issue description**:
When I set application language to English (via "Edit" -> "Preferences"), the language of items in "Plugins" menu remains in system locale (Russian in my case).

![screenshot_005](https://user-images.githubusercontent.com/332868/76856067-14f8a500-6885-11ea-9410-4cdce20a9de5.png)

How to reproduce:
1. Ensure that your system locale is any other than English.
2. Start Synfig
3. Select "Edit" -> "Preferences" from menu
4. Choose any language, different from your system locale 
![screenshot_006](https://user-images.githubusercontent.com/332868/76856140-38235480-6885-11ea-88e1-5f9492fe19b9.png)
5. Click OK to apply new settings.
6. Restart Synfig.
7. Click "Plugins" menu and observe items in your system language.

**Comment by man-of-code** [comment]
Hey, @morevnaproject Can I work on this??

**Comment by ice0** [comment]
@man-of-code Sure, assigning you to this.

**Comment by man-of-code** [comment]
@morevnaproject @ice0 Thank you!!
Any idea where to start ??

**Comment by FirasH** [comment]
I think this has been fixed in 51ba106

**Comment by rodolforg** [comment]
I confirm it is solved on master e64c7d6784fa10ab8b1753c0c03ab120269fa1c0
