### ISSUE TITLE
"1-setup-linux-native.sh" script: Use values from "/etc/os-release" to detect OS

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1255]
As improvement to #1231:
We can use `/etc/os-release` file to detect OS properly.

Here is the contents of this file on my Linux Mint sysem:
```
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
```

We can import those values into `1-setup-linux-native.sh` script with this:
```
source /etc/os-release
```

...and then check `ID_LIKE` variable:

```
if [ "$ID_LIKE" == "ubuntu" ]; then
   ... (apt-get stuff) ...
elif ...
```

@FirasH what do you think about this? ^__^

**Comment by FirasH** [comment]
@morevnaproject I like it!

**Comment by FirasH** [comment]
This is the output of my openSUSE 15.1:
~> `cat /etc/os-release`
NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by ice0** [comment]
@morevnaproject I agree, but not all OS support `os-release` file. Just checked CentOS 6 (yep, it still supported) and they have no `os-release` file.

So I suggest to leave the script as is, especially since it works well.

**Comment by morevnaproject** [comment]
@ice0 I suggest to modify script to use `/etc/os-release` files and add fallback to old method in case if this file is missing. We can do something like this:

```
if [ -f /etc/os-release ]; then
   source /etc/os-release
fi

if [ -z $ID_LIKE ]; then
   if command -v dnf >/dev/null; then
      export ID_LIKE="fedora"
   elif command -v apt-get >/dev/null; then
      export ID_LIKE="debian"
   elif ...
      ...
   fi 
fi

if [ "$ID_LIKE" == "ubuntu" ] || [ "$ID_LIKE" == "debian" ]; then
   ... (apt-get stuff) ...
elif ...
```

**Comment by ice0** [comment]
@morevnaproject I like this approach

**Comment by FirasH** [comment]
Can I try to implement it?

**Comment by FirasH** [comment]
I had a bit of time so I made a first draft of it.
