### ISSUE TITLE
Dot product convert method not working

### ISSUE THREAD

**Issue by saurabh-ramola** [synfig/synfig#1256]
**Synfig version & platform**:
Synfig version : 786f25f7f3985f14005d48cb7b0956f4435092d3
Platform - Ubuntu 16.04 LTS

**Issue description**:
While trying to apply dot convert method on radius of a circle, I received the following errors : `Convert 'Layer Parameter (Circle):Radius' to ValueNode type 'Dot Product': real ` and on closing this dialog box I received the error `Action Failed.` . I have attached the screenshots for the same.

![pic1](https://user-images.githubusercontent.com/31828811/76938325-6bfd8900-691c-11ea-8626-19f537acb2e0.png)
![pic2](https://user-images.githubusercontent.com/31828811/76938420-93545600-691c-11ea-9ec2-66087eb913fa.png)

Am I doing something wrong or is there an error in the implemented Dot Convert method ?

**Comment by rodolforg** [comment]
It was actually never working! :o

**Comment by ice0** [comment]
@saurabh-ramola Fix #1260 merged into master. Please check.

**Comment by saurabh-ramola** [comment]
@ice0 , It's working now. 
@rodolforg , Thank you for the fix ^_^
