### ISSUE TITLE
DashItem Offset and Length variables are not consistent when editing them

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1265]
**Issue description**:

0. Create a new document
1. Create an Advanced Outline: `Toolbox > Spline Tool > enable "Advanced Layer"`
2. Select it and in the `Parameters` Window open the sub-menu `Dash Item List > Dash Item 001`

Here you can see the list of parameters. If you select either `Offset` or `Length` the value is displayed without unit (by default 0.100000):
![view](https://user-images.githubusercontent.com/6705690/77224418-c63d5a80-6b65-11ea-95c1-84039ca9f626.png)

but if you try to edit it, it will display 6.00000px:
![edit](https://user-images.githubusercontent.com/6705690/77224424-d0f7ef80-6b65-11ea-95fa-45aac590ba77.png)

I assume those two values should be consistent, because as it is now, you have to "guess" the value which corresponds to px and viceversa.

**Comment by FirasH** [comment]
0,100000 should be a relative size to length of the spline.

**Comment by FirasH** [comment]
I also found this code:
https://github.com/synfig/synfig/blob/b57b2809af3e52f16bc5d67b351e79fd04d9b222/synfig-core/src/modules/lyr_std/sphere_distort.cpp#L158-L162

where `.set_is_distance(false)` is used.

But if I'm not wrong the variable `bool is_distance_` is set to `false` by default:
https://github.com/synfig/synfig/blob/b57b2809af3e52f16bc5d67b351e79fd04d9b222/synfig-core/src/synfig/paramdesc.h#L107

thus calling the method:
https://github.com/synfig/synfig/blob/b57b2809af3e52f16bc5d67b351e79fd04d9b222/synfig-core/src/synfig/paramdesc.h#L233

with `false` is redundant. Right?

**Comment by FirasH** [comment]
The same issue is also happening for `Dash Items Offset`. It should be a relative value to the length of the advanced outline.

**Comment by FirasH** [comment]
Even for exported values something similar happens:

0. Create a new document
1. Select the Spline Tool and create an Outline Layer
2. Go to the `Parameter Panel` and right-click on `Outline Width > Export Value` (default value 1.000000pt)

In the `Library Panel` the value is now stored and not consistent (0.016667).
In this case I'm not sure if this behavior can be considered an issue...

**Comment by rodolforg** [comment]
> thus calling the method:
> 
> https://github.com/synfig/synfig/blob/b57b2809af3e52f16bc5d67b351e79fd04d9b222/synfig-core/src/synfig/paramdesc.h#L233
> 
> with `false` is redundant. Right?

Yes, it is.

**Comment by rodolforg** [comment]
> Even for exported values something similar happens:
> 
>     1. Create a new document
> 
>     2. Select the Spline Tool and create an Outline Layer
> 
>     3. Go to the `Parameter Panel` and right-click on `Outline Width > Export Value` (default value 1.000000pt)
> 
> 
> In the `Library Panel` the value is now stored and not consistent (0.016667).
> In this case I'm not sure if this behavior can be considered an issue...

Default value is 1.0*px*. It is equals to (strange internal unit) 0.016667.
It is not a bug, but yes, it is annoying :P

**Comment by FirasH** [comment]
> Default value is 1.0**px**. It is equals to (strange internal unit) 0.016667.
> It is not a bug, but yes, it is annoying :P

Yes, but how can we make it consistent from a logical point of view?

I think there are 2 main points to deal with:
1. If I export a value, and I want to use it for both a unit value (e.g. 1.000000px) and for a relative value (e.g. 0.016667).
2. Making consistent the "preview" and the "edited" value should be the quite simple (`set_is_distance()` does that).
