### ISSUE TITLE
[Timetrack] Different look for semi-transparent waypoints

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1266]
From https://github.com/synfig/synfig/pull/1135#issuecomment-594702477:

Semi-transparent representation of waypoints makes users think that they are "inactive" (cannot be moved).

![screenshot_005](https://user-images.githubusercontent.com/332868/75907814-91e65080-5e7b-11ea-9a14-2add02ee29fb.png)

Can we think about some different representation? Maybe remove transparency and have a double outline for them?

![screenshot_001](https://user-images.githubusercontent.com/332868/77062209-05f12e80-6a0e-11ea-8f94-6bff6e205063.png)

@rodolforg what do you think?

**Comment by rodolforg** [comment]
Code points:
1. It should change `waypointrenderer.cpp` to accept another argument, besides `selected` and `hover`.
2. It must add drawing code for each interpolation type (TCB, linear, clamped, etc) and half (before/after) if this new argument is set.
3. Fix the calling code that pushes and pops cairo state for painting with some transparency: e.g.
https://github.com/synfig/synfig/blob/6591875e830e41352d753a0f9f1b47135fbd31b9/synfig-studio/src/gui/widgets/widget_timetrack.cpp#L390-L394
