### ISSUE TITLE
[Timetrack] Buttons to change interpolation for selected waypoints

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1267]
It would be nice to add buttons, which allow to change interpolation for selected waypoints:
![zzzz](https://user-images.githubusercontent.com/332868/77225647-6796d180-6ba3-11ea-8d7e-c2ced6724a68.png)

5 buttons, each button has icon of corresponding interpolation type.

Clicking on button changes interpolation on selected waypoints.

Note: Those buttons act differently than move/duplicate/scale buttons in TimeTrack panel. They do not switch to specific "mode" (tool), instead they just apply particular action to selected waypoints. This is why I added separator to toolbar, so interpolation buttons visually stand away from other buttons.

**Comment by rodolforg** [comment]
If those buttons needs more space, should we use a popup/popover menu/bar?

**Comment by morevnaproject** [comment]
Good idea!

**Comment by mohamedAdhamc** [comment]
Hey @morevnaproject @rodolforg, should these five buttons apply the selected interpolation type for the in/out interpolation together?

**Comment by mohamedAdhamc** [comment]
Merged in #2615
