### ISSUE TITLE
Synfig AppImage 1.3.13 doesn't render from command-line

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1269]
**Synfig version & platform**:
1.3.13 AppImage

**Issue description**:
```
./SynfigStudio-1.3.13-testing-2020.03.14-linux64-7816d.appimage -i e11t12.sifz -o dir/w.png
```
https://forums.synfig.org/t/error-commandline-render/10767

**Comment by morevnaproject** [comment]
Solved - https://forums.synfig.org/t/error-commandline-render-close/10767/16?u=konstantindmitriev
