### ISSUE TITLE
Creating a "Shade" Layer in an empty animation crashes Synfig Studio

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1271]
**Synfig version & platform**:
Master b57b280

**Issue description**:
1) Start Synfig Studio, a new empty animation will be created
2) Go to: `Layer > New Layer > Stylize > Shade`

Synfig crashes consistently.

**Comment by ice0** [comment]
@morevnaproject Should it be available if there are no layers?

**Comment by rodolforg** [comment]
@ice0 even if there is some layers, Synfig crashes if you disable those later.

**Comment by ice0** [comment]
@rodolforg Thanks for pointing this out.
