### ISSUE TITLE
Not able to add color stops in linear gradient layer

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#1274]
**Synfig version & platform**:
Synfig version: master branch - https://github.com/synfig/synfig/commit/3f3c7979181ee74282deb5d6deaa60e7959e254a
Platform: Ubuntu 18.04.4 LTS

**Issue description**:

In the gradient editor(for gradient layer), I am not able to add a `color stop` using two finger touch on the touchpad(right click on the mouse works). In general two finger touch is bind to right clicking in my OS. I also checked that this 2 finger touch is working on other areas of Synfig, like canvas.
Is there some key binding problem here?

![Screenshot from 2020-03-24 05-07-39](https://user-images.githubusercontent.com/30872212/77348526-9ce81e80-6d5f-11ea-97e4-b80923c04a8c.png)

**Comment by rodolforg** [comment]
AFAIK, it shows up a popup menu that pops down as soon as you release right mouse-button :/

**Comment by AnishGG** [comment]
Alright, So will this count as non Synfig issue. I mean, all that Synfig registers is release of right mouse-button and then shows up a popup menu?

Here I am attaching an image showing the area where the 2 finger touch works:

![90752374_2949474555121838_273271275642683392_n](https://user-images.githubusercontent.com/30872212/77353968-f6544b80-6d67-11ea-9290-be97814cf743.jpg)
