### ISSUE TITLE
Spline Tool doesn't close outlines correctly

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#1281]
**Synfig version & platform**:
Master
Linux
**Issue description**:

Spline Tool doesn't close outlines correctly:

1. Select the Spline Tool.
2. Create a shape without dragging .
3. Try to close the shape.
4. The shape doesn't close.

[Video of this behavior](https://youtu.be/3xgiixT5XrI)

**Comment by rodolforg** [comment]
I noticed it: it happens due to `tangent` (yellow) handle overlaps [first-vertex](url) (green) handle…
If you hide `tangents`, it works fine.

Any suggestions?

**Comment by ebarranco** [comment]
Drawing tangents first vertices last. I think that is already the case tought or deactivate tangents when we select the tool But I don't think that is the best way neither..

**Comment by ebarranco** [comment]
@rodolforg Maybe a shortcut for the `Loop Spline` function that closes outlines and shapes. Something like C, alt+C, only press Ctrl, something fast that way you won't have to go to your first vertex every time. Or an `Automatic Loop Spline` when you move your last vertex over the first one. Maybe both.

**Comment by rodolforg** [comment]
Done :)
