### ISSUE TITLE
Delete vertices makes Synfig crash

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#1282]
**Synfig version & platform**:
Master
Linux

**Issue description**:

Deleting vertices make Synfig crash:
1. Use Spline Tool.
2. Close a shape.
3. Delete vertices one at the time.
4. Crash.

[Video of this behavior](https://youtu.be/mKKb0zNWhnw)

**Comment by rodolforg** [comment]
I believe it would be fixed by https://github.com/synfig/synfig/pull/1188 .

**Comment by ebarranco** [comment]
thanks, I'll be pending to test it.

**Comment by rodolforg** [comment]
@morevnaproject @ice0 this issue is really easy to trigger and can be workaround'ed by that PR.
It's not the best solution, but it avoids this problem.

**Comment by ice0** [comment]
@rodolforg ok, I will merge it tomorrow.

**Comment by ice0** [comment]
Ok, I merged it. @ebarranco can you check it please?

**Comment by ebarranco** [comment]
@rodolforg @ice0 It seems is working fine now, thank you.
