### ISSUE TITLE
History Panel records useless entries while editing Colors

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1302]
**Synfig version & platform**:
Master: c1b848

**Issue description**:

0. Create a new animation
1. Insert a Circle on Canvas (to have an object that has a color)
2. Select it and in the Parameters Panel edit the `Color`
3. In the Colors Dialog, drag around the white circle defining the color

Now in the History Panel there are many records that are useless and practically tedious to undo.

I think it would be more effective to record only when the mouse button is released or after a predefined time has elapsed.

**Comment by ice0** [comment]
Linked issue: https://github.com/synfig/synfig/issues/451

Old ColorChooser vs New ColorChooser: https://github.com/synfig/synfig/issues/536#issuecomment-603406715

ping @morevnaproject @rodolforg

**Comment by Keyikedalube** [comment]
Closed in favor of the linked issue above.
