### ISSUE TITLE
Warning when opening file of older version

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1307]
This issue is a followup to those two issues -
https://github.com/synfig/synfig/issues/1284
https://github.com/synfig/synfig/issues/314#issuecomment-603703084

We now got outline layer, which is breaks "forward compatibility".

I.e. if user opens old file in new version and saves it, then the resulting file cannot be correctly opened in old version again (he will get different placement of widthpoints and incorrect placement  of Spline Vertex converter).

I think it would be nice to add warning dialog when opening files with canvas version of 1.0 or lower. It should warn user that he is opening file of older version and saving this file might make it impossible to open correctly in old version again.

@rodolforg @ice0 what do you think? ^__^

**Comment by morevnaproject** [comment]
Even better it would be nice if warning dialog displayed only in case if opened file has advanced outlines or Spline Vertex convert.

**Comment by morevnaproject** [comment]
> Even better it would be nice if warning dialog displayed only in case if opened file has advanced outlines or Spline Vertex convert.

Um... actually there could be following situation:

- user opens old file received from other user who has older version of Synfig (the file doesn't contains  advanced outlines or Spline Vertex convert).
- user adds advanced outline (looped), saves file and sends it back to original user.
- recipient gets file, tries to open and gets distorted content.

So, maybe we should display warning in any case when opening files with canvas version of 1.0 or lower?

**Comment by morevnaproject** [comment]
So, any ideas about this? @ice0 @rodolforg ^__^

**Comment by rodolforg** [comment]
I'm out of ideas :(
