### ISSUE TITLE
"Plant Layer" freezes Synfig Studio

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1314]
**Synfig version & platform**:
Master: 97acd21
openSUSE 15.1
This happened also with previous revisions (also 1.3.x), but not on Windows

**Issue description**:

0. Create a new animation
1. Go to: `Layer > New Layer > Other > Plant`
2. Draw something on Canvas

Synfig Studio freezes.

**Comment by FirasH** [comment]
Terminal output:

```
synfig(25744) [13:08:52] info: constructed 268 million particles...

(synfigstudio:25744): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: std::bad_alloc
```

**Comment by rodolforg** [comment]
I can't reproduce it. :/

**Comment by FirasH** [comment]
That has something to do with the libraries I have installed then... It happens on 2 of my openSUSE 15.1 machines (built from master) but not on Windows 10 (1.3.13).

I don't use the `Plant Layer` but it's worth to know this issue.

**Comment by ice0** [comment]
> synfig(25744) [13:08:52] info: constructed 268 million particles...

I don't have this message about particles.  Can you make a short video with whole process?

> what: std::bad_alloc

Looks like not enough memory problem. How much memory you have on openSUSE?

**Comment by FirasH** [comment]
> I don't have this message about particles. Can you make a short video with whole process?

Screencast: https://drive.google.com/open?id=11d0zXLU5o8QvhVRkgAHnJE0eQz1NN3dk

> Looks like not enough memory problem. How much memory you have on openSUSE?

On the system where I made the screencast I have 8gb of ram, on the other one where I wrote the report 12gb.

**Comment by FirasH** [comment]
Cannot reproduce with f4a59e9 on openSUSE 15.2
