### ISSUE TITLE
Crash on Undo after deleting grouped layers 

### ISSUE THREAD

**Issue by mbasaglia** [synfig/synfig#1324]
**Synfig version & platform**:
built from git on linux

**Issue description**:

There's some issues with canvas parenting, this is how to reproduce:
* create a layer (like a circle or whatever)
* create a group containing that layer
* select both layers in the layer list (so both the group and its child)
* delete them
* undo

This results in a segmentation fault in `Canvas::get_root` because `parent_` is equal to `this` and goes into infinite recursion.

The `parent_` is assigned this value from `Layer_PasteCanvas::on_canvas_set` based on what I saw in the debugger.

**Comment by rodolforg** [comment]
Could you test this PR?
https://github.com/synfig/synfig/pull/1072

**Comment by mbasaglia** [comment]
yup that fixes it
