### ISSUE TITLE
Add ability to Zoom Timeline directly in the Timetrack

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1326]
**Synfig version**:
Master: 81dc3b6

**Issue description**:
Currently to `Zoom In on Timeline` and `Zoom Out on Timeline` it is necessary to go through the top `View` menu.

Sometimes it is useful to zoom in/out rapidly to edit the waypoints (e.g. when having many closely placed waypoints)

It would be convenient to have the ability to do that directly in the Timetrack regardless of the keyboard shortcuts (that need to be known as a prerequisite).

Some possibilities could be:
1. Add buttons somewhere in the new Timetrack
2. Personally I would suggest to use `Ctrl + Scroll` because (at least for me) it seems very intuitive and also the mouse is already in use for editing on the Timetrack.

What do you think about it?

**Comment by doc-halo** [comment]
Good idea. I prefer using the hot-key method.

**Comment by rodolforg** [comment]
Currently (since 1.2 at least) You can ctrl+scroll on time slider (on "almost-top" of timetracker) to zoom in and zoom out :)

**Comment by FirasH** [comment]
> Currently (since 1.2 at least) You can ctrl+scroll on time slider (on "almost-top" of timetracker) to zoom in and zoom out :)

I didn't know that, indeed you can `Ctrl + Scroll` on the `Timebar` even with current master.

Personally, I suggest to extend this feature outside of the `Timebar` to all the `Timetrack` Panel, it would be much more intuitive especially for new and regular users.

**Comment by rodolforg** [comment]
Yes, it's not intuitive at all. I don't even know how I've discovered it (wiki or read something in forums).

`Ctrl+Scroll` is used in Graph and Sound panels for zooming it (vertically).
So, how can we do horizontal(=time) zooming?

**Comment by FirasH** [comment]
Ok, so we have to deal with horizontal and vertical zooming both with hot-keys.

One possible solution could be:
- `Ctrl + Scroll` for horizontal zooming (to keep it consistent with the `Timebar`)
- `Ctrl + Shift + Scroll` for vertical zooming

**Comment by FirasH** [comment]
This is current `Timebar` scroll zoom code:
https://github.com/synfig/synfig/blob/4d7689b40a7a846400195672e9dfc3f2db653c1c/synfig-studio/src/gui/selectdraghelper.h#L759-L793

And this should be how current vertical zoom is implemented in `Graphs`:
https://github.com/synfig/synfig/blob/4d7689b40a7a846400195672e9dfc3f2db653c1c/synfig-studio/src/gui/widgets/widget_timegraphbase.cpp#L96-L108

**Comment by rodolforg** [comment]
You can also zoom time via `Ctrl`+`+` and `Ctrl`+`_`

In code view, you should change the `TimeModel`.

**Comment by FirasH** [comment]
@rodolforg I've linked a pull request that works in `Graphs` panel.
It's easily applied also on other panels based on `widget_timegraphpanel.`

What do you think about it?

The only minor thing different with respect to timebar is that zooming is applied keeping current time fixed instead of cursor position.

**Comment by rodolforg** [comment]
> The only minor thing different with respect to timebar is that zooming is applied keeping current time fixed instead of cursor position.

By cursor you mean time cursor or mouse cursor?

**Comment by FirasH** [comment]
> By cursor you mean time cursor or mouse cursor?
Mouse cursor.
Current time is the position reference for zooming in and out.

To do it like the timebar we need to use some Gdk event to pick mouse cursor position.

**Comment by rodolforg** [comment]
You can use `get_pointer()` to get current mouse position :)

**Comment by FirasH** [comment]
> You can use `get_pointer()` to get current mouse position :)

Thanks!
