### ISSUE TITLE
Better shortcuts for tools and other actions

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#1336]
**Synfig version & platform**:
Synfig Studio 1.3.13 , Windows 10 build 1909

**Issue description**:
Many hotkey shortcuts in windows do not work as they are expected. For example when I press Alt + w, instead of selecting the width tool, it opens the windows option from the menu bar. It's the same with various other options. 
And as a suggestion, I feel many synfig actions should have a hotkey shortcut, like for grouping and ungrouping, splitting tangents and merging tangents, a shortcut for color picker and many others. It'll just help make synfig a better tool to create awesome animations.
https://synfig-docs-dev.readthedocs.io/en/latest/projects/shortcuts.html

**Comment by Keyikedalube** [comment]
Not only on Windows
This issue is noticeable on Linux too

For instance, try hitting **Alt+C** and Canvas properties menu pops up
While the expected outcome is activating Circle tool

Conflicting hotkeys because one mnemonic is assigned to two things

**Comment by yoSachinkr** [comment]
And because of this bug, we all have to depend on mouse clicks for every single tasks, which could have been done easily by hotkeys.

**Comment by Keyikedalube** [comment]
# Solution idea
It'd be nice if synfig uses GIMP and Inkscape model
- _r_ for drawing rectangle
- _e_ for ellipse (or circle in synfig)
- ...

Single letter for tools
And **Alt+_key_** combinations for menu items and buttons

# Technical
I'm guessing Gtk::Window `signal_key_press_event()` can do the trick

**Comment by yoSachinkr** [comment]
Inkscape model will be the best. It'll make creating the artwork within the synfig a joy.

**Comment by Keyikedalube** [comment]
@yoSachinkr I like inkscape model too ;)

@rodolforg Both Synfig & Inkscape are vector drawing software (at least at the core)
Imagine an Inkscape user seamlessly drawing on either of these two using the same hotkeys
Ain't that cool?

BTW, here are two more related issues if Inkscape model is approached:
- #1122
- #1005

**Comment by rodolforg** [comment]
Whoa! I just checked the Inkscape shortcuts for tools... they aren't number keys anymore!!! 

So they are simple one-key shortcut, just like Gimp. Nice.

**Comment by ice0** [comment]
I am also vote for one-key shortcuts. @morevnaproject?

**Comment by yoSachinkr** [comment]
Using shortcut keys is very much important because it speeds up art creation. While using just mouse, our other hand remains idle which obviously is less productive. This issue should be on a priority list to fix.

**Comment by rodolforg** [comment]
@yoSachinkr @ebarranco @Keyikedalube @Jose-Moreno @morevnaproject 

Could you please propose a new shortcut key/hotkey list for Synfig tools and actions?
These are the current documented ones https://wiki.synfig.org/Keyboard_Shortcuts

**Comment by Keyikedalube** [comment]
# Tool items from toolbox
## Compatible (with Inkscape)
- *s* -> Transform tool
- *m* -> Smooth move
- Mirror
*h* -> Horizontal
*v* -> Vertical
- *e* -> Circle
- *r* -> Rectangle
- _*_ -> Star
- *g* -> Gradient
- *b* -> Spline
- *u* -> Bucket tool
- *d* -> Eyedrop
- *t* -> Text
- Zoom
*+* -> In
*-* -> Out
## Unknown
- *?* -> Draw tool
- *?* -> Cutout
- *?* -> Width
- *?* -> Sketch
- *?* -> Scale
On Inkscape selecting transform tool s takes care of scaling
But since synfig has its own scale tool...
- *?* -> Polygon
Inkscape uses same key * for star and polygon

**Comment by yoSachinkr** [comment]
Single key binding would be awesome, but if it's not possible then I'd suggest following key bindings

- while spline tool is on
( holding **shift** key while clicking on the canvas should create vertex with split tangent handles and its forward tangent handle should be adjustable till the right mouse click is held)

- while transform tool is selected
( clicking a vertex and pressing **alt + X** should switch between **merge tangents and split 
 tangents**)

- **alt + 1 to 6** should do what it does in the current version while **alt + 7** should be show grid and **alt + 8 ** should be snap to grid

- a suggestion on layers panel 
(double click to rename should be removed and instead F2 to rename layers should be retained - reason - sometimes clicking on the layers just to select them invokes rename function)

- **alt + spacebar** should invoke panning across the canvas

- while creating a new shape on the canvas, only the new layers should be active, instead of the new layers plus the layer below it, it'll help grouping newly created layers quick and easy

- shortcut for grouping layers should be **ctrl + g** and for ungrouping layers should be **ctrl + shift + g**

- for selecting all vertices **ctrl + a** and deselecting vertices ** ctrl + shift +a **

-for selecting all layers ** ctrl + d ** and for deselecting all layers ** ctrl + shift + d**

- undo and redo should be **ctrl + z ** and **ctrl +shift+z* respectively

- ctrl + x , ctrl + c , ctrl + v should do their respective funtions

-ctrl + w should be width tool
ctrl + t should be transform tool
ctrl + m should be horizontal mirror tool while ctrl + shift + m should be vertical mirror tool
ctrl + k should be cut- out tool
ctrl + r should be rectangle tool while ctrl + shift + r should create a square
ctrl + Y should be star tool
ctrl + shift + y should create circle
ctrl + b should be spline tool while ctrl + shift + b should be draw tool
ctrl + f should be fill tool while ctrl + shift + f should be gradient tool
ctrl + e should be scale tool
ctrl + p should be sketch tool
ctrl + L should be polygon tool
alt + x is okay for text tool
holding alt should invoke color picker tool while canvas is active

- for zooming default is okay

- for duplicating layers ** alt + d ** is okay
- for duplicating keyframes ** alt + shift + k ** will do the work while for adding keyframe ** alt + k**





-

**Comment by morevnaproject** [comment]
I am also think we need one-key shortcuts for Tools. ^__^

Also I recommend to check shortcuts from Animate CC, as they extremely effective and many animation artists use it - https://helpx.adobe.com/animate/kb/animate-keyboard-shortcuts.html

Also, it would be nice to put a plan for Shortcuts rework at a dedicated page in [Synfig Developer Documentation](https://synfig-docs-dev.readthedocs.io/en/latest/projects.html). We can put initial draft there, then as discussion here goes on we can change it with PRs. And when we get happy with the plan do the last thing - implement it. ^__^

**Comment by rodolforg** [comment]
> Single key binding would be awesome, but if it's not possible […]

It is :)

**Comment by yoSachinkr** [comment]
Apart from tools, we need hotkey shortcuts for repetitive actions as well, like grouping, splitting and merging tangents, panning across the canvas, setting layers into switch group, setting layers aside, color picker, linking, looping and unlinking also.  @morevnaproject

**Comment by yoSachinkr** [comment]
https://github.com/synfig/synfig/issues/546#issuecomment-472710076
Considering the answer provided by the @morevnaproject  in the above link, I thought, shortcut keys with single key binding could cause problems, and hence I provided a comprehensive and easy to memorize set of key bindings which uses ctrl, shift and alt to reduce the possibility of further bugs. @rodolforg  . Though if single key binding is not going to cause any problem then It'll be awesome but if the hotkeys for the mentioned actions in my last comment were added too, then it'd just become perfect. :)

**Comment by rodolforg** [comment]
I think this was fixed by https://github.com/synfig/synfig/pull/898

**Comment by yoSachinkr** [comment]
It'd be amazing to see new hotkey bindings then 😀

**Comment by rodolforg** [comment]
Well, the challenge is: how to decide the new shortcuts lol

For example, I prefer redo to be "`ctrl+shift+z`", but [some software use "`ctrl+y`"](https://en.wikipedia.org/wiki/Control-Y) (like [GIMP](https://docs.gimp.org/2.10/en/gimp-edit-redo.html)), some use "`ctrl+r`"  (I'd say er... MS Word, [but they say they use `ctrl+y`](https://support.office.com/en-us/article/undo-redo-or-repeat-an-action-84bdb9bc-4e23-4f06-ba78-f7b893eb2d28))

**Comment by yoSachinkr** [comment]
The lazy me says **ctrl + shift + z** is a best suited for redo because in that case I'd not have to stretch my finger too far to reach to either R or Y while holding a ctrl key to do a very trivial task as redo.

**Comment by rodolforg** [comment]
It was just an example of a matter of taste. (I prefer that way too).
But what about other actions?

@Keyikedalube proposed some, you may prefer other set, @morevnaproject another… lol

Anyway, something must be done, as currently hotkeys for "all" tools are broken (it depends on the locale as they are now with `alt`…)

**Comment by yoSachinkr** [comment]
A default hotkey bindings need to be set first, 
I've seen many softwares provide customization for hotkeys. If that will be implemented too, it'll just solve the problem of preference of hotkeys.

**Comment by yoSachinkr** [comment]
Be it GIMP, Krita, Inkscape, or any other image manipulation software, they all provide keyboard shortcut customizations.

**Comment by rodolforg** [comment]
Collecting some related issues you both mentioned here : #546 #1005 #1122 
About shortcut customization: https://github.com/synfig/synfig/issues/422
Other shortcut/hotkey related: #491 #412 #414 #568 #1148 #1208

**Comment by Keyikedalube** [comment]
If I remember correctly, IntelliJ IDEA has a keyboard shortcut layout preset for existing Eclipse & Netbeans users to ease switching between JetBrains and existing development software.
Users working on multiple animation software like @morevnaproject preference fits here.

@yoSachinkr idea sounds good too. Customization.

I'd love both on synfig <3 <3 <3

**Comment by rodolforg** [comment]
Allow users to choose different layout presets require the same changes shortcut customization feature requires. So IMHO we should first focus on fix what's wrong now.
Customization later.

**Comment by rodolforg** [comment]
> * while spline tool is on
>   ( holding **shift** key while clicking on the canvas should create vertex with split tangent handles and its forward tangent handle should be adjustable till the right mouse click is held)
> * while transform tool is selected
>   ( clicking a vertex and pressing **alt + X** should switch between **merge tangents and split
>   tangents**)

These should be a separate issue @yoSachinkr

**Comment by rodolforg** [comment]
> * while creating a new shape on the canvas, only the new layers should be active, instead of the new layers plus the layer below it, it'll help grouping newly created layers quick and easy

This one too

**Comment by rodolforg** [comment]
> * a suggestion on layers panel
>   (double click to rename should be removed and instead **F2** to rename layers should be retained - reason - sometimes clicking on the layers just to select them invokes rename function)

Separate issue

**Comment by yoSachinkr** [comment]
![image](https://user-images.githubusercontent.com/50204208/79991755-45f57680-84d0-11ea-8599-2fb72e3ac443.png)
![image](https://user-images.githubusercontent.com/50204208/79991764-48f06700-84d0-11ea-9e16-931fc3de148f.png)
split and merge tangents functions are already there, and I think assigning hotkeys to them will help a lot.

**Comment by rodolforg** [comment]
Yes, but you propose to change the behavior of spline tool, not fix a hotkey :)

About merge/split toggle is a new action. So better to separate it from here :)

**Comment by yoSachinkr** [comment]
I agree.

**Comment by rodolforg** [comment]
> Allow users to choose different layout presets require the same changes shortcut customization feature requires.

@Keyikedalube Anyway, the way to go is Gtk::AccelMap

**Comment by morevnaproject** [comment]
As discussion seems to be faded, I suggest to prepare resolution (outcome) on a special page of Developer's documentation - https://synfig-docs-dev.readthedocs.io/en/latest/projects/shortcuts.html

This page will be a form of guidelines for developers who are willing to implement the changes in code. 

I suggest to start by adding initial draft to this page, summarized from https://github.com/synfig/synfig/issues/1336#issuecomment-615364030 and https://github.com/synfig/synfig/issues/1336#issuecomment-615439460

After that all participants are welcome to propose changes to this page via PRs. Each PR can be discussed separately.

**Comment by morevnaproject** [comment]
Also, please note that you can tweak shortcuts on your own (without changing Synfig code) - just eedit `accelrc` configuration file in Synfig's configuration dir. Please see more details at the top of this page - https://wiki.synfig.org/Keyboard_Shortcuts

I believe this can help testing new shortcuts. ^__^

**Comment by yoSachinkr** [comment]
I tried using the accelrc but with no effect. I've read that wiki long ago before posting this issue. So I thought there must be some underlying issues with the way Synfig handles hotkeys.

**Comment by morevnaproject** [comment]
@yoSachinkr Just make sure to remove ";" symbols

**Comment by yoSachinkr** [comment]
Even after removing the ";" , changes made to the shortcut keys doesn't seem to have any effect.

**Comment by Keyikedalube** [comment]
@yoSachinkr It'll be wise to add this link https://synfig-docs-dev.readthedocs.io/en/latest/projects/shortcuts.html in your description https://github.com/synfig/synfig/issues/1336#issue-598305591. That way it'll guide potential implementers to the right place. The conversation here is already lengthy.

BTW, are you working on making a PR for your suggestion https://github.com/synfig/synfig/issues/1336#issuecomment-615439460?

**Comment by morevnaproject** [comment]
> Even after removing the ";" , changes made to the shortcut keys doesn't seem to have any effect.

@yoSachinkr 
I have tested it on Linux by replacing shortcut for arrow tool from ALT+a to ALT+r:
![screenshot_009](https://user-images.githubusercontent.com/332868/82472370-43e3ff00-9af2-11ea-9a67-a43ea66b952b.png)

Possibly, you assigned a shortcut which was already assigned to other action?

**Comment by yoSachinkr** [comment]
Well, I forgot that I was using a portable version of synfig, my bad. 
Now since I'd tried this, I did find out that changes made to the shortcuts , after closing synfig, reverts back to the defaults. So I changed the write permission of **accelrc** and now it's working.

**Comment by yoSachinkr** [comment]
And I found out there are not many functions listed in that file like grouping and duplicating layers etc. Is there any work around?

**Comment by Keyikedalube** [comment]
I'm branching my [single key shortcuts](https://synfig-docs-dev.readthedocs.io/en/latest/projects/shortcuts.html) proposal to a new issue for Hacktoberfest.

This issue addresses too many things at once :(

Also, I'm hiding my comments here so the dicussion is more directed to other issues.

**Comment by rodolforg** [comment]
Can this issue be closed?

**Comment by Keyikedalube** [comment]
Closing this issue because the above-linked PR kinda resolved the conflicting hotkeys bug this issue originally pointed at.

Please open new issues if some of the discussions/suggestions made above have been unmet. Also, be specific so it's easier for contributors to target feature XYZ instead of letting them guess what "other action shortcuts" mean.
