### ISSUE TITLE
It takes a long time for the Synfig studio to run

### ISSUE THREAD

**Issue by RezaSh13** [synfig/synfig#1340]
version synfigstudio-appimage  1.3.13-2

manjaro kde

`[lxclxd@Plasma ~]$ synfigstudio 

   synfig studio -- starting up application...

Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "appmenu-gtk-module"

(synfigstudio:32665): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(synfigstudio:32665): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(synfigstudio:32665): Gtk-WARNING **: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(synfigstudio:32665): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(synfigstudio:32665): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(synfigstudio:32665): Gtk-WARNING **: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(synfigstudio:32665): Gtk-WARNING **: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: Failed to load module "appmenu-gtk-module"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load default config file
synfig(32665) [05:20:08 PM] info: Starting Subsystem "Sound"
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Types"
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Rendering"
synfig(32665) [05:20:09 PM] info: rendering threads 2
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Modules"
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Layers"
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Targets"
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Importers"
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Cairo Importers"
synfig(32665) [05:20:09 PM] info: Starting Subsystem "Thread Pool"
synfig(32665) [05:20:09 PM] info: Loading modules from /tmp/.mount_8rwxPy/usr/etc/synfig_modules.cfg
synfig(32665) [05:20:09 PM] info: Loading modules from /tmp/.mount_8rwxPy/usr/etc/synfig_modules.cfg
synfig(32665) [05:20:09 PM] info: Loading lyr_std..
synfig(32665) [05:20:09 PM] info: Attempting to register "lyr_std"
synfig(32665) [05:20:09 PM] info: Found module "lyr_std"
synfig(32665) [05:20:09 PM] info: Success for "lyr_std"
synfig(32665) [05:20:09 PM] info: Loading lyr_freetype..
synfig(32665) [05:20:09 PM] info: Attempting to register "lyr_freetype"
synfig(32665) [05:20:09 PM] info: Found module "lyr_freetype"
synfig(32665) [05:20:09 PM] info: Initializing FreeType...
synfig(32665) [05:20:09 PM] info: Success for "lyr_freetype"
synfig(32665) [05:20:09 PM] info: Loading mod_geometry..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_geometry"
synfig(32665) [05:20:09 PM] info: Found module "mod_geometry"
synfig(32665) [05:20:09 PM] info: Success for "mod_geometry"
synfig(32665) [05:20:09 PM] info: Loading mod_gradient..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_gradient"
synfig(32665) [05:20:09 PM] info: Found module "mod_gradient"
synfig(32665) [05:20:09 PM] info: Success for "mod_gradient"
synfig(32665) [05:20:09 PM] info: Loading mod_particle..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_particle"
synfig(32665) [05:20:09 PM] info: Found module "mod_particle"
synfig(32665) [05:20:09 PM] info: Success for "mod_particle"
synfig(32665) [05:20:09 PM] info: Loading mod_example..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_example"
synfig(32665) [05:20:09 PM] info: Found module "mod_example"
synfig(32665) [05:20:09 PM] info: Success for "mod_example"
synfig(32665) [05:20:09 PM] info: Loading mod_gif..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_gif"
synfig(32665) [05:20:09 PM] info: Found module "mod_gif"
synfig(32665) [05:20:09 PM] info: Success for "mod_gif"
synfig(32665) [05:20:09 PM] info: Loading mod_imagemagick..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_imagemagick"
synfig(32665) [05:20:09 PM] info: Found module "mod_imagemagick"
synfig(32665) [05:20:09 PM] info: Success for "mod_imagemagick"
synfig(32665) [05:20:09 PM] info: Loading mod_magickpp..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_magickpp"
synfig(32665) [05:20:09 PM] info: Found module "mod_magickpp"
synfig(32665) [05:20:09 PM] info: Success for "mod_magickpp"
synfig(32665) [05:20:09 PM] info: Loading mod_mng..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_mng"
synfig(32665) [05:20:09 PM] warning: Unable to find module "mod_mng" (file not found)                                                                         
synfig(32665) [05:20:09 PM] info: Loading mod_noise..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_noise"
synfig(32665) [05:20:09 PM] info: Found module "mod_noise"
synfig(32665) [05:20:09 PM] info: Success for "mod_noise"
synfig(32665) [05:20:09 PM] info: Loading mod_filter..
synfig(32665) [05:20:09 PM] info: Attempting to register "mod_filter"
synfig(32665) [05:20:09 PM] info: Found module "mod_filter"
synfig(32665) [05:20:09 PM] info: Success for "mod_filter"
synfig(32665) [05:20:10 PM] info: Loading mod_ffmpeg..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_ffmpeg"
synfig(32665) [05:20:10 PM] info: Found module "mod_ffmpeg"
synfig(32665) [05:20:10 PM] info: Success for "mod_ffmpeg"
synfig(32665) [05:20:10 PM] info: Loading mod_bmp..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_bmp"
synfig(32665) [05:20:10 PM] info: Found module "mod_bmp"
synfig(32665) [05:20:10 PM] info: Success for "mod_bmp"
synfig(32665) [05:20:10 PM] info: Loading mod_dv..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_dv"
synfig(32665) [05:20:10 PM] info: Found module "mod_dv"
synfig(32665) [05:20:10 PM] info: Success for "mod_dv"
synfig(32665) [05:20:10 PM] info: Loading mod_png..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_png"
synfig(32665) [05:20:10 PM] info: Found module "mod_png"
synfig(32665) [05:20:10 PM] info: Success for "mod_png"
synfig(32665) [05:20:10 PM] info: Loading mod_ppm..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_ppm"
synfig(32665) [05:20:10 PM] info: Found module "mod_ppm"
synfig(32665) [05:20:10 PM] info: Success for "mod_ppm"
synfig(32665) [05:20:10 PM] info: Loading mod_openexr..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_openexr"
synfig(32665) [05:20:10 PM] warning: Unable to find module "mod_openexr" (file not found)                                                                     
synfig(32665) [05:20:10 PM] info: Loading mod_jpeg..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_jpeg"
synfig(32665) [05:20:10 PM] info: Found module "mod_jpeg"
synfig(32665) [05:20:10 PM] info: Success for "mod_jpeg"
synfig(32665) [05:20:10 PM] info: Loading mod_libavcodec..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_libavcodec"
synfig(32665) [05:20:10 PM] info: Found module "mod_libavcodec"
synfig(32665) [05:20:10 PM] info: Success for "mod_libavcodec"
synfig(32665) [05:20:10 PM] info: Loading mod_yuv420p..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_yuv420p"
synfig(32665) [05:20:10 PM] info: Found module "mod_yuv420p"
synfig(32665) [05:20:10 PM] info: Success for "mod_yuv420p"
synfig(32665) [05:20:10 PM] info: Loading mod_svg..
synfig(32665) [05:20:10 PM] info: Attempting to register "mod_svg"
synfig(32665) [05:20:10 PM] info: Found module "mod_svg"
synfig(32665) [05:20:10 PM] info: Success for "mod_svg"
synfig(32665) [05:20:10 PM] info: DONE
synfig(32665) [05:20:10 PM] info: Loading Basic Settings...
synfig(32665) [05:20:10 PM] info: Loading Plugins...
synfig(32665) [05:20:10 PM] info: Loading plugins from /tmp/.mount_8rwxPy/usr/share/synfig/plugins
synfig(32665) [05:20:10 PM] info:    Loading plugin: add-skeleton-simple
synfig(32665) [05:20:10 PM] info:    Loading plugin: lottie-exporter
synfig(32665) [05:20:10 PM] info:    Loading plugin: view-unhide-all-layers
synfig(32665) [05:20:10 PM] info: Loading plugins from /home/lxclxd/.config/synfig/plugins
synfig(32665) [05:20:10 PM] info: Init UI Manager...
synfig(32665) [05:20:10 PM] info: Init Dock Manager...
synfig(32665) [05:20:10 PM] info: Init State Manager...
synfig(32665) [05:20:10 PM] info: Init Main Window...
synfig(32665) [05:20:10 PM] info: Init Toolbox...
synfig(32665) [05:20:10 PM] info: Init About Dialog...
synfig(32665) [05:20:10 PM] info: Init Tool Options...
synfig(32665) [05:20:10 PM] info: Init History...
synfig(32665) [05:20:11 PM] info: Init Canvases...
synfig(32665) [05:20:11 PM] info: Init Keyframes...
synfig(32665) [05:20:11 PM] info: Init Layers...
synfig(32665) [05:20:11 PM] info: Init Parameters...
synfig(32665) [05:20:11 PM] info: Init MetaData...
synfig(32665) [05:20:11 PM] info: Init Library...
synfig(32665) [05:20:11 PM] info: Init Info...
synfig(32665) [05:20:11 PM] info: Init Navigator...
synfig(32665) [05:20:11 PM] info: Init SoundWave...
synfig(32665) [05:20:11 PM] info: Init Timetrack...
synfig(32665) [05:20:12 PM] info: Init Curve Editor...
synfig(32665) [05:20:12 PM] info: Init Layer Sets...
synfig(32665) [05:20:12 PM] info: Init Color Dialog...
synfig(32665) [05:20:12 PM] info: Init Gradient Dialog...
synfig(32665) [05:20:12 PM] info: Init DeviceTracker...
synfig(32665) [05:20:12 PM] info: Init ModPalette...
synfig(32665) [05:20:12 PM] info: Init Setup Dialog...
synfig(32665) [05:20:12 PM] info: Init Input Dialog...
synfig(32665) [05:20:12 PM] info: Loading Custom Workspace List...
synfig(32665) [05:20:12 PM] info: Init auto recovery...
synfig(32665) [05:20:12 PM] info: Loading Settings...
synfig(32665) [05:20:13 PM] info: Init Tools...
synfig(32665) [05:20:13 PM] info: Checking auto-recover...
synfig(32665) [05:20:14 PM] info: Done.

(synfigstudio:32665): Gtk-WARNING **: Allocating size to gtkmm__GtkWindow 0x1dc47b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

`

**Comment by raniaamina** [comment]
it alos happen to me on Debian Sid KDE

**Comment by raniaamina** [comment]
i found this: #682

**Comment by morevnaproject** [comment]
Please check updated builds:
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux64-a2ca6.appimage
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux32-a2ca6.appimage

**Comment by ice0** [comment]
Let's continue here: https://github.com/synfig/synfig/issues/1849

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
