### ISSUE TITLE
Windows: unable to start FFmpeg when installed into path with non-latin symbols 

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1341]
Synfig fails to find FFmpeg when Synfig is installed into path with non-latin symbols.

I.e. "D:\Программы\Synfig".

**Comment by morevnaproject** [comment]
Should be easy to fix in the same way as here - https://github.com/synfig/synfig/commit/024eac72aece88e4fd5b1a4c7809662854490c04

**Comment by FirasH** [comment]
https://github.com/synfig/synfig/blob/8081eb89d66dfdefb20d3d88ac2fd2e928e882df/synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp#L175-L185

**Comment by ice0** [comment]
Just checked. All works fine now.
