### ISSUE TITLE
TimeTrack not updated in 1.3.13

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1342]
**Synfig version & platform**:
1.3.13 (old TimeTrack)

**Issue description**:

I discovered one more critical bug in version 1.3.13 - TimeTrack not updated properly when user animates bones.

Video demonstration - https://youtu.be/IDRbC2RrD0w 

I would like to note, that 1.3.13 still uses old timetrack (while we have new TimeTrack in master).

This issue is blocking 1.4.0 release, again.

So, there are 2 choices here:
1. Fix old timetrack code in [v1.3.x branch](https://github.com/synfig/synfig/commits/v1.3.x)
2. or, Merge new TimeTrack into v1.3.x branch and ship it with 1.4.0. For that we need at least [this](https://github.com/synfig/synfig/issues/1266) issue solved.

@rodolforg @ice0 your opinions?

**Comment by rodolforg** [comment]
Ok, I checked it's a regression: it works on 1.2.2 .

However, I don't know if new timetrack is mature/tested enough.

Regarding the transparency issue, we could simply remove this visual effect if it is the only problem to merge it in 1.4.0 . Not the best solution, but it would behave like 1.2 branch does.

**Comment by rodolforg** [comment]
Does this problem appear only in 1.3.13 ? 1.3.12 it was fine?

**Comment by rodolforg** [comment]
> Regarding the transparency issue, we could simply remove this visual effect if it is the only problem to merge it in 1.4.0 . Not the best solution, but it would behave like 1.2 branch does.

Solved by PR #1344  ugh it took me 2 hours of work o.O

**Comment by rodolforg** [comment]
This is the culprit commit in 1.3 version: aeb01c14cafdb409f5a67a865a5ad8b5fa06b0b7

**Comment by rodolforg** [comment]
But, as a user, I'd love to user new timetrack :P

**Comment by morevnaproject** [comment]
> However, I don't know if new timetrack is mature/tested enough.

This is also what I worried about.
It worked well for me, but most of the time I use version 1.3.13, so it wasn't tested that much on my side.

We can ship new TimeTrack with 1.3.14, but if we will find issues in new TimeTrack functionality, then this can delay release of 1.4.0 even more (which is already delayed too much). And this might put additional stress to you, this is what I afraid.

I would like to finish 1.4.0 as soon as possible, and then make 1.4.1 release with features from master branch.

> Solved by PR #1344 ugh it took me 2 hours of work o.O (just coding the drawing…)

Awesome! Thank you so much!

**Comment by rodolforg** [comment]
> then this can delay release of 1.4.0 even more (which is already delayed too much).

Indeed.

> I would like to finish 1.4.0 as soon as possible, 

So, what is really missing in order to release it? :)
Shouldn't we prioritize issues and PR related to 1.4 milestone and GSOC?

**Comment by morevnaproject** [comment]
> So, what is really missing in order to release it? :)
> Shouldn't we prioritize issues and PR related to 1.4 milestone and GSOC?

They are on my priority last weeks, and thanks to you and @ice0  they are solved very quickly! ^__^

The issues blocking the release are ones **[in v1.4.0 milestone](https://github.com/synfig/synfig/milestone/3)** which are **marked with "Critical" label**. All other issues in v1.4.0 milestone can be postponed for latter releases. ^__^

Right now, for this solution I am testing your solution given in https://github.com/synfig/synfig/issues/1342#issuecomment-613096778

Also, I am waiting for someone to approve #1334 (which will close #1307).
And I waiting for #1214 to be finished.

After that I can release 1.3.14 and send it to user for one more testing round.

If we will not find critical issues in it, then it will become 1.4.0. ^__^

**Comment by morevnaproject** [comment]
My logic in defining issue as "critical" or "not critical":
- if issue was existing in previous stable release, then it is "not critical".
- if issue was **not** existing in previous stable release, then it is "critical".

In other words, my logic is that v1.4.0 should be not worse than 1.2.2. It shouldn't introduce regressions. ^__^

**Comment by morevnaproject** [comment]
> This is the culprit commit in 1.3 version: aeb01c1
> More specifically : this line deletion ...

It worked! Thank you so much for solution! ^__^

**Comment by rodolforg** [comment]
Did you add this commit to master too?
I think you should do it, because that timetrack cellrenderer is used on Params and Library panels too
