### ISSUE TITLE
Sound panel should list available audio layers

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#1346]
The Sound panel lets user choose an audio from filesystem by browsing instead of show a combobox with the audio layers the scene has.

Once user selects a sound layer, it should automatically obey the delay parameter value of this layer and set it in sound panel.

A possible problem is if user uses multiple sound layers with same name. The combobox contents would have "identical" items (delay parameters may be different).

It should keep tracking scene for sound layers additions and removals and renames.

**Comment by morevnaproject** [comment]
Great addition! I would love to have that functionality in Synfig! ^__^

**Comment by rodolforg** [comment]
Any suggestion for the repeated layer names?
