### ISSUE TITLE
Dropdowns for some parameters are still activated with double-click

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1349]
After merge of #1325 and #1337 we have all parameters available for editing after a single click.

Still I found in two places it is still required to do 2 clicks to go into editing mode.

1. Canvas parameter of Group Layer:
![screenshot_006](https://user-images.githubusercontent.com/332868/79239236-86cf0900-7e9a-11ea-8c32-a4f1ed0ea705.png)

2. Parent parameter of any Bone:
![screenshot_008](https://user-images.githubusercontent.com/332868/79239249-8c2c5380-7e9a-11ea-943a-17298bc1f4a5.png)

@rodolforg can  you please take a look when you have time? ^__^

**Comment by rodolforg** [comment]
Oh... they aren't enum parameters :) that's why they're missing

I'll take a look later

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
