### ISSUE TITLE
Z depth in grouped layers does nothing when layers are above and below main layers.

### ISSUE THREAD

**Issue by Michael82548** [synfig/synfig#1362]
v1.3.13 Dev build

EXTREMELY annoying issue
![image](https://user-images.githubusercontent.com/53535277/79496496-379ceb80-7ff4-11ea-8ccc-56f462e1af70.png)
When I tell this to go down in layers it will not go down correctly. I want to group 2 layers above and below the main layers like this:
![image](https://user-images.githubusercontent.com/53535277/79496674-76cb3c80-7ff4-11ea-8283-e9dadfd0a02b.png)
But It won't work! I can't group layers like that. It's either above or below the main layers. Any fix for this?

**Comment by Keyikedalube** [comment]
Grouping layers isolate them from the rest so changing z-depth only affects those layers inside the group.

Your second screenshot is the correct way even though character parts are no longer organized in groups.

**Comment by Keyikedalube** [comment]
Closing this because I feel the above comment already answered why grouping works that way.
