### ISSUE TITLE
Allow user to stop the Rendering process in Synfig Studio

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1366]
**Synfig version & platform**:
Master: ccf39ec

**Issue description**:
1. Open any animation project
2. Go to: `File > Render...` and start to render your animation to the output target

Once the rendering process is started, it is not possible to stop it from Synfig Studio.

It would be very useful to have a button somewhere in the `Info` Panel near to the progress percentage bar to stop it:
![Stop_rendering_button](https://user-images.githubusercontent.com/6705690/79641544-6ce23e80-8198-11ea-8bec-65f26105134c.png)

This feature would be used for example in case a rendering is started by mistake or with wrong options.

**Comment by rodolforg** [comment]
Could you check if t's possible to stop rendering from the last button of workarea toolbar (ie at right side)?
![Captura de tela de 2020-04-18 13-39-49](https://user-images.githubusercontent.com/1323987/79643656-6c3aaf80-817a-11ea-9ee9-c793bd89f075.png)

If so, we could make another instance of this button next to render progressbar

**Comment by FirasH** [comment]
> Could you check if t's possible to stop rendering from the last button of workarea toolbar (ie at right side)?
> ![Captura de tela de 2020-04-18 13-39-49](https://user-images.githubusercontent.com/1323987/79643656-6c3aaf80-817a-11ea-9ee9-c793bd89f075.png)
> 
> If so, we could make another instance of this button next to render progressbar

AFAIK it does not.

**Comment by rodolforg** [comment]
You can stop rendering via `RenderSettings::async_renderer` property. This object has a `stop()` method.
The "Stop Render" button may be next of rendering status progressbar Info panel.

**Comment by rodolforg** [comment]
By the way, starting to render while rendering hangs Synfig…

**Comment by rodolforg** [comment]
@FirasH  Do you want to try to implement it?

A new `Gtk::Button` should be placed right of the `Gtk::ProgressBar` `render_progress` of `Dock_Info`.
Its `signal_clicked` should call the stop() method of `async_renderer` of the (strange enough) `RenderSettings` dialog. (IMO the renderer should be in `App`…)

**Comment by FirasH** [comment]
@rodolforg sure, I can give it a try

**Comment by FirasH** [comment]
@rodolforg I'm trying to connect a button from [dock_info.cpp](https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/docks/dock_info.cpp) to a method in [render.cpp](https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/render.cpp) where `async_renderer` is defined and I could stop it with `async_renderer->stop()` as you suggested.

The issue is that in `dock_info.cpp` I cannot reference `async_renderer` because it's a private member of `RenderSettings`:
https://github.com/synfig/synfig/blob/8b93aa1c2baf37ca687010c617db988632df79fb/synfig-studio/src/gui/render.h#L90

Any idea how to tackle this type of things? I guess it's a scenario you encounter a lot in coding...

**Comment by rodolforg** [comment]
You could provide access by creating a new `etl::handle<AsyncRenderer> get_async_renderer() const` method :)

**Comment by FirasH** [comment]
> You could provide access by creating a new `etl::handle<AsyncRenderer> get_async_renderer() const` method :)

Sounds so easy to read... How did I not think about it :expressionless:
Thank you!
