### ISSUE TITLE
16-bit PNG files displayed incorrectly

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1371]
**Synfig version & platform**:
1.3.12, 1.3.13 & master branch

**Issue description**:
Sample file - 
![file 00060](https://user-images.githubusercontent.com/332868/79840702-778f1480-83e0-11ea-8035-aada62b5861f.png)

File info: PNG image data, 480 x 270, **16-bit**/color RGBA, non-interlaced

When imported in Synfig it looks like this:
![screenshot_002](https://user-images.githubusercontent.com/332868/79840716-7eb62280-83e0-11ea-832e-8f01307c9f8c.png)

In Synfig 1.3.11 and 1.2.2 works fine.

This is only for 16-but PNG files, 8-bit files are okay,

**Comment by rodolforg** [comment]
related to #1160 ?

Git bisecting…

**Comment by rodolforg** [comment]
Ironically, this is pointed as culprit 1c09d1652f6a45eb6bba258454af07dfb8af45ef

**Comment by morevnaproject** [comment]
> Ironically, this is pointed as culprit 1c09d16

Awesome! Thank you for revealing this!
Then,  I can revert this commit in 1.3.x branch. The issue will remain in master branch and can be solved without a hurry.

**Comment by morevnaproject** [comment]
Woops! And right at the moment when I posted last comment you submitted #1375. Thank you so much! ^__^
