### ISSUE TITLE
Improve look of Warning dialog

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1376]
Synfig displays warning dialog when opening old files and in some other cases (i.e. to inform user about missing images).

This dialog is ugly, note the empty space in this case (screenshot from #1334  -
![warning](https://user-images.githubusercontent.com/332868/80128011-50db0480-85bf-11ea-9bfa-6c8571fffc33.png)

It would be nice to improve it! ^__^

**Comment by FirasH** [comment]
If someone wants to contribute, here is the function used to generate this type of dialogs:
https://github.com/synfig/synfig/blob/40593a09e815c08229334bce57001c69ca0d1607/synfig-studio/src/gui/app.cpp#L3535-L3581

**Comment by Keyikedalube** [comment]
A single warning message would suffice

Because I opened my one of my old files and happened to stumble upon multiple repeating messages like this

![Screenshot_2020-04-29_10-44-31](https://user-images.githubusercontent.com/24214509/80562879-b89daf00-8a06-11ea-910c-994bc4a0191c.png)

**Comment by Keyikedalube** [comment]
Thanks, @FirasH for the pointer :)

Here's my two possible solutions:
1. Use `property_wrap()` for label
![Screenshot from 2020-05-27 13-53-19](https://user-images.githubusercontent.com/24214509/83001407-521da800-a029-11ea-8dee-71517949536c.png)

2. Use `Gtk::Grid` instead of `Gtk::ScrolledWindow`
![Screenshot from 2020-05-27 13-59-54](https://user-images.githubusercontent.com/24214509/83001422-55189880-a029-11ea-887b-e4615dad935d.png)

Me, personally, I prefer option 2 because I don't have to explicitly set size request. Grid takes care of the size based on the contents of label. Whereas, ScrolledWindow size needs to be tweaked manually with code.

Maybe I could do a PR on this issue?

**Comment by FirasH** [comment]
@Keyikedalube I prefer option 2 as well.

If it's resizing itself depending on its content it should be good also for longer warnings.
Do you have an example of how it looks with a long warning message?

**Comment by Keyikedalube** [comment]
@FirasH I don't have any synfig file that will trigger longer warnings.

Maybe send me a sample sif file here...?

**Comment by Keyikedalube** [comment]
Never mind @FirasH 

I just did a quick hack with the same warning message:
# Screenshot 1
![Screenshot from 2020-05-27 17-02-00](https://user-images.githubusercontent.com/24214509/83014547-8e0e3880-a03c-11ea-83d2-b8261100fcf6.png)
# Screenshot 2
![Screenshot from 2020-05-27 17-05-13](https://user-images.githubusercontent.com/24214509/83014559-95354680-a03c-11ea-9921-d44fd638dd96.png)

Both screenshots had dialog resizable property turned off. It's nice to see GTK taking care of dialog UI size.

**Comment by FirasH** [comment]
Nice work 👍

Is it possible to add some margins on the left/right of the `Gtk::Grid`?

**Comment by Keyikedalube** [comment]
IDK

All I can think of right now is using space(s)

**Comment by Keyikedalube** [comment]
Got the solution:
```c++
grid.set_border_width(10)
```
![Screenshot from 2020-05-27 19-59-03](https://user-images.githubusercontent.com/24214509/83033441-bc980d80-a054-11ea-9634-473197a2cca6.png)

**Comment by rodolforg** [comment]
All Gtk widgets have margins. Gtk::Widget::set_margin_(top|bottom|left/start|right/end)

**Comment by rodolforg** [comment]
And Containers  have also border like you used :D. Sorry ;)

**Comment by Keyikedalube** [comment]
Thanks @rodolforg 
I see `start` and `end` are needed only

set_border_width() sets to all sides of a widget. In this case, I'm unnecessarily adding extra margins on top and bottom.

**Comment by Keyikedalube** [comment]
![Untitled](https://user-images.githubusercontent.com/24214509/83040683-27e5dd80-a05d-11ea-8a3a-3113b05443e6.png)
1. set_border_width()
2. set_margin_start/end()

**Comment by FirasH** [comment]
2nd is better in my opinion 👍

**Comment by morevnaproject** [comment]
Hi guys! Can anyone check the case if there are 30+ warnings? (we might have situation like that when opening old files with many missing images)

Like this one - [missing-images.sifz.zip](https://github.com/synfig/synfig/files/4712273/missing-images.sifz.zip)

**Comment by FirasH** [comment]
> Hi guys! Can anyone check the case if there are 30+ warnings? (we might have situation like that when opening old files with many missing images)
> 
> Like this one - [missing-images.sifz.zip](https://github.com/synfig/synfig/files/4712273/missing-images.sifz.zip)

The warning dialog is higher than my screen:
![missing_images](https://user-images.githubusercontent.com/6705690/83440666-9a800000-a445-11ea-81a3-c553aae3e581.png)

**Comment by Keyikedalube** [comment]
Same output confirmed

Just like the same issue with old canvas warning message #1391
Can multiple missing images implement a similar solution like that?

**Comment by ice0** [comment]
> Can multiple missing images implement a similar solution like that?

I think we need string numbers to understand which parts of the file needs attention.
Maybe push the text widget into a scrollable container?

**Comment by morevnaproject** [comment]
> I think we need string numbers to understand which parts of the file needs attention.

I agree.

> Maybe push the text widget into a scrollable container?

Good idea.
But we had scrolled window before #1450 and it was looking not good with a small amount of warnings (see initial post in this thread).

Maybe it is possible to add scrolled window conditionally?

**Comment by morevnaproject** [comment]
> The warning dialog is higher than my screen:

@FirasH I wonder how you managed to create such screenshot :rofl:

**Comment by Keyikedalube** [comment]
>     1. Use `property_wrap()` for label

And set the scrolled window size from (400, 300) to (400, 200)
To reduce those blank empty spaces

Apart from the repeating message
`Layer 'import' rejected value for parameter 'filename'`
Doesn't clearly specify what file actually is causing the error (missing)
ie., it'd be nice if the layer name **file0000.png** is also indicated

**Comment by morevnaproject** [comment]
> it'd be nice if the layer name file0000.png is also indicated

Yes, this is absolutely needed!

**Comment by FirasH** [comment]
I'll take a look at this

**Comment by FirasH** [comment]
Made some experiments, here is the current result.

Warning old file (very short):
![old_file](https://user-images.githubusercontent.com/6705690/84600318-a40f5c00-ae78-11ea-997e-5293e8f7425d.png)
Under a certain height the scrollbar is not visible.

Warning missing images (very long):
![long_warning](https://user-images.githubusercontent.com/6705690/84600325-b12c4b00-ae78-11ea-88c2-9d57e99b05da.png)

If the label is larger than current dialog width the label is wrapped, if width/height is increased the message is resized accordingly. This means that the horizontal scrollbar is never in use.

**Comment by Keyikedalube** [comment]
Is there a way to also indicate layer name ie., file0000.png ..?

Because we are showing the text content to the user. It'd be more useful if he knows what layer is causing the problem. Reading a very lengthy repeating message doesn't really help the user at all. If this is also implemented warning dialog would be more meaningful++ than the current one we have right now :)

**Comment by FirasH** [comment]
> @FirasH Is there a way to also indicate layer name ie., file0000.png ..?
> 
> Because we are showing the text content to the user. It'd be more useful if he knows what layer is causing the problem. Reading a very lengthy repeating message doesn't really help the user at all. If this is also implemented warning dialog would be more meaningful++ than the current one we have right now :)

I didn't really dive into that problem, but I would suggest to separate the 2 issues (dialog part and message part).

@Keyikedalube I'll open a new issue to keep track of that!

**Comment by morevnaproject** [comment]
> If the label is larger than current dialog width the label is wrapped, if width/height is increased the message is resized accordingly. This means that the horizontal scrollbar is never in use.

I like this! ^__^
