### ISSUE TITLE
Multiple repeated warning messages when opening old file

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#1380]
When opening an old file (2017) https://wiki.synfig.org/images/3/38/Crosshair-leg.zip
I got this warning dialog:
![Captura de tela de 2020-04-26 09-36-33](https://user-images.githubusercontent.com/1323987/80307770-95be9100-87a1-11ea-9bd3-39f73de5a123.png)

**Comment by FirasH** [comment]
Confirmed with master 40593a0
