### ISSUE TITLE
Circle deforms with Skeleton

### ISSUE THREAD

**Issue by eucedajosue** [synfig/synfig#1384]
Windows Version 1.2.2
Circle tool deforms when link to skeleton and move with skeleton

![Captura](https://user-images.githubusercontent.com/17987417/80448419-7d519200-88d9-11ea-8742-9bb31f809aef.PNG)

**Comment by rodolforg** [comment]
It seems you linked bone to some of circle vertices.
Coul you post a demonstration file?

**Comment by eucedajosue** [comment]
File attached
-Create a circle with Circle tool
-Group ouline and region
-add a skeleton
-right clic con the group and clic on Select All Child Layers
-ctr+a to select all vertex
-ctr + clic on the skeleton
right clic con the skeleton and Link to Bone

[Synfig Animation 1.zip](https://github.com/synfig/synfig/files/4559686/Synfig.Animation.1.zip)

**Comment by morevnaproject** [comment]
> -right clic con the group and clic on Select All Child Layers
You do not have to do this step.
You need to have group selected (not its content) and link it to bone.

**Comment by eucedajosue** [comment]
> > -right clic con the group and clic on Select All Child Layers
> > You do not have to do this step.
> > You need to have group selected (not its content) and link it to bone.

yes, i have to. if not, no Link to bone option is displayed.

Trying solutions, a found: 

1. before you link to bone, edit the origin set: 0px,0px, then i have to move the circle to the desired position. 

2.  select All Handles, right clic on any vertex and select the option: Merge Tangents Radius.

after this you can link to bone and the results will be as espected. only happen with Circle tool.

**Comment by rodolforg** [comment]
No, you don't have to :)
Instead of selecting children layers and their vertices, just select the Group origin (the green handle) to link to bone.
I think that's what morevna meant.

**Comment by eucedajosue** [comment]
> No, you don't have to :)
> Instead of selecting children layers and their vertices, just select the Group origin (the green handle) to link to bone.
> I think that's what morevna meant.

Great, that solves de problem. I was fallowing the steps in documentation: https://wiki.synfig.org/Doc:Basic_Bone_Tutorial#Attaching_the_bones

**Comment by morevnaproject** [comment]
One more reason to update the docs! ^__^

**Comment by rodolforg** [comment]
Polygon and splines by default have their origins at (0,0) as pointed as
solutuon for circle region by OP

Em ter, 5 de mai de 2020 13:12, Konstantin Dmitriev <
notifications@github.com> escreveu:
