### ISSUE TITLE
Multiple warning instead of one (about opening old version of file)

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1385]
Sample file (works with any other file which has multiple groups) -
[devochka.sifz.zip](https://github.com/synfig/synfig/files/4543763/devochka.sifz.zip)

When opened in Synfig (latest master or 1.3.14) it displays warning multiple times:
![screenshot_002](https://user-images.githubusercontent.com/332868/80454659-95b2c280-8954-11ea-8641-e132f09384e0.png)

**Comment by FirasH** [comment]
#1380

**Comment by morevnaproject** [comment]
@FirasH Oh, sorry, missed it. ^__^
