### ISSUE TITLE
Some labels in dialog buttons are not correctly aligned

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1390]
**Synfig version & platform**:
Synfig 1.3.13 on all platforms

**Issue description**:
In some dialogs the text labels are not correctly aligned.
For example in `Help > About Synfig Studio`, the button `Close` is aligned to the top:
![button_label_alignment](https://user-images.githubusercontent.com/6705690/80622536-3b475e00-8a49-11ea-8534-aacfc70c4917.png)

**Comment by Keyikedalube** [comment]
Rodolforg explained it here https://github.com/synfig/synfig/issues/1061#issuecomment-576243244

Just uncomment that custom GTK theming code and misaligned layouts will be corrected

But someone's got to implement the styling class for toolbars first
