### ISSUE TITLE
File corruption: Copy-paste layers with exported values from one file to another

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1393]
There is a very common situation when user can get his file corrupted by simply copy-pasting layers from one file to another. This happens if layer contains exported values (note that bones are exported values too!).

Steps to reproduce this situation:
1. Launch Synfig and create new file.
2. Create a simple Circle Layer.
3. Select Circle Layer, right-click its Radius parameter and select "Export".
4. Enter name for exported value, i.e. "test". Click Export.
5. Save file as "file1.sifz"
6. Hit Ctl+C to copy circle layer to clipboard.
6. Create a new file in other tab.
7. Hit Ctrl+V to paste circle from clipboard. Circle will appear on workspace. Notice, that layer is copied, but it is still references exported value from "file1.sifz"
8. Save file as "file2.sifz"
9. Quit Synfig.
10. Now remove (or rename) "file1.sifz".
11. Launch Synfig and try to open "file2.sifz".
12. Error:
![screenshot_001](https://user-images.githubusercontent.com/332868/80699264-df8eda80-8b05-11ea-934b-7c4702fdffe9.png)

@rodolforg @ice0 @FirasH  I think this is a top-priority issue to solve for next stable release (1.4.1 or 1.6.0).

What should be done here:

1. Change how Synfig deal with pasting layers when layer has exported values.
2. Change how Synfig handles situations with broken links to exported values in external documents.

**Comment by morevnaproject** [comment]
Broken files reported by users regularly.
Examples: #786, #1387

**Comment by morevnaproject** [comment]
> 1. Change how Synfig deal with pasting layers when layer has exported values.
> 2. Change how Synfig handles situations with broken links to exported values in external documents.

I think (1) should be a scope of this issue. (2) should be submitted a separate issue.

**Comment by morevnaproject** [comment]
> 1. Change how Synfig deal with pasting layers when layer has exported values.

Here is my proposal for solving this - https://synfig-docs-dev.readthedocs.io/en/latest/projects/copy-paste-exported-values.html

**Comment by Gilraiser** [comment]
Hello, I would like to show you an error that has to do with the topic. Here I present a video and two example files of how bones made are corrupted when copied to another file.

Original file:
[example-01.sif.zip](https://github.com/synfig/synfig/files/4663967/example-01.sif.zip)

Copied file:
[example-02.sifz.zip](https://github.com/synfig/synfig/files/4663965/example-02.sifz.zip)

Video with the demonstration:
https://www.youtube.com/watch?v=aTBuhxQpS1c&feature=youtu.be

I hope the information is useful. Thank you

**Comment by rodolforg** [comment]
@Gilraiser  Sadly a long-time known issue https://github.com/synfig/synfig/issues/453
I'm trying to investigate it, but I'm confuse how skeletons work in Synfig ;)

**Comment by Gilraiser** [comment]
I wish I could help more. I know it must be very complex. Thank you.

**Comment by morevnaproject** [comment]
I suggest to split this issue into multiple easy steps.

1. When "paste" command is invoked - check if pasted data references any exported elements. If yes - then display warning message in console.
2. Replace warning in console with a dialog box, which shows a message: "The pasted data contains layers, which still reference exported values from original files. That means your current file will depend on original file and might become unreadable if you delete original file. Do you still want to paste? [Yes] [No]"
3. Improve warning dialog - display a list of exported values, which are referenced by pasted layers.

I think those 3 steps are easy enough to start on gradually solving this issue. I can provide further steps later, if needed. ^__^

**Comment by rodolforg** [comment]
I started to work on this issue today, and then it raised me a doubt:
What if an exported value node has links for other  exported valuenodes.
  I just list the 'top' valuenode?

**Comment by rodolforg** [comment]
The conflict is when there are two different types of valuenode, right? Like "Add" vs. "Scale"

**Comment by ice0** [comment]
@rodolforg Hi!
@morevnaproject got sick, he will answer as soon as he gets better.

**Comment by rodolforg** [comment]
Oh, I wish he gets better soon.

**Comment by ice0** [comment]
> I think we need a small icon to a value node is from an external canvas.

I agree. A visual difference is required.

**Comment by morevnaproject** [comment]
> What if an exported value node has links for other exported valuenodes.
> I just list the 'top' valuenode?
> 
> Example: I have a skeleton layer and one of its bones is exported. The origin of this exported bone is exported too.
> When I copy'n paste this layer, I warn about the bone export only, or both valuenodes?

I think we should list both valuenodes. Can we achieve that? 

Let's think about the following situation:
1. We have a skeleton layer and one of its bones is exported (valueA)
2. The origin of this exported bone is exported too (valueB)
3. User copies skeleton layer to other document
4. The dialog displays both values "valueA" and "valueB".
5. User chooses NOT to copy "ValueA" (bone). So, it will be linked instead.
6. ...but that means we cannot copy "ValueB"! Because it belongs to "ValueA", which cannot be changed (as it is linked, not copied).

How can we solve this?

**Comment by morevnaproject** [comment]
> How can we solve this?

Okay, I figured what we should do.

In the situation described in my previous comment user chooses NOT to copy "ValueA" (bone).
So, ValueA is linked from source file AND it depend on ValueB from source file too (because ValueA in source file is depends on ValueB).

So, in this exact situation it is really doesn't matter if user chooses to copy ValueB or not (because if ValueA is not copiedthen ValueB not directly included into any parameter of copied layer(s)).

But! There could be the following situation: ValueB is linked to some other parameter of the copied layer. For example:
- We have a skeleton layer and one of its bones (Bone1) is exported (valueA)
- The origin of this exported bone is exported too (valueB)
- The Opacity Parameter of this Skeleton Layer is linked to valueB too.

So, when user copy Skeleton Layer to another file and chooses NOT to copy "ValueA" AND copy "ValueB", then we will get the following result:
- Bone1 is linked to ValueA from source file (this ValueA is depends on ValueB from the same source file)
- Opacity Parameter is linked to ValueB, which is COPIED to destination file.

So, as result we will get following:
- In source file: Bone1 depends on Opacity parameter of the same Skeleton Layer
- In destination file: Bone1 depends on Opacity parameter of Skeleton Layer from source file

I think this is logical behavior.

**Comment by rodolforg** [comment]
So, in this case, the original link between Bone1 Opacity and Bone1 Origin will be lost on destination file.
Is it okay?

**Comment by rodolforg** [comment]
> I think we should list both valuenodes. Can we achieve that?

Yes, it.

**Comment by morevnaproject** [comment]
> I think we need a small icon to a value node is from an external canvas.
> The following icon is used to indicate a layer parameter is a value node (in Parameter panel):
> ![valuenode_icon](https://user-images.githubusercontent.com/1323987/113003821-76ff1200-9149-11eb-8535-0c69e6dc1aba.png)
> How to change it for indicate this difference?

We have path in "Source file" column, maybe this is enough to indicate that the value node is from an external canvas?

![screenshot_015](https://user-images.githubusercontent.com/332868/120012616-ee4a0880-c009-11eb-8e43-0ac8aa7b6796.png)

**Comment by rodolforg** [comment]
The link icon there says that value node will be copied and linked to existent valuenode in target file.

It is somehow confusing :P

**Comment by rodolforg** [comment]
@morevnaproject  The link icon there says that value node will be copied and linked to existent valuenode in target file.

It is somehow confusing :P

**Comment by rodolforg** [comment]
Hm… I think I know how to differentiate it:
- When it will be linked to external file, use the Link icon
- When it will be copied, but 'linked' to an existent exported valuenode, we use (deprecated) Connect/Plug icon: this is the way we represent the action to link to an exported value anyway

What do you think?

---

Regarding the copying about external nested value nodes, I think I'll change your proposal. Repeating your example:

-     We have a skeleton layer and one of its bones (Bone1) is exported (valueA)
-     The origin of this exported bone is exported too (valueB)
-     The Opacity Parameter of this Skeleton Layer is linked to valueB too.

Case 1: User chooses to copy the external "valueA". So user can still freely decides about copying or not the external "valueB".

Case 2: User chooses to link to the external "valueA". As external "valueA" depends on external "valueB", user can't choose anything about the action for "valueB" – it should be automatically linked too.

**Comment by morevnaproject** [comment]
> I think we need a small icon to a value node is from an external canvas.
> The following icon is used to indicate a layer parameter is a value node (in Parameter panel):
> ![valuenode_icon](https://user-images.githubusercontent.com/1323987/113003821-76ff1200-9149-11eb-8535-0c69e6dc1aba.png)
> How to change it for indicate this difference?
> Or doesn't it worth?

@rodolforg 
I've just re-read your comment and realized that I possibly misinterpreted your question.
Do you mean indication in Parameters Panel, right? -
![screenshot_004](https://user-images.githubusercontent.com/332868/129186179-a53df109-99e8-4222-a760-179b0757d20e.png)

**Comment by morevnaproject** [comment]
> Regarding the copying about external nested value nodes, I think I'll change your proposal.

I have tested how your proposal works in current implementation and it looks like good solution to me!
