### ISSUE TITLE
"View" - "Toolbar" is not effective for all visible canvases

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1394]
**Expected behavior:**
"View" - "Toolbar" should show/hide toolbar in all canvas windows.

**Bug description:**
This doesn't happens when you have 2 (or more) canvas windows visible at the same time.
Illustration - https://www.youtube.com/watch?v=rzsEBRC6bjo

Note: This happens because in current code the toolbar state is updated when canvas window is switched. Instead, it would be better to improve code, which is executed when user selects "View" - "Toolbar" menu item - the code should  iterate all opened instances (canvas views) and update their toolbar state.

@ARYA-BHARDWAJ can you take a look o this issue, please? ^__^

**Comment by ARYA-BHARDWAJ** [comment]
Yes, I will work on this.

**Comment by morevnaproject** [comment]
Great! Assigned then.

**Comment by morevnaproject** [comment]
Closed via #1395.
