### ISSUE TITLE
New plugin does not work to export and import

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#1397]
**Synfig Studio 1.5.0 production build. Archlinux 64x**:

**Issue description**:
When installing the new plugin made by Mattia Basaglia in the way indicated in the documentation (https://synfig.readthedocs.io/en/latest/plugins.html), whether you want to export or import, the following message is presented of mistake:
![Captura de pantalla_2020-05-04_10-23-54](https://user-images.githubusercontent.com/45057390/81003564-b1184480-8e10-11ea-98c8-0f025f67c3e8.png)
Clarifying that I previously installed the python-lottie framework as indicated by Mattia's gitlab (http://mattia.basaglia.gitlab.io/python-lottie/index.html). Including adding to the plugin folder the lib / lottie folder as indicated for the synfig scrip.

I hope the information is helpful
Thank you very much for the excellent work.

**Comment by ice0** [comment]
@mbasaglia Can you take a look?

**Comment by mbasaglia** [comment]
It was an issue that should already be fixed, try downloading the latest version of my plugin: http://mattia.basaglia.gitlab.io/python-lottie/downloads.html

**Comment by Gilraiser** [comment]
Hi Mattia, I checked more thoroughly and the only thing that allows me is to import into svg with very good results. The rest does not allow me to import or export.

It is an excellent plugin. Thanks for sharing. I hope the information is helpful.

**Comment by mbasaglia** [comment]
dunno, it works fine for me, maybe send the files that don't work

probably it's better to create a ticket on the tracker for my framework https://gitlab.com/mattia.basaglia/python-lottie/-/issues (It also allows attaching more file types than github)

**Comment by Gilraiser** [comment]
@mbasaglia Made some changes to how the plugin is packaged. Everything works perfect now. Thank you very much again Mattia.
