### ISSUE TITLE
Width Points Get Glitched Out when Their Positions Were Changed (But On Unlooped Adv. Outlines Only)

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#1401]
**Synfig version & platform**:
v1.3.13 (Portable) on Win 10
and also found in v1.3.14 (also Portable) that i got from here-> #536 

**Issue description**:
Note:
as far as we can find, this only occurs on unlooped advanced outlines.
The looped lines (like from shapes layers) wont have this issue for some reason.
(thanks to rodolforg for this finding on this comment -> https://github.com/synfig/synfig/issues/1401#issuecomment-624841672)

To simplify, width points keep glitching out everytime i try to move their positions.

How to reproduce:
1. Create an **Unlooped** Advanced Outlines
2. Check "Show Width Points" and select the advanced outline layer
3. Try to move its width points' (the center ones) positions

Doesn't matter how i do it, whether using mouse-dragging or arrow keys, those points will jump to random positions within their designated line. Though as for the arrow keys one, sometimes it'll nudge properly as they should, but mostly it's the same jumpy glitch thing.

Edit: title and description has been updated for clearer explanation on this issue

**Comment by FadhilKwan** [comment]
um.... a bit of update

This somehow also happened on 1.3.12 (also Portable version) as well, and now i'm confused...

I did try changing the width points' positions on v1.2.2 that are currently installed on my laptop, and this issue didn't occur at all.

Can someone confirm if this issue happened to any others? Because i feel like there's a chance that this is only happening on my device.

**Comment by rodolforg** [comment]
I can't reproduce it.
What am I doing different of you?
https://youtu.be/C5UThpNjZWk

**Comment by FadhilKwan** [comment]
> I can't reproduce it.
> What am I doing different of you?
> https://youtu.be/C5UThpNjZWk

Hmmm~...?

Okay, so i checked your clip, and...
......ah, i see! (maybe?)

Anyway, try unlooping the circle, then moving the width points once again

**Comment by ebarranco** [comment]
@rodolforg @FadhilKwan I can reproduce this problem, the width point snap in random places when I try to change its position.

**Comment by ebarranco** [comment]
...It  also happens with non closed outlines made with drawing and Spline tool @rodolforg .

**Comment by rodolforg** [comment]
Ok, I could reproduce only in unlooped cases.
The last spline segment is making trouble s

**Comment by FadhilKwan** [comment]
> ...It also happens with non closed outlines made with drawing and Spline tool @rodolforg .

Okay, so it's confirmed after all. Thank goodness it wasn't my machine's fault.


> Ok, I could reproduce only in unlooped cases.

Yup, same here as well. I did try the ones from your clip (the circle ones) right after, and the width points did move properly.
Also yeah, the drawing that i used to test the width points is a simple S-shape (which is obviously unlooped). And i forgot to mention that one, sorry ._.v

Now that the issue has been confirmed, i can finally edit some of the issue's description and title for better explanation on it.

**Comment by rodolforg** [comment]
@morevnaproject @ice0 blocking issue to 1.4 :(

**Comment by rodolforg** [comment]
It works fine in 1.3.11
It stopped to work in 1.3.12

**Comment by morevnaproject** [comment]
This problem is result of reworked outlines (same origin as here - https://github.com/synfig/synfig/issues/1284).

Note, that when you try to put widthpoint closer to start of outline, then the jumping gets smaller.

Also, note that if spline constructed of 4 points, you can't drag beyound 3rd point (Synfig "thinks" that 3rd point is an end of spline).

![screenshot_004](https://user-images.githubusercontent.com/332868/81323170-27da6980-90bf-11ea-81c3-7233a08065d9.png)

**Comment by rodolforg** [comment]
Argh. I can't find the problem…

**Comment by FadhilKwan** [comment]
I decided to check this issue again (in 1.3.14 portable) and found something quite... interesting.

It seems that the jumps are not random, but affected in some way.

It's a bit complicated to explain, but much easier to notice if you play with this problem with 3 vertex point-line (or 2 line segments).

When i drag the width points to a value, and let it go, that point will jump to the double of it's value (with a little decimal rounding).

Example, dragging and dropping the width point to value 0.300 and letting it go will make it jump to value ~0.600 (or a little more or less, depends on the rounding)

Then what if i drop it on a value somewhere over 0.500? Most likely the same as well.

Then what about 4 vertex point-line (3 line segments)?
It's a little weird, the points in that line jump by half of it's intended value.
Say you drop it on 0.260, the point will jump by 0.260/2=0.130, landing it on 0.390 instead.
It may works differently for lines with more vertex points as well, but i haven't tried that yet.

I also found out that when you drag and drop a width point to it's exact value, it won't jump at all, it'll just stand still.
Again, a bit difficult to explain, but this is what i did:
1. I dragged and dropped the width point to a random point (example 0.700), the point then jumped to a different value,
2. Check the point's position value on parameter panel,
3. Tried drag and dropping the point to match that value (with 3 decimal rounding; e.g. if the panel displays 0.7009, then i'll drag and drop it on 0.701),
4. And the point will stay in that place, it won't jump at all.

This also works with values under 0.500.

I don't know why, but i feel like this has something to do with the homogenous setting maybe?
I don't know much about the homogenous thing though, so i could be wrong...

Welp, that's all i can find for now. I might try to look more into this again later on ._.v

**Comment by morevnaproject** [comment]
@FadhilKwan Yes, the behavior you just described is because Synfig doesn't count the last segment of spline while dragging ("doesn't see" the segment). But when you release mouse button it takes calculated position value and applies it to full outline.

Position  of widthpoint on outline is a value in range [0;1]. where 0 - start of outline and 1 is last point of outline (end).

Suppose, you have outline constructed of N segments.
You drag widthpoint to position P, then releasing mouse button and it "jumps" to position `P * N/(N-1)`.

**Comment by morevnaproject** [comment]
I have remembered an issue with similar symptoms - #1014.
Relevant fix - https://github.com/synfig/synfig/commit/a90d014c56f0cbee21c2ab0ef68936b9e84c49b1

Maybe this can help to understand where to look for fix.

**Comment by morevnaproject** [comment]
Guess what? Reverting a90d014 fixes the issue. But #1014 returns then. ^__^

**Comment by morevnaproject** [comment]
Here, lines 193 and 194:
https://github.com/synfig/synfig/blob/b5e5294121bda033f2a9f86a80e7e2fdbdb3d9ef/synfig-core/src/synfig/valuenodes/valuenode_bline.cpp#L191-L196

The `count` variable decreased twice, while it should be decreased only once. This makes spline shorter by one segment. ^__^

**Comment by morevnaproject** [comment]
...and while digging with this issue I found another one - https://github.com/synfig/synfig/issues/1431

**Comment by FadhilKwan** [comment]
whoaaaa~, so that's why the width handles did that thing. I think that's kinda crazy, I mean, it was all caused by a single line of code.... ._.v

But I'm glad that the source of the problem has been found (and it seems that it'll be fixed as well). I really have to thank you very much! ^O^

And yes, i did take a look at that other issue (#1431). That is also pretty weird, and it caught me off guard a bit because i thought there was nothing wrong there, until i realized the line's width didn't readjust itself at all after the homogenous turned on.
