### ISSUE TITLE
Misaligned animation preview thumbnail under Wayland

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1414]
**Synfig version & platform:**
Building from source
Debian (under GNOME Wayland)

**Issue description:**
Animation thumbnail preview alignment under Wayland is not consistent with X11
[Screenshot with description](https://github.com/synfig/synfig/issues/1144#issuecomment-623866635)

Here is the thumbnail code, if trying to fix the incorrect positioning on wayland:
https://github.com/synfig/synfig/blob/9ad7d22d857c42b49bde109af298c77d661a68b4/synfig-studio/src/gui/widgets/widget_canvastimeslider.cpp#L98

_Originally posted by @rodolforg in https://github.com/synfig/synfig/issues/1144#issuecomment-623870289_

**Comment by rodolforg** [comment]
Does it help?
From Gtk dev docs:
"Using GTK+ with Wayland

The GDK Wayland backend provides support for running GTK+ applications under the Wayland display server. To run your application in this way, select the Wayland backend by setting GDK_BACKEND=wayland.

Currently, the Wayland backend does not use any additional commandline options or environment variables.

For up-to-date information about the current status of this backend, see the project page."

https://wiki.gnome.org/Initiatives/Wayland/GTK%2B

**Comment by Keyikedalube** [comment]
> The gtk3 package has the Wayland backend enabled. GTK will default to the Wayland backend, but it is possible to override it to Xwayland by modifying an environment variable: GDK_BACKEND=x11.

https://wiki.archlinux.org/index.php/Wayland#GTK_3

I think this applies to Debian too.
However, when I tried to `echo $GDK_BACKEND`, I received a blank output
So I manually tried setting the environment variable with `export GDK_BACKEND=wayland`

Still the same misaligned thumbnail

**Comment by Keyikedalube** [comment]
Was reading this too: [unix stackexchange](https://unix.stackexchange.com/questions/326331/where-to-set-gdk-backend)

Tried
`env GDK_BACKEND=wayland <path-to-synfig-executable>`
Synfig launches but doesn't help the thumbnail misalignment :(

**Comment by Keyikedalube** [comment]
A temporary fix for the meantime:

`env GDK_BACKEND=x11 <path-to-synfig-executable>`

Thumbnail placement works correctly just like as it would on GNOME X11 session
