### ISSUE TITLE
Shouldn't Preferences > Restore Defaults give the user a chance to confirm?

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1415]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
![Screenshot from 2020-05-16 09-30-36](https://user-images.githubusercontent.com/24214509/82109947-23b1ea00-9758-11ea-9aa6-bac18f5f5a5a.png)

When I hit the Restore Defaults button, synfig restores everything back to factory settings AND saves it without the user either confirming the changes with OK button or Canceling the changes.

My expected outcome for Restore Defaults is
1. Change to factory default values
2. Wait for the user to either
    - Confirm the change (OK)
                    or
    - Revert the change (Cancel)

**Comment by ice0** [comment]
I agree. @morevnaproject @rodolforg  what do you think?

**Comment by rodolforg** [comment]
I agree too

**Comment by morevnaproject** [comment]
I agree. ^__^

**Comment by FirasH** [comment]
I think I got the fix, just built a test binary and it seems working fine...

**Comment by Keyikedalube** [comment]
@FirasH your fix works :)

But we have a lil bit weird UX.
## Here's my understanding of your algorithm:
```
1. User hits Restore Defaults
2. Show a dialog message popup
3. If Confirmed:
        load default values
                &&
        apply changes
   else:
        close message popup
4. Back to preferences dialog
```
The preferences dialog window is still open. Now the user might get confused with the purpose of **OK** and **Cancel** button.

## I prefer this method:
```
1. User hits Restore Defaults button
2. Load default values
3. if OK pressed:
        apply changes
   else:
        revert changes
4. Back to synfig window
```
Here, we are utilizing the already present OK and Cancel button in the preferences dialog. And pressing one of them decides whether to apply the changes or not.

**Comment by FirasH** [comment]
@Keyikedalube I get what you mean.
If we do it the way you intend it there is no need for any confirm dialog or similar solutions, just reject with `Cancel` or confirm with `Apply`.

**Comment by FirasH** [comment]
@rodolforg @ice0 @morevnaproject 
Currently when `Restore Defaults` is pressed this code is called:
https://github.com/synfig/synfig/blob/7684be864f20b5cda39dd07833e74e78a874e6d3/synfig-studio/src/gui/app.cpp#L2271-L2310

If I understand correctly, calling it means that the values get overridden as if `Apply` was pressed.

To accomplish what @Keyikedalube proposes, a possible solution could be to change the values of the editable items in:
https://github.com/synfig/synfig/blob/7684be864f20b5cda39dd07833e74e78a874e6d3/synfig-studio/src/gui/dialogs/dialog_setup.cpp#L644-L649

which would end up with something very similar to:
https://github.com/synfig/synfig/blob/7684be864f20b5cda39dd07833e74e78a874e6d3/synfig-studio/src/gui/dialogs/dialog_setup.cpp#L888-L1029

exept that the values we set are hardcoded (copied from `App::restore_default_settings()`).

For example:
`toggle_autobackup.set_active("1");`

Doing so the value is only assigned to their relative widgets and when `Apply` is pressed they are actually applied to `synfigapp`.

Does it make sense or I'm completely off? Any ideas are welcome!

**Comment by FirasH** [comment]
With the last commit it works as expected. Settings get applied only on OK pressed.

**Comment by morevnaproject** [comment]
> @Keyikedalube I get what you mean.
> 
> If we do it the way you intend it there is no need for any confirm dialog or similar solutions, just reject with `Cancel` or confirm with `Apply`.

I think we still need confirmation dialogue.

Consider the following situation:
User opens preferences, then does some tweaks according to his taste. After that he accidentally clicks Reset to Defaults button. So it would be nice to ask if he really wants to do that, otherwise he will loose his tweaks. ^__^

**Comment by Keyikedalube** [comment]
@morevnaproject interesting...

Alright, I'll go with FirasH algorithm

Also, experimented with GIMP preferences dialog just now. Pressing Reset button shows confirmation dialog. If the user presses Reset within the dialog, well... reset to default -> Back to preferences window. Now if the user presses Cancel in the pref dialog, all settings go back to the previous settings the user had before Reset was done. This concept is missing in synfig.

Synfig actually saves it as @FirasH  pointed out
> If I understand correctly, calling it means that the values get overridden as if Apply was pressed.

Here's my supposed improved FirasH algorithm:
```
1. User hits Restore Defaults
2. Show a dialog message popup
3. If Confirmed:
        load default values
        //        &&
        //apply changes
   else:
        close message popup
4. Back to preferences dialog
5. If OK:
        apply changes
    else:
        Revert changes
6. Back to synfig window
```

Notice in step 3, we don't want to apply the changes immediately yet. That way, step 5 cancel works. Currently this issue already describes it as broken.

**Comment by morevnaproject** [comment]
@Keyikedalube Possibly my previous comment wasn’t clear. I just wanted to say that I support method suggested by you. ^__^

**Comment by morevnaproject** [comment]
> Here's my supposed improved FirasH algorithm:
> ...

Yes, that one is even better! ^__^

**Comment by FirasH** [comment]
Ok, that should be straightforward.
In practice there's a confirm dialog when `Restore Defaults` is pressed.

**Comment by FirasH** [comment]
The code part is complete.

@morevnaproject now there are some parts of the code which aren't used anywhere as of now:
https://github.com/synfig/synfig/blob/6d3f75ffc8a3450587c8105a738e1b6db79f7956/synfig-studio/src/gui/app.cpp#L2272

should that be removed?

**Comment by Keyikedalube** [comment]
@FirasH Tested synfig from your branch. It's complete :)

@morevnaproject No, I wasn't thinking in a biased way :) I'm a human being too. So my method (or any future methods) that I suggest is mostly wrong. Facts and explanations help developers a lot :)

Hope I'm not being too nosy without contributing any code at all but thanks again for reading my comments and (of course) processing them too ;P

Looking forward for the merge!

**Comment by Keyikedalube** [comment]
> https://github.com/synfig/synfig/blob/6d3f75ffc8a3450587c8105a738e1b6db79f7956/synfig-studio/src/gui/app.cpp#L2272
> 
> should that be removed?

Didn't notice this was mentioned here.

Deleted my comment on your PR. But I think it's safe to remove.

**Comment by FirasH** [comment]
At this point the merge request is tested and ready.
Let me know if it's ok or needs some other improvements.
