### ISSUE TITLE
Imported Drawing Not Visible!!

### ISSUE THREAD

**Issue by Oreoluwakiiti** [synfig/synfig#1417]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:
I followed a guide and drew a vector image in inkscape after which i proceeded to save the file with a .sif extension. Next I imported the drawing into synfig but the image of the drawing wasn't visible. However, the outline of the layers was seen in the bottom right corner of the screen which caused further confusion. Please help me sort this issue out. Thankyou
![Annotation 2020-05-16 220718](https://user-images.githubusercontent.com/65468253/82130255-ac18a500-97c1-11ea-98c9-85f527721f90.png)

**Comment by ice0** [comment]
Hi! 
Which OS and Synfig version you are using?

Also can you try to run a command from console:
```
synfig ./yourfile.sif -o test.png
```

This command must run synfig renderer with output to the `test.png` file.

**Comment by morevnaproject** [comment]
Can you please attach .sif file here?

**Comment by Oreoluwakiiti** [comment]
> Hi!
> Which OS and Synfig version you are using?
> 
> Also can you try to run a command from console:
> 
> ```
> synfig ./yourfile.sif -o test.png
> ```
> 
> This command must run synfig renderer with output to the `test.png` file.



Thanks for replying. I'm running synfig on Windows10Pro. As for the version info, I'm not entirely sure; But the download file reads **SynfigStudio-1.2.2-18.09.14-win64-286f1**  [This](http://www.synfig.org/download-stable/) is the link from which i downloaded the application.

**Comment by Oreoluwakiiti** [comment]
> Can you please attach .sif file here?

Thanks for replying. 
[Anim.zip](https://github.com/synfig/synfig/files/4646970/Anim.zip)
 Thats the file

**Comment by ice0** [comment]
![screen1](https://user-images.githubusercontent.com/5604544/82409111-364d5b80-9a97-11ea-91a7-732ea3835b64.png)

It looks like your object was imported with the wrong coordinates, and now it is outside the canvas.

@morevnaproject is that a known problem?

**Comment by Oreoluwakiiti** [comment]
> ![screen1](https://user-images.githubusercontent.com/5604544/82409111-364d5b80-9a97-11ea-91a7-732ea3835b64.png)
> 
> It looks like your object was imported with the wrong coordinates, and now it is outside the canvas.
> 
> @morevnaproject is that a known problem?

It appears so. Do you have any recommendation as to how to resolve the issue?

**Comment by Oreoluwakiiti** [comment]
?!?!?!?!?!?!?!?

**Comment by morevnaproject** [comment]
This is because document created in Inkscape is bigger than Synfig document.

This is easy to fix - just group everything and scale down. 
Here is a video to show how - https://www.youtube.com/watch?v=HMeTyQ2xPhc

**Comment by Oreoluwakiiti** [comment]
Thank you
