### ISSUE TITLE
[Lottie Exporter] Add support for blur layers

### ISSUE THREAD

**Issue by saurabh-ramola** [synfig/synfig#1419]
Make possible to export [Blur](https://wiki.synfig.org/Blur_Layer) layers from Synfig to Lottie Format.

**Comment by saurabh-ramola** [comment]
@AnishGG is this complete now?

**Comment by AnishGG** [comment]
Just waiting for the merge of #1505  ^__^

**Comment by AnishGG** [comment]
Closing this now. :D
