### ISSUE TITLE
Shortcut for switching between animation windows

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#1422]
Can we have something like `Alt + 1`/`Alt + 2` to switch between animation windows. This is used in firefox to change the tabs. Google chrome uses `Ctrl + num` for the same.
I guess this will be useful for people who have multiple tabs of animation windows open.

**Comment by saurabh-ramola** [comment]
I feel this will be a great addition, I personally use it a lot in switching between tabs.
