### ISSUE TITLE
[Feature request] I think it's time to change the way the synfig shortcut system works

### ISSUE THREAD

**Issue by boubouh** [synfig/synfig#1428]
I think sinfig should use the same shortcut as blender and take advantage of the popularity of blender to allow new users get into synfig much faster.
and I even find that a new open source 2D program called [ENVE](https://github.com/MaurycyLiebner/enve) uses the same shortcut as blender as demonstrated in this video:
https://www.youtube.com/watch?v=xT8AO11uMPY

**Comment by morevnaproject** [comment]
I think Blender's shortcuts are not intuitive for new users - I mean those who had no previous experience with Blender.
 From my point of view, the good side of Synfig is that it always been more friendly for new users than Blender - Synfig is easy for beginner users.  Those users who are familiar with Blender could not be classified as "beginners" in my opinion. ^__^

In any case, I suggest to join discussion here - #1336.
