### ISSUE TITLE
Add Show Guides and Snap to Guides buttons in Synfig Studio Toolbar

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1451]
**Synfig version**:
master 4c519a9

**Issue description**:
If using `Guides`, sometimes it's useful to toggle `Guides` visibility and snapping quickly like for the `Grid`.

My suggestion is to add two buttons to the Toolbar:
1. button for showing the guides
2. button for enabling snapping to guides

i.e. exactly the same behavior currently used for grids.

What do you think?

**Comment by rodolforg** [comment]
I agree with the feature request.
But I see the toolbar so cluttered… In some monitors, the onion skin options isn't even shown.
Maybe a PopOver menu in current snapping options?

**Comment by FirasH** [comment]
I'm thinking about a possible solution...

As for now I think that snapping options should not be put in a popover menu but rather move some buttons we have currently in the toolbar to another position.
I personally find using popover toolbar button (like in the latest GIMP release for the tools) not intuitive and kind of going against the purpose of a having a quicker way of enabling or setting options. 

Maybe placing handles and snapping buttons vertically on the right side of the canvas could be a better solution?
Mockup:
![mockup-1451](https://user-images.githubusercontent.com/6705690/83323789-56340a80-a261-11ea-917a-2cf38257bc85.png)

**Comment by rodolforg** [comment]
> like in the latest GIMP release for the tools

Yeah, they're not right. But I think that click on Snap button automatically pops over the option list: no matter where you click on Snap button.

**Comment by FirasH** [comment]
I have an idea of something more similar to Inkscape (like the mockup) but we can give it a try if you want 👍.

I don't know what @morevnaproject and @ice0 think about this, maybe they have something better in mind.

**Comment by FirasH** [comment]
I was thinking about how the UI could be improved and here are my thoughts:

1) I don't see why tools should be in the `Toolbox` and use all of that screen space:
![Tools](https://user-images.githubusercontent.com/6705690/92369962-f1a70800-f0f9-11ea-8cd1-6e35b93df246.png)

Wouldn't it be better to place them vertically on one side of Canvas? For example on the **left** in an Inkscape style UI (See my previous mockup).

While the color part:
![Colors](https://user-images.githubusercontent.com/6705690/92370784-0b951a80-f0fb-11ea-89ec-d0b59964ee91.png)
could be left alone in the `Toolbox` window and moved to this group:
![Colors_moved](https://user-images.githubusercontent.com/6705690/92371044-69296700-f0fb-11ea-9a5b-f7dcde9de9bb.png)
and be automatically shown when a Tool is selected.

2) Regarding the previous solution of the old mockup (see my first comment), I think File / Edit stuff (Open/Save/Render settings/Undo and Redo etc.) should be placed on the **right** side of Canvas, leaving on **top** the remaining buttons (Handles/Grid/Onion Skin etc.).
The motivation for this setup is that we could leave part of that horizontal space for a "variable part". With this I mean that a part of the upper Canvas could change according to the selected tool showing some options.

3) If this makes sense, I would also add the buttons for Open Recent/Export/Import/Close document/Preferences.

This way the menus won't be used in most operations and the used screen space won't change (probably less space used for windows)

Let me know what you think about it :+1:

**Comment by morevnaproject** [comment]
We have this space free ^__^ -
![screenshot_003](https://user-images.githubusercontent.com/332868/92379463-b7f1f380-f131-11ea-9507-6bf362c53a73.png)

**Comment by morevnaproject** [comment]
> Wouldn't it be better to place them vertically on one side of Canvas? For example on the **left** in an Inkscape style UI (See my previous mockup).
> 
> While the color part:
> ![Colors](https://user-images.githubusercontent.com/6705690/92370784-0b951a80-f0fb-11ea-89ec-d0b59964ee91.png)
> could be left alone in the `Toolbox` window and moved to this group:
> ![Colors_moved](https://user-images.githubusercontent.com/6705690/92371044-69296700-f0fb-11ea-9a5b-f7dcde9de9bb.png)

This is interesting idea.

**Comment by morevnaproject** [comment]
>     1. Regarding the previous solution of the old mockup (see my first comment), I think File / Edit stuff (Open/Save/Render settings/Undo and Redo etc.) should be placed on the **right** side of Canvas

How about moving File/Edit buttons to toolbox?
![screenshot_004](https://user-images.githubusercontent.com/332868/92379861-5aaa7200-f132-11ea-9ecf-55e9b98774c1.png)

**Comment by FirasH** [comment]
> How about moving File/Edit buttons to toolbox?
> ![screenshot_004](https://user-images.githubusercontent.com/332868/92379861-5aaa7200-f132-11ea-9ecf-55e9b98774c1.png)

I don't see an advantage in moving them, because there is enough space to show all the buttons.

I forgot to add this: another problem is that for vertically placed buttons we should have an icon, because text would be too large.

Preparing a mockup to see if what I'm proposing makes sense or not :+1:

**Comment by FirasH** [comment]
![mockup](https://user-images.githubusercontent.com/6705690/92384960-4e61ed00-f111-11ea-882b-f3685af6792b.jpg)

Repeated icons are for filling the space with some other buttons

**Comment by FirasH** [comment]
The top toolbar is a `Gtk::HBox` filled with buttons:
https://github.com/synfig/synfig/blob/f1d830afc790f775fc020a78383adaaa7ebfe8e6/synfig-studio/src/gui/canvasview.cpp#L1139-L1401

which is attached to a `Gtk::Grid` containing Canvas and other stuff:
https://github.com/synfig/synfig/blob/f1d830afc790f775fc020a78383adaaa7ebfe8e6/synfig-studio/src/gui/canvasview.cpp#L634-L638

Knowing this, I assume that creating two `Gtk::VBox` Widgets and attaching them to the `Gtk::Grid` should get what I proposed done.

**Comment by FirasH** [comment]
Made a quick test, and positioning buttons is possible:
![Mockup](https://user-images.githubusercontent.com/6705690/93707852-3a1ae880-fb32-11ea-866b-72d34b0a5c86.png)

Still, need to fix the size of vertical icons.

**Comment by Keyikedalube** [comment]
> Still, need to fix the size of vertical icons.

Call Synfig CSS class `synfigstudio-efficient-workspace` like this
https://github.com/synfig/synfig/blob/86cb9ce0e412a2e58750516e63370ed1f0cfb86b/synfig-studio/src/gui/canvasview.cpp#L544-L546
and icons will be adjusted like the rest :)
