### ISSUE TITLE
Add ability to select available Sets when adding Layers to Sets

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1452]
**Synfig version**:
master 4c519a9

**Issue description**:
1. Open any animation or create a new one
2. In the `Layers Panel` right-click on a Layer and select `Add Layers to Set`

A dialog will pop up asking for the name of the `Set`:
![add_set](https://user-images.githubusercontent.com/6705690/83269871-fccbcd00-a1c7-11ea-9214-e3c681d88f64.png)

At this point if the user wants to add a Layer to an already existing `Set`, it's needed to assign the same name of that `Set`.

It would be useful to add the functionality to select from the already created `Sets` using something like a drop-down menu listing available options.

**Comment by rodolforg** [comment]
A dropdown list with an text entry field or just add a list in this dialog shown in OP would be enough to close this issue. ;)

**Comment by FirasH** [comment]
@rodolforg you think it would be more seamless to use:
1. a text field that includes a drop-down menu (all in one)
2. a separate drop-down menu for available sets

or something else? You know gtkmm much better than me :+1:

**Comment by rodolforg** [comment]
Your first option was what I tried to describe first, but you did it better than me ;)

I prefer to not use dropdown menu. It's worse to search items.

**Comment by FirasH** [comment]
Seems a great solution to me :blush:

**Comment by ice0** [comment]
I vote for:


> 1. a text field that includes a drop-down menu (all in one)

**Comment by morevnaproject** [comment]
Agree. ^__^

**Comment by rodolforg** [comment]
@FirasH Do you want to try to implement it?

**Comment by FirasH** [comment]
> @FirasH Do you want to try to implement it?

I can take a look if you want 👍

**Comment by FirasH** [comment]
A couple of places to start with. Firstly, where the action is called:
https://github.com/synfig/synfig/blob/b6995dc5864f43239b4e5ac9b119222328af6af1/synfig-studio/src/gui/instance.cpp#L1207-L1294

Secondly, the code of the dialog:
https://github.com/synfig/synfig/blob/b6995dc5864f43239b4e5ac9b119222328af6af1/synfig-studio/src/gui/app.cpp#L3756-L3802

**Comment by FirasH** [comment]
We could use `Gtk::EntryCompletion` to list available Sets.
Not sure how that would look like or if it has a drop-down button... What do you think?

Minor question, any idea where to get the list of current Sets?

**Comment by rodolforg** [comment]
Oh, sorry I didn't see it before, @FirasH .

Internally, Layer Group is actually Layer Encapsulation, and Layer Set is… Layer Group =P

You can get the layer set from `canvas_interface()->get_canvas()->get_groups()`

**Comment by FirasH** [comment]
@rodolforg found this [tutorial](https://developer.gnome.org/gtkmm-tutorial/stable/sec-comboboxentry.html.en).
Do you think it fits our purpose?

**Comment by FirasH** [comment]
Still a work in progress... the entry looks like this:
![sets_dialog](https://user-images.githubusercontent.com/6705690/100552807-b5fb8480-3289-11eb-94ee-19e8814630ee.png)

**Comment by FirasH** [comment]
Cleaned up a bit the code, I'll link a merge request.

This is the dialog right now with visible menu:
![sets_dialog_menu_open](https://user-images.githubusercontent.com/6705690/100553904-3e315800-3291-11eb-8f80-390fbf176c2d.png)

and closed menu:
![sets_dialog_menu_closed](https://user-images.githubusercontent.com/6705690/100553906-48535680-3291-11eb-9ebf-1607ea156d75.png)

To show the `Sets` names it is necessary to click on the dropdown button.

In case the typed string corresponds to one of the available `Sets` the `Layer` is assigned to the same corrisponding `Set` (as with current master) .

**Comment by rodolforg** [comment]
Yes.
You can use these links  as entry completion reference:
https://developer.gnome.org/gtk3/stable/GtkEntryCompletion.html
https://www.kksou.com/php-gtk2/sample-codes/setup-GtkEntry-with-auto-completion.php (in PHP, but adaptable to C++)

**Comment by rodolforg** [comment]
Maybe the button label should change depending on current entry text?
"Add" and "Add to new set"

@morevnaproject @ice0 @Keyikedalube

**Comment by FirasH** [comment]
I used `Gtk::ComboBoxText` which has an `Entry`, but not a `Gtk::EntryCompletion`.

That's because I didn't find how to use `Gtk::EntryCompletion` in case where any text is typed.
Now, with `Gtk::ComboBoxText` even without typing anything you can just choose from the dropdown menu.

**Comment by Keyikedalube** [comment]
> Maybe the button label should change depending on current entry text?
"Add" and "Add to new set"

I haven't used sets to organize my layers so my best suggestion would be to replicate other popular vector drawing programs like Inkscape or CorelDraw.

However, "Add" alone sounds fine to me. But if presenting new and existing set information (button label) to the user is important then:
1. _rodolforg's suggestion_
2. "Add" and "Create"

I prefer 2 :) fast readability.
