### ISSUE TITLE
new timetrack doesn't autoupdate when user moves a keyframe in Timetrack panel

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#1454]
**Synfig version & platform**:
master 6d3f75f

**Issue description**:
The new timetrack doesn't autoupdate when user moves a keyframe in Timetrack panel.
If user clicks on timetrack area, it refreshes correctly though;

**Comment by morevnaproject** [comment]
Hmm... I can't reproduce this on 6d3f75f, with simple animated circle.

**Comment by rodolforg** [comment]
It happens without any layer at least.

**Comment by morevnaproject** [comment]
Resolved in Synfig version 1.5.1 - https://www.synfig.org/2021/10/30/synfig-studio-1-5-1-released/
