### ISSUE TITLE
Services bar empty in Mac version

### ISSUE THREAD

**Issue by chandratushu21** [synfig/synfig#1463]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:
> The Services bar is empty in Mac version. Which functions you are expecting to add in the Admin menu bar ??
<img width="373" alt="Screenshot 2020-06-03 at 1 36 42 PM" src="https://user-images.githubusercontent.com/64960756/83612667-55241580-a5a0-11ea-877b-d872586b309a.png">

> 

>  Also which new features do you want to add in the admin menu bar ?

**Comment by FirasH** [comment]
Confirmed on macOS 10.15.4 with Synfig 1.3.14.
I'm not a macOS user though, don't know what should be found in there.
