### ISSUE TITLE
App crashes unexpectedly 

### ISSUE THREAD

**Issue by chandratushu21** [synfig/synfig#1464]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:
1. Click on **File** from meny bar> **Render** > **choose..** > In the popup finder type in any alphabet to look for your file, The seach bar takes the input but the app crashes unexpectedly with following window.

<img width="632" alt="Screenshot 2020-06-03 at 10 55 44 PM" src="https://user-images.githubusercontent.com/64960756/83668604-db1a7d80-a5ed-11ea-8b98-133abd512d6b.png">

It will do so multiple time when you follow 1. again and again.

**Comment by BobSynfig** [comment]
Tried to reproduce it under Ubuntu 18.04 x64 / Synfig 1.3.14 x64
No crash

Please check your permissions on disk access for the application (as you are under MacOS)
and please indicate which version of Synfig and MacOs you use

**Comment by ice0** [comment]
Hi! Which OS version and Synfig version you are using?

**Comment by BobSynfig** [comment]
Note: expanding Comments / "Show Details" should bring some help in debugging process :P

**Comment by FirasH** [comment]
Could not reproduce with 1.3.14 on macOS 10.5.5.
@chandratushu21 do you have some other info about the issue or maybe a screencast?

**Comment by chandratushu21** [comment]
The latest version of synfig as available on the official website and running on latest **macOS 10.15.5**

**Comment by rodolforg** [comment]
Why did you close if it's not solved?
Or is it? :)
