### ISSUE TITLE
Error animating advanced spline.

### ISSUE THREAD

**Issue by strujillodv** [synfig/synfig#1480]
**Synfig version & platform**: AppImage 1.3.14 -  Archlinux KDE

**Issue description**:

Animate an advanced spline doesn't work well in development version 1.3.14.

You searched for -> Version 1.2.2

![Version 1.2.2](https://i.giphy.com/media/h5ocX332tiP5BcJ3vH/source.gif)
https://drive.google.com/file/d/1N7LegIjv0jKZtsYe0gDWepUZFnG6Io8p/view?usp=sharing

The opted -> Version 1.3.14

![Version 1.3.14](https://i.giphy.com/media/YTJaRCydddInMW7e5n/source.gif)
https://drive.google.com/file/d/1LgKH5AcSeAv8Ve_xKrUs_j9c6R3Efa4X/view?usp=sharing

**File exercise**: https://drive.google.com/file/d/1QtYhewPdsbh80UH9HNHr2M5Vsz0Mp50q/view?usp=sharing

**Comment by rodolforg** [comment]
1.3.11 : ok
1.3.12 : bad :P 

@strujillodv , in the meanwhile, just type a number close enough to 1.0 in width point poistion, like 0.9999 , but no 1.0

**Comment by strujillodv** [comment]
@rodolforg, Changing to a value less than 1.0 it does not work,

**Comment by rodolforg** [comment]
Here it worked: the starting point fixed in 0.00001 instead of 0 and end width point moves until 0.9999 or something like that.
I'll try again later.

Devs: Anyway, after a `git bisect`, the guilty commit
c35c7478cbde5bba2b630085005f199be892db15

**Comment by FirasH** [comment]
#1329 is the same issue?

**Comment by morevnaproject** [comment]
Agrh, again outline issues! :rofl:

**Comment by rodolforg** [comment]
@morevnaproject 
Could you take a look at this test file?
All drawn lines are advanced outlines with three equally spaced vertices and two width points (positions 0.1 and 0.9)
I change the Side Type Before of first (left) width point and the  Side Type After of the last (right) width point.

Is this behavior correct?

[not-looped-advanced-line-tip-test.zip](https://github.com/synfig/synfig/files/4843323/not-looped-advanced-line-tip-test.zip)

![not-looped-advanced-line-tip-test](https://user-images.githubusercontent.com/1323987/85963723-6852b700-b98d-11ea-99c0-07055d66ec1f.png)

**Comment by rodolforg** [comment]
Looped advanced-outline layers with 3 vertices and 2 width points (called here as WP).
I changed the `Side Type Before` of the first WP and the `Side Type After` of the last WP as shown. The remaining `side type`s are set `Interpolation`.
I also changed the position of both WP as also shown.

So we can notice that the specific cases of WP in the boundaries are an issue.
Other issue is that the `sharp` `cuspid` is not as expected (it doesn't "go straight" to the corner).
And for last we can see that if a WP is at the beginning (0.0), it shows the cuspid shape even though the last WP is not near the end of spline (as shown in second row of last column)

![looped-advanced-line-tip-test](https://user-images.githubusercontent.com/1323987/85976921-f345a880-b9b1-11ea-83e7-b69eb17ed79e.png)

@morevnaproject

**Comment by rodolforg** [comment]
I colored to highlight what is wrong (red) and what is right (green) regarding the WP positions and the cuspid shape.
![looped-advanced-line-tip-test](https://user-images.githubusercontent.com/1323987/85977858-c98d8100-b9b3-11ea-9dfa-9388b5495516.png)
[looped-advanced-line-tip-test.zip](https://github.com/synfig/synfig/files/4844044/looped-advanced-line-tip-test.zip)

**Comment by morevnaproject** [comment]
@rodolforg Thank you so much! I am investigating this issue now... ^__^

**Comment by morevnaproject** [comment]
> You searched for -> Version 1.2.2
> 
> ![Version 1.2.2](https://camo.githubusercontent.com/647a413bcfafbfb3d2592a991b2a79af8523eac9/68747470733a2f2f692e67697068792e636f6d2f6d656469612f68356f63583333327469503542634a3376482f736f757263652e676966)
> 
> The opted -> Version 1.3.14
> 
> ![Version 1.3.14](https://camo.githubusercontent.com/476ab7df0aa28e93017d290e98d781f4a427c687/68747470733a2f2f692e67697068792e636f6d2f6d656469612f59544a61524379646464496e4d573765356e2f736f757263652e676966)

I can see there are two different issues here.

First one -  line visible where is shouldn't - is addressed in #1518.

Second issue is in looped spline (triangle) - the position of animated widthpoint is wrong. This is related to  issue discussed in https://github.com/synfig/synfig/issues/314#issuecomment-603739718. It was fixed, but seems it still appears for cases when widthpoint is animated. Needs further investigation. (Possibly, I need to look how Animated valuenode handles widthpoints...)

**Comment by rodolforg** [comment]
> Second issue is in looped spline (triangle) - the position of animated widthpoint is wrong. This is related to issue discussed in [#314 (comment)](https://github.com/synfig/synfig/issues/314#issuecomment-603739718)

I don't think it is wrong.
The Sif file was created in 1.3.14. Opening it in 1.2 will always have this problem.
The inverse (file 1.2 in 1.3.14) was fixed

**Comment by morevnaproject** [comment]
Hey, you right! False alarm. :smile: 
That's great!

**Comment by strujillodv** [comment]
The error continues
[![Log Synfig](https://drive.google.com/uc?export=view&id=1cdotV6gMbTZtnJSFICCm0kSRa9SLRV6x)](https://drive.google.com/file/d/1F_qb6dLZsyNODEusvURrDm4H3QYHyc3Q/preview)

Synfig-git built on July 17

![Version 1.2.2](https://media.giphy.com/media/S5oA9fc5UHkpdrvMAL/giphy.gif)

Synfig stable

![Version 1.2.2](https://media.giphy.com/media/f4JBte67avOQ51CHpY/giphy.gif)

**Comment by rodolforg** [comment]
@strujillodv It was fixed in master and 1.3.x branch.

What git branch did you use it?

**Comment by strujillodv** [comment]
@rodolforg this is the version
![Log Synfig](https://drive.google.com/uc?export=view&id=1qIj8bXxrPVRkfCU0jG6XKxhihjbqC2Vj)

**Comment by rodolforg** [comment]
@strujillodv strange enough I can't find that Revision ID in master branch.
However, the fix was merged into master branch July 12.

So please update your master branch and build it again:
- If you downloaded the sourcecode in a zip file, redo it
- If you used git commands, call `git pull origin`

**Comment by strujillodv** [comment]
@rodolforg Sorry, my mistake had not updated the repository before testing.

It is working very well

Gif created with Synfig-git built

![Version 1.2.2](https://media.giphy.com/media/fvYMc1zYhV0kOUO9C8/giphy.gif)
