### ISSUE TITLE
[CMake] Missing icons

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1511]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
After successfully building synfig and running it... icons are missing

![Screenshot from 2020-06-24 18-23-14](https://user-images.githubusercontent.com/24214509/85560789-a035c380-b648-11ea-87bc-d95057f51f44.png)

I think you guys forgot to update the other build script
From #1483:
> I didn't touch the CMake stuff...

**Comment by AYESDIE** [comment]
Did you try building `build_images` target?

**Comment by Keyikedalube** [comment]
> Did you try building build_images target?

Yup, found out the icons were installed in the old directory `pixmaps/synfigstudio`

https://github.com/synfig/synfig/blob/2ce6c92c88dbb039e3d4b2df6df6884f81c63aba/synfig-studio/images/CMakeLists.txt#L266-L268

rodolforg has moved them to new directory `/share/synfig/icons/classic` in the Autotools version
There is an ongoing WIP to migrate from deprecated StockID & IconFactory to IconTheme #1508
#1483 was the first commit. Noticed CMake was left behind.

**Comment by Keyikedalube** [comment]
Noticed a slight behavior change with locks & links icons from CMake build
# Expected
![Screenshot from 2020-06-25 07-18-45](https://user-images.githubusercontent.com/24214509/85644540-dc067280-b6b4-11ea-95b6-92b87b96cb70.png)

# Result
![Screenshot from 2020-06-25 07-18-19](https://user-images.githubusercontent.com/24214509/85644543-df016300-b6b4-11ea-84c2-f7dfb0163cb8.png)

**Comment by rodolforg** [comment]
> Noticed CMake was left behind.

Yes :( I said in PR comments I didn't touch CMake. I don't know CMake :( a lot of commands

**Comment by Keyikedalube** [comment]
@rodolforg No worries ;) that's what contributors are for... delegating task.
