### ISSUE TITLE
synfigstudio-git compiling from aur

### ISSUE THREAD

**Issue by RezaSh13** [synfig/synfig#1513]
I wanna install synfigstudio-git, But when compiling, it needs more than 4 gigs. Please introduce a repo that offers a binary version؛ the appimage version has a problem for me and it takes a long time to run

Please add the synfigstudio-testing to Snap and Flatpak

Manjaro KDE Plasma

:(

**Comment by strujillodv** [comment]
Hi, how are you?

You can install synfig manually.

$ git clone https://github.com/synfig/synfig.git ~ / synfig.git
$ cd ~ / synfig.git
$ ./1-setup-linux-native.sh

**Comment by rodolforg** [comment]
Or change the last 2 command lines to :
```
$ ./2-build-production.sh
$ ~/synfig.git/_production/build/bin/synfigstudio
```
To a smaller (and a little faster) binary and building files.
