### ISSUE TITLE
Synfig 1.2.2 won't open

### ISSUE THREAD

**Issue by krisnaxda** [synfig/synfig#1520]
**Synfig version & platform**:
SynfigStudio-1.2.2-18.09.14-linux64-286f1.appimage
Linux Mint 19.2 64bit
**Issue description**:
already set appimage executable, but synfig won't open it says 

```
./bin//launch.sh: line 66: 19763 Bus error               (core dumped) "$BASE_DIR/bin/synfigstudio.wrapper" "$@"
```

![image](https://user-images.githubusercontent.com/30945632/86457194-761d8900-bd4d-11ea-969a-87de57f192aa.png)

**Comment by Jose-Moreno** [comment]
@krisnaxda Can you try these linux development appimages for version 1.3.14 to see if you still have similar errors?
[Linux AppImage 32bit](https://www.fosshub.com/Synfig-Development.html?dwl=SynfigStudio-1.3.14-testing-2020.04.30-linux32-b2662.appimage)
[Linux AppImage 64bit](https://www.fosshub.com/Synfig-Development.html?dwl=SynfigStudio-1.3.14-testing-2020.04.30-linux64-b2662.appimage)

**Comment by krisnaxda** [comment]
> @krisnaxda Can you try these linux development appimages for version 1.3.14 to see if you still have similar errors?
> [Linux AppImage 32bit](https://www.fosshub.com/Synfig-Development.html?dwl=SynfigStudio-1.3.14-testing-2020.04.30-linux32-b2662.appimage)
> [Linux AppImage 64bit](https://www.fosshub.com/Synfig-Development.html?dwl=SynfigStudio-1.3.14-testing-2020.04.30-linux64-b2662.appimage)

yes, it return like this
```
./bin//launch.sh: line 66: 12855 Bus error               (core dumped) "$BASE_DIR/bin/synfigstudio.wrapper" "$@"

```

**Comment by Jose-Moreno** [comment]
@krisnaxda Thanks, by testing that the developers can verify that the bug is still present and prioritize it. I also found an older issue where the program crashes when saving with a similar error in Ubuntu and with an AppImage as seen in https://github.com/synfig/synfig/issues/417

So it seems this problem could not only be a linux only problem, probably even an AppImage only problem. 
If that is indeed the case, can you please test the FlatPak version for Synfig 1.2.2 https://flathub.org/apps/details/org.synfig.SynfigStudio 

AFAIK FlatPak has built-in support in Linux Mint 18.3 or greater so you should be able to install it right away.

**Comment by morevnaproject** [comment]
I am on Linux Mint 19 (but not 19.2) and appimage 1.2.2 works fine for me...

**Comment by krisnaxda** [comment]
@Jose-Moreno - thank you, I will try as soon as possible after getting a stable connection

@morevnaproject - what version are you use? and what DE?

**Comment by morevnaproject** [comment]
@krisnaxda It says this:

```
$ cat /etc/issue
Linux Mint 19 Tara \n \l
```

I am using Mate DE (Mate Edition).

**Comment by BobSynfig** [comment]
Please check your permissions on /tmp
They should be root:root and 777

**Comment by krisnaxda** [comment]
> Please check your permissions on /tmp
> They should be root:root and 777

yes it say like this

```
$ ls -ld /tmp
drwxrwxrwt 15 root root 4096 Jul 12 10:20 /tmp
```

**Comment by ice0** [comment]
Just checked on 19.3 - all works fine.
How much memory do you have?
Can you show backtrace from core dump?

**Comment by BobSynfig** [comment]
Try to _(backup_ first _and)_ remove your ~/.config/dconf/user
It is often recommended in case of  "Bus error (core dumped)"

Do other .appimage applications work properly on your system?

**Comment by krisnaxda** [comment]
@ice0 
i am using 19.2 Mate, this is my memory usage, sorry i don't know how to show backtrace
![image](https://user-images.githubusercontent.com/30945632/87244444-9b09ae80-c467-11ea-8d30-5459c4a6f3e9.png)

@BobSynfig 
already delete user file, and try other .appimage and working, i try other unofficial synfig studio 1.2.1 from linux mint software manager and work
but when i try synfig from appimage, it always show like this

```
$ ./SynfigStudio-1.3.14-testing-2020.04.30-linux64-b2662.appimage

   synfig studio -- starting up application...

./bin//launch.sh: line 66: 30598 Bus error               (core dumped) "$BASE_DIR/bin/synfigstudio.wrapper" "$@"
```

**Comment by morevnaproject** [comment]
@krisnaxda Can you try to create a new user, login under its name, download appimage and try to launch appimage from there?

**Comment by BobSynfig** [comment]
I just tried from a fresh VM: 4 cores, 4 Gb Ram, 128Mb Gfx
Mint 19.2 x64 MATE (not installed, live)
SynfigStudio-1.2.2-18.09.14-linux64-286f1.appimage from Github

Runs perfectly from console or from file manager, the only error messages are the "classical ones" about Fontconfig

I will install, update and check again in case some libs have changed

**Comment by krisnaxda** [comment]
@morevnaproject 
still return error like before

@BobSynfig 
yes i got that looping message too when first time i run the synfig.appimage, also the synfig studio icon not showing in mintmenu

**Comment by BobSynfig** [comment]
> i am using 19.2 Mate, this is my memory usage, sorry i don't know how to show backtrace
> ![image](https://user-images.githubusercontent.com/30945632/87244444-9b09ae80-c467-11ea-8d30-5459c4a6f3e9.png)

3.3Gb RAM ?
Looks like upper limit reachable with 32-bit OS...
Are you sure to run a 64-bit OS?
It could explain "Bus error" due to incompatible architecture https://en.wikipedia.org/wiki/Bus_error
What give `uname -a` and `lscpu` ?

**Comment by krisnaxda** [comment]
> > i am using 19.2 Mate, this is my memory usage, sorry i don't know how to show backtrace
> > ![image](https://user-images.githubusercontent.com/30945632/87244444-9b09ae80-c467-11ea-8d30-5459c4a6f3e9.png)
> 
> 3.3Gb RAM ?
> Looks like upper limit reachable with 32-bit OS...
> Are you sure to run a 64-bit OS?
> It could explain "Bus error" due to incompatible architecture https://en.wikipedia.org/wiki/Bus_error
> What give `uname -a` and `lscpu` ?

4gb ram, and running 64-bit OS

![image](https://user-images.githubusercontent.com/30945632/87623840-815eb480-c750-11ea-9e29-267159bc1d06.png)

**Comment by ice0** [comment]
@krisnaxda can you check new AppImages?
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux64-a2ca6.appimage
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux32-a2ca6.appimage

**Comment by Keyikedalube** [comment]
Closing this issue because v1.2.2 stable release is old + due to inactivity too.

But feel free to reopen it in case you guys need this resolved.
