### ISSUE TITLE
[Skeleton Tool] Add button for creating new Skeleton layer into Tool Options Dialog

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1535]
![screenshot_003](https://user-images.githubusercontent.com/332868/86768481-dbd48280-c077-11ea-8f97-2b37642fd88c.png)

This button will create a new skeleton layer and makes it active (selected).

This is useful if user has some Skeleton Layer selected, but wants to create a new one.

**Comment by morevnaproject** [comment]
Tested it. I can see it creates a layer with one bone. Can we make it create a layer without a bone?

**Comment by Aa20475** [comment]
Hey! 

If we have no bones initially, that means, there is no active bone. In that case, I was trying to use `ValueNodeStaticListInsert` to add a bone. But when there are no bones initially, I am not able to figure out how to do it. Can you guide me with this? :eyes:

**Comment by morevnaproject** [comment]
Can you use `ValueNodeStaticListInsert` in the same way as it is used  in `valuedesccreatechildbone.cpp`? -

https://github.com/synfig/synfig/blob/8c19653c0e273085acd23f6bf7b9221694808b09/synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp#L220-L235

**Comment by Aa20475** [comment]
Okay will give it a shot!

**Comment by Aa20475** [comment]
Hey!

I actually tried this. I used `Action::Group` and added `ValueNodeStaticListInsert` and `ValueDescSetActiveBone` to it. But I don't think it is undoable. What do you think? 

Also, do you think it's important to have no bones? I think it's fine to have something to start with :sweat_smile:

**Comment by morevnaproject** [comment]
> I actually tried this. I used `Action::Group` and added `ValueNodeStaticListInsert` and `ValueDescSetActiveBone` to it. But I don't think it is undoable. What do you think?

I don't think that using  `Action::Group` will make it non-undoable. Can you push your code so I can take a look?

> Also, do you think it's important to have no bones?

This is really not critical, but it would be nice to have so. ^__^

In any case we should consider situation, when user removes all bones from Skeleton Layer and makes attempt to add new bones. ^__^

**Comment by Aa20475** [comment]
Yess! That case is important! Will do that! Will push it!

**Comment by Aa20475** [comment]
Hey!

I've been thinking about this. Even without the skeleton tool, there is no way to add a bone if the number of bones is 0. We can either-

- Forbid the user from doing so.
- Remove the layer when deleting the last bone.
- Write an action to add bone  when there are no bones.

What do you think?

**Comment by morevnaproject** [comment]
Hi! In 2 weekly reports in a row you identified that this issue is slowing you down. I have asked you to push the code (even non-working), so I can take a look. What's the problem here?

**Comment by Aa20475** [comment]
Hey! 

I was successfully able to add a new object into the list but I'm struggling with writing the conditions. I'll push the code asap before today!

**Comment by Aa20475** [comment]
Can you tell me where I can refer to get an understanding of `PassiveGrouper`?
