### ISSUE TITLE
[Skeleton Tool] Visible bone when user does click-and-drag

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1536]
When user creates a new bone with click-and-drag, there should be a visible bone, which is changing its size according to mouse movements. 

Similar feedback currently is possible using Spline Tool - it displays vertex and tangent dynamically. But currently for Skeleton Tool this not works.

See video for demonstration - https://youtu.be/TIYmL2518M8

**Comment by Aa20475** [comment]
Hey! I've been thinking about how to do this.

* When a mouse button is down, we can add a childbone.
* We can then manipulate the bone with mouse motion.
* When it is released, we can check the conditions and see if we need a default bone.

This will work fine but I can't understand how to make this undoable. We can undo it but during redo, I don't think we'll have the right results. What do you say?

**Comment by morevnaproject** [comment]
> When a mouse button is down, we can add a childbone.

This is not a good solution I think.

I suggest to examine code of Circle Tool. It has everything you need.

![screenshot_002](https://user-images.githubusercontent.com/332868/87879629-5311fb00-ca16-11ea-9b0d-8e38fa575626.png)

You can also look on how Gradient Tool works (when it creates Linear Gradients).

**Comment by morevnaproject** [comment]
I just want to note: you do not have to draw full bone when user does click-and-drag. Just draw some points to show some something is going on. ;)

**Comment by Aa20475** [comment]
Ohhh alright!! I get it!! Thanks for the tip... Will finish it asap!

**Comment by Aa20475** [comment]
Alright! It works now! I was brainstorming to add a full bone :facepalm:

> you do not have to draw full bone when user does click-and-drag. Just draw some points to show some something is going on. ;)

Please verify @morevnaproject . If you want to have more ducks to be added acoording to the length. I think I can do that :thinking: But the present one is good too! Lemme know asap! :D

**Comment by morevnaproject** [comment]
Testing now. ^__^

**Comment by morevnaproject** [comment]
Can you please add a dashed line, which connecting two ducks? See creation of Linear Gradient with GradientTool for example.

**Comment by Aa20475** [comment]
Okay!! :D

**Comment by Aa20475** [comment]
I did it! Please check!

**Comment by morevnaproject** [comment]
Looks good to me. Thank you!

**Comment by Aa20475** [comment]
Hey! I've found a bug in this functionality and I'm unable to figure out why this is happening.

[Here is the link to the video](https://youtu.be/ToCMQCjeNZk)

**Comment by morevnaproject** [comment]
Should you write proper `refresh_ducks()` function?

![screenshot_003](https://user-images.githubusercontent.com/332868/88459067-9360f580-cebc-11ea-959a-442d7a0bc20f.png)

**Comment by morevnaproject** [comment]
Well, scratch my previous comment. This won't help you.

**Comment by morevnaproject** [comment]
I suggest to add printing of debug messages on click/drag/release events to see which positions are reported by events.

Also, I have noticed you use multiple variables, which hold same information. Probably it is worth to reduce them?
![screenshot_004](https://user-images.githubusercontent.com/332868/88459580-a8d81e80-cec0-11ea-8701-22a3e7153447.png)

One more issue found: if you start creating a bone and drag its tip to some point of another (existing) bone, then no bone is created (the existing bone is made active instead) - https://youtu.be/Eq8-_ENdkbw

**Comment by Aa20475** [comment]
Ohh right will fix them!

**Comment by Aa20475** [comment]
>One more issue found: if you start creating a bone and drag its tip to some point of another (existing) bone, then no bone is created (the existing bone is made active instead) - https://youtu.be/Eq8-_ENdkbw

Oh yeah! The code I used for duck detection is old so I didn't update it.. Fixed it in next commit.

**Comment by morevnaproject** [comment]
> It says the video is private :eyes:

Sorry, my mistake. Fixed now. ^__^

> Hey! I've found a bug in this functionality and I'm unable to figure out why this is happening.

I have tested and it is fixed now. Congrats!



> > One more issue found: if you start creating a bone and drag its tip to some point of another (existing) bone, then no bone is created (the existing bone is made active instead) - https://youtu.be/Eq8-_ENdkbw
> 
> Oh yeah! The code I used for duck detection is old so I didn't update it.. Fixed it in next commit.

There is new issue now: when I try to move control points of existing bones it creates new bone sometimes.
See video - https://youtu.be/z4A7T8QcLSI

**Comment by morevnaproject** [comment]
Hi! I have tested latest commit (cae5dcf14d1e) and there is still problem with creating bones in certain situations. Since we already got visible bone working I am closing this issue and opened new one #1592.
