### ISSUE TITLE
 [Skeleton Tool] Undo not working for Skeleton Tool

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1537]
Currently it is not possible to undo actions made by Skeleton Tool.

**Comment by Aa20475** [comment]
Hey!

As you suggested, I've referred to `canvas_interface` to see what I can do. So I thought it this way:

- Add a signal that is emitted whenever active bone is changed.
- Connect that signal in `canvas_view` in which I'll add a function that'll process the active bone signal.
- Add a new action `valuedescsetactivebone`, as you said, which will trigger that signal.
- Use passive grouper to perform CreateChild and SetActiveBone together.

I think this can solve the issue. But does it match with the coding style of Synfig? Please say yours views on this. :D

**Comment by morevnaproject** [comment]
I suggest to make it this way:

Check `CanvasViewUIInterface` class -
![screenshot_001](https://user-images.githubusercontent.com/332868/86938695-e1f75b80-c16a-11ea-91e8-4e8371ed4a3f.png)

This is a class which is returned when action call `get_canvas_interface()`.

You can add `set_active_bone` function to `CanvasViewUIInterface` class.
`CanvasViewUIInterface` has access to `CanvasView`, so it can set active bone.

This way you will not need to implement `valuedescsetactivebone` action. ^__^

**Comment by Aa20475** [comment]
>This is a class which is returned when action call get_canvas_interface().

I thought `get_canvas_interface()` returns `CanvasInterface` from here. :thinking: 

![image](https://user-images.githubusercontent.com/35968657/87075991-c52c5800-c23e-11ea-907b-db72ccfaee23.png)

**Comment by morevnaproject** [comment]
> This is a class which is returned when action call `get_canvas_interface()`.

> I thought `get_canvas_interface()` returns `CanvasInterface` from here. thinking

Oh, you right. I made a mistake. The correct is to call  `get_canvas_interface()_>get_ui_interface()`.

![screenshot_003](https://user-images.githubusercontent.com/332868/87169618-7512cb80-c2fa-11ea-93dc-5eb395dc2509.png)

After thinking about that again, I think it wasn't very good idea - to modify `CanvasViewUIInterface`.

Maybe you can try to use `signal_value_node_deleted`?
![screenshot_004](https://user-images.githubusercontent.com/332868/87170374-75f82d00-c2fb-11ea-8697-0bae3b24e520.png)

You can create a function in WorkArea class which is responding to this event.

Here is how it is used in `ChildrenTreeStore`:

![screenshot_006](https://user-images.githubusercontent.com/332868/87170745-f159de80-c2fb-11ea-8edb-d132d46c62a9.png)

![screenshot_005](https://user-images.githubusercontent.com/332868/87170470-92946500-c2fb-11ea-96d1-fa095d75c6fc.png)

**Comment by Aa20475** [comment]
Hey! 

This works! But still the user can't undo setting of active bone. Do you think we need to make a separate action for it?

**Comment by morevnaproject** [comment]
Works perfectly! Congratulations!

> But still the user can't undo setting of active bone. Do you think we need to make a separate action for it?

I think it is okay that user can't undo setting of active bone. This is not necessary.

Closing this issue.

**Comment by Aa20475** [comment]
OMG! I just added that :grimacing:  Also, as `valuedesccreatechildbone` is derived from `super` we can't implement `undo()` :cry:  So I had to make a new action and add it into createChildBone. There is still one issue though, undoing the create_layer action is crashing Synfig. I'll try to fix it, only if you want me to :eyes: :sweat_smile:  Else I'll revert it back.

**Comment by Aa20475** [comment]
I fixed the undo tooo! We can revert back if you want.. but I think this active bone undo will be useful too :thinking:

**Comment by morevnaproject** [comment]
Ah, well, that's great! Let me test it to see how it works... Thank you!

**Comment by morevnaproject** [comment]
I have tested it and I like the way it works. This is actually useful to  have additional action for "Set Active Bone". Thanks and congrats! ^__^
