### ISSUE TITLE
[Skeleton Tool] Unable to activate bone

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1538]
I am unable to set active bone at some circumstances. Here I am attaching file ([set-active-bone-bug.sifz.zip](https://github.com/synfig/synfig/files/4857180/set-active-bone-bug.sifz.zip)), where I cannot set this bone as active -
![screenshot_001](https://user-images.githubusercontent.com/332868/86232650-78051200-bbbe-11ea-89f0-04d132eee786.png)
When I click this bone it creates new bone instead.
Video - https://youtu.be/2x51K-oBFRw

**Comment by Aa20475** [comment]
@morevnaproject  Can you please verify now? Check PR #1485

**Comment by morevnaproject** [comment]
Testing now!

**Comment by morevnaproject** [comment]
It works good well now, thank you! ^__^

**Comment by morevnaproject** [comment]
BTW, I like that the active bone is highlighted with yellow color now. ^__^

**Comment by Aa20475** [comment]
I actually made that change a long time back, I forgot to push it :grimacing:  :sweat_smile:  Thanks! :D
