### ISSUE TITLE
[Skeleton Tool]  Implement "Set as Parent to Active Bone" command

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1539]
As explained here - https://github.com/synfig/synfig/pull/1485#issuecomment-651741917

**Comment by Aa20475** [comment]
Hey... Can you check this too?

**Comment by morevnaproject** [comment]
tested and I can confirm that it has a weird issue with origin.

Also, you have to do additional checks to avoid circular dependencies: i.e. when A parent for B, B parent for C, and C parent for A. ^__~

**Comment by Aa20475** [comment]
Yep will fix that!

**Comment by morevnaproject** [comment]
I have tested latest commit and there is no "Set as Parent to Active Bone" command anymore...

**Comment by Aa20475** [comment]
I fixed that. :sweat_smile:  Working on the origin fix.

>you have to do additional checks to avoid circular dependencies:

and this :v:

**Comment by Aa20475** [comment]
https://github.com/synfig/synfig/pull/1485#issuecomment-650746925

As you mentioned here, I got the global coordinates of the origin with animated matrix of the old parent (which is P here) and then applied the new parent's animated matrix to get the new origin. Did the reverse in Undo. I even fixed the scaling too. So I can't understand what's going wrong. Can you please check?

**Comment by morevnaproject** [comment]
Here is an explanation what you should do - https://youtu.be/6YAGpm0qqw4

**Comment by Aa20475** [comment]
Hey! I actually did the same! But I think we have to also considered that the bones are scaled. I'm trying to figure that out!

**Comment by morevnaproject** [comment]
@Aa20475 You have problem when you apply `scalelx` to origin. If your parent bones are not scaled, then there are no offset after re-parenting.

**Comment by morevnaproject** [comment]
@Aa20475 I suggest to bring into order variable names. This can help you to find mistake. At the moment it is not clear where `old_parent`, where `new_parent` and where `active_bone`.

**Comment by Aa20475** [comment]
Yeah! Sure! Will make that change!

**Comment by Aa20475** [comment]
> you apply scalelx to origin 

What you mean by this @morevnaproject ? :sweat_smile:

**Comment by Aa20475** [comment]
Damn! I made an absolute blunder. I've been doing the right thing from the start. The mistake I was doing was that I was taking the `scalelx` of the child bone instead of the parent. :facepalm:  I think it works fine now!

**Comment by morevnaproject** [comment]
> The mistake I was doing was that I was taking the `scalelx` of the child bone instead of the parent.

Exactly. This is why good variable names can help you. ^__^

**Comment by morevnaproject** [comment]
Also, can you please set more meaningful name to `bone_desc`? Currently it is impossible to determine which bone it is.
![screenshot_007](https://user-images.githubusercontent.com/332868/88287688-d4220880-cd1c-11ea-8fbf-a3e5d857ef1e.png)

**Comment by Aa20475** [comment]
Yes done!

**Comment by morevnaproject** [comment]
It looks better now. I suggest to improve code readability even more in function `Action::ValueDescBoneSetParent::perform()`:

1. `new_parent_bone_desc.get_value(time).get(Bone()).get_scalelx()` - make this a variable (`new_parent_scale`), just like `old_parent_scale`.
2. `angle+=old_parent_angle-new_parent_angle;` - I suggest to split this into two lines:
   - `angle+=old_parent_angle`
   - `angle-=new_parent_angle`
... and put last line before `if(child_bone->set_link("parent",...` line.

This will make code easier to understand.

And same should be done for `Action::ValueDescBoneSetParent::undo()` function.

**Comment by morevnaproject** [comment]
Completed!
