### ISSUE TITLE
[Skeleton Tool]  Implement functionality of "Default Bone Width" parameter

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1541]
![screenshot_006](https://user-images.githubusercontent.com/332868/86791576-e270f300-c093-11ea-9063-ccbb506d6842.png)

**Comment by Aa20475** [comment]
Please verify this @morevnaproject . PR #1485

**Comment by morevnaproject** [comment]
It is working now. Thank you!

![screenshot_006](https://user-images.githubusercontent.com/332868/87038005-538ce380-c217-11ea-9b4b-b165b0ebba77.png)
