### ISSUE TITLE
[Skeleton Tool] Bones placed incorrectly when Skeleton Layer is transformed

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1542]
When Skeleton Layer is placed inside of transformed group then tool places bones incorrectly.

Demonstration video - https://youtu.be/8iSq5Yg5fjI

**Comment by Aa20475** [comment]
Hey! Can you help me with this?

**Comment by morevnaproject** [comment]
You need to take into account transformation, which is defined by the parent group.

So, when group is transformed then Skeleton Layer residing in different coordinates, than workarea coordinates.
That means you need to apply reverse transformation to your coordinates.

I suggest to take a look at code of Circle Tool as example of how this done -
![screenshot_002](https://user-images.githubusercontent.com/332868/86940266-c8efaa00-c16c-11ea-9113-931e582e3b11.png)

**Comment by Aa20475** [comment]
So does this have effect on the parent bones `animated_matrix`  too?

**Comment by morevnaproject** [comment]
`animated_matrix` is calculated in coordinates _inside_ of the group.
So, you should apply reverse transformation of `curr_transfrom_stack` to `animated_matrix`.

**Comment by morevnaproject** [comment]
Any progress on this? ^__^

**Comment by Aa20475** [comment]
I actually focussed on the other smaller ones. I'll finish it today! :sweat:

**Comment by Aa20475** [comment]
Hey! I need a bit more assistance on this one. I've explored all the codes related to `transformstack`  and `transform`. They have `perform` and `unperform` functions which apply the respective transformations. What do you actually mean by applying it's back transformation to `animated_matrix` given it's a matrix? 🤧 I do understand Affine transformations and everything. But I'm unable to find a connection here.

**Comment by morevnaproject** [comment]
Did you examined how this is done in Circle Tool?

> applying it's back transformation to animated_matrix

You do not need it to apply  to animated matrix. Apply it to coordinates of point where user clicks.

**Comment by Aa20475** [comment]
Yess! I did checkout other tools.. I even tried applying it to individual points. Maybe I'm doin something wrong here. I'll do some testing and push the chnages

**Comment by Aa20475** [comment]
I don't know why but it's working ! I'm sure I made those changes before but it didn't work then. Maybe the bugs I was seeing are in the actions that I wrote (which were imperfect then :P)  Please verify @morevnaproject

**Comment by morevnaproject** [comment]
I have tested and found an issue. For some reason, when Skeleton Layer is created it is placed at the top of all layers. The correct behavior is to place it on top of currently selected layer. 

I guess this is why you had problems with the changes you made before. See this video - https://youtu.be/H3g8yrBzACc

**Comment by Aa20475** [comment]
>I have tested and found an issue. For some reason, when Skeleton Layer is created it is placed at the top of all layers. The correct behavior is to place it on top of currently selected layer.

I fixed this.

**Comment by morevnaproject** [comment]
It works as expected now. Thank you!
