### ISSUE TITLE
[Skeleton Tool] Allow to create Skeleton Deformation layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1543]
There should be an option to create Skeleton Deformation layer using Skeleton Tool.

The option can be like a choice:

![screenshot_007](https://user-images.githubusercontent.com/332868/86797748-3da5e400-c09a-11ea-9e3b-7bab1ad1ddb1.png)

This choice takes in effect in 2 situation:
1. When currently selected layer is not Skeleton or Skeleton Deformation (then it will create a layer of chosen type when user creates first bone).
2. When user clicks "New Skeleton Layer" button (see #1535).

**Comment by Aa20475** [comment]
Does this apply to normal click actions too?

**Comment by morevnaproject** [comment]
Yes, this apply when user creates first bone and when currently selected layer is not Skeleton or Skeleton Deformation. User can create first bone with click or click-and-drag.

**Comment by Aa20475** [comment]
Please verify this in the latest commit if these are working as you said.  :D @morevnaproject

**Comment by morevnaproject** [comment]
Hi! Tested it and there is one issue:

It shouldn't create any layer when user has some skeleton layer selected (Regular or Deformation).
It should work with currently selected layer in this case.

It should create new layer (of chosen type) only when user has non-skeleton layer selected. ^__^

**Comment by Aa20475** [comment]
Ohh I thought it the other way. If he chooses a skeleton layer and is working with a deform, then we'll make a skeleton layer 🤔 I guess this will more convenient?

**Comment by morevnaproject** [comment]
Yes, the approach I proposed in https://github.com/synfig/synfig/issues/1543#issuecomment-656085991 is more convenient for user.
The tool should adapt to current situation.

Otherwise user has to watch which type of layer he got selected in Tool Options Panel and compare it with currently selected layer. This is not convenient for user.

**Comment by Aa20475** [comment]
All rightey! Will make the change!

**Comment by Aa20475** [comment]
Please verify this too. :v:

**Comment by morevnaproject** [comment]
I have tested and now it works as expected, thank you!

There is also one more thing to fix:

Consider that in Skeleton Deformation layer every bone is actually a pair of two bones:
![screenshot_001](https://user-images.githubusercontent.com/332868/87321448-704a5380-c556-11ea-8a2f-e0fc51a17baa.png)

First bone is "initial position" - i.e. bone placement at undeformed status. This is same as "rest pose" concept in Blender.
Second bone defines bone position at deformed status.

The first bone becomes visible when Skeleton Deformation Layer is disabled -
![screenshot_002](https://user-images.githubusercontent.com/332868/87321679-bef7ed80-c556-11ea-961b-f2c1823e8f93.png)

And when Skeleton Tool used to create new bone for Skeleton Deformation Layer, then it should set location/angle/length for both bones from the pair. ^__^

**Comment by Aa20475** [comment]
Okay I didn't know that 😬 will fix it!!

**Comment by morevnaproject** [comment]
Yes, that's functionality details I didn't told you earlier, so you can concentrate on "one small step at once", instead of giving you a "one big task". ^__^

**Comment by morevnaproject** [comment]
It works as expected now with commit 8a2f44b. Thank you!
