### ISSUE TITLE
[Skeleton Tool] Name in Paremeter Panels has no effect

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1546]
![screenshot_005](https://user-images.githubusercontent.com/332868/87038116-7c14dd80-c217-11ea-9832-2f693345a842.png)

Name field should define name of newly created layer. ^__^

**Comment by Aa20475** [comment]
Alright! Will fix that! 😅

**Comment by Aa20475** [comment]
It's working :+1:  Please verify now

**Comment by morevnaproject** [comment]
Hi! I have tested latest commit. It works when I click Create layer button. But it doesn't works in this case - https://youtu.be/P6sUmXi8_-Q

**Comment by Aa20475** [comment]
:facepalm:  I missed that case.. Will make that change!

**Comment by Aa20475** [comment]
Please check it now.

**Comment by morevnaproject** [comment]
Works perfectly now! Thank you!
