### ISSUE TITLE
[Skeleton Tool] When user clicks on workarea place bone vertically

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1547]
Currently, when user clicks on workarea the tool creates a bone and it is rotated horizontally -
![screenshot_007](https://user-images.githubusercontent.com/332868/87049041-ad48da00-c226-11ea-95c2-2e2858806042.png)

It is more common for animation software when bone is aligned vertically.
So, it will be better to align new bone like this -
![screenshot_008](https://user-images.githubusercontent.com/332868/87049142-cce00280-c226-11ea-9f3f-f1864c2997ce.png)

**Comment by Aa20475** [comment]
Hey!

Please verify this. Except for when a skeleton layer is created normally or when bone is drawn, all the other bones will be vertical.

**Comment by morevnaproject** [comment]
It works now, thank you! ^__^
