### ISSUE TITLE
[Skeleton Tool] Bone should become active when user clicks on any of its controls

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1549]
When user clicks on (or modifies) any bone's control point (origin/angle/length) then that bone should become active.

**Comment by Aa20475** [comment]
So.. ducks will have the same function but when the user uses a duck to change the bone.. the bone is set to active?

**Comment by morevnaproject** [comment]
Yes. I think this is logical - the last touched bone is marked as "active".

The second reason for that is that sometimes it is hard to click on bone to activate it (sometimes I mis-click and as result new bone is created). Clicking on duck is simpler to hit. ^__^

**Comment by morevnaproject** [comment]
Hi! I tested last commit in skeleton_tool branch (8a2f44b9e2725cdecc137).
The bone is highlighted when I click its control point, but it doesn't really set as active. Here is a video illustrating the problem - https://youtu.be/RH2NPuTf4Ug

**Comment by Aa20475** [comment]
Ohhh!! I thought I did that! Okay! Will check it out!

**Comment by morevnaproject** [comment]
Also, please try to avoid doing 2 or more fixes in one commit. In 8a2f44b there are fixes for two issues at once and that makes hard to understand the changes. One commit for one fix is always a good idea. ^__^

**Comment by Aa20475** [comment]
hey! Please test this in the latest commit!

**Comment by morevnaproject** [comment]
Works perfectly now! Thank you!
