### ISSUE TITLE
[Skeleton Tool] Trigger visibility of Width Points depending on conditions

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1556]
Notice, when we use Width Tool, Synfig automatically enables visibility of Width control points and disables all other control points. See in this video - https://youtu.be/eOPvFRg0FbQ

When constructing Skeleton Deformation layer the visibility of Wodth Points is also very important.

So, I suggest that the Skeleton Tool will enable visibility of Width control points automatically when user works with  Skeleton Deformation layer (all other control points remain visible).

Question: When Width control points should become visible?
1. When active layer is Skeleton Deformation Layer.
2. When user clicks "Create Layer" button while the option "Skeleton Deformation Layer" is activated.
![screenshot_004](https://user-images.githubusercontent.com/332868/87325888-38dea580-c55c-11ea-9d67-800cf66aa682.png)

**Comment by Aa20475** [comment]
Hey! I fixed this. Can you check it?!

**Comment by morevnaproject** [comment]
Hi! I have tested and found one issue: can we get back to previous state (previous set of enabled ducks) when other tool activated? Just like with Width Tool - https://youtu.be/vPBUhes2YxU

**Comment by Aa20475** [comment]
Yes! Do you want me to push it to the review branch?

**Comment by morevnaproject** [comment]
No, please push your changes to "skeleton_tool2" (you will need to rebase it on top of "skeleton_tool"). ^__^

**Comment by Aa20475** [comment]
Okay! 😃

**Comment by morevnaproject** [comment]
I have tested latest changes and it works well now. There is only one issue remaining - for some reason the buttons on toolbar are not always updated -
![screenshot_001](https://user-images.githubusercontent.com/332868/89313301-86a18600-d6a2-11ea-8bdc-a5ff670b4316.png)

For example, they are not updated after I create new Skeleton Deformation layer, I have recorded a video about this - https://youtu.be/F6OW_4HfF2w

**Comment by Aa20475** [comment]
Okay! Checking!

**Comment by morevnaproject** [comment]
Hi! I have tested PR #1616 - it fixes issue with buttons on toolbar. But when I switch from Bone Tool to Arrow Tool it doesn't restores previous state (previous set of enabled ducks).

Video - https://youtu.be/nmVn3nugJhg
