### ISSUE TITLE
Synfig's Onion Skin Works Differently

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#1562]
**Synfig version & platform**:
1.3.15 on Win10 (64bit)

**Issue description**:
Instead of showing onion skins for **Only Keyframes**, Synfig's onion skin setting shows onion skins of **Every Frame**,

I'm not sure if this is a bug (i'm pretty sure it is), but i'll post it anyway...

Here's an example on version stable 1.2.2, with onion skin turned on and showing just 1 past keyframe, and the time slider was positioned on 2nd keyframe:
![1-2-2](https://user-images.githubusercontent.com/25135159/87595227-6a9c6b80-c718-11ea-956c-937934b79b0b.jpg)

and here's the same onion skin setting but on synfig dev version 1.3.15. Notice how it **shows onion skin for Previous Frame instead of Previous Keyframe**
![1-3-15](https://user-images.githubusercontent.com/25135159/87595329-928bcf00-c718-11ea-98a3-c3178f9a1290.jpg)

Found first by tawatoons recently over in this synfig forum thread :
https://forums.synfig.org/t/broken-onion-skin-in-synfig-1-3-14/11192
(they also included the test file for this issue by the way)
I'm just sending the ticket for this issue, that's all ._.v

But i've confirmed that this also happens on my part as well

**Comment by morevnaproject** [comment]
Yes, onionskin code was re-written and now it works differently. The rewriting wasn't completed, so someone still  need to improve this functionality (I think there should be options on how to display onionskin).

**Comment by petersteier** [comment]
This is a game breaker for me; I will go back to version 1.2.0, until it  is fixed.

**Comment by ebarranco** [comment]
Yeah @petersteier ! working "differently" is not the right word for me, neither. Onion skin doesn't work correctly it's more appropriate.

**Comment by petersteier** [comment]
Interrestingly, a lot of things work almost perfect with 1.2.0 (e.g. dual screens, workspace widget), but no longer with 1.2.2). For me, 1.2.0 is an acceptable solution, I do not know the new 1.4.0 features. Generally, Synfig is a impressive piece of good work.

**Comment by morevnaproject** [comment]
Linked issue: #600

**Comment by FirasH** [comment]
I've never used Onion skin but it seems like a fundamental tool for complex animations, so I spent a bit of time studying how this works in Synfig Studio.

> Yes, onionskin code was re-written and now it works differently. The rewriting wasn't completed, so someone still need to improve this functionality (I think there should be options on how to display onionskin).

@morevnaproject I've made some tests with current master and I was able to make onion skin work with keyframes only.
It shouldn't be very hard to add the option you mentioned that allows the user to choose how to display it (a button in the toolbar as a temporary solution?).

From what I've seen in the code Onion skin basically stacks the rendered canvases at the specified times on top of each other varying their opacity and arbitrary frame numbers could be added to this stack. If a small interface is added to the Timetrack it should be possible to create an interface like the one of OpenToonz (mentioned in the linked issue).

Though I currently have no idea how to recreate that interface...
@rodolforg any idea how to add that on top of timetrack?

**Comment by rodolforg** [comment]
>  @rodolforg any idea how to add that on top of timetrack?

The widget that displays time ticks is Widget_Canvastimeslider, a Gtk::DrawingArea.
It's height is indirectly set by the height of the treeview header of Parameter Panel.

You'll have to first (learn how / code) to draw the onion skin boundaries. Later you implement how to change it via, e.g., `on_button_press_event()`, or by making use of SelectDragHelper (but maybe it's too much for this implementation).

**Comment by ice0** [comment]
I think it's better to split this task into smaller ones:
1) Add ability for onion skin to switch between frame/keyframe modes 
2) Timeline stuff

**Comment by morevnaproject** [comment]
> @morevnaproject I've made some tests with current master and I was able to make onion skin work with keyframes only.
> It shouldn't be very hard to add the option you mentioned that allows the user to choose how to display it (a button in the toolbar as a temporary solution?).

Yes, it would be nice to start with adding an option to make onion skin work with keyframes only.

I agree with @ice0 that it's better to split the task into smaller ones.

**Comment by morevnaproject** [comment]
Resolved in Synfig version 1.5.1 - https://www.synfig.org/2021/10/30/synfig-studio-1-5-1-released/
