### ISSUE TITLE
[Windows] Plugins are failed to execute when Synfig started with "--console" parameter.

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1569]
**Synfig version & platform**:
master branch, commit 2b0a8874afafb0881a466e595d99cad74d2fafdd

**Issue description**:
Steps to reproduce:
1. Start Synfig Studio with "--console" parameter:
![screenshot_005](https://user-images.githubusercontent.com/332868/87956703-8a95ab80-cad9-11ea-8050-e41b29932da2.png)
2. Open any file and try to launch any plugin. You'll get an error:
![screenshot_006](https://user-images.githubusercontent.com/332868/87956830-aef18800-cad9-11ea-9c0e-c4bd06ecf5e4.png)

The bug doesn't reproducible if started without "--console" parameter.

**Comment by rodolforg** [comment]
My guess is the boolean expression `stderr_str.empty()` shown below:
https://github.com/synfig/synfig/blob/4b7f89beab97bd565df50d7dd559124ebb163b52/synfig-studio/src/gui/pluginmanager.cpp#L354-L360
I don't know why an empty stderr output is a problem. (I don't know what would be normally expected though).

**Comment by morevnaproject** [comment]
The issue seems to be fixed in 1.4.x branch.

I have made a test builds of 1.4.3, here are the links:
- [SynfigStudio-1.4.3-testing-2022.05.03-win32-b02a5.exe](https://cloud.morevnaproject.org/s/iDAgacoRL9DS9XN)
- [SynfigStudio-1.4.3-testing-2022.05.03-win64-b02a5.exe](https://cloud.morevnaproject.org/s/68KifzqxMocNHFE)
