### ISSUE TITLE
[Windows] Plugins are failed to execute for files with non-latin characters

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1570]
**Synfig version & platform**:
master branch, 2b0a8874afafb0881a466e595d99cad74d2fafdd

**Issue description**:
Steps to reproduce:
1. Open any file with non-latin characters.
2. Try to run any plugin. You'll get an error:

![screenshot_007](https://user-images.githubusercontent.com/332868/87957192-29220c80-cada-11ea-866c-6c369c627327.png)

**Comment by ice0** [comment]
This problem will be easy to reproduce for someone who have Windows and can use non-latin characters.

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.

**Comment by ice0** [comment]
Just checked. Problem is still exists.

**Comment by rodolforg** [comment]
@ice0 does the issue exist on master branch?

**Comment by morevnaproject** [comment]
Still reproducible in latest 1.4.3 build.

**Comment by morevnaproject** [comment]
Hmmm... But I have noticed the behavior is different - now it is crashing Synfig instead of giving an error message :-/

Here are links to test builds:
- [SynfigStudio-1.4.3-testing-2022.05.03-win32-b02a5.exe](https://cloud.morevnaproject.org/s/iDAgacoRL9DS9XN)
- [SynfigStudio-1.4.3-testing-2022.05.03-win64-b02a5.exe](https://cloud.morevnaproject.org/s/68KifzqxMocNHFE)

**Comment by rodolforg** [comment]
What about now?
