### ISSUE TITLE
Existing files are overwitten if warning dialog is closed

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1572]
**Synfig version**:
master f4a59e9

**Issue description**:
1. Create a new animation
2. Export to an arbitrary target (e.g. .png or .mp4)
3. Export again to the a target with the same name in order to display the warning dialog about overwriting an existing file
4. Close the dialog (press `Esc`)

Synfig will export the target overwriting the existing files.

It should work like `Use Another Name...`

**Comment by FirasH** [comment]
Same happens for all `App::dialog_message_2b` dialogs

**Comment by FirasH** [comment]
This is likely the problematic code:
https://github.com/synfig/synfig/blob/efbef4f708085982dc1a5a06e98fcd800cb41a10/synfig-studio/src/gui/app.cpp#L3617

Looking into it...

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.
