### ISSUE TITLE
[Linux] Synfig Studio fails to load its GUI

### ISSUE THREAD

**Issue by saurabh-ramola** [synfig/synfig#1576]
**Synfig version & platform**:
Synfig Version : 7ece93c86ea09475ea123fda59a02e588f3c5997
Platform : Ubuntu 16.04 LTS
**Issue description**:
Synfig Studio fails to load the GUI outputting this error. 
**ERROR**
saurabh@saurabh-GL552VW:~/GSOC/synfig$ ./_production/build/bin/synfigstudio

   synfig studio -- starting up application...

synfig(5130) [04:36:15  IST] info: Starting Subsystem "Sound"
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Types"
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Rendering"
synfig(5130) [04:36:15  IST] info: rendering threads 8
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Modules"
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Layers"
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Targets"
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Importers"
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Cairo Importers"
synfig(5130) [04:36:15  IST] info: Starting Subsystem "Thread Pool"
synfig(5130) [04:36:15  IST] warning: Cannot open ./synfig_modules.cfg
synfig(5130) [04:36:15  IST] warning: Cannot open /home/saurabh/.local/share/synfig/synfig_modules.cfg
synfig(5130) [04:36:15  IST] info: Loading modules from /home/saurabh/GSOC/synfig/_production/build/etc/synfig_modules.cfg
synfig(5130) [04:36:15  IST] info: Loading modules from /home/saurabh/GSOC/synfig/_production/build/etc/synfig_modules.cfg
synfig(5130) [04:36:15  IST] info: Loading lyr_std..
synfig(5130) [04:36:15  IST] info: Attempting to register "lyr_std"
synfig(5130) [04:36:15  IST] info: Found module "lyr_std"
synfig(5130) [04:36:15  IST] info: Success for "lyr_std"
synfig(5130) [04:36:15  IST] info: Loading lyr_freetype..
synfig(5130) [04:36:15  IST] info: Attempting to register "lyr_freetype"
synfig(5130) [04:36:15  IST] info: Found module "lyr_freetype"
synfig(5130) [04:36:15  IST] info: Initializing FreeType...
synfig(5130) [04:36:15  IST] info: Success for "lyr_freetype"
synfig(5130) [04:36:15  IST] info: Loading mod_geometry..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_geometry"
synfig(5130) [04:36:15  IST] info: Found module "mod_geometry"
synfig(5130) [04:36:15  IST] info: Success for "mod_geometry"
synfig(5130) [04:36:15  IST] info: Loading mod_gradient..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_gradient"
synfig(5130) [04:36:15  IST] info: Found module "mod_gradient"
synfig(5130) [04:36:15  IST] info: Success for "mod_gradient"
synfig(5130) [04:36:15  IST] info: Loading mod_particle..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_particle"
synfig(5130) [04:36:15  IST] info: Found module "mod_particle"
synfig(5130) [04:36:15  IST] info: Success for "mod_particle"
synfig(5130) [04:36:15  IST] info: Loading mod_example..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_example"
synfig(5130) [04:36:15  IST] info: Found module "mod_example"
synfig(5130) [04:36:15  IST] info: Success for "mod_example"
synfig(5130) [04:36:15  IST] info: Loading mod_gif..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_gif"
synfig(5130) [04:36:15  IST] info: Found module "mod_gif"
synfig(5130) [04:36:15  IST] info: Success for "mod_gif"
synfig(5130) [04:36:15  IST] info: Loading mod_imagemagick..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_imagemagick"
synfig(5130) [04:36:15  IST] info: Found module "mod_imagemagick"
synfig(5130) [04:36:15  IST] info: Success for "mod_imagemagick"
synfig(5130) [04:36:15  IST] info: Loading mod_magickpp..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_magickpp"
synfig(5130) [04:36:15  IST] info: Found module "mod_magickpp"
synfig(5130) [04:36:15  IST] info: Success for "mod_magickpp"
synfig(5130) [04:36:15  IST] info: Loading mod_mng..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_mng"
synfig(5130) [04:36:15  IST] info: Found module "mod_mng"
synfig(5130) [04:36:15  IST] info: Success for "mod_mng"
synfig(5130) [04:36:15  IST] info: Loading mod_noise..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_noise"
synfig(5130) [04:36:15  IST] info: Found module "mod_noise"
synfig(5130) [04:36:15  IST] info: Success for "mod_noise"
synfig(5130) [04:36:15  IST] info: Loading mod_filter..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_filter"
synfig(5130) [04:36:15  IST] info: Found module "mod_filter"
synfig(5130) [04:36:15  IST] info: Success for "mod_filter"
synfig(5130) [04:36:15  IST] info: Loading mod_ffmpeg..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_ffmpeg"
synfig(5130) [04:36:15  IST] info: Found module "mod_ffmpeg"
synfig(5130) [04:36:15  IST] info: Success for "mod_ffmpeg"
synfig(5130) [04:36:15  IST] info: Loading mod_bmp..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_bmp"
synfig(5130) [04:36:15  IST] info: Found module "mod_bmp"
synfig(5130) [04:36:15  IST] info: Success for "mod_bmp"
synfig(5130) [04:36:15  IST] info: Loading mod_dv..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_dv"
synfig(5130) [04:36:15  IST] info: Found module "mod_dv"
synfig(5130) [04:36:15  IST] info: Success for "mod_dv"
synfig(5130) [04:36:15  IST] info: Loading mod_png..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_png"
synfig(5130) [04:36:15  IST] info: Found module "mod_png"
synfig(5130) [04:36:15  IST] info: Success for "mod_png"
synfig(5130) [04:36:15  IST] info: Loading mod_ppm..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_ppm"
synfig(5130) [04:36:15  IST] info: Found module "mod_ppm"
synfig(5130) [04:36:15  IST] info: Success for "mod_ppm"
synfig(5130) [04:36:15  IST] info: Loading mod_openexr..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_openexr"
synfig(5130) [04:36:15  IST] info: Found module "mod_openexr"
synfig(5130) [04:36:15  IST] info: Success for "mod_openexr"
synfig(5130) [04:36:15  IST] info: Loading mod_jpeg..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_jpeg"
synfig(5130) [04:36:15  IST] info: Found module "mod_jpeg"
synfig(5130) [04:36:15  IST] info: Success for "mod_jpeg"
synfig(5130) [04:36:15  IST] info: Loading mod_libavcodec..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_libavcodec"
synfig(5130) [04:36:15  IST] warning: Unable to find module "mod_libavcodec" (file not found)
synfig(5130) [04:36:15  IST] info: Loading mod_yuv420p..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_yuv420p"
synfig(5130) [04:36:15  IST] info: Found module "mod_yuv420p"
synfig(5130) [04:36:15  IST] info: Success for "mod_yuv420p"
synfig(5130) [04:36:15  IST] info: Loading mod_svg..
synfig(5130) [04:36:15  IST] info: Attempting to register "mod_svg"
synfig(5130) [04:36:15  IST] info: Found module "mod_svg"
synfig(5130) [04:36:15  IST] info: Success for "mod_svg"
synfig(5130) [04:36:15  IST] info: DONE
synfig(5130) [04:36:15  IST] info: Loading Basic Settings...
synfig(5130) [04:36:15  IST] info: Loading Plugins...
synfig(5130) [04:36:15  IST] info: Loading plugins from /home/saurabh/GSOC/synfig/_production/build/share/synfig/plugins
synfig(5130) [04:36:15  IST] info:    Loading plugin: view-unhide-all-layers
synfig(5130) [04:36:15  IST] info:    Loading plugin: lottie-exporter
synfig(5130) [04:36:15  IST] info:    Loading plugin: add-skeleton-simple
synfig(5130) [04:36:15  IST] info: Loading plugins from /home/saurabh/.config/synfig/plugins
synfig(5130) [04:36:15  IST] warning: Can't read plugin directory: Error opening directory '/home/saurabh/.config/synfig/plugins': No such file or directory
synfig(5130) [04:36:15  IST] info: Init UI Manager...
synfig(5130) [04:36:15  IST] info: Init Dock Manager...
synfig(5130) [04:36:15  IST] info: Init State Manager...
synfig(5130) [04:36:15  IST] info: Init Main Window...
synfig(5130) [04:36:15  IST] info: Init Toolbox...
synfig(5130) [04:36:15  IST] info: Init About Dialog...
synfig(5130) [04:36:15  IST] info: Init Tool Options...
synfig(5130) [04:36:15  IST] info: Init History...
synfig(5130) [04:36:15  IST] info: Init Canvases...
synfig(5130) [04:36:15  IST] info: Init Keyframes...
synfig(5130) [04:36:15  IST] info: Init Layers...
synfig(5130) [04:36:15  IST] info: Init Parameters...
synfig(5130) [04:36:15  IST] info: Init MetaData...
synfig(5130) [04:36:15  IST] info: Init Library...
synfig(5130) [04:36:15  IST] info: Init Info...
synfig(5130) [04:36:15  IST] info: Init Navigator...
synfig(5130) [04:36:15  IST] info: Init SoundWave...
synfig(5130) [04:36:15  IST] info: Init Timetrack (old)...
synfig(5130) [04:36:15  IST] info: Init Timetrack...
synfig(5130) [04:36:16  IST] info: Init Curve Editor...
synfig(5130) [04:36:16  IST] info: Init Layer Sets...
synfig(5130) [04:36:16  IST] info: Init Color Dialog...
synfig(5130) [04:36:16  IST] info: Init Gradient Dialog...
synfig(5130) [04:36:16  IST] info: Init DeviceTracker...
synfig(5130) [04:36:16  IST] info: Init ModPalette...
synfig(5130) [04:36:16  IST] info: Init Setup Dialog...
synfig(5130) [04:36:16  IST] info: Init Input Dialog...
synfig(5130) [04:36:16  IST] info: Loading Custom Workspace List...
synfig(5130) [04:36:16  IST] info: Init auto recovery...
synfig(5130) [04:36:16  IST] info: Loading Settings...
synfig(5130) [04:36:16  IST] info: Init Tools...
synfig(5130) [04:36:16  IST] info: Checking auto-recover...
synfig(5130) [04:36:16  IST] info: Done.

(synfigstudio:5130): Gtk-WARNING **: Allocating size to gtkmm__GtkWindow 0x1ab4280 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

**Comment by saurabh-ramola** [comment]
It was giving the same error on a previous build so I updated it to the latest build but it is still giving the same error.

**Comment by rodolforg** [comment]
That last warning appears to me, but it opens normally.
I don't have the first warning though (regarding Sound Subsystem).

**Comment by saurabh-ramola** [comment]
@rodolforg I was able to fix the warning regarding the Sound Subsystem, but even now it gives the same result minus the Sound System warning. The output log is same minus the Sound System warning and it fails to render the GUI.
I used ./2-build-production.sh and the build completed without any problem.

**Comment by ice0** [comment]
@saurabh-ramola can you make a short video showing that is happens?

**Comment by saurabh-ramola** [comment]
@ice0

**Comment by saurabh-ramola** [comment]
@ice0 This is what happens when I run _production/build/bin/synfigstudio. It was working perfectly fine till two days ago.
https://youtu.be/3DyPIKumwew

**Comment by ice0** [comment]
Hmm, looks like it hangs on start.

Can you try debug build?

Also will be nice if you can get stack using 
```
apt install elfutils
eu-stack -p <synfig_pid>
```
and post it here

**Comment by saurabh-ramola** [comment]
Here is the stack : 
![image](https://user-images.githubusercontent.com/31828811/88302981-20247b80-cd24-11ea-97c0-c195e323eeec.png)

I will try the debug build for now.

**Comment by rodolforg** [comment]
@saurabh-ramola you can also investigate what was the problematic commit via [git bisect](https://git-scm.com/docs/git-bisect).

Basically, you mark what was your latest known good commit and current as a bad one.
The git will be automatically checking out intermediate commits (somewhat like quick-sort does) letting you build from that point, check if it's good or bad and mark this situation for the current commit.
Then git checks out another commit, and it goes on and on. ;)

But the page explains better than me lol

**Comment by ice0** [comment]
@saurabh-ramola looks like you need to do
```
sudo eu-stack -p <pid>
```

**Comment by saurabh-ramola** [comment]
@ice0  My bad, had no idea how the command functions :disappointed: . Here is the output log after applying sudo to the command : 

PID 4748 - process
TID 4748:
#0  0x00007f76b957f74d poll
#1  0x00007f76ba38238c
#2  0x00007f76ba382712 g_main_loop_run
#3  0x00007f76bb4e0c75 gtk_main
#4  0x000000000050a4e2 main
#5  0x00007f76b94a4830 __libc_start_main
#6  0x00000000005506e9 _start
TID 4749:
#0  0x00007f76b957f74d poll
#1  0x00007f76ba38238c
#2  0x00007f76ba38249c g_main_context_iteration
#3  0x00007f76ade5b41d
#4  0x00007f76ba3a8c55
#5  0x00007f76bd4136ba start_thread
#6  0x00007f76b958b41d __clone
TID 4750:
#0  0x00007f76b957f74d poll
#1  0x00007f76ba38238c
#2  0x00007f76ba38249c g_main_context_iteration
#3  0x00007f76ba3824d9
#4  0x00007f76ba3a8c55
#5  0x00007f76bd4136ba start_thread
#6  0x00007f76b958b41d __clone
TID 4751:
#0  0x00007f76b957f74d poll
#1  0x00007f76ba38238c
#2  0x00007f76ba382712 g_main_loop_run
#3  0x00007f76b7f8e9f6
#4  0x00007f76ba3a8c55
#5  0x00007f76bd4136ba start_thread
#6  0x00007f76b958b41d __clone
TID 4753:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4754:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4755:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4756:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4757:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4758:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4759:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4760:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bda16704 synfig::rendering::RenderQueue::get(int)
#3  0x00007f76bda1689d synfig::rendering::RenderQueue::process(int)
#4  0x00007f76bbbf319d
#5  0x00007f76ba3a8c55
#6  0x00007f76bd4136ba start_thread
#7  0x00007f76b958b41d __clone
TID 4797:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bd8d5e93 synfig::ThreadPool::thread_loop(int)
#3  0x00007f76b9e25c80
#4  0x00007f76bd4136ba start_thread
#5  0x00007f76b958b41d __clone
TID 4798:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bd8d5e93 synfig::ThreadPool::thread_loop(int)
#3  0x00007f76b9e25c80
#4  0x00007f76bd4136ba start_thread
#5  0x00007f76b958b41d __clone
TID 4799:
#0  0x00007f76bd419360 pthread_cond_wait@@GLIBC_2.3.2
#1  0x00007f76b9e2091c std::condition_variable::wait(std::unique_lock<std::mutex>&)
#2  0x00007f76bd8d5e93 synfig::ThreadPool::thread_loop(int)
#3  0x00007f76b9e25c80
#4  0x00007f76bd4136ba start_thread
#5  0x00007f76b958b41d __clone

**Comment by saurabh-ramola** [comment]
@ice0 , completed the debug build and it is still giving me the same result. :(

**Comment by ice0** [comment]
@rodolforg said this commit (https://github.com/synfig/synfig/commit/5862c7611232cb180d8eb2934b17b2f306404f10) can lead to something like this. 

So please try switching to an earlier commit like this (https://github.com/synfig/synfig/commit/2fb1e659f70ede5ba97ff149efdb2b352680a5b1).

**Comment by saurabh-ramola** [comment]
@ice0 , Tried doing this and didn't work. I am assuming there was a problem with my system so I reinstalled Ubuntu. There is no problem now and Synfig Studio is running perfectly now.

**Comment by rodolforg** [comment]
So can we close it?

**Comment by morevnaproject** [comment]
Yes! ^__^
