### ISSUE TITLE
Synfig 1.3.14 Unstable Link to Spline

### ISSUE THREAD

**Issue by turbubestia** [synfig/synfig#1579]
**Synfig 1.3.14 & Window**:

**Issue description**:
If I draw a spline (either line or curved) with more than 2 point and then I link the center of an object to the spline to the object can follow that path the position interpolation in the first segment is fine, from the second to last-1 is that bad, but the last segment is totally unstable and make the application crash sometimes.

![image](https://user-images.githubusercontent.com/33103381/88337936-8ea61100-cd05-11ea-9185-5e95332e50d3.png)

This works fine in 1.2.2.

**Comment by rodolforg** [comment]
Fixed in master.
Testing on tag v1.3.15

**Comment by rodolforg** [comment]
It works fine in next release v1.3.15. Phew :)
@turbubestia please wait for the next development release. It should happen really soon (#1574)

**Comment by rodolforg** [comment]
@turbubestia  Could you please try it? :D https://www.synfig.org/2020/08/01/synfig-studio-1-3-15-released/
If everuthing is ok – or not, please tell us.

**Comment by turbubestia** [comment]
In 1.3.15 it work fine. 👍
