### ISSUE TITLE
[Skeleton Tool] Use dashed outline to display parent-child relationships for bones

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1588]
"Set as Parent to Active Bone" command is working now, but for user the result of this work is not visible intuitively.

I think it should be improved by displaying parent-child relationship between bones, using dashed lines like this -
![screenshot_006](https://user-images.githubusercontent.com/332868/88541987-dd261900-d03f-11ea-907b-cd69ab987041.png)

**Comment by morevnaproject** [comment]
I have tested current status of PR #1605 and I can see that dashed lines correctly connected to bone origin, but not to the tip of previous bone.
![screenshot_001](https://user-images.githubusercontent.com/332868/89422341-65529f80-d75f-11ea-8e15-da7fb7eddd11.png)

I suggest to make a simple test: try to connect origin of child bone with **origin** of parent bone. Can you do that?

**Comment by Aa20475** [comment]
Okay! Will do it asap!

**Comment by Aa20475** [comment]
>I suggest to make a simple test: try to connect origin of child bone with origin of parent bone. Can you do that?

It is working!

**Comment by morevnaproject** [comment]
Okay, now you know correct coordinates of origin point.
Next can you find coordinates of a tip? (relatively to origin)

Please write a formula here how to calculate coordinates of bone tip relatively to bone origin (considering that you know bone length and bone angle)

**Comment by Aa20475** [comment]
`tip = (origin_x + length*cos(angle),origin_y + length*sin(angle))` ?

**Comment by morevnaproject** [comment]
Try this now with your current code.

**Comment by Aa20475** [comment]
It's working!

**Comment by morevnaproject** [comment]
Looks good!
![screenshot_007](https://user-images.githubusercontent.com/332868/89654095-551ef980-d8f2-11ea-9e2c-87b365028e0c.png)

Please resolve issues in PR.

**Comment by rodolforg** [comment]
Wow! Great Job!

**Comment by Aa20475** [comment]
Thank you! :smile:

**Comment by morevnaproject** [comment]
Closed via #1605
