### ISSUE TITLE
Dashed outline rendered incorrectly in non-homogenous mode

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1589]
**Synfig version & platform**:
master branch, 1.3.15

**Issue description**:
Dashed outline rendered incorrectly when homogenous parameter is off.

Sample file - 
[dashes.sifz.zip](https://github.com/synfig/synfig/files/4982099/dashes.sifz.zip)

Here is how it rendered in 1.2.2 -
![screenshot_008](https://user-images.githubusercontent.com/332868/88544113-1b710780-d043-11ea-9a05-15307d4f82c5.png)

Here is result on master and 1.3.15 -
![screenshot_007](https://user-images.githubusercontent.com/332868/88544096-13b16300-d043-11ea-8088-01a99da03778.png)

**Comment by rodolforg** [comment]
I tested the 1.2.2 and homogeneous parameter doesn't affect dashes.
Should they always behave like this?

**Comment by morevnaproject** [comment]
Yes, in 1.0.2 and 1.2.2 homogeneous parameter do not affects dashes.
We need the same behavior. Thank you! ^__^
