### ISSUE TITLE
Duplicate ignores all layers except the first one

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#1590]
### Issue description
Say you have Duplicate layer over two others layers such as Translate and Circle. Each of layers have special conversions: Translate shifts X value with each iteration, Circle changes color with each iteration. The problem is that only Translate layer properly calculates duplicate conversion, the other one is ignored.

This picture illustrates the problem:
![DupBug1315](https://user-images.githubusercontent.com/28569334/88574564-321b5c80-d04b-11ea-8b0f-5462ad1f3c29.PNG)

Pay attention that in 1.0.2 version not only circle shifts its value, but also changes color.
Test sif file is also attached.
[DupBug.zip](https://github.com/synfig/synfig/files/4983629/DupBug.zip)

### Affected versions
Synfig 1.2.2 and higher.

**Comment by rodolforg** [comment]
Confirmed.
Via git log, the change in layer_duplicate between 1.0 and 1.2 is the Cobra renderer implementation.

**Comment by rodolforg** [comment]
@Svarov-RZM , if you want to/can test it… here it is :)

**Comment by Svarov-RZM** [comment]
@rodolforg 
I've tested your branch, duplicate layer now works as expected. Additionally, it fixes particle template which I am a huge fan of. Many thanks for solving this issue, you rock man!

**Comment by rodolforg** [comment]
>  it fixes particle template

I don't have any idea what it is, but I'm glad it works now. lol

**Comment by morevnaproject** [comment]
> I don't have any idea what it is, but I'm glad it works now. lol

https://wiki.synfig.org/Particles_V2.0 ^__^

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.
