### ISSUE TITLE
[Skeleton Tool] Bone not created when mouse button released over existing bone point

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1592]
Bone is not created if user release mouse button when cursor is over control point of existing bone.

Video - https://youtu.be/y6FIGO9u2Eg

**Comment by Aa20475** [comment]
Thanks for pointing this out! Will fix it!

**Comment by Aa20475** [comment]
Fixed. Please test this.

**Comment by morevnaproject** [comment]
Works good now! Thank you. ^__^
