### ISSUE TITLE
Markers in Sound Panel are too big

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1601]
**Synfig version & platform**:
1.3.15

**Issue description**:

![screenshot_008](https://user-images.githubusercontent.com/332868/89190387-95693980-d5cb-11ea-84b9-36d585e100d9.png)

Details - https://forums.synfig.org/t/why-is-the-keyframe-marker-size-in-v-1-3-15-is-way-too-big-in-my-computer/11246/8

**Comment by rodolforg** [comment]
I believe it's all about porting void
Dock_Curves::on_update_header_height(int height) into Dock_SoundWave
