### ISSUE TITLE
[Skeleton Tool] Skeleton Deformation Layer should be created as "disabled"

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1615]
Skeleton Deformation Layer should be created with "visibility" checkbox turned off -
![screenshot_006](https://user-images.githubusercontent.com/332868/89715985-d4d0c500-d9d3-11ea-9ca9-6260eafd2060.png)

Explanation:

Skeleton Deformation Layer stores two positions for every bone:
1 - Initial position (same as "Rest Pose" in Blender). This position is displayed when visibility of Skeleton Deformation Layer is turned off.
2 - Deformed position. This position is displayed when visibility of Skeleton Deformation Layer is enabled - then actual deformation is applied.

In this video you can see that Skeleton Deformation Layer is constructed when its visibility is turned off - https://youtu.be/FX8rgPJ38AI?t=333

So, this is why behavior of a Skeleton Tool should be like this.

**Comment by Aa20475** [comment]
Hey! I just found out, as the Deformation layer is disabled and I'm highlighting only the `second` bone, we can't see the highlighting now. Do you think I should change it to `first` bone?

**Comment by morevnaproject** [comment]
Good catch! Yes, the first bone should be highlighted.

**Comment by Aa20475** [comment]
Fixed this. Please merge it asap! :sweat_smile:

**Comment by morevnaproject** [comment]
can't find where the changes located. Maybe you need to create a new PR? ^__^
