### ISSUE TITLE
[Skeleton Tool] Enable/Disable Skeleton Deformation layer when tool switched

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1624]
Need to implement two cases:

1. If ((user switches to Skeleton Tool) and (current selected layer is "Skeleton Deformation")), then:
set this "Skeleton Deformation" as invisible/disabled.

2. If ((user switches from Skeleton Tool to any other tool) and (current selected layer is "Skeleton Deformation")), then:
set this "Skeleton Deformation" as visible/enabled.

**Comment by Aa20475** [comment]
Hey! I've made this change but the `dock_layers` is not getting upgraded.Do I have to trigger a signal for this? Or is there a function to update it?

**Comment by rodolforg** [comment]
From `layer.cpp`:
```c++
void
Layer::set_active(bool x)
{
	if(active_!=x)
	{
		active_=x;

		Node::on_changed();
		signal_status_changed_();
	}
}
```

**Comment by rodolforg** [comment]
And theoretically it's updated in `layertreestore.cpp`:

```c++
LayerTreeStore::LayerTreeStore(etl::loose_handle<synfigapp::CanvasInterface> canvas_interface_):
	Gtk::TreeStore			(ModelHack()),
	queued					(false),
	canvas_interface_		(canvas_interface_)
{
	layer_icon=Gtk::Button().render_icon_pixbuf(Gtk::StockID("synfig-layer"),Gtk::ICON_SIZE_SMALL_TOOLBAR);

	// Connect Signals to Terminals
	canvas_interface()->signal_layer_status_changed().connect(sigc::mem_fun(*this,&studio::LayerTreeStore::on_layer_status_changed));
```

**Comment by Aa20475** [comment]
Hey! Are active and enable the same?

**Comment by rodolforg** [comment]
Whoops I don't know:) @morevnaproject ?

**Comment by morevnaproject** [comment]
Yes, active and enable are the same. See `synfig-studio/src/synfigapp/actions/layeractivate.cpp`. ^__^

**Comment by rodolforg** [comment]
So, it would automatically update the layer tree view :)

**Comment by Aa20475** [comment]
Ohh thanks! @morevnaproject  @rodolforg I triggered the `signal_layer_status_changed` in `CanvasInterface`. :)

**Comment by Aa20475** [comment]
I think this issue is closed! ^__^
