### ISSUE TITLE
[Skeleton Tool] Edit Second bone too when Skeleton Deformation Layer edited

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1626]
Let's suppose user created several bones in Skeleton Deformation Layer (using Skeleton Tool).
Then he realized that some bones are not placed correctly, so he changed their points.
With current behavior, when user edits first bone (initial position) the position of second bone is not changed.
This leads to problems, shown in this video -https://youtu.be/obN94tO6xGM

Solution:

When user edits first bone of Skeleton Deformation Layer, then the same modification should be applied to second bone.

It is important to note that we should apply delta value.

I.e. let's suppose first bone has angle 30 degrees and it was changed to value of 45 degrees. Then we should add 15 degrees to second bone.

**Comment by Aa20475** [comment]
Hey!
I've been thinking about how to solve this issue. But I couldn't come up with any way. I thought,
- Add the second bone's corresponding duck to selected ducks so that the drag applies to it too but I couldn't find a way to get access to it as it's hidden? Also, other thing is that, when the user is selecting a duck to modify the bone, the click handler which I write is not being used. (any tips on this?)
- Save the values of offsets and other parameters during click event and then update the second bone accordingly. Here also, the click handler which I write is not being used. 

What do you think? Also, I think issue #1627 is related to this.

**Comment by morevnaproject** [comment]
I think it's better to go with a second approach.

> Here also, the click handler which I write is not being used.

Can you please push a code you have and show which part you talking about?

**Comment by Aa20475** [comment]
>Can you please push a code you have and show which part you talking about?

I was talking about this handler. When I was solving some other issue, I found out that this handler is not being called when the user clicks on a duck. So, now I'm confused bout how to get the initial offsets and parameters of the bone on click.
https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/states/state_bone.cpp#L523

**Comment by morevnaproject** [comment]
Maybe modify SetValueNode action? Possibly, you can check which valuenode was modified and if it is a bone of Skeleton Deformation Layer, then do changes  for second bone?

![screenshot_002](https://user-images.githubusercontent.com/332868/90337286-b427f100-e00b-11ea-947e-c4430b307728.png)

**Comment by Aa20475** [comment]
Heya that's a nice idea! Will try! 😁

**Comment by morevnaproject** [comment]
We still need this issue resolved, it is blocking 1.6.0 release.

In current source code moving bones of Skeleton Deformation layer using Skeleton Tool is not working correctly. Here's the video showing the problem - https://youtu.be/KcO3Q6ejfac

**Comment by morevnaproject** [comment]
The issue happens only when changing position of bone origin. when changing bone angle or length everything works correctly.

@ice0 @rodolforg I see this issue as blocker for 1.6.0 release.

**Comment by rodolforg** [comment]
I can take a look later. But are you planning to release 1.6.0 soon, without more 1.5.x dev releases?
I'd like to work on the copy'n paste skeleton issues and better SVG native import first.
Hopefully the new Color Dialog.

We could have too the new Render Resize dialog that @Keyikedalube did.

Also more checks / fixes for  Bone Tools.

**Comment by morevnaproject** [comment]
> But are you planning to release 1.6.0 soon, without more 1.5.x dev releases?

I plan to have more 1.5.x releases until we get all current critical issues resolved (by "critical" I mean "something that was working in previous stable version, but doesn't works in current" or "an issue in new functionality, which prevents its correct usage"). ^__^



> I'd like to work on the copy'n paste skeleton issues

> Also more checks / fixes for Bone Tools.

That two would be awesome.

Other new features can be added after 1.6.0. Though, if they will be ready earlier - that's great. 

Still, it would be nice to concentrate on things that blocking 1.6.0 release. ^__^

**Comment by morevnaproject** [comment]
> The issue happens only when changing position of bone origin. when changing bone angle or length everything works correctly.

The issue is somewhere in this place - 
https://github.com/synfig/synfig/blob/c5fbb27b3e817a1fb0e846e1dd98d9bdf7a6bb17/synfig-studio/src/synfigapp/actions/valuedescset.cpp#L241-L268

The expected logic:
- We need to find the delta (offset) value - how much the origin of "first" bonw was moved
- Then we have to apply the same offset to "second" bone
