### ISSUE TITLE
The sound panel does not show the wave for all files.

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#1649]
**Synfig version & platform**:

Development version: 1.5.0
Revision: 20200817
Branch: master
Revision ID: 2beffbe 
Built on Aug 17 2020

Archlinux  amd64

**Issue description**:

Hello, cordial greetings. The sound panel does not show the wave for all files. I tried with mp3, wav and ogg files without finding a pattern that makes it display the wave correctly or not. I hope the information is useful. Thank you very much for supporting this software. Excellent work.

Here the files I used and their characteristics:

**Audio files showing the sound wave**

renewal32.mp3 > Duration: 00:00:16.13, start: 0.023021, bitrate: 35 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 35 kb/s
[renewal32.mp3.zip](https://github.com/synfig/synfig/files/5113539/renewal32.mp3.zip)

bienvenida.mp3 > Duration: 00:00:15.72, start: 0.023021, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 320 kb/s
[bienvenida.mp3.zip](https://github.com/synfig/synfig/files/5113487/bienvenida.mp3.zip)

Fuego Redentor-media.mp3 > Duration: 00:00:15.17, start: 0.023021, bitrate: 142 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 142 kb/s
[Fuego Redentor-media.mp3.zip](https://github.com/synfig/synfig/files/5113536/Fuego.Redentor-media.mp3.zip)

bienvenida.ogg > Duration: 00:00:15.74, start: 0.000000, bitrate: 445 kb/s
    Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 499 kb/s
[bienvenida.ogg.zip](https://github.com/synfig/synfig/files/5113492/bienvenida.ogg.zip)

feliz.ogg >   Duration: 00:00:00.77, start: 0.000000, bitrate: 469 kb/s
    Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 499 kb/s
[feliz.ogg.zip](https://github.com/synfig/synfig/files/5113493/feliz.ogg.zip)

musicavideojuego.ogg >  Duration: 00:00:38.00, start: 0.000000, bitrate: 344 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 499 kb/s
[musicavideojuego.ogg.zip](https://github.com/synfig/synfig/files/5113494/musicavideojuego.ogg.zip)

**Audio files with which the sound wave is not displayed**

10.wav > Duration: 00:00:10.33, bitrate: 768 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s
[10.wav.zip](https://github.com/synfig/synfig/files/5113495/10.wav.zip)

Prueba de estereo.mp3 > Duration: 00:00:07.03, start: 0.025057, bitrate: 243 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 243 kb/s
[Prueba de estereo.mp3.zip](https://github.com/synfig/synfig/files/5113501/Prueba.de.estereo.mp3.zip)

thunder.mp3 > Duration: 00:00:25.10, start: 0.025057, bitrate: 98 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 98 kb/s
[thunder.mp3.zip](https://github.com/synfig/synfig/files/5113502/thunder.mp3.zip)

invictus.ogg >  Duration: 00:01:22.43, start: 0.000000, bitrate: 325 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 499 kb/s
[Invictus-a.ogg.zip](https://github.com/synfig/synfig/files/5113507/Invictus-a.ogg.zip)

160.mp3 > Duration: 00:00:16.14, start: 0.025057, bitrate: 155 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 155 kb/s
[160.mp3.zip](https://github.com/synfig/synfig/files/5113540/160.mp3.zip)

**Comment by morevnaproject** [comment]
Resolved in Synfig version 1.5.1 - https://www.synfig.org/2021/10/30/synfig-studio-1-5-1-released/
