### ISSUE TITLE
[Skeleton Tool] Active bone not set for Skeleton Deformation

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1656]
With Skeleton Deformation Layer:

When user clicks **on any control point** of bone, then this bone is highlighted as "active" but it doesn't really becomes active. As result, next created bone is not parented to this bone.

Note: when user clicks on bone itself (**not** its control point), then everything works as expected.

Video - https://youtu.be/hTLZSWxRzUo

**Comment by Aa20475** [comment]
Now?
