### ISSUE TITLE
[Skeleton Tool] Hide "Make Parent To Active Bone" menu item when not using Skeleton Tool

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1669]
The "Make Parent To Active Bone" menu item appears when user right-clicks on any control point of bone.
This menu item should be visible only when Skeleton Tool is active.

**Comment by Aa20475** [comment]
I will proceed with this issue when #1626  will get closed

**Comment by morevnaproject** [comment]
In latest version menu item is called "Set as Parent To Active Bone" ^__^
