### ISSUE TITLE
Packaging latest synfig difficult

### ISSUE THREAD

**Issue by Vaelatern** [synfig/synfig#1674]
I'm working on the package for a Linux distribution trying to update the distributed synfig from 1.2.2 to 1.3.16

We previously ran a build based on gnu-configure, but that clearly is no longer preferred, so I tried the cmake build. This is a straight invocation of cmake, to support things like cross building, and making sure all the environment variables are set correctly. However, it does not do all the steps in the 2-build-cmake or 2-build-production scripts, being more vanilla and specific to this software distribution.

I was hoping for some insight into a specific problem I have.

When running the `make install` step, I get told a file is missing.

```
[snip]
-- Installing: /destdir/synfig-1.3.16/usr/include/synfig/weightedvalue.h
-- Installing: /destdir/synfig-1.3.16/usr/include/synfig/widthpoint.h
-- Installing: /destdir/synfig-1.3.16/usr/include/synfig/zstreambuf.h
-- Installing: /destdir/synfig-1.3.16/usr/lib/libsynfig.so
-- Installing: /destdir/synfig-1.3.16/usr/lib/cmake/synfig-core/synfig-core-config.cmake
-- Installing: /destdir/synfig-1.3.16/usr/lib/cmake/synfig-core/synfig-core-config-release.cmake
-- Installing: /destdir/synfig-1.3.16/usr/bin/synfig
-- Set runtime path of "/destdir//synfig-1.3.16/usr/bin/synfig" to ""
-- Installing: /destdir/synfig-1.3.16/usr/etc/synfig_modules.cfg
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/liblyr_freetype.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/liblyr_freetype.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/liblyr_std.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/liblyr_std.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_bmp.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_bmp.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_dv.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_dv.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_example.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_example.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_ffmpeg.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_ffmpeg.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_filter.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_filter.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_geometry.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_geometry.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_gif.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_gif.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_gradient.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_gradient.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_imagemagick.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_imagemagick.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_jpeg.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_jpeg.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_mng.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_mng.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_noise.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_noise.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_openexr.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_openexr.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_particle.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_particle.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_png.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_png.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_ppm.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_ppm.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_svg.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_svg.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_yuv420p.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_yuv420p.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/synfig/modules/libmod_magickpp.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/synfig/modules/libmod_magickpp.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/lib/libsynfigapp.so
-- Set runtime path of "/destdir//synfig-1.3.16/usr/lib/libsynfigapp.so" to ""
-- Installing: /destdir/synfig-1.3.16/usr/bin/synfigstudio
-- Set runtime path of "/destdir//synfig-1.3.16/usr/bin/synfigstudio" to ""
CMake Error at synfig-studio/images/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/builddir/synfig-1.3.16/build/synfig-studio/images/about_icon.png": No
  such file or directory.
Call Stack (most recent call first):
  synfig-studio/cmake_install.cmake:48 (include)
  cmake_install.cmake:49 (include)


make: *** [Makefile:137: install] Error 1
```

Now, `/builddir/synfig-1.3.16/build/synfig-studio/images/about_icon.png` does not exist. Is there a specific command that can create these asset files? Or is cmake supposed to generate them already?

(This is from the source tarball generated by github)

**Comment by AYESDIE** [comment]
Can you specify the commands you used so this can be reproduced?
Can you tell the operating system on which you tried?

Those assets are built by `build_images` target. 
You can try this command to build those files (which should include `/about_icon.png` 
```
$ make build_images
```

But there's no need to specify that target when doing `make install`.

**Comment by Vaelatern** [comment]
Seems that the default target ('all') does not actually build "all"

I'll correct by manually specifying the targets `build_images all`

Commands for reproducing are distro specific, but I can link to a travis build if this keeps failing.

**Comment by AYESDIE** [comment]
> I'll correct by manually specifying the targets `build_images all`

I'm pretty sure there should not be a need to manually specify those since it's added as a dependency on the target `synfigstudio`. But sure you can give it a try. 

> Commands for reproducing are distro specific, but I can link to a travis build if this keeps failing.

That'll help too ^_^

**Comment by Vaelatern** [comment]
https://travis-ci.org/github/Vaelatern/void-packages/jobs/721908910

Build starting. I've had to specify `all build_images` but `build_images` can't succeed:

```
Scanning dependencies of target build_images
/bin/sh: synfig: command not found
make[3]: *** [synfig-studio/images/CMakeFiles/build_images.dir/build.make:76: build_images] Error 127
```

**Comment by AYESDIE** [comment]
It's weird that it built the target `synfigstudio` without ever building `build_images` [here](https://travis-ci.org/github/Vaelatern/void-packages/jobs/721908910#L4388). Let me take a look at it.

**Comment by AYESDIE** [comment]
Alright, so I checked the issue and looks like the CMake file over [here](https://github.com/synfig/synfig/blob/v1.3.16/synfig-studio/images/CMakeLists.txt) (as of version 1.3.16) is not up to date. 

You can find this issue #1132.

**Comment by ice0** [comment]
Hi guys!

Currently autotools is still recommended for building packages. We are currently working on improving CMake, but it is still under testing/development stage, so we recommend it mostly to developers only.

Also, the 1.3 branch does not have all the features backported from the `master` branch, and the latest CMake improvements is unfortunately missing.

**Current roadmap:**

After fixing all critical bugs, version 1.3.x-unstable will become 1.4-stable.
`master` branch will be the next 1.5-unstable, so CMake is scheduled for 1.6-stable.

**Comment by Vaelatern** [comment]
Hello, a stupid question then.

Autotools would involve having a configure script, right? Or enough for autoreconf to function. So, because neither are present, how might I trigger an autotools build?

**Comment by ice0** [comment]
Synfig is divided into three components: ETL, synfig-core and synfig-studio.

ETL - the extended template library.
synfig-core - contains the render engine and core/command-line tool (cli)
synfig-studio - gui for the application.

This is why it have 3 configure scripts for each module.
More information here: https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html

**Comment by rodolforg** [comment]
Any progress @Vaelatern ?

**Comment by Vaelatern** [comment]
I've made an effort. 1.3 series builds don't have a bootstrapped source tarball, so I have to re-run things like autoreconf, but I have it working for me.

Thanks for the guidance!
