### ISSUE TITLE
[Skeleton Tool] Can't load saved file that has layers made with skeleton tool

### ISSUE THREAD

**Issue by Aa20475** [synfig/synfig#1680]
Can be replicated when you try to load this file.

[Robby.zip](https://github.com/synfig/synfig/files/5145213/Robby.zip)

This is what happens. 

![Screenshot 2020-08-29 12:00:25](https://user-images.githubusercontent.com/35968657/91637027-c97e2180-e9f4-11ea-9585-59346be290ec.png)

**Comment by Aa20475** [comment]
I am working on it.

**Comment by morevnaproject** [comment]
Yes, I can reproduce the same.

This only happens when Skeleton Layer is made with Skeleton Tool and has more than one bones.
Video - https://youtu.be/n7Qqxabkah4
