### ISSUE TITLE
[Skeleton Tool] Crash when switching to Skeleton Tool

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1683]
Steps to reproduce:
1. Switch to Skeleton Tool
2. Create 2 bones
3. Switch to Rectangle Tool.
4. Create Rectangle
5. Switch to Skeleton Tool
 -> Crash.

Video - https://youtu.be/l2iFpzEFKnI

**Comment by Aa20475** [comment]
Hey! Please close this issue asap
