### ISSUE TITLE
Windows build crashes opening external dialogs (Open/Save/Import)

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1687]
**Synfig version & platform**:
master (built on Windows 10 using cmake)

**Issue description**:
1) Start `Synfig Studio`
2) Go to: `File -> Open`

Synfig Studio crashes.

This crash happens also with other dialogs that require a similar window for external stuff, like Open/Save/Import (I think all of them use the same gtk code)

**Comment by ice0** [comment]
This problem and the icon problem both indicates some kind of problem with GTK.
Something similar happened to me when I trying MSVC build without correct `.gsettings` file and some files associated with the theme.

So can you try to reinstall GTK package?

**Comment by FirasH** [comment]
Reinstalled from scratch msys because there was a problem with repositories.
Even after full recompilation the crash is there.

Nope, no error messages from the console.

**Comment by rodolforg** [comment]
:/
It happens with CMake only? Or you didn't try with autotools?

**Comment by FirasH** [comment]
@rodolforg 

I couldn't build it with current autotools because my home directory has a blank space (#1058)
Honestly I have no interest in Windows at all, but if I could build it correctly I could use Synfig at work easily...

**Comment by ice0** [comment]
Ok. I can reproduce the problem by moving the project to a directory containing spaces.
Looks like GTK has a problem with this too. I will investigate further.

**Comment by BobSynfig** [comment]
May be related, I have the same problems of crash  with Inkscape 1.0.1

Inkscape-4035a4f-x86_64.AppImage (1.0.0) -> No problem

Inkscape-3bc2e81-x86_64.AppImage (1.0.1)
> Setting _INKSCAPE_GC=disable as a workaround for broken libgc
> (...)
> (org.inkscape.Inkscape:26080): GLib-GIO-ERROR **: 17:15:23.116: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap

(Ubuntu x64 18.04.5)

**Comment by ice0** [comment]
@BobSynfig  Looks interesting.  Synfig also crashes on `Trace/breakpoint trap`.

I found 2 solutions:
1. Copy `/mingw64/share/glib-2.0` to `output/share/glib-2.0`

or

2. Remove `libgio-2.0-0.dll` and `libglib-2.0-0.dll` from output/bin directory.

Looks like `glib` searches for `gschemas.compiled` using relative path. So when you remove it from `bin` library it loads from `/mingw64/bin/` and can find `gschemas.compiled` file using `../share/glib-2.0` path.

**Comment by ice0** [comment]
This PR (https://github.com/synfig/synfig/pull/1711) should fix that (I am already merged it). 

Can you please check latest master with clean build?

**Comment by FirasH** [comment]
> 
> 
> This PR (#1711) should fix that (I am already merged it).
> 
> Can you please check latest master with clean build?

Rebuilt from scratch using `2-build-msys-cmake.sh` and I cannot get the executable to run.

I get the following errors:
- `libcairo-2.dll` not found (but I have `mingw-w64-x86_64-cairo 1.17.2-2` installed)
- `libatkmm-1.6-1.dll` not found (but I have `mingw-w64-x86_64-atkmm 2.28.0-1` installed)
- `libcairomm-1.0-1.dll` not found (but I have `mingw-w64-x86_64-cairomm 1.12.2-2` installed)
- `libgdk-3-0.dll` not found (but I have `mingw-w64-x86_64-gdk-pixbuf2 2.40.0-1` installed, not sure if it's the correct match though)

**Comment by ice0** [comment]
Whoops, forgot to fix this script :)

Can you try:
```
mkdir build-cmake
cd build-cmake
cmake <synfig_dir> -G"MSYS Makefiles"
make -j8
```

or if you have `Ninja`
```
mkdir build-cmake
cd build-cmake
cmake <synfig_dir> -GNinja
ninja
```

after what you can run `build-cmake\output\bin\synfigstudio.exe`

**Comment by FirasH** [comment]
@ice0 I get the same errors even with the last build commands.

**Comment by FirasH** [comment]
> 
> 
> @FirasH one more question: MSYS2 installed at default path (c:\msys64) or in your home folder?

Yes, `C:\msys64` and my synfig folder is `C:\msys64\home\Postazione 2\synfig`

**Comment by FirasH** [comment]
Cannot reproduce this anymore, tested now building from scratch b277312
