### ISSUE TITLE
Canvas pan and zoom shortcut not work when switch to other program then get back

### ISSUE THREAD

**Issue by firecloud888** [synfig/synfig#1691]
**Synfig version & platform**:
Windows 10, steam

**Issue description**:
Not sure how to trigger the bug, when I go to other apps and then get back to krita, sometimes it will happen. I must restart krita to fix that.

**Comment by rodolforg** [comment]
Hi.
By Krita, do you mean Synfig? If not, maybe you open an issue in wrong project ;)

If you talk about Synfig: what are the specific shortcuts you use and what  is your Synfig version?

**Comment by ice0** [comment]
Please reopen if you mean Synfig and not Krita.
