### ISSUE TITLE
Objects/layers scale with change in Canvas size

### ISSUE THREAD

**Issue by hellocatfood** [synfig/synfig#1694]
**Synfig version & platform**:
Synfig 1.3.16 on Ubuntu 20.04

**Issue description**:
I've created an animation with canvas size 500x500 and added some objects to it (original.sifz). 

![Screenshot from 2020-09-05 00-20-06](https://user-images.githubusercontent.com/151947/92290891-d4154b00-ef0d-11ea-83d6-7226e9b840cb.png)

I got the canvas size incorrect and so I pressed f8 to change it to 1500x500. When I pressed OK the canvas size is changed but also all of the layers are scaled (scaled.sifz).

![Screenshot from 2020-09-05 00-20-15](https://user-images.githubusercontent.com/151947/92290896-da0b2c00-ef0d-11ea-869a-c10813dc406e.png)

What I expected to see:

![Screenshot from 2020-09-05 00-21-18](https://user-images.githubusercontent.com/151947/92290905-e7c0b180-ef0d-11ea-80bb-f5c11631762c.png)

It seems as though the scale is being calculated in relation to the canvas size.

[files.zip](https://github.com/synfig/synfig/files/5177292/files.zip)

**Comment by Jose-Moreno** [comment]
@hellocatfood Ok sorry it took me so long to test this. Please do the following in development version 1.3.16:

1) Go to the topbar menu > **Canvas**
2) In the canvas dialog go to > **Other** tab
3) there uncheck **Image Span** from the _Lock & Links_ section
4) try to resize your canvas now. Does this satisfy your requirements?

If I understood you correctly this should allow your desired outcome.

**Comment by hellocatfood** [comment]
Yes, that works. Thank you!
