### ISSUE TITLE
Missing Bundle Identifier key in Info.plist (macOS build)

### ISSUE THREAD

**Issue by suschizu** [synfig/synfig#1705]
I've noticed that this app doesn't contain a bundle identifier key in the Info.plist (https://github.com/synfig/synfig/blob/master/autobuild/osx/app-template/Contents/Info.plist)

every macOS app is supposed to have a unique CFBundleIdentifier

https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier

**Comment by ice0** [comment]
Ok,  thank you! I will take a look.

**Comment by DhairyaBahl** [comment]
I would like to work on this issue if its still available

Thanks :)

**Comment by ice0** [comment]
@DhairyaBahl Assigned to you!

**Comment by DhairyaBahl** [comment]
@ice0 I closed previous pull requests. It got messed up and i got confused too. I started again and made a new pull request with proper branching. Hope you don't mind. 

Thanks :)
