### ISSUE TITLE
Cannot save to folder that is named with Chinese characters

### ISSUE THREAD

**Issue by SirCodyC** [synfig/synfig#1707]
**Synfig version & platform**:
Synfig 1.2.2 Windows 64 bit - Downloaded 9_17_2020
I am running the program in English. 

**Issue description**:
Projects will save to folders named such as "test1", "test_project", "pony", "lion".
However, the folders for the art project I am working on are **labeled with CJK Characters (Chinese)** such as:
"獅子" which means lion "小馬" which means pony, etc, **do not allow saving**. After clicking save button, save screen goes away but the project is left unnamed with the asterisk remaining.

This is for very large project for Chinese language and I don't want to rename my about 177 folders to ASCII characters just to be sure that they will save. I would like to put my animations in each folder that corresponds to which animal that is a animation for.

If you could fix this, this would really help. For now I will save projects in a temp folder on the Desktop, but I really can't keep organized until I can put them in my Documents (All of the subfolders use many Chinese characters) Thank you.

**Comment by ice0** [comment]
Hi, @SirCodyC!

Can you check if this is fixed in 1.3 release? (You can download [portable ](https://github.com/synfig/synfig/releases/download/v1.3.16/SynfigStudio-1.3.16-testing-2020.08.06-win64-bc82b.zip) version and run it without installation )

**Comment by morevnaproject** [comment]
Yes, this issue should be fixed in 1.3.16. ^__^

**Comment by morevnaproject** [comment]
Yes, this issue is already fixed in 1.3.16. ^__^

**Comment by SirCodyC** [comment]
Yes, it works now (I downloaded the portable 1.3 version that @ice0 linked). Thank you so much!
I had clicked the "Download Lastest Stable Release" button. That must be how I got to 1.2.2 rather than the newer one.

謝謝！(Thank you!)
