### ISSUE TITLE
UI suggestion: Reduce float precision displayed

### ISSUE THREAD

**Issue by define-private-public** [synfig/synfig#1708]
**Synfig version & platform**:
I'm using 1.3.16 on Ubuntu 18.04 (via AppImage)

**Issue description**:
I'm looking to start doing a 2D animation series and I've been trying to pick out some animation software that doesn't break the bank.  So far I'm looking at Synfig, but I think there are some things that can be done to improve the usability.  As for this ticket:

**When displaying a floating point, don't show the exact number**

Take a look at this:
![synfig_precision](https://user-images.githubusercontent.com/4551425/94099231-71bab680-fdf8-11ea-8d7a-44eb4001f7c6.png)

For `Z Depth` and `Opacity`, I think showing `1` or `1.0` would suffice, instead of showing my six digits of precision.  Only if a user has entered, say `1.555`, it should then show all of those digits.

The value for `Transformation` is interpolated.  I also don't think that showing such precision is necessary.  Maybe showing a truncated/rounded version would be fine, but then if a user clicks (or hovers over) the field/value, it's true decimal value will be shown.

IIRC, other editing tools that I use (such as DaVinci Resolve) typically show an integer, but support floats if you want them, and sometimes allow up to three decimals of precision.

**Comment by define-private-public** [comment]
@ice0 thanks for tagging this, there's also a tag for UI tickets.  Can you add that too?  I have a whole slew of UI suggestions I'd like to make.

**Comment by ice0** [comment]
Sure!

**Comment by define-private-public** [comment]
If I wanted to implement this myself, where in the code should I go looking?

**Comment by rodolforg** [comment]
I'll make a long answer here…

For Parameter Panel, we use:
- the `ParamTree` class, a derived class of `Gtk::TreeView` widget : `synfig-studio/src/gui/trees/paramtree.h` (.cpp);
- the `LayerParamTreeStore` class, a derived class of `Gtk::TreeModel` data model : `synfig-studio/src/gui/trees/layerparamtreestore.h` (.cpp);

But what really show the cell data in a `TreeView` are `Gtk::CellRenderer` classes. The TreeView class make this glue (besides another visual stuff like tree scrolling, collapsing/expanding, etc.). The "Value" column of Parameter Panel is rendered by our custom widget class named `CellRenderer_ValueBase` (`synfig-studio/src/gui/cellrenderer/cellrenderer_value.h`(.cpp)), that renders any of our value types (Canvas, Real, bool, etc.) as string. Its `render_vfunc()` method does the job.

We now have a `synfig-core/src/synfig/string_helper.h`(.cpp) with some string functions that may help you on it.

If you want to change stuff when editing a cell, `Gtk::TreeView` uses the `Gtk::CellEditable` interface returned by `CellRenderer::start_editing_vfunc()`, so our already mentioned `CellRenderer_ValueBase` provides one for each value type.

**Comment by define-private-public** [comment]
Started working on a PR.  Right now I changed the precision to just 1 decimal.  It's only showing in that one panel, there are still a few other areas in the software that should have adjusting.  Here's how it looks at the moment:

![Screenshot_2021-08-01_16-30-00](https://user-images.githubusercontent.com/4551425/127784523-9e97d7e3-a0e7-41b0-af40-3d893bf6ae0a.png)

If you click to edit a value you'll then see its full float value.

So far I think this looks good for most.  But I can see an issue with fields like "Opacity" that probably should have at least 2 decimals of precision shown.   As an alternative, I could try to do a "truncate all trialing zeroes", but that would be a bit more work.

**Comment by define-private-public** [comment]
Question: in the "Layers" can "z-Depth" ever be a floating point?  I don't see how I can edit that z-depth, and I think I've only see integer values there.  But they are currently displayed as floats.

**Comment by ice0** [comment]
> But I can see an issue with fields like "Opacity" that probably should have at least 2 decimals of precision shown. 

Why should "Opacity" be more precise? 

> As an alternative, I could try to do a "truncate all trialing zeroes", but that would be a bit more work. 

The problem with floats, in they "floating" precision. For example, a 5 in a floating point number might be "4.999998", so I don't know how truncating trailing zeros might help here. Anyway, you can try it - it will probably help in most cases. 

> Question: in the "Layers" can "z-Depth" ever be a floating point? I don't see how I can edit that z-depth, and I think I've only see integer values there. But they are currently displayed as floats.

The problem here is that "z-Depth" is stored as a real (float) number. So we can't just make it `int` without breaking compatibility. 
I don't know why it was made a floating point number, perhaps because of the possibility to export/link this value with other fields.

@morevnaproject @rodolforg Any ideas here?

**Comment by define-private-public** [comment]
> Why should "Opacity" be more precise?

I figured that people might do opacity values of around two decimals (e.g. 75%).

I'm wondering, is there already a function in the code base that can check if a float/real-number is actually an integer?  It might be nice to instead have any values such as "1.0" be shown as "1", but that should only be the case if there is no decimal component.

**Comment by ice0** [comment]
> I figured that people might do opacity values of around two decimals (e.g. 75%).

Ok, got it. 

> I'm wondering, is there already a function in the code base that can check if a float/real-number is actually an integer? It might be nice to instead have any values such as "1.0" be shown as "1", but that should only be the case if there is no decimal component.

I thought that `remove_trailing_zeroes("1.0", force_decimal_point = false)` does the job. Have you checked it?

**Comment by define-private-public** [comment]
> I thought that remove_trailing_zeroes("1.0", force_decimal_point = false) does the job. Have you checked it?

No, it wasn't doing that.

Inside of the `CellRenderer_ValueBase::render_vfunc()`, how can I check for the property's name.  E.g.  I'd like to have use two decimals of precision if the property the value is representing is `Opacity`.

**Comment by morevnaproject** [comment]
> I don't see how I can edit that z-depth,

Please check “z-depth” parameter in Params Panel - it allows to define “shift of Z-depth” for current layer.
https://wiki.synfig.org/Z_Depth_Parameter

**Comment by morevnaproject** [comment]
> I don't know why it was made a floating point number

It is made a floating point number type to allow smooth animation ^__^

**Comment by define-private-public** [comment]
So is the `Z-Depth` parameter in the layer panel, I can understand it being a floating point for animation purposes (under the hood).  But if it's always going to be shown to the user as an integer, can we just make it as such?

---

AFAICT, it doesn't seem like there is function `is_float_an_integer(float x)` in the code base yet.  I'd like to add one.  Into which file should I put this, and where should I put the unit tests?
