### ISSUE TITLE
List quality Synfig issues for Hacktoberfest

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1710]
Could be:
- easy ones (highly preferred for first timers)
- difficult ones too (for dev already experienced with synfig development)

I'd love synfig team to label issues for Hacktoberfest. This will encourage many new contributions and invite new developers too. I think good first issue are a good starting point to label "Hacktoberfest"
For difficult issues, synfig team members know best 😼😄

Event is from 1st-31st Oct
https://hacktoberfest.digitalocean.com/

**Comment by ice0** [comment]
Are there any requirements for the issue difficulty?

**Comment by Keyikedalube** [comment]
No, there are no requirements. Labeling issues allows anyone to quickly discover projects to contribute using the top-right GitHub search feature.

However, project maintainers will have to monitor the PR submitted for quality issues. The page describes something about invalidating user-submitted PR if it's a spam or doesn't actually solve the project issue.

In my opinion, good first issue is a good starting point because incoming contributors are likely to be newbies, students, etc Issues easy to solve are better and motivating :)

**Comment by Keyikedalube** [comment]
"Hacktoberfest" is on 😁😃

This issue is resolved.
