### ISSUE TITLE
Dragging Tabs and Panels Make Mouse Cursor Disappear.... but NOT on Its Portable Version

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#1718]
**Synfig version & platform**:
Dev version 1.3.16 on Win 10 (installer version)

**Issue description**:
Yeah..... this is odd...

So while i was working on a drawing i decided to try using the portable version v1.3.16 instead of the stable one, and... it worked really great for me!
So, i decided to install it permanently into my pc (and replacing my stable ones in the process).

And after it's done installing, i tried to play around with it, and found this issue by accident while i was about to arrange my workarea a bit.
I don't know why this only happens on installer version of this synfig build and not on the portable one...

**Comment by FadhilKwan** [comment]
A bit of update on this one:
Apparently i managed to 'fix' it with a bit of a workaround.
So what i did was copying the entire contents from the portable version of v1.3.16 (excluding the .bat file) into the folder of another synfig that i just installed.
(i mean they both are v1.3.16, so it should be fine, right?~)

But i still have no idea how did that fixed the issue....
or even why this is a thing in the first place..... ._.?

**Comment by ice0** [comment]
Hi!
This reminds me of the issue with missing cursors (https://github.com/synfig/synfig/issues/536).
I think there might be a difference in the `share` folder.

**Comment by morevnaproject** [comment]
Hi! I have reproduced the issue on my machine and confirming it. 
I have found that some (many) cursors are missing in version shipped as  installer package.
Do not know why this happened, I need to check our build server and scripts at https://github.com/morevnaproject/morevna-builds ...

**Comment by morevnaproject** [comment]
I have cleaned up build server and started rebuild process...

**Comment by morevnaproject** [comment]
I have made a rebuild and nothing changed - some files are still missing in installer.

But I have found where the problem comes from!
Some files in "cursors" directory are symlinks to other files. When those files are packed into zip they become regular files. But they are simply ignored when packed into NSIS installer.
Working on fixing this. ^__^

**Comment by morevnaproject** [comment]
Issue is fixed. Here are exe and zip files generated by build server:
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.16-testing-2020.10.11-win64-bc82b.exe
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.16-testing-2020.10.11-win64-bc82b.zip
