### ISSUE TITLE
Set AboutDialog transient & modal properties

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1722]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
Synfig Preferences dialog has transient & modal properties set. It's better if AboutDialog has the same behavior :)

**Comment by Keyikedalube** [comment]
If Synfig team wants to have this feature implemented 👉 label **easy** and **Hacktoberfest** 😁

**Comment by ice0** [comment]
@Keyikedalube Thank you for reminding!

**Comment by Keyikedalube** [comment]
Anyone who wants to take on this issue:
https://github.com/synfig/synfig/blob/41fda6cf928e46e6ac3915d74ffdd599842afa6b/synfig-studio/src/gui/dialogs/about.cpp#L78-L81

Transient property is already set. The only property left to set is the modal property :)

**Comment by snhardin** [comment]
Happy Hacktoberfest!

I am a total C++ noob and would like to take this. 🙂

**Comment by ice0** [comment]
Now it's yours! )

**Comment by AnshitaVishwa** [comment]
@Keyikedalube I figured out how to set the modal property. Should Imake a PR?

**Comment by Keyikedalube** [comment]
@snhardin Are you still working on this? It's been 8 days and no response from you.
@AnshitaVishwa Please wait till this week and give our current assignee time to respond OK.

If you still want I'll remind you next week to take on this issue. In the meantime there are other interesting issues, check them out...

**Comment by snhardin** [comment]
Hello. Yes, I'm still working on this. Sorry, I work full-time, so really much of my time is confined to weekends. Thank you for being patient with me. 🙂

**Comment by ice0** [comment]
@AnshitaVishwa maybe you can take this? https://github.com/synfig/synfig/issues/826

**Comment by snhardin** [comment]
I submitted a PR. I couldn't actually find the Preferences window to look off of, but I'm assuming `set_modal` is what you guys wanted here.

**Comment by Keyikedalube** [comment]
@snhardin Your PR is correct :) And yes, `set_modal` is what we wanted...

Maintainers are human beings too. So don't worry when they don't respond OK

I'm approving your changes anyway :)
