### ISSUE TITLE
Improve synfigstudio CMake script

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1732]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
Project name is already defined in the CMake script of synfig-studio root (not the top root one)
https://github.com/synfig/synfig/blob/75f78f249e76c70453c992f5795908979f8dd40d/synfig-studio/CMakeLists.txt#L5
It's wise to use the defined CMake variable `PROJECT_NAME` instead of manually typing in the already defined project name (in target, linking, etc) over and over again. That way when it's time to change the project name later in the future, you only have to edit once and let CMake propagate the change everywhere :)

**Note:** This issue is highly encouraged for CMake first timers.
**Hint:** 👉 [synfig/synfig-studio/src/gui/CMakeLists.txt](https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/CMakeLists.txt) 👈 This file is the one needing improvement

**Comment by Keyikedalube** [comment]
Easy and Hacktoberfest :)

**Comment by ice0** [comment]
At the moment there are 3 CMake projects: ETL, synfig-core and synfig-studio. So you can build them separately, just like autotools does. Maybe we need that in the future. Therefore, for now, I propose to leave it as it is ^___^

**Comment by Keyikedalube** [comment]
Synfigstudio project() call:
```
CMAKE_PROJECT_NAME -> top most root -> project(synfig-studio)
      PROJECT_NAME -> sub directory -> project(synfigstudio)
```

I've checked synfig-core and the target names are quite conflicting; there's **synfig** and **synfig_bin**
Didn't check out ETL

However, synfig-studio sub-directory is pretty safe to use `PROJECT_NAME` because its value is correctly set with the recent call to `project()` *depicted above*

Anyway, I agree with you too. Set in the future, it is :)
