### ISSUE TITLE
Remove Navigation menu and implement Gtk::ShortcutsWindow

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1733]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
![Screenshot](https://user-images.githubusercontent.com/24214509/94932473-bfb17780-04e6-11eb-9ee1-ee73350970cd.png)

We already have navigation buttons in the toolbar just above the time track panel and I don't think there is a setting in the Preferences/View menu that allows making it hidden. And for this reason...
**Navigation** menu option in the menu bar is quite redundant.
However, the available menu option lists keyboard shortcuts which is quite informative.

I propose implementing `Gtk::ShortcutsWindow` listing all the available navigation shortcuts and removing **Navigation** menu from the menu bar.

**Comment by Keyikedalube** [comment]
I could work on this issue if you guys want this feature implemented...

**Comment by rodolforg** [comment]
> I propose implementing `Gtk::ShortcutsWindow` listing all the available navigation shortcuts and removing **Navigation** menu from the menu bar.

Wow :) I didn't know it! But I couldn't track what gtkmm minimal required version for this feature.

**Comment by Keyikedalube** [comment]
@rodolforg Since gtkmm 3.20 *From devhelp program :)*

**Comment by morevnaproject** [comment]
> **Navigation** menu option in the menu bar is quite redundant.

I agree with that.

**Comment by FirasH** [comment]
Also it is not possible to change the shortcuts in the settings afaik

**Comment by Keyikedalube** [comment]
I'm already working on implementing `Gtk::ShortcutsWindow` for Navigation. Planning to make this window flexible with multiple shortcut sections. So maybe for now I'll implement only the navigation section part and later in the future someone could implement the toolbox shortcuts section. And so on...

**Comment by morevnaproject** [comment]
> Also it is not possible to change the shortcuts in the settings afaik

It is not possible from GUI, but should work by editing configuration file (called `accelrc`).

**Comment by Keyikedalube** [comment]
- Help menu
![Screenshot from 2020-10-05 16-46-02](https://user-images.githubusercontent.com/24214509/95074130-a2211f80-072b-11eb-91b5-b6e1d8ed226e.png)
- Actual window
![Screenshot from 2020-10-05 16-45-15](https://user-images.githubusercontent.com/24214509/95073755-00013780-072b-11eb-93ae-3ce092ba6398.png)

Sadly, removing Navigation menu also removes all navigation accelerator keyboard shortcuts for play, pause, seek, etc Accelerator shortcuts seem to be integrated with the menu items.

**Comment by Keyikedalube** [comment]
In case an alternative shortcut solution is implemented... I recommend changing play/pause to just spacebar. Blender and Kdenlive both uses spacebar and it's intuitive. I didn't know synfig has accelerator keys for play/pause until I started working on this issue. I still use mouse click to play/pause and that's much more better than memorizing new quirky shortcuts just for one application. Spacebar is quite universal :) Works across YouTube, Totem, VLC, the above two I mentioned :) etc

**Comment by rodolforg** [comment]
> Spacebar is quite universal :) Works across YouTube,

I use 'k' on YouTube lol Sometimes spacebar just scrolls the page :P

**Comment by Keyikedalube** [comment]
Yup, spacebar works fine as soon as the page loads and I haven't clicked somewhere else around the page. I do use 'k' too when I have to skip ('j' and 'l') promotions and repetitive call to actions by content creators or skip some sections of tutorial and hit pause. Best UX :)

**Comment by morevnaproject** [comment]
Shortcuts for frame seeking are used frequently in my case.

**Comment by Keyikedalube** [comment]
Do you think the below frame seeking shortcuts would be better?
Next frame - right arrow
Prev frame - left arrow
Next keyframe - Shift + right arrow
Prev keyframe - Shift + left arrow

**Comment by morevnaproject** [comment]
Arrows are often used to move objects on workarea ^__^

**Comment by Keyikedalube** [comment]
Oh... I forgot about that.

**Comment by Keyikedalube** [comment]
It's possible to set the accelerator property to buttons but jump buttons are missing.

There is:
1. play/pause - `Ctrl+P` `Escape`
2. single frame seeking - `Ctrl+.` `Ctrl+,`
3. and keyframe seeking buttons - `Ctrl+[` `Ctrl+]`

`Shift+Ctrl+>` `Shift+Ctrl+<` buttons are missing.

![Screenshot from 2020-10-08 15-32-02](https://user-images.githubusercontent.com/24214509/95444934-020e0500-097c-11eb-8f64-aa2b32956edb.png)

Do you want me to add these two buttons or discard the jump frame feature?

**Comment by ice0** [comment]
> Arrows are often used to move objects on workarea ^__^

Agree. But I think about context-aware keys. So when you select timeline window, you can use them also.

**Comment by Keyikedalube** [comment]
I used frame seek buttons icon for jump buttons too

![Screenshot from 2020-10-09 07-12-42](https://user-images.githubusercontent.com/24214509/95532735-e0099680-09fe-11eb-86da-0f0c059e6112.png)

Keyboard accelerators respond to all these buttons but a bit slower due to `button->signal_clicked()` animation being played first and then the timeline cursor responding...

I made a rough new icon demonstration for frame seek and frame jump buttons.
![frame seeker](https://user-images.githubusercontent.com/24214509/95532873-527a7680-09ff-11eb-816a-76bf65d53acb.png)

You can notice the icons reflect the time track dashes; smaller dash for frames and bigger dash for seconds. The dash color could be changed to white with black outline in the final step just to keep it consistent with the other dial buttons.

Opinions..?

**Comment by morevnaproject** [comment]
@ice0 I prefer to have those shortcuts with global scope. It’s hard to track the focus. Sometimes I move object with keyboard arrows, then use shortcut to jump a few frames ahead and then again moving object with arrows.

**Comment by morevnaproject** [comment]
@Keyikedalube Shame on me, I do not remember what “jump” action actually does (probably, because I never used it). What is the meaning of this action? (I don’t have synfig here right now to check)

**Comment by Keyikedalube** [comment]
> What is the meaning of "jump" action?

There are two frame seek actions:
1. 1 frame front and back `Ctrl+.` `Ctrl+,`
2. 1 second front and back `Shift+Ctrl+>` `Shift+Ctrl+<`

**Comment by Keyikedalube** [comment]
I experimented with new keyboard shortcuts for frame seeking:
1. 1 frame front and back `.` ',`
2. 1 second front and back `Shift+>` `Shift+<`

and maybe...
3. Start and end `Shift+Ctrl+>` `Shift+Ctrl+<`

Intuitive?

**Comment by morevnaproject** [comment]
> > What is the meaning of "jump" action?
> 
> There are two frame seek actions:
> 
>     1. 1 frame front and back `Ctrl+.` `Ctrl+,`
> 
>     2. 1 second front and back `Shift+Ctrl+>` `Shift+Ctrl+<`


@Keyikedalube Thank you for clarification!


> Do you want me to add these two buttons or discard the jump frame feature?

Then, I think there is no reason to add two extra buttons for frame jump actions. It's okay to have them in Shortcuts window only.




> I experimented with new keyboard shortcuts for frame seeking:
> 
>     1. 1 frame front and back `.` `,`
> 
>     2. 1 second front and back `Shift+>` `Shift+<`

Sounds good! ^__^

**Comment by FirasH** [comment]
In the Italian keyboard layout the key `>` is obtained with `Shift + <`.
No idea if that could be an issue.

**Comment by Keyikedalube** [comment]
The country where I'm from mostly (just my guess) uses QWERTY keyboard layout apart from small group of people who uses additional keyboard stickers to type in their native language (HIndi)

I notice period, coma, and angle brackets are grouped together in this keyboard layout. Thought it'd be much more better to use single keystroke for commonly used accelerators.

Thanks for the info though :)

**Comment by Keyikedalube** [comment]
Okay PR is a bit delayed because I didn't like the current solution :(

> It's possible to set the accelerator property to buttons

The reason

> Keyboard accelerators respond to all these buttons but a bit slower due to button->signal_clicked() animation being played first and then the timeline cursor responding...

Keyboard shortcuts are meant to accomplish some actions fast without having to go through these two obstacles Mouse > GUI buttons/menus.

You can try it out yourself:
1. Comment out Navigation menu (app.cpp)
3. And `set_accel_path()` to play and frame seek buttons (framdial.cpp)

When you hit the keyboard accelerator, you can notice GUI buttons respond first by playing clicked animation and then the time line cursor moves.

Users are mostly going to expect instant response when they hit play/pause button. But with current implementatioin... pausing at 1s4f is going to be far ahead maybe 1s15f

I experimented with CSS transition-delay and transition-timing-function and gosh that took more time and energy because it's my frist encounter with gtk stylesheet ever since I took on this issue. I thought there would be a way to disable clicked animation, there must be!!! GTK team designed this toolkit with designers and programmers in mind. Button animation and fancy widget transition effects are all customizable using CSS.

However, I've also another [alternative solution]( https://stackoverflow.com/questions/19653295/connecting-key-accelerators-in-gtk-gtkmm) in mind in case CSS fails me.

If anyone knows what I'm missing with CSS thing, please let me know.

**Comment by Keyikedalube** [comment]
What about new keyframe seeking shortcuts without `Ctrl` key:
1. Next keyframe `]`
2. Prev keyframe `[`

BTW, I realized `Home` and `End` buttons are implemented for seek begin and end on `CanvasView::on_key_press_event`

Since the below two new shortcuts are agreed

> I experimented with new keyboard shortcuts for frame seeking:
>
> 1. 1 frame front and back . ,
> 2. 1 second front and back Shift+> Shift+<
>
> and maybe...
> 3. Start and end Shift+Ctrl+> Shift+Ctrl+<

The third option is implementable. I noticed **Seek to Begin** and **Seek to End** are without accelerator actions.

I'm working on the alternative solution ie., move **Navigation** to a new menubar and make its `Gtk::Box` container hidden. That way users won't see this redundant menu option but keep the shortcut accelerators active behind the scene :)

**Comment by morevnaproject** [comment]
agree with all proposals in https://github.com/synfig/synfig/issues/1733#issuecomment-707754140 ^__^

**Comment by Keyikedalube** [comment]
Thanks @morevnaproject 

I just got to set the shortcut key bindings inside the source file now. Hidden menubar is already implemented on my side.

I got to implement changes for autotools though. Thanks to rodolforg! He committed the autotools script in my previous PR #1577.
This issue and that has the same build commands. Fingers crossed copy-paste would work just fine :)
