### ISSUE TITLE
Cut/Copy/Paste shortcuts are incorrect within dialog text boxes on Mac

### ISSUE THREAD

**Issue by sflanker** [synfig/synfig#1734]
**Synfig version & platform**:

Mac OS Catalina 10.15.6
Synfig Stable (1.2.2)

**Issue description**:

While the keyboard shortcuts for Cut/Copy/Pasting layers reflect Mac standards (Command+X/C/V), the shortcuts when editing text inside of dialogs (such as the HTML code text in the color dialog) are hardcoded to be Ctrl+X/C/V.

**Comment by sflanker** [comment]
And in Synfig v. 1.3.16 cut/copy/paste shortcuts in dialog text boxes is broken completely!

**Comment by rodolforg** [comment]
For implementation:

> For example, on X11/Windows, the Control key is used for invoking menu shortcuts (accelerators), whereas on Apple computers it’s the Command key (which correspond to GDK_CONTROL_MASK and GDK_MOD2_MASK, respectively).
(Source: https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkModifierIntent)

So, GDK_CONTROL_MASK masks Control key on both systems, but on MacOS it should used GDK_MOD2_MASK instead.

**Comment by rodolforg** [comment]
> And in Synfig v. 1.3.16 cut/copy/paste shortcuts in dialog text boxes is broken completely!

Could you please give me an example/use case? I'm not a MacOS user, so I need some guidance here :)

**Comment by sflanker** [comment]
Repro steps: Open color dialog (double click on fill color), select HTML color code, hit either Ctrl+C and/or Cmd+C, close the color dialog and open another one (i.e. double click on the color for a some shape), select the HTML color code, hit either Ctrl+V and/or Cmd+V.

Expected behavior: the color code from the first color should be pasted in to the color code text box for the second. Ideally this works with the OS specific keyboard shortcut by default.

In 1.2.2 this works if you use Ctrl+C and Ctrl+V. In 1.3.16 neither one works. It should go without saying that copy and pasting text to/from other applications should also work.

**Comment by sflanker** [comment]
I think in 1.3.16 the keypress is getting picked up by the main work area and causing the currently selected layer to be copy and pasted.

**Comment by ice0** [comment]
Looks like the same problem here https://github.com/synfig/synfig/issues/1713

**Comment by Keyikedalube** [comment]
> And in Synfig v. 1.3.16 cut/copy/paste shortcuts in dialog text boxes is broken completely!

Cut/Copy/Paste behavior fixed in #1821 😃 

> Mac standards (Command+X/C/V), the shortcuts when editing text inside of dialogs (such as the HTML code text in the color dialog) are hardcoded to be Ctrl+X/C/V.

Anyone who fixes #1814 also fixes this issue

**Comment by rodolforg** [comment]
> And in Synfig v. 1.3.16 cut/copy/paste shortcuts in dialog text boxes is broken completely!

This issue is already fixed in v1.4.1.

**Comment by ice0** [comment]
Just checked. Works like expected.
