### ISSUE TITLE
The tab key should move focus between the X and Y input boxes of Size, Orientation, Origin

### ISSUE THREAD

**Issue by sflanker** [synfig/synfig#1735]
**Synfig version & platform**:

MacOS 10.15.6
Synfig 1.3.16

**Issue description**:

The tab key should move the focus from the X to the Y input boxes and then commit the changes when pressed from the Y input box.

**Comment by rodolforg** [comment]
Maybe duplicated #1208

**Comment by sflanker** [comment]
Yup, I opened a duplicate. Sorry about that.
