### ISSUE TITLE
Animated shapes and text rendering within the animation canvas has become noticeably blurry in v. 1.3.16

### ISSUE THREAD

**Issue by sflanker** [synfig/synfig#1736]
**Synfig version & platform**:
MacOS 10.15.6
Synfig 1.3.16

**Issue description**:

Text and shapes in the animation canvas render with a lot of blur. It's not all shapes, for example new shapes look sharp, but shapes that have been animated are blurry. It didn't use to have this problem in earlier versions. This happens with both the Cobra (software) and Cobra Preview (software) rendering modes, but it does not happen in Cobra Draft mode, however that mode fails to render text (I'm not sure if it's worth noting here but rendering is obscenely slow now, again not a problem in 1.2.2).

Stable (1.2.2):

![](https://www.paulwheeler.us/files/SynfigTextRendering1-2-2.png)

Dev (1.3.16):

![](https://www.paulwheeler.us/files/SynfigTextRendering1-3-16.png)

**Comment by rodolforg** [comment]
Sadly, the current implementation of text layer makes this happen to all layers below it.
So, as a (annoying) quick fix, you can encapsulate the text layer into a group, with the text as its solo element.

**Comment by ThaFireDragonOfDeath** [comment]
Related: https://github.com/synfig/synfig/issues/831

**Comment by Keyikedalube** [comment]
Closed this in favor of the linked issue above

**Comment by Keyikedalube** [comment]
Closed this in favor of the linked issue above
