### ISSUE TITLE
Use correct data type and reduce build warning messages

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1738]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
g++ reports build warning message about incompatible data type in an if condition.

![20201005_08h27m54s_grim](https://user-images.githubusercontent.com/24214509/95036593-0620f500-06e6-11eb-9727-32c433c28208.png)

I think it's better to use the correct data type and resolve those (there are more) warning messages.
Easy issue for Hacktoberfest :)

**Comment by Keyikedalube** [comment]
All these three files need to define their data types as `unsigned long` from `int`
- https://github.com/synfig/synfig/blob/75f78f249e76c70453c992f5795908979f8dd40d/synfig-studio/src/gui/widgets/widget_soundwave.cpp#L200-L201
- https://github.com/synfig/synfig/blob/75f78f249e76c70453c992f5795908979f8dd40d/synfig-studio/src/gui/states/state_bone.cpp#L1092
- https://github.com/synfig/synfig/blob/75f78f249e76c70453c992f5795908979f8dd40d/synfig-studio/src/synfigapp/actions/vectorization.cpp#L272

**Comment by rahmanuh** [comment]
Hi,

I am interested to try to solve this. May I work on this issue?

Best regards,
Rahmanu

**Comment by morevnaproject** [comment]
Assigned to you!
