### ISSUE TITLE
Correct wrong documented comment

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1742]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
JackDial class has incorrect documented name at the end of its class declaration
https://github.com/synfig/synfig/blob/60dc5b6b29c215e73c38bd3da4d2884696faf49e/synfig-studio/src/gui/dials/jackdial.h#L67

I'm working on another synfig issue where I need to find out all occurences of the word 'FrameDial' and the above one is misleading...

![Screenshot from 2020-10-06 18-52-48](https://user-images.githubusercontent.com/24214509/95207471-8be79200-0805-11eb-894a-6f2d93cab916.png)

Change the wrong documented name to its proper class name.
Easy issue for Hacktoberfest

**Comment by rahmanuh** [comment]
Hi again. 
I think it needs a hacktoberfest label  :)

**Comment by DhairyaBahl** [comment]
I would like to work on this issue. Kindly assign it to me 

Thanks :)

**Comment by Keyikedalube** [comment]
Synfig repo is already labeled with "hacktoberfest" topic and any issue you pick regardless of the said label applied or not is already part of Hacktoberfest.

>3. Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as hacktoberfest-accepted.

You can begin working and make a PR for this issue :)

**Comment by ice0** [comment]
@DhairyaBahl Assigned to you!

**Comment by DhairyaBahl** [comment]
@ice0 @Keyikedalube A fixed the issue and made a pull request. 

Thanks :)
