### ISSUE TITLE
Update .gitignore for qtcreator IDE

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1752]
**Issue description**:
Synfig doc has a new [QtCreator IDE guide](https://synfig-docs-dev.readthedocs.io/en/latest/ide/QtCreator.html) and like other IDEs, this IDE also generates two unique files for project setup:
- build-synfig-*
- CMakeLists.txt.user

We don't want to track those files so they need to be added to .gitignore lists like how they're done for NetBeans and CLion
https://github.com/synfig/synfig/blob/045039035ffc3c54c21f29d1c14957f4a47e1808/.gitignore#L238-L249

**Comment by Keyikedalube** [comment]
👉 Easy and Hacktoberfest 😁

**Comment by marcelodof** [comment]
heyy, I can help you
