### ISSUE TITLE
Fix whitespace indentation for duckmatic.cpp

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1755]
**Issue description**:
The file duckmatic.cpp is indented with spaces. All synfig files use tab character for indentation.
Moreover, we also have `-Wmisleading-indentation` warning message triggered because of inconsistent whitespace indentation.

On your preferred IDE or programming text editor, turn on whitespace visualization (if this feature is provided) to easily fix this issue.

# Spaces
![Screenshot from 2020-10-09 12-25-06](https://user-images.githubusercontent.com/24214509/95552554-80c17b80-0a2a-11eb-8c39-7df034d831f4.png)

# Tabs
![Screenshot from 2020-10-09 12-24-18](https://user-images.githubusercontent.com/24214509/95552506-69828e00-0a2a-11eb-801d-59b6dc8be38f.png)

**Comment by Keyikedalube** [comment]
👉 Easy and Hacktoberfest 😃

**Comment by akshitagupta20** [comment]
Hi @Keyikedalube 
I would like t o contribute to this issue.

**Comment by rahmanuh** [comment]
Does it mean duckmatic.cpp should use tab for indent instead of spaces?

**Comment by Keyikedalube** [comment]
@rahmanuh Yes

**Comment by rahmanuh** [comment]
There will be many changes in the file. May I take this issue?

13 okt. 2020 09:49 av notifications@github.com:

**Comment by Keyikedalube** [comment]
Go make that PR :)

You should make sure `-Wmisleading-indentation` warning is resolved OK
