### ISSUE TITLE
Change single-line comment to multi-line comment

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1756]
**Issue description**:
The file below uses the ` \` character to document through visualization but backlash character triggers multi-line comment warning message while building synfigstudio.

- https://github.com/synfig/synfig/blob/edce8cc811ff8a58bc3a30cdd72aca846b814128/synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp#L1281-L1291
- https://github.com/synfig/synfig/blob/edce8cc811ff8a58bc3a30cdd72aca846b814128/synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp#L1388-L1399

Using multi-line comment will resolve this issue. Something like this:
```c++
/*
 *         Multi
 *         /   \
 *      line   comment
 *
 * Won't cause -Wcomment warning
 * Will compile just fine
 */
```

**Comment by Keyikedalube** [comment]
👉 Easy and Hacktoberfest 😃

**Comment by DhairyaBahl** [comment]
@Keyikedalube @AYESDIE 

I would like to work on this issue. Kindly look on my previous 3 PRs.
Thank you

**Comment by DhairyaBahl** [comment]
Kindly assign this to me :)
