### ISSUE TITLE
Resolve misleading indentation warning

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1760]
**Issue description**:
Minor issue caused by the use of inconsistent whitespace character for indentation.

Warning message to resolve:
`warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]`

![Screenshot from 2020-10-09 21-06-03](https://user-images.githubusercontent.com/24214509/95603148-842d2500-0a73-11eb-8b5a-608ff5ce2422.png)

https://github.com/synfig/synfig/blob/cde6d0a960a6bee84473fddcaa425fe6c67c9d64/synfig-studio/src/gui/workarea.cpp#L1472

**Comment by Keyikedalube** [comment]
👉 Easy and Hacktoberfest 😃

**Comment by BobSynfig** [comment]
Please avoid to create issues tagged "Hacktoberfest" for everything, this is counter productive and against the rules.
This could even be reported as spam with "Report a repository that doesn't follow Hacktoberfest's values." and void the efforts of real PR submiters.
If someone needs so much desperately a T-shirt, I have a few in my closet that are now too small for me


https://hacktoberfest.digitalocean.com/details

> **Quality standards**
> In line with Hacktoberfest value #2 (Quantity is fun, quality is key), we have provided examples of pull requests that we consider to be low-quality contributions (which we discourage).
> 
> Pull requests that are automated (e.g. scripted opening pull requests to remove whitespace/fix typos/optimize images).
> Pull requests that are disruptive (e.g. taking someone else's branch/commits and making a pull request).
> Pull requests that are regarded by a project maintainer as a hindrance vs. helping.
>**Something that's clearly an attempt to simply +1 your pull request count for October.**
> **Last but not least, one pull request to fix a typo is fine, but 4 pull requests to remove a stray whitespace is not.**

> **Let's work together to reduce spam**
> Spammy pull requests can be given a label that contains the word "invalid" or "spam" to discount them. Maintainers are faced with the majority of spam that occurs during Hacktoberfest, and we dislike spam just as much as you. If you're a maintainer, please label any spammy pull requests submitted to the repositories you maintain as "invalid" or "spam", and close them. Pull requests with this label won't count toward Hacktoberfest.
> There's a fourteen-day review window for all pull requests before they count toward completing the challenge. Once a participant has submitted four eligible pull requests (ready-to-review, not drafts), the review window begins. This period gives maintainers time to identify and label spammy pull requests as invalid. If the pull requests are not marked as invalid within that window, they will allow the user to complete the Hacktoberfest challenge. If any of the pull requests are labeled as invalid, the user will return to the pending state until they have four eligible pull requests, at which point the review period will start again.
> **Bad repositories will be excluded. In the past, we've seen many repositories that encourage participants to make simple pull requests – such as adding their name to a file – to quickly gain a pull request toward completing Hacktoberfest. While this may be a learning tool for new contributors, it goes against one of our core values for Hacktoberfest. The quality of pull requests is paramount; quantity comes second. These repositories do not encourage quality contributions and provide an unfair advantage in completing the Hacktoberfest challenge. We've implemented a system to block these repositories, and any pull requests submitted to such repositories will not be counted.**
> 
> Report a repository that doesn't follow Hacktoberfest's values.

<div align="center">
<img src="https://i.imgflip.com/4hz3cz.jpg" >
</center>

@morevnaproject @ice0 @rodolforg

**Comment by Keyikedalube** [comment]
@BobSynfig You do realize at some point those issues were going to be resolved by someone else in the future, right?
*Even if I did not open them...*

I know I create issues that are too easy and request maintainers to tag them with **Easy** and **Hacktoberfest**
Kind of makes me look like a douchebag who's chasing after "quantity" rather than "quality"

But you are also missing the actual value new contributors provide. They're learning:
1. Not just synfig codebase
2. But git too &&
3. Most importantly enhancing their programming skills

And with those skills gained, imagine their future effort diversifying more and more to other projects and their programming careers.

Go and check some of the PR they made. How much effort is being given to help and nurture them. That's the value of Open Source and the real reason Hacktoberfest event is being done every year.

And when they make a successful PR, they're actually resolving issues. Issues that I think are worth resolving.
Now there's quality.

When you see their effort as low quality or spammy, you're also seeing my effort in celebrating Open Source the same too.

# Just to make sure I'm aware of them below quality standard examples

> Pull requests that are automated (e.g. scripted opening pull requests to remove whitespace/fix typos/optimize images).

Haven't encountered an automated PR. Or I don't know what that is.

>Pull requests that are disruptive (e.g. taking someone else's branch/commits and making a pull request).

Yup, and what was done with the PR https://github.com/synfig/synfig/pull/1721

> Pull requests that are regarded by a project maintainer as a hindrance vs. helping.

Here's an example of hindrance https://github.com/synfig/synfig/pull/1720

> Something that's clearly an attempt to simply +1 your pull request count for October.

The above two PR I just linked

> Last but not least, one pull request to fix a typo is fine, but 4 pull requests to remove a stray whitespace is not.

A similar PR https://github.com/synfig/synfig/pull/1748
Thank me later when you use your IDE search feature to track all occurences of the word *FrameDial* and that mistake doesn't pop up. I just saved you some eye muscles.

# My reason behind tagging hacktoberfest for all issues I open
Branding dude

There are no activities for issues that are not tagged with "Hacktoberfest" because incoming new contributors think those issues are too difficult (my guess)
Compare that to willing contributors already working and making a PR for issues tagged with "Easy" and "Hacktoberfest"

The stats 📈 say synfig's participation in the Hacktoberfest event is on the right track.

**Comment by morevnaproject** [comment]
Thanks for bringnin this up, @BobSynfig!

I think it is okay to have a few simple issues to help new people get started with contributing  to Synfig or any other open-source project, especially considering that the amount of such issues is limited and they will end soon.
Also. such simple tasks might be tedious for established contributors, but they should be fixed anyway. So, I think it is good to give them to newbies, allowing them yo gain basic contributing experience.

Of course, it would be better to group similar issues together into bigger tasks. I.e. instead of having multiple issues like "Fix whitespace indentation in file X" it would be nice to have "Fix whitespace indentation in all files" (or "Fix whitespace indentation in synfig-core"). ^__^

In any case I strongly believe @Keyikedalube have good intentions in mind and his efforts on attracting new community members are much appreciated. Also, thanks to all contributors who helping newbies to gain new knowledge. ^__^

**Comment by Keyikedalube** [comment]
This issue is open for newbies :) Previous PR was closed due to inactivity from the OP

**Comment by rahmanuh** [comment]
Is the fix also for other lines? For example:
https://github.com/synfig/synfig/blob/0576fa82b92210aacdc9b8ed6d32a3dfbceea9b7/synfig-studio/src/gui/workarea.cpp#L204

**Comment by Keyikedalube** [comment]
@rahmanuh No, that's vertical alignment :)
https://github.com/synfig/synfig/blob/0576fa82b92210aacdc9b8ed6d32a3dfbceea9b7/synfig-studio/src/gui/workarea.cpp#L202-L205

All those parameters belong to `drawing_area`, that's why they were indented this way. And the indentation's perfectly valid.

The only fix needed is already hinted above in the issue description to resolve the said warning message.

**Comment by rahmanuh** [comment]
Okay, I will only fix the hinted one.
I see in my IDE that in the line I mentioned has tab and whitespaces.

**Comment by Keyikedalube** [comment]
> I see in my IDE that in the line I mentioned has tab and whitespaces.

Thanks :) But this line doesn't trigger any warning message so we can safely ignore that.

Maybe one day when `drawing_area` needs to be changed/adapted, that vertical alignment could be fixed with consistent tabs.
