### ISSUE TITLE
Can’t move origin box relative to layer with Ctrl pressed in version 1.3.16

### ISSUE THREAD

**Issue by BobSynfig** [synfig/synfig#1763]
**Synfig version & platform**:
Versions >=1.3.12

**Issue description**:
From the forums, all credits to Synfigme:
https://forums.synfig.org/t/bug-cant-move-origin-box-relative-to-layer-with-ctrl-pressed-in-version-1-3-16/11356

> **synfigme**
> 
> When I try to move the origin box position over the layer, while I hold the left mouse button down over the green dot, with the cntrl button pressed, the box moves the position of the layer instead of moving over the layer. I never had this prob in earlier

> **BobSynfig**
> I confirm, it seems this has changed between 1.3.11 and 1.3.12 :confused: (at least for origin of Group Layer)

**Comment by morevnaproject** [comment]
Hi! This is an expected behavior. User now should drag violet control point (right under green control point) to change origin. ^__^
