### ISSUE TITLE
Migrate from Gtk::H/VBox to Gtk::Grid for CanvasView

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1764]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
CanvasView class uses `Gtk::HBox` and `Gtk::VBox` containers which are already deprecated long ago.

Migrate from old deprecated container box to `Gtk::Grid` which is pretty much stable.

![Screenshot from 2020-10-10 10-45-31](https://user-images.githubusercontent.com/24214509/95646822-d872ec00-0ae9-11eb-8bc8-b75e1d230e88.png)

The reason I'm not recommending `Gtk::Box` is because [packing API names](https://developer.gnome.org/gtk4/stable/ch40s02.html#id-1.7.4.4.21) have changed in Gtk4. And using Box over Grid would just add another maintenance flag to look out for in the future when synfig upgrades to gtkmm4.

With Grid implemented, these files **synfig/synfig-studio/src/gui/canvasview[.h,.cpp]** would be free of `Gtk::Box` API and improve synfigstudio stability.

**Comment by Keyikedalube** [comment]
👉 Easy and Hacktoberfest 😃

**Comment by fardragon** [comment]
Hi, I'd like to take a crack at this.

**Comment by Keyikedalube** [comment]
@fardragon Go ahead and make a PR :)

Happy hacking!
