### ISSUE TITLE
Improve canvas zoom keyboard shortcut UX

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1768]
**Issue description**:
Synfig uses the following keyboard shortcuts for canvas zooming:
1. `Ctrl + =` -> Zoom in
2. `Ctrl + -` -> Zoom out
3. `Ctrl + Shift + z` -> Best fit

Point no. 3 is causing this issue #1005 on Linux systems.

In order to resolve this, below is the new improved keyboard shortcuts list for canvas zooming based on Inkscape model:
1. `=` -> Zoom in
2. `-` -> Zoom out
3. `0` -> Best fit

The file to modify -> synfig/synfig-studio/src/gui/app.cpp
You should know [accelerator keynames](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gdk/keynames.txt) in order to successfully implement the above new shortcut.

**Comment by Keyikedalube** [comment]
👉 Easy and Hacktoberfest 😃

**Comment by AnshitaVishwa** [comment]
@Keyikedalube I would like to work on this issue.

**Comment by Keyikedalube** [comment]
Yours :)

Maintainers will assign you soon

Good luck!

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
