### ISSUE TITLE
[MSYS/CMake] Build fails if msys64 is not installed to c:\msys64

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#1785]
**Issue description**
Because of hard-coded path "c:/msys64/usr/bin/perl" in "synfig.git\cmake\SynfigIntltool.cmake build fails if MSYS is installed to a different place (drive H: in my case).

I made a quick patch to address this problem. It determines current WIN32 path to msys64 directory in 2-build-msys-cmake.sh script and then passes it to cmake through '-D' argument. I will send a pull request if this is a correct way to address this issue (my understanding of cmake is very basic).

**Comment by ice0** [comment]
```
# When MinGW is used without MSYS environment (for example, Ninja
# generator uses the standard Windows `cmd` shell for building), `intltool-merge`
# cannot be started, because it is just a Perl script, and `cmd` does not know how
# to run it. In this case, we need to explicitly add the interpreter to the command.
if(INTLTOOL_MERGE_EXECUTABLE AND MSYS)
    message(STATUS "Fixing intltool-merge command...")
    set(INTLTOOL_MERGE_EXECUTABLE c:/msys64/usr/bin/perl ${INTLTOOL_MERGE_EXECUTABLE})
endif()
```

I think there should be `NOT MSYS`. This way it will patch the intltool path only if MSYS is not found.
I broke it in this commit: https://github.com/synfig/synfig/commit/42dd20a6bfa683c84787bb0e286d9816d55b37da

**Comment by Svarov-RZM** [comment]
@ice0 
I think the current logic is correct. The problem is that ninja itself calls cmd.exe from MSYS environment for processing external commands instead of using bash or call it directly. Cmd.exe, in turn, know nothing about perl scripts, so we need to specify full path to the interpreter.

I sent patch I was talking about that addresses this issue.

**Comment by ice0** [comment]
Yes, you are right.
In this situation, is better to detect MSYS path by using environment variables. They are already set, if you run CMake from MSYS shell.

So here the place where you can define MSYS_ROOT:

**synfig/CMakeLists.txt**
```
# MSYS is defined for MSYS Makefiles generator and undefined for Ninja (for example)
# But if you run CMake from MSYS shell, we can still detect MSYS by environment variables (MINGW_PREFIX)
# https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Write-Platform-Checks
if(MINGW AND NOT MSYS)
	if (NOT DEFINED ENV{MINGW_PREFIX})
		message(FATAL_ERROR "Currently we only support MSYS2 environment for MinGW compiler on Windows."
				" Please pass '-DMSYS=1' to your CMake command to force using MSYS."
				" Also you need to set MINGW_PREFIX environment variable if your MSYS2 installation is not in standard path (c:\\msys64\\)")
	else()
		set(MSYS ON)
		set(MSYS_ROOT "$ENV{MINGW_PREFIX}/..") <--------------------- here
	endif()
endif()
```

**Comment by Svarov-RZM** [comment]
1. @ice0 I checked the review on my commit and yes, MSYS_ROOT=\`pwd -W|grep -o .*/msys64\` will not properly determine path, I am stupid. The correct line should be MSYS_ROOT=\`cygpath -m /|sed 's/\\/$//'\`, sed is needed to remove the leading slash.
2. @AYESDIE suggested using env. variable MINGW_PREFIX and it will not work. If you run it in MSYS `echo $MINGW_PREFIX` you will get output `/mingw32` (or /mingw64) and we need the WIN32 path like C:\msys2. Or am I missing something?

**Comment by AYESDIE** [comment]
That's why you need to set `MSYS_ROOT` as `$ENV{MINGW_PREFIX}/..` if you need to use the path where msys2 is installed.

**Comment by ice0** [comment]
> Or am I missing something?

Yes. MSYS is doing path mangling, when needed. You can check this by running `cmd` from MSYS2 shell.

```
cmd
echo %MINGW_PREFIX%

C:/msys64/mingw64
```
As you can see it convert path to Windows style when needed :)

**Comment by Svarov-RZM** [comment]
Oh my god, I would have never guessed that there's some path mangling underneath...
Alright, I closed the original pull request, reverted everything, and rebuilt Synfig with suggested changes. It works on my system with custom path, so seems to be good.

I am a bit hesitant on sending pull requests now, can you please check it on my fork first: https://github.com/Svarov-RZM/synfig/commit/a0f2dfc172216e4ff444359373b73d6bd63bc49a
If looks good, I will send a new pull request.

**Comment by ice0** [comment]
@Svarov-RZM looks good!
