### ISSUE TITLE
Migrate old Widget_Defaults container to Gtk::Grid

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1787]
**Issue description**:
1. `Gtk::Table` to `Gtk::Grid`
2. `Gtk::VBox` &nbsp; to `Gtk::Grid`

![Screenshot from 2020-10-19 10-46-43](https://user-images.githubusercontent.com/24214509/96405089-19f64c00-11fa-11eb-9c60-977d0de78790.png)

Both Table and Grid has `attach()` functions but their arguments differ. You've to adapt the existing [Table](https://developer.gnome.org/gtkmm/stable/classGtk_1_1Table.html#a28b6926e68337a51ba29f2b4dd69f087) container to [Grid](https://developer.gnome.org/gtkmm/stable/classGtk_1_1Grid.html#a664d8700c0a8176c2e2595e1d9938ff0) by eliminating most of its arguments.

Pen and paper is a good starting point to visualize how each widgets are supposed to be attached :)

**Comment by Keyikedalube** [comment]
:point_right: Easy and Hacktoberfest :smiley:

**Comment by Keyikedalube** [comment]
Hacktoberfest is ending soon and I doubt this issue will be resolved at all from *new contributors*

There are more widgets apart from widget_defaults that use `Gtk::Table`. Maybe, I could resolve all of them in one PR :)

- widget_coloredit
- widget_waypoint

@rodolforg @ice0 opinion?

**Comment by ice0** [comment]
I think that a good idea :)

**Comment by Keyikedalube** [comment]
I'm working on this :)
