### ISSUE TITLE
Improve tool items keyboard shortcuts

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1794]
**Issue description**:
- New single key shortcuts proposal
[draft document](https://synfig-docs-dev.readthedocs.io/en/latest/projects/shortcuts.html)

- Keynames code for reference
[gdk keynames](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gdk/keynames.txt)

- File to modify
https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/app.cpp

Using menu mnemonics for tool items is causing conflicting keyboard shortcuts. Some were discussed here #1336

Single key shortcuts are based on Inkscape model and some proposed shortcuts are already resolved:
- **Zoom in and Zoom out**
New improved zoom shortcuts implemented here #1769

While some need to be adapted to newer shortcuts:
- **Scale and Rotate**
New navigation shortcuts use those keys now #1776

You can propose yours below and could be discussed with project contributors :)
Though the final approval would have to be made by @morevnaproject

**Comment by Keyikedalube** [comment]
:point_right: Easy and Hacktoberfest :smile:

**Comment by Keyikedalube** [comment]
I guess it's OK now to remove the Hacktoberfest label. The event's over in 2 hrs (over here).

BTW, I feel this issue is deserving of "good first issue" :)

**Comment by ice0** [comment]
Done :)

**Comment by DhairyaBahl** [comment]
@ice0 I would like to work on this issue but should I ?? its good first issue so i ideally i should leave it for the new contributors. I dunno, plz tell me. 

Thanks:)

**Comment by ice0** [comment]
@DhairyaBahl Sure, just take it. There is a lot of interesting issues for a new contributors and we can add more later :)

**Comment by DhairyaBahl** [comment]
@ice0 @keyikedalube 

I referred to [draft document](https://synfig-docs-dev.readthedocs.io/en/latest/projects/shortcuts.html) and there is no mention of use of the alt key. So, Do I have to use the alt key or just key ???

Kindly tell me Thanks :)

**Comment by Keyikedalube** [comment]
The goal is to implement single key behavior for synfig tool items just like Inkscape and GIMP.

Yes, you are going to use just the key.

Alt key is reserved for menu and button mnemonics.

**Comment by DhairyaBahl** [comment]
> The goal is to implement single key behavior for synfig tool items just like Inkscape and GIMP.
> 
> Yes, you are going to use just the key.
> 
> Alt key is reserved for menu and button mnemonics.

@Keyikedalube 
Hello Interacting with you after a long time :) 

Got it Thanks for help :)

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
