### ISSUE TITLE
Implement canvas zoom legacy keyboard shortcuts

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1798]
Maintainers, it's possible to have two keyboard shortcuts at the same time. For now, we have this PR implementing Inkscape style shortcuts
1. canvas-zoom-in &nbsp;&nbsp;:  `=`
2. canvas-zoom-out :  `-`
3. canvas-zoom-fit &nbsp;&nbsp;:  `0`

The above new canvas zoom shortcuts is already paving way for UX consistency for issue #1122

However, if you want to keep the legacy style
1. canvas-zoom-in &nbsp;&nbsp;:  `Ctrl + =`
2. canvas-zoom-out :  `Ctrl + -`
3. canvas-zoom-fit &nbsp;&nbsp;:  `Ctrl + 0` <--- New

It's possible with this PR #1776 I made; hidden menubar

So it's a win-win for both parties; improved vs legacy

_Originally posted by @Keyikedalube in https://github.com/synfig/synfig/pull/1769#issuecomment-709933305_

**Comment by Keyikedalube** [comment]
:point_right: Easy and good first issue :point_left:

**Comment by Keyikedalube** [comment]
I guess it's OK now to remove the Hacktoberfest label. The event's over in 2 hrs (over here)

**Comment by DhairyaBahl** [comment]
@Keyikedalube @ice0 I would like to work on this issue. It is much more like the previous issue that I solved of keyboard shortcuts.
Kindly Assign it to me. :)

**Comment by Keyikedalube** [comment]
:) Thanks for wanting to tackle this issue!

Go make that PR

**Comment by DhairyaBahl** [comment]
@Keyikedalube I wanted to know, 
* Do I have to add legacy key controls as normal method?? Will They Work ??
*Or do i have to use hidden menubar you created ??

Kindly tell me. Thanks :)

**Comment by Keyikedalube** [comment]
hidden menubar

**Comment by Keyikedalube** [comment]
Linked PR merged. Issue fixed.
