### ISSUE TITLE
Don't dock dockable widgets again on next launch if user undocks and closes them

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1803]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
I'm trying to keep my dock toolbar minimal with fewer but frequently used docks so it's easier to browse around.
Most docks can be closed or removed from the toolbar however some (or just one, haven't tried all) can't,

One such dock that I don't even use a lot/at all is the canvas browser.
I can close it but quit & run synfigstudio again, I'm always presented with this window.

Is this dock that important to always be docked?

![Screenshot from 2020-10-24 19-15-43](https://user-images.githubusercontent.com/24214509/97083466-fe41da00-162d-11eb-9a9f-a0febc07aa52.png)

**Comment by rodolforg** [comment]
No, it's a bug, most probably on Synfig initialization, because, if you close the Canvas panel from layout/workspace, it isn't stored in workspace.layout in synfig settings file.

**Comment by Keyikedalube** [comment]
Investigating...

**Comment by Keyikedalube** [comment]
Late reply :P

Anyway, I did a quick investigation with your suggested "workspace.layout" file. The class that does the core work of set/get layout key values is `DockManager`
Tried printing the string `res` content when `DockManager::save_layout_to_string()` is called:

1. Default layout before closing canvas dock
> Final res string: [mainwindow|0|0|1366|704|[hor|1064|[vert|505|[hor|142|[book|toolbox,229]|[mainnotebook]]|[hor|355|[book|params|keyframes]|[book|timetrack|curves|children|meta_data|soundwave]]]|[vert|257|**[book|*canvases*|pal_edit|navigator|info]**|[vert|207|[book|tool_options|history]|[book|layers|groups]]]]]

2. After closing the dock
> Final res string: [mainwindow|0|0|1366|704|[hor|1025|[vert|469|[hor|137|[book|toolbox,211]|[mainnotebook]]|[hor|342|[book|params|keyframes]|[book|timetrack|curves|children|meta_data|soundwave]]]|[vert|239|**[book|pal_edit|navigator|info]**|[vert|192|[book|tool_options|history]|[book|layers|groups]]]]]

3. Re-launch synfigstudio
> Final res string: **[dialog|26|23|177|159|[book|canvases]]**|[mainwindow|0|0|1366|704|[hor|1064|[vert|505|[hor|142|[book|toolbox,91]|[mainnotebook]]|[hor|355|[book|params|keyframes]|[book|timetrack|curves|children|meta_data|soundwave]]]|[vert|257|[book|pal_edit|navigator|info]|[vert|207|[book|tool_options|history]|[book|layers|groups]]]]]

I haven't much time to keep digging more. I don't know what triggers *canvases* dock to be set as a dialog and not use the saved settings from step 2.

**Comment by rodolforg** [comment]
As I tried to mean, the workspace layout is saved fine. My guess is DockManager or Studio initialization force the Canvas dock reopening on launch :)

**Comment by Keyikedalube** [comment]
Same behavior confirmed for Toolbox dock too. Tried to keep only the **Tool Options** dock and use new tool items keyboard shortcuts to keep my docks tab minimal. Toolbox dialog was presented after closing and opening synfig.

**Comment by Keyikedalube** [comment]
Taking a look at this in my free time...

**Comment by rodolforg** [comment]
Only this ome?

**Comment by Keyikedalube** [comment]
@rodolforg Time's all lost and gone by the time I'm done contemplating what the appropriate solution to this would be LOL.

The thing is I want to solve at least one synfig issue this month :)

**Comment by Keyikedalube** [comment]
> My guess is DockManager or Studio initialization force the Canvas dock reopening on launch

Yup

For toolbox, this is the line
https://github.com/synfig/synfig/blob/7d4d8b79ba5e00e1e28d66fb3b2ebb30f875387e/synfig-studio/src/gui/app.cpp#L1710
and Canvas Browser _but these lines are not the cause_
https://github.com/synfig/synfig/blob/7d4d8b79ba5e00e1e28d66fb3b2ebb30f875387e/synfig-studio/src/gui/app.cpp#L1504-L1506

Now the "contemplating" part... 

Since toolbox not only contains tools but fg/bg color widgets too, deleting that line `dock_toolbox->present(); ` would also make it hard for users to configure their color choice before creating a new layer from the tool items. Do you want to move the color widget to it's own dock_color.cpp?

Canvas Browser is complicated since both the actual workarea canvas and this dock are one. So even if the browser dock is detached and closed, loading canvas on synfig startup would automatically load the dock again as a dialog. I don't exactly know how this class works so I need to dig deeper before I can suggest a possible solution.
