### ISSUE TITLE
Papagayo integration is buggy with synfig v1.3.16

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#1804]
Synfig v1.3.16 on windows 10 20H2

.pgo layer should show all the phonemes layers as its child layer after importing it, but it's not showing.
![Screenshot 2020-10-25 203116](https://user-images.githubusercontent.com/50204208/97110820-4d0c7400-1701-11eb-9b49-d2edf0971405.png)

**Comment by ice0** [comment]
ping @morevnaproject

**Comment by morevnaproject** [comment]
@yoSachinkr Can you please provide PGO file?

**Comment by yoSachinkr** [comment]
[Track-27-1.zip](https://github.com/synfig/synfig/files/5495860/Track-27-1.zip)
Here's the zip file containing .pgo and .wav files. @morevnaproject
