### ISSUE TITLE
Make toolbar spinbuttons and entries lose focus on mouse leave event

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1808]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
![Screenshot from 2020-10-26 17-10-05](https://user-images.githubusercontent.com/24214509/97168786-0b3a0700-17af-11eb-8891-fd764442de88.png)

When these buttons grab focus, single key canvas navigation (`.` one frame forward and `,` one frame backward) shortcuts become a bit difficult to access.

With focus on and off feature using mouse enter/leave event, users don't have to worry their keyboard shortcuts losing focus to another widget.

I tried implementing this behavior in my sample program [over here](https://stackoverflow.com/questions/64535307/turn-widgets-focus-on-and-off-based-on-mouse-enter-leave-event). Hope this behavior is achievable for synfig too :)

**Comment by Keyikedalube** [comment]
I'm working on this issue.

**Comment by ice0** [comment]
Works not as good as I expected. For example, if you click to window and move mouse cursor out (to not interfere with text cursor) you can't type anything :(

**Comment by Keyikedalube** [comment]
If we default to earlier style ie., without my PR then we'd have to select some other widgets to use:
1. Play/pause and
2. Frame seek keyboard shortcuts

I want input focus to be able to quickly get back to my canvas workspace without having to worry my play key is still being captured by onion spinbutton entry. Plus clicking on the timeline doesn't make the focus go away so from my perspective it's annoying when these entry widgets continue to hold focus after I'm already done with them. The quirky method I used before I made my PR was to click on any framedial buttons or other widgets that'll make the focus go away.

Still the decision is up to you guys. Let me know and I'll close both :)

**Comment by Keyikedalube** [comment]
After thinking this through... I guess there are users who prefer moving the cursor away from the widget before typing. While some like me can get used to hovering and staying put and then editing the entry contents.

I think play/pause and navigation shortcuts would have to be changed to old-style again in the future ie., combine it with `<Control>` key. However, this requires feedback from users. For now, I don't think this issue has much weight that it needs resolving.

Closing it.

**Comment by ice0** [comment]
> it's annoying when these entry widgets continue to hold focus after I'm already done with them

I want to back to this question later, but for me the standard way to get focus out of the edit window is to press the ʻEnter` key or click somewhere outside of it.
