### ISSUE TITLE
Previous selected/created layer is held for draw tool

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1809]
**Synfig version & platform**:
Debian sid
Building from source

**Issue description**:
Same issue like #1666

![Screenshot from 2020-10-27 19-47-17](https://user-images.githubusercontent.com/24214509/97314301-925dac80-188d-11eb-875d-dd3135119990.png)

1. Create a rectangle layer
2. Create any random shape using Draw tool

Draw tool layer is created while still holding the previously selected/created layer.

**Comment by FirasH** [comment]
I can take a look at this one, should be similar to #1699
