### ISSUE TITLE
Migrate ui to resources folder

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1818]
> - move ui into a new gui/resources folder

This is to standardize synfigstudio resources folder like gedit and other gtk apps.

Changes required:
- Move glade files to new proposed folder
- Update CMake and Autotools script

_Originally posted by @rodolforg in https://github.com/synfig/synfig/pull/1577#issuecomment-663950623_

**Comment by Keyikedalube** [comment]
"Easy" and "good first issue" ;)

**Comment by DhairyaBahl** [comment]
@Keyikedalube @ice0 I would like to work on this issue !!

**Comment by ice0** [comment]
Assigned it to you.
