### ISSUE TITLE
Dock keyframes doesn't capture space input in entry text field

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1820]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
[Keyframes dock screencast.zip](https://github.com/synfig/synfig/files/5491701/Keyframes.dock.screencast.zip)

New canvas navigation shortcuts capture the following inputs
- `space` play/pause and
- `-` canvas zoom out

to canvas workspace making it difficult to enter those characters in keyframes dock description column.

**Comment by Keyikedalube** [comment]
I think this could be resolved with this suggestion https://github.com/synfig/synfig/issues/1713#issuecomment-719995751

> Remove it and implement `on_key_press_event()` for all problematic dialogs in a similar way I did in MainWindow when I fixed #257 and 'we' discovered this problem you reported.

**Comment by ice0** [comment]
Can't reproduce on Windows.

**Comment by rodolforg** [comment]
@ice0 the Keyframe dock must be undocked, as a floating window.

**Comment by ice0** [comment]
@rodolforg Confirmed. Thank you!
