### ISSUE TITLE
Improper interpolation of bool type

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#1825]
**Issue description**

The issue is that 'bool' values take three waypoints to change their state. Let's describe the following animation: the circle layer has its color wrapped into a 'switch' converter. We want the color to be blue at 0s and then change it to green at 1s. Should be easily accomplished with 2 waypoints: 'switch-off' at 0s and 'switch-on' at 1s. But that's not going to work because as soon as time changes to 1f the boolean value will change to 'true'. As a workaround we need three waypoints: 'false' at 0s, 'false' at 23f and 'true' at 1s which is counter-intuitive and cumbersome.
![BoolInterpolationBug](https://user-images.githubusercontent.com/28569334/98463540-daa19680-21cc-11eb-8c89-c207d602f8fd.PNG)

**Note**: The interpolation actually shouldn't matter for boolean values, because, you know, they only have two states. So any interpolation should be treated as constant.

**Affected versions**

Seems to be all. Moreover, there's a duplicate issue here: https://github.com/synfig/synfig/issues/658
It didn't get any attention, so I am making a version with more detailed description and example file: 
[BoolInterpolationBug.zip](https://github.com/synfig/synfig/files/5506222/BoolInterpolationBug.zip)

I hope that it at least gets 'confirmed' status so it will be addressed somewhere in the future.

**Comment by Svarov-RZM** [comment]
Alright, I've tested it and all seems to be good. Boolean values now change their state on waypoints and not affected by any interpolation type. Would be nice to see this merged into the upcoming stable version. Thanks @rodolforg.

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.
