### ISSUE TITLE
About SETs. Dialog window to choose existing set or create it.

### ISSUE THREAD

**Issue by MiLoCasellas** [synfig/synfig#1850]
TIP, IDEA: When you have created some SETs, it would be good if when you want to add layers to an existing set, a dialog window will be shown with the list of existing sets instead of having to write the name of an existing set. Then, to be able to choose an existing set or create a new one, from that dialog window.

**Comment by FirasH** [comment]
#1452

**Comment by MiLoCasellas** [comment]
Oh I'm sorry. I always search before writing, but did not find this. Thank you.

**Comment by FirasH** [comment]
With #1878 the feature you asked for has been added to master.

**Comment by MiLoCasellas** [comment]
> With #1878 the feature you asked for has been added to master.

Great! :-) Thanks! ^_^
