### ISSUE TITLE
Minimization bug

### ISSUE THREAD

**Issue by VaibhavDS19** [synfig/synfig#1871]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)
Latest normal build
**Issue description**:
Minimizing the window and then closing it causes the app to never get maximized. This includes when it takes time to build and if we minimize it, it seems to crash sometimes and then never gets maximized. Opening the app causes it to be minimized. Uninstalling and reinstalling doesn't seem to work.
**OS so far used and tried on**
Windows
**Success rate of triggering this issue**
One hundred percent so far.

**Comment by rodolforg** [comment]
Thank you for reporting!
A possible workaround is to erase (or manually edit) the synfig preferences file (`settings-1.4`).
I'm not sure the exact path on windows, but if you're using portable version, the folder is named "config".

**Comment by VaibhavDS19** [comment]
Thank you for replying so fast. Yes, the workaround seems to work perfectly.

**Comment by VaibhavDS19** [comment]
Idea of how it might happen?

**Comment by rodolforg** [comment]
Synfig saves the window position and size on closing. But it seems that it doesn't check if it was minimized or something like that.

**Comment by VaibhavDS19** [comment]
ok, thank you very much for replying.

**Comment by rodolforg** [comment]
It must be fixed :)

**Comment by rodolforg** [comment]
@ice0 @morevnaproject do we really need to save main window position and size? :P
Gtk has some explanations against it: https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-get-position (last paragraph of this method)

**Comment by ice0** [comment]
@rodolforg I think yes. At least we need window size to correctly restore workspace. 
Also it just convenient. No need to move the window to your preferred location every time.

As I see this is Windows-related problem. When you minimize window it just moves it to -30000, -30000 position.

**Comment by rodolforg** [comment]
Is size kept "correctly" (same value before being minimized)?

If I'm not crazy I saw other reports about 'invisible' Synfig when user has two screens then open it later with only one.

**Comment by rodolforg** [comment]
Anyway, here is the code point to work on: https://github.com/synfig/synfig/blob/bbb2dd7c274785398d7f46475175053a9a7d9bf0/synfig-studio/src/gui/docks/dockmanager.cpp#L584

**Comment by ice0** [comment]
> Is size kept "correctly" (same value before being minimized)?

For Windows 10 - yes, Windows 7 - not tested.

**Comment by rodolforg** [comment]
Ok. What about this:

- if width or height < 50, write as something like 640 x 480.
- if left or top < -1000, write as 0,0.
- on read, if left+width < 0, set at (0,y)
- 0n read, if top+height > screen height, set at (x,0)

**Comment by ice0** [comment]
> if left or top < -1000, write as 0,0.

Looks like -100 will be enough.

> on read, if left+width < 0, set at (0,y)
> 0n read, if top+height > screen height, set at (x,0)

I'm not sure if this is required. As for me, if you can see the upper left corner of the window - this gives you the ability to resize the window and this will be enough.

**Comment by rodolforg** [comment]
> Looks like -100 will be enough.

But maybe user moved it that way?



> I'm not sure if this is required. As for me, if you can see the upper left corner of the window - this gives you the ability to resize the window and this will be enough.

My logic was to check if windows is hidden on startup (moved away so it can't be seen in screen). 
In second thought, :
- I didn't propose a check if left > screen width (and in a similar way, the vertical direction)
- I don't know how it behaves when user more than one screen :P

**Comment by rodolforg** [comment]
This issue is fixed in v1.4.1.

**Comment by ice0** [comment]
Just checked, all works fine now.
