### ISSUE TITLE
Installed fonts are missing in Font Family list

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1873]
**Synfig version & platform**:
master bbb2dd7
Windows 10

**Issue description**:

1) Install a new font (.otf or .ttf)
2) Launch Synfig Studio
3) Insert a `Text Layer` on `Canvas`
4) Go to the `Parameters` panel and change `Font Family` value to select the font installed in step 1

The font is not available in the `Font Family` list.

**Comment by FirasH** [comment]
Works fine on openSUSE

**Comment by rodolforg** [comment]
Maybe fontconfig is not updated automatically…

**Comment by FirasH** [comment]
It has something to do with the last commits (a couple of months).

I have some animations made with previous versions of 1.5.0 on Windows where fonts were correctly listed.
Now the same fonts on the same machine are not listed anymore.

**Comment by rodolforg** [comment]
As the related code didn't change since I created the Widget_FontFamily, I don't know how to inspect it.
Maybe something about building? Autotools x CMake? I don't know :(

**Comment by ice0** [comment]
Just checked. This is FontConfig problem (https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/144).

As a temporary solution - right-click on your font file and choose "Install for all users".
