### ISSUE TITLE
 When I try to save a palette the program crashes.

### ISSUE THREAD

**Issue by EdisonMuniz** [synfig/synfig#1876]
**Synfig version 1.4 Window 10**:

Every time I try to record a new color palette Synfig closes.
I tried to save to the desktop and it worked. 
My Windows is in English, but I use Portuguese for the folder names.
I believe the problem is related to the accentuation.

I created two folders on drive C:
A "TEST" and another "AÇÃO".
In the Test folder it worked correctly, but in the Ação folder the program ends.
This confirms that the lock is related to the accentuation.

I take this opportunity to congratulate you on the new implementations. Some were very desired.

**Comment by ice0** [comment]
Hi! Thanks for reporting. I will take a look.

**Comment by ice0** [comment]
Could you please check if this problem is resolved?

Portable version (x64) - download, unpack and run `synfigstudio.exe` from `bin` folder:
https://ci.appveyor.com/api/buildjobs/muhuv6ahwyct88f2/artifacts/SynfigStudio-1.3.16-testing-2020-12-06-win64-73aa7.zip
