### ISSUE TITLE
no package 'sigc++-2.0' found with cmake, vcpkg and pkg-config on windows 10

### ISSUE THREAD

**Issue by mhao1999** [synfig/synfig#1877]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:
I git cloned source code at 2020/11/8, and want to setup visual studio 2017 project file, but failed.
I am trying to build synfig project with cmake, vcpkg and pkg-config on windows 10 with below commands:
```
d:\gtkmm\vs>cmake -DCMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake ..\synfig\
```
and with errors:
```
    -- Building for: Visual Studio 15 2017
    CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
    -- The C compiler identification is MSVC 19.16.27043.0
    -- The CXX compiler identification is MSVC 19.16.27043.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- CMAKE_BUILD_TYPE: Debug
    -- Found Git: C:/Program Files/Git/bin/git.exe (found version "2.27.0.windows.1")
    CMake Deprecation Warning at ETL/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    -- Found Boost: C:/src/vcpkg/installed/x86-windows/include (found version "1.73.0") found components: system
    -- Found ZLIB: optimized;C:/src/vcpkg/installed/x86-windows/lib/zlib.lib;debug;C:/src/vcpkg/installed/x86-windows/debug/lib/zlibd.lib (found version "1.2.11")
    -- Found PkgConfig: C:/pkgconfig/pkg-config.exe (found version "0.26")
    -- Checking for module 'sigc++-2.0'
    --   No package 'sigc++-2.0' found
    CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.19/Modules/FindPkgConfig.cmake:553 (message):
      A required package was not found
    Call Stack (most recent call first):
      C:/Program Files (x86)/CMake/share/cmake-3.19/Modules/FindPkgConfig.cmake:741 (_pkg_check_modules_internal)
      synfig-core/src/CMakeLists.txt:27 (pkg_check_modules)
    
    
    -- Configuring incomplete, errors occurred!
    See also "D:/gtkmm/vs/CMakeFiles/CMakeOutput.log".
    See also "D:/gtkmm/vs/CMakeFiles/CMakeError.log".
```
My vcpkg is placed in c:\src\vcpkg
CMkake is installed in C:/Program Files (x86)/CMake/
and downloaded pkg-config files in C:\pkgconfig according to [here](https://stackoverflow.com/a/1711338/5674536)
I think the pkg-config don't know the place the sigc++ installed with vcpkg, because when I check the libsigcpp with command:
`vcpkg install libsigcpp`
it tells:
```
Computing installation plan...
    The following packages are already installed:
        libsigcpp[core]:x86-windows
    Package libsigcpp:x86-windows is already installed
```
Can anyone help, thank you in advance.

**Comment by ice0** [comment]
Hi! Unfortunately Visual Studio support is still in development. For Windows development you can use MSYS2 environment.
https://synfig-docs-dev.readthedocs.io/en/latest/building/Preparing%20Environment.html#windows

**Comment by ice0** [comment]
Also, since I am currently targeting VS 2019 and higher, is there a reason not to upgrade to VS 2019?

**Comment by mhao1999** [comment]
@ice0 thank you for your comment. I installed vs2019 yesterday, but error is still there, I search in vcpkg dir and could not find sigc++-2.0. Is there a step-by-step guide to setup vs2019+cmake+vcpkg+pkg-config, thanks!

**Comment by ice0** [comment]
@mhao1999 Visual Studio support is still under development, so it is not currently supported.

Only MSYS2 is available for Windows.
https://synfig-docs-dev.readthedocs.io/en/latest/building/Preparing%20Environment.html#windows

**Comment by mhao1999** [comment]
thank you, I will follow the post to build it on windows, by the way, what is a good IDE if not VS to review source code, debug, set breakpoint IDE on windows platform? Qt creator?

**Comment by ice0** [comment]
Yes, Qt creator. Also you can try CLion (https://www.jetbrains.com/clion/) as a temporary solution (they have 30-days trial)

**Comment by mhao1999** [comment]
Hi ice0, how to setup qt creator, should I download and install qt creator from msys2 shell, or just download it from qt official website? is there document for setup qt creator in detail, thanks.

**Comment by ice0** [comment]
Yes, there is an instruction for Qt Creator: https://synfig-docs-dev.readthedocs.io/en/latest/ide/QtCreator.html

**Comment by mhao1999** [comment]
I install msys2 on windows, then open synfig with qt creator but an error with "No package 'mlt++' found":
Running C:\Program Files (x86)\CMake\bin\cmake.exe -S C:/msys64/home/EDZ/synfig.git -B C:/Users/EDZ/AppData/Local/Temp/QtCreator-uxiQOL/qtc-cmake-IbQKlQDM -GNinja "-DCMAKE_BUILD_TYPE:String=Debug" "-DQT_QMAKE_EXECUTABLE:STRING=C:/Qt/5.15.2/mingw81_64/bin/qmake.exe" "-DCMAKE_PREFIX_PATH:STRING=C:/Qt/5.15.2/mingw81_64" "-DCMAKE_C_COMPILER:STRING=C:/Qt/Tools/mingw810_64/bin/gcc.exe" "-DCMAKE_CXX_COMPILER:STRING=C:/Qt/Tools/mingw810_64/bin/g++.exe" "-DMSYS=1" in C:\Users\EDZ\AppData\Local\Temp\QtCreator-uxiQOL\qtc-cmake-IbQKlQDM.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Qt/Tools/mingw810_64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw810_64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: Debug
-- Found Git: C:/Program Files/Git/bin/git.exe (found version "2.27.0.windows.1") 
CMake Deprecation Warning at ETL/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Boost: C:/msys64/mingw32/include (found version "1.73.0") found components: system 
-- Found ZLIB: C:/msys64/mingw64/lib/libz.dll.a (found version "1.2.11") 
-- Found PkgConfig: C:/msys64/mingw32/bin/pkg-config.exe (found version "0.29.2") 
-- Checking for module 'sigc++-2.0'
--   Found sigc++-2.0, version 2.10.3
-- Checking for module 'glibmm-2.4'
--   Found glibmm-2.4, version 2.64.2
-- Checking for module 'giomm-2.4'
--   Found giomm-2.4, version 2.64.2
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.46.1
-- Checking for module 'libxml++-2.6'
--   Found libxml++-2.6, version 2.40.1
-- Checking for module 'mlt++'
--   No package 'mlt++' found
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.19/Modules/FindPkgConfig.cmake:553 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.19/Modules/FindPkgConfig.cmake:741 (_pkg_check_modules_internal)
  synfig-core/src/CMakeLists.txt:33 (pkg_check_modules)

**Comment by ice0** [comment]
Please try to install mlt using `MSYS2 MinGW 64-bit` console:
`pacman -S mingw-w64-x86_64-mlt`

**Comment by mhao1999** [comment]
it works! thank you, @ice0.

**Comment by mhao1999** [comment]
Thank you, now configuring the project works, but the build process failed with five errors like below (partial messages, and I use MSYS2 MinGW 32-bit):
core\src\synfig\CMakeFiles\synfig.dir\base_types.cpp.obj.d -o synfig-core/src/synfig/CMakeFiles/synfig.dir/base_types.cpp.obj -c C:/msys64/home/EDZ/synfig.git/synfig-core/src/synfig/base_types.cpp
C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: synfig-core/src/synfig/CMakeFiles/synfig.dir/base_types.cpp.obj: too many sections (42336)
C:\Users\EDZ\AppData\Local\Temp\ccyL6WS0.s: Assembler messages:
C:\Users\EDZ\AppData\Local\Temp\ccyL6WS0.s: Fatal error: can't write 3922 bytes to section .text of synfig-core/src/synfig/CMakeFiles/synfig.dir/base_types.cpp.obj: 'File too big'
C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: synfig-core/src/synfig/CMakeFiles/synfig.dir/base_types.cpp.obj: too many sections (42336)
C:\Users\EDZ\AppData\Local\Temp\ccyL6WS0.s: Fatal error: can't close synfig-core/src/synfig/CMakeFiles/synfig.dir/base_types.cpp.obj: File too big
[29/577 0.3/sec] Building CXX object synfig-core/src/modules/lyr_std/CMakeFiles/lyr_std.dir/zoom.cpp.obj
[30/577 0.3/sec] Building CXX object synfig-core/src/modules/mod_gif/CMakeFiles/mod_gif.dir/main.cpp.obj
[31/577 0.3/sec] Building CXX object synfig-core/src/modules/mod_ffmpeg/CMakeFiles/mod_ffmpeg.dir/main.cpp.obj
[32/577 0.3/sec] Building CXX object synfig-core/src/modules/mod_filter/CMakeFiles/mod_filter.dir/halftone.cpp.obj
[33/577 0.3/sec] Building CXX object synfig-core/src/modules/mod_filter/CMakeFiles/mod_filter.dir/lumakey.cpp.obj
[34/577 0.3/sec] Building CXX object synfig-core/src/modules/mod_filter/CMakeFiles/mod_filter.dir/blur.cpp.obj
[35/577 0.4/sec] Building CXX object synfig-core/src/modules/mod_filter/CMakeFiles/mod_filter.dir/main.cpp.obj
[36/577 0.4/sec] Building CXX object synfig-core/src/modules/mod_filter/CMakeFiles/mod_filter.dir/halftone3.cpp.obj
[37/577 0.4/sec] Building CXX object synfig-core/src/modules/mod_filter/CMakeFiles/mod_filter.dir/halftone2.cpp.obj
ninja: build stopped: subcommand failed.
21:55:38: process"C:\Program Files (x86)\CMake\bin\cmake.exe" exit，exit code is 1 。
Error while building/deploying project synfig-studio (kit: Desktop Qt 5.15.2 MinGW 64-bit)
When executing step "CMake Build"
21:55:38: Elapsed time: 01:40.

**Comment by ice0** [comment]
>  I use MSYS2 MinGW 32-bit
In this case you need to use i686 packages. For example `mingw-w64-i686-mlt`.

To fix build errors - first better to build synfig manually using `MSYS2 MinGW 32-bit` console.
For example:
```
# creating work directory
mkdir synfig-w32 && cd synfig-w32

# cloning repo
git clone https://github.com/synfig/synfig

# installing dependencies
./synfig/1-setup-windows-msys2.sh

# building
mkdir build && cd build
cmake ../synfig/ -G"MSYS Makefiles"
make -j4
```

Output:
```
...
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/renderer_canvas.cpp.obj
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/renderer_dragbox.cpp.obj
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/renderer_ducks.cpp.obj
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/renderer_grid.cpp.obj
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/renderer_guides.cpp.obj
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/renderer_timecode.cpp.obj
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/renderer_bonesetup.cpp.obj
[ 99%] Building CXX object synfig-studio/src/gui/CMakeFiles/synfigstudio.dir/workarearenderer/workarearenderer.cpp.obj
[100%] Linking CXX executable ../../../output/bin/synfigstudio.exe
[100%] Built target synfigstudio

```

**Comment by ice0** [comment]
Ans as I can see you use different MinGW installation (C:/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe)
It's better to use the mingw tools from MSYS - they are located in `c:\msys64\mingw32\bin`

**Comment by ice0** [comment]
Current state with Visual Studio build:

**VS + vcpkg**
- Not working, code changes required (compiler incompatibility)

**VS + vcpkg + clang tools**
- Not working - libsigc++ not building (it has some compiler specific parts, vcpkg configures it for the MSVC compiler). There are no official vcpkg triplets for Clang tools.

**VS + MSYS2 + clang tools**
Requirements
- Should be run from MSYS2 console (without this it cannot find pkg-config. If add pkg-config path to PATH variable, it cannot find cmake, cmake is still in PATH)
- CMake from Clang toolset cannot find libraries using `find_library` command (they have looking for VS specific prefixes like `v142`) so need to add explicit paths to Boost.System and zlib libraries.

Configure command
- `cmake -G"Visual Studio 16 2019" -T"ClangCL" ../synfig -DZLIB_LIBRARY=/mingw64/bin/zlib1.dll -DBoost_SYSTEM_LIBRARY=/mingw64/bin/libboost_system-mt.dll`

Additional information
- Toolset name can be found by path: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Platforms\x64\PlatformToolsets"

Result
- Not working - libsigc++ not building. Same problem here (it has some compiler specific parts). 


**VS + WSL + gcc**

Requirements
- Need to install WSL

Result
- Builds and synfig working. synfigstudio fails with error "cannot open display", but this is because xserver needs to be installed.

**VS + MinGW + MSYS2**

Requirements
- Need to fix configuration manually. Some variables, like `TOOLSET_VERSION` set incorrectly.

Result
- Builds and working, but gdb pretty-print not working (string values not visible)

CMakeSettings.json
```
{
  "configurations": [
    {
      "name": "x64-Debug (default)",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "variables": []
    },
    {
      "name": "Mingw64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "mingw_64" ],
      "environments": [
        {
          "MINGW_PREFIX": "C:/msys64/mingw64",
          "MINGW64_ROOT": "C:/msys64/mingw64",
          "BIN_ROOT": "${env.MINGW64_ROOT}/bin",
          "FLAVOR": "x86_64-w64-mingw32",
          "TOOLSET_VERSION": "10.2.0",
          //"PATH": "${env.MINGW64_ROOT}/bin;${env.MINGW64_ROOT}/../usr/local/bin;${env.MINGW64_ROOT}/../usr/bin;${env.MINGW64_ROOT}/../bin;${env.PATH}",
          "PATH": "${env.MINGW64_ROOT}/bin;${env.PATH}",
          "PKG_CONFIG_PATH": "${env.MINGW64_ROOT}/lib/pkgconfig/",
          "INCLUDE": "${env.MINGW64_ROOT}/include/c++/${env.TOOLSET_VERSION};${env.MINGW64_ROOT}/include/c++/${env.TOOLSET_VERSION}/tr1;${env.MINGW64_ROOT}/include/c++/${env.TOOLSET_VERSION}/${env.FLAVOR}",
          "environment": "mingw_64"
        }
      ],
      "variables": [
        {
          "name": "CMAKE_C_COMPILER",
          "value": "${env.BIN_ROOT}/gcc.exe",
          "type": "STRING"
        },
        {
          "name": "CMAKE_CXX_COMPILER",
          "value": "${env.BIN_ROOT}/g++.exe",
          "type": "STRING"
        }
      ],
      "intelliSenseMode": "linux-gcc-x64"
    }
  ]
}
```

launch.vs.json
```
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "default",
      "project": "CMakeLists.txt",
      "projectTarget": "synfigstudio.exe (output\\bin\\synfigstudio.exe)",
      "name": "synfigstudio.exe (output\\bin\\synfigstudio.exe)"
    },
    {
      "type": "cppdbg",
      "name": "CMakeLists.txt",
      "project": "CMakeLists.txt",
      "projectTarget": "",
      "cwd": "C:\\projects\\synfig-wsl\\synfig\\out\\build\\Mingw64-Debug\\output\\bin",
      "program": "synfigstudio.exe",
      //"processId": 0,
      "MIMode": "gdb",
      "miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
      "externalConsole": false,
      "args": [
        "-enable-pretty-printing"
      ],
      "debugType": "managed"
    }
  ]
}
```

**Comment by mhao1999** [comment]
works! thanks!

**Comment by mhao1999** [comment]
Thanks! Now I installed Mingw32 bit qt creator and use c:\msys64\mingw32 toolchain, building is ok. and I can run synfig-studio.exe.
But when I try to debug (press "start debugging of startup project"), a window pops up says(breakpoint cannot be hit):
The selected debugger may be inappropriate for the inferior.
Examining symbols and setting breakpoints by file name and line number may fail.
The inferior is in the Portable Executable format.
Selecting GDB as debugger would improve the 
debugging experience for this binary format.
Note: Tools->Options->Kits->Debugger: GNU gdb 8.1 for MinGW 8.1.0 32-bit is the default, cannot be changed.

**Comment by mhao1999** [comment]
I follow your suggestion as "build synfig manually using MSYS2 MinGW 32-bit console". then open project with qt creator, building is ok. But cannot debug the project with break points.

**Comment by mhao1999** [comment]
Hi ice0, sovled, I cloned a kit and change its debugger, now everything is ok, thank you for your all kind help!

**Comment by ice0** [comment]
Awesome!
