### ISSUE TITLE
in the "view" menu "Toolbar" option isn't active

### ISSUE THREAD

**Issue by Blu12345** [synfig/synfig#1881]
version 1.4.0 on OSX in the "view" menu "Toolbar" option isn't active

view->toolbar cannot be enabled

this[ issue](https://github.com/synfig/synfig/issues/733#issue-416215598) was apparently solved however it's still happening 

maybe it was only solved for windows?

<img width="605" alt="Screen Shot 2020-12-01 at 10 52 58 PM" src="https://user-images.githubusercontent.com/60356184/100801227-fc86e580-3427-11eb-824a-3438a3d85599.png">

**Comment by ice0** [comment]
This was fixed in master branch, and was not backported to 1.4.0 
Added backport label for 1.4.1 (https://github.com/synfig/synfig/pull/1386)

**Comment by rodolforg** [comment]
This issue is fixed in v1.4.1.
