### ISSUE TITLE
1.4.0 Cant render saved files: No such file or directory

### ISSUE THREAD

**Issue by OrangNeedl4** [synfig/synfig#1885]
![Screenshot](https://user-images.githubusercontent.com/75488669/101176802-c1520580-3625-11eb-88a1-61e3100de8fa.jpg)

![Error](https://user-images.githubusercontent.com/75488669/101178676-0d9e4500-3628-11eb-8bad-26dff0c9e2dc.png)

On the new stable version of Synfig, every time i try to render a secuence of a saved file (doesnt matter if its from an older version or new) it just appears an error that says **"unable to create file C:/User/Pictures/*name of the file*: No such file directory"** this also happens with an image sequence, i tried to reinstall synfig but it happens exactly the same, My system uses Windows 10

**Comment by BobSynfig** [comment]
Try to render it in a folder without a "non-latin" character in the path.
The tilde is surely the (well-known) problem.

**Comment by OrangNeedl4** [comment]
Wow, thanks Bob, it looks that i just had to take off the ñ of my file, (also, in the older version this doesnt happen)thank u again

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.
