### ISSUE TITLE
Edit image in external tool NOT WORKING windows 10

### ISSUE THREAD

**Issue by Khemardi** [synfig/synfig#1909]
**Synfig version & platform**:
Using Synfig Studio 1.4 on Windows 10 Home
Processor: Intel(R) Core(TM) i7-8700K
CPU: 3.700GHz
RAM: 16 GB
Graphics Card: GeForce GTX 1080 Ti

**Issue description**:
Nothing happens when I right click an image layer and select "Edit image in external tool". I have it set up to edit in Krita, but it doesn't work. I even tried changing it to open in Photoshop and other image manipulation software and still nothing.

**Comment by ice0** [comment]
Confirmed. I will take a look.

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.
