### ISSUE TITLE
Stretched "Scale to fit canvas" switch icon on import image dialog

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1910]
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
<strike>I think `vexpand` property is turned on for this toggle widget. If so, it should be off.
Stretching it makes it look ugly.</strike>

Checked the source code in app.cpp. It's not `vexpand` property as I suspected.

- Source code
https://github.com/synfig/synfig/blob/4aac1b85c241b3b5b000e7cd82a5139864efbcc2/synfig-studio/src/gui/app.cpp#L4455-L4474

![20201209_19h37m46s_grim](https://user-images.githubusercontent.com/24214509/101641452-c2d16280-3a57-11eb-9b12-c8db546fe937.png)

**Comment by Keyikedalube** [comment]
Either that switch widget is stretched or... squeezed.

**Comment by rodolforg** [comment]
It can be. You can check it at runtime by using gtkinspector. If you have it installed, called from any gtk program by pressing ctrl+shift+d or ctrl+shift+i . In synfig, only last shortcut works because former is already mapped.

**Comment by rodolforg** [comment]
It's its valign value :)

**Comment by Keyikedalube** [comment]
Thanks, @rodolforg I forgot to get back to this issue.

Anyway, I'm not solving this issue. So, if you aren't too... then I think this issue is deserving of "good first issue" + "easy" tag :P for GTK newbies
