### ISSUE TITLE
[Synfig Studio] Right-clicking on Groups in Sets causes crash

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1917]
**Synfig version & platform**:
master e84f6cb
Windows

**Issue description**:
1) Open the [attached file](https://github.com/synfig/synfig/files/5682789/2020_11_27_V6.zip) and close the `Warning` dialog (did not attach linked fonts and stuff but result is unchanged)
2) Go to `Sets` Windows
Here you can a `Set `called `Testo` which contains some `Text Layers` and `Groups`

3) Right-click on one of the `Groups`

Synfig Studio crashes.

**Comment by rodolforg** [comment]
Reproducible on Linux too.
