### ISSUE TITLE
[Synfig Studio] Duplicating Layers where Duplicate is used, creates a new index but doesn't update Connected value

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1921]
**Synfig version & platform**:
master e84f6cb

**Issue description**:

1) Create a new animation
2) Add a Layer on `Canvas`, for example a `Star` (no need for outlines etc.)
3) Add a `Duplicate` Layer
Now in the `Library` window a new value called `duplicate` is added.

4) `Group` the `Star` and the `Duplicate` Layers
5) Select the `Star` and in the `Parameters` window right-clic on `Origin` and `Convert > Composite`
Now `Origin` has two sub-parameters: `X-Axis` and `Y-Axis`

6) Select `X-Axis` and connect to the `duplicate` value in the `Library` window
Now on Canvas there's a `Star` duplicated three times horizontally.

7) Duplicate the `Group` created in step 4
In the `Library` window a new value called `Index 1` is added. This value should be the parameter used by the duplicated `Duplicate` Layer.

If you drag the duplicated `Group` you can see it contains only one star. That's because it's still connected to the old `duplicate` value.
From a logical point of view it makes sense, but from a user perspective I expect to duplicate everything and get a whole copy of the duplicated Layer.

8) Connect the `Star` to `Index 1`
The duplicated group now has three stars

I think Step 8 should be the expected behavior of Synfig at Step 7, what do you think?

**Comment by rodolforg** [comment]
This issue is fixed in v1.4.1.
