### ISSUE TITLE
where those png files come from?

### ISSUE THREAD

**Issue by mhao1999** [synfig/synfig#1930]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:

I git cloned the source code of synfig to local directory, and search *.png in the directory, cannot find those toolbutton png files.
However, when I build the cmakefiles.txt, in the output directory "c:\...\build\output\share\synfig\icons\classic" found many png files.

Please kindly tell where those png files come from? thanks!

**Comment by ice0** [comment]
They are generated by `synfig` console tool from the `.sif` files located in the `synfig-studio/images` folder.

**Comment by mhao1999** [comment]
Thank you @ice0, I saw the cmake command install(....) to add those image file to binary finally. One more question, how to build a exe file on windows 10, it should be a "make install" command or something like? could you give me a practical instruction, I had a little "make" related knowlege and was keen to get a executable installer, thanks!

**Comment by ice0** [comment]
> it should be a "make install" command or something like?

Just `make` or `make synfigstudio`. Built binaries located inside `<build_folder>/output/bin` folder.
`make install` command use mostly when preparing portable installation. It copies required system libraries and files to one place. This will not required during development.

**Comment by BobSynfig** [comment]
I think this should be discussed in the Development section of the forums instead of opening an issue (which is not!)
https://forums.synfig.org/c/development/
The more "issues" we open, the less potential contributors will be prone to check if the same issue has been already reported (and then will create another duplicate!)

**Comment by mhao1999** [comment]
thank you @ice0 , I meant to portable installation (installer on windows) , any command to generate the installer? I saw the CPackConfig.cmake which was said to invoke nsis to generate installer, but don't know detailed steps. @BobSynfig I know this is not a issue, will check the forum later, thanks!
