### ISSUE TITLE
Font does not change in the Textbox

### ISSUE THREAD

**Issue by MrTeeXD** [synfig/synfig#1934]
**Synfig version & platform**:
1.4.0
Windows 10 64bit 20H2

**Issue description**:
When adding a Textbox and changing the font type in the Parameters, the text does not change the font family. Even after installing the prefered font, it will not change the font family.

**Comment by rodolforg** [comment]
Try to use the font filename.
Font family support isn't publicly available yet.

**Comment by MrTeeXD** [comment]
Alright, will try next time
