### ISSUE TITLE
[Synfig Studio] Preview Window is always above Preview Options

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1946]
**Synfig version & platform**:
master e320613

**Issue description**:
1) Create a new animation
2) Go to: `File > Preview` and launch a Preview
3) Click on the button with the small pencil to reopen Preview Options

![preview-options](https://user-images.githubusercontent.com/6705690/102937217-f1b0f500-44a9-11eb-89d8-03452fb0ab67.png)

Preview Window is always on top of Preview Options.

**Comment by FirasH** [comment]
https://github.com/synfig/synfig/blob/e3206139323757abdc878acc9cd5651ae0e24ce1/synfig-studio/src/gui/dialogs/dialog_preview.cpp#L69-L82

Is it enough to remove `set_keep_above()` or there's a reason for that?

**Comment by ice0** [comment]
ping @morevnaproject
