### ISSUE TITLE
[Synfig Studio] Reorganize buttons around canvas area

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1951]
**Synfig version & platform**:
master

**Issue description**:
Successor to discussion started in #1451.

The key idea is to reduce used screen estate by reorganizing the buttons/tools most used.
There are some mockups in the linked issue.

Here you can see an actually working test I made right now by splitting the top bar in two.
On top there are file/export/preview options, while on the right drawing options like ducks and guides/grid (all in a single row are too wide).

![canvas-buttons-reorder](https://user-images.githubusercontent.com/6705690/103151451-7dfb3a80-477e-11eb-9f21-8ce15d92d70c.png)

Another step step could be to move tools out of the toolbox to the left side of canvas (Inkscape style interface) and move somewhere the color editor in the toolbox.

Let me know what you think!

**Comment by morevnaproject** [comment]
I like this!
