### ISSUE TITLE
[Synfig Studio] Waypoint Editor "Value" could set not feasible Parameter values

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1965]
**Synfig version & platform**:
master 4b7f89b

**Issue description**:
1. Create a new animation
2. Draw a `Star` on Canvas (works with any Layer)
3. Enable Animate mode and create a waypoint for `Blend Method` parameter
4. Double-click on the waypoint created in step 3 to open `Waypoint Editor` dialog
![waypoint-editor-value](https://user-images.githubusercontent.com/6705690/103482777-19298b00-4de3-11eb-9ec7-abaeffa5e407.png)
`Value` is represented as a spin box, not as a dropdown.

5. Scroll on `Value` spin box to change its value e.g. -20
![waypoint-editor-out-of-bounds](https://user-images.githubusercontent.com/6705690/103482973-4c204e80-4de4-11eb-9383-debd0629612e.png)
The spin box hasn't a min/max value and the value is set.

This happens for all values set with dropdowns in `Parameters` panels.

**Comment by rodolforg** [comment]
This issue is fixed in v1.4.1.
