### ISSUE TITLE
Use "Constant" interpolation by default for all "enum" parameters

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1972]
Problem description:

> Noticed that with enums type of variables when some kind of interpolation is set, those will get through all variables (this happened even before)
For example if you interpolate from `Blend Method` `Composite` to `Alpha` Synfig will get through each one of them like from 0 to 20.

> If interpolation is set to Constant it's fine, but I don't know if this is a plus or an issue...

_Originally posted by @FirasH in https://github.com/synfig/synfig/issues/1968#issuecomment-753650346_

**Comment by ice0** [comment]
ping @morevnaproject

**Comment by morevnaproject** [comment]
I agree, it would be nice to set default interpolation for Blend Method parameter.
I think it should be a "default interpolation" flag set for new created layers, as follows - https://youtu.be/Bxn0eRY1Kv0

**Comment by FirasH** [comment]
Didn't know about that feature...
I'll check how to apply that by default.

**Comment by morevnaproject** [comment]
Some parameters have "Static" flag applied by default. I think the interpolation flag can be applied in similar way.
![screenshot_001](https://user-images.githubusercontent.com/332868/104095802-7170f900-52cb-11eb-86d2-50318effbbaa.png)

**Comment by morevnaproject** [comment]
BTW, I have noticed that "Blend Method" parameter is set to "Static" for Group Layer. O_O
Maybe this is what we want for other layers?
![screenshot_002](https://user-images.githubusercontent.com/332868/104095828-92d1e500-52cb-11eb-9709-8e665ca3c717.png)

**Comment by FirasH** [comment]
Yes, you're right. I'm also for setting it as `Static`.
Then if some animation is required the user will deal with interpolations.

**Comment by FirasH** [comment]
Enum parameters not set to `Static`:
* Blurs > Motion Blur > Subsampling Type
* Blurs > Blur > Type
* Distortions > Noise Distort > Interpolation
* Distortions > Spherize > Distort Type
* Filters > Halftone 2 > Type
* Filters > Halftone 3 > Type
* Geometry > Advanced Outline > Type of Feather
* Geometry > Advanced Outline > Winding Style
* Geometry > Advanced Outline > Tip Type at Start
* Geometry > Advanced Outline > Tip Type at End
* Geometry > Advanced Outline > Width Point List > Side Type Before
* Geometry > Advanced Outline > Width Point List > Side Type After
* Geometry > Advanced Outline > Cusps Type
* Geometry > Advanced Outline > Dash Item List > Side Type Before
* Geometry > Advanced Outline > Dash Item List > Side Type After
* Geometry > Outline > Type of Feather
* Geometry > Outline > Winding Style
* Geometry > Polygon > Type of Feather
* Geometry > Polygon > Winding Style
* Geometry > Region > Type of Feather
* Geometry > Region > Winding Style
* Geometry > Star > Type of Feather
* Geometry > Star > Winding Style
* Gradients > Noise Gradient > Interpolation
* Other > Text > Style
* Other > Text > Weight
* Stylize > Bevel > Type
* Stylize > Shade > Type

**Comment by FirasH** [comment]
When Layers are created using Tools Static parameters are set differently.
