### ISSUE TITLE
1.4.0: [synfig-studio] non-free/minified "plugins/lottie-exporter/bodymovin.js" (Open Source compliance)

### ISSUE THREAD

**Issue by onlyjob** [synfig/synfig#1978]
https://github.com/synfig/synfig/blob/master/synfig-studio/plugins/lottie-exporter/bodymovin.js is a source-less pre-minified file - therefore it is non-compliant with Open Source and DFSG. Please always provide complete sources.

Effectively minified code is equivalent of pre-compiled binary -- un-readable, non-modifiable and non-distributable in [Debian](https://debian.org).  
It is a bad practice to commit binaries to VCS. Minification can be easily done on build-time.

Read more in https://wiki.debian.org/onlyjob/no-minification

Thanks.

**Comment by ice0** [comment]
@onlyjob Hi! Thanks for pointing to this.
ping @saurabh-ramola @AnishGG

**Comment by rodolforg** [comment]
I just found out it came from: https://github.com/airbnb/lottie-web/blob/master/build/player/lottie_html.js
There's a lottie_html.min.js there too.

**Comment by rodolforg** [comment]
I had to change the https://github.com/synfig/synfig/blob/master/synfig-studio/plugins/lottie-exporter/lottie-exporter.py
here:
https://github.com/synfig/synfig/blob/81b13a488b9d958d53a2bd910a47ac896d0071eb/synfig-studio/plugins/lottie-exporter/lottie-exporter.py#L100
To be surrounded by `<script>` and `</script>` tags.

**Comment by rodolforg** [comment]
And here
https://github.com/synfig/synfig/blob/81b13a488b9d958d53a2bd910a47ac896d0071eb/synfig-studio/plugins/lottie-exporter/lottie-exporter.py#L69
to point to right file.

HOWEVER, I don't know what is the difference to the above line:
https://github.com/synfig/synfig/blob/81b13a488b9d958d53a2bd910a47ac896d0071eb/synfig-studio/plugins/lottie-exporter/lottie-exporter.py#L67

**Comment by ice0** [comment]
> To be surrounded by <script> and </script> tags.

I think we need to include original files, and do minification job at build-time as suggested. In this case, no plugin changes are required.

**Comment by rodolforg** [comment]
The bodymovin.js has in its contents the <script> tags. :/

**Comment by rodolforg** [comment]
ping @AnishGG :D

**Comment by AnishGG** [comment]
What kind of minification tool can we use? There is one called [`jsmin`](https://pypi.org/project/jsmin/). I tested it and it minified the [original](https://github.com/airbnb/lottie-web/blob/5fb1fb1436206ecbbe113581f642ca08c440b78b/build/player/lottie.js) `js` file from  14176 lines to 1398 lines. But the original [minified](https://github.com/airbnb/lottie-web/blob/5fb1fb1436206ecbbe113581f642ca08c440b78b/build/player/lottie.min.js) version has only 8 lines. 
So will this be fine? or should we use some other minification tool?



> The bodymovin.js has in its contents the <script> tags. :/

I couldn't find any <script> tags here.

**Comment by onlyjob** [comment]
If I _had_ to minify I'd try Debian's `uglifyjs` package and maybe `minify` package. But we don't even have to minify - it is not like we are saving a lot of CDN traffic. Why bother? Merely to save 10 KiB or so? For single user where software will use cached version after first load? To save a millisecond of I/O once per application start? Is it worth the effort by any means?

**Comment by AnishGG** [comment]
So, If I understand this right, we just need to use the non-minified version of the bodymovin script?

**Comment by onlyjob** [comment]
I think it's the best. Since you have to ship original/unminified version anyway, for Open Source compliance and best practice, why not just use this very version?
There are times and places where minification might be more useful but frankly I think we have a weak case here.
Thanks!

**Comment by rodolforg** [comment]
> I tested it and it minified the [original](https://github.com/airbnb/lottie-web/blob/5fb1fb1436206ecbbe113581f642ca08c440b78b/build/player/lottie.js) `js` file from 14176 lines to 1398 lines. But the original [minified](https://github.com/airbnb/lottie-web/blob/5fb1fb1436206ecbbe113581f642ca08c440b78b/build/player/lottie.min.js) version has only 8 lines.

Only for clarification, more important than the line number is the number of bytes. :)
Anyway, issue solved :D

**Comment by rodolforg** [comment]
Hey @onlyjob -– sorry for contact you here… but did you see this error? https://tracker.debian.org/pkg/synfig
```
 Problems while searching for a new upstream version high
uscan had problems while searching for a new upstream version:

In debian/watch no matching files for watch line
  https://github.com/synfig/synfig/releases .*/archive/v?(\d[\d\.]+)\.tar\.gz
```

**Comment by onlyjob** [comment]
You can always just email to me, @rodolforg... I think some time ago GitHub changed download URLs and that wrecked new release monitoring/checking in many packages. We will have to update "debian/watch" file unless _uscan_ introduce a generic workaround for GitHub...

**Comment by rodolforg** [comment]
I did send you an email on April 16 (about other question related to Synfig + Debian), but as you never answered me, I thought you don't use that @debian.org email address.  ;)


> We will have to update "debian/watch" file unless _uscan_ introduce a generic workaround for GitHub...

👍
