### ISSUE TITLE
Application is closing when it is selected "Link to Spline".

### ISSUE THREAD

**Issue by sprino** [synfig/synfig#1987]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

Version on Ubuntu 18.04:
SynfigStudio-1.4.0-stable-2020.11.14-linux64-b9862.appimage
SynfigStudio-1.2.1-stable

**Issue description**:
When i clik "Link to spline" the application is colosing. 

`(synfigstudio:8611): Gtk-WARNING **: Allocating size to gtkmm__GtkNotebook 0x218b180 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
./bin//launch.sh: riga 66:  8611 Errore di segmentazione (core dump creato) "$BASE_DIR/bin/synfigstudio.wrapper" "$@ `

**Comment by rodolforg** [comment]
I just tested on 1.4.0 appimage version and it worked.
Could you please detail the step you did so I can reproduce it?

**Comment by sprino** [comment]
Ok,
on windows 7 (virtualized in virtual box) it does the same problem.


https://user-images.githubusercontent.com/32312522/104782290-42073400-5784-11eb-959c-53c08b7721a8.mp4

![Schermata del 2021-01-15 22-47-28](https://user-images.githubusercontent.com/32312522/104782311-49c6d880-5784-11eb-932e-85a7a960324b.png)

**Comment by rodolforg** [comment]
Strange. I try to reproduce it but I couldn't.

https://youtu.be/zx_46AiQzFE

**Comment by rodolforg** [comment]
Ok. I saw a minor difference: you select one of the spline vertices too before link to spline.
Try without selecting it: you don't need to select any spline vertex.

**Comment by sprino** [comment]
I confirm, if I do not select the vertex of the line the problem does not occur.
Anyway, do we leave the issiu open or should it be closed?
I would leave it open with the title change and description to specify the particular case.

**Comment by rodolforg** [comment]
Let it open.
The problem exists, and on current stable release :)
