### ISSUE TITLE
Rotating Tool Does Not Work

### ISSUE THREAD

**Issue by MrTeeXD** [synfig/synfig#1989]
**Synfig version & platform**:
Version 1.4.0

**Issue description**:
When I select the rotating tool, I dont get a rotating handle for a drawn square and thus I cannot rotate the square at will

Screenshot:
![synfigstudio_EauHRRFT4g](https://user-images.githubusercontent.com/37266538/104823785-60893000-5855-11eb-9f2b-3deb48116b62.png)

**Comment by rodolforg** [comment]
You created a Rectangle as a "shape" layer: it's defined only by those two vertices and can't be rotated by itself.
- You can use a [Rotate](https://synfig.readthedocs.io/en/latest/layers/rotate.html) layer over it to rotate anything below it; or
- You can create a [rectangle region](https://wiki.synfig.org/Tool_Options_Panel#Rectangle_Tool) instead; or
- [Group](https://synfig.readthedocs.io/en/latest/layers/group.html) your rectangle layer and rotate it by using the group [handles](https://wiki.synfig.org/Handle).

**Comment by MrTeeXD** [comment]
I found by grouping the Shape Layer, I can easily Rotate it. Closing this.
