### ISSUE TITLE
Merge tangents for all vertices of object

### ISSUE THREAD

**Issue by bbrizzy89** [synfig/synfig#2010]
**Synfig version & platform**: 1.4.0
MacOS10.15.7

**Issue description**: When importing from inkscape and other situations, an object may be made where all the vertices have unmerged tangents, and so to animate and preserve smooth appearing curves I currently have to go in and manually right click each vertex individually and merge tangents. Can a function be added to be able to right click somewhere (either on the object in the viewer window, or somewhere in the properties pane, etc) to "merge all tangents"? Would save a lot of time! Thank you!

**Comment by ice0** [comment]
Hi!
@bbrizzy89 can you attach some sample file? And maybe make a short video showing a problem?
Just for better understanding. This will help a lot.

**Comment by bbrizzy89** [comment]
Hey ice0 thanks so much - I'm attaching a file. Had to get it down to 480p and chop up a bit to make the file fit but I think it communicates the issue okay. Thanks so much for considering! 

https://user-images.githubusercontent.com/78452200/106848015-25a83a00-6654-11eb-8fc6-ebc007e1cf2e.mov
