### ISSUE TITLE
[Synfig Studio] Delete event doesn't reset CanvasProperties rend_desc values

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2014]
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
1. Open Canvas Properties dialog
2. Change width value
3. Close dialog using the close button from the title bar
4. Open Canvas Properties dialog again
5. Width value is not reset

**Comment by rChen10** [comment]
I'd like a go at this issue. Can someone assign it to me?
