### ISSUE TITLE
Isolate Time properties to its own dialog

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2025]
At this point the dialog `Canvas > Properties...` is going to be disassembled (right?) in smaller dialogs, something like:

* **Time...** dialog which contains Time tabs from `Canvas > Properties...` and `Canvas > Options...` not as a tab, but as a specific whole dialog

_Originally posted by @FirasH in https://github.com/synfig/synfig/issues/1895#issuecomment-750148155_

**Comment by Keyikedalube** [comment]
Interested contributors, please wait for the linked PR to be merged.

**Comment by morevnaproject** [comment]
I like the idea!

Also, I think we do not need "Duration" entry, as it duplicates "End Time" option -
![screenshot_001](https://user-images.githubusercontent.com/332868/118385000-51fd2a80-b635-11eb-9241-06eea84cef0c.png)

**Comment by ice0** [comment]
I am not sure about this. When I want to change some canvas options, better to do that from one place, rather than open and close different  windows.

**Comment by FirasH** [comment]
> Also, I think we do not need "Duration" entry, as it duplicates "End Time" option

Maybe replacing it with a non editable label which reports the resulting duration just as a quick way to auto-check total frames?


> I am not sure about this. When I want to change some canvas options, better to do that from one place, rather than open and close different windows.

I agree with this observation, maybe the number of Time settings (Frames Per Second, Start Time, End Time) is too small to have a single specific dialog… If there aren’t any other options to add to `Time`, those could be placed next to width, height and size stuff just as a “dimension” parameter?

**Comment by Keyikedalube** [comment]
> I am not sure about this. When I want to change some canvas options, better to do that from one place, rather than open and close different windows.

Makes sense 🤔

**Comment by ice0** [comment]
> Also, I think we do not need "Duration" entry, as it duplicates "End Time" option -

I think it would be more correct to make End Time as a label, because I always know the desired duration and do not want to calculate the End Time. 

For example, this is layout in After Effects:
![Screenshot_140](https://user-images.githubusercontent.com/5604544/118429124-25abe180-b6fb-11eb-8ad6-3878833d75a4.png)

**Comment by Keyikedalube** [comment]
I've been using end time because it's close to start time widget and also easily accessible with the press of the tab key.

Both widgets serve the purpose well. I'm OK with changing either one as label widget :)

**Comment by Keyikedalube** [comment]
> I am not sure about this. When I want to change some canvas options, better to do that from one place, rather than open and close different windows.
>
>> Makes sense 🤔 

On second thought, I've realized that in my experience I open Canvas properties mostly to edit:
- time duration (very frequent)
- or width/height (very rare because I mostly stick to the fixed resolution set in Preferences)
    _However it's necessary, explained in this issue #777 linked [blog post](http://www.segtsy.com/2013/12/a-significant-synfig-setback/)_

So it makes sense to isolate this dialog to simplify editing just the time properties. We already have width/height dialog implemented in this PR #1895

Also, maybe leave the other tabs in **Canvas Properties** & **Canvas Options** as they are based on how rare their usage is. In conclusion, I think isolating dialogs only for this issue and the above PR would suffice. The rest, we don't need to.

**Comment by ice0** [comment]
> I open Canvas properties mostly to edit time duration (very frequent)

No need to open Canvas properties. You can edit time duration in place:
![Screenshot_148](https://user-images.githubusercontent.com/5604544/118443213-d6bf7580-b715-11eb-997c-f25015d9c178.png)

**Comment by Keyikedalube** [comment]
> No need to open Canvas properties. You can edit time duration in place:

Doesn't work as expected for render settings. End time will be set for canvas but not the render settings. I remember setting both twice on my animation project some time ago.
This can be rectified in another issue.

https://user-images.githubusercontent.com/24214509/118469742-a1ba1f80-b723-11eb-9453-13019e84d746.mp4

We could instead add a start time widget in that toolbar and discard implementing time widgets dialog proposal.

**Comment by ice0** [comment]
@morevnaproject 
This is very strange. Looks like a bug in my opinion.

**Comment by FirasH** [comment]
I think the `Render Settings > Time` options remember the last inserted value because it’s not always necessary to render the whole animation.

As an example using png sequences it could be useful to render only changed frame intervals.

If you check Canvas Properties the Time of the animation should be changed, but is not related to Render Settings which are a different thing.

**Comment by Keyikedalube** [comment]
Both Canvas Properties and Render Settings invoke the same `Widget_RendDesc` class. Therefore I'm expecting the same behavior between these two dialogs.

I remember making a simple loop animation, finished it, and realized I only need to extend the end time a bit further. Changed it from the toolbar and then rendered my file assuming changes are already reflected in Render Settings. The annoying part I had to learn as a new habit was to rely only on Canvas Properties to make sure `Edit once > reflect all other dialogs too`

> because it’s not always necessary to render the whole animation.

Agree 👍🏽 

I'm curious then why if a user changes the time from Canvas Properties, Render Settings is affected too. It should only modify the widget from the toolbar since the latter does the same.

The code below explicitly refreshes Canvas Properties after `signal_end_time_changed` is triggered:
https://github.com/synfig/synfig/blob/41d6ac086e2bfc1ffed6bdd3d8bffd6e8326780c/synfig-studio/src/gui/canvasview.cpp#L1427-L1436

**Comment by morevnaproject** [comment]
My opinion:

- I agree that "Duration" is better than "End Time", as it is not requires to do calculations in mind
- The widget in workarea should be replaced to "Duration" - 
![Screenshot_148](https://user-images.githubusercontent.com/5604544/118443213-d6bf7580-b715-11eb-997c-f25015d9c178.png)
- I think we still need a separate dialog with "Start Time" and "Duration" widgets. I do not think it is good to add "Start Time" to workarea, because it is used quite rarely.


>>>> No need to open Canvas properties. You can edit time duration in place:
>>>> ![Screenshot_148](https://user-images.githubusercontent.com/5604544/118443213-d6bf7580-b715-11eb-997c-f25015d9c178.png)
>>>
>>> Doesn't work as expected for render settings. End time will be set for canvas but not the render settings. I remember setting both twice on my animation project some time ago.
>>> This can be rectified in another issue.
>>
>> This is very strange. Looks like a bug in my opinion.
>
> I think the Render Settings > Time options remember the last inserted value because it’s not always necessary to render the whole animation.
>
> As an example using png sequences it could be useful to render only changed frame intervals.

Yes, it looks like a bug, which is happens because Render Settings dialog "remembers" last value.
So this is more like UX design flaw.

I suggest that the Render Settings dialog should be changed:
- Add "Range" checkbox and two entry fields "Start frame" and "End frame" (I guess here it make sense to use End Frame, as it makes easier to identify rendering segment?)
- The  "Range" checkbox is disabled by default.
- When "Range" checkbox is disabled, then "Start frame" and "End frame" entry fields are inactive -> Synfig renders whole file, from start to end.

**Comment by Keyikedalube** [comment]
> I suggest that the Render Settings dialog should be changed:
> 
>     * Add "Range" checkbox and two entry fields "Start frame" and "End frame" (I guess here it make sense to use End Frame, as it makes easier to identify rendering segment?)
> 
>     * The  "Range" checkbox is disabled by default.
> 
>     * When "Range" checkbox is disabled, then "Start frame" and "End frame" entry fields are inactive -> Synfig renders whole file, from start to end.

This goes to #721

**Comment by Keyikedalube** [comment]
> > No need to open Canvas properties. You can edit time duration in place:
> 
> Doesn't work as expected for render settings. End time will be set for canvas but not the render settings. I remember setting both twice on my animation project some time ago.
> This can be rectified in another issue.

Figured this is actually a bug.
1. Change the end time from the toolbar
2. Save the document
3. Close Synfig Studio
4. Open Synfig Studio
5. Re-open the save file
6. Open Render dialog
7. End time is updated

Should close this issue? Because the above comments want to update the time widget only for Render settings dialog.

**Comment by ice0** [comment]
> Should close this issue? Because the above comments want to update the time widget only for Render settings dialog.

Done :)
