### ISSUE TITLE
[Feature request] Hotkey to toggle animate on/off

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2026]
**Issue description**:
The animate button doesn't have a hotkey to toggle it on and off. I believe implementing one would improve the workflow.

Original post 👉🏽  https://forums.synfig.org/t/anyone-know-how-to-toggle-animate-mode-as-a-hotkey/11787

**Comment by Keyikedalube** [comment]
[Initial hotkey suggestion](https://forums.synfig.org/t/anyone-know-how-to-toggle-animate-mode-as-a-hotkey/11787/7?u=keyikedalube):
- `Ctrl + Space`
- `Ctrl + M`

@FirasH @morevnaproject @rodolforg @ice0 @BobSynfig

**Comment by FirasH** [comment]
I vote for `Ctrl + Space`

**Comment by rodolforg** [comment]
As `space` means "play" animation", I suppose `ctrl+space` good for toggle animation/'view' mode.

Is 'M' currently mapped to something by default?

**Comment by Keyikedalube** [comment]
> Is 'M' currently mapped to something by default?

Yes, SmoothMove Tool
![Screenshot from 2021-02-21 07-26-12](https://user-images.githubusercontent.com/24214509/108613249-1b3cbd00-7416-11eb-941c-45dad90a688d.png)

**Comment by rodolforg** [comment]
So I'd vote for  `ctrl+space` by default for toggle animation mode.

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
