### ISSUE TITLE
Improve jump to begin/end behavior if play bound is enabled

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2034]
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
![Screenshot from 2021-02-19 10-24-06](https://user-images.githubusercontent.com/24214509/108459511-d2adc400-729c-11eb-9237-ccbec6ce2c91.png)

I want jump to begin/end change dynamically to "jump to left bound or right bound" if playback bounds is enabled. Currently, that keyboard shortcut jumps all the way to 0f (begin) or \<n\>f (end) which is not intuitive.

![Screenshot from 2021-02-19 10-23-12](https://user-images.githubusercontent.com/24214509/108459736-451ea400-729d-11eb-99cb-87b86c5f6f56.png)

**Comment by FirasH** [comment]
I looked at this issue and the behavior of the first button is defined here:
https://github.com/synfig/synfig/blob/2fd42d255e6dd59f2024b17fef51d723e92e8d22/synfig-studio/src/gui/canvasview.cpp#L939-L940

although if I change it to:
```
	framedial->signal_seek_begin().connect(
		sigc::bind(sigc::mem_fun(*canvas_interface().get(), &CanvasInterface::set_time), time_model()->get_actual_play_bounds_lower()) );
```

it always goes back to 0f even after changing the bounds... It's like bound values are not getting updated or I'm missing something...

**Comment by Keyikedalube** [comment]
`&CanvasInterface::set_time`? Could that be the issue? The 1st code was `&CanvasInterface::seek_time`

**Comment by FirasH** [comment]
> 
> 
> `&CanvasInterface::set_time`? Could that be the issue? The 1st code was `&CanvasInterface::seek_time`

I've changed `&CanvasInterface::seek_time` to `&CanvasInterface::set_time` because the first is used to move forward and backward using a relative value (like -6 frames) while the second places the time cursor at the specified time.

**Comment by FirasH** [comment]
Made some tests but there's something I'm missing for sure...

If the code is changed to this:
```
framedial->signal_seek_end().connect(
		sigc::bind(sigc::mem_fun(*canvas_interface().get(), &CanvasInterface::set_time), Time(2)) );
```
when the button is clicked, the time cursor will be placed at 2 seconds which is the frame with value 2*fps.

For some reason `time_model()->get_actual_play_bounds_lower()` and `time_model()->get_actual_play_bounds_upper()` are not returning the `Time` variable I want or I'm binding the returned value wrongly...

**Comment by FirasH** [comment]
Got the issue...
The problem what that as it's defined now the binded value is picked only on interface initialization and when bounds are changed the same binded value isn't updated.

I've just connected the button to a function that does the same but picks the updated values and works perfectly!
