### ISSUE TITLE
[Feature request] Close a workspace tab using middle mouse click 

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2035]
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
Synfig offers multiple tab feature so I'd love if tabs can also be closed using the middle mouse click action just like on Firefox :)

![Screenshot from 2021-02-19 14-27-01](https://user-images.githubusercontent.com/24214509/108481836-ac991b80-72be-11eb-86bd-aaaac6095989.png)

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
