### ISSUE TITLE
Improve render progress info widgets

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2037]
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
![Screenshot from 2021-02-19 16-04-37](https://user-images.githubusercontent.com/24214509/108493517-6cd93080-72cc-11eb-97a6-0aa518c55e9c.png)

Show that button only when an animation project is being exported and then hide it again after it's done.

UPDATE: The intention of this issue changed based on discussions below.

**Comment by FirasH** [comment]
Makes sense to me, plus current button is not pretty to look at...

**Comment by morevnaproject** [comment]
Agree. ^__^

**Comment by FirasH** [comment]
What do you think about moving the stop button to the right of the render bar like in this quick draft:

![proposal-render](https://user-images.githubusercontent.com/6705690/112456784-5efb4d00-8d5b-11eb-8729-5e51de90c34b.png)

maybe this way we can keep it visible and enable/disable it as needed?

**Comment by Keyikedalube** [comment]
Nice idea. What icon are we using then? Also, we might need to add a tool tip to briefly describe the button purpose.

However, I feel that layout works best on status bar. For now, these widgets are placed on info dock panel with spacious content area so the current vertical layout looks OK to me.

**Comment by FirasH** [comment]
> 
> 
> Nice idea. What icon are we using then? Also, we might need to add a tool tip to briefly describe the button purpose.
> 
> However, I feel that layout works best on status bar. For now, these widgets are placed on info dock panel with spacious content area so the current vertical layout looks OK to me.

I would use this red one:
![stop-button](https://user-images.githubusercontent.com/6705690/112466132-cae2b300-8d65-11eb-8503-df473dad0c3a.PNG)

About the vertical layout I don't like it as of now because the button gets unecessarily very wide.
I have to check though how to align it vertically next to render bar because the text percentage is part of the bar IIRC.

**Comment by Keyikedalube** [comment]
> I have to check though how to align it vertically next to render bar because the text percentage is part of the bar IIRC.

Hope this sample statement works
`widget.set_valign(Gtk::ALIGN_END)`

**Comment by FirasH** [comment]
What do you think about something like this?
![stop-button-right](https://user-images.githubusercontent.com/6705690/112545828-f3e06380-8db8-11eb-9591-b9b7bfd61a4d.png)

The progress bar is centered so that the percentage value is not biased to left/right making it look weird.

**Comment by Keyikedalube** [comment]
Also, progress bar and button are not center aligned properly. Could be KDE? I'll test your PR on GNOME desktop...

**Comment by FirasH** [comment]
> Also, progress bar and button are not center aligned properly. Could be KDE? I'll test your PR on GNOME desktop...

As of now the progress bar is centered and the button is placed next to it.

Do you have a screenshot of it?

**Comment by Keyikedalube** [comment]
![Screenshot from 2021-03-26 15-37-26](https://user-images.githubusercontent.com/24214509/112615921-1d48d000-8e49-11eb-926c-bfb4f3efe13c.png)

I think it'd look nice to have that stop button padded at least 3px from the progress bar.

**Comment by ice0** [comment]
Another version:

![render-progress1](https://user-images.githubusercontent.com/5604544/112709305-ddd2c000-8eea-11eb-9303-d231e727068c.png)
![render-progress2](https://user-images.githubusercontent.com/5604544/112709306-df9c8380-8eea-11eb-9a5c-b5cb93bb73dd.png)

**Comment by Keyikedalube** [comment]
**Render Progress:** center-aligned looks better. Gets the user's attention easily :)

**Comment by FirasH** [comment]
> Another version:
> 
> ![render-progress3](https://user-images.githubusercontent.com/5604544/112709395-d364f600-8eeb-11eb-9277-fdc65e5eef76.png)
> 
> ![render-progress1](https://user-images.githubusercontent.com/5604544/112709305-ddd2c000-8eea-11eb-9303-d231e727068c.png)
> ![render-progress2](https://user-images.githubusercontent.com/5604544/112709306-df9c8380-8eea-11eb-9a5c-b5cb93bb73dd.png)

I wasn’t able to place the percentage inside the progress bar, how do you do that? I tried but without success.

**Comment by rodolforg** [comment]
I don't know if it possible with Progress Bar itself, or via CSS.

But you can do the trick with a GtkOverlay and signals :P Not difficult, but annoying lol

**Comment by Keyikedalube** [comment]
Found a related StackOverflow post for this: https://stackoverflow.com/questions/61298451/c-gtk-progressbar-not-acting-as-expected
One of the comment seems to provide a solution to the said issue: https://www.youtube.com/playlist?list=PLN_MPJUQgPVotiGnpwXQXNMHcGKr144z6

**Comment by ice0** [comment]
> I wasn’t able to place the percentage inside the progress bar, how do you do that? I tried but without success.

This is Photoshop magic :)

Anyway, this is an example of how to that using the `Overlay` class:

![Screenshot_103](https://user-images.githubusercontent.com/5604544/112742414-9286e300-8fb8-11eb-8815-2c20d0c0f324.png)


```
import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, GLib

class ProgressBarWindow(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title="ProgressBar Demo")
        self.set_border_width(10)

        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
        self.add(vbox)

        overlay  = Gtk.Overlay()

        css_provider = Gtk.CssProvider.new()
        css_provider.load_from_data(str.encode("trough, progress { min-height: 30px; }"))

        self.progressbar = Gtk.ProgressBar()
        self.progressbar.get_style_context().add_provider(css_provider, Gtk.STYLE_PROVIDER_PRIORITY_USER)

        overlay.add(self.progressbar)

        self.plabel = Gtk.Label.new()
        overlay.add_overlay(self.plabel)

        overlay.set_valign(Gtk.Align.CENTER) 

        vbox.pack_start(overlay, True, True, 0)

        button = Gtk.CheckButton(label="Show text")
        button.connect("toggled", self.on_show_text_toggled)
        vbox.pack_start(button, True, True, 0)

        self.timeout_id = GLib.timeout_add(50, self.on_timeout, None)
        self.activity_mode = False

    def on_show_text_toggled(self, button):
        show_text = button.get_active()
        text = None
        self.progressbar.set_text(text)
        self.progressbar.set_show_text(show_text)

    def on_timeout(self, user_data):
        """
        Update value on the progress bar
        """
        if self.activity_mode:
            self.progressbar.pulse()
        else:
            new_value = self.progressbar.get_fraction() + 0.01

            if new_value > 1:
                new_value = 0

            self.progressbar.set_fraction(new_value)
            self.plabel.set_text(str(int(new_value*100)) + "%")

        # As this is a timeout function, return True so that it
        # continues to get called
        return True


win = ProgressBarWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
```

**Comment by FirasH** [comment]
With `Gtk::Overlay` I managed to make it quite quickly.

Here you can see the current result:
![progress-text-overlay](https://user-images.githubusercontent.com/6705690/112748100-f1009100-8fb9-11eb-9624-e8ada029ec89.png)
