### ISSUE TITLE
Inconsistent dialog action button order

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2038]
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
![Screenshot from 2021-02-19 19-44-40](https://user-images.githubusercontent.com/24214509/108516216-f5b39480-72eb-11eb-9a70-9baac82079a1.png)

Should be **Cancel** -> **OK** instead of the reverse

**Comment by Keyikedalube** [comment]
Same issue with this text input dialog 👉  #2041

**Comment by FirasH** [comment]
Same for Gradient/Color dialogs

**Comment by DhairyaBahl** [comment]
@ankit-kumar-dwivedi I would like to work on this issue ! Kindly assign this to me. Thank You

**Comment by FirasH** [comment]
@DhairyaBahl great! You can start to work on it 👍
If you want a reference this is how some other buttons have been fixed https://github.com/synfig/synfig/commit/d8388cabf95fefa21d6d950798a58b841dc3b652

**Comment by DhairyaBahl** [comment]
@FirasH Thank You ! I am on it.

**Comment by ankit-kumar-dwivedi** [comment]
> @ankit-kumar-dwivedi I would like to work on this issue ! Kindly assign this to me. Thank You

Done

**Comment by DhairyaBahl** [comment]
@ankit-kumar-dwivedi @FirasH I have created PR for this issue ! Kindly check it out. Thanks :)

**Comment by ankit-kumar-dwivedi** [comment]
> @ankit-kumar-dwivedi @FirasH I have created PR for this issue ! Kindly check it out. Thanks :)

It would be great if you can fix these as well in the same PR [^_^]

> Same for Gradient/Color dialogs



> Same issue with this text input dialog 👉 #2041

**Comment by DhairyaBahl** [comment]
@ankit-kumar-dwivedi Working on it . Will push my changes soon ^_^

**Comment by DhairyaBahl** [comment]
![image](https://user-images.githubusercontent.com/71627983/111863565-6a78fd80-8982-11eb-80b4-ecc065f5a0b5.png)


@ankit-kumar-dwivedi  @FirasH  Kindly tell me if this is layout is good to go ? I have moved the "close" button before the other two buttons. Kindly confirm if I did this correctly . Then I will push the changes in the PR.

Thanks and Regards ^__^

**Comment by DhairyaBahl** [comment]
![image](https://user-images.githubusercontent.com/71627983/111869198-2c8cd100-89a4-11eb-9054-cf09c93a8250.png)

I've also fixed button layout for #2041 

@ankit-kumar-dwivedi @FirasH @Keyikedalube Kindly check both of my added screenshots ^_^

Regards

**Comment by Keyikedalube** [comment]
> I've also fixed button layout for #2041

@DhairyaBahl 
No, that's the first dialog that pops up when the user creates a text layer.
We need to fix the other dialog that pops up when you try to modify text content again.

https://user-images.githubusercontent.com/24214509/111869582-45968180-89a6-11eb-8f35-56ac501f4da2.mov

**Comment by DhairyaBahl** [comment]
> ![image](https://user-images.githubusercontent.com/71627983/111863565-6a78fd80-8982-11eb-80b4-ecc065f5a0b5.png)

![image](https://user-images.githubusercontent.com/71627983/111873307-b1341b00-89b5-11eb-8157-62ddec930d1e.png)

@Keyikedalube I fixed this ! but I am still not sure about the gradient one ! Kindly check it out and tell me if that one is correct ?

Thanks & Regards [^__^]

**Comment by Keyikedalube** [comment]
@DhairyaBahl Fetching and building...

**Comment by DhairyaBahl** [comment]
> @DhairyaBahl Fetching and building...

I have also included the screenshot for the same in the previous comment :) and I haven't pushed these changes in the PR :(

**Comment by Keyikedalube** [comment]
@DhairyaBahl Please push. There's no way I can test if you haven't pushed LOL

**Comment by DhairyaBahl** [comment]
@Keyikedalube Just A minute . Sorry for inconvenience.

**Comment by Keyikedalube** [comment]
> Kindly check it out and tell me if that one is correct ?

It's correct to me. Cancel/Close should always come first. Part of GNOME HIG. GIMP and Inkscape follow that.

**Comment by DhairyaBahl** [comment]
> > Kindly check it out and tell me if that one is correct ?
> 
> It's correct to me. Cancel/Close should always come first. Part of GNOME HIG. GIMP and Inkscape follow that.

@Keyikedalube Got it . And I have pushed the changes. Kindly check those out. Sorry for inconvenience again [._.]

**Comment by FirasH** [comment]
Closing as PR was merged :+1:
