### ISSUE TITLE
Menu mnemonics for text layer input dialog

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2041]
**Is your feature request related to a problem? Please describe.**
Can't use keyboard mnemonics `Alt + O` or `Alt + C` to apply or cancel changes

**Describe the solution you'd like**
Implement the mnemonics

**Describe alternatives you've considered**
Use mouse click to apply or cancel changes

**Additional context**
![Screenshot from 2021-02-21 13-29-19](https://user-images.githubusercontent.com/24214509/108661697-78a63c00-74f2-11eb-9cde-435297310a9e.png)

**Comment by rodolforg** [comment]
Maybe support `ctrl + Enter/Return` too as an OK button press.

**Comment by rChen10** [comment]
@Keyikedalube @rodolforg I would like to work on this.

**Comment by Keyikedalube** [comment]
@rChen10 What about #2018? Too much workload is not a good idea.

**Comment by rChen10** [comment]
Yeah, you're right. I'll finish #2018 first. Probably jumping the gun here too much.

**Comment by harish911** [comment]
@rodolforg  where is the code of text can you help me

**Comment by rodolforg** [comment]
Sure!
The code of this dialog is here:
https://github.com/synfig/synfig/blob/a8278a3f82fbab3b823ec08f524552b14afdb4f3/synfig-studio/src/gui/app.cpp#L3761

**Comment by mohamedAdhamc** [comment]
> Maybe support `ctrl + Enter/Return` too as an OK button press.

    if this hasn't been done yet (I tested it and seems like it hasn't). I would like to do it.  However, @rodolforg Just to be clear here though, this "OK button press" is the same thing @Keyikedalube  meant by "to apply change". and cancel change is, therefore "cancel button press". 

   Also, If what I'm getting here is correct what button combos would be best for these two ? I have noticed for the text tool it's just enter for ok and escape for cancel, should it just be that as well to be more unified.

**Comment by mohamedAdhamc** [comment]
> Maybe support `ctrl + Enter/Return` too as an OK button press.

 If this hasn't been done yet (I tested it and seems like it hasn't). I would like to do it.  However, @rodolforg Just to be clear here though, this "OK button press" is the same thing @Keyikedalube  meant by "to apply change". and cancel change is, therefore "cancel button press".  
Also, If what I'm getting here is correct what button combos would be best for these two ? I have noticed for the text tool it's just enter for ok and escape for cancel, should it just be that as well to be more unified.

**Comment by rodolforg** [comment]
> this "OK button press" is the same thing @Keyikedalube meant by "to apply change"

Yes: Pressing OK applies the changes and close the dialog. The shortcut `Ctrl`+`Enter` would do the same.


> and cancel change is, therefore "cancel button press".

Yes, `Esc` would close the dialog without apply the changes. It's the same behavior if user clicks on Cancel button or Close button.



> I have noticed for the text tool it's just enter for ok and escape for cancel, should it just be that as well to be more unified.

No. The Paragraph dialog is for allowing text with more than one line. So `Enter` should work for new lines.
It's just like this text-area here. `Enter` means new-line/break line, `Ctrl+Enter` behaves user clicking on the green "Comment" button.

**Comment by mohamedAdhamc** [comment]
> > this "OK button press" is the same thing @Keyikedalube meant by "to apply change"
> 
> Yes: Pressing OK applies the changes and close the dialog. The shortcut `Ctrl`+`Enter` would do the same.
> 
> > and cancel change is, therefore "cancel button press".
> 
> Yes, `Esc` would close the dialog without apply the changes. It's the same behavior if user clicks on Cancel button or Close button.
> 
> > I have noticed for the text tool it's just enter for ok and escape for cancel, should it just be that as well to be more unified.
> 
> No. The Paragraph dialog is for allowing text with more than one line. So `Enter` should work for new lines. It's just like this text-area here. `Enter` means new-line/break line, `Ctrl+Enter` behaves user clicking on the green "Comment" button.

Oh alright makes sense, so (ctrl+enter) for applying change and (Esc) for canceling the change. Will be working on this in a couple hours.
