### ISSUE TITLE
Non-ascii characters in filename produce no such file while trying to render 

### ISSUE THREAD

**Issue by jussikiova** [synfig/synfig#2058]
Synfig generates a "no such file or directory" -error if there are non-ascii chactacters in the file name while trying to render. Example of such a path is C:\Users\jussi\OneDrive\Työpöytä\test.avi.

Ascii filenames do work normally.

 - OS version: Windows 10 Home v. 19042.804
 - Synfig version: 1.4.0

**Comment by BobSynfig** [comment]
Well-known and already solved issue.
Fixed version should be available in 1.4.1
See https://github.com/synfig/synfig/issues/1885

**Comment by jussikiova** [comment]
Good, I'm glad =) I just didn't find the #1885 by search, so I reported it just in case. After all, the bug stops the show during basic tutorial for some of us.
