### ISSUE TITLE
Inconsistent tool name in tool options panel and toolbox window

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#2067]
**Describe the bug**
Tool names are inconsistent in the Tool Options Panel and The Toolbox window tool (description/tooltip)

**Expected behavior**
These names must be consistent at both places.

**Screenshots**
![Screenshot 2021-03-18 at 8 02 39 PM](https://user-images.githubusercontent.com/37617951/111645328-98e1c600-8826-11eb-81c7-5aac5b0927c5.png)
![Screenshot 2021-03-18 at 8 00 21 PM](https://user-images.githubusercontent.com/37617951/111645339-9c754d00-8826-11eb-94eb-0a68924f333b.png)
![Screenshot 2021-03-18 at 7 48 13 PM](https://user-images.githubusercontent.com/37617951/111645343-9da67a00-8826-11eb-8c4d-8a00295b86ed.png)
![Screenshot 2021-03-18 at 7 46 34 PM](https://user-images.githubusercontent.com/37617951/111645344-9e3f1080-8826-11eb-8b16-4608badc5915.png)

**Desktop (please complete the following information):**
 - OS: Mac 
 - OS version: 10.15.7 Catalina
 - Synfig version: 1.4.0

**Comment by ankit-kumar-dwivedi** [comment]
@ice0 @rodolforg @morevnaproject your take on this?

**Comment by FirasH** [comment]
I think this has been fixed in 1.5 and a backport is needed

**Comment by FirasH** [comment]
Found the commit: 67b1ab7fc451c2d201da6bfc6b31083125481537

**Comment by FirasH** [comment]
Also this commit could be backported: 5156403d193864c9afb76c24326f56c509ea9e15

**Comment by ankit-kumar-dwivedi** [comment]
thanks, @FirasH closing this one.
