### ISSUE TITLE
Shortcut for Save all menu action

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2073]
**Is your feature request related to a problem? Please describe.**
OP wants a shortcut key to instantly save all his animations files
https://forums.synfig.org/t/problem-assigning-shortcut-to-save-all-action/11955

**Describe the solution you'd like**
Implement the accel key for Save all
OP tried `Ctrl+E`

**Describe alternatives you've considered**
Access Save all animation files through the menu bar

**Additional context**
_Nil_

**Comment by VaibhavDS19** [comment]
Is this ok for GSoC? I have literally 0 code experience with this but it seems interesting, so I thought I could learn this. Please let me know.

**Comment by Keyikedalube** [comment]
Yes, if it's related to your project proposal. So if an aspiring GSoC student is targeting Synfig GUI hacking then this issue is perfectly suited for beginners like you :)

**Comment by VaibhavDS19** [comment]
Ok thank you. Where do I find the code documentation? Is it on the website or on the Github repo inside the code?
Please let me know

**Comment by DhairyaBahl** [comment]
@VaibhavDS19  You can refer to [this](https://synfig-docs-dev.readthedocs.io/) and try building synfig in your local system. ^_^

**Comment by Keyikedalube** [comment]
- Best way to learn GTKMM comprehensively in your free time:
https://developer.gnome.org/gtkmm-tutorial/3.24/gtkmm-tutorial.html
- Quick API reference:
https://developer.gnome.org/gtkmm/3.24/

Unfortunately, Synfig still uses deprecated API from older versions of gtkmm so you have to be flexible learning directly from reading the source code (not necessarily understanding the "how" but the ability to observe patterns)

Hope this helps 🙂
