### ISSUE TITLE
[Synfig Studio] Skeleton "Name" value is not updated as new Layers are created

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#2082]
**Synfig version**:
master 1ffe5c3

**Issue description**:
1) Create a new animation
2) Select the `Skeleton Tool`
Now in the `Toolbox` window a `Name:` value is assigned automatically like "NewSkeleton014".
3) Create more Layers using the `Create Layer` button

Only the first Layer created uses the value assigned then it reuses the same value for all the next ones.
The tool should update the name value on each time a new Layer is created and keep consistent the used and the displayed value.

**Comment by rChen10** [comment]
@FirasH I'd like to work on this issue.

**Comment by FirasH** [comment]
> @FirasH I'd like to work on this issue.

Awesome! I’ll assign it to you 👍

**Comment by rodolforg** [comment]
@rChen10 Any news? Do you need any help?
