### ISSUE TITLE
Make Sets select layer with a single click instead of double-clicking

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#2085]
I propose to make behavior of selecting layers in 'Sets' panel similar to 'Layers' panel where active layer changes as soon as user clicks on it. In 'Sets' you need to double-click on a layer in order to make it active, if you just click on it'll simply become highlighted which is basically useless.
![SetsHL](https://user-images.githubusercontent.com/28569334/112953486-30f47f00-9146-11eb-9a44-e9c042169a2b.png)

Since 'Sets' supposed to ease access to important layers I think it makes sense to select layer as soon as user clicks on it rather than just make it highlighted. It especially becomes an inconvenience when you need to select several layers from the set, because you can't distinguish between the layer being selected or just highlighted.

**Comment by FirasH** [comment]
https://github.com/synfig/synfig/blob/2ef1e6f6553b2c6dd844a6b94014350b1b64ea83/synfig-studio/src/gui/trees/layergrouptree.cpp#L201-L269

**Comment by rodolforg** [comment]
Should we backport it to 1.4.2 as stated in milestone or to future 1.4.3?

**Comment by ice0** [comment]
@rodolforg I suggest to move it to 1.4.3.
