### ISSUE TITLE
Cannot open exported canvas

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2087]
**Describe the bug**
It is not possible to open exported canvas after it is closed.

**To Reproduce**
1. Open any file with exported canvas (i.e. this one - [aaa.sifz.zip](https://github.com/synfig/synfig/files/6229850/aaa.sifz.zip) ).
2. In Canvas Browser Panel double-click exported canvas -> new tab will open with contents of that exported canvas
3. Close that tab.
4. Double-click again on exported canvas in Canvas Browser Panel. -> nothing happens

**Expected behavior**
New tab should open with contents of that exported canvas.

**Screenshots**
Video - https://youtu.be/vmhRrq4cgfQ

**Desktop (please complete the following information):**
 - OS:Linux Mint 19
 - OS version: Mint 19
 - Synfig version: master branch  - ef901e498d8a9653b06971f034b9641946ba4f50

**Comment by Keyikedalube** [comment]
Closing #2027 in favor of this issue.

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
