### ISSUE TITLE
Problems when linking Group to Bone - Origin Parameter is linked instead of Transformation Parameter

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2089]
In this video at 33:00 - https://youtu.be/PdNn6-Itvqw?t=1975 - user tests latest build from master on windows.

He has problems when he tries to link Group to bone - after linking the Group moved incorrectly when Bone is moved.

I have watched it carefully and it looks like the problem in following:
-  notice that he modifies origin of transformation (purple point) before linking object to bone
-   for some reason purple point remains active (even after he clicking green point)
-   as result, when he links to bone, the bone attached to “origin of transformation” parameter. This is why the group transformed incorrectly when bone is moving.

![screenshot_001](https://user-images.githubusercontent.com/332868/113012047-9bd4a300-91a4-11eb-8af9-391c14ea74f7.png)

Unfortunately, I cannot reproduce the issue here on Linux.
Can anyone try to reproduce on Windows?

Liink to windows build used in the video - https://ci.appveyor.com/api/buildjobs/vuxprwrpomydqber/artifacts/SynfigStudio-1.5.0-testing-2021-03-17-win64-3b1f3.zip

**Comment by vinurd** [comment]
https://youtu.be/gs6ap7bpHBQ
at this stage, there are two problems. Layers walk when bound to the bones. And the canvas.In the video, I voiced it.

**Comment by rodolforg** [comment]
> Unfortunately, I cannot reproduce the issue here on Linux.

I think  he kept the `ctrl` key pressed: moved the origin (light pink/purple), ctrl+click to select skeleton too, plus ctrl+click to select bone.

**Comment by Keyikedalube** [comment]
> plus ctrl+click to select transformation handle (green handle).

Yeah, that was the culprit.

After the bone is highlighted `ctrl` key didn't need to be held down, if the OP had done that the origin handle would be deselected and bone link would behave normally.

Below is a sample video reproduced on Fedora Linux

https://user-images.githubusercontent.com/24214509/125930404-2c2ac520-ee3e-4d78-9ea3-babbd61a51be.mp4
