### ISSUE TITLE
Software Not Opening

### ISSUE THREAD

**Issue by ChirathPansilu** [synfig/synfig#2091]
**Describe the bug**
Software is not opening. It is shown in windows toolbar but when I try to access in nothing happens.

This is the windows debug console output ->

> (synfigstudio.exe:15096): Gtk-←[1;33mWARNING←[0m **: Could not find the icon 'missing-image-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
(synfigstudio.exe:15096): Gtk-←[1;33mWARNING←[0m **: Allocating size to gtkmm__GtkWindow 0529B288 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

**Expected behavior**
This software worked correctly before and this happened after I closed it and reopened the software

**Screenshots**
![image](https://user-images.githubusercontent.com/55843917/113299037-1115b480-931a-11eb-9531-fa6d7c681ca5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS version: 10
 - Synfig version: 1.4.0

**Additional context**
This happened even after I reinstalled the software after uninstalling.

**Comment by ice0** [comment]
@ChirathPansilu Hi!

Looks like [minimization bug](https://github.com/synfig/synfig/issues/1871). This happens when you minimize the main window and close it with the right mouse button. To fix this, just remove or rename `%USERPROFILE%\Synfig\settings-1.4` file.

**Comment by ChirathPansilu** [comment]
@ice0 Hi!

Thank You very much, It worked.
Happy to hear that it will be fixed.
