### ISSUE TITLE
texture gradient

### ISSUE THREAD

**Issue by vinurd** [synfig/synfig#2103]
Dots, lines, and crosses. Like a gradient on a surface. Allows you to create graininess as in the illustrator.
![2021-04-09_23-17-56](https://user-images.githubusercontent.com/32761694/114202554-dfd85c80-9989-11eb-86d7-37e60db3d9a2.png)
![2021-04-09_23-17-33](https://user-images.githubusercontent.com/32761694/114202562-e1a22000-9989-11eb-90ef-56e2ba3c98c8.png)
![2021-04-09_23-20-11](https://user-images.githubusercontent.com/32761694/114202854-32b21400-998a-11eb-8420-ea325a86c848.png)
![2021-04-09_23-19-26](https://user-images.githubusercontent.com/32761694/114202858-33e34100-998a-11eb-93f5-03c55baa179b.png)

**Comment by yoSachinkr** [comment]
You can already do that in synfig.

**Comment by yoSachinkr** [comment]
It can be achieved by creating a "dissolve" blend mode in synfig.

**Comment by yoSachinkr** [comment]
May be this is the formula to create the dissolve blend mode. I've found this on a site:
![image](https://user-images.githubusercontent.com/50204208/128604420-43bab798-0298-42e7-bf1f-daf41bcf89a9.png)

**Comment by yoSachinkr** [comment]
![image](https://user-images.githubusercontent.com/50204208/128605400-f4185450-fb7f-4af5-a5ca-2a980a06599b.png)

**Comment by yoSachinkr** [comment]
http://www.yaldex.com/open-gl/ch19lev1sec6.html#:~:text=base%20%2B%20blend)%20*%200.5%3B-,19.6.3.%20Dissolve,-In%20the%20DISSOLVE

**Comment by yoSachinkr** [comment]
https://github.com/opentoonz/opentoonz/blob/cfbc8be0c70c45d5ad88eb6cf0646bd9ec450fb1/toonz/sources/stdfx/dissolvefx.cpp

**Comment by morevnaproject** [comment]
This feature already available with Halftone 2 layer.
![screenshot_002](https://user-images.githubusercontent.com/332868/132994246-5795fa18-3e0b-44ca-a3b2-23c7f809fbed.png)

Sample file - 
[halftone.sifz.zip](https://github.com/synfig/synfig/files/7149867/halftone.sifz.zip)
