### ISSUE TITLE
Move non-portable `popen` code to one place (discussion)

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#2108]
We have a non-portable pipe code that starts a process and reads its output using `popen`, `pclose`.
It is used in plugins (to run Python binaries), `mod_ffmpeg` (to run ffmpeg),` mod_dv` (encodedv), and `mod_imagemagick` (convert). 

I suggest moving this code to one place. Maybe to `synfig::FileSystem` as it work with files?

**Comment by rodolforg** [comment]
What about an OS class/namespace for handling things we know are specific to OS?
pipe, access / status, another binary running, etc.

**Comment by ice0** [comment]
> What about an OS class/namespace for handling things we know are specific to OS?
> pipe, access / status, another binary running, etc.

Sounds good.
