### ISSUE TITLE
Crashes when user (wrongly) try to move a group layer into a child group

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#2110]
**Describe the bug**
Synfig Studio doesn't check if a group layer is being moved into a child group layer.

**To Reproduce**
1. Create a Group layer (Group A in the screenshot below)
2. Create a Group layer named Group B
3. By dragging and dropping, move the Group B into Group A (as shown in screenshot below)
4. Now drag Group A to inside Group B.
5. It crashes.

![Captura de tela de 2021-04-16 15-59-09](https://user-images.githubusercontent.com/1323987/115071547-c163eb00-9ecc-11eb-8d69-d1a9439635af.png)

**Expected behavior**
Synfig should ignore this type of layer movement.

**Desktop (please complete the following information):**
 - OS: any
 - OS version: any
 - Synfig version: 1.4.0

**Comment by rodolforg** [comment]
Solution should be done here:
https://github.com/synfig/synfig/blob/c76ede2b0f8625886ae5c7a2b4f243d56b4b8ca1/synfig-studio/src/gui/trees/layertreestore.cpp#L512

**Comment by rodolforg** [comment]
@ice0 this issue should be for 1.4.2, right?

**Comment by ice0** [comment]
> @ice0 this issue should be for 1.4.2, right?

Yes, you are right. Moved it to 1.4.2

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
