### ISSUE TITLE
Set minimum CMake version to old old stable

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2115]
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
Synfig has an inconsistent `cmake_minimum_required` version for ETL and SynfigStudio projects.
One is too old (v2.x) and the other set to v3.x.

With Fedora 34 releasing soon this month and CMake 20 already out, my current system is already complaining about synfig's outdated CMake version compatibility
![Screenshot from 2021-04-19 10-38-01](https://user-images.githubusercontent.com/24214509/115184194-ec338680-a0fa-11eb-8de1-9a8de14b2964.png)

I propose updating the CMake requirement to old-old stable ie., v3.5 (thanks to rodolforg for tracking that down [here](https://forums.synfig.org/t/gtk-gtkmm-versions-x-linux-distros/12017/8))

**Comment by ice0** [comment]
Ok, I will take it.

**Comment by rodolforg** [comment]
Not related comment, but I think it's pretty cool that I use Debian (testing), you use Fedora, Konstantin Linux Mint, ice0 and Fadhil Windows :)
