### ISSUE TITLE
Warp Layer crops incorrectly when used with Noise Gradient

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2124]
Warp Layer gives incorrect result with Noise Gradient Layer when "Clip" Parameter is set to "true".

Sample file - https://gitlab.com/synfig/synfig-tests/-/raw/130851ed95424abeee9b6fe7cf58c6f81dbc8ce3/rendering/sources/layers/warp/warp-noise-gradient-1point-clip.sif?inline=false

Current master branch (d66774460d52b3a5b237cae04b81585c45970476) (notice the area is not clipped correctly) -
![screenshot_008](https://user-images.githubusercontent.com/332868/115888588-4a56c580-a47d-11eb-949f-94655be9280e.png)

Synfig 1.4.1 -
![screenshot_009](https://user-images.githubusercontent.com/332868/115889467-2b0c6800-a47e-11eb-9f91-e75e050cb85d.png)

Synfig 1.0.2 -
![screenshot_007](https://user-images.githubusercontent.com/332868/115888498-30b57e00-a47d-11eb-971f-2b245556c03a.png)

**Comment by morevnaproject** [comment]
I am afraid this issue is blocking 1.4.3 release (we plan to ship reworked Warp Layer in 1.4.3).

@rodolforg @ice0 any ideas how we can deal with this?

**Comment by morevnaproject** [comment]
As one possible workaround - I can try to revert all commits to (temporary) exclude this feature from master branch. Considering the amount of changes, I am not sure this will be possible, but if I will manage to achieve that, then we can put those changes into separate PR and keep it unmerged until the issue will be resolved.

**Comment by rodolforg** [comment]
After a `git bisect start -- synfig-core/src/modules/lyr_std/warp.cpp synfig-core/src/modules/lyr_std/perspective.cpp`
I found out the problem is this commit 6af075f1fe0ef00a7dbfbbb77bf8c724b2702866
