### ISSUE TITLE
Wide spaces between close button and tab's edge when multiple tabs are opened

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2127]
**Synfig version & platform**:
Building from source
Fedora 33

**Issue description**:
Is this an expected behavior?
https://user-images.githubusercontent.com/24214509/116174354-dbeb5f00-a72b-11eb-821f-a4c74fec81c2.mov

**Comment by rodolforg** [comment]
No, it's not ;)

**Comment by FirasH** [comment]
Confirmed on Windows 10

**Comment by FirasH** [comment]
It happens when there are enough opened tabs to fill the available horizontal space. `Gtk::Notebook` will automatically expand the tabs to fill the available space without leaving "partially" hidden tabs.

The aestethic problem is that the close button doesn't keep a consistent distance from the tab right border.

**Comment by FirasH** [comment]
Looked a bit into the issue and starting from this:
![before-long-name](https://user-images.githubusercontent.com/6705690/116798510-7105a380-aaf0-11eb-80d3-4f9be4527598.png)

if we center the label it becomes like the following:
![after-long-name](https://user-images.githubusercontent.com/6705690/116798517-7d89fc00-aaf0-11eb-8ac2-6bc947b17813.png)

**Comment by ice0** [comment]
I think better to move close button to the right.

**Comment by rodolforg** [comment]
It doesn't happen in 1.4.x branch

**Comment by Keyikedalube** [comment]
I agree with ice0 too. All modern desktop apps with tabs have close button set close to the right.

**Comment by Keyikedalube** [comment]
@FirasH This issue was caused by PR #1774. Now we're seeing why `Gtk::Grid` is a bad replacement for single row container LOL. I tested the code with `Gtk::Box`:
- `pack_start()` for label and
- `pack_end()` for close button

Also, you need to set close button halign to `Gtk::ALIGN_END` otherwise the button is stretched. I guess @rodolforg might have noticed stretched button in 1.4.x branch :)

**Comment by Keyikedalube** [comment]
BTW, in GTK 4 `pack_start` and `pack_end` have been replaced with prepend and append. But the decision to use which API (Gtk 3)  is up to you.

**Comment by FirasH** [comment]
Made some changes and now it looks like this:
![close-button-right](https://user-images.githubusercontent.com/6705690/116872741-b6bc8c00-ac16-11eb-83b4-734b7dc748b6.png)

With this last version I'm only changing the tab associated with the document tabs without affecting others like docks or windows.

**Comment by FirasH** [comment]
@Keyikedalube I've left the current `Gtk::Grid`, but that could be changed quickly if needed :+1:

**Comment by Keyikedalube** [comment]
@FirasH never mind. You found a better solution than me.
