### ISSUE TITLE
AppVeyor build crashes opening a new animation

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#2162]
**Describe the bug**
Starting Synfig Studio AppVeyor build an error message pops out:
![error-start](https://user-images.githubusercontent.com/6705690/118701719-559ad800-b814-11eb-873f-d748bf838469.PNG)

**To Reproduce**
1. Launch Synfig Studio
2. Go to: `File > New`

Synfig crashes consistently.

**System information:**
 - OS: Windows
 - OS version: 10
 - Commit ID: 96c85ed

**Comment by ice0** [comment]
Related PR: https://github.com/synfig/synfig/pull/2157

**Comment by FirasH** [comment]
@ice0 I confirm the related PR fixes the issue.
