### ISSUE TITLE
Rhubarb suport 🙃

### ISSUE THREAD

**Issue by b-aaz** [synfig/synfig#2169]
Hi
Two days ago I made a topic in synfig forms for Margeing papagayo and synfig

● So in my opinion papagayo is not a stable program and it has lots of bugs and problems I it has been a week that iam searching for a way to make papagayo work correctly but there was no result 🥲
But then today I found a program called rhubarb it has alot of features and my only problem with it was the lack of gui but that’s OK it just makes some things a little harder

■ Rhubarb is supported by lot of animation softwares (opentoonz moho adobe Ae) :sunglasses:🤌and it is new and more stable​:muscle: and also it dosent need a duiloge it’s funny that it done the same thing that I did in last topic :grinning_face_with_smiling_eyes:

:heart: My point is if you can make synfig to suport rhubarb exported formats that would be nice (or maybe you can add it as a plug-in or a tool):smiling_face_with_three_hearts:

Thank Rodolforg for suggesting me to post this here 😃

**Comment by rodolforg** [comment]
If anyone wants to pick this issue, a way to is to improve ValueNode_AnimatedFile to support more than .pgo files.

And add the correspondent extension here:
https://github.com/synfig/synfig/blob/7ba303a3afab3edd5816b6a39d4af41a7f45d158/synfig-studio/src/synfigapp/canvasinterface.cpp#L729-L735

Link to Rhubarb LipSync for more info about file format (on ReadMe and exporters folder)
https://github.com/DanielSWolf/rhubarb-lip-sync

**Comment by rodolforg** [comment]
Here is where things should be added: https://www.github.com/synfig/synfig/tree/master/synfig-core%2Fsrc%2Fsynfig%2Fvaluenodes%2Fvaluenode_animatedfile.cpp .

The link is my previous post was just for adding the file extension ;)

**Comment by ice0** [comment]
@b-aaz 
>  I need two functions one to change a opacity of a group In a certain frame and the other one to make the groups

Opacity in synfig terms is the `amount` property. 

Group - is `Layer_Paste`.
To add a group, you need to call Action. This must be done so that the operation can be cancelled (undo).

**Comment by b-aaz** [comment]
> @b-aaz 
> >  I need two functions one to change a opacity of a group In a certain frame and the other one to make the groups
> 
> Opacity in synfig terms is the `amount` property. 
> 
> Group - is `Layer_Paste`.
> To add a group, you need to call Action. This must be done so that the operation can be cancelled (undo). 
> 
Thanks that was exactly what I wanted 😄 iam little busy now (exams 🤐📃) but I am trying to finish it and also thank you for adding the tag / label 🏷 😄

**Comment by rodolforg** [comment]
@b-aaz Could you tell me what Rhubarb file extensions are?

**Comment by b-aaz** [comment]
> @b-aaz Could you tell me what Rhubarb file extensions are? 

Sorry if I am late but xml tsv json and dat 
They have examples at their github page https://github.com/DanielSWolf/rhubarb-lip-sync
