### ISSUE TITLE
Blender like text boxes 

### ISSUE THREAD

**Issue by b-aaz** [synfig/synfig#2181]
Hi
 so in synfig text boxes need you to click on them type a value and hit the enter to see the effect on the shape 😶
I think that's little bit time consuming😪 because you need to do this cycle multiple time to make the shape as you want 😴
I found the blender text boxes very easy to use🤗 because 
1 you can change the value with mouse 
2 it updates the shape live 
3 it has little arrows to change the value 
Here is the image of it ![2423e78d162b0de1b39a03de041e6f9a8d702977.gif](https://user-images.githubusercontent.com/85005689/121292881-eb032680-c8ff-11eb-8299-212507569eec.gif)

Overally I think this type of input is very better for graphics software like synfig (also inkscape needs this too)

**Comment by rodolforg** [comment]
Duplicate #1470 

Thank you anyway :)

**Comment by b-aaz** [comment]
> Duplicate #1470 
> 
> Thank you anyway :)

Oh iam very sorry I😬😬😬
