### ISSUE TITLE
Unused header "gui/docks/dockmanager.h" included on multiple synfigstudio project files

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2183]
**Synfig version & platform**:
Building from source
Fedora Linux

**Issue description**:
Use the advanced project-wise search feature from your preferred IDE and track down the keyword `DockManager` with case sensitivity turned off.
There are multiple files that included that class's header file but are not using it.

Here's how it looks like on Qt Creator:
![Screenshot_2021-06-10_16-43-33](https://user-images.githubusercontent.com/24214509/121516444-d6ac5000-ca0b-11eb-9fb4-a42611e232cb.png)

Files that use it will look like this:
![Screenshot_2021-06-10_16-52-51](https://user-images.githubusercontent.com/24214509/121516842-4de1e400-ca0c-11eb-829d-9a5c061f50f3.png)

**Comment by FirasH** [comment]
I can take a look at this one

**Comment by FirasH** [comment]
I didn't find places in the code where `gui/docks/dockmanager.h` is included but unused.

In the cases where there's the `#include`, but there isn't an explicit reference to the `DockManager` class, it is anyway necessary as some of its methods are called "indirectly" from other parts of the code. Removing them doesn't allow code compilation to succeed.

**Comment by Keyikedalube** [comment]
Including headers that are not used in the current h/cpp file is redundant. Also, bottlenecks compilation time in case that included header file is modified.

> it is anyway necessary as some of its methods are called "indirectly" from other parts of the code

For this, we can ignore the said include directive in files that serve as core or parent classes to other classes.

But there are definitely some files that really don't need the header `"gui/docks/dockmanager.h"`.

**Comment by FirasH** [comment]
@Keyikedalube 
I've removed `#include <gui/docks/dockmanager.h>` for each file and tried to compile.
In none of the case the inclusion was useless or at least the compilation wasn't successful.

Not sure if I'm missing something.

**Comment by Keyikedalube** [comment]
@FirasH I took the time to look into this myself and you're right!

This issue could be reworded to "Improve include DockManager contract for app.h"
If you've noticed the said included file was done in implementation file app.cpp and that's the reason why all those remaining files I reported above are seen as redundant. Because they don't know what `DockManager` is yet that's why weird indirect dependency.

My solution to this is include `<gui/docks/dockmanager.h>` in app.h file instead and clean out that include in all remaining files. This will not only improve code readability but also improve compilation time. Because we have around 5 files that don't necessarily construct `DockManager` object in their classes.

@ice0 opinion?

**Comment by Keyikedalube** [comment]
And thank you @FirasH for looking into this yourself. Appreciate your time :)

**Comment by mohamedAdhamc** [comment]
> And thank you @FirasH for looking into this yourself. Appreciate your time :)

Hey it seems like noone is wo

> 

hey, it seems like no one is doing that could I possibly take this on?

**Comment by FirasH** [comment]
@mohamedAdhamc you can take this one 👍, assigning to you.

**Comment by mohamedAdhamc** [comment]
> @mohamedAdhamc you can take this one 👍, assigning to you.
alright thanks, just so I'm sure I understand correctly though. What needs to be done here is to include that file in-app.h and therefore removing the need to include it in other places, so then just removing the #include from other not needed places and making sure Synfig is building correctly after doing so. correct?

**Comment by mohamedAdhamc** [comment]
if so then I'm already doing this, and I successfully removed one of them and checked that synfig was building correctly. I will just remove the others and then make a proposal.

**Comment by mohamedAdhamc** [comment]
Done

**Comment by Keyikedalube** [comment]
Why "gui/docks/dockmanager.h" inclusion was done that way explained here https://github.com/synfig/synfig/pull/2579#issuecomment-1070290974

More info in the referenced PR. Closing this.
