### ISSUE TITLE
Hard to read editable input text fields for layer object parameters

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2186]
**Describe the bug**
It's hard to read values being edited when one of the parameters' property is activated. User input is obscured by existing values even when it's being edited.

**To Reproduce**
1. Draw a rectangle layer
2. Go to **Parameters** dock
3. Activate any one of the editable properties
4. Overlaid value is making it hard to read while being edited

**Expected behavior**
User input should not be obscured but clear and visible so reading it is not painful

**Screencast**

https://user-images.githubusercontent.com/24214509/121679754-53a3fc00-cad6-11eb-8d82-9073aba9c460.mp4

**System information:**
 - OS: Fedora Linux
 - OS version: 34
 - Commit ID: eafeda4828fea262646abba906b6650fb16591f4

**Additional comments**
-nil-

**Comment by ice0** [comment]
This is how it looks on my system (Mint 20):

![Screenshot_167](https://user-images.githubusercontent.com/5604544/121761900-ec7d5a80-cb5c-11eb-8bf2-0e57050eea76.png)

**Comment by Keyikedalube** [comment]
Oops! That was my GTK theme issue: Materia.

Not a bug LOL. Should've tried to verify with the default GTK Adwaita theme first. Closing it 😅

**Comment by ice0** [comment]
@Keyikedalube I think maybe we need to use a different approach here. I added screenshot just to show how it planned to be, so it looks like we need to dig further.

**Comment by Keyikedalube** [comment]
I confirm that this issue is not related to Synfig, it's a third-party GTK theme issue so I'm thinking the bug should be reported to Materia theme developers.

**Comment by ice0** [comment]
![Screenshot_115](https://user-images.githubusercontent.com/5604544/121763153-ef2f7e00-cb63-11eb-9da2-b74db1f08894.png)

This is the same widget with 50% opacity.
When we add the overlay widget, I think we need to change its opacity to 100% to make sure it doesn't clash with the theme settings.

**Comment by rodolforg** [comment]
Since some Gtk version, it just overlays the edit-widget of a TreeView cell.
It can be seen with a vector parameter, for example. Between the two TextEntry you can see the regular CellRenderer :/

**Comment by ice0** [comment]
> Since some Gtk version, it just overlays the edit-widget of a TreeView cell.

I thought this is Synfig widget.

@Keyikedalube can you check how CellRendererSpin looks on your system?
https://python-gtk-3-tutorial.readthedocs.io/en/latest/cellrenderers.html#cellrendererspin

Last example. Just save it as `cellrendererspin.py` and run with `python3 ./cellrendererspin.py`

**Comment by Keyikedalube** [comment]
![Screenshot_2021-06-16_15-28-52](https://user-images.githubusercontent.com/24214509/122199469-b1aa5800-ceb7-11eb-8436-90a391bd86b5.png)
![Screenshot_2021-06-16_15-29-08](https://user-images.githubusercontent.com/24214509/122199531-be2eb080-ceb7-11eb-84c7-4dfc89045076.png)

_3rd row same as 2nd screenshot_

**Comment by Keyikedalube** [comment]
So this is actually a third-party theme issue... not Synfig.

https://matrix.to/#/!aUhETchlgthwWVQzhi:matrix.org/$16255827622499Ythga:matrix.org?via=gnome.org&via=matrix.org&via=haecker.io
![Screenshot_2021-07-06_20-18-08](https://user-images.githubusercontent.com/24214509/124620784-5e646d80-de97-11eb-8fa3-b23e1b1f598d.png)

Close this issue?

**Comment by ice0** [comment]
I thought it was our custom widget, but this is standard cell renderer. So yes, I think we can close this issue now.
