### ISSUE TITLE
Can't undo end time set from toolbar

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2197]
**Describe the bug**
Canvas workspace doesn't indicate one of its properties (end time) has changed when set from toolbar.

**To Reproduce**
1. Go to the toolbar
2. Change the end time
3. Press enter
4. Document is updated but changes cannot be undone

**Expected behavior**
Undo operation should recover our previous canvas document state.

**Screenshots**
![Screenshot_2021-06-22_16-38-32](https://user-images.githubusercontent.com/24214509/122915070-f848f800-d378-11eb-843a-674d9381318e.png)

**System information:**
 - OS: Fedora Linux
 - OS version: 34
 - Synfig version: 1.4.1

**Additional comments**
-nil-

**Comment by FirasH** [comment]
I think this is related to #2198.
When end time is changed from the toolbar (`framedial.cpp`) the value in `renddesc.cpp` is not updated.

Connecting those two values should very likely fix both issues.

**Comment by rodolforg** [comment]
Sorry I was too lazy to edit video or record it again.
But here I show how to fix it (I use QtCreator as IDE, although I don't like Qt :P )

The Gtk::Inspector was useless in this case…

https://youtu.be/H8rR6_qzRH4

**Comment by Keyikedalube** [comment]
I thought `synfig::RendDesc` should emit signal changed when one of their properties have been modified or set so we don't have to explicitly call `refresh_rend_desc()` or `canvas_properties.refresh()` inside `on_set_end_time_widget_changed()` but I wasn't giving much thought to solving this.

@rodolforg Why didn't you submit the PR instead LOL
You could've tagged us to this comment https://github.com/synfig/synfig/issues/2198#issuecomment-875728683 which is more valuable than fishing the solution 😆 

@FirasH do you want to submit PR for this and the linked issue? Or if you're busy I can.

**Comment by rodolforg** [comment]
> I thought `synfig::RendDesc` should emit signal changed when one of their properties have been modified or set so we don't have to explicitly call `refresh_rend_desc()` or `canvas_properties.refresh()` inside `on_set_end_time_widget_changed()`

Synfig library is not for interactivity, for performance reasons on rendering.
For that, there is synfigapp layer.

I don't know if these command calls are needed. They should be connected to synfigapp signals. I guess it is currently needed because the choice of a single global instance for those dialogs.

> @rodolforg Why didn't you submit the PR instead LOL

I was at my lunch time lol
Besides, I wanted to record a way to investigate synfigstudio code. For newcomers, I hope...

**Comment by Keyikedalube** [comment]
> Besides, I wanted to record a way to investigate synfigstudio code. For newcomers, I hope...

I'll tag this and the linked issue for newcomers then :)

Interested contributors solution explained in https://github.com/synfig/synfig/issues/2198#issuecomment-875728683 and demonstrated here https://github.com/synfig/synfig/issues/2197#issuecomment-875724454

**Comment by Keyikedalube** [comment]
Interested contributors solution explained in https://github.com/synfig/synfig/issues/2198#issuecomment-875728683 and demonstrated here https://github.com/synfig/synfig/issues/2197#issuecomment-875724454

**Comment by rodolforg** [comment]
> I don't know if these command calls are needed.

Tested. They are not necessary.

**Comment by FirasH** [comment]
> 
> 
> I thought `synfig::RendDesc` should emit signal changed when one of their properties have been modified or set so we don't have to explicitly call `refresh_rend_desc()` or `canvas_properties.refresh()` inside `on_set_end_time_widget_changed()` but I wasn't giving much thought to solving this.
> 
> @rodolforg Why didn't you submit the PR instead LOL
> You could've tagged us to this comment [#2198 (comment)](https://github.com/synfig/synfig/issues/2198#issuecomment-875728683) which is more valuable than fishing the solution 😆
> 
> @FirasH do you want to submit PR for this and the linked issue? Or if you're busy I can. we could delegate them to newcomers :)

Sure, the code in the video is correct right?
