### ISSUE TITLE
End time not updated in render settings

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2198]
> > No need to open Canvas properties. You can edit time duration in place:
> 
> Doesn't work as expected for render settings. End time will be set for canvas but not the render settings. I remember setting both twice on my animation project some time ago.
> This can be rectified in another issue.

Figured this is actually a bug.
1. Change the end time from the toolbar
2. Save the document
3. Close Synfig Studio
4. Open Synfig Studio
5. Re-open the save file
6. Open Render dialog
7. End time is updated

_Originally posted by @Keyikedalube in https://github.com/synfig/synfig/issues/2025#issuecomment-861475064_

**Comment by rodolforg** [comment]
Those changes should be done via synfigapp actions not directly.

**Comment by rodolforg** [comment]
Sorry I was too lazy to edit video or record it again.
But here I show how to fix it (I use QtCreator as IDE, although I don't like Qt :P )

The Gtk::Inspector was useless in this case…

https://youtu.be/H8rR6_qzRH4

**Comment by rodolforg** [comment]
synfigapp is a middleware between GUI and synfig library.

It is responsible for undo-redo actions, generate/propagate signal for several synfig changes (layer adding, deleting, metadata renaming/changes, etc.).
So every action GUI performs should actually use synfigapp::Action or synfig::CanvasInterface ;)

**Comment by Keyikedalube** [comment]
Interested contributors solution explained in https://github.com/synfig/synfig/issues/2198#issuecomment-875728683 and demonstrated here https://github.com/synfig/synfig/issues/2197#issuecomment-875724454
