### ISSUE TITLE
Middle mouse click on exported subcanvas closes the root canvas

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2203]
**Describe the bug**
Closing any exported sub-canvases using the middle mouse click closes the root canvas and all its opened sub-canvases

**To Reproduce**
1. Create a rectangle layer and group it
2. Export the group to a new sub-canvas
3. Create an ellipse layer and group it
4. Export the group again
5. Open both sub-canvases
5. Close any sub-canvas using middle mouse click

**Expected behavior**
Only the selected sub-canvas should close

**Screencast**

https://user-images.githubusercontent.com/24214509/124211250-6eccbf00-db0a-11eb-8826-c348f26bab4d.mp4

**System information:**
 - OS: Fedora Linux
 - OS version: 34
 - Commit ID: https://github.com/synfig/synfig/commit/4273435309266fa4181269fdb3e9cc454cf14337

**Additional comments**
This PR can help https://github.com/synfig/synfig/pull/2107

**Comment by rodolforg** [comment]
According to this code that creates the Close button, we should change the callback function when user click with middle-button.

https://github.com/synfig/synfig/blob/2c2062c5d11551394126a995b7107d0c85c3cc1b/synfig-studio/src/gui/canvasview.cpp#L1987-L1998

**Comment by Keyikedalube** [comment]
I'll work on this.
