### ISSUE TITLE
Colored action buttons for `Gtk::FileChooserDialog`

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2208]
**Is your feature request related to a problem? Please describe.**
Synfig file chooser dialog utilizes header bar while some dialogs utilize standard `Gtk::Dialog` with the title bar. It'll be more useful if action buttons placed in the header bar are colored like normal GTK/GNOME apps to visually guide/assist the user.

**Describe the solution you'd like**
GTK provides CSS classes `suggested-action` and `destructive-action` for action buttons **OK/Open/Save** and **Cancel/Close** respectively

**Describe alternatives you've considered**
-nil-

**Additional comments**
- _**Current dialog: action buttons not colored**_
![Screenshot_2021-07-07_08-49-16](https://user-images.githubusercontent.com/24214509/124695739-6e189c00-df01-11eb-8713-6ca5f1a59435.png)

- _**Suggested feature: colored action buttons**_
![Screenshot_2021-07-07_07-26-30](https://user-images.githubusercontent.com/24214509/124695756-740e7d00-df01-11eb-8a42-5a0908387fb7.png)

**Comment by nickleus27** [comment]
is anyone working on this?

**Comment by rodolforg** [comment]
Not that I know of. :)

**Comment by nickleus27** [comment]
cool. I will work on it if that is okay.

**Comment by nickleus27** [comment]
@ice0 @rodolforg Am I understanding this correctly: ```Gtk::FileChooserDialog``` should have colored action buttons? For example ```cancel``` or ```save``` buttons in the save diolog, or ```cancel``` and ```open``` in the open diolog?

**Comment by ice0** [comment]
@nickleus27 
Yes if it is possible. I haven't tested it, but maybe they just aren't customizable.

**Comment by nickleus27** [comment]
@ice0 at the moment I am not finding any information on how to colorize the ```FileChooserDialog buttons```.  I understand how to colorize individual buttons, but not the ```FileChooserDialog buttons```

**Comment by Keyikedalube** [comment]
Hello :)

@nickleus27 if you're on Linux there's a package called `gtk3-demo`. I found out about colored action buttons in this example program `Theming > Style Classes`

For Synfig IIRC you have to get the dialog [object style context](https://stackoverflow.com/a/48643439/13138783) and call in `object.add_class("action-name")`

**Comment by nickleus27** [comment]
@Keyikedalube Thank you, that is very helpful.  I am experimenting with that now.

**Comment by Keyikedalube** [comment]
@nickleus27 Forgive my incorrect answer. Instead of the entire dialog you have to get only the button's object style context.

**Comment by rodolforg** [comment]
> @ice0 @rodolforg Am I understanding this correctly: any `Gtk::FileChooserDialog` should have colored action buttons? For example `cancel` or `save` buttons in the save diolog, or `cancel` and `open` in the open diolog?

The aim is not to make everything colorful :D I believe @Keyikedalube suggested to follow these guidelines: https://wiki.gnome.org/HowDoI/Buttons .

**Comment by nickleus27** [comment]
Thanks for all the help everyone. I have made an example app with ```"suggested-action"``` class and the ```"destructive-action"``` class. This example is coloring the action buttons correctly. 
 @Keyikedalube I am having trouble finding how to get the  button object from the dialog object. With ```filechooserdialog``` you do ```dialog->add_button``` so the object is of type ```dialog```?

**Comment by nickleus27** [comment]
@rodolforg right, the idea is to use ```"suggested-action"``` class and ```destructive-action "``` class for the ```action buttons``` in the ```filechooserdialogs```?

**Comment by nickleus27** [comment]
I have made an example app and have successfully added the "suggested-action" and "destructive-action" to the buttons. However, I am having trouble getting the button object from the ```filechooserdialog```.  I thought ```dialog->add_button()``` returns a button, but when I compile it says that the return type is ```void```.  Last question, should I be using ```xml``` for this like the gtk+demo example and the reference Rodolfo posted?

**Comment by rodolforg** [comment]
> Should I be using `xml` for this like the gtk+demo example and the reference Rodolfo posted?

No, you don't have to. Sometimes it could not be possible anyway
