### ISSUE TITLE
Missing skeleton tool

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2222]
**Describe the bug**
Latest stable version doesn't have skeleton tool in toolbox dock and toolbox menu.

**To Reproduce**
1. Open SynfigStudio
4. No skeleton tool in toolbox dock and menu

**Expected behavior**
Should have skeleton tool accessible both in dock and menu.

**Screenshots**
![Screenshot_2021-07-13_08-27-52](https://user-images.githubusercontent.com/24214509/125384474-9a776100-e3b6-11eb-9e8d-7c1aa08d6848.png)

**System information:**
 - OS: Fedora Linux
 - OS version: 34
 - Synfig version: 1.4.1

**Additional comments**
Skeleton tool is listed in Layers dock bottom toolbox **New Layer > Other > Skeleton** .

**Comment by ice0** [comment]
I'm not sure if it should be available in the 1.4 branch. 
ping @morevnaproject

**Comment by rodolforg** [comment]
>  Skeleton tool is listed in Layers dock bottom toolbox **New Layer > Other > Skeleton** .

This is not Skeleton Tool, but the Skeleton layer. It's available since some few stable versions ago.

Skeleton Tool implementation has a few consistent crashes. Maybe on next stable release 1.4.3…

**Comment by Keyikedalube** [comment]
> This is not Skeleton Tool, but the Skeleton layer.

Yikes! My mistake 😅 
Closing this issue because right now this is not relevant for stable releases.
