### ISSUE TITLE
Panel doesn't go further down.

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#2231]
synfig v1.4.2 windows 10 21h1

There are few panels I want to move a bit to the bottom, but it seems like they're locked to a particular minimum size which was not the case in older version of synfig. 
Please lower the minimum size of the those panels.

https://user-images.githubusercontent.com/50204208/126040293-93e7fa2e-2894-4e49-8fd9-bc93747a805e.mp4

**Comment by rodolforg** [comment]
Hm… I guess it was my fault with Sound Panel. Could you check by closing it please?

**Comment by yoSachinkr** [comment]
Yeah, it was because of the sound panel. I just checked it.

**Comment by dhruvdabhi101** [comment]
I would like to try this. Can you please tell me where should i start ? like a file or something that i can look into and further modify it. Thank You.

**Comment by rodolforg** [comment]
Look for dock_soundwave.h/cpp

**Comment by dhruvdabhi101** [comment]
Thank you :)
