### ISSUE TITLE
Issues With Naming/Renaming Layers if The 'Layers' Panel is Separated from Main Window

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#2254]
**Describe the bug**
When naming a layer from separated 'Layers' panel, instead of typing the letters in, Synfig will respond to shortcut keys if certain letter keys are pressed. I can select the names, but typing any of those letters just selects tools, or any other actions depend on which ones that they're assigned to.

**To Reproduce**
1. Drag the Layers panel out of the main window. The easiest way to do this is to just...... drag it out of the main window
2. Create a layer then select its name in 'Layers' panel to name or rename it
3. Try typing 'a', 'l', 'm', 's', 'g', or any other letters that are currently assigned to tools or actions.
4. The layer name stays selected and remains unchanged, but other behaviours occur instead, such as selecting other tools, etc.

**Expected behavior**
The layer name changes properly as you type in Any letters into it.

**Screenshots**
This setup should be enough to trigger the issue:
![layernamingbug](https://user-images.githubusercontent.com/25135159/127781252-e2df9376-7b0b-4c37-b726-399e537112ae.JPG)

**System information:**
Windows 10 64-bit, Synfig version: Stable 1.4.2 (both Installer and Portable version).

**Additional comments**
This issue only occurs with letters that have shortcuts tied to them, so any other letters that are NOT assigned to anything still work properly (such as 'n', 'x'',  etc.).
This issue doesn't exist in the previous Stable version (1.4.1).

**Comment by rodolforg** [comment]
The issue happens on AppImage too. It doesn't happen on master branch.

**Comment by rodolforg** [comment]
>     The easiest way to do this is to just...... drag it out of the main window

You can now right-click and select "Undock" too ;) But I prefer drag it out :D

**Comment by rodolforg** [comment]
This is the fix, I suppose: #1827

**Comment by morevnaproject** [comment]
Will use it for 1.4.3, thank you! ^__^

**Comment by rodolforg** [comment]
@morevnaproject  please add this for 1.4.3

**Comment by morevnaproject** [comment]
Done! Thank you! ^__^

**Comment by rodolforg** [comment]
Can we close this issue? @morevnaproject @FadhilKwan

**Comment by FadhilKwan** [comment]
@rodolforg Oh yeah, sure! I thought this was already closed long ago! :D
