### ISSUE TITLE
Dock area drop buttons are huge

### ISSUE THREAD

**Issue by caryoscelus** [synfig/synfig#227]
Just built a fresh synfig from master and dock area buttons are now this huge: 
![synfig-1](https://cloud.githubusercontent.com/assets/1758893/18312723/312875da-751c-11e6-8488-a360f309faca.png)
 Version info:

```
Development version:
Revision: 20160902
Branch: master
Revision ID: b297b1

Built on Sep  7 2016

Built with:
ETL 0.04.20
Synfig API (010002)
Synfig library 49
GTK+ 3.21.5
GNU G++ 6.2.0

Using:
Synfig 1.1.11
GTK+ 3.21.5
```

GTK themes: i tried Adwaita and Numix - both have this issue. Some themes that don't support gtk-3.20+ seem to not draw this buttons at all. For now i solved this problem by disabling this buttons, since i couldn't find a way to fix their size. But i suppose they're the only way to make new dock layouts now..
##

**Comment by sphaero** [comment]
Same here. Running on Debian Strech. Makes the UI unusable.
How did you disable these buttons?

**Comment by caryoscelus** [comment]
Simply commented them out.

https://github.com/caryoscelus/synfig/commit/b15a22afc87dcca52db52b736960a9a614ae41ef

**Comment by morevnaproject** [comment]
As temporary workaround you can use latest binary packages - https://gumroad.com/l/synfig-dev (there are no such issue there, because of older GTK bundled).

**Comment by Dragularos** [comment]
Hi there, I'm using MacOsX and i have no UI issues like these on my apple computer. But the whole program seems to be very slow. May I ask how many people are still developing or coding?

**Comment by morevnaproject** [comment]
Hello @Dragularos,

>  i have no UI issues like these

That's because OSX version is currently bundled with older GTK. ^__^

> the whole program seems to be very slow

I wonder, do you use development or stable version? Latest development should work faster for you -- https://gumroad.com/l/synfig-dev

> how many people are still developing or coding?

We have one hired developer, but right now we are completely out of funds to pay for his work. So, currently his work is bounty-based, like here - https://www.bountysource.com/issues/1372043-tremendous-memory-usage-when-importing-large-pngs

**Comment by caryoscelus** [comment]
http://www.synfig.org/forums/viewtopic.php?f=12&t=10085#p32062

Apparently the issue can be avoided by using Breeze theme.

**Comment by sphaero** [comment]
I can confirm this works:

    GTK_THEME=Breeze synfigstudio

You'll need the breeze theme installed

**Comment by mray** [comment]
Thank you for this awesome hint, i wasn't aware that you can easily start specific applications with different themes! ```GTK_THEME=Ambiance synfigstudio``` did the trick for me, too!

This bug is an annoyance still. :(

**Comment by caryoscelus** [comment]
Even though workaround works just fine, i still decided to fix this. Turned out to be pretty easy.

That said, i still wouldn't recommend using Adwaita for now, because it eats a lot of space elsewhere as well.
