### ISSUE TITLE
Synfig hangs on attempt to use Halftone 2 Layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2307]
**Describe the bug**
Any attempt to use Halftone 2 Layer results in Synfig hanging.

Synfig is built from source, master branch. The issue not happens on version 1.4.2.

**To Reproduce**
1. From menu select "Layer" -> "New Layer" -> "Filters" -> "Halftone 2"
2. New  "Halftone 2" layer created -> Synfig hangs.

**Expected behavior**
 "Halftone 2" layer should be correctly displayed don Workarea

**System information:**
 - OS: Linux
 - OS version: Mint 19
 - Commit ID: 96f9856dda598a3d6a5baeac557613ffe4708d04

**Comment by rodolforg** [comment]
`git bisect` point to 4273435309266fa4181269fdb3e9cc454cf14337

Wow o.O

**Comment by rodolforg** [comment]
The problem is the `abs` method. It is now from C library: int parameter and return value type...
https://github.com/synfig/synfig/blob/96f9856dda598a3d6a5baeac557613ffe4708d04/synfig-core/src/modules/mod_filter/halftone.cpp#L109-L136
