### ISSUE TITLE
Crash on unexporting value

### ISSUE THREAD

**Issue by caryoscelus** [synfig/synfig#231]
Steps to reproduce:
- export value
- connect to that value from another node of same layer
- unexport value while connected nodes are visible in parameters dock

There is a bit of variation on whether crash occurs or not. E.g. if file is saved & reloaded before unexporting, crash only happens when unexporting from library (i.e. not from parameters dock).

Error message doesn't seem to be very helpful, but anyway:

```
(synfigstudio:23776): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: ValueNode in ValueNodeList: xx
```

Sample file: http://my-files.ru/Save/wfl2t7/test-11-unexport.sifz
##

**Comment by rodolforg** [comment]
Here is how to reproduce it:
1. Create a new document
2. Create a `circle` layer anywhere
3. Select and right-click its `feather` parameter
4. In the context menu, select `Export value` and type any name
5. Show `Library` panel, expand `ValueBase Nodes`
6. Select the exported value
7. Select `Opacity` parameter and right-click on it
8. In the context menu, select `Connect`
9. Select back `feather` parameter
10. In `Library` panel, right-click on selected exported value
11. In the context menu, "Unexport"
12. Crash!

The "problem" : https://github.com/synfig/synfig/blob/fc7a046ad041978bf4071d1e15e6dc2e64176d4c/synfig-core/src/synfig/valuenode.cpp#L413

**Comment by rodolforg** [comment]
Fixed in master @ice0  @morevnaproject

**Comment by rodolforg** [comment]
The problem here is called by RendererDuck trying to render a duck of the exported valuenode, by using an invalid (outdated) ValueDesc: it refers to a valuenode name that doesn't exist anymore.

**Comment by morevnaproject** [comment]
Is it okay to close this now?

**Comment by ice0** [comment]
I think yes :)
