### ISSUE TITLE
1.5.0 - Individual tarballs?

### ISSUE THREAD

**Issue by limburgher** [synfig/synfig#2313]
Hi! I'm the Fedora package maintainer or synfigstudio, and we build from the individual tarballs for ETL, synfig, and synfigstudio. Will those be released soon?  Thank you!

**Comment by ice0** [comment]
Hi!
We did not prepare separate archives for 1.5.0 because it is an unstable version.

**Comment by limburgher** [comment]
Ah, ok. How long do you think it will be before the next stable release?

**Comment by ice0** [comment]
@morevnaproject found several bugs in 1.6, so it will be released when we fix them.
The planned release date is until the end of next month.

**Comment by limburgher** [comment]
Understood, thanks!
