### ISSUE TITLE
Importing image shows it upside-down

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#2328]
**Describe the bug**
On master branch, when importing a PNG, the TL-BR coordinates of Bitmap layer has the vertical component values swapped and image is vertically flipped.

**To Reproduce**
1. Open Import dialog
2. Unselect "Fit to Canvas"
3. Import any PNG image
4. See visual error in Canvas/WorkArea

**Expected behavior**
Work as before, not flipped.

**System information:**
 - OS: Linux - Debian
 - OS version: testing (pre-12, bookworm)
 - Commit ID: 5c930dc8a3d71f7bcba9d4b71deed297642baf74

**Additional comments**
I did a `git bisect` for investigation, and I found out this is the guilty commit: 5c930dc8a3d71f7bcba9d4b71deed297642baf74
I couldn't however identify the problem.

**Comment by morevnaproject** [comment]
Yes, we also hit that problem yesterday XD

**Comment by morevnaproject** [comment]
I wonder, is it somehow related to this condition? 🤔
![BD1A68C2-A03F-4BD2-B92C-D98775480CCF](https://user-images.githubusercontent.com/332868/134812602-d0e37290-ff61-4101-b9ec-471b913cb4e6.jpeg)
