### ISSUE TITLE
Does not show link to spline when trying to connect vertex to spline

### ISSUE THREAD

**Issue by bubutec** [synfig/synfig#2344]
**Describe the bug**
In Synfig version 1.0.2 this function works perfectly and makes it much easier when animating clothing designs with details that require this type of functionality.
Already in version 1.4.2 is not showing this function.

**To Reproduce**
1 - Create two drawings using the spline tool.
2 - select the two shapes you want to link.
3 - select the vertex you want to link the spline with.
4 - click with the right button of the mouse so that the context menu appears.

**Expected behavior**
See that the link to spline option does not appear in this version of Synfig Studio 1.4.2.
in version 1.0.2 it is working perfectly. 

**Screenshots**

**System information:**
 - OS version: Linux Kdeneon 5.22
 - Synfig version: 1.4.2

**Additional comments**

**Comment by yoSachinkr** [comment]
Even in v1.3.16 this feature used to work perfectly.

**Comment by morevnaproject** [comment]
It works in 1.4.0, but not in 1.4.1.

**Comment by morevnaproject** [comment]
The fix will be shipped in versions 1.4.3 and 1.5.1.

**Comment by morevnaproject** [comment]
Resolved in Synfig version 1.5.1 - https://www.synfig.org/2021/10/30/synfig-studio-1-5-1-released/
