### ISSUE TITLE
Link to correct issue/bug tracking

### ISSUE THREAD

**Issue by mray** [synfig/synfig#235]
It is not obvious (aside from the low number of issues) that this isn't the offical bug tracker.
There should be a prominent link to http://www.synfig.org/issues/thebuggenie/synfig probably.

**Comment by caryoscelus** [comment]
Only this seems to be new official bug tracker (see comments on http://www.synfig.org/issues/thebuggenie/issues/thebuggenie/synfig/issues/983). So i guess it's the other way around - link on Synfig development page should be changed.

**Comment by morevnaproject** [comment]
Fixed link at http://www.synfig.org/cms/en/development/. Thanks for note!

**Comment by mray** [comment]
Well in that case it might be sensible to link from github to the old bug tracker.
People should probably search there if something has been issued already.
Or maybe even import the old issues?

**Comment by morevnaproject** [comment]
> Or maybe even import the old issues?

Unfortunately, I don't have anyone who can handle this. The old bugtracker have a lot of outdated bugs, so the process is not straight-forward. For now it could be easier just shut down old tracker and see what issues get filled here.
