### ISSUE TITLE
Adjust Ruler font color to dark theme

### ISSUE THREAD

**Issue by mray** [synfig/synfig#236]
The ruler text color is way too bright for the dark theme and adds unwanted noise.
Reducing the brightness seems like a win.

**negative part is how it should look like imho:**

![iyrjquqc7m](https://cloud.githubusercontent.com/assets/164785/18853752/30e95ff0-8447-11e6-91f3-8ab1c48e996c.png)
##

**Comment by chrislondon** [comment]
Which operating system are you using. If you're using Ubuntu I believe you can tweak your own theme settings to get the desired affect.

The code uses old/deprecated functions and it could use a good overhaul to work with the new CSS-type styling.  Maybe I can take a crack at a rework that.

**Comment by mray** [comment]
Actually this is also relevant to the light theme.  I guess adding something like a 50% transparency  might be a general fix:

![selection_005](https://cloud.githubusercontent.com/assets/164785/18873537/3b58ff30-84c0-11e6-81cc-53e8f3da1f39.png)

**Comment by caryoscelus** [comment]
I think 50% might be too unreadable on some themes/color schemes, so set to 60% for now.

**Comment by caryoscelus** [comment]
Wanted to also add a "show rulers" toggle, but that will require some more effort and doc reading to do properly. Will return to it later.

**Comment by morevnaproject** [comment]
This fix now available in the latest development version - https://morevnaproject.org/2017/02/04/synfig-studio-1-3-1-development/
