### ISSUE TITLE
reveal tab placement crosses on mouse-over 

### ISSUE THREAD

**Issue by ghost** [synfig/synfig#238]
Those "tab placement crosses";

![selection_003](https://cloud.githubusercontent.com/assets/164785/18873569/6e47ed8e-84c0-11e6-90f8-59740c6968ab.png)

 add much to the high noise of the UI but is only needed when tabs are dragged. I propose to only make them visible upon dragging something on them  - _or_ - make them all visible only when anything starts getting dragged. 
##

**Comment by caryoscelus** [comment]
While it would be nice to hide them altogether when they are not required, latest fix makes them less noisy (as a side effect, actually), depending on theme. I.e. with Adwaita light:

![dockdroparea-light](https://cloud.githubusercontent.com/assets/1758893/22299107/5a511eec-e33c-11e6-86ef-811f64d850f1.png)

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
