### ISSUE TITLE
Don’t let `configure` filter out the compiler’s `-g` option to produce debug information

### ISSUE THREAD

**Issue by newbluemoon** [synfig/synfig#2392]
**Is your feature request related to a problem? Please describe.**
On Void Linux packages are built with gcc’s `-g` option to produce debug information which is then stripped into a separate package.

However, around line 85 in
https://github.com/synfig/synfig/blob/master/ETL/m4/subs.m4
https://github.com/synfig/synfig/blob/master/synfig-core/m4/subs.m4
https://github.com/synfig/synfig/blob/master/synfig-studio/m4/subs.m4
`ETL`, `synfig` and `synfig-studio` filter out that option if a debug build isn’t enabled. That leaves us either to enable debug mode and not have any optimizations or have no debug data at all.

We could patch the corresponding lines out when building the package, but it would be nice to not have to carry a patch around for this all the time.

**Describe the solution you'd like**
Do not filter out the `-g` option, like e.g.
```
--- a/m4/subs.m4	2021-07-12 17:45:48.000000000 +0200
+++ b/m4/subs.m4	2021-10-29 14:23:24.271523009 +0200
@@ -85,8 +85,8 @@
 		;;
 		no|*)
 			debug_flags="-DNDEBUG"
-			CXXFLAGS="`echo $CXXFLAGS | sed 's:-g[[a-z-]]*\s::g' | sed 's:-g[[a-z-]]*$::'` $debug_flags"
-			CFLAGS="`echo $CFLAGS | sed 's:-g[[a-z-]]*\s::g' | sed 's:-g[[a-z-]]*$::'` $debug_flags"
+			CXXFLAGS="$CXXFLAGS $debug_flags"
+			CFLAGS="$CFLAGS $debug_flags"
 		;;
 	esac
``` 

**Describe alternatives you've considered**

**Additional comments**
Maybe there is a good reason for this behaviour which I don’t get right now, but I think someone who is using these flags does so for a specific reason.

Anyway, I just had to ask and thank you in advance for any insights.

**Comment by ice0** [comment]
@newbluemoon 

Hi! Sorry for a late answer.

> Maybe there is a good reason for this behaviour which I don’t get right now, but I think someone who is using these flags does so for a specific reason.

This was done a very long time ago because some user experienced problems building the release version. 
Now no one remembers the details, so let's see if anyone has issues with it again.

Thanks for your help.
