### ISSUE TITLE
Unable to execute plugins

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#2393]
**Describe the bug**
Unable to execute plugin. Synfig throws the following error.
![image](https://user-images.githubusercontent.com/50204208/139531896-45a5e2a3-4d67-425f-8cc6-f7a3bbdce6ae.png)

**Expected behavior**
Plugins should execute.

**System information:**
 - OS: windows 10 21h2
 - OS version: 64bit
 - Commit ID: SynfigStudio-1.5.1-2021.10.21-win64-2cb6c

ps: I.m using zip package and using synfigstudio.bat to open synfig.

**Comment by rodolforg** [comment]
Working normally in Synfig AppImage 1.5.1

@morevnaproject Is it a bundling issue?

**Comment by ice0** [comment]
> Working normally in Synfig AppImage 1.5.1
> 
> @morevnaproject Is it a bundling issue?

Yes. I don't know why, but `${MINGW_BIN}/gspawn-win??-helper.exe` is missing. You need to add it to the archive.

**Comment by BobSynfig** [comment]
The binary is named as gspawn-win64-helper<b>-console</b>.exe (or gspawn-win32-helper<b>-console</b>.exe)
 It can be renamed gspawn-win64-helper.exe (in /bin under Synfig's install directory) and it will work, but there is another bug appearing then:
Plugin execution failed: Failed to execute child process (invalid argument)...

**Comment by ice0** [comment]
> Please check testing build - [SynfigStudio-1.4.3-testing-2022.04.05-win64-71775.exe](https://cloud.morevnaproject.org/s/NrH2Dx8DFL4dtNT)

Works without any issues.
