### ISSUE TITLE
Windows version: No pressure sensitivity

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#241]
Pressure sensitivity of graphic tablet isn't working in Windows version.
##

**Comment by Foxbud** [comment]
Just to add my experience to this... After messing around with settings, I was able to get tablet sensitivity, but anything I drew would be offset up and to the left of the cursor. There is no offset when sensitivity is disabled.

**Comment by morevnaproject** [comment]
@Foxbud  Thank you for posting a bounty for this! Can you please let me know the model of your tablet. Also, what settings did you used to make pressure sensitivity to work? (screenshot of "Input Devices" dialog will help). Thanks!

**Comment by morevnaproject** [comment]
To anyone interested: 
I would appreciate if you help to spread a word about the bounty. Maybe someone will want to join and pitch the reward amount to get it fixed sooner. Bounty page - https://www.bountysource.com/issues/38212106-windows-version-no-pressure-sensitivity

**Comment by Foxbud** [comment]
Yeah, no problem.

I'm using a Huion H610pro. When I first start Synfig, the tablet allows me to draw normally, but the spline is of a constant thickness regardless of the pressure I apply. When I go into the input dialog, I see this:
![idialog](https://cloud.githubusercontent.com/assets/18452764/22650802/b3da24ac-ec4e-11e6-8465-1e45ecca914d.png)

My first suspicion on seeing the Huion driver listed twice was that I did not install the driver itself correctly, so I reinstalled it and I still had two drivers in the list. The first instance of the driver does not appear to affect anything, but the second driver, once set to "Screen", does make pressure sensitivity work, but everything I draw will appear offset up and to the left of my cursor as this GIF displays:
![offset](https://cloud.githubusercontent.com/assets/18452764/22650969/46085ace-ec4f-11e6-9e83-27a38b64c7af.gif)

To make sure it was Synfig and not my tablet that was causing the issue, I tried to use it in another pressure sensitive drawing program, FireAlpaca, and it worked as intended.

I'm using Windows 10 and the latest version of the Huion H610pro driver (v 6.1.7600.16385). This bug appears in both Synfig 1.2.0 and the dev version 1.3.0-20170114.

Thanks for taking a look into this bug!

**Comment by caryoscelus** [comment]
To make sure the issue is with Synfig and not Gtk3/windows, you can check whether MyPaint works for you.

**Comment by caryoscelus** [comment]
@Foxbud , also: i suppose all tools (e.g. spline, circle, etc) have this offset, not just freehand drawing?

**Comment by Foxbud** [comment]
@caryoscelus, I tried out MyPaint, and its tracking and pressure sensitivity for my tablet are working fine. And yes, all the tools I use have this offset once the driver is enabled in the input dialog.

**Comment by caryoscelus** [comment]
Hmm, this is a really weird one, but i can occasionally reproduce it - it seems tablet devices works only after initial startup and then virtual pointer takes priority. I have no idea how to debug it, though, being unable to build for windows.

**Comment by caryoscelus** [comment]
One possible reason why it works on gnu/linux and doesn't work on windows is that device switching is broken, but it's not really used on linux (pressure works with just "virtual core pointer" device and no device switch events are registered). I wonder if we really need CanvasView::on_input_device_changed. Would be nice if someone would try https://github.com/caryoscelus/synfig/tree/input_investigation on windows.

**Comment by morevnaproject** [comment]
Assigned to @blackwarthog, he can debug this on windows.

**Comment by blackwarthog** [comment]
Seems graphic tablet gtk-devices represented differently in windows and linux. In windows axis coordinates are relative (against absolute in linux).

**Comment by morevnaproject** [comment]
@Foxbud Thanks for detailed instructions, I also got my Wacom tablet working on Win.

@blackwarthog Can you please provide build for testing. ^__^

**Comment by blackwarthog** [comment]
This is 64-bits version, 32-bits will coming soon
http://icystar.com/downloads/synfigstudio-1.3.1-20170202-64bit-fix.exe

**Comment by blackwarthog** [comment]
And 32-bits
http://icystar.com/downloads/synfigstudio-1.3.1-20170202-64bit-fix.exe

**Comment by Foxbud** [comment]
@morevnaproject Of course, I'm glad to hear it!

@blackwarthog Thanks for the fix! The 64-bit download is working great so far.

**Comment by morevnaproject** [comment]
The fix now shipped with latest development builds - https://morevnaproject.org/2017/04/23/synfig-studio-1-3-2-development/

**Comment by dmyger** [comment]
Windows 10 Pro
synfigstudio-1.3.2-20170408-64bit.exe
Tablet XP-Pen G540
Synfig now crushed just on first touch the drawing pen in any area of program.
Previous version does not work correctly, but at least had not crashed on any manipulations with the pen on the same tablet.

**Comment by morevnaproject** [comment]
The discussion of crash of Tablet XP-Pen is here #351
