### ISSUE TITLE
`Esc` should cancel the in-going edition of a layer parameter value

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig#2411]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm typing a new value for a parameter and I gave up on this edition, but I can't cancel it by keyboard.

**Describe the solution you'd like**
By pressing `Esc` I should be able to cancel my in-going edition on the Value column of the Parameters Panel as I'm able to when editing a layer name in the Layers Panel.

**Comment by nickleus27** [comment]
Hi @rodolforg ! Is anyone working on this issue? If not I am interested.

**Comment by ice0** [comment]
Hi @nickleus27!
Assigned it to you.

**Comment by nickleus27** [comment]
@ice0 I am looking in ```layertree.cpp``` with no luck.  Also, the only ```GDK_KEY_Escape``` case is in ```state_bline.cpp``` in the ```event_key_release_handler``` method, and in ```selectdraghelper.h``` in the ```process_key_release_event``` method.  I cannot see how these methods connect with the layer_tree?

**Comment by ice0** [comment]
I think Rodolfo wrote about this panel:

![Screenshot_2](https://user-images.githubusercontent.com/5604544/144701312-f056f046-73b3-46b5-bd93-9382508f903a.png)

it should be located in the `dock_params.cpp` file. 

> Also, the only GDK_KEY_Escape case is in state_bline.cpp in the event_key_release_handler method, and in selectdraghelper.h in the process_key_release_event method. I cannot see how these methods connect with the layer_tree?

I think the `Esc` key is currently not connected to this panel and that is the reason why you cannot find it. 
As for me it's best to start with a simple `gtkmm` app here, just to test how it works out of the box. 
Also you can check the `gtk-demo` application, it should be located in `/opt/homebrew/bin/gtk3-demo`.

**Comment by nickleus27** [comment]
@ice0 awesome, will do.  This will help get me going 👍

**Comment by nickleus27** [comment]
Hi @rodolforg !  ice0 recommended i look in ```dock_params.cpp``` in regards to this issue.  After looking there for a while I ended up in ```cellrenderer_value.cpp``` .  Any advice if I am looking in the right area on this issue?  I see that ```on_editing_done()``` in ```cellrenderer_value.cpp```  is called when the you press enter in the "value" cell of the param table.  But, it does not respond when you press esc.

**Comment by nickleus27** [comment]
@ice0 I have been looking over the gtk3-demo.  I have been looking at the editable cells demo, and the GtkCellRenderer::editing-started signal.  I am having a hard time figuring out why the cell responds to say the "return" key but not the "escape" key in the param "value" column in synfig.

**Comment by ice0** [comment]
@nickleus27 

Please check `bool on_event(GdkEvent *event)` method (`cellrenderer_value.cpp`). It looks like it stopping propagation of the event.

P.S. Rodolfo wrote that he will be busy at work for a while, this is the reason why he doesn't respond.

**Comment by nickleus27** [comment]
@ice0 Thank you for your response. The GDK_KEY_RELEASE gets triggered when you press `esc` in the ```bool on_event(GdkEvent *event)``` method but it does not trigger ```void on_editing_done()``` method in the same class.  This issue might be out of the scope of my understanding.  It is not clear to me how ```on_editing_done()``` is called from ```on_event(*event)```

**Comment by nickleus27** [comment]
I guess it gets called from ```signal_edited()``` ?

**Comment by rodolforg** [comment]
Hi @nickleus27 sorry my absence, I'm really 'suffocated' with my job due to end of year.
But take a look here https://github.com/synfig/synfig/issues/1208, maybe it helps you.

**Comment by nickleus27** [comment]
@rodolforg Thank you for your response, this definitely helps.

**Comment by nickleus27** [comment]
I am still having a hard time understanding how program branches to ```on_editing_done()``` or ```on_value_editing_done()``` from what I think it ```on_event(Gdk::Event *event)``` after reading issue #1208 .

**Comment by rodolforg** [comment]
Several (all?) gtk signal callbacks/slots that are supposed to return a bool value that, if true, means the event shouldn't handled anywhere else - you did what it should be done. 

The `on_event` is a general signal slot (for 'any' event signal), `on_key_press_event` is specific for key-press signal. So, `on_event`, yes,, can be used to handle the key-press signal.

The Esc key pressing should call the editing_canceled signal. https://docs.gtk.org/gtk3/signal.CellRenderer.editing-canceled.html

**Comment by ice0** [comment]
> I have been looking over the gtk3-demo. I have been looking at the editable cells demo, and the GtkCellRenderer::editing-started signal. I am having a hard time figuring out why the cell responds to say the "return" key but not the "escape" key in the param "value" column in synfig.

This is the expected behavior ([docs](https://developer-old.gnome.org/gtkmm/3.24/classGtk_1_1CellEditable.html#a1d284887ce7c17b68e6e996e5a17db1d)).

> Implementations of Gtk::CellEditable are responsible for emitting this signal when they are done editing, e.g. Gtk::Entry emits this signal when the user presses Enter. Typical things to do in a handler for signal_editing_done() are to capture the edited value, disconnect the cell_editable from signals on the Gtk::CellRenderer, etc.

Unfortunately, they didn't describe how to intercept the Esc key, so it just should work out of the box. 
I think the reason it doesn't work is because it is not a standard widget in Synfig. 
As you may notice in `CellRenderer_ValueBase::start_editing_vfunc`:

https://github.com/synfig/synfig/blob/d37e72ac3dcb42bbf64deb0ae6b9d1c90649f229/synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp#L654-L663

Here Synfig creates a new `ValueBase_Entry` widget and display it on top of the standard cell widget.
So this widget just doesn't know how to handle keypress events.

Also, if you check the `ValueBase_Entry` code, you will notice the interesting part here: 

https://github.com/synfig/synfig/blob/d37e72ac3dcb42bbf64deb0ae6b9d1c90649f229/synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp#L85-L91

I mean the commented `set_events(...)` code. It looks like this work is not finished here. 
Hope this helps.

**Comment by nickleus27** [comment]
@ice0 @rodolforg thanks guys. This is really helpful information.

**Comment by nickleus27** [comment]
@ice0 Lol, I have most of the value EventBox's escaping now except when the the EventBox has the Value type of real. Trying to figure that out at the moment.

**Comment by rodolforg** [comment]
Closed by #2455

**Comment by rodolforg** [comment]
Thank you, @nickleus27 ! :)

**Comment by nickleus27** [comment]
Thank you @rodolforg
