### ISSUE TITLE
build.sh auto thread count detection?

### ISSUE THREAD

**Issue by b-aaz** [synfig/synfig#2412]
**Is your feature request related to a problem? Please describe.**
It takes aloooooot of time to compile 
**Describe the solution you'd like**
So in the build.sh in autobuild directory line 54 we have 
`MAKE_THREADS=2				#count of threads for make
`
And I actually didn't know this variable existed for along time and I think meny other people don't know it too So can the script get the value from /proc/cpuinfo or nproc or ls cpu?
I reduced my compile time from 23mins to 13 mins!🤯
**Describe alternatives you've considered**
Maybe including this variable in build tutorial and Readme will  be a good idea 😄
**Additional comments**
If nproc or lscpu will be used they should be added to build time dependencys

**Comment by ice0** [comment]
Hi!

Thank you for a response. To increase the number of build threads, you can use the `build.conf` file. 
It is already described here: https://synfig-docs-dev.readthedocs.io/en/latest/building/Building%20using%20Autotools.html

> And finally a quick note about “build.conf.sample” file in the root of source repository.
>
> With this file you can tweak the number of threads used by the build scripts. Just copy “synfig.git/build.conf.sample” to “synfig.git/build.conf” and adjust its contents according to your needs.

Have you seen this instruction? 
Maybe move this section to the beginning? Or add it to the readme file?

**Comment by morevnaproject** [comment]
Woah! That's the feeling when you are the person who wrote that thing with  “build.conf.sample” and forgot that.
I was building with 2 threads last months! XD
