### ISSUE TITLE
Can't reopen saved file if bone linked to bone, fixed by moving <defs> before <bones>

### ISSUE THREAD

**Issue by clawsoon** [synfig/synfig#2415]
If I:

 - create two unconnected bones,
 - export Local Length Scale from one bone as BoneLength,
 - use the exported value in the other bone, then
 - save the file,

Synfig is not able to re-open the saved file, failing with:

"Unable to load [path to file]: &lt;bone&gt;:55:error: Unable to resolve BoneLength"

The file can be rescued by opening it in a text editor and moving the &lt;defs&gt; section before the &lt;bones&gt; section.

I have attached example buggy and fixed files.  The problem seems to occur reliably.

System info:

Windows 7
1.5.1 download from:
https://www.fosshub.com/Synfig-Development.html
$ md5sum.exe SynfigStudio-1.5.1-2021.10.21-win64-2cb6c.exe
6de9523e783fb9eabb4a6a33d0dc0f1a *SynfigStudio-1.5.1-2021.10.21-win64-2cb6c.exe

**Comment by clawsoon** [comment]
[bug.zip](https://github.com/synfig/synfig/files/7534720/bug.zip)

**Comment by rodolforg** [comment]
Related to #362

**Comment by clawsoon** [comment]
Ah, yes, that appears to be exactly the same problem.  I see from that bug that simply swapping the order of defs and bones isn't enough, since that creates a different problem.
