### ISSUE TITLE
Wider time track space at start and end

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2417]
This issue continues #1145 and PR #2400. ^__^

It would be nice to have wider margins at the start at at the end of timetrack.

The PR #2400 sets extra margin = 3px.
And it is easy to make it wider, just by changing one line of code.
I have set it to 8px and it looks nice.

But after changing margin to 8px there is a problem appears: now it allows to drag waypoint from frame 0 to frame -1 or -2.
This can be confusing for user.

![screenshot_003](https://user-images.githubusercontent.com/332868/141808834-fd95a3a5-82b7-41e5-be76-02a50969f925.png)

Video - https://youtu.be/lwuFQxbO-LE

Is there a possibility to add check like this? - "if user grabs at frame 0, then forbid dragging in negative direction".
Or maybe other solutions?

**Comment by rodolforg** [comment]
Only 0 or any time lower than current minimum time (set in Canvas properties)?
