### ISSUE TITLE
Synfig hangs when text layer created (windows version)

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#242]
Tested on Synfig dev build (synfigstudio-1.1.11-20160727-32bit.exe).
##

**Comment by Darkspace65** [comment]
Works on Synfig dev build (synfigstudio-1.1.11-20160727-64bit.exe) on Windows 10.

**Comment by morevnaproject** [comment]
@Darkspace65 Can you please check if it is possible to change fonts in Windows version, according to this tutorial - https://morevnaproject.org/2016/09/08/set-font-style-synfig/

**Comment by Darkspace65** [comment]
@morevnaproject Yep. That works. You have to save your sif file first though, but after that all goes well.

**Comment by morevnaproject** [comment]
Thank you for testing! ^__^

**Comment by morevnaproject** [comment]
I found what was the problem. When you use the text tool for first time after Synfig got installed, then it  will freeze for a few minutes. I suspect it does some font initialization - i.e. creates a font cache for your system. Just wait until the application start responding again (you will see a text layer appeared on workarea when this happens).

When you will use Text Tool next time there is no delay should happen.

I remember GIMP also starts very long for the first time because it creates font cache. Maybe we also have to do that as separate initialization stage at  first start.
