### ISSUE TITLE
Titles next to dockers' icons take up a lot of space.

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#2426]
**Describe the bug**
Titles next to docker icons take up a lot of space unnecessarily that takes away the size of the workspace.

**Expected behavior**
Dockers should display the title and icon only when given considerable width by resizing the docker

**Screenshots**
![synfigdockerstitle](https://user-images.githubusercontent.com/45057390/142481913-546c2ac1-07ab-46b8-97b3-c4cbb5b0fc03.png)

**System information:**
 - OS: Arch Linux x64
 - Commit ID: 27ea632ec8b214ccdbc37034dcda563672010a1d

**Additional comments**
I respectfully suggest that the title is only displayed if the docker width is resized.

Thank you so much for improving Synfig every day.

Excellent work :).

**Comment by ice0** [comment]
Fixed in https://github.com/synfig/synfig/pull/2436

**Comment by Gilraiser** [comment]
Muchas gracias,
