### ISSUE TITLE
Add Snap ability to waypoints like snap to guide

### ISSUE THREAD

**Issue by Bala621** [synfig/synfig#2427]
In the latest version, we can easily handle waypoints (duplicate,move,scale) except one think ( snap with timeline cursor option ) 

 Because sometimes we have to work with long animation project and also many waypoints that time we have to resize the timeline panel to minimum with ctrl+shift+(-). If we want to change a location of waypoint position to exact frame or sec, we must zoom it again ctrl+shift+(+) because all waypoints look like small in minimize state and we cannot drag it exact position without zooming it.

 If waypoint have snap option, we dont need zoom it again whenever we want to relocate waypoints. 
  
 Because in my last animation https://youtu.be/CR9fdhbLbEI i have faced this problem. 

 And also it will be very usefull for make long walkcycle animation ( without using timeloop )
 
  I think, if add snap option to waypoint like snap to guide it will be much better. Any other opinion?

**Comment by ice0** [comment]
@Bala621 
Hi!
Why did you close this issue? Have you found a solution for this?
