### ISSUE TITLE
In the ToolBox tab, the color selection window does not keep his position saved.

### ISSUE THREAD

**Issue by ghost** [synfig/synfig#243]
I set the program interface to my liking and put the ToolBox tab at the top left and under this the options tool window. But when I start Synfig again, the window of color selection moves and is underhanded.

![synfig_01](https://cloud.githubusercontent.com/assets/20951035/19008241/18b18dec-876a-11e6-861a-ca9794f4c477.jpg)

![synfig_02](https://cloud.githubusercontent.com/assets/20951035/19008245/1e1dd6f0-876a-11e6-9e1a-2702228d8cbe.jpg)
##

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
