### ISSUE TITLE
AppImage Not Working On Fedora

### ISSUE THREAD

**Issue by THEBATEZIOPARKER** [synfig/synfig#2434]
I am Using Fedora 35, Synfig Studio 1.4.2 AppImage is Not Working
Even The Development Version Is Not Working!!!!!!!!
I Am Getting This Error :-
https://user-images.githubusercontent.com/87817029/142832957-ed43b6c1-15a7-41f2-b8e7-08fcc99bdcb7.png

PLEASE HELP !!!!!!!!!!!!

**Comment by rodolforg** [comment]
Related to #2397

**Comment by ice0** [comment]
@THEBATEZIOPARKER 
Can you try flatpak version?
1.4.1 - on main channel and 1.5.1 is on beta channel.

**Comment by THEBATEZIOPARKER** [comment]
@ice0 
I have been using Flatpak until Yesterday,
In the Flatpak Version Using The Draw-Tool, Synfig-Studio Crashes (From The Main Channel)
Need To try from the Beta Channel
