### ISSUE TITLE
Animation doesn´t appears correctly on canvas

### ISSUE THREAD

**Issue by ghost** [synfig/synfig#244]
Well, what happens is that I'm starting with the Step by Step Manual (http://wiki.synfig.org/Doc:Animation_Basics) and in the first practice I have a strange behavior when playing the animation on the canvas own.

This is the first animation of the manual where a circle moves to right and returns to the left. Well, when the animation reaches the end (2s) the animation sometimes does not reach your site. This occurs under Windows and Linux and on two different computers.

I uploaded a video on YouTube to better illustrate it:

https://youtu.be/ioDeQmfTN-k
##

**Comment by mray** [comment]
Did you try moving the last waypoint one frame forwards?
Could be that Synfig allows you to select/use the last frame which would actually be the first frame outside your time limit.

**Comment by MLCasellas** [comment]
mray, thank you. Yeah, I tried and did not work. It's funny, when you select the circle layer this happens:

![synfig_report_005](https://cloud.githubusercontent.com/assets/20951035/19628711/4cef4a84-9964-11e6-86e4-c474c625e348.jpg)

**Comment by mray** [comment]
Looks like some kind of offset - can you post the project file?

**Comment by MLCasellas** [comment]
Of course...

[sp001_red_animated_point.sifz.zip](https://github.com/synfig/synfig/files/546567/sp001_red_animated_point.sifz.zip)

**Comment by mray** [comment]
Works fine here. My guess is that it will probably render correctly if you export a video. It might be your preview settings that reduce the framerate for better performance. Did you try zooming in on the error to see if a redraw fixes the display?

**Comment by MLCasellas** [comment]
Yes, render and preview works fine. 

I tryed zoom and low res and continues the issue. In Windows 7, Xubuntu 16.04LTS and in 2 laptops. Well, it's strange then...

**Comment by MLCasellas** [comment]
If is a valuable infro, the both graphics cards are ATI.

**Comment by MLCasellas** [comment]
Well, a dual graphics: Intel/ATI

**Comment by caryoscelus** [comment]
Seem to work fine for me as well. Which version of Synfig are you using?

**Comment by MLCasellas** [comment]
Development version 1.1.11 But also occurs me with the stable 1.0.2

**Comment by ice0** [comment]
Works as expected on 1.4.0, so I close it now.
