### ISSUE TITLE
Flatpak Version Of Synfig-Studio Is Crashing When Using The Draw Tool !!!!!!

### ISSUE THREAD

**Issue by THEBATEZIOPARKER** [synfig/synfig#2446]
Flatpak Version of Synfig-Studio is crashing when using the draw tool !!!!!!!
I have Tried in Fedora,Manjaro,Ubuntu And Arch, Flatpak Version is Crashing in All These Distros, Every Time It Crashes When Using The Tool.

While Running From Terminal Is Shows :-

❯ flatpak run org.synfig.SynfigStudio

   synfig studio -- starting up application...

Gtk-Message: 07:53:56.995: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:53:56.995: Failed to load module "pk-gtk-module"
Gtk-Message: 07:53:57.128: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:53:57.128: Failed to load module "pk-gtk-module"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Sound"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Types"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Rendering"
synfig(2) [07:53:58 AM] info: rendering threads 4
synfig(2) [07:53:58 AM] info: Starting Subsystem "Modules"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Layers"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Targets"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Importers"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Cairo Importers"
synfig(2) [07:53:58 AM] info: Starting Subsystem "Thread Pool"
synfig(2) [07:53:58 AM] warning: Cannot open ./synfig_modules.cfg
synfig(2) [07:53:58 AM] warning: Cannot open /home/Bruce/.local/share/synfig/synfig_modules.cfg
synfig(2) [07:53:58 AM] info: Loading modules from /app/etc/synfig_modules.cfg
synfig(2) [07:53:58 AM] info: Loading modules from /app/etc/synfig_modules.cfg
synfig(2) [07:53:58 AM] info: Loading lyr_std..
synfig(2) [07:53:58 AM] info: Attempting to register "lyr_std"
synfig(2) [07:53:58 AM] info: Found module "lyr_std"
synfig(2) [07:53:58 AM] info: Success for "lyr_std"
synfig(2) [07:53:58 AM] info: Loading lyr_freetype..
synfig(2) [07:53:58 AM] info: Attempting to register "lyr_freetype"
synfig(2) [07:53:58 AM] info: Found module "lyr_freetype"
synfig(2) [07:53:58 AM] info: Initializing FreeType...
synfig(2) [07:53:58 AM] info: Success for "lyr_freetype"
synfig(2) [07:53:58 AM] info: Loading mod_geometry..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_geometry"
synfig(2) [07:53:58 AM] info: Found module "mod_geometry"
synfig(2) [07:53:58 AM] info: Success for "mod_geometry"
synfig(2) [07:53:58 AM] info: Loading mod_gradient..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_gradient"
synfig(2) [07:53:58 AM] info: Found module "mod_gradient"
synfig(2) [07:53:58 AM] info: Success for "mod_gradient"
synfig(2) [07:53:58 AM] info: Loading mod_particle..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_particle"
synfig(2) [07:53:58 AM] info: Found module "mod_particle"
synfig(2) [07:53:58 AM] info: Success for "mod_particle"
synfig(2) [07:53:58 AM] info: Loading mod_example..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_example"
synfig(2) [07:53:58 AM] info: Found module "mod_example"
synfig(2) [07:53:58 AM] info: Success for "mod_example"
synfig(2) [07:53:58 AM] info: Loading mod_gif..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_gif"
synfig(2) [07:53:58 AM] info: Found module "mod_gif"
synfig(2) [07:53:58 AM] info: Success for "mod_gif"
synfig(2) [07:53:58 AM] info: Loading mod_imagemagick..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_imagemagick"
synfig(2) [07:53:58 AM] info: Found module "mod_imagemagick"
synfig(2) [07:53:58 AM] info: Success for "mod_imagemagick"
synfig(2) [07:53:58 AM] info: Loading mod_magickpp..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_magickpp"
synfig(2) [07:53:58 AM] info: Found module "mod_magickpp"
synfig(2) [07:53:58 AM] info: Success for "mod_magickpp"
synfig(2) [07:53:58 AM] info: Loading mod_mng..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_mng"
synfig(2) [07:53:58 AM] warning: Unable to find module "mod_mng" (file not found)
synfig(2) [07:53:58 AM] info: Loading mod_noise..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_noise"
synfig(2) [07:53:58 AM] info: Found module "mod_noise"
synfig(2) [07:53:58 AM] info: Success for "mod_noise"
synfig(2) [07:53:58 AM] info: Loading mod_filter..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_filter"
synfig(2) [07:53:58 AM] info: Found module "mod_filter"
synfig(2) [07:53:58 AM] info: Success for "mod_filter"
synfig(2) [07:53:58 AM] info: Loading mod_ffmpeg..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_ffmpeg"
synfig(2) [07:53:58 AM] info: Found module "mod_ffmpeg"
synfig(2) [07:53:58 AM] info: Success for "mod_ffmpeg"
synfig(2) [07:53:58 AM] info: Loading mod_bmp..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_bmp"
synfig(2) [07:53:58 AM] info: Found module "mod_bmp"
synfig(2) [07:53:58 AM] info: Success for "mod_bmp"
synfig(2) [07:53:58 AM] info: Loading mod_dv..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_dv"
synfig(2) [07:53:58 AM] info: Found module "mod_dv"
synfig(2) [07:53:58 AM] info: Success for "mod_dv"
synfig(2) [07:53:58 AM] info: Loading mod_png..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_png"
synfig(2) [07:53:58 AM] info: Found module "mod_png"
synfig(2) [07:53:58 AM] info: Success for "mod_png"
synfig(2) [07:53:58 AM] info: Loading mod_ppm..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_ppm"
synfig(2) [07:53:58 AM] info: Found module "mod_ppm"
synfig(2) [07:53:58 AM] info: Success for "mod_ppm"
synfig(2) [07:53:58 AM] info: Loading mod_openexr..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_openexr"
synfig(2) [07:53:58 AM] info: Found module "mod_openexr"
synfig(2) [07:53:58 AM] info: Success for "mod_openexr"
synfig(2) [07:53:58 AM] info: Loading mod_jpeg..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_jpeg"
synfig(2) [07:53:58 AM] info: Found module "mod_jpeg"
synfig(2) [07:53:58 AM] info: Success for "mod_jpeg"
synfig(2) [07:53:58 AM] info: Loading mod_libavcodec..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_libavcodec"
synfig(2) [07:53:58 AM] info: Found module "mod_libavcodec"
synfig(2) [07:53:58 AM] info: Success for "mod_libavcodec"
synfig(2) [07:53:58 AM] info: Loading mod_yuv420p..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_yuv420p"
synfig(2) [07:53:58 AM] info: Found module "mod_yuv420p"
synfig(2) [07:53:58 AM] info: Success for "mod_yuv420p"
synfig(2) [07:53:58 AM] info: Loading mod_svg..
synfig(2) [07:53:58 AM] info: Attempting to register "mod_svg"
synfig(2) [07:53:58 AM] info: Found module "mod_svg"
synfig(2) [07:53:58 AM] info: Success for "mod_svg"
synfig(2) [07:53:58 AM] info: DONE
synfig(2) [07:53:58 AM] info: Loading Basic Settings...
synfig(2) [07:53:58 AM] info: Loading Plugins...
synfig(2) [07:53:58 AM] info: Loading plugins from /app/share/synfig/plugins
synfig(2) [07:53:58 AM] info:    Loading plugin: add-skeleton-simple
synfig(2) [07:53:58 AM] info:    Loading plugin: lottie-exporter
synfig(2) [07:53:58 AM] info:    Loading plugin: view-unhide-all-layers
synfig(2) [07:53:58 AM] info: Loading plugins from /home/Bruce/.config/synfig/plugins
synfig(2) [07:53:58 AM] info: Init UI Manager...
synfig(2) [07:53:58 AM] info: Init Dock Manager...
synfig(2) [07:53:58 AM] info: Init State Manager...
synfig(2) [07:53:58 AM] info: Init Main Window...
synfig(2) [07:53:58 AM] info: Init Toolbox...
synfig(2) [07:53:58 AM] info: Init About Dialog...
synfig(2) [07:53:58 AM] info: Init Tool Options...
synfig(2) [07:53:58 AM] info: Init History...
synfig(2) [07:53:58 AM] info: Init Canvases...
synfig(2) [07:53:58 AM] info: Init Keyframes...
synfig(2) [07:53:58 AM] info: Init Layers...
synfig(2) [07:53:58 AM] info: Init Parameters...
synfig(2) [07:53:58 AM] info: Init MetaData...
synfig(2) [07:53:58 AM] info: Init Library...
synfig(2) [07:53:58 AM] info: Init Info...
synfig(2) [07:53:58 AM] info: Init Navigator...
synfig(2) [07:53:58 AM] info: Init SoundWave...
synfig(2) [07:53:59 AM] info: Init Timetrack...
synfig(2) [07:53:59 AM] info: Init Curve Editor...
synfig(2) [07:53:59 AM] info: Init Layer Sets...
synfig(2) [07:53:59 AM] info: Init Color Dialog...
synfig(2) [07:53:59 AM] info: Init Gradient Dialog...
synfig(2) [07:53:59 AM] info: Init DeviceTracker...
synfig(2) [07:53:59 AM] info: Init ModPalette...
synfig(2) [07:53:59 AM] info: Init Setup Dialog...
synfig(2) [07:53:59 AM] info: Init Input Dialog...
synfig(2) [07:53:59 AM] info: Loading Custom Workspace List...
synfig(2) [07:53:59 AM] info: Init auto recovery...
synfig(2) [07:53:59 AM] info: Loading Settings...
synfig(2) [07:54:00 AM] info: Init Tools...
synfig(2) [07:54:00 AM] info: Checking auto-recover...
synfig(2) [07:54:00 AM] info: Done.
/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = synfig::Vector; _Alloc = std::allocator<synfig::Vector>; std::vector<_Tp, _Alloc>::reference = synfig::Vector&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

**Comment by ice0** [comment]
@THEBATEZIOPARKER 
Can you check this build:

`flatpak install --user https://dl.flathub.org/build-repo/66106/org.synfig.SynfigStudio.flatpakref`

**Comment by THEBATEZIOPARKER** [comment]
This Works!!!!!!!!!!!!!!!!!!!!!!!
THANKS A LOT

**Comment by ice0** [comment]
@THEBATEZIOPARKER 
Thanks for testing it.
