### ISSUE TITLE
Distortions at the end of lines made with the drawing tool

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#2448]
**Describe the bug**
The drawing tool generates a distortion at the end of the drawing that is made. The error occurs when the contour, region and advanced contour options are activated, whether they are used alone or at the same time.

**To Reproduce**
1. Click on the drawing tool.
2. Draw any shape with long click.
3. Finish the form by releasing the click.
4. The error can be seen at the end of the line in the drawing.

**Expected behavior**
It is true that, depending on the modifications that the tool has had, certain variations to what is drawn are expected, such as smoothness. But you would expect the tangent and vertex handles to not get so tangled in the end.

**Screenshots**

https://user-images.githubusercontent.com/45057390/143924401-31c74db1-f985-489e-80ea-0587b5e0b253.mp4

**System information:**
 - OS: Arch Linux x64
 - Commit ID: 0ab9d69 

**Additional comments**
I hope the information is useful for everyone.
Thanks for the excellent work :)

**Comment by rodolforg** [comment]
@Gilraiser do you stay up-to-date via git?
Can you remember when this problem started?
Are you able to git-bisect?

**Comment by rodolforg** [comment]
via `git-log`, maybe until this commit, everything could be normal: c3e196e1974108a264016c61909cf12f8d802560
After it, we made some cleanups that maybe broke it: like feb62c586f9b8c5378ce724854c7180d674e8326 4bb7366bcc87133ae68bd0341c08d000faf9a887 2ce7109e2f8a2973c8c85255d74516b052004bee

**Comment by Gilraiser** [comment]
Hello, cordial greetings. I'm sure it started with committee 0ab9d69. The only thing done with git is git clone. Searching the internet, I see that git-bisect is for searching within code when you are not sure when the error started. I am very sure that it is in the commit that I just pointed out where the bug started. I reported it immediately.

**Comment by rodolforg** [comment]
Yes, `git-bisect` help us to search the culprit commit.
We say to git what commit we are sure something was good and what commit is in a bad state (normally head commit).
Then it starts checking out the commit in the midway: we build and test and tell if it is a good or a bad commit. Then git checks out other commit, narrowing the search. We keep doing it until it finds a good commit followed by a bad one :)

Anyway, I'll investigate the commit you mentioned. Thank you :)

**Comment by genete** [comment]
Issue reappear in SynfigStudio-1.4.4-2022.12.25-osx-b8d62 using MacOS 10.13.6 (17G14042)
