### ISSUE TITLE
Unwanted Vertex Points at the end of line, when using Draw tool 

### ISSUE THREAD

**Issue by THEBATEZIOPARKER** [synfig/synfig#2460]
I am using Fedora 35, Synfig-Studio Flatpak version

https://user-images.githubusercontent.com/87817029/145769322-024a5487-443b-4f74-8567-0ede45476a29.mp4

How to Fix This ?

**Comment by ice0** [comment]
@morevnaproject @rodolforg 
Any ideas here?

**Comment by rodolforg** [comment]
Duplicate of #2448 ?

**Comment by THEBATEZIOPARKER** [comment]
@rodolforg Yes

**Comment by THEBATEZIOPARKER** [comment]
Where Can I Get The Draw Tool Bug Fixed Version ?

**Comment by ice0** [comment]
@THEBATEZIOPARKER 
On Linux you can compile it from source.
Flatpak will be available tomorrow.

**Comment by ice0** [comment]
@THEBATEZIOPARKER 

Can you check flatpak build?
```
flatpak install --user https://dl.flathub.org/build-repo/70486/org.synfig.SynfigStudio.flatpakref
```

**Comment by THEBATEZIOPARKER** [comment]
@ice0 This flatpak build works without any issues
