### ISSUE TITLE
Can't select active bone when creating Skeleton Deformation layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2469]
**Describe the bug**
When creating  Skeleton Deformation Layer using Bone Tool clicking on existing bone should set it as active (parent to next one).
But if Skeleton Deformation Layer is placed inside of **transformed** group, then it is not possible to select active bone anymore.

**To Reproduce**
Video - https://youtu.be/1hExD64ZkbE

**System information:**
 - Commit ID: 310aaad378224b6db22c

**Comment by rodolforg** [comment]
It works if you click on Bone "line" o.O

**Comment by morevnaproject** [comment]
Oh, you right O_O

**Comment by morevnaproject** [comment]
So, the fix is needed for points only.

**Comment by rodolforg** [comment]
I found out what is happening: WorkArea don't pass click events to current state/tool if a duck is clicked. :/

Mouse button release, on other hand, is always passed.

**Comment by morevnaproject** [comment]
I have discovered that this issue also happens for regular Skeleton Layer, not just Skeleton Deformation.
