### ISSUE TITLE
Linux: command line multithreaded rendering not working

### ISSUE THREAD

**Issue by raf32** [synfig/synfig#248]
I have a anim1.sifz file which is rendered just fine with the following command:
`synfig anim1.sifz -t ffmpeg --fps 24 --video-codec libx264 --video-bitrate 2000 -o test.mp4`

But if I try to use multithreaded rendering like so:

`synfig anim1.sifz -t ffmpeg -T 2 --fps 24 --video-codec libx264 --video-bitrate 2000 -o test.mp4`

I get this error:

`boost::bad_any_cast: failed conversion using boost::any_cast`

Looking this error up in google it seems it is related to a c++ library used for multithreading.

My system is:
Debian Jessie (8.6) 64bit, Kernel 3.16.0-4-amd64
Intel core i5 520M
GPU NVidia NVS3100M 512mb
4 gb RAM DDR3 1333 mhz
Synfig 1.0.2
##

**Comment by caryoscelus** [comment]
Can you try latest development version? At the current state of things, i'm afraid there aren't enough developers to look into bugs in "stable" release.

**Comment by raf32** [comment]
I have tried the following version from the tarball: synfigstudio-1.1.11-20160727.x86_64

Had to install libxcb-randr0 to get it working (can't this library be included in the tarball?). 

I am running synfig from the download dir with the provided shell script (which uses `export LD_LIBRARY_PATH`).

Now it does not crash when I try to use the multithreaded mode but it makes no difference either: regardless of the number of threads, it takes the same time to render. That is 5min for ffmpeg and 14min for yuv420p, for an animation with 800x600 pixels, 24 fps, 4 minutes and no sound. Is this expected or multithreading is not actually working on my machine?

**Comment by caryoscelus** [comment]
Apparently this option is actually ignored at the moment. I get the message `synfig(26952) [12:25:14] info: rendering threads 4` regardless of specifying thread amount, but system monitor shows that only one cpu core is used.

**Comment by ebarranco** [comment]
I still have this exact issue with synfig 1.2.2

**Comment by rodolforg** [comment]
I don't have this problem with master branch in Linux.
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                       
11013 rodolfo   20   0 3679484   2,0g 119156 S 261,5  12,9   3:25.14 synfig     
```

**Comment by ice0** [comment]
I close it, since it has already been fixed.
