### ISSUE TITLE
Hide unanimated properties

### ISSUE THREAD

**Issue by mray** [synfig/synfig#250]
There should be a way to toggle the visibility of animated properties in this section:

![selection_006](https://cloud.githubusercontent.com/assets/164785/19400081/cbffafec-9254-11e6-9433-0ca6cd8c7a44.png)

I only plan to animate the position of this project so i'd like to put everything else out of the way while i'm working. Maybe there is a way to do this already? I could not find it.

**Comment by mray** [comment]
For illustration: after using the toggle (maybe a button) the result would be this:

![selection_007](https://cloud.githubusercontent.com/assets/164785/19400522/e1336afa-9256-11e6-8d81-d12153fb9dd7.png)

**Comment by jcome** [comment]
currently there is no way to hide "a group of parameters".  introducing a filter system would be nice:
http://www.synfig.org/forums/viewtopic.php?f=14&t=3634#p15602

**Comment by caryoscelus** [comment]
#268 is a superset of this feature proposal, so closing this one.
