### ISSUE TITLE
Layer order does not work when used a skeleton deformation layer [$20]

### ISSUE THREAD

**Issue by fnpulido** [synfig/synfig#251]
The character is an exploded bitmap, which I imported into layers, each piece in a layer, I added a layer with a Skeleton deformation and have set up all bones.

![simoncapas02](https://cloud.githubusercontent.com/assets/17544336/19420744/4fd857c6-93f2-11e6-8308-bf5c1ade4eca.png)

Apparently everything works well with regard to the areas of influence of the bones, but when I start to put the pieces in the correct place, do not appear in the order they should, this should be from the bottom up: left arm, left leg, trunk, right leg, right arm and head and in the layers panel, appears keeping the left arm ZOrder value 6 and the head ZOrder with value 1.

But when I place the pieces to animate them, the trunk appears in first plane

![simoncapas01](https://cloud.githubusercontent.com/assets/17544336/19420746/57c37de4-93f2-11e6-8c22-6939ddb43069.png)

Anyway, I can not get an arm and a leg on each side.

**Comment by morevnaproject** [comment]
Hello @fnpulido !
Skeleton Deformation layer doesn't deal with layer order at all (because it works with "merged context"). You have to tweak "Z-Depth" parameter of each bone to define the order of parts.

![screen-11](https://cloud.githubusercontent.com/assets/332868/19623773/e780c728-9903-11e6-98ff-80879befda7c.png)

**Comment by morevnaproject** [comment]
I am closing this, since this is not a code issue. I hope you will be able to retract the bounty. ^__^

**Comment by fnpulido** [comment]
Thank you. One question. Are there any way to identificate a bone? I don't
know what is, for example, "Bone 379", and when this is selected I Can't
see any mark or similar.

**Comment by fnpulido** [comment]
The bounty it's OK. I's a contribution :)

**Comment by morevnaproject** [comment]
> Are there any way to identificate a bone? I don't know what is, for example, "Bone 379", and when this is selected I Can't see any mark or similar.

With the [latest build of Synfig](https://morevnaproject.org/synfig/) you can click on any control point of bone and this will make corresponding parameter selected in Params Panel.

**Comment by morevnaproject** [comment]
> The bounty it's OK. I's a contribution :)

Thank you very much! ^__^

@blackwarthog, I think it would be best if you will claim the bounty, since you are the author of Skeleton Deformation feature. Just don't forget to fix #271 with that. ^__^

**Comment by fnpulido** [comment]
Thank you. I'm going to try it.

**Comment by blackwarthog** [comment]
I've fixed bug in rendering of Layer_SkeletonDeformation [#271](https://github.com/synfig/synfig/issues/271) in [this commit](https://github.com/synfig/synfig/commit/4ab7efec0bf137333e1d00e282de5297e5c85f5c)
