### ISSUE TITLE
Feature request: Grouping of selected layers using a hotkey

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#2525]
Grouping of layers is a bit cumbersome in synfig and takes a lot of clicks to do so.
It would be way easier if we'd be able to select layers right from the canvas and group them using a hotkey.

**Comment by veermetri05** [comment]
@rodolforg , will this be suitable for me to solve? Also, please provide me necessary information to solve this issue

The shortcuts in Inkscape are Ctrl + G and Ctrl + Shift + G for group and ungroup.

I think we should use the same, and we can use some other shortcut for Enabling/Disabling Grid.

**Comment by rodolforg** [comment]
> if we'd be able to select layers right from the canvas

You can with `Ctrl`+click .

> The shortcuts in Inkscape are Ctrl + G and Ctrl + Shift + G for group and ungroup.

Now a good amount of actions has its shortcuts configurable via Preferences I don't have any problems about it.
But I'm not the best person who you should ask it XD @morevnaproject @Keyikedalube @ice0 

> I think we should use the same, and we can use some other shortcut for Enabling/Disabling Grid.

Inkscape use `#` for grid and `|` for guides.

**Comment by morevnaproject** [comment]
> The shortcuts in Inkscape are Ctrl + G

Krita uses `Ctrl+G` too and I like it. 

> > I think we should use the same, and we can use some other shortcut for Enabling/Disabling Grid.
> 
> Inkscape use `#` for grid and `|` for guides.

I like that!

So, I vote for changing Grid shortcut to `#` and using `Ctrl+G` for Grouping action.

**Comment by rodolforg** [comment]
The default accelerator map is defined in `synfig-studio/src/gui/app.cpp` (method `App::get_default_accel_map()`).

The layer actions are mapped to `"<Actions>/action_group_layer_action_manager/action-<LAYER_ACTION_NAME>"`.
And, well, `<LAYER_ACTION_NAME>` is the layer action name :P All synfigapp actions are separated in individual files in `synfig-studio/src/synfigapp/actions/`. Search for `ACTION_SET_NAME()` macro.

**Comment by rodolforg** [comment]
@veermetri05 do you need any help here?

**Comment by rock16** [comment]
@rodolforg I don't know if I'm right or not. But it turns out the action for grouping layers has been implemented in `synfig-studio/src/synfigapp/actions/groupaddlayers.(h,cpp)` but the ability to group layers with hotkeys (ctrl + g) hasn't right?

I would love to work on this if it has not been implemented.

**Comment by Keyikedalube** [comment]
> but the ability to group layers with hotkeys (ctrl + g) hasn't right?

Yes, the OP requests hotkey as a new feature to maximize his productivity.

> I would love to work on this if it has not been implemented.

I would suggest to look at the code. Play around and replicate said action hotkey by referencing other action hotkeys. There are a lot.
If you are working on this let me know and I'll assign this issue to you :)

**Comment by rodolforg** [comment]
> But it turns out the action for grouping layers has been implemented in `synfig-studio/src/synfigapp/actions/groupaddlayers.(h,cpp)`

Hey, @rock16 ! Well, you aren't right here, but it's not your fault.
A synfig Canvas (may) have Layer Sets (https://synfig.readthedocs.io/en/latest/ui/panel_sets.html), but Set is the word used in the GUI, but not in the source code :( That difference exists due to a change made a long time ago (https://wiki.synfig.org/Terminology).

You should search for "encapsulate".

**Comment by rock16** [comment]
@Keyikedalube 

> I would suggest to look at the code. Play around and replicate said action hotkey by referencing other action hotkeys. There are a lot.
If you are working on this let me know and I'll assign this issue to you :)

This is what I intend to do right away.

I do need to get somethings right. 

@rodolforg 
> A synfig Canvas (may) have Layer Sets (https://synfig.readthedocs.io/en/latest/ui/panel_sets.html), but Set is the word used in the GUI, but not in the source code

Does it mean Layer Sets on the GUI is actually refered to as Group on the source code? speaking of `studio/src/synfigapp/actions/groupaddlayers.(h, cpp)`. 

From the GUI layer panel, one can add selected layers to set and one can also group selected layers as Group; from the documentation, such group is also refered to as a layer.

Is this feature request about set or group?

**Comment by Keyikedalube** [comment]
Okay, inked PR #2581 resolved this issue.
