### ISSUE TITLE
Bone Shape in Skeleton Deformation ignores group transformation

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2526]
If you put Skeleton Deformation into transformed group, the Bone Shape areas will appear in wrong place.

Video - https://youtu.be/tE9yeF6nwDA

**Comment by rodolforg** [comment]
I fixed the translation and rotation issue, but not scale and skew :(

**Comment by morevnaproject** [comment]
> but not scale and skew :(

...and not Twirl, Noise Distort, Spherize and other rendering stuff. :thinking: 

Hmmm... it looks like the problem gets too complicated here.

**Comment by rodolforg** [comment]
Not impossible, though.
We can divide the bone outline into segments, transform them and draw them.

**Comment by morevnaproject** [comment]
Exciting! I believe users with slower PCs can always switch to Draft mode.
