### ISSUE TITLE
Synfig crashes with a segfault when closing

### ISSUE THREAD

**Issue by nickleus27** [synfig/synfig#2536]
**Describe the bug**
The synfig application produces a segmentation fault when closing the application. The output in the terminal after closing synfig is:
```
Quit Request
Quit Request sent
Application appears to have terminated successfully
zsh: segmentation fault  ./output/Debug/bin/synfigstudio
```

**To Reproduce**
1. clone synfig master branch
2. mkdir cmake-build && cd cmake-build
3. cmake .. && make
4. ./output/Debug/bin/synfigstudio
5. Go to File, and click on quit

**Expected behavior**
I expected synfig to quit without a seg fault. The output in the terminal after quitting should look like:
```
Quit Request
Quit Request sent
Application appears to have terminated successfully
```

This is the same output as before minus the seg fault

**System information:**
 - OS: MacOS M1 chip
 - OS version: Monterey
 - Commit ID: e0548010697637acc2c5a187434a937b262f94d2

**Comment by ice0** [comment]
@nickleus27 Can you check it?

**Comment by nickleus27** [comment]
@ice0 Yes! #2536 fixes the segfault when closing on macos.
