### ISSUE TITLE
Add key marks for the PGO layer to the new Timetrack

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#2538]
While checking this PR (#2495) I noticed that the new Timetrack does not have the key marks for the PGO layer. 

Left: New Timetrack
Right: Old Timetrack

![No marks](https://user-images.githubusercontent.com/5604544/153978593-564950eb-5895-4a89-95ea-391533dc65e6.png)

**Comment by rodolforg** [comment]
#2385

**Comment by rodolforg** [comment]
Is this fixed by #2385 ?

**Comment by ice0** [comment]
> Is this fixed by #2385 ?

Yes, it is fixed now!
