### ISSUE TITLE
right-click in layer window should show layer options

### ISSUE THREAD

**Issue by ghost** [synfig/synfig#254]
Currently a right click in the empty area of the layers tab shows no context.
I expect layer relevant context options – like the layer menu there.
##

**Comment by caryoscelus** [comment]
Yeah, some menu there would be nice. Not sure if it makes sense to actually have full layer menu (most of it is indeed contextual to some layer selection), maybe just new layer. That will actually solve the problem of too much clicking to create new layer (the better alternative is to add a "new layer" button with submenu, but it can be harder to implement).
