### ISSUE TITLE
Error while building debug verision on windows.

### ISSUE THREAD

**Issue by mohamedAdhamc** [synfig/synfig#2565]
I had followed all the steps and had one last thing to do which is run
"$ ./2-build-debug.sh "
but then i get an error stating 
"cp: cannot stat '/opt/mlt-7.2.0/*.dll': No such file or directory "
looking around at what happened during the installation i have found this stating that the path was changed 
"/tmp/mlt-7.2.0 /tmp ~/synfig.git
Install path: /opt/mlt-7.2.0
Fixed MLT Path: C:/msys64/opt/mlt-7.2.0"
I have thought of rerunning "$ ./1-setup-windows-msys2.sh", or changing the path manually but im not at all experienced with that so it might take some time.

If anyone experienced a similar thing, help would be greatly appreciated.

p.s 
errors encountered during the process 
"error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_23NZGj/.INSTALL; post_install 41.0-1 ) failed to execute correctly" however i think this one is a bit far fetched

this is where the issues started i think:

/tmp/mlt-7.2.0 /tmp ~/synfig.git
Install path: /opt/mlt-7.2.0
Fixed MLT Path: C:/msys64/opt/mlt-7.2.0
/tmp/mlt-7.2.0/build /tmp/mlt-7.2.0 /tmp ~/synfig.git
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/msys64/tmp/mlt-7.2.0/build/CMakeFiles/CMakeOutput.log".
1 out of 1 hunk FAILED
patching file /mingw64/include/libintl.h
Hunk #1 FAILED at 359.
1 out of 1 hunk FAILED -- saving rejects to file /mingw64/include/libintl.h.rej

20102@DESKTOP-011T3NV MINGW64 ~/synfig.git
$ pacman -S mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja
warning: mingw-w64-x86_64-cmake-3.22.3-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-x86_64-cmake-3.22.3-1  mingw-w64-x86_64-ninja-1.10.2-3

Total Download Size:    2.47 MiB
Total Installed Size:  82.93 MiB
Net Upgrade Size:      13.77 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 mingw-w64-x86_64...     2.5 MiB  1192 KiB/s 00:02 [#####################] 100%
(2/2) checking keys in keyring                     [#####################] 100%
(2/2) checking package integrity                   [#####################] 100%
(2/2) loading package files                        [#####################] 100%
(2/2) checking for file conflicts                  [#####################] 100%
(2/2) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/2) reinstalling mingw-w64-x86_64-cmake          [#####################] 100%
(2/2) installing mingw-w64-x86_64-ninja            [#####################] 100%

20102@DESKTOP-011T3NV MINGW64 ~/synfig.git
$ ./2-build-debug.sh
cp: cannot stat '/opt/mlt-7.2.0/*.dll': No such file or directory

**Comment by mohamedAdhamc** [comment]
oh and i'm doing all this on windows 10, 64 bits .

**Comment by mohamedAdhamc** [comment]
> Update: installed the dependencies again and the previous error was fixed but now it gives out a new error saying "Use the -v/--verbose option for more details. *** No libtoolize nor glibtoolize found, please install the intltool package ***"

i checked and intltool was actually installed successfully which make all this more confusing

**Comment by ice0** [comment]
> I did multiple times actuallly xd.

I think there is should be a reason why MLT is not installed. 
Can you show output of `ls -la /opt/mlt-7.2.0` command?

**Comment by ice0** [comment]
> *** No libtoolize nor glibtoolize found, please install the intltool package ***"

I will take a look. Currently, the preferred way to build on Windows is to use cmake. 
Use `2-build-msys-cmake.sh` script for that.
To change build type, just change `-DCMAKE_BUILD_TYPE=Release` to `-DCMAKE_BUILD_TYPE=Debug` for debug build.

**Comment by mohamedAdhamc** [comment]
> > *** No libtoolize nor glibtoolize found, please install the intltool package ***"
> 
> I will take a look. Currently, the preferred way to build on Windows is to use cmake. Use `2-build-msys-cmake.sh` script for that. To change build type, just change `-DCMAKE_BUILD_TYPE=Release` to `-DCMAKE_BUILD_TYPE=Debug` for debug build.

oh ok thanks. it's in the process of building using c make now.

**Comment by ice0** [comment]
MSYS2 moved `libtoolize` to the new `libtool` package and renamed `mingw-w64-x86_64-libtool` to `mingw-w64-x86_64-libltdl`

This issue should be fixed with this PR #2566

**Comment by mohamedAdhamc** [comment]
> MSYS2 moved `libtoolize` to the new `libtool` package and renamed `mingw-w64-x86_64-libtool` to `mingw-w64-x86_64-libltdl`
> 
> This issue should be fixed with this PR #2566

great, thanks will definitely try to build it again that same way when the pr is merged.

**Comment by mohamedAdhamc** [comment]
> > *** No libtoolize nor glibtoolize found, please install the intltool package ***"
> 
> I will take a look. Currently, the preferred way to build on Windows is to use cmake. Use `2-build-msys-cmake.sh` script for that. To change build type, just change `-DCMAKE_BUILD_TYPE=Release` to `-DCMAKE_BUILD_TYPE=Debug` for debug build.

P.S  while running with cmake i encountered an error but it was relatively easy and i solved and made a proposal for the solution (simple tweak of the command in the docs). PR #87[https://github.com/synfig/synfig-docs-dev/pull/87](url)

**Comment by mohamedAdhamc** [comment]
> MSYS2 moved `libtoolize` to the new `libtool` package and renamed `mingw-w64-x86_64-libtool` to `mingw-w64-x86_64-libltdl`
> 
> This issue should be fixed with this PR #2566

I retried and it still gives out the same error.

**Comment by mohamedAdhamc** [comment]
> > *** No libtoolize nor glibtoolize found, please install the intltool package ***"
> 
> I will take a look. Currently, the preferred way to build on Windows is to use cmake. Use `2-build-msys-cmake.sh` script for that. To change build type, just change `-DCMAKE_BUILD_TYPE=Release` to `-DCMAKE_BUILD_TYPE=Debug` for debug build.

Also sorry for the constant bothering but could you please elaborate on the "-DCMAKE_BUILD_TYPE=Debug" because i tried running the command and it just gives out no ssuch file or directory

**Comment by rodolforg** [comment]
> I retried and it still gives out the same error.

That PR wasn't merged to master branch yet. In the meanwhile, you can patch the changes yourself into your cloned repo.



> but could you please elaborate on the "-DCMAKE_BUILD_TYPE=Debug"

He meant you change https://github.com/synfig/synfig/blob/master/2-build-msys-cmake.sh: instead of `-DCMAKE_BUILD_TYPE=Release`, replace it with `-DCMAKE_BUILD_TYPE=Debug` (line 5).

**Comment by mohamedAdhamc** [comment]
> > I retried and it still gives out the same error.
> 
> That PR wasn't merged to master branch yet. In the meanwhile, you can patch the changes yourself into your cloned repo.
> 
> > but could you please elaborate on the "-DCMAKE_BUILD_TYPE=Debug"
> 
> He meant you change https://github.com/synfig/synfig/blob/master/2-build-msys-cmake.sh: instead of `-DCMAKE_BUILD_TYPE=Release`, replace it with `-DCMAKE_BUILD_TYPE=Debug` (line 5).

Oh, my bad didn't notice that. Thanks !

**Comment by mohamedAdhamc** [comment]
> > I retried and it still gives out the same error.
> 
> That PR wasn't merged to master branch yet. In the meantime, you can patch the changes yourself into your cloned repo.
> 
> > but could you please elaborate on the "-DCMAKE_BUILD_TYPE=Debug"
> 
> He meant you should change https://github.com/synfig/synfig/blob/master/2-build-msys-cmake.sh: instead of `-DCMAKE_BUILD_TYPE=Release`, replace it with `-DCMAKE_BUILD_TYPE=Debug` (line 5).

Hey I have an idea of why not make another seperate script and have the "-DCMAKE_BUILD_TYPE=Debug" and then give it a diffrent name so that new contributors using c-make could just pick a script to use instead of doing this manually. just like how Autotools has two different scripts "2-build-debug.sh", and "2-build-production.sh". Also as noted by @ice0 the preferred way now is using cmake so I think it would make sense.

Do you think this is a good idea? If so I can make a pull request adding the script and also update the documentation for that part.

**Comment by BobSynfig** [comment]
> > cp: cannot stat '/opt/mlt-7.2.0/*.dll': No such file or directory
> 
> You need to run `1-setup-windows-msys2.sh` first.

In the current version of `1-setup-windows-msys2.sh`, there is a call to [build_mlt.sh](https://github.com/synfig/synfig/blob/master/autobuild/msys2/build_mlt.sh), which requires... cmake and ninja
As per the current install documentation, these 2 tools are installed *after* the execution of `1-setup-windows-msys2.sh`, but they should be installed before.
As the 2 packages are arch dependant, there are 2 solutions:
- Install first cmake and ninja (according their arch) and the execute `1-setup-windows-msys2.sh`
- Modify `1-setup-windows-msys2.sh` to install the 2 packages (according their arch) before the call to build_mlt.sh

Other point, [libintl.h.patch](https://github.com/synfig/synfig/blob/master/autobuild/msys2/libintl.h.patch) needs to be adapted to the new version of libintl.h

I am installing MSYS2 on a Windows 10 where it has never been installed (let's say "fresh install"), following the current documentation.
Nothing that can't be fixed ;)

**Comment by ice0** [comment]
> In the current version of 1-setup-windows-msys2.sh, there is a call to [build_mlt.sh](https://github.com/synfig/synfig/blob/master/autobuild/msys2/build_mlt.sh), which requires... cmake and ninja

Thanks. I didn't notice it because AppVeyor has them already installed. 
Should be fixed by this PR (#2575)

> Other point, [libintl.h.patch](https://github.com/synfig/synfig/blob/master/autobuild/msys2/libintl.h.patch) needs to be adapted to the new version of libintl.h

Looks like MSYS2 already fixed it so I just removed it. (#2576)

**Comment by BobSynfig** [comment]
> Looks like MSYS2 already fixed it so I just removed it. (#2576)

extern int sprintf (char *, const char *, ...);
will point at `#namespace std { using ::libintl_sprintf; }`
instead of `namespace std { using ::sprintf; }`
Let's hope there will be no side effects

I modified the documentation to reflect the change in PR #2575

**Comment by ice0** [comment]
@mohamedAdhamc 
Can it be closed or are there any issues left unresolved?

**Comment by mohamedAdhamc** [comment]
> @mohamedAdhamc Can it be closed or are there any issues left unresolved?

Last that I know of, it was still giving out errors however I will try running it now and see how it goes.

**Comment by mohamedAdhamc** [comment]
at the end it gives out 
`C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 73254
collect2.exe: error: ld returned 1 exit status
make[4]: *** [Makefile:1640: synfigstudio.exe] Error 1
make[4]: Leaving directory '/home/20102/synfig.git/_debug/synfig-studio/src/gui'
make[3]: *** [Makefile:4088: all-recursive] Error 1
make[3]: Leaving directory '/home/20102/synfig.git/_debug/synfig-studio/src/gui'
make[2]: *** [Makefile:450: all-recursive] Error 1
make[2]: Leaving directory '/home/20102/synfig.git/_debug/synfig-studio/src'
make[1]: *** [Makefile:693: all-recursive] Error 1
make[1]: Leaving directory '/home/20102/synfig.git/_debug/synfig-studio'
make: *** [Makefile:529: all] Error 2
`
and the build isn't completed

**Comment by BobSynfig** [comment]
I had the same error last weekend, it is a common issue when having too many symbols exports in one lib (max 65535), so the debug mode is a bit broken at the moment (for Windows).
I will try the build system (https://github.com/morevnaproject/morevna-builds) to see if the recent changes were successful.
P.S.: Production build also fail on creation of some icons on AutoTools, obviously because of modifications of some layers/parameters in the .sif

**Comment by mohamedAdhamc** [comment]
> 

yea, I'm actually just using c-make now. way more convenient as of right now.

**Comment by ice0** [comment]
MSYS2 Autotools `Release/production` build should be fixed with https://github.com/synfig/synfig/pull/2818.
MSYS2 Autotools `Debug` build still fails due to too many exported symbols.
