### ISSUE TITLE
Copy-pasting using keyboard shortcuts should respect input focus [$10]

### ISSUE THREAD

**Issue by caryoscelus** [synfig/synfig#257]
It seems that now all copy-paste shortcuts are defined globally and act on layers. This is unintuitive and makes copypasting numeric & textual values kinda painful.
##

**Comment by morevnaproject** [comment]
Bounty posted for this issue by Susssu - https://www.bountysource.com/issues/38567642-copy-pasting-using-keyboard-shortcuts-should-respect-input-focus

**Comment by morevnaproject** [comment]
@rodolforg This possibly could be solved in the same way as #629?

**Comment by rodolforg** [comment]
@morevnaproject  I can do a hack'ish way :/

**Comment by rodolforg** [comment]
DONE :O

**Comment by morevnaproject** [comment]
@rodolforg I suspect your fix (PR #898) also covers your previous fixes with Delete/Home/End keys. I mean, now it is possible to make those keys global (at the moment they are only active when CanvasView/LayerPanel focused). That would simplify things a bit. ^__^

**Comment by morevnaproject** [comment]
@rodolforg Also, please make sure to identify that you solved the issue at bounty page - https://www.bountysource.com/issues/38567642-copy-pasting-using-keyboard-shortcuts-should-respect-input-focus ^__^

**Comment by morevnaproject** [comment]
Reopening, so I will not forget about this

**Comment by rodolforg** [comment]
> @rodolforg I suspect your fix (PR #898) also covers your previous fixes with Delete/Home/End keys. I mean, now it is possible to make those keys global (at the moment they are only active when CanvasView/LayerPanel focused). That would simplify things a bit. ^__^

Yep, that could be done. However, we'll lose:
1. the Home/End key press behavior for list widgets like Layer dock
2. possible Delete usage for waypoints in Timetrack dock

It's a matter of choice. If so, just git revert that commits and change Ctrl+delete to Delete.

**Comment by morevnaproject** [comment]
> 1. the Home/End key press behaviour for list widgets like Layer dock

Got it. That's okay, in my opinion.

> 2. possible Delete usage for waypoints in Timetrack dock

This is important for the future. Is it possible to change condition in `MainWindow::on_key_press_event()`  to check if focus is on TimeTrack?

**Comment by rodolforg** [comment]
> > 1. possible Delete usage for waypoints in Timetrack dock
> 
> This is important for the future. Is it possible to change condition in `MainWindow::on_key_press_event()` to check if focus is on TimeTrack?

Yes, it's possible. Maybe any GtkDrawingArea should have priority?

**Comment by morevnaproject** [comment]
> Maybe any GtkDrawingArea should have priority?

Maybe, but I am not sure. IIRC, we do not have much GtkDrawingArea widgets yet...

I have made modifications for "Delete" key - https://github.com/synfig/synfig/commit/03d322afb843a1abfc659000ab3bca80828f7536

For Home/End keys I left things as they are. ^__^

**Comment by morevnaproject** [comment]
@rodolforg Since this issue is solved by you, can you please click "Claim bounty" button here? ^__^ - https://www.bountysource.com/issues/38567642-copy-pasting-using-keyboard-shortcuts-should-respect-input-focus
![screenshot_001](https://user-images.githubusercontent.com/332868/65142417-dbadbc80-da3c-11e9-91f3-032ac034d362.png)

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
