### ISSUE TITLE
Display Zoom state

### ISSUE THREAD

**Issue by mray** [synfig/synfig#260]
Currently I don't see any way to easily know what my zoom level is.
I can press "1" to be sure it is 100% again, but without pressing I don't know *what* the zoom level is, not even if it is 100%.

Here is what comes to my mind to fix the issue:

![screenshot from 2016-10-21 20-21-52_](https://cloud.githubusercontent.com/assets/164785/19607937/8df8c39a-97cd-11e6-86cb-5bce6b21121c.png)

**Comment by caryoscelus** [comment]
After a fight with Gtk i added widget that not only displays, but can also change zoom.

**Comment by mray** [comment]
Sounds awesome!
