### ISSUE TITLE
AppImage doesn't start

### ISSUE THREAD

**Issue by PhilDevProg** [synfig/synfig#2607]
**Describe the bug**
The AppImage isn't able to start

**To Reproduce**
1. Download the AppImage of version 1.5.1 from GitHub
2. Run `chmod +x SynfigStudio-1.5.1-2021.10.21-linux64-2cb6c.appimage` in the Terminal
3. Run `.SynfigStudio-1.5.1-2021.10.21-linux64-2cb6c.appimage` to start Synfig
4. See error message: 

> ls: /tmp/.mount_mA0gRF/usr/lib/libselinux.so.1: no version information available (required by ls)
find: /tmp/.mount_mA0gRF/usr/lib/libselinux.so.1: no version information available (required by find)
sed: /tmp/.mount_mA0gRF/usr/lib/libselinux.so.1: no version information available (required by sed)
sed: /tmp/.mount_mA0gRF/usr/lib/libselinux.so.1: no version information available (required by sed)
/tmp/.mount_mA0gRF/usr/bin/synfigstudio: /tmp/.mount_mA0gRF/usr/lib/libselinux.so.1: no version information available (required by /lib64/libmount.so.1)
/tmp/.mount_mA0gRF/usr/bin/synfigstudio: symbol lookup error: /lib64/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language

**Expected behavior**
Start without the error message.

**System information:**
 - Linux distro: Fedora
 - OS version: 36
 - Package: AppImage
 - Synfig version: 1.5.1

**Comment by Keyikedalube** [comment]
Reproducible both in v1.4.2 and v.1.5.0

**Comment by Keyikedalube** [comment]
This isn't Synfig problem.

Here's another project reporting the same issue https://github.com/vircadia/vircadia/issues/1483
Another one https://sourceforge.net/p/flightgear/codetickets/2651/

**Comment by ice0** [comment]
ping @morevnaproject

**Comment by morevnaproject** [comment]
Related to https://github.com/synfig/synfig/issues/2397

**Comment by ice0** [comment]
@PhilDevProg 

What desktop environment are you using?

**Comment by PhilDevProg** [comment]
@ice0 I'm using GNOME 42 on Wayland

**Comment by PhilDevProg** [comment]
It works again after I removed the font cache with `rm -rf $HOME/.cache/fontconfig`
