### ISSUE TITLE
[1.4.x] Build error: call of overloaded 'abs(synfig::Real&)' is ambiguous

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2612]
I've got the following error when building packages from [v1.4.x branch](https://github.com/synfig/synfig/commits/v1.4.x) (commit id 71775e696d32388b0f04a267c02a3785732f4bdc):

```
plant.cpp: In member function 'void Plant::sync() const':
plant.cpp:244:21: error: call of overloaded 'abs(synfig::Real&)' is ambiguous
  Real step(abs(step_));
                     ^
```

**Comment by ice0** [comment]
@morevnaproject use `std::abs` here instead.
