### ISSUE TITLE
Edit waypoint with double-click

### ISSUE THREAD

**Issue by ghost** [synfig/synfig#262]
Currently it seems you have to right-click and choose "edit" to edit any waypoint.
A double click on a waypoint could show the respecitve "edit" popup window for easier editing.
![screenshot from 2016-10-22 01-02-58](https://cloud.githubusercontent.com/assets/164785/19614266/9a09ee54-97f3-11e6-8b94-34b68be03f12.png)
##

**Comment by caryoscelus** [comment]
I just learned something new about waypoints :D

Also, good idea.

**Comment by ashutoshjv661** [comment]
I would like to look into this issue #262 : )

**Comment by morevnaproject** [comment]
Great, it is yours now! ^__^

**Comment by morevnaproject** [comment]
Hi @ashutoshjv661! Any progress on this? ^__^

**Comment by morevnaproject** [comment]
Hi @ashutoshjv661 ! Do you plan to continue working on this?

**Comment by ashutoshjv661** [comment]
Sorry . I can't  work on this issue.  You can assign it to someone else .

**Comment by morevnaproject** [comment]
Okay, thanks for letting me know! ^__^
