### ISSUE TITLE
Interface background become white after clicking OK in Preferences dialog

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2636]
**Describe the bug**
On master branch, commit 865f197

After clicking OK in Preferences dialog (even when no changes to preferences are made) the background of workarea becomes white.

**To Reproduce**
1. Open Synfig
2. Select "Edit" - "Preferences" from menu
3. Preferences window will appear.
4. Do not do any changes, just click "OK" in the Preferences window
5. The workarea background will become white.

**Screenshots**
Video - https://youtu.be/UwfXUyZ-jkw

See screenshots:
- Window before
![screenshot_003](https://user-images.githubusercontent.com/332868/168810386-71bc9fd4-7340-41f5-8174-1b50d75a2a89.png)

- Window after
![screenshot_002](https://user-images.githubusercontent.com/332868/168810362-a765d5c7-21aa-416f-a875-4e075be40577.png)

**System information:**
 - OS: Linux Mint 19
 - OS version: Mint 19
 - Commit ID: 865f197

**Comment by ice0** [comment]
@morevnaproject 

It looks like the old problem. I have the same issue on 1.4.3 and 1.5.1 AppImages. 
I can reproduce it just minimizing and maximizing the window.

**Comment by rodolforg** [comment]
It happens, actually, when any dialog is closed:
1. Open Synfig
2. Draw anything 
3. Click to close the unsaved document
4. Answer the Confirmation dialog as you like
5. The background becomes white

1. Open Synfig
2. Click to edit Foreground Color
3. Close the Color Dialog
5. The background becomes white
