### ISSUE TITLE
Icons are not displayed in tool options.

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#2639]
**Describe the bug**

![no_icon_04](https://user-images.githubusercontent.com/45057390/168937309-8448d779-d20f-482c-86b8-6083d997d8fc.png)

Icons are not displayed in any of the tool options

**Screenshots**

![no_icon_01](https://user-images.githubusercontent.com/45057390/168937221-442d2a36-d3f6-4e5d-8979-a5a639eda9d1.png)
![no_icon_02](https://user-images.githubusercontent.com/45057390/168937354-3e8fd8a0-644a-4ee6-8ef9-1fda89706c2a.png)
![no_icon_03](https://user-images.githubusercontent.com/45057390/168937364-da4a2acb-3e62-4907-80e6-9a8f7617826d.png)

**System information:**

 - OS: Arch Linux x64 with Kernel 5.15.40-1-lts
 - Commit ID: 2a11e92
 - Built on May 17 2022

**Additional comments**

I hope it will be useful for everyone. Thank you very much.

**Comment by mohamedAdhamc** [comment]
same here on windows version.

**Comment by ice0** [comment]
Ok, I will take a look.
