### ISSUE TITLE
Crash on renaming vertex value

### ISSUE THREAD

**Issue by mray** [synfig/synfig#264]
Synfig crashes Ubuntu 16.10 upon renaming a vertex value like in the screenshot below.
Pressing enter on the following dialog maxes Synfig close immediately

[Sample File](https://github.com/synfig/synfig/files/545746/crash-on-vertex--value-rename.zip)

![screenshot from 2016-10-22 13-11-05](https://cloud.githubusercontent.com/assets/164785/19618943/155224a4-9859-11e6-9186-f8129c5caa42.png)

**Comment by caryoscelus** [comment]
I don't think it's supposed to be edited. It's not really a name, more like "it's too complex value to represent directly, so lets just print type name here".

**Comment by caryoscelus** [comment]
This actually looks like two issues:

- gui allows to edit uneditable value
- editing code uses `assert` instead of throwing error (which would likely be caught)

**Comment by caryoscelus** [comment]
Same happens for width points on advanced outlines.
