### ISSUE TITLE
Crash when clicking on "Position" control point of Group Layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2643]
Version: Appimage package SynfigStudio-1.5.1-testing-2022.05.17-linux64-865f1.appimage
Commit id: 865f1

**Describe the bug**
Synfig crashes when user clicks on Control Point using BoneTool (happens in particular file).

**To Reproduce**
1. Download sample file and unpack it - [024-v4.zip](https://github.com/synfig/synfig/files/8737059/024-v4.zip)
2. Open `024-v4.sif`
3. Click on image, shown on workarea (Layer called "Carrot-r1.png")
4. Select Bone Tool from Toolbox
5. Click with left mouse button on green control point of selected layer.
6. Crash.

**Screenshots**
Video - https://youtu.be/vh5RCtqevh4

![screenshot_001](https://user-images.githubusercontent.com/332868/169470935-b5c77788-21b4-4356-afaf-a4dc1110408a.png)

**System information:**
 - OS: Linux Mint
 - OS version: Linux Mint 19
 - Commit ID: 865f1

**Additional comments**
I wasn't able to reproduce that on empty file. But this is reproducible with sample file.

**Comment by ice0** [comment]
@morevnaproject 

Unfortunately but I can't reproduce. 
Can you try to remove the settings file (just move it somewhere as we will need it in the future) and try with clean settings?

**Comment by rodolforg** [comment]
@ice0 @morevnaproject I can't reproduce either in current master

**Comment by morevnaproject** [comment]
I have tested it again and found why it isn't reproducible.
To make it reproducible it is required to resize bottom panels to the minimum height (actually it is probably enough to resize  Parameters Panel only).
Also, I found that step 4 (Select Bone Tool from Toolbox) is not necessary to reproduce the bug.

So, here are updated instructions to reproduce the bug:

1. Download sample file and unpack it - [024-v4.zip](https://github.com/synfig/synfig/files/8737059/024-v4.zip)
2. Launch Synfig Studio
3. Resize Parameters Panel to minimum height
4. Open `024-v4.sif`
5. Click on image, shown on workarea (Layer called "Carrot-r1.png")
6. Click with left mouse button on green control point of selected layer.
7. Crash.

Here is the video demonstration -
https://youtu.be/Z0KykNxwrAA

**Comment by morevnaproject** [comment]
Some statistics about versions:
- SynfigStudio-1.5.1-testing-2022.04.06-linux64-e54c2.appimage - NO CRASH
- SynfigStudio-1.5.1-testing-2022.05.17-linux64-865f1.appimage (and later) - CRASH REPRODUCIBLE

**Comment by rodolforg** [comment]
I still can't reproduce :( Maybe a Gtk issue? My gtkmm is 3.24.6-1 (Debian)

**Comment by ice0** [comment]
Same for me, still can't reproduce.
@morevnaproject Can you reproduce this on the latest master, or if you build it from source?

**Comment by morevnaproject** [comment]
You right, this is probably a Gtk issue.

I cannot reproduce it when it is built from source (gtk 3.22.30, gtkmm 3.22.2, linux mint 19).

But on appimage it is reproducible. I tested it with recent commit cc59c1247fcdaa1c293bc1fc704922bd9348f7a1. 
Here is a link to download appimage - [SynfigStudio-1.5.1-testing-2022.06.25-linux64-cc59c.appimage](https://cloud.morevnaproject.org/s/dLrzniH3XQKFpkw)
It uses gtk-3.22.12 and gtkmm-3.22.0.

**Comment by morevnaproject** [comment]
I have manged to reproduce similar behavior on Windows - https://youtu.be/MGNFW0Rfxl0 (apologies for ambient noise, I kept audio to be able hear clicks).
It doesn't crashes when I click on "Position" control point, but it crashes when I click on "Resize" control point.

**Comment by morevnaproject** [comment]
What I plan to do next:

1. Check if this bug is reproducible on 1.4.x branch
2. There is a possibility that the bug is related with changes in our builder environment. I will try to rebuild version "2022.04.06-linux64-e54c2" (the one which isn't crashing) with current builder to verify it. 
  * If produced binary will have NO bug, then problem is in synfig's source code. 
  * If produced binary will have this bug, then the problem is related with builder environment.

In any case, I can also try to update gtk/gtkmm versions in our builder environment and see if the bug will go away.

**Comment by morevnaproject** [comment]
This is Windows binary that I used to reproduce the bug - [SynfigStudio-1.5.1-testing-2022.06.13-win64-ee395-new-mingw.exe](https://cloud.morevnaproject.org/s/HCrY74P3Hzfmr7a)

**Comment by morevnaproject** [comment]
1. Version 1.4.3 is not affected by this issue. 
2. I have made a build of commit e54c2 with our current builder environment. And it produced an appimage binary which IS affected by this bug - it crashes.
That means the problem NOT in Synfig's code, this is a problem in builder environment.
The problem is introduced somewhere between commit https://github.com/morevnaproject/morevna-builds/commit/03f5515c23bb913c86ca2d86a846388a6e4256a2 (2022.04.06) and https://github.com/morevnaproject/morevna-builds/commit/cc625cbd17e09f1da3e68de3d2c55a94a2eb518c (2022.05.17).

I am going to do git bisect for our builder environment and see which commit affects the issue.

**Comment by morevnaproject** [comment]
I have found guilty commit - https://github.com/morevnaproject/morevna-builds/commit/ead44ed5a5e8ac6fb20815
Related PR - https://github.com/morevnaproject/morevna-builds/pull/53

It's a surprise we've got affected by glib/glibmm version...

Two options here:
- Try to downgrade glib/glibmm
- Try to upgrade Gtk/Gtkmm

**Comment by morevnaproject** [comment]
Should we stay on Gtk 3.22.x or go for latest Gtk 3.24.x?

**Comment by rodolforg** [comment]
We should try 3.24 for MS Windows packages.

It has lots of big fixes, as it is currently only in maintenance mode.

We could test draw, duck movements, vertex deletion, bones, png import, save, load and export.

**Comment by morevnaproject** [comment]
Woops... it looks like I have managed to fix the bug by updating Gtk to 3.22.30 and Gtkmm to 3.22.2 ^__^"

I agree that it is better to update to 3.24, but this seems to be more complicated and might lead to discover more issues. I suggest to release 1.4.3 and 1.5.2 and after that update to gtk 3.24.

**Comment by morevnaproject** [comment]
Here are new builds, the bug is not reproducible on them anymore:
* [SynfigStudio-1.5.1-testing-2022.07.12-win64-19589.exe](https://cloud.morevnaproject.org/s/jcTadeNfPrK2KK2)
* [SynfigStudio-1.5.1-testing-2022.07.12-linux64-19589.appimage](https://cloud.morevnaproject.org/s/BWTYjKSya8ZyJQL)
