### ISSUE TITLE
No context menu shown for Transformation parameter of Group Layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2672]
Master branch, commit id 17b8f43ab44d8

**Describe the bug**
When user makes right-click on transformation Parameter, no context menu shown.

**To Reproduce**
1. Create Group Layer
2. Right-click on Transformation Parameter in Parameters Panel
3. Error - No context menu shown

**Expected behavior**
It should display context menu after right-click

**Screenshots**
![screenshot_002](https://user-images.githubusercontent.com/332868/172036052-39778d13-33c8-4f84-bb39-3448793306d7.png)

**Comment by ice0** [comment]
Guilty commit: https://github.com/synfig/synfig/commit/78e7a2c733bc4d59a6b94323111420af1927d182
