### ISSUE TITLE
Can't build latest master on Ubuntu 16.04

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#270]
Building commit id 01de3c54d results in:

```
Making all in synfigapp
make[1]: Entering directory '/home/konstantin/sources/synfig.single/synfig-studio/src/synfigapp'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/konstantin/sources/synfig.single/synfig-studio/src/synfigapp'
Making all in gui
make[1]: Entering directory '/home/konstantin/sources/synfig.single/synfig-studio/src/gui'
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src  -DWITH_OPENGL -pthread -D_REENTRANT -std=c++11 -I/home/konstantin/sources/synfig.single/synfig-core/src -I/home/konstantin/synfig//include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/mlt++ -I/usr/include/mlt -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -pthread -std=c++11 -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DIMAGE_DIR=\"/home/konstantin/synfig/share/pixmaps/synfigstudio\" -DIMAGE_EXT=\"png\" -DPLUGIN_DIR=\"/home/konstantin/synfig/share/synfig/plugins\" -DLOCALEDIR=\"/home/konstantin/synfig//locale\" -g -std=c++11  -D_DEBUG -g -O0 -fno-inline -MT dials/synfigstudio-zoomdial.o -MD -MP -MF dials/.deps/synfigstudio-zoomdial.Tpo -c -o dials/synfigstudio-zoomdial.o `test -f 'dials/zoomdial.cpp' || echo './'`dials/zoomdial.cpp
dials/zoomdial.cpp: In constructor 'studio::ZoomDial::ZoomDial(Gtk::IconSize&)':
dials/zoomdial.cpp:76:52: error: use of 'auto' in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
  current_zoom->signal_event_after().connect([this](auto event) {
                                                    ^
dials/zoomdial.cpp: In lambda function:
dials/zoomdial.cpp:77:12: error: base operand of '->' is not a pointer
   if (event->type == Gdk::BUTTON_RELEASE)
            ^
In file included from /usr/include/sigc++-2.0/sigc++/functors/slot.h:7:0,
                 from /usr/include/sigc++-2.0/sigc++/signal_base.h:27,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from /usr/include/gtkmm-3.0/gtkmm/tooltip.h:8,
                 from dials/zoomdial.h:32,
                 from dials/zoomdial.cpp:35:
/usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h: In instantiation of 'typename sigc::adaptor_functor<T_functor>::deduce_result_type<T_arg1>::type sigc::adaptor_functor<T_functor>::operator()(T_arg1) const [with T_arg1 = _GdkEvent* const&; T_functor = studio::ZoomDial::ZoomDial(Gtk::IconSize&)::<lambda(int)>; typename sigc::adaptor_functor<T_functor>::deduce_result_type<T_arg1>::type = void]':
/usr/include/sigc++-2.0/sigc++/functors/slot.h:142:20:   required from 'static T_return sigc::internal::slot_call1<T_functor, T_return, T_arg1>::call_it(sigc::internal::slot_rep*, sigc::type_trait_take_t<T_arg3>) [with T_functor = studio::ZoomDial::ZoomDial(Gtk::IconSize&)::<lambda(int)>; T_return = void; T_arg1 = _GdkEvent*; sigc::type_trait_take_t<T_arg3> = _GdkEvent* const&]'
/usr/include/sigc++-2.0/sigc++/functors/slot.h:149:37:   required from 'static void* (* sigc::internal::slot_call1<T_functor, T_return, T_arg1>::address())(void*) [with T_functor = studio::ZoomDial::ZoomDial(Gtk::IconSize&)::<lambda(int)>; T_return = void; T_arg1 = _GdkEvent*; sigc::internal::hook = void* (*)(void*)]'
/usr/include/sigc++-2.0/sigc++/functors/slot.h:584:90:   required from 'sigc::slot1<T_return, T_arg1>::slot1(const T_functor&) [with T_functor = studio::ZoomDial::ZoomDial(Gtk::IconSize&)::<lambda(int)>; T_return = void; T_arg1 = _GdkEvent*]'
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1731:26:   required from 'sigc::slot<T_return, T_arg1, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::slot(const T_functor&) [with T_functor = studio::ZoomDial::ZoomDial(Gtk::IconSize&)::<lambda(int)>; T_return = void; T_arg1 = _GdkEvent*]'
dials/zoomdial.cpp:79:3:   required from here
/usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:89:30: error: no match for call to '(studio::ZoomDial::ZoomDial(Gtk::IconSize&)::<lambda(int)>) (_GdkEvent* const&)'
     { return functor_(_A_arg1); }
                              ^
dials/zoomdial.cpp:76:62: note: candidate: studio::ZoomDial::ZoomDial(Gtk::IconSize&)::<lambda(int)> <near match>
  current_zoom->signal_event_after().connect([this](auto event) {
                                                              ^
dials/zoomdial.cpp:76:62: note:   conversion of argument 1 would be ill-formed:
In file included from /usr/include/sigc++-2.0/sigc++/functors/slot.h:7:0,
                 from /usr/include/sigc++-2.0/sigc++/signal_base.h:27,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from /usr/include/gtkmm-3.0/gtkmm/tooltip.h:8,
                 from dials/zoomdial.h:32,
                 from dials/zoomdial.cpp:35:
/usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:89:30: error: invalid conversion from '_GdkEvent*' to 'int' [-fpermissive]
     { return functor_(_A_arg1); }
                              ^
/usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:89:30: error: return-statement with a value, in function returning 'void' [-fpermissive]
Makefile:1878: recipe for target 'dials/synfigstudio-zoomdial.o' failed
make[1]: *** [dials/synfigstudio-zoomdial.o] Error 1
make[1]: Leaving directory '/home/konstantin/sources/synfig.single/synfig-studio/src/gui'
Makefile:453: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by caryoscelus** [comment]
>error: use of 'auto' in lambda parameter declaration only available with -std=c++14 or -std=gnu++14

This should be the problem. Can you try building with c++14 std?

In case there is a good reason to support old compilers, it shouldn't be hard to rewrite in c++11 standard, though.

**Comment by morevnaproject** [comment]
> Can you try building with c++14 std?

With "-std=c++14" it compiles fine.

We still have to support "C++11". We use pretty old debian distro to build binary packages of synfig. I doubt that it is capable to use "C++14". (Building synfig on old distro gives guarantee that it will run on most modern Linux systems).

**Comment by caryoscelus** [comment]
Which version do you want to keep supporting and for how long? Hopefully current stable debian should be fine as gcc 4.9 supports most of c++14 features.

However, apart from compiling/non-compiling status, there might also be problems with incompatible ABIs.

One way of getting rid of all these problems would be to make "all-in-one" builds with bundled dependencies and only make regular builds for modern systems.

**Comment by morevnaproject** [comment]
> Which version do you want to keep supporting and for how long?

We use wheezy. Will be supporting it until the major block will appear.

> One way of getting rid of all these problems would be to make "all-in-one" builds with bundled dependencies

This is exactly what we do. Please check the Linux builds here - https://morevnaproject.org/synfig/

Right now we almost done migrating package format to AppImage.

**Comment by caryoscelus** [comment]
>This is exactly what we do

Then why build on old system? It shouldn't be a problem to build bundled version on modern system and run on old.

**Comment by morevnaproject** [comment]
> Then why build on old system? It shouldn't be a problem to build bundled version on modern system and run on old.

That's because it is not possible to bundle really ALL dependencies. For example we can't bundle libc. And libc is a subject of ABI incompatibility. This is a long, but well documented story:
- https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#creating-portable-appimages
- http://freegamedev.net/wiki/Portable_binaries

**Comment by caryoscelus** [comment]
I see. Have you tried building current master on that wheezy system (perhaps it might not support -std=c++14, but some support should be there through -std=c++1y or -std=gnu++1y)?

Anyway, my position is that development convenience is generally more important than compatibility with old systems. So for little changes like the one introduced this problem, it's ok to fall back to c++11, but for something more long-term and heavy it's better to use best tools available.

**Comment by probonopd** [comment]
> development convenience is generally more important than compatibility with old systems

That's a very developer-centric rather than user-centric view. Some users appreciate to use LTS versions of the OS for years but still would like to have recent applications. The latest Firefox, for example, still runs on _really_ ancient OSes.

**Comment by caryoscelus** [comment]
@probonopd good for them that they can afford to do that.

**Comment by blackwarthog** [comment]
I've fixed compatibility issues.

And also i've disabled feature with selection of text on click into zoom-widget, because it makes impossible to deselect text or select part of text by mouse. I've tried to make code to select text on widget focused, but don't found the solution.

**Comment by caryoscelus** [comment]
Do you seriously want C++03 compatibility and lack of lack of boost now?

Re: zoom widget selection: why not create issue for that instead of just throwing it away?

**Comment by morevnaproject** [comment]
> Do you seriously want C++03 compatibility and lack of boost now?

As mentioned above, we need that compatibility to build "portable" linux binaries. This is required to ship Synfig packages to end users.

> Re: zoom widget selection: why not create issue for that instead of just throwing it away?

Sorry, this is my fault - I have pushed commits of @blackwarthog too early, without opening discussion.

**Comment by morevnaproject** [comment]
"Zoom widget selection" commit restored - 5609732978d73db

**Comment by caryoscelus** [comment]
>As mentioned above, we need that compatibility to build "portable" linux binaries. This is required to ship Synfig packages to end users.

1. boost is not some cutting-edge tech and should exist on any distro
2. gcc 4.7 in wheezy supports most of c++11 ( https://gcc.gnu.org/gcc-4.7/cxx0x_status.html ). While it might not support c++14, that isn't as essential as 11. (There's also possibility to install newer gcc, but that would require some research, i suppose)
3. replacing c++ code with unsafe c code (scanf, strptinf) is really weird regardless of standards

**Comment by morevnaproject** [comment]
Yes, the boost exists even in our (old) build environment. The logic of @blackwarthog - avoid boost if its can be achieved through "std::" functions. In this case he reduced it to even simpler C code, because it is shorter.

Please feel free to reopen bug and re-write in more comfortable to you way. But please avoid c++14 for now. We need to publish package with all latest changes ASAP, this is why such hurry.

**Comment by caryoscelus** [comment]
Some boost can be avoided by using new C++ cause many parts of it enter standard ;) But if the goal is to avoid boost, it can be avoided everywhere, but the code quality will go down. Shorter code isn't necessarily better - e.g. using const or smart pointers adds verbosity, but also makes code less error-prone.

Ok, then if nobody minds i'll revert the changes and replace original offending part to be C++11 conforming and put it into a separate branch so that you can confirm it builds on your environment before it hits master. If c++11 would sill not work for you, we can continue this compatibility discussion.

**Comment by morevnaproject** [comment]
@blackwarthog Can we setup Travis CI to make it easier to track such issues?

**Comment by blackwarthog** [comment]
ok
