### ISSUE TITLE
Linux version not understands "\" as directory separator

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2723]
**Describe the bug**
Linux version of Synfig does not parses "\\" as directory separator (in image filenames).

**To Reproduce**
1. Download and unpack sample archive - [paths.zip](https://github.com/synfig/synfig/files/9032840/paths.zip)
2. Open `paths.sif` file.
3. See image is not displayed -

![screenshot_005](https://user-images.githubusercontent.com/332868/176997086-add2ba69-eaff-4d8e-8765-29e360c6cd87.png)

In version 1.4.2 it is displayed correctly -

![screenshot_004](https://user-images.githubusercontent.com/332868/176997095-74f6ca0d-c8fc-4135-ab67-d7f7e3d6460e.png)

You can examine image layer, and see its "Filename" property -
![screenshot_006](https://user-images.githubusercontent.com/332868/176997149-4db70a12-a4a2-4b9c-8a15-67336422744f.png)

Notice that it uses "\\" as directory separator. This usually happens when file was created in WIndows version of Synfig.

**Expected behavior**
Synfig should treat both "/" and "\\" as directory separators.

**Comment by morevnaproject** [comment]
Originally reported here - https://forums.synfig.org/t/1-5-1/13295/4

**Comment by rodolforg** [comment]
Ouch.
It should be not stored with "\" :( Now it was, we should support both on loading. Argh.
