### ISSUE TITLE
Low-res rendering is offset on larger zoom levels

### ISSUE THREAD

**Issue by caryoscelus** [synfig/synfig#273]
Specific zoom level to trigger this depends on image size. Offset can be horizontal or vertical.
![lowres](https://cloud.githubusercontent.com/assets/1758893/19784147/b3e152a2-9ca5-11e6-8b55-627f18bb2f44.png)

**Comment by caryoscelus** [comment]
Works for me now.

**Comment by morevnaproject** [comment]
This fix will be shipped with upcoming 1.3.5 build.

**Comment by morevnaproject** [comment]
Now shipped with Synfig 1.3.5 - https://morevnaproject.org/2017/12/25/synfig-studio-1-3-5/
