### ISSUE TITLE
Synfig [2022.07.12-linux64-19589] damages file after saving

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2757]
**Describe the bug**
Error with this Synfig build - [SynfigStudio-1.5.1-testing-2022.07.12-linux64-19589.appimage](https://cloud.morevnaproject.org/s/BWTYjKSya8ZyJQL)

When saving file it cannot be opened again anymore.

Video -
https://www.youtube.com/watch?v=QAnhMPDGp2c

**To Reproduce**
1. Download sample file - [Synfig-22-final-03.sif](https://forums.synfig.org/uploads/short-url/6HAYqRETUIYRx6aclxuQdI0nqNX.sif) and open it in Synfig.
2. Make some changes to file.
3. Save and close the file.
4. Try to open file again -> it shows an error.

**Screenshots**
![screenshot_001](https://user-images.githubusercontent.com/332868/179808937-22cc55a3-93d6-45b7-9c40-822ee753440d.png)

**System information:**
 - OS: Linux Mint 19
 - OS version: Linux Mint 19
 - Commit ID: 19589

**Comment by morevnaproject** [comment]
Original issue on forum - https://forums.synfig.org/t/synfig/13340

**Comment by rodolforg** [comment]
Look the filename parameter of Sound Layer: it is messed up!
https://youtu.be/QAnhMPDGp2c?t=27
