### ISSUE TITLE
Synfig MSVC build didn't start

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#2759]
The issue is in that code:

https://github.com/synfig/synfig/blob/d1192e1d4685b0e4db9d1a0b94423fdcd0b0d90b/synfig-studio/src/gui/docks/dock_soundwave.cpp#L245-L247

guid is empty on start.

UPD:
Linux version pass "-no-audio-" guid.

@hesham-essam 
Can you check which value is passed in your case?

**Comment by hesham-essam** [comment]
I get `guid = -no-audio-`.

**Comment by ice0** [comment]
I'm thinking maybe reproducing this problem depends on the order of initialization of static variables?

Just did a rebuild and the problem is gone.
Rebuild again and luckily it's back.

```
'synfigstudio.exe' (Win32): Loaded 'C:\Windows\System32\WindowsCodecs.dll'. Symbol loading disabled by Include/Exclude setting.
'synfigstudio.exe' (Win32): Loaded 'C:\Windows\System32\shfolder.dll'. Symbol loading disabled by Include/Exclude setting.
The thread 0x5774 has exited with code 0 (0x0).
The thread 0x62c4 has exited with code 0 (0x0).
Exception thrown: read access violation.
layer_sound.**obj** was nullptr.

The program '[28288] synfigstudio.exe' has exited with code 0 (0x0).
```
![Screenshot_33](https://user-images.githubusercontent.com/5604544/180189543-b8230f57-205a-4b88-aa39-98f160ce5b7c.png)

**Comment by hesham-essam** [comment]
It's very likely related to initialization order indeed.
I must've built synfig over 10 times (VS 2022) with different build parallelization options (-j for parallel jobs and --parallel for parallel compilations in the same job, using msbuild and ninja, with external cmake and vs's cmake), but still couldn't reproduce the issue locally.

I will put it on hold temporarily, and fix the other issues.

**Comment by ice0** [comment]
> I will put it on hold temporarily, and fix the other issues.

I noticed that `vcpkg` also has a cache in `%LOCALAPPDATA%\vcpkg` so I will try to remove it and do a clean build tomorrow.

**Comment by hesham-essam** [comment]
Also try removing the "synfig"'s data folder in "C:/Users/<user>/Synfig"

**Comment by ice0** [comment]
It looks like we are somehow working with locales incorrectly.

I noticed that there is an error with my build when I try to open the saved file:

![Screenshot_34](https://user-images.githubusercontent.com/5604544/180396439-9b6b3520-c7fc-4b1a-98d9-ba2948062e44.png)


`Glib::ustring` `operator==` returns false for the same string (after switching locale), and this breaks the whole logic:

Test 1:
```
synfig::ChangeLocale changeLocale(LC_NUMERIC, "");

{
	Glib::ustring test_ustr = "test";
	std::cout << "Result1: " << (test_ustr == "test") << std::endl;
}
std::locale l("");
{
	Glib::ustring test_ustr = "test";
	std::cout << "Result2: " << (test_ustr == "test") << std::endl;
}
```
Output:
```
Result1: 1
Result2: 0
```

Test 2:
```
{
	Glib::ustring test_ustr = "test";
	std::cout << "Result1: " << (test_ustr == "test") << std::endl;
}
std::locale l("");
{
	Glib::ustring test_ustr = "test";
	std::cout << "Result2: " << (test_ustr == "test") << std::endl;
}
```
Output:
```
Result1: 1
Result2: 1
```

After a quick hack on the `get_locale_decimal_point()` function, I didn't notice any problems.
```
get_locale_decimal_point()
{
	return '.';
}
```

**Comment by hesham-essam** [comment]
It's probably that `==` uses `strcmp` like semantics internally (byte wise comparison).
I would guess that at the beginning `UTF-8` is used, and when the locale is changed `UTF-16` is used, or maybe the otherway around.

**Comment by ice0** [comment]
Maybe this will be helpful:
```
inline bool
operator==(const ustring& lhs, const ustring& rhs)
{
  return (lhs.compare(rhs) == 0);
}

int
ustring::compare(const ustring& rhs) const
{
  return g_utf8_collate(string_.c_str(), rhs.string_.c_str());
}
```

**Comment by hesham-essam** [comment]
I would actually suggest always saving files in utf-8 format with specific locale, so that the output format is independent of the machine it is on. This would make it less prone to bugs.

Was it the case that different encodings were the cause? I'm skeptical that `g_utf8_collate` would work with different encodings (utf-8 and utf-16 for example).

**Comment by ice0** [comment]
I don't know why, but this issue is not reproduced now. So I am closing it.
