### ISSUE TITLE
Gif rendering issues

### ISSUE THREAD

**Issue by Darkspace65** [synfig/synfig#277]
Hi!
While writing a tutorial for Synfig I noticed that rendering to Gif in Synfig dev build (synfigstudio-1.1.11-20160727-64bit.exe) on Windows 10 produces anomalies. 
Greetz!

![bouncingball](https://cloud.githubusercontent.com/assets/23108356/19958199/966a3674-a19d-11e6-8ddd-0c367c298903.gif)

**Comment by morevnaproject** [comment]
@Darkspace65 Please specify which module have you used for exporting to gif? Is it "magick++" or "gif"?

**Comment by Darkspace65** [comment]
@morevnaproject I used "gif" which is corrupt, but "magick++" works like a charm. Thanks for the tip. :-) Have to make a note on the wiki about rendering to gif via "magick++" instead of "gif".

**Comment by caryoscelus** [comment]
I guess we should drop "gif" module then to avoid confusion.

**Comment by morevnaproject** [comment]
@caryoscelus Agree. It works worse then magick++ anyway (even regarding file size). Just consider that gif export won't work without Magick++ then.
