### ISSUE TITLE
Segmentation fault when building icons

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#2787]
**Describe the bug**
```
/bin/sh: line 1: 49487 Segmentation fault: 11  /Users/runner/work/synfig/synfig/build-cmake/output/Release/bin/synfig action_add_to_set_icon.sif -o /Users/runner/work/synfig/synfig/build-cmake/output/Release/share/synfig/icons/classic/128x128/action_add_to_set_icon.png --time 0f --quiet
```

https://github.com/synfig/synfig/runs/7767408007?check_suite_focus=true

**To Reproduce**

`Synfig CI / macOS 11 Big Sur (CMake+Ninja) (pull_request) `

**System information:**
 - OS: MacOS
 - OS version: 11

**Comment by rodolforg** [comment]
Even with PR based on previous commits (i.e. not up-to-date with master), this test is failing. :/
See MohamedAdhamc PR...
