### ISSUE TITLE
Move "Default interpolation" dropdown to Preferences dialog

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2856]
I suggest to remove "Default interpolation" dropdown widget from main Synfig window and place it into Preferences ("Edit" -> "Preferences" -> "Editing").

This function is rarely used and after the change the UI become less cluttered.

![screenshot_002](https://user-images.githubusercontent.com/332868/196446630-98a4ff25-2593-4f5a-acbd-9ba92f9e6e47.png)

**Comment by mohamedAdhamc** [comment]
will hopefully start working on this tomorrow (i.e. in about 10 hrs). Just commenting so that if someone already started they would let me know.

**Comment by yoSachinkr** [comment]
I don't think putting **default interpolation** dropdown to preferences dialog is a good idea. 
A synfig file can have different layers and you may want different layers to have different kind of interpolation. Having the dropdown available handy helps in presetting the interpolation before animating a particular layer. Putting it in preferences dialog will just add extra steps if someone wants to work with different interpolation settings for different layers.

**Comment by rodolforg** [comment]
What about both? Default for new empty files in Preferences and one for current file (saved in metadata).
We already have one way for setting default interpolation for layer parameters...

Anyway, I think Konstantin proposed to reduce GUI pollution. Am I right, @morevnaproject ? Any alternative?

**Comment by morevnaproject** [comment]
Hi @yoSachinkr!

Can you please clarify: do you use this dropdown in your daily work?

> A synfig file can have different layers and you may want different layers to have different kind of interpolation.

From my experience, the interpolation type is generally required on per-parameter basis (not per-layer basis).
For that we have possibility to set default interpolation for each parameter -
![screenshot_001](https://user-images.githubusercontent.com/332868/197422351-fe7e3d1a-2318-499f-8315-cdf0ba777a73.png)

**Comment by morevnaproject** [comment]
> Anyway, I think Konstantin proposed to reduce GUI pollution. Am I right, @morevnaproject ? Any alternative?

Exactly. ^_^

**Comment by morevnaproject** [comment]
Additional note: In OpenToonz the default interpolation is also configured only through Prefernces dialog.
![screenshot_002](https://user-images.githubusercontent.com/332868/197422508-4b72bab4-5173-4f73-9d4e-a2166f2ab2e1.png)

**Comment by yoSachinkr** [comment]
> do you use this dropdown in your daily work?

I do use this feature as it's a handy way to work with different interpolation methods.

https://user-images.githubusercontent.com/50204208/197781074-378fd210-545c-467b-a73a-d6d30ce7c203.mp4

That dropdown helps in presetting the interpolation of the properties of layers in a much quicker way.

**Comment by morevnaproject** [comment]
@yoSachinkr 
Got it, thank you for the feedback.
I am closing this then.
