### ISSUE TITLE
Changing interpolation of Canvas parameter changes interpolation for other waypoints

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2857]
This is an issue related to recently added buttons, which allow to change interpolation - https://github.com/synfig/synfig/pull/2615

If we will select a Group layer and try to change interpolation for waypoints of Canvas parameter, then it changes interpolation for other parameters of this Group layer.

This shouldn't happen because Canvas parameter of group layer represents waypoints of all _child_ layers inside of the group layer.

Demo:
![Peek 2022-10-18 21-59](https://user-images.githubusercontent.com/332868/196468594-374ffbc0-6607-44ae-a1a1-84c07c78cf18.gif)

Steps to reproduce:
1. Download sample file - [Synfig Animation 3.sifz.zip](https://github.com/synfig/synfig/files/9811828/Synfig.Animation.3.sifz.zip)
2. Select Group layer
3. Select waypoints which belong to Canvas parameter
4. Click any Interpolation button on the right of TimeTrack
5. bug - all waypoints of Group layer will change.

Expected behavior: only selected waypoints should be changed.

@mohamedAdhamc can you take a look, please? :)

**Comment by mohamedAdhamc** [comment]
@morevnaproject oops, I just replicated. ok, I will look into it.
