### ISSUE TITLE
Rename "Target" to "Module"

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2862]
In render dialog there is a dropdown to choose render module. It is called "Target".
I suggest to rename it to "Module".

![screenshot_001](https://user-images.githubusercontent.com/332868/197731489-5edb8cb2-f7a7-4f06-a37c-f02d9a23cb7e.png)

**Comment by rodolforg** [comment]
What about "Renderer"?

**Comment by morevnaproject** [comment]
I am afraid that we already have "Renderers" ^__^

![screenshot_002](https://user-images.githubusercontent.com/332868/200118952-5c3c8e93-a957-4e03-976e-2960fdf24555.png)
