### ISSUE TITLE
No context menu when right-clicking on waypoint

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2875]
This is reproducible in current master branch (8bf9c30).

1. Download and open sample file - 
[wp-right-click-bug.sifz.zip](https://github.com/synfig/synfig/files/9961597/wp-right-click-bug.sifz.zip)
2.  Select group "1".
3. Try right-clickig on waypoints, which I indicated on screenshot below -
![screenshot_001](https://user-images.githubusercontent.com/332868/200579147-3adb7bb8-5d6e-4fca-a362-19b6be8dd806.png)

Notice that no menu shown after right-click.

For other waypoints menu show normally.

This seems to be related with #2858 fix.

@mohamedAdhamc can you take a look, please? ^__^

**Comment by mohamedAdhamc** [comment]
@morevnaproject sure, I will hopefully start looking into it tonight :).
