### ISSUE TITLE
Parameters panel alternate row color

### ISSUE THREAD

**Issue by pgilfernandez** [synfig/synfig#2884]
**Is your feature request related to a problem? Please describe.**
Sometimes it's hard to match a waypoint with its parameter as there is no row visual helper. It indeed depends on situations, if you have just animated a parameter then it is obvious, but when you have a layer with lot of parameters animated it is when this UX issue raises:

![lines_now](https://user-images.githubusercontent.com/5942369/202133371-f2a186e9-264f-4c53-a854-5a9f7792e6e8.jpg)

**Describe the solution you'd like**
I would say this can be pretty easily setup with a GTK style but I don't know how it is coded inside Synfig. So, I would suggest to have something like the following:

![lines_suggested](https://user-images.githubusercontent.com/5942369/202133608-adff90bc-92b4-4f86-be28-99eaa49b26c0.jpg)

**Describe alternatives you've considered**
IMHO this feature could be added to Preferences panel so that users can set that color as their will.

**Additional comments**
none

**Comment by Keyikedalube** [comment]
I believe there's a similar issue to this opened by @FirasH a year/s ago.

> I would say this can be pretty easily setup with a GTK style

Yes and no.
I tried experimenting app theming some months back. Figured if one manually code styled alternate rows you also had to do it for all custom themes gtk already has (Adwaita, Adwaita dark, Materia, Numix, and so on)

I believe the proper way would be to implement a Synfig specific standard theme like GIMP did. GTK dev encourages that so uniform app branding is guaranteed across all platforms.

**Comment by FirasH** [comment]
@Keyikedalube , that's right, here it is: #2132

**Comment by pgilfernandez** [comment]
Thanks, it looks like it is harder than expected...
It would be nice that GTK 3.0 CSS would work but I could get any usable style by adding code to gtk-keys.css (which looks like the only available CSS file to add some code in)

Any class I try doesn't work... only:
```
* {
background: red;
}
```
It looks like `treeview`doesn't work any more... at least in this gtk-keys.css file

**Comment by Keyikedalube** [comment]
Closing this since https://github.com/synfig/synfig/issues/2132 issue request the same feature.

Thanks for opening :)
