### ISSUE TITLE
AppVeyor Windows build does not start

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#2885]
**Describe the bug**
The latest builds of Synfig Studio from AppVeyor do not start on Windows.

**To Reproduce**
1. Download latest AppVeyor build
2. Start `synfigstudio.exe`

A system error pops-out saying that `libpcre2-8-0.dll` is missing and it's required to reinstall the software.

**System information:**
 - OS: Windows
 - OS version: 10
 - Commit ID: 94b9861

**Comment by ice0** [comment]
@FirasH 

Fixed.
