### ISSUE TITLE
Hotkey for Duplicate Layer button

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#2891]
`ctrl + d` hotkey for "duplicate layer" function would help speed up artwork creation in Synfig.
![image](https://user-images.githubusercontent.com/50204208/202483565-3f8d7711-1530-457d-818e-28256d4b370f.png)

**Comment by BobSynfig** [comment]
For sure but it would be nice but prone to introduce new bugs:
We have to take account of how much deep we duplicate ("leaf" layer or even tree/branch?)
and GUIDs to be unique; linked values and converters...
(similar issues as bones/skeletons duplication to be expected)

**Comment by mohamedAdhamc** [comment]
hmm, i'm curious here as how the hotkey/accelerator itself would produce these bugs ? AFAIK the layer-duplicate action is already present and this would be just mapping it to the accelerator or am i wrong ?

**Comment by BobSynfig** [comment]
Ah ok, just the hotkey would be fine, if the existing fonction is already safe then no reason of additional bug.
Nevermind, I read wrong!
