### ISSUE TITLE
Perspective layer produces artefacts on sewing

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#2894]
**Description**
When two or more perspective layers meet they produce a visible line in that place. Check out this picture:
![WarpAA](https://user-images.githubusercontent.com/28569334/202864608-6972b4f2-0d11-46f5-bf27-662eb2a3ae9a.png)
You can see a line in the middle of a cube right where warp layers meet.
This bug makes it very hard to align textures.

I assume it's because anti-aliasing is enabled for this layer which produces feathering on edges, but it's just a guess, of course. Whatever the cause it would be nice to have it fixed. If anti-aliasing is a problem, then we can introduce an option to disable it just like in the 'Region' layer for example.

**How to reproduce the problem**
* Open attached file, render current frame, you'll see the artifact just like in the image above
* Disable perspective layers, render one frame again - there's no more visible line
[WarpAA.zip](https://github.com/synfig/synfig/files/10047659/WarpAA.zip)

**Expected behavior**
There should be no visible line between two perspective layers.

**System information**
 - OS: Windows 10 x64
 - OS version: Not important
 - Commit ID: 71a30418475bf1800d97b1437561a22272cad02d

**Comment by yoSachinkr** [comment]
![image](https://user-images.githubusercontent.com/50204208/210100134-581ef930-8685-4021-a2c7-86e5c47679b8.png)

**Comment by Svarov-RZM** [comment]
> ![image](https://user-images.githubusercontent.com/50204208/210100134-581ef930-8685-4021-a2c7-86e5c47679b8.png)

I am not talking about regions, I am talking about **perspective** layers. They don't have Anti-Aliasing option like regions, so it's not possible to match them well together without producing a visible line like shown in the top image.

**Comment by Svarov-RZM** [comment]
I am closing this.
Turns out, it is possible to disable anti-aliasing by setting "Interpolation" parameter to "Nearest Neighbor" and the line disappears.
