### ISSUE TITLE
Eyedrop Tool should take fill color by default

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2899]
![screenshot_005](https://user-images.githubusercontent.com/332868/203082620-abee1094-6065-4857-9a2e-7ad9faacc6d4.png)

Currently Eyedrop Tool has the following behavior in master branch:
- click on workarea picks color and puts it into the  **OUTLINE** color
- Ctrl+click  on workarea picks color and puts it into the  **FILL** color

I suggest to swap this behavior:
- click on workarea picks color and puts it into the **FILL** color
- Ctrl+click  on workarea picks color and puts it into the **OUTLINE** color

![screenshot_006](https://user-images.githubusercontent.com/332868/203083692-17076a8c-9b63-4af8-9853-666da96b4940.png)

**Comment by mohamedAdhamc** [comment]
Writing here just in case someone already started, I will be working on this along-side related #2900, starting tomorrow hopefully   : ).
