### ISSUE TITLE
SVG import crash

### ISSUE THREAD

**Issue by algorev** [synfig/synfig#290]
On Mac OS X, SynfigStudio crashes when importing SVGs. Tested with this file:
https://www.dropbox.com/s/a8f5jyjmnhabopu/ScratchCat.svg?dl=0

**Comment by caryoscelus** [comment]
Which version do you use?

Doesn't crash for me on gnu linux, but hangs instead. Another svg that results in hanging: https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg

Some simple svgs created with inkscape work though.

**Comment by SpooikypokDev** [comment]
I use SVG 1.1. The only feature not necessarily used in most svgs but used in this file is groups. That may be the cause of the problem...

**Comment by SpooikypokDev** [comment]
I tried to remove the <g></g> tags, but it seems not to be the problem.

**Comment by caryoscelus** [comment]
I meant version of Synfig, not svg.

**Comment by infusiastic** [comment]
I have this as well with Synfig 1.2.0 for OS X.
