### ISSUE TITLE
Feature request: Separation of horizontal and vertical scaling of Graph Panel

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#2926]
**Is your feature request related to a problem? Please describe.**
In synfig, when we hold `ctrl `and `scroll` in the graph panel, the graph panel scales horizontally and vertically simultaneously.

**Describe the solution you'd like**
It'd be convenient if we could be able to scale the graph panel horizontally and vertically separately. May be by using `ctrl + scroll` to scale vertically and `alt + scroll` to scale horizontally. This feature will be useful when the graph is too tall or too wide and when we just want to shorten the tallness or wideness of the graph.

**Comment by rodolforg** [comment]
They are separated, aren't they?
`ctrl`+`scroll` (or `scroll` over time mark bar): horizontal zoom
`ctrl`+`shift`+`scroll`: vertical zoom
