### ISSUE TITLE
Can the PIXEL_RENDERING_LIMIT be set to a FullHD equivalent of 2100000?

### ISSUE THREAD

**Issue by zeddicus-pl** [synfig/synfig#2943]
**Is your feature request related to a problem? Please describe.**
When you are working on FullHD frames (1920x1080) things like radial blur get cut-off at 781px of height, example:

(you won't see this on white background as there is white radial blur underneath the figure in the front, that is cut-off)
![tyrael](https://user-images.githubusercontent.com/79473394/208169503-24f47271-4a43-4353-b54b-6330e624da6b.png)

**Describe the solution you'd like**
Change it to 2100000 (the exact number for FullHD is 2073600)

**Comment by BobSynfig** [comment]
This reminds me something https://github.com/synfig/synfig/issues/711 (closed)

**Comment by zeddicus-pl** [comment]
@BobSynfig it is indeed similar, but not the same. The previous one was caused by the code splitting the render into pieces incorrectly - in this example it is correctly doing that **however** there is a different issue.

For my that looks like when the radial blur is calculated, on the start of the next "frame" it starts from a "blank" space, causing the blur to be inconsisten.

I understand that this limit or 1.5 pixel was introduced due to some technical limitations of some system/graphic card. On windows 11, on a gaming laptop that's not an issue at all. And this bug prevents from correctly rendering FullHD frames (which, let's be honest is nothing special these days).

For me that's a deal breaker, and I couldn't use this app. Fortunately I'm a developer so I can just change it :)

Could this be configurable in the settings maybe?
