### ISSUE TITLE
Linux 64 bit AppImage for Synfig Studio 1.2.0: libbz2.so.1.0 not found

### ISSUE THREAD

**Issue by VirgilioVasconc** [synfig/synfig#296]
**Synfig version & platform**:
Linux 64 bit AppImage for Synfig Studio 1.2.0 on Fedora 24

**Issue description**:
When trying to execute the file (already with chmod +x) I get the following error:
/tmp/.mount_LxT1CA/usr/bin/synfigstudio: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

I've renamed the file to ".tar" and browsed through its contents and couldn't find that library.

**Comment by caryoscelus** [comment]
I am not involved in making appimages, but i would suppose that this library was expected to be a system one. Though i should say that on my debian sid i don't have it either (only `libbz2.so` without suffix).

**Comment by morevnaproject** [comment]
Assigned to @blackwarthog

**Comment by blackwarthog** [comment]
@VirgilioVasconc can you run following command to check all missing libraries at once:

./synfigstudio-1.2.0-64bit.appimage --appimage-exec ldd bin/synfigstudio

so we can add copies of all of them into appimage

**Comment by VirgilioVasconc** [comment]
Hi, @blackwarthog, I've run it with `grep "not found"` to map only the missing libraries:

```
./synfigstudio-1.2.0-64bit.appimage --appimage-exec ldd bin/synfigstudio | grep "not found"
	libbz2.so.1.0 => not found
	libbz2.so.1.0 => not found
	libbz2.so.1.0 => not found

```
All other libraries seems to be ok. :)

**Comment by probonopd** [comment]
My general recommendation is to include all BUT [these](https://github.com/probonopd/AppImages/blob/master/excludelist).

**Comment by morevnaproject** [comment]
Hello! @blackwarthog fixed appimages now. Please download updated version - https://gumroad.com/l/synfig
