### ISSUE TITLE
error: use 'template' keyword to treat 'assign' as a dependent template name

### ISSUE THREAD

**Issue by ryandesign** [synfig/synfig#298]
**Synfig version & platform**:

etl 0.04.22
synfig 1.2.0
macOS Sierra 10.12.3 beta
Xcode 8.2.1

**Issue description**:

After applying the fix from #297 synfig still does not build:

```
In file included from rendering/software/renderersw.cpp:70:
In file included from rendering/software/function/fft.h:30:
rendering/software/function/array.h:435:58: error: use 'template' keyword to treat 'assign' as a dependent template name
                for(Iterator i(*this); i && j; ++i, ++j) i.get_array().assign<TT>(j.get_array());
                                                                       ^
                                                                       template 
rendering/software/function/array.h:440:50: error: use 'template' keyword to treat 'process' as a dependent template name
                { for(Iterator i(*this); i; ++i) i.get_array().process<function>(x); }
                                                               ^
                                                               template 
rendering/software/function/array.h:446:58: error: use 'template' keyword to treat 'process' as a dependent template name
                for(Iterator i(*this); i && j; ++i, ++j) i.get_array().process<function, TT>(j.get_array());
                                                                       ^
                                                                       template 
rendering/software/function/array.h:451:50: error: use 'template' keyword to treat 'process' as a dependent template name
                { for(Iterator i(*this); i; ++i) i.get_array().process<function>(); }
                                                               ^
                                                               template 
4 errors generated.
```

I am not a C++ programmer so I don't feel confident to attempt to fix this myself.

**Comment by ryandesign** [comment]
> I am not a C++ programmer so I don't feel confident to attempt to fix this myself.

Applying this patch does allow synfig to build:

```diff
--- src/synfig/rendering/software/function/array.h.orig	2016-11-30 05:00:57.000000000 -0600
+++ src/synfig/rendering/software/function/array.h	2017-01-13 01:00:35.000000000 -0600
@@ -432,23 +432,23 @@
 	void assign(const Array<TT, Rank> &x) const
 	{
 		typename Array<TT, Rank>::Iterator j(x);
-		for(Iterator i(*this); i && j; ++i, ++j) i.get_array().assign<TT>(j.get_array());
+		for(Iterator i(*this); i && j; ++i, ++j) i.get_array().template assign<TT>(j.get_array());
 	}
 
 	template<typename function>
 	void process(const Type &x) const
-		{ for(Iterator i(*this); i; ++i) i.get_array().process<function>(x); }
+		{ for(Iterator i(*this); i; ++i) i.get_array().template process<function>(x); }
 
 	template<typename function, typename TT>
 	void process(const Array<TT, Rank> &x) const
 	{
 		typename Array<TT, Rank>::Iterator j(x);
-		for(Iterator i(*this); i && j; ++i, ++j) i.get_array().process<function, TT>(j.get_array());
+		for(Iterator i(*this); i && j; ++i, ++j) i.get_array().template process<function, TT>(j.get_array());
 	}
 
 	template<typename function>
 	void process() const
-		{ for(Iterator i(*this); i; ++i) i.get_array().process<function>(); }
+		{ for(Iterator i(*this); i; ++i) i.get_array().template process<function>(); }
 };
 
 template<typename T>
```

I don't know if that's the correct fix.

**Comment by caryoscelus** [comment]
Please specify how are you building synfig (cmake or autotools), where did you get the source (git (tag? master?) or release tar.gz) and compiler version.

**Comment by blackwarthog** [comment]
@ryandesign yes your patch is the right way to solve the problem. Thanks a lot!

**Comment by ryandesign** [comment]
> Please specify how are you building synfig (cmake or autotools), where did you get the source (git (tag? master?) or release tar.gz) and compiler version.

autotools
The synfig-1.2.0.tar.gz tarball on SourceForge
Apple LLVM version 8.0.0 (clang-800.0.42.1)

**Comment by caryoscelus** [comment]
Perhaps it should be fixed by passing standard flags instead of changing code, then. Can you try to build with `-std=c++11`, `std=c++14` or `-std=c++1y` options?

**Comment by ryandesign** [comment]
Your configure script automatically added `-std=c++11`. If you would like me to try changing it, how would I instruct your configure script to do that?

Does synfig (or ETL or synfigstudio) (now) require C++11? (or C++14?)

**Comment by caryoscelus** [comment]
Tried clang myself and i get these errors too, with both 11 and 14 standard, while gcc doesn't give even a warning, even when non-gnu version of standard is chosen. I wonder if gcc still implicitly enables some extension or if it's a compiler bug in clang or gcc.

AFAIR (i don't use autotools anymore) you can pass flags through CXXFLAGS environment variable, but since i've already tried clang you don't need to.

I have no idea about 1.2.0 requirements. The code i write is C++11/14, but it's not what caused build failure for you here.
