### ISSUE TITLE
Z-Depth not Working Properly

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#299]
**Synfig version & platform**:
Synfig version 1.2.0 - Windows 10

**Issue description**:
Z-Depth doesn't working properly, **except if the entire layer grouped in another group**
Looks like the canvas itself lost its entity as a group

[Bug Pictured as sifz.zip](https://github.com/synfig/synfig/files/706678/Bug.Pictured.as.sifz.zip)

**Comment by blackwarthog** [comment]
Fixed, thanks!

**Comment by FadhilKwan** [comment]
you're welcome, sir! :D

**Comment by morevnaproject** [comment]
This fix now available in the latest development version - https://morevnaproject.org/2017/02/04/synfig-studio-1-3-1-development/
