### ISSUE TITLE
error library GDI32.dll

### ISSUE THREAD

**Issue by markoletto** [synfig/synfig#3004]
Good morning,
I have downloaded and installed SynfigStudio version 1.4.4. When I try to start the software I get this message: "impossibile trovare il punto di ingresso ScriptIsComplex della procedura nella libreria di collegamento dinamico GDI32.dll".
I have tried reinstalling the Italian language package of the "Visual C++ Redistributable for Visual Studio 2013" but the problem has not been solved.
My pc has the Windows 7 Home Premium 64-bit operating system with service pack 1.
What will be the problem?
Thank you for your support.

**Comment by ice0** [comment]
@markoletto 

Hi!
Can you try this build?
https://cloud.morevnaproject.org/s/jES3xeaJKFcysaz

I only have Win 7 (x32) so I can't test it right now.

@morevnaproject 
Collected information:

Load order:
![image](https://user-images.githubusercontent.com/5604544/218453359-b6582bf3-6688-4622-8363-738541cbae3f.png)

Dumpbin info:
```
dumpbin /imports libpangowin32-1.0-0.dll | grep -i \.dll
Dump of file libpangowin32-1.0-0.dll
    libpango-1.0-0.dll
    libglib-2.0-0.dll
    libgobject-2.0-0.dll
    GDI32.dll
    KERNEL32.dll
    msvcrt.dll
    USER32.dll
    USP10.dll
    libgcc_s_dw2-1.dll
```

After this PR (https://github.com/morevnaproject/morevna-builds/pull/104/files) libraries should be in the correct order, but looks like they are not.

**Comment by ice0** [comment]
@morevnaproject 
[SynfigStudio-1.4.4-testing-2023.02.09-win64](https://cloud.morevnaproject.org/s/jES3xeaJKFcysaz/download) works fine on Windows 7. Can you build an x86 version for testing?

**Comment by markoletto** [comment]
Hi,
I installed test version 1.4.4. of SynfigStudio (2023.02.09-win64) and the application now starts without errors on my Windows 7.
Thank you very much for the solving support!

**Comment by morevnaproject** [comment]
32bit version - https://cloud.morevnaproject.org/s/CL2tLfBfWba37AX

**Comment by morevnaproject** [comment]
Let's keep this open until I update the builds on the server

**Comment by markoletto** [comment]
Sorry...

**Comment by morevnaproject** [comment]
No problem :)

**Comment by morevnaproject** [comment]
Official builds are updated now - https://www.synfig.org/2023/04/05/windows-builds-updated-for-version-1-4-4/
