### ISSUE TITLE
Dev version not rendering sound layer

### ISSUE THREAD

**Issue by wooxy** [synfig/synfig#3008]
**Describe the bug**
I have noticed that when rendering anything with imported .wav file, I can make various avi, mp4 etc that work fine with the released version of 1.5.synfig.git 1 (linux), but same .sifz when rendered fred Development 1.5.1 I build from cloning there is no sound layer in the rendered files.  I looked again using ffprobe to be sure.  

**To Reproduce**
1. Make any synfig composition and import a .wav file.
2. verify that it plays in Synfig
3. Render it as (default) avi once eack from released 1.5.1 and once from development 1.5.1
4. ffprobe (or simply trying to play the resulting avi file) will reveal that only one of them contains sound.

**Expected behavior**
I don't think you will be able to render / create any file containing audio using Development 1.5.1

**System information:**
 -Ubuntu 22.10
 - OS version:
 - Synfig version: (Development)1.5.1 built today from http://github.com/synfig/synfig.git

**Comment by rodolforg** [comment]
Do you have MLT++ dev packages installed?

The audio playback (and "rendering") is done based on this framework.

**Comment by wooxy** [comment]
I do not.  That is almost certainly the problem.  Thanks,
