### ISSUE TITLE
Constrain keyboard events to active text field

### ISSUE THREAD

**Issue by adrian5** [synfig/synfig#303]
When typing in Parameter fields, keys like `Home` and `End` register with the global UI, instead of acting on the active cursor. It would be nice if text fields behaved in accordance with what has become the standard across applications and operating systems (I don't know if has ever been formalized anywhere or evolved organically).

In that spirit, it would also be good if the user could toggle through parameters (textual or not) via the TAB key.

**Comment by caryoscelus** [comment]
Related: #257

**Comment by morevnaproject** [comment]
Fixed via #898

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
