### ISSUE TITLE
Can't download synfig from synfig.org

### ISSUE THREAD

**Issue by wgw** [synfig/synfig#3030]
Is the download site dead? I can't seem to signup for the forum on synfig.org either. 

https://downloads.synfig.org/stable/SynfigStudio-1.4.4-2022.12.25-win64-b8d62.exe

hangs. 

I can get the source from github....but the windows exec would be ....easier.

Offered here though, but I don't know if filehippo is legit:
https://filehippo.com/download_synfig-studio/post_download/?nodl=1

Suggestions?

(Looks like a brilliant piece of software...)

**Comment by wgw** [comment]
Sorry, I downloaded the package from here, github, so issue somewhat closed. Unsure why the synfig.org forum isn't working (?).

**Comment by morevnaproject** [comment]
Hi! Thank you for reporting! I am looking at the issue now...
