### ISSUE TITLE
Feature request: Gui handles for Bevel layer

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#3042]
Gui handles for the following 3 parameters of Bevel layer will improve usability of the layer.
1.  Light angle (represented by angle handle in the gui)
2. Depth of Bevel (represented by circle handle in gui)
3. Softness ( represented by circle handle in gui)
(kind of like the star region handles)
![image](https://user-images.githubusercontent.com/50204208/230603775-bd582e57-7a27-4e2d-bf1b-5ecccf44b2d9.png)
![image](https://user-images.githubusercontent.com/50204208/230603828-9888162d-e235-4fe0-9419-699cc92eec3c.png)

**Comment by rodolforg** [comment]
@yoSachinkr Like #3044 ? :)

**Comment by yoSachinkr** [comment]
@rodolforg Works perfectly! 😀👍
