### ISSUE TITLE
Noise distort layer not working in Synfig 1.2.0 and 1.3.0

### ISSUE THREAD

**Issue by boubouh** [synfig/synfig#305]
**Synfig 1.2 and 1.3 & lunix and windows**:
![capture](https://cloud.githubusercontent.com/assets/5199504/22176612/7036b322-e006-11e6-979b-e1999f0a73af.PNG)

**noise distort layer not working in new Synfig 1.2.0...**:

**Comment by morevnaproject** [comment]
Noise Distort is actually works, it just applies some weird transformation to underlying layers. See example file - http://sync.morevnaproject.org/seafile/f/fd2a9d2955/?raw=1
(try to disable distortion to see the effect).

Of course this should be fixed. Assigning to @blackwarthog.

**Comment by morevnaproject** [comment]
This fix now available in the latest development version - https://morevnaproject.org/2017/02/04/synfig-studio-1-3-1-development/

**Comment by morevnaproject** [comment]
This fix now available in the latest development version - https://morevnaproject.org/2017/02/04/synfig-studio-1-3-1-development/
