### ISSUE TITLE
Link to Skeleton

### ISSUE THREAD

**Issue by adamfbuchanan** [synfig/synfig#306]
[This method](https://www.youtube.com/watch?v=P65_ACqWxbQ&t=117s) does not work in the synfig im running. I have tried in both the latest stable and testing versions. mac osx.
I do exactly what is stated in the video. After I have done what the video says, and the bones should be connected to the image, the bones and image are not connected. I move a bone and the image does not move. Can you help?

Three screen shots: selecting the spline layer and bone layer, linking to skeleton, and then the bone is not moving the spline shape. 
<img width="1278" alt="screen shot 2017-01-22 at 11 26 39 am" src="https://cloud.githubusercontent.com/assets/25273836/22179128/01aaa5c2-e096-11e6-9888-07850d990ffd.png">
<img width="1280" alt="screen shot 2017-01-22 at 11 26 48 am" src="https://cloud.githubusercontent.com/assets/25273836/22179129/01ad6f1e-e096-11e6-971b-4b04bbd8fe6c.png">
<img width="1280" alt="screen shot 2017-01-22 at 11 27 05 am" src="https://cloud.githubusercontent.com/assets/25273836/22179130/01b092e8-e096-11e6-8010-24d11af98624.png">

**Comment by adamfbuchanan** [comment]
Hi Caryoscelus. 
I see you added a 'Bones' label to the the thread. I also see no replies have happened yet. Im new to this forum, should i (and how would I) add more 'labels', 'projects', and 'milestones' to boost the threads activity?
Thanks 
Adam :)

**Comment by caryoscelus** [comment]
Hi, Adam. FIrst of all, this is not really a forum, it's an issue tracker (forum is here: http://www.synfig.org/forums/). You can't add labels etc cause you're not owner/collaborator on this repo and in any case it isn't for boosting activity - more like for keeping track of things.

As for lack of replies - it only means that nobody who hangs around here/receiving notifications either can't do much about it or is busy to attend to the issue now. If your goal is to receive help (as opposed to having bug fixed), forum is a better place - there are more active users who can't fix issue, but can help with workaround or advice.

**Comment by morevnaproject** [comment]
Hello Adam,
You need to set bone influence area (controlled by purple dots) to cover points of your shape. After that use "Link to Skeleton" command. 
![screen-13](https://cloud.githubusercontent.com/assets/332868/22334604/fb3a5a18-e40d-11e6-9156-2a8b9902399d.png)

**Comment by adamfbuchanan** [comment]
Awesome. it works! 👍 👍 👍
