### ISSUE TITLE
build with ffmpeg6

### ISSUE THREAD

**Issue by zlice** [synfig/synfig#3062]
This is a basic patch I did to get ffmpeg6 to build (should compile with 5 too)

[synfig-ffmpeg6.patch.txt](https://github.com/synfig/synfig/files/11408246/synfig-ffmpeg6.patch.txt)

There should be more `ifdef`s but this should be good enough to make those.

**Comment by rodolforg** [comment]
Hi, @zlice .

Did you try the code from master branch?

**Comment by zlice** [comment]
nope lol. sry, just going through random packages. i'll snag a diff from there for a patch and close this.
