### ISSUE TITLE
Synfig Studio doesn't open on Mac OS X Sierra

### ISSUE THREAD

**Issue by genete** [synfig/synfig#307]
**Version and operating system**
synfigstudio - 1.3.0 - 20170114
OS X 10.12.2

**Issue description**:
After install Synfig Studio at the Applications folder it refuses to open. Gatekeeper offers the "Open anyway" button after refuse to run applications from not recognized developers, but after press button button, after a while the bouncing Synfig Studio icon on dock vanishes.

Sequence of operations:

1. Install SynfigStudio at the Applications folder (more than 2 GB) 
2. Double click the icon. Bounces at the dock 
3. "Verifying SynfigStudio"... (takes a while)
4. "SynfigStudio can't be opened because it comes from a non identified developer". 
5. Go to System Preferences > Security and privacy. Press the "Open anyway" button
6. Icon bounces at the dock... Verifying ...
7. Are you sure that you want to open "SynfigStudio"? Yes
8. "Verifying SynfigStudio"... (takes a while)
9. And the dock icon vanishes. :(

Also happens with 1.2.0 stable version.

**Comment by morevnaproject** [comment]
Hello, Carlos! Does it works when trying to run Synfig app directly from DMG archive?

**Comment by genete** [comment]
How can I do that? Which binary to execute and with which parameters?

**Comment by morevnaproject** [comment]
Just open DMG container and click SynfigStudio icon inside.

**Comment by genete** [comment]
It happens exactly the same than explained at the beginning (except step 1.)

**Comment by genete** [comment]
In past versions I think it has happened too and I barely remember that it is possible to open the Contents folder and run synfigstudio executable from the terminal to know what's happening on run time (error messages).
Can you remind me how to proceed?

**Comment by morevnaproject** [comment]
Please try to follow instructions on this page - http://wiki.synfig.org/Doc:Troubleshooting_Synfig_on_OSX

**Comment by genete** [comment]
I've done this:

- Updated XQuartz
- Reboot
- Double click on DMG package synfigstudio icon
- After verifying it told me that **package was corrupt**! 
- Started it over by downloading the package again and checking the shasum. 
- It opened finally!

Notes: first downloaded dmg package had correct and same shasum than second downloaded package.

**Comment by genete** [comment]
Again happen the same thing.
Using same OS X and newest synfigstudio-1.3.1-20170202.dmg
It repeats the steps from 1 to 9 exactly the same.
Running `/tmp/skl/SynfigStudio/Contents/Resources/synfig/bin/synfigstudio` gives:
`-bash: /tmp/skl/SynfigStudio/Contents/Resources/synfig/bin/synfigstudio: No such file or directory`
Ideas?
Now double clicking again the icon just do **nothing**.

**Comment by genete** [comment]
```
shasum synfigstudio-1.3.1-20170202.dmg 
10e6b6122aaec86f897687f7880e0b774f5ec24a  synfigstudio-1.3.1-20170202.dmg
```
which is correct

**Comment by genete** [comment]
Tied this:
Double click icon on DMG package > Verifying SynfigStudio > Not recognized developer, Open? -> Yes > Icon vanishes. :-(

**Comment by morevnaproject** [comment]
Hello @genete, do you run from Applications directory or directly from DMG archive?

Second, please do the following steps:

1. Reboot your Mac.
2. Open DMG package you downloaded and double-click SynfigStudio app to run it (this step is necessary even if nothing happens after that).
3. If it doesn't run and no error message is given, then open terminal window and execute: `ls /tmp/skl/SynfigStudio/Contents/Resources/synfig/bin/` Please post output here.
4. Next, run `/tmp/skl/SynfigStudio/Contents/Resources/synfig/bin/synfigstudio` (please post messages that you get after that command)

**Comment by genete** [comment]
> do you run from Applications directory or directly from DMG archive?

Last time I tried from the Applications directory and the DMG archive with same result.

>  1. Reboot your Mac.

Done

>  2. Open DMG package you downloaded and double-click SynfigStudio app to run it (this step is necessary even if nothing happens after that).

Done. After double click it took long time to do the "Verifying SynfigStudio" task (12 minutes). It said: "SynfigStudio can't be opened because we cannot confirm developer identity". So went to System Preferences > Security and Privacy and asked to open it anyway. It Verified it a second time (quick) and then asked me to open one Synfig Studio and accepted. After a while Synfig Studio **opened**.

So now, once I close Synfig Studio, how should I run it again? Should I install it to the Applications folder or should I run it from the DMG again?

**Comment by morevnaproject** [comment]
I am strongly suspect the problem comes when you copy Synfig into your Application folder.

Look, here is how it works:
When you launch Synfig Studio (by clicking on its icon) it creates a symlink at `/tmp/skl/SynfigStudio/`. And then application started from there. When you reboot your mac the contents of /tmp dir is automatically  erased. This is why IT IS USELESS to invoke any terminal commands if you didn't clicked on Synfig icon.

So, if Synfig doesn't start (when you click on icon), then you can troubleshoot the problem by doing the following steps:

1. Open terminal window and execute: `ls /tmp/skl/SynfigStudio/Contents/Resources/synfig/bin/`. Please post output here.
2. Next, run `/tmp/skl/SynfigStudio/Contents/Resources/synfig/bin/synfigstudio` (please post messages that you get after that command).

Also, it would be good to note where did you started Synfig from - Appliactions or DMG?

I also suspect you did started several copies in parallel, shich is caused conflicts (because they used the same `/tmp/skl/SynfigStudio/` prefix.

**Comment by genete** [comment]
Let's summarize the **current** situation of the application in my computer:

1. I don't have Synfig Studio installed in the Applications folder. I had it in the 1.2.0 and the 1.3.0 versions but starting with 1.3.1 I have removed the application from there and I have never copied it to Applications folder again.
2. Known the above, **I always double clicked the icon of the DMG folder** of the 1.3.1 version.
3. Currently **there is not trouble opening Synfig Studio** (it runs fine btw) but it obligates me to pass through the Security and Privacy from System Preferences **every time**. 

So my question is: Should I install Synfig Studio into the Applications folder to run it from there (and supposedly avoid the cumbersome Security and Privacy dialog)?

**Comment by morevnaproject** [comment]
Yes, please try to copy to Application folder and let's see what happens.

**Comment by genete** [comment]
Congratulations! Phew! Finally it opened and doesn't ask me never go through Security and Privacy dialogue! Thank you very much!!!!

**Comment by eltiare** [comment]
I'm running this on El Captain and having this problem. If I start it from the commandline it works fine with some warnings output to the console.

**Comment by morevnaproject** [comment]
@eltiare Please clarify what do you mean by "the same" problem (the discussion above includes several different symptoms).

**Comment by eltiare** [comment]
@moreevnaproject: Sorry. I mean it puts up the prompt saying "Verifying SynfigStudio" that sits there for a long time before saying it can't be opened because it's from an unidentified developer. When I go to the control panel to launch it anyway, nothing happens.

**Comment by eltiare** [comment]
Scratch that. After several minutes the process starts all over again. It only appeared to be nothing because it took so long to start.

**Comment by technobrat** [comment]
I am using Yosemite and had to use the following command because the above suggestions did not work
>>>  sudo defaults write com.apple.frameworks.diskimages skip-verify true

**Comment by morevnaproject** [comment]
@technobrat Thank you for the hint! Right now we are working on reducing the size of OSX package, which should eliminate this issue.

**Comment by morevnaproject** [comment]
@technobrat The size of OSX package is reduced 5 times now - https://morevnaproject.org/2017/10/13/osx-version-synfig-now-5-times-smaller/
