### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by probonopd** [synfig/synfig#308]
On https://www.fosshub.com/Synfig.html the link to "Download Synfig Linux App Image (64-bit)" is broken. Also, it should be "AppImage" rather than "App Image".

**Comment by morevnaproject** [comment]
64bit appimage link works fine for me here. I think they have some kind of mechanism that prevents leech links downloading.

**Comment by FossHub** [comment]
We modified the text to AppImage, thank you!

Just tested the download and worked fine.

Some automated tools might not work, and we do not offer support for them. Please see our post: https://www.reddit.com/r/sysadmin/comments/5g5npg/fosshub_message_for_chocolatey_please_stop_with/

Please use a clean browser, and the download should work fine. Clean means without any 3rd party browser add-ons that act as a download manager or any similar tools.

**Comment by probonopd** [comment]
Works now! Thanks.
