### ISSUE TITLE
Add the ability to open the guide editor dialog by double clicking on the guide.

### ISSUE THREAD

**Issue by mohamedAdhamc** [synfig/synfig#3084]
Related: #2777 

Title nicely explains it. This feature requests that when a guide is double clicked its assoicated guide editor dialog pops up (in the same way it does now when its right clicked and then the guide editor dialog is chosen).

**Comment by Himanshu-370** [comment]
Can I be assigned?

**Comment by ice0** [comment]
@Himanshu-370 
Sure.

**Comment by mohamedAdhamc** [comment]
> @ice0 I should make changes in the dialog_editor.cpp file for this issue right?

`dialog_guide` contains implementation for the dialog itself. Changes for this one should mostly be in `workarea` this is also where the right click on guide is handle so it would make sense to handle double click there as well. You can check the original PRs implementation for right click it should give you a good idea.

**Comment by Himanshu-370** [comment]
@mohamedAdhamc Could you help me with the file? I am not exactly sure how to locate the code. 
I am a beginner. 
Thanks

**Comment by mohamedAdhamc** [comment]
@Himanshu-370 in #2777. Check `workarea.cpp` line 1363 onwards is the part responsible for creating the two menu item "edit guide" and "delete". You can look at those to figure out stuff. But overall in that same area `on_drawing_area_event` method handles many of the work area (think canvas) events like button press release etc... . I suggest first figuring out how to catch a double click in it (and just log something when you do to make sure it is working correctly). Then you can move on to replace the logging code with the actual code for opening the guide dialog.

p.s. if you haven't already you should build synfig first to be able to test out your changes. For that check synfig dev docs.

**Comment by Afterdie** [comment]
I am working on the solution and will submit a pr soon can you assign this to me please?
