### ISSUE TITLE
Sound Layer Waveform not showing 

### ISSUE THREAD

**Issue by Rhvy1** [synfig/synfig#3117]
**Describe the bug**
Sound waveform panel doesn't display waveform on audio import

**To Reproduce**
1. Go to Sound Layer Panel
2. Click on Select audio
3. Select any audio
5. See error (Blank) 

**Expected behavior**
An audio waveform was supposed to be displayed 

**System information:**
 - OS: Windows 
 - OS version: 10
 - Synfig version: 1.5.1

**Additional comments**
This doesn't happen in stable version

**Comment by rodolforg** [comment]
Could you provide the audio sample? Or describe the specs (sample rate, number of channels, bitrate, file format, etc.) ?

**Comment by Rhvy1** [comment]
It does the same for any audio I import so I don't think it's the audio. I just noticed also that it doesn't play audio during preview unlike before

**Comment by MBear227** [comment]
This issue still persists (i am experiencing it too and it makes it much harder to make an animation)

**Comment by rodolforg** [comment]
Could you check if it is solved in 1.5.3?

**Comment by Rhvy1** [comment]
1.5.3? where can i get that build?
I can only see a 1.5.2 in testing on AppVeyor.

**Comment by rodolforg** [comment]
https://github.com/synfig/synfig/releases/tag/v1.5.3

**Comment by Rhvy1** [comment]
Thank you!
It's been solved.
