### ISSUE TITLE
Feature Request: Link to Plugin folder in Synfig Preferences

### ISSUE THREAD

**Issue by yoSachinkr** [synfig/synfig#3119]
Link to plugin folder in Synfig preferences to help find plugin folder easily for users to install plugins.
![Screenshot 2023-07-07 151356](https://github.com/synfig/synfig/assets/50204208/63b0c09c-2b38-4cb1-b3b2-31be5c4d18f2)

**Comment by Afterdie** [comment]
I'd like to work on this feature!

**Comment by ice0** [comment]
Sure. Assigned it to you.
