### ISSUE TITLE
import image not working

### ISSUE THREAD

**Issue by tabebqena** [synfig/synfig#3137]
**Describe the bug**
Synfig can't impoer singl epng image.

**To Reproduce**
1. Go to `File`
2. Click on 'import'
3. Select any '.png' image.
4. Click import.

**Expected behavior**
The image should be imported .

**System information:**
 - OS: [Linux,  # 42 ~20.04.1-Ubuntu]
 - OS version: Linux  5.13.0-37-generic  # 42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

 - Synfig version: 1.4.4

**Additional comments**
If I clicked on 'import sequence', they imported succeeefully.

**Comment by rodolforg** [comment]
Are you using AppImage, snap, package from Ubuntu official repository or you compiled Synfig Studio yourself?

**Comment by tabebqena** [comment]
> Are you using AppImage, snap, package from Ubuntu official repository or did you compile Synfig Studio yourself?

I am using app image.

**Comment by tabebqena** [comment]
There is a similar thread in the forum, one say that it will work after saving the file ( & that is correct )

**Comment by rodolforg** [comment]
Duplicate #3023

**Comment by rodolforg** [comment]
Solution: #2243  (available in next release)

**Comment by AnthraxBass** [comment]
I confirm the same issue on both portable versions for Windows 10, release 1.4.4
