### ISSUE TITLE
Preference Dialog Icons dont work

### ISSUE THREAD

**Issue by Afterdie** [synfig/synfig#3155]
**Describe the bug**
The icons responsible for add and remove path for brush presets dont work it just uses a placeholder image instead.

**To Reproduce**
1. Go to 'Edit'
2. Click on 'Preferences'
3. Click on 'System'

**Expected behavior**
Buttons should show up with a + - icon inside of them.

**Screenshots**
![image](https://github.com/synfig/synfig/assets/82810411/5a067b40-e44f-4c01-86b6-a00f75c585f1)

**Comment by ice0** [comment]
Hi!

Can you describe your system?
The code is correct so I just want to understand which systems are affected because I didn't see this issue on Mint 21.

![image](https://github.com/synfig/synfig/assets/5604544/837c807f-f700-454a-a1db-dda78a4f0db9)

**Comment by Afterdie** [comment]
Im on windows 11 and this issue occurs in the release version as well. You can see [this](https://github.com/synfig/synfig/issues/3119) happening for this user too.

**Comment by ice0** [comment]
Got it, thanks!
