### ISSUE TITLE
Feature request: edit guide position in "Guide editor" popup window

### ISSUE THREAD

**Issue by pgilfernandez** [synfig/synfig#3165]
**Is your feature request related to a problem? Please describe.**
I discovered recently PR https://github.com/synfig/synfig/pull/3152 and its related feature request https://github.com/synfig/synfig/issues/3084. It's very nice, good job!

**Describe the solution you'd like**
I would like to suggest that you add to that "guide editor" popup the option not to just edit the rotation but also the position.

**Describe alternatives you've considered**
none

**Additional comments**
Thanks!

**Comment by Afterdie** [comment]
Thanks! Im working on this feature and its almost finished 
#3153

**Comment by pgilfernandez** [comment]
Awesome!

Thanks!

**Comment by rodolforg** [comment]
Duplicate #3083
