### ISSUE TITLE
Color Correct's gamma parameter doesn't work well

### ISSUE THREAD

**Issue by genete** [synfig/synfig#317]
**synfigstudio 1.3.0 20170114 Windows XP**:

**Issue description**:

Open examples/cells.sifz and notice the wrong render of the file due to the gamma parameter of the Color Correct layer. 
![cells](https://cloud.githubusercontent.com/assets/346755/22461882/6a36247e-e7ab-11e6-946a-7d688d3ca5c0.png)

Open it with older versions (1.0.2) of Synfig Studio and you'll see correctly rendered.
![cells](https://cloud.githubusercontent.com/assets/346755/22461902/7bef76ac-e7ab-11e6-98fa-d99ba90f2563.jpg)

**Comment by blackwarthog** [comment]
Hello @genete! I think bug related with additional composite blending operation. Any blending clamps the color channels and makes such artifacts. Can you do some checks in old Synfig:
- create any contour at the front
- put all layers into group
