### ISSUE TITLE
Wrong button labels in Custom Workspace editor 

### ISSUE THREAD

**Issue by pgilfernandez** [synfig/synfig#3174]
**Describe the bug**
Actual Custom Workspaces Editor looks like:
<img width="342" alt="workspaces_editor" src="https://github.com/synfig/synfig/assets/5942369/89b7944a-8e14-4cf4-a716-de3edc7a3bbb">

**To Reproduce**
1. Open Window / Workspace / Edit workspace...
2. Look at the buttons labels

**Expected behavior**
I guess the right labels would be just "Delete" and "Close"

**System information:**
 - OS: macOS
 - OS version: 12.6.7
 - Synfig version: 1.5.1

**Additional comments**
none

**Comment by rodolforg** [comment]
Problem is here: synfig-studio/src/gui/resources/ui/dialog_workspaces.glade

**Comment by pgilfernandez** [comment]
@rodolforg thanks for the tip. I made a simple PR to fix it: https://github.com/synfig/synfig/pull/3175

Thanks

**Comment by pgilfernandez** [comment]
close as completed in https://github.com/synfig/synfig/pull/3175
