### ISSUE TITLE
Warp horizon parameter doesn't work well

### ISSUE THREAD

**Issue by genete** [synfig/synfig#318]
**synfigstudio 1.3.0 20170114 Windows XP**:

**Issue description**:
Open examples/backdrop.sifz and you'll notice that the floor tiles doesn't reach the wall (also it is cut at the left of the image):
![backdrop](https://cloud.githubusercontent.com/assets/346755/22462040/fb32ad80-e7ab-11e6-8610-f74c6b180df1.png)
It should render like in older versions (1.0.2) where the floor tiles reach the wall:
![backdrop](https://cloud.githubusercontent.com/assets/346755/22462081/1985738a-e7ac-11e6-994c-34f280a6ca62.jpg)

**Comment by Darkspace65** [comment]
Hi!
I can confirm that it also has the same issue on windows 10 version 1.2.0. The rotation layer seems to affect it. Hello Genete!!!!
Greetz!

**Comment by morevnaproject** [comment]
Can anyone check if this still a problem with the latest commit? - 6b433d2503ed81bd6577c17748d2ae59ce0573c6

**Comment by morevnaproject** [comment]
Confirmed to be fixed in master
![screenshot_001](https://user-images.githubusercontent.com/332868/75606849-831e3780-5b23-11ea-81e4-fae4ba5b951f.png)
