### ISSUE TITLE
Timetrack toolbar disappears when closing file

### ISSUE THREAD

**Issue by pgilfernandez** [synfig/synfig#3187]
**Describe the bug**
The new Timetrack panel toolbar (with move, duplicate, scale and waypoints) on the right side disappears when you close a file

**To Reproduce**
I found 2 simple ways described in the following video:
![panel2](https://github.com/synfig/synfig/assets/5942369/24c86ac0-aaac-48bb-89d5-348ccc911d8c)

**Expected behavior**
That toolbar never should close... unless there is an option to enable/disable it manually of course.

**System information:**
 - OS: macOS
 - OS version: 12.6.7
 - Synfig version: 1.5.1

**Additional comments**
Thanks

**Comment by mohamedAdhamc** [comment]
Fixed :) , pushing the PR soon.
