### ISSUE TITLE
Incorrect blend mode for "None" Subsampling type in Motion blur layer

### ISSUE THREAD

**Issue by pgilfernandez** [synfig/synfig#3199]
**Describe the bug**
Related to this new feature https://github.com/synfig/synfig/pull/3173, when setting Subsampling type to "none", the blending mode is `Add` when I guess it should be `Composite` (or just none as we don't really want the subsamples to blend).

**To Reproduce**
1. create any Geometry layer
2. add Motion blur layer
3. set "subsampling type" to "none"
4. check how they are blended using `Add`

**Expected behavior**
They should not get blended but added one behind the other one

**Screenshots**
Here an example:
<img width="557" alt="example" src="https://github.com/synfig/synfig/assets/5942369/697c0f3a-f79c-4005-8d04-289e1ee02784">
Another one:
<img width="536" alt="example2" src="https://github.com/synfig/synfig/assets/5942369/57fb976b-da83-40a1-a524-dd460f75f8e5">

**System information:**
 - OS: macOS (I guess applicable to all)
 - OS version: 12.6.7
 - Commit ID: bb67147

**Additional comments**
Maybe it would be a good idea to "open" the blending mode as a parameter so that users could change it and get different interesting results...

Thanks

**Comment by rodolforg** [comment]
I only tested with a white star :P sorry

**Comment by pgilfernandez** [comment]
> I only tested with a white star :P sorry

Hehehe, no problem =)
