### ISSUE TITLE
Single thread only

### ISSUE THREAD

**Issue by Darkspace65** [synfig/synfig#320]
Hi! 
Under Edit-preferences-system, there is still a line that says "_Single thread only (CPU's)_" but without a tick box to select/unselect. Is that still relevant and or a problem under Windows 10?
Synfig 1.2.0 , Windows 10.
Greetz!

**Comment by caryoscelus** [comment]
Relevant code:

```c++
// uncomment define SINGLE_THREADED to use a single thread, and hopefully get more stability (dooglus) - changed to be default if using windows (Nov 2009 pixelgeek)
#ifdef _WIN32
#define SINGLE_THREADED
#endif
```

Since that's defined in app.h (which means only affects studio, not core), it might as well be outdated. I guess someone needs to compile for windows with that line disabled and see if it works.

You can try running synfig command line renderer and see if it uses more than one thread.

**Comment by morevnaproject** [comment]
Yes, this is an outdated. Should be removed.

**Comment by blackwarthog** [comment]
As i remember SINGLE_THREADED option makes windows build more stable. It's affects method of rendering tiles - simultaneous or sequential. Now synfigstudio don't split image while rendering. But when user scrolls the window, synfig dont redraws whole scene, just render small previously invisible part of image. So user may initiate couple of rendering task for different areas of scene while scrolling, and studio (gui part of our program) can run some rendering preparations in parallel threads. This behaviour seemed us unstable at windows earlier, i don't remember why.

**Comment by blackwarthog** [comment]
I've fixed this option for now, anyway dialog layout was broken in previous row (brushes)

**Comment by morevnaproject** [comment]
The fix now shipped with latest development builds - https://morevnaproject.org/2017/04/23/synfig-studio-1-3-2-development/
