### ISSUE TITLE
PNG file import converts RED component of RGB colors to FF (100% red) on certain images

### ISSUE THREAD

**Issue by KingoftheBears** [synfig/synfig#321]
synfigstudio-1.3.1-20170202-64bit.appimage running on OpenSUSE Leap 42.2 all updated

I built an animation project a couple of years ago with a black and blue PNG background image of a spiral that I then animated to rotate.

When the enhancements to the speed of raster image processing were announced perhaps a year ago, when I would load the .sif file, the PNG background image had the RED component set to FF throughout the image.  If I convert the PNG to a JPG with Imagemagick, the JPG loads with the correct colors.  I apologize for not reporting it sooner, but I thought it was so blatant that others would find it promptly, but I gather it is a bug specific to some attribute of my image. The latest development build continues to have this problem.  Origin of the PNG image was gimp ... I recreated that image with the latest version of gimp, and it still produces the same results upon import.

To duplicate this problem, just run the above version of Synfigstudio, File-Import-1rotcolortest.png, and it comes up all red & magenta (red for the black part of the image which of course went from 000000x to FF0000x, magenta for the modification of the blue part with red added).  To see how the original file appeared in old versions of Synfig, import the JPG version of the file as attached in the same synfig session.

Happy to assist with tests, etc.  The only other test I did was to surround the original png image with a white border, and it loaded correctly. All other applications that I have used to view the PNG file render it correctly (gwenview, gimp, display, etc).

![1rotcolortest](https://cloud.githubusercontent.com/assets/25046307/22619994/8bce1930-eacf-11e6-819a-39ff5fad36f2.png)
![1rotcolortest](https://cloud.githubusercontent.com/assets/25046307/22619995/9001c34e-eacf-11e6-9299-bf35a640fec4.jpg)

**Comment by caryoscelus** [comment]
Perhaps your images use limited palette. I remember having some problems with certain pngs (with other software) and converting them to PNG24 helped. You can try that too (converting can be done with imagemagick: `convert source.png PNG24:target.png`).

**Comment by caryoscelus** [comment]
No, that doesn't work either.

**Comment by ice0** [comment]
@KingoftheBears hi!
I checked your file on latest Synfig version and it looks ok. Can you please check it on latest version?
https://github.com/synfig/synfig/releases

**Comment by KingoftheBears** [comment]
It is working!  EXCELLENT!  Thank you very much!  I've been wanting to
do more work on that project and you wouldn't think such a small thing
would hold me back, but it did *;O)

Very much appreciated!

*
Arthur Knight Hammer

**Comment by ice0** [comment]
Thank you! So I close this issue.
