### ISSUE TITLE
Warp layers bug

### ISSUE THREAD

**Issue by MBear227** [synfig/synfig#3216]
https://drive.google.com/file/d/1Dc-jr8nOmc8Za1nYPAaTNE8PK7IrIOCI/view?usp=sharing
![Screenshot 2023-09-13 164932](https://github.com/synfig/synfig/assets/46875299/63b73109-8ff0-42f4-a67c-4d6886fe3eb0)
As you can see, the lines don't line up. I have attached the file so you can investigate.

**Comment by rodolforg** [comment]
Try to use "Nearest neighbors" in the "interpolation" parameter of Warp (Perspective) layer.

**Comment by MBear227** [comment]
what do you mean?
![Screenshot 2023-10-05 131318](https://github.com/synfig/synfig/assets/46875299/e0d2b717-1cf3-4b30-83a3-1e47521c4b89)

**Comment by luzpaz** [comment]
Is this still relevant ? (there is no version this bug is associated to)

**Comment by MBear227** [comment]
i don't remember which version i was using here, i found a workaround so no i wouldn't say this is relevant anymore

**Comment by luzpaz** [comment]
Close in that case ?

**Comment by MBear227** [comment]
yeah
