### ISSUE TITLE
Font is not working on Windows 10.

### ISSUE THREAD

**Issue by AwesomePaper** [synfig/synfig#322]
**Synfig version & platform**:
Synfig 1.2.0
Microsoft Windows 10

**Issue description**:
Font is not working on Windows platform. When I using font, synfig is not respond. Can I using font on synfig on Windows 10?

**Comment by morevnaproject** [comment]
Hello @AwesomePaper, did you tried this tutorial? - https://morevnaproject.org/2016/09/08/set-font-style-synfig/

**Comment by Darkspace65** [comment]
Hi!
@AwesomePaper, @morevnaproject This works on Synfig 1.3.1. Just make sure that you save your file first before you change the font in the parameters panel of the text layer.
