### ISSUE TITLE
macOS autotools builds miss app icon

### ISSUE THREAD

**Issue by pgilfernandez** [synfig/synfig#3222]
**Describe the bug**
Builds produced with autotools under macOS result in apps without icon

**To Reproduce**
1. run `./1-setup-osx-brew.sh`
2. run `./2-build-production.sh`
3. run `./3-package-osx-dmg.sh`
4. check SynfigStudio.app has no icon

**Expected behavior**
It should have Synfig icon

**Screenshots**

<img width="613" alt="screenshot" src="https://github.com/synfig/synfig/assets/5942369/05d139f3-abb8-47f4-8087-a194fa2ee019">

**System information:**
 - OS: macOS
 - OS version: 12.6.7
 - Synfig version: 1.5.1

**Additional comments**
I observed since a few month but I didn't pay attention as I usually run these test builds without packaging.
Now I wanted to have a shareable updated Synfig dev version and I found out this.

I'm experiencing another problems but I still would like to test or try to solve them by myself as I don't know if they depend on my setup or it's a real bug. I'll open another Issue in case I can't solve it.
Thanks

**Comment by rodolforg** [comment]
Maybe this link helps: https://stackoverflow.com/questions/646671/how-do-i-set-the-icon-for-my-applications-mac-os-x-app-bundle

**Comment by pgilfernandez** [comment]
I found the problem, PR https://github.com/synfig/synfig/pull/3223 solves this issue, let me close this.

PS - While looking for the problem I found out `.icns` macOS icon files are pretty outdated as they don't include higher resolutions used in modern OS versions so I'm creating another PR for updating them both. =)
