### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by davidstekly** [synfig/synfig#327]
![synfig - font issue](https://cloud.githubusercontent.com/assets/5794878/23244841/2e602ccc-f9dc-11e6-9a6a-a619a00cf95f.png)
Synfig Studio 1.2.0 & Windows 10

Hello, just recently installed Synfig. Using last stable version under Windows 10 64bit. Once installation is finished and you open the software there is one issue, no text is displayed, only weird symbols so you have no chance to use it at all. Is there any font related issue with installation? Any idea how to fix this? Please see the attachment.

Thanks for any assistance.

**Comment by morevnaproject** [comment]
Finally I have figured out why this can happen.

It is possible your system is missing a set default fonts. To workaround this, please try to install Droid Sans font, which is used by default by Synfig's Gtk3 engine - https://fonts.google.com/specimen/Droid+Sans

**Comment by morevnaproject** [comment]
Alternative link for downloading Droid Sans font - https://www.fontsquirrel.com/fonts/droid-sans
The issue is confirmed as solved.
