### ISSUE TITLE
synfig itself does not render .lst images; synfigstudio works fine

### ISSUE THREAD

**Issue by marnanel** [synfig/synfig#3271]
**Describe the bug**
On master, synfig itself does not render images pulled in from .lst files. synfigstudio both displays and renders them correctly. 

**To Reproduce**
1. Unpack attached tarball, and cd into the directory
2. `synfig lst-test`
3. You get 120 blank pngs (or, if you render to a video container format, a five-second grey video)

[lst-test.zip](https://github.com/synfig/synfig/files/13393797/lst-test.zip)

**Expected behavior**
An alternating sequence of red.png and blue.png.

**Screenshots**
As rendered on the commandline
![image](https://github.com/synfig/synfig/assets/292241/68ebfbd1-c53a-40b0-94ca-4ab99d5d696c)

As rendered by synfigstudio
![image](https://github.com/synfig/synfig/assets/292241/d6f2f569-08f1-4f2c-b2d5-3ae3aefd8059)

Looking at the .sif in synfigstudio
![image](https://github.com/synfig/synfig/assets/292241/4f9b16d2-788c-4aa0-8ec9-ad796aede592)

**System information:**
 - OS: Debian
 - OS version: 12.2
 - Commit ID: 69f4ea71908f666a2e2c8907f77c1c284f1aa870

**Additional comments**
I'm sure this used to work.

**Comment by rodolforg** [comment]
It doesn't work on 1.5.1 (CLI and GUI).
