### ISSUE TITLE
Infinite Error Windows from Eyedropper

### ISSUE THREAD

**Issue by jnilken** [synfig/synfig#3288]
**Describe the bug**
When attempting to use the eyedropper, I go the error "Unable to set all layer parameters," but the eyedropper is apparently still active. Attempting to close the error window results in the eyedropper trying to pick the color of the error box and spawned new error windows for every click. The escape and enter key all seem to also select colors and spawn new errors instead of letting me exit. I can't close the window from my taskbar, so I either have to use task manager or wait for it to crash. Recovery saved my work, so no big issues there.

Cause of Error: I opened the color picker then realized the color I wanted was on the bottom layer and covered. I moved that layer while the color picker was open, then attempted to sample from it. The correct color was chosen before the error occurred. On my second attempt, the same error did not happen.

My layers were an advanced outline, a region, and a png (in that order from top to bottom). Then I moved the png to the top layer. There is an error that occurs before "Unable to set all layer parameters," but it is covered too fast for me to easily read it.

**To Reproduce**
1. Go to Parameters (for a region)
2. Click on the color box next to the Color parameter to open the selector
3. Move the bitmap layer to the top
4. Attempt to select a color from bitmap image
5. See error

**Expected behavior**
The color is selected, or the resulting error can be exited.

**Screenshots**
![image](https://github.com/synfig/synfig/assets/152563065/7fe8f6ed-a733-4f0c-9ef2-23b074f667f9)

**System information:**
 - OS: Windows 10
 - OS version: 10.0.19045 Build 19045
 - Synfig version: 1.4.2

**Additional comments**
I was able to reproduce it consistently. This only occurs when I move and sample from a bitmap image, not a region or outline.

**Comment by BobSynfig** [comment]
Please check first with (at least) 1.4.4 and current dev version.
Lots of bugs have been corrected since 1.4.2

**Comment by jnilken** [comment]
Just checked on the 1.4.4 and replicated the bug using the same process. Not sure I have the time right now to get the dev version up and running on my machine.

Also a note: I'm guessing v1.4.4 is a stable release. Given that, why does the synfig.org "purchase" form (https://synfig.gumroad.com/l/synfig) give users the 1.4.2 release for the Windows 64bit exe? That is why I had an older version.

**Comment by jnilken** [comment]
Image of the same bug on v1.4.4

![image](https://github.com/synfig/synfig/assets/152563065/34d56579-5130-47c7-abef-bad011b7cfdb)

**Comment by BobSynfig** [comment]
> Also a note: I'm guessing v1.4.4 is a stable release. Given that, why does the synfig.org "purchase" form (https://synfig.gumroad.com/l/synfig) give users the 1.4.2 release for the Windows 64bit exe? That is why I had an older version.

Good to know, let's the "Boss" @morevnaproject be aware of this for check.

Did you try with a (portable) dev release?
The last available from AppVeyor is available here: https://ci.appveyor.com/project/Synfig/synfig/builds/48718219/artifacts  (link expires Jan 9th 2024)

**Comment by jnilken** [comment]
Thanks for the link! Same bug with same error messages, though it briefly froze when I first clicked the eyedropper this time (no warnings/errors popped up in the console yet, though). When I did attempt to select a color, each new error box seemed to align with the console warning `Cancel depth: 0`

**Comment by rodolforg** [comment]
Long time after the report, now PR  #3373 fixes it. I hope.
Could you test it, please? https://ci.appveyor.com/api/buildjobs/cctv7pxaq7ijd23t/artifacts/SynfigStudio-1.5.2-testing-2024-06-09-win64-7cfc0.zip (link expires July 9)
Please note that is a dev. version. Do not save your projects from 1.4.x versions with it without a proper backup.
