### ISSUE TITLE
Unable to render with ffmpeg

### ISSUE THREAD

**Issue by legocef01** [synfig/synfig#332]
**Synfig version 1.3.1 (also version 1.2.0) & platform Ubuntu 16.10**

**Issue description**:
I can't render a video with ffmpeg (no matter option of encoding chose). When I click on render button, no thing happens in the output directory. In terminal, it displays this : 

`avconv: relocation error: avconv: symbol av_vdpau_get_surface_parameters, version LIBAVCODEC_57 not defined in file libavcodec.so.57 with link time reference`

**Comment by morevnaproject** [comment]
It seems something wrong with your avconv installation. Can you please try to remove avconv package and try without it?

**Comment by legocef01** [comment]
Ok thanks for answering.

I tried rendering without avconv installed. When I click on render, it displays an dialog box which says : 

**Error: No FFmpeg binary found.**
**Please install "ffmpeg" or "avconv" (libav-tools package).**

Nevertheless, I have ffmpeg installed in my system.

After this, I remove ffmpeg and avconv, the I reinstall them. Now, I have this in terminal after clicking on render  :+1: 

`synfig(25424) [17:34:21] warning: Broken Pipe...`

and it displays that in many lines

**Comment by morevnaproject** [comment]
Thanks for testing! Another question: do you use AppImage binary or compiled Synfig from source?

**Comment by legocef01** [comment]
I use AppImage binary and I used, for this, the last stable and testing AppImage

**Comment by morevnaproject** [comment]
OK. Please open terminal window and type  following command:
`which avconv; which ffmpeg`

Please post result here.

**Comment by legocef01** [comment]
`which avconv`

`/usr/bin/avconv`

and second : 

`which ffmpeg`

`/usr/bin/ffmpeg`

**Comment by legocef01** [comment]
I have this with ffmpeg or avconv commands :



`ffmpeg version 3.0.7-0ubuntu0.16.10.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.2.0 (Ubuntu 6.2.0-5ubuntu12) 20161005


  configuration: --prefix=/usr --extra-version=0ubuntu0.16.10.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.10.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_amrwbenc
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
`
You cant see 
 
`WARNING: library configuration mismatch`

in this output. I don't know if it is that the proplem.

**Comment by morevnaproject** [comment]
This might be because Ubuntu uses  avconv instead off ffmpeg by default. Having two packages can cause conflicts. You can try to remove ffmpeg package and check if it work with avconv only.

**Comment by legocef01** [comment]
Without ffmpeg, I have a dialog box which says :

**Error: No FFmpeg binary found.**
**Please install "ffmpeg" or "avconv" (libav-tools package).**

**Comment by legocef01** [comment]
sometimes, when I whant to render, after saying : 
`avconv: relocation error: avconv: symbol av_vdpau_get_surface_parameters, version LIBAVCODEC_57 not defined in file libavcodec.so.57 with link time reference`

I have plenty of lines saying  : 

`synfig(9162) [01:08:29] warning: Broken Pipe...`
`synfig(9162) [01:08:29] warning: Broken Pipe...`
`synfig(9162) [01:08:29] warning: Broken Pipe...`
`synfig(9162) [01:08:29] warning: Broken Pipe...`

**Comment by legocef01** [comment]
I installed synfig 1.0.2-1 from ubuntu repository, and with it, I don't have a problem rendering with ffmpeg.

But I want the last version from app image.

**Comment by revast** [comment]
I made packages for ubuntu 16.04
get them at
http://openartist.org/debian/xenial64/

**Comment by morevnaproject** [comment]
@legocef01 We have updated appiamge builds - https://morevnaproject.org/2017/04/23/synfig-studio-1-3-2-development/
Can you please test if the problem still happens?

**Comment by ammine007** [comment]
I have the exact same problem with ffmpeg/libav video export. I'm using Debian Stretch 9 everything works fine with 1.0.2 that comes with the official debian repositories. But both 1.2.0 and 1.3.3 AppImages do not work correctly in the case of rendering with the ffmpeg option selected.

Here is the educational video that i've made with success on the Official 1.0.2 version : https://www.youtube.com/watch?v=xFeZYESfvOE

**Comment by morevnaproject** [comment]
Hello! I have been able to reproduce this issue. 

@ammine007, @legocef01 can you please download latest appimage (1.3.3) and post output of the following command:

```/path/to/your/file/synfigstudio-1.3.3-20170430-linux-64bit.appimage --appimage-exec which ffmpeg```

**Comment by legocef01** [comment]
Hi @morevnaproject 

by entering the command : 

`./synfigstudio-1.3.3-2017.04.30-56018-linux-64bit.appimage --appimage-exec which ffmpeg`

This is what i have : 

`./bin//ffmpeg`

**Comment by morevnaproject** [comment]
Thank you! Then this one, please:
```/path/to/your/file/synfigstudio-1.3.3-20170430-linux-64bit.appimage --appimage-exec env```

**Comment by legocef01** [comment]
Command : 
`./synfigstudio-1.3.3-2017.04.30-56018-linux-64bit.appimage --appimage-exec env`

Output : 
`CLUTTER_IM_MODULE=xim
LD_LIBRARY_PATH=/tmp/.mount_haHAIQ/usr/lib:/tmp/.mount_haHAIQ/usr/lib64:./lib/:./lib/i386-linux-gnu/:./lib/x86_64-linux-gnu/:./lib32/:./lib64/:../lib/:../lib/i386-linux-gnu/:../lib/x86_64-linux-gnu/:../lib32/:../lib64/:
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_MEASUREMENT=fr_FR.UTF-8
LC_PAPER=fr_FR.UTF-8
LC_MONETARY=fr_FR.UTF-8
XDG_MENU_PREFIX=gnome-
SYNFIG_MODULE_LIST=/tmp/.mount_haHAIQ/usr/etc/synfig_modules.cfg
KIGITHUB=https://github.com/KiCad
LANG=fr_FR.UTF-8
GDM_LANG=fr_FR
MANAGERPID=3287
DISPLAY=:0
INVOCATION_ID=d434ae137bf5497e8a3810073b2dd4ca
COMPIZ_CONFIG_PROFILE=ubuntu
GTK2_MODULES=overlay-scrollbar
APPIMAGE=/opt/synfig/testing/synfigstudio-1.3.3-2017.04.30-56018-linux-64bit.appimage
COLORTERM=truecolor
MAGICK_CONFIGURE_PATH=/tmp/.mount_haHAIQ/usr/lib/ImageMagick-6.8.7/config-Q16/
DESKTOP_AUTOSTART_ID=102a7ca17ac2dd1f2c14967260499418300000013610007
ZEITGEIST_DATA_PATH=/home/legocef/.local/share/zeitgeist
CADENCE_AUTO_STARTED=true
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
GIO_LAUNCHED_DESKTOP_FILE_PID=1684
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
KICAD_PATH=/usr/share/kicad
DSSI_PATH=/home/legocef/.dssi:/usr/lib/dssi:/usr/local/lib/dssi
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LC_NAME=fr_FR.UTF-8
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/legocef
USER=legocef
DESKTOP_SESSION=ubuntu
SUIL_MODULE_DIR=/opt/kxstudio/lib/suil-0
QT4_IM_MODULE=ibus
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
QT_QPA_PLATFORMTHEME=gtk2
PWD=/tmp/.mount_haHAIQ/usr
HOME=/home/legocef
JOURNAL_STREAM=8:24941353
QT_ACCESSIBILITY=1
LIBVIRT_DEFAULT_URI=qemu:///system
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/tmp/.mount_haHAIQ/usr/share:./share/:/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/usr/local/share/:/usr/share/
MAGICK_CODER_MODULE_PATH=/tmp/.mount_haHAIQ/usr/lib/ImageMagick-6.8.7/modules-Q16/coders/
QT_XKB_CONFIG_ROOT=:/usr/local/share/X11/xkb:/usr/share/X11/xkb
GSETTINGS_SCHEMA_DIR=/tmp/.mount_haHAIQ/usr/share/glib-2.0/schemas/
XDG_SESSION_DESKTOP=ubuntu
LC_ADDRESS=fr_FR.UTF-8
SSH_AGENT_LAUNCHER=gnome-keyring
LC_NUMERIC=fr_FR.UTF-8
SYNFIG_ROOT=/tmp/.mount_haHAIQ/usr
LADSPA_PATH=/home/legocef/.ladspa:/usr/lib/ladspa:/usr/local/lib/ladspa
GTK_MODULES=gail:atk-bridge:unity-gtk-module
LV2_PATH=/home/legocef/.lv2:/usr/lib/lv2:/usr/local/lib/lv2
PAPERSIZE=a4
MAGICK_CODER_FILTER_PATH=/tmp/.mount_haHAIQ/usr/lib/ImageMagick-6.8.7/modules-Q16/filters/
QT_PLUGIN_PATH=./lib/qt4/plugins/:./lib/i386-linux-gnu/qt4/plugins/:./lib/x86_64-linux-gnu/qt4/plugins/:./lib32/qt4/plugins/:./lib64/qt4/plugins/:./lib/qt5/plugins/:./lib/i386-linux-gnu/qt5/plugins/:./lib/x86_64-linux-gnu/qt5/plugins/:./lib32/qt5/plugins/:./lib64/qt5/plugins/:
GNOME_SESSION_XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session4
VTE_VERSION=4402
TERM=xterm-256color
SHELL=/usr/bin/fish
USER_CONFIG_DIR=/home/legocef/.config/synfig
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=1
VST_PATH=/home/legocef/.vst:/usr/lib/vst:/usr/local/lib/vst
XDG_CURRENT_DESKTOP=Unity:Unity7
GPG_AGENT_INFO=/home/legocef/.gnupg/S.gpg-agent:0:1:
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
MLT_REPOSITORY=/tmp/.mount_haHAIQ/usr/lib/mlt/
GIO_LAUNCHED_DESKTOP_FILE=/home/legocef/.config/autostart/tilda.desktop
SHLVL=3
LANGUAGE=fr_FR:en
PYTHONPATH=./share/pyshared/:
LC_TELEPHONE=fr_FR.UTF-8
MLT_DATA=/tmp/.mount_haHAIQ/usr/share/mlt/
GDMSESSION=ubuntu
APPDIR=/tmp/.mount_haHAIQ
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=legocef
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/legocef/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session4
XDG_CONFIG_DIRS=/home/legocef/.config/synfig:/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=./bin/:./sbin/:./games/:../bin/:../sbin/:/opt/simFlow/simFlow-3.0:/opt/simFlow/simFlow:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LC_IDENTIFICATION=fr_FR.UTF-8
PERLLIB=./share/perl5/:./lib/perl5/:
SYNFIG_GTK_THEME=Adwaita
APPIMAGE_ROOT=/tmp/.mount_haHAIQ/usr
SESSION_MANAGER=local/kuosi:@/tmp/.ICE-unix/1361,unix/kuosi:/tmp/.ICE-unix/1361
OWD=/opt/synfig/testing
GTK_IM_MODULE=ibus
LC_TIME=fr_FR.UTF-8
_=/usr/bin/env`

**Comment by ammine007** [comment]
Salamu alaikum,

Here is the result of the first command:

$ ./synfigstudio-1.3.3-20170430-linux-64bit.appimage --appimage-exec which ffmpeg
./bin//launch.sh: ligne 7: ldconfig : commande introuvable
./bin//ffmpeg

And here is the result of the second one : 

$ ./synfigstudio-1.3.3-20170430-linux-64bit.appimage --appimage-exec which env
./bin//launch.sh: ligne 7: ldconfig : commande introuvable
/usr/bin/env

**Comment by legocef01** [comment]
@ammine007  
the second command should be : 
`./synfigstudio-1.3.3-20170430-linux-64bit.appimage --appimage-exec env`

you added *which* between *appimage-exec* and *env*

**Comment by ammine007** [comment]
Sorry, Thank you for poiting this out. Here is the result of the command

$ ./synfigstudio-1.3.3-20170430-linux-64bit.appimage --appimage-exec env
./bin//launch.sh: ligne 7: ldconfig : commande introuvable
LD_LIBRARY_PATH=/tmp/.mount_CaJ86i/usr/lib:/tmp/.mount_CaJ86i/usr/lib64:./lib/:./lib/i386-linux-gnu/:./lib/x86_64-linux-gnu/:./lib32/:./lib64/:../lib/:../lib/i386-linux-gnu/:../lib/x86_64-linux-gnu/:../lib32/:../lib64/::/tmp/.mount_CaJ86i/usr/lib.extra
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_MEASUREMENT=fr_FR.utf8
LC_PAPER=fr_FR.utf8
LC_MONETARY=fr_FR.utf8
XDG_MENU_PREFIX=gnome-
SYNFIG_MODULE_LIST=/tmp/.mount_CaJ86i/usr/etc/synfig_modules.cfg
LANG=fr_FR.UTF-8
GDM_LANG=fr_FR.UTF-8
DISPLAY=:0
OLDPWD=/home/webuser
APPIMAGE=/home/webuser/Téléchargements/synfigstudio-1.3.3-20170430-linux-64bit.appimage
COLORTERM=truecolor
MAGICK_CONFIGURE_PATH=/tmp/.mount_CaJ86i/usr/lib/ImageMagick-6.8.7/config-Q16/
SYNFIG_DISABLE_JACK=1
USERNAME=webuser
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=3
USER=webuser
DESKTOP_SESSION=default
QT_QPA_PLATFORMTHEME=qgnomeplatform
PWD=/tmp/.mount_CaJ86i/usr
HOME=/home/webuser
JOURNAL_STREAM=8:25259
SSH_AGENT_PID=1986
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/tmp/.mount_CaJ86i/usr/share:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/local/share/:/usr/share/
MAGICK_CODER_MODULE_PATH=/tmp/.mount_CaJ86i/usr/lib/ImageMagick-6.8.7/modules-Q16/coders/
QT_XKB_CONFIG_ROOT=:/usr/local/share/X11/xkb:/usr/share/X11/xkb
GSETTINGS_SCHEMA_DIR=/tmp/.mount_CaJ86i/usr/share/glib-2.0/schemas/
XDG_SESSION_DESKTOP=default
GJS_DEBUG_OUTPUT=stderr
LC_NUMERIC=fr_FR.utf8
SYNFIG_ROOT=/tmp/.mount_CaJ86i/usr
GTK_MODULES=gail:atk-bridge
MAGICK_CODER_FILTER_PATH=/tmp/.mount_CaJ86i/usr/lib/ImageMagick-6.8.7/modules-Q16/filters/
WINDOWPATH=2
QT_PLUGIN_PATH=./lib/qt4/plugins/:./lib/i386-linux-gnu/qt4/plugins/:./lib/x86_64-linux-gnu/qt4/plugins/:./lib32/qt4/plugins/:./lib64/qt4/plugins/:./lib/qt5/plugins/:./lib/i386-linux-gnu/qt5/plugins/:./lib/x86_64-linux-gnu/qt5/plugins/:./lib32/qt5/plugins/:./lib64/qt5/plugins/:
VTE_VERSION=4601
TERM=xterm-256color
SHELL=/bin/bash
USER_CONFIG_DIR=/home/webuser/.config/synfig
XDG_CURRENT_DESKTOP=GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
MLT_REPOSITORY=/tmp/.mount_CaJ86i/usr/lib/mlt/
XDG_SEAT=seat0
SHLVL=2
PYTHONPATH=./share/pyshared/:
WINDOWID=29360134
MLT_DATA=/tmp/.mount_CaJ86i/usr/share/mlt/
GDMSESSION=default
APPDIR=/tmp/.mount_CaJ86i
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=webuser
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/home/webuser/.config/synfig:
PATH=./bin/:./sbin/:./games/:../bin/:../sbin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PERLLIB=./share/perl5/:./lib/perl5/:
SYNFIG_GTK_THEME=Adwaita
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
APPIMAGE_ROOT=/tmp/.mount_CaJ86i/usr
SESSION_MANAGER=local/DESKTOP-POS:@/tmp/.ICE-unix/1933,unix/DESKTOP-POS:/tmp/.ICE-unix/1933
OWD=/home/webuser/Téléchargements
LC_TIME=fr_FR.utf8
_=/usr/bin/env

**Comment by matejmosko** [comment]
It is the same for me. I am not a pro, but this "./bin//ffmpeg" doesn't seem right. Shouldn't it be "./bin/ffmpeg"?

**Comment by caryoscelus** [comment]
>"./bin//ffmpeg" doesn't seem right

Shouldn't matter, extra slashes are ignored (try `ls //usr//` or `/bin///bash`).

**Comment by morevnaproject** [comment]
I have made some test code to verify why the problem happens.

@blackwarthog, please build an 64bit appimage of "ffmpeg-test" branch from morevnaproject/synfig repository.

**Comment by morevnaproject** [comment]
https://github.com/morevnaproject/synfig/commit/425d43921d452f9c0fb0d91e5e1bce60dda5a38f

**Comment by morevnaproject** [comment]
@legocef01 @ammine007 Please check if this package will work for you - https://icystar.com/downloads/experimental/SynfigStudio-1.3.3-2017.08.04-425d4-linux-64bit.appimage

**Comment by morevnaproject** [comment]
The fix is shipped with Synfig Studio 1.3.4 - https://morevnaproject.org/2017/08/10/synfig-studio-1-3-4-released/
