### ISSUE TITLE
Import of raster work is broken in Master

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#3331]
**Description**
I was preparing to test rodolforg's Curve Warp port and before I got to it I noticed that import of raster images (pngs, jpegs) is broken. For example, an imported png would look like this:
![Test](https://github.com/synfig/synfig/assets/28569334/82460026-bd49-4e04-9106-6eaad390b665)

While pngs are a complete mess, jpegs are imported almost correctly but have wrong colors.

**To Reproduce**
On empty canvas, import any png image through "File->Import". It will look similar to the image above with weird lines and wrong colors.

**Expected behavior**
It would have been nice if all supported image formats would display correctly.

**System information:**
Windows 10 Pro, version 2004.
Commit: 7f39534c86faf005dae4ded1ac313d97e353c624
Something broke very recently I believe.

**Comment by yoSachinkr** [comment]
In Appveyor builds, import of raster images except pngs doesn't work at all. Same is with the exports.

**Comment by yoSachinkr** [comment]
> > Something broke very recently I believe.
> 
> @Svarov-RZM @yoSachinkr
> 
> What is the latest version commit you tested and worked?
It has been like that for me in every Appveyor builds. These builds only import/export pngs and export avi for video.

**Comment by rodolforg** [comment]
But they import PNG fine or with the issues svarov mentioned in original post?

**Comment by yoSachinkr** [comment]
@rodolforg pngs are working fine in SynfigStudio-1.5.2-testing-2024-02-04-win64-9153d for me.

**Comment by rodolforg** [comment]
> @rodolforg pngs are working fine in SynfigStudio-1.5.2-testing-2024-02-04-win64-9153d for me.

But not the jpg in this file?~~~~

**Comment by Svarov-RZM** [comment]
> What is the latest version commit you tested and worked?

Last working commit: 613acd23cd2fc43e70b072d6f9af33317a818410
So broken since:  ceb0868bf1f665643f0d6dd89c36a985f01c40e9

Can you reproduce the problem on your machine? Maybe it's a Windows bug?

P.S. @yoSachinkr is talking about unrelated issue caused by packaging setup of Appveyor where it just doesn't include all the libraries needed for additional functionality. I would assume audio playback doesn't work either in Appveyor builds since mlt libraries aren't included.

**Comment by rodolforg** [comment]
@Svarov-RZM do you know what is the magick++ version do you have? Could you please disable this module just for check if everything else is fine?

**Comment by Svarov-RZM** [comment]
Well, I tested the commit and it fixes the problem... partially.
Jpegs are now imported correctly, but pngs are still wrong like in the picture at the top.

In the MSYS pacman reports that my imagemagick version is mingw-w64-x86_64-imagemagick 7.0.10.11-3

**Comment by rodolforg** [comment]
Ouch. I didn't test with transparent images

**Comment by rodolforg** [comment]
@Svarov-RZM and now?
(by the way, and CurveWarp ? ;) )

**Comment by Svarov-RZM** [comment]
Yes, it is indeed fixed, thank you!

> by the way, and CurveWarp ? ;)

Oh, I did some surface tests but don't have a proper conclusion yet. I have a complex work with a lot of Curve Warp layers on top of raster work I was going to test against but raster images were broken. Now that you fixed it, can you please rebase your "cobra-curvewarp" branch to include this fix so I can finish testing?
