### ISSUE TITLE
[GSOC 2024] - Plugin Dialogue Manager and Other Shortcuts

### ISSUE THREAD

**Issue by Funinja** [synfig/synfig#3339]
Hi Synfig Community,

I have a couple ideas I believe is implementable for this year's GSOC which I would like try out as an applicant.

The core features I'm proposing are:
-  Plugin Dialogue Manager with file and git access to access plugins. Optionally, using git to update the plugins automatically, similar to auto-updated plugins on vim.
- Macro system, where a user can easily define a macro to setup a tool or enter a set of actions in one go.
- Shortcuts that can be added be either for the plugin manager or macro system.

If you guys think it's too little or if it's not feasible then let me know and I'll be sure to change it.

Thanks for reading,
Dennis

**Comment by mohamedAdhamc** [comment]
Hello @Funinja 

> Macro system, where a user can easily define a macro to setup a tool or enter a set of actions in one go.

I like the idea, -if I understand it correctly- this would be an alternative to allow synfig users (with no programming knowledge) to automate certain actions. 

Could you elaborate a little on how you envision this Macro system, and the differences between creating a plugin and a macro ? I'm curious to know what you have thought of... :)

**Comment by Funinja** [comment]
> Hello @Funinja
> 
> > Macro system, where a user can easily define a macro to setup a tool or enter a set of actions in one go.
> 
> I like the idea, -if I understand it correctly- this would be an alternative to allow synfig users (with no programming knowledge) to automate certain actions.
> 
> Could you elaborate a little on how you envision this Macro system, and the differences between creating a plugin and a macro ? I'm curious to know what you have thought of... :)

Hi @mohamedAdhamc 

Thanks for commenting!

In creating this feature, the basic difference between a plugin and a macro is that the plugins are scripted using Python while a macro can be created from a history of actions from the user.

For the Macro system, I was thinking it could be similar to how vim macros work. For example to create a 50% transparent square:

1. User inputs the macro start record shortcut followed by a shortcut to activate the macro (say for this example, Ctrl + 6)
2. User selects the square shape icon to create a square
3. User selects the 50% transparent setting for the square creation
4. User draws square
5. User selects mouse tool
6. User inputs the macro stop record shortcut

Then when the macro is inputted (Ctrl + 6), steps 2 to 5 are repeated and the user can create an transparent square.

There are some flaws with it where corner cases would be needed to make sure the program doesn't crash. For example, to create a macro, a person must not select or delete a layer they have not created during the macro process, as when they input the macro they might select or delete a layer that doesn't exist. However, I believe this would greatly increase the workflow of people to remove repetitive tasks in their workflow. 

Additionally, I'm aiming to make an undo Macro and an undo plugin command, as big changes can be made with the macros and I see that currently Synfig has no undo plugin feature.

**Comment by veermetri05** [comment]
Hi, @Funinja .
I loved the concept of Marcos in Synfig. As a Synfig user, it would greatly improve my productivity, and help with repetitive tasks on large number of objects.

> I see that currently Synfig has no undo plugin feature.

You are right that there is no direct undo feature available. 
Here's what happens when you run a plugin
1. Initially you save the file
2. You execute the plugin
3. Your file is modified by the plugin
4. And the modified Synfig file is loaded in Synfig Studio
It is important to note that the new modified file isn't saved by default.
It means that if the user wants to discard the modifications of the plugin, he can simply close the file and re open the file which he initially saved.

So, it is not a true Undo funtionality, but simply the modifications by the Plugin can be discarded.

**Comment by Funinja** [comment]
> veermetri05
Thanks for the info @veermetri05!

That's helpful to know, I didn't realise that the run plugin function actually closes the original file and opens a temporary file with the modifications of the plugin. A little bit more effort will be required I guess to create an undo function for the plugin.

**Comment by Funinja** [comment]
> Hi, @Funinja . I loved the concept of Marcos in Synfig. As a Synfig user, it would greatly improve my productivity, and help with repetitive tasks on large number of objects.
> 
> > I see that currently Synfig has no undo plugin feature.
> 
> You are right that there is no direct undo feature available. Here's what happens when you run a plugin
> 
> 1. Initially you save the file
> 2. You execute the plugin
> 3. Your file is modified by the plugin
> 4. And the modified Synfig file is loaded in Synfig Studio
> 
> It is important to note that the new modified file isn't saved by default. It means that if the user wants to discard the modifications of the plugin, he can simply close the file and re open the file which he initially saved.
> 
> So, it is not a true Undo funtionality, but simply the modifications by the Plugin can be discarded.
