### ISSUE TITLE
Open and save are not working.

### ISSUE THREAD

**Issue by AwesomePaper** [synfig/synfig#336]
**Synfig version & platform**: 1.3.1 & Windows 10

**Issue description**: I can't open any sif and sifz file and save my project.
                                  When I open the file, the message "Uncaught error on file open(BUG)" appears.
                                  And when I save my project, the message "Unable to save to (My Folder)\(My Project).sifz" appears.
                                  How can I fix that?

**Comment by caryoscelus** [comment]
That's not very descriptive. Can you open/save with other versions? What exactly do you mean by "can't"?

**Comment by AwesomePaper** [comment]
I cannot open/save the file in even 1.2.0 version.

**Comment by AwesomePaper** [comment]
I mean "When I open/save the file, an error message appeared.".

**Comment by caryoscelus** [comment]
Well, what error message? Where did you get synfig? (or did you built yourself?) Have you tried another computer, reinstalling, rebooting, etc?

**Comment by AwesomePaper** [comment]
I got 1.3.1 version at sourceforge and got 1.2.0 version at fosshub.

**Comment by AwesomePaper** [comment]
In ubuntu linux, open/save works properly in 1.3.1 version. But in Windows 10, it didn't works.
Reinstalling and rebooting is useless to solve this error.

**Comment by AwesomePaper** [comment]
Also, I can open/save the file in Synfig 1.0.2. It seems that open/save don't works properly after 1.2.0 on Windows 10 only.

**Comment by caryoscelus** [comment]
So, what is the error message?

**Comment by AwesomePaper** [comment]
The error message when I load the file is "Uncaught error on file open(BUG)". And another error message "Unable to load file" appears.
The error message when I save the file is "Unable to save to (My Folder)\(My Project).sifz".

**Comment by caryoscelus** [comment]
Have you tried compatibility mode or something like that? Maybe running in Wine can help.

Are you willing to compile code yourself?

Also, in case you haven't tried, you can try an [empty file (should be renamed to have .sif extension)](https://github.com/synfig/synfig/files/879425/test-empty.txt). Not that it's really likely to help though - the problem shouldn't be in actual parsing code.

**Comment by morevnaproject** [comment]
@AwesomePaper Can you please record a video  showing your attempt to open file? This might help to determine what's wrong. Thank you!

**Comment by AwesomePaper** [comment]
How can I send a recorded video?

**Comment by AwesomePaper** [comment]
OK. I'll send a recorded video.

**Comment by AwesomePaper** [comment]
This video shows open/save error that appears in 1.2.0. This problem is
occured in 1.3.1, too.

2017-03-29 23:55 GMT+09:00 Konstantin Dmitriev <notifications@github.com>:

**Comment by morevnaproject** [comment]
@AwesomePaper Can you please upload video to some file sharing service and provide link here? Alternatively, you can upload video to YouTube (as unlisted) and also send link here. Thank you!

**Comment by AwesomePaper** [comment]
I knew why error message appear. If user name is korean in Windows 10, the error message appears. But if user name is english, the error message not appears. This means a user name must be english if using synfig.

**Comment by ice0** [comment]
Hi! @AwesomePaper can you check this error with Synfig development version? You can download it form https://synfig.org. I checked on version 1.3.6 and all works fine. As far as I know there was an error with filename locale conversion, but it's already fixed.

**Comment by AwesomePaper** [comment]
It works! In 1.3.6 version, synfig doesn't show the error message even in korean user name. Thanks for informing me.
