### ISSUE TITLE
Appimages don't work.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#339]
**Synfig version & platform**:

synfigstudio-1.2.0-64bit-r2
synfigstudio-1.3.1-20170202-64bits

Linux 4.9.20-1-MANJARO 17.1 x86_64 

**Issue description**:

Appimages don't work.

Terminal line:
/tmp/.mount_WSdJs2/usr/bin/synfigstudio: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory

**Comment by morevnaproject** [comment]
@blackwarthog Seems we need to include libselinux.so.1?

**Comment by ebarranco** [comment]
Thanks @blackwarthog  the appimages work fine now with: 
synfigstudio-1.3.2-20170408
