### ISSUE TITLE
Unable to import image via drag-n-drop

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#3409]
If image filename contains non-latin characters, then it is unable to import it via drag-n-drop.

Demo:
![Peek 2024-08-22 16-19](https://github.com/user-attachments/assets/dffa46c0-bd32-4922-988f-cac3dd97f9d3)

Here is a sample file with non-latin characters -
[006_уличный двор_02.png.tar.gz](https://github.com/user-attachments/files/16708331/006_._02.png.tar.gz)

Tested on master branch - 78e866cde56d844b1d2b66d83b5de7249788d0ab

**Comment by ice0** [comment]
Crashes on Windows

**Comment by rodolforg** [comment]
The PR?
