### ISSUE TITLE
Save workspaces.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#341]
**Feature request description**:
The possibility of create, save and delete your own workspaces. #245

**Comment by morevnaproject** [comment]
Hello @ebarranco! Please submit separate issues for both requests.

**Comment by ebarranco** [comment]
@morevnaproject done! I edited this one and I opened a new one with the other feature requested.

**Comment by morevnaproject** [comment]
Great! Thank you! ^__^

**Comment by ebarranco** [comment]
¡Thanks @rodolforg ! This is working very well for me. :+1:

**Comment by rodolforg** [comment]
Shouldn't this issue be closed?

**Comment by ebarranco** [comment]
Yes I think so @rodolforg I did think it was missing some details or something like that but it works fo me. We can close it now. Should I do it?

**Comment by morevnaproject** [comment]
> Should I do it?

Sure! ^__^
