### ISSUE TITLE
Allow manipulation of tangent waypoints in Graphs panel

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#3426]
### Description
In "Graphs" panel we can manipulate waypoints of all the default types (vector, real, etc.) but Radial Composite isn't one of them. Therefore, when you try to move tangent's waypoints in the Graphs you get "Add waypoint: Action is not ready" error:
![ActionIsntReady](https://github.com/user-attachments/assets/f5298da7-b39d-4bae-8a8f-55c3620ff6af)

### To Reproduce
1. Create an outline
2. Move one of the tangents in the animated mode - a waypoint is created
3. Select the tangent you animated in the Parameters panel
4. Go to Menu->Window->Graphs
5. Try to move a waypoint, you'll get the above error

### Expected behavior
Being able to manage waypoints that have Radial Composite type in the Graphs panel. I can understand the problem of moving waypoints if valuenode has some user conversions but in case of Radial Composite it's what Synfig itself saves tangents in by default so it's reasonable to expect them to work.

**Comment by rodolforg** [comment]
It happens also with regular Composite.
I don't know if any other value node type has the same issue.

**Comment by Svarov-RZM** [comment]
> It happens also with regular Composite.

Yeah, but it's not important for this issue, since Composite is not a default type, the user clicked on a node and hit Convert->Composite. 

I'd say let's fix all the default types (don't know if anything is there besides Radial Composite that doesn't work) and leave the rest for the feature request. For example, in "Add" converter we can have LHS as a free node that we can manipulate through Graphs and RHS for user-specified conversion but it'll complicate things, so let's leave it out for now.

**Comment by rodolforg** [comment]
Radial Composite is not a primitive: a tangent is a vector too.

Anyway, I fixed them. Three work hours :P

**Comment by Svarov-RZM** [comment]
> a tangent is a vector too.

I know. Someone along the line thought that storing tangents as Radial composites instead of plain vectors was a good idea. I don't know what reasoning was behind that... We could change it but then we would have to care about backwards compatibility, additional hooks in loadcanvas.cpp, not sure it's worth it.

> Anyway, I fixed them. Three work hours :P

Thanks dude, I do appreciate what you do for Synfig. I am sorry if I am causing you stress... Please don't feel obligated to fix any of my issues, I don't want you to burn out. If you feel like taking a break, please do, it is open source, you don't owe anyone your time. I was about to post two more issues, tell me if it's alright, or I will just chill out for some time with all this posting.

**Comment by rodolforg** [comment]
> Someone along the line thought that storing tangents as Radial composites instead of plain vectors was a good idea.

I think the reason is about tangent vector being normally referred by polar coordinates, as modulo and angle is more intuitive regarding the direction the curve will follow.

Origin is a 'vector' but is more like a point...

> Please don't feel obligated to fix any of my issues, I don't want you to burn out.

No worries. I just thought it would be simpler and faster :P

> I was about to post two more issues, tell me if it's alright, or I will just chill out for some time with all this posting.

You can do it :) If I'm (we're) tired or unable or indifferent to solve them, I just drop it or try it later.
I'm struggling to finish the port remaining layers to Cobra renderer due to some pixel shifting, so it's good to have other stuff to do. ;)

**Comment by Svarov-RZM** [comment]
> I'm struggling to finish the port remaining layers to Cobra renderer

Yeah, this is a hard task. The whole situation with Cobra engine where the lead programmer left mid-development still angers me to this day... Wish you luck with this task and you can always ping me if you need some testing to be done.

> You can do it :)

Alright then, I am gonna post a pretty heavy issue later today.
