### ISSUE TITLE
Flatpak reports that runtimes have reached EOL

### ISSUE THREAD

**Issue by J-Verz** [synfig/synfig#3432]
**Describe the bug**
I have Synfig installed through Flatpak. Since about a week I get the following messages when running `flatpak update`, reporting that the used runtimes org.gnome.Platform, org.freedesktop.Platform.VAAPI.Intel and org.freedesktop.Platform.GL.default are end-of-life:
```
Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   org.synfig.SynfigStudio

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.synfig.SynfigStudio

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.synfig.SynfigStudio
```

Is this something that I can fix myself?
Thanks!

**System information:**
 - Linux distro: Ubuntu (Kubuntu)
 - OS version: 24.04.1
 - Package: Flatpak
 - Synfig version: 1.5.3

**Comment by BobSynfig** [comment]
Known issue https://github.com/flathub/org.synfig.SynfigStudio/issues/21

@ice0 : can't we just force runtime-version to 44 instead of waiting for the original PR's poster to make a change?
It seems that he doesn't have activity here for a lot of months

**Comment by ice0** [comment]
Hi guys!
I'm currently working on this. There are some issues with the ImageMagick libraries after switching to GNOME 46, but I plan to fix it soon.

**Comment by ice0** [comment]
Should be fixed now.

**Comment by J-Verz** [comment]
Great, thanks! :fire:
