### ISSUE TITLE
Layer color doesn't change simultaneously when multiple layers are selected

### ISSUE THREAD

**Issue by Stas-Kholodilin** [synfig/synfig#3469]
**Describe the bug**
When multiple layers are selected and you change color, the color is applied only in the upper layer instead of all of them. 
**To Reproduce**
1. Create 2 or more circles.
2. Select all of them
3. Change layer color
4. See that the color changes only in the upper layer.

**Expected behavior**
The same color should be applied in every selected layer. 

**System information:**
 - OS: Linux 6.1.1.110-1.el7.3 x86_64 x86_64
 - OS version: RED OS, MATE 1.28.1
 - Commit ID: Synfig-Studio Master branch.

**Additional comments**
It does work in the version 1.5.3, but not in the master branch version. The other parameters, such as radius, work as expected.

**Comment by Zloi-KoteikA** [comment]
This bug introduced in bab18f404daeda872435fbf1eea8cc5820782f7a

Part of PR #3373

@rodolforg
