### ISSUE TITLE
Synfig's Interface went Too Thick

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#348]
**Synfig version & platform**:
synfig dev version 1.3.2 and 64bit Windows 10

**Issue description**:
uhm.. well, this is interesting...
so i just installed the new dev version and i got some vividly noticeable bugs
here's the first one

![snip_20170423194946](https://cloud.githubusercontent.com/assets/25135159/25314163/fb5317f2-2868-11e7-8cc7-d89c097820ed.png)

as you can see, the whole interface went thick out (even more noticeable in the carat button)
as for those greyed words, look over here : #349

**Comment by caryoscelus** [comment]
>i also have no idea what does it do though ._.

It's actually visible on your screenshots: toolbar on first one contains new/open/save/... buttons and on seconds one starts right away with undo/redo buttons.

As for thickness, it's probably because bundled gtk theme has changed. I have no idea how to change it on windows though.

**Comment by morevnaproject** [comment]
Hello, @FadhilKwan! Please split this topic to separate issues:
- thick interface
- grayed elements in Window menu

**Comment by FadhilKwan** [comment]
@caryoscelus oh, i understand now, thank you!! :)
@morevnaproject sure thing. i'll be right back ;)

**Comment by morevnaproject** [comment]
@blackwarthog You might need to use GTK Inspector to fix this.

First, enable GTK inspector for your environment:
```$ gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true```

And then you can start any GTK application with Inspector by passing ```GTK_DEBUG=interactive``` into commandline. I.e.:
```$ GTK_DEBUG=interactive synfigstudio``` 

See also - https://blog.gtk.org/2017/04/05/the-gtk-inspector/

**Comment by blackwarthog** [comment]
Is it ok?

![2017-08-09 21 08 00](https://user-images.githubusercontent.com/5143743/29125898-873bbb26-7d4f-11e7-9b56-bf56de5b5655.png)

**Comment by FadhilKwan** [comment]
Yaaaaayyy!!! 😄

**Comment by morevnaproject** [comment]
Now shipped with Synfig 1.3.5 - https://morevnaproject.org/2017/12/25/synfig-studio-1-3-5/
