### ISSUE TITLE
Cannot Hide Toolbars Via Preferences

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#350]
**Synfig version & platform**:
Synfig 1.3.2 & 1.3.1 and 64bit Windows 10

**Issue description**:
**EDIT:
This is not a bug, please ignore this issue...**

i disabled this option here and restarted my Synfig, and it doesn't work (look to the left)
![snip_20170423200558](https://cloud.githubusercontent.com/assets/25135159/25314235/5cc184c8-286a-11e7-8cb4-be132e3d3609.png)

same goes to earlier dev version (1.3.1)
![set3](https://cloud.githubusercontent.com/assets/25135159/25314251/ba403f72-286a-11e7-8d62-d567480f5006.png)

**Comment by caryoscelus** [comment]
I don't see a bug. On your screenshots option is disabled and there is no file toolbar..

**Comment by FadhilKwan** [comment]
oh... it's this one......
![set4](https://cloud.githubusercontent.com/assets/25135159/25314453/4c96663c-286e-11e7-9d05-8323422a9ad0.png)
now i'm really ashamed... -_-

@caryoscelus could you please tag this as "Not a Bug" ?
i couldn't find any way to erase this issue :(
