### ISSUE TITLE
Some Texts in Installer and Splash Screen Gone Missing

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#352]
**Synfig version & platform**:
Synfig Version 1.3.2 and 64bit Windows 10
just in case if it helps, i'm using the Japanese locale

**Issue description**:
As far as i can found this isn't a major issue. More of cosmetic-ish ones
But it was right there so might as well reporting this one

so usually the installation window has some texts like these
![st2](https://cloud.githubusercontent.com/assets/25135159/25337225/3afaf2e6-2925-11e7-8a57-a9bd235dca54.png)

but in 1.3.2 , it's missing
![st1](https://cloud.githubusercontent.com/assets/25135159/25337244/4f1e8ab2-2925-11e7-8941-4232beed7751.png)
and same goes to the uninstaller for 1.3.2
Oh, and just to point out, the license agreement look slightly different on the header

as for the splash screen, here's a proof
![st3](https://cloud.githubusercontent.com/assets/25135159/25337279/71530658-2925-11e7-9109-1a3733cb60ec.png)

**Comment by Keyikedalube** [comment]
> so usually the installation window has some texts like these

This is still a thing with 1.4.1

![Screenshot_2021-07-13_12-11-01](https://user-images.githubusercontent.com/24214509/125405955-ebe31880-e3d5-11eb-91ea-d583c11c2c59.png)

Below is notepad++ with a similar license review statement

![Screenshot_2021-07-13_12-20-34](https://user-images.githubusercontent.com/24214509/125406333-58f6ae00-e3d6-11eb-86e0-aef2f2630eab.png)

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
