### ISSUE TITLE
Crash when saving as png spritesheet

### ISSUE THREAD

**Issue by aGodsky** [synfig/synfig#356]
Synfig version 1.2.0 x64 / Windows 10 x64:

Program crash while trying to save as png-spritesheet
Seems the issue only with this save option, tested in Administrator mode - still crashes

**Comment by caryoscelus** [comment]
I can confirm the crash when rendering some files.

However, before crash synfig tells this in console:

```
Uninitialized sheet parameteras. Reset parameters.
Frame count121
synfig(22005) [12:53:50] error: [read_png_file] File /data/all/tmp/Test1.png could not be opened for reading
synfig(22005) [12:53:50] error: The image is too large. It's size must be not more than 5000*2000=10000000 px. Now is 77440*360=27878400 px.
set_rend_desc()
Frame count121
synfig(22005) [12:53:50] error: [read_png_file] File /data/all/tmp/Test1.png could not be opened for reading
synfig(22005) [12:53:50] error: The image is too large. It's size must be not more than 5000*2000=10000000 px. Now is 77440*360=27878400 px.
start_frame()
Segmentation fault
```

Rendering small files (e.g. 32x32 24 frames) works fine.

While it might not make sense to allow enormously large sprite-sheets, the crash itself is still a bug.
