### ISSUE TITLE
Bug Synfig Studio 1.3.2 Dynamic connect

### ISSUE THREAD

**Issue by Toybulldog** [synfig/synfig#360]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

Hello synfig people
my name is peter , and I come from germany .

In my video you can see the problem .
https://vimeo.com/216629892

I hope the Synfig Studio is further developed .
thank you for the effort

Lg peter

**Comment by caryoscelus** [comment]
Closing this in favour of #362 which has better text description.
