### ISSUE TITLE
BONES structure is saved before DEFS structure

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#362]
### Description:
If there're bones in Synfig project, they will be saved BEFORE defs structure. It means, that all exported values that attached (linked) to bones will not resolve correctly and Synfig won't be able to open a file.

### Affected version:
All Synfig versions started from 1.0.2.

### To reproduce:
Open attached file in Synfig and then just save it somewhere else or as sifz file. Now, try to open the newly saved file. You can't.
[BoneFollowsSpline.zip](https://github.com/synfig/synfig/files/987120/BoneFollowsSpline.zip)

Relevant: https://github.com/synfig/synfig/issues/360
That guy has the same problem. He even made a whole video about it.

P.S. Cursed github doesn't allow sif/sifz attachments.

**Comment by caryoscelus** [comment]
Yeah, i think it's pretty widely known issue. AFAIK, can be solved by un-exporting values, but i may be wrong.

**Comment by rodolforg** [comment]
@Svarov-RZM I know it has been a long time, but can you please test it (if you are able to build synfig)?

**Comment by Svarov-RZM** [comment]
@rodolforg I don't have a development setup to build Synfig, I am just a user.
But if someone provides a test build for Windows - I'll test it right away.

**Comment by ice0** [comment]
Portable version with this changes:
https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.0-testing-2020.02.27-win64-ca377.zip

**Comment by Svarov-RZM** [comment]
@ice0 @rodolforg @blackwarthog 
Well, yeah, it's working now, partly.
Fixing this problem introduces another one - you can't link exported vertexes to the bone. This was fixed before this issue by placing \<bones\> before \<defs\> structure (see this recent thread https://github.com/synfig/synfig/pull/1176).

Some more in-depth thinking is needed to correctly solve this issue. I actually was wondering why \<bones\> couldn't be placed **inside** \<defs\>? Anyway, to reproduce the issue I attached another file. Connect one of 'IamExported' vertexes to 'ConnectToMe' bone, save, and file won't open upon reload. 
[BoneToExportedSpline.zip](https://github.com/synfig/synfig/files/4269965/BoneToExportedSpline.zip)
