### ISSUE TITLE
problem with auto-recovery (1.3.2 and 1.1.11 version)

### ISSUE THREAD

**Issue by boubouh** [synfig/synfig#363]
**1.3.2 and 1.1.11 version & Ubuntu 16.04**:

**after i install Synfig Studio 1.3.1 (development) in my system (Ubuntu 16.04) on top of Synfig Studio 1.1.11, the auto-recovery no more working .....
i try uninstall (purge) all synfig package and install the last development version 1.3.2...but the problem still there ....**

**Comment by boubouh** [comment]
Has anyone run into the same problem !!??

**Comment by morevnaproject** [comment]
Can you please provide exact steps to reproduce the problem?

**Comment by boubouh** [comment]
There are two kinds of problems:

1-if synfig crash after i save my scene minimum once: in this case nothing happen after i restart synfig...(no recovery message ).

2-if i don't do any save and synfig crash: in this case, i can see the recovery message but when i click recovery ......  recovery give me error (see image).


![1](https://cloud.githubusercontent.com/assets/5199504/25978902/2443eba2-36bd-11e7-89a0-d0c28a872e6f.png)

![2](https://cloud.githubusercontent.com/assets/5199504/25978918/4870efde-36bd-11e7-9aaa-977b946c6dad.png)

![3](https://cloud.githubusercontent.com/assets/5199504/25978920/4e35784a-36bd-11e7-950b-b8bb93432312.png)

**Comment by morevnaproject** [comment]
Thank you for detailed description! We will take a look at this problem.

**Comment by blackwarthog** [comment]
Should we to delete backups when user don't want to load it (pressed "ignore" at startup)?

**Comment by morevnaproject** [comment]
Yes, it's ok to delete them.

**Comment by blackwarthog** [comment]
Fixed with some [restrictions](410) #410

**Comment by morevnaproject** [comment]
Now shipped with Synfig 1.3.5 - https://morevnaproject.org/2017/12/25/synfig-studio-1-3-5/

**Comment by boubouh** [comment]
thank you
