### ISSUE TITLE
Let the user rename layers

### ISSUE THREAD

**Issue by WPFilmmaker** [synfig/synfig#367]
**Synfig version & platform**:
Synfig 1.3.3

**Issue description**:
Hi, I couldn't find a way to rename layers, hence I thought this feature was not implemented and thought it would be useful especialyl when you work with many layers. Give the user the ability to rename layers. Ideally by right-click on the layer->menu->rename.

**Comment by caryoscelus** [comment]
They can be renamed by left-clicking on layer name or by rmb->set layer description.

**Comment by morevnaproject** [comment]
Also you can rename any layer by just clicking on its name with left mouse button.
