### ISSUE TITLE
Preview settings - Frame range not remembered

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#371]
**Synfig version & platform**:
1.3.3

**Issue description**:
Frame range is reset to canvas defaults after each preview.

**Comment by zozorg** [comment]
I'm using version 1.3.4 and frame range still isn't remembered?

**Comment by morevnaproject** [comment]
This is fixed in current development source code and will be shipped with 1.3.5. 

You can see the list of issues pending for releasing on this page - https://github.com/synfig/synfig/projects/1 (the ones in the "Done" column).
