### ISSUE TITLE
Implement a correct sorting in 'Sets'

### ISSUE THREAD

**Issue by Svarov-RZM** [synfig/synfig#372]
### Description:
Synfig has a very nice thing called 'Sets'. You can add diffident control layers in it and easily access them from one place. I use it extremely. But layers inside a set are sorted randomly without any pattern: nor alphabetically nor by Z depth, which increase the time to find the needed layer. This is how it looks:
![setssorting](https://cloud.githubusercontent.com/assets/28569334/26545409/2cd76d34-446e-11e7-91ca-0a619e51b9a8.png)

See? Random order, but should be: R-1, R-2, R-3, etc.

### Feature request:
Implement a correct sorting algorithm in 'Sets' panel. It can sort by name or by Z depth. For me, alphabetical sorting would be ideal, but if it possible to implement different methods it would be great.

### To reproduce:
Open attached file (done in 1.3.3) and go to 'Window->Sets', you'll see that layers are sorted in a random order.
Note: Synfig can actually sort it right sometimes, so if it looks OK, restart the program several times until you see a screwed up sorting.
[BadSorting.zip](https://github.com/synfig/synfig/files/1035475/BadSorting.zip)

### Experienced on:
All versions since 1.0.2 on Windows 10. Didn't test on other platforms.

**Comment by zozorg** [comment]
Added $10 ( total $25 ), it would be even better to be able to move it around ( kind of a "group Z-depth" ), but alphabetical order should be OK too.

**Comment by caryoscelus** [comment]
As far as i can tell, it sorts by "last added to set". You can see this by creating two sets and dragging layer around them: it will always come on bottom.

Anyway, if you're ok with sets themselves being sorted, name sorting should be pretty easy to implement. In fact, i already got sorting half-working (newly-added layers are not sorted, until you click).

**Comment by caryoscelus** [comment]
So yeah, name sorting works fine now.
![sets_sorted](https://user-images.githubusercontent.com/1758893/33908190-7d7ac338-df7f-11e7-8d5c-a1faf95b0520.gif)

**Comment by caryoscelus** [comment]
Added z depth as well.

**Comment by caryoscelus** [comment]
>Svarov rejected: Hey, I would like to test it first before accepting the claim. Can you provide an installer with 'Sets' fixed? Or we can always wait for the official dev build. 

I can build .deb for debian testing or unstable, i guess. Or you can wait for morevna project build. I don't care either way.

**Comment by morevnaproject** [comment]
I have configured our buildbot to make a test build for this feature. Should be ready by tomorrow. ^__^

**Comment by morevnaproject** [comment]
/remind me about the thing in 12 hours

**Comment by morevnaproject** [comment]
@Svarov-RZM @caryoscelus Please check the test builds:
https://dev.icystar.com/downloads/SynfigStudio-1.3.5-testing-17.12.18-win32-11676.exe
https://dev.icystar.com/downloads/SynfigStudio-1.3.5-testing-17.12.18-win64-11676.exe
https://dev.icystar.com/downloads/SynfigStudio-1.3.5-testing-17.12.18-linux64-11676.appimage

**Comment by Svarov-RZM** [comment]
Tested it. Works perfectly - thanks!

@caryoscelus 
You can submit the claim again.
Seems that bountysource does not allow you to change your mind after you initially rejected the claim :(
