### ISSUE TITLE
Moving Dockers Makes the Cursor Disappear

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#374]
**Synfig version & platform**:
Synfig Dev Ver. 1.3.3
On Windows 10 at 64-bit

**Issue description**:
So i decided to get this version (and glad to find out that the greyed 'Window' has already fixed ^^ )
and tinkering around it a little bit more
While rearranging my 'big-sized' dockers i found this

![snip_20170607204545](https://user-images.githubusercontent.com/25135159/26881832-d0e2f0c8-4bc2-11e7-8d17-f026cc8988ab.png)

Well to say the least, i like the highlighted docker feature. Pretty fancy looking.
And the Icon for the window that you're dragging at the moment was shown on top left of the 'screen' window (A little bit awkward of a placement to be honest, but i'm fine with it :)  )

Although sadly, **i cannot see my mouse cursor at all while dragging the docker window**. It's legit gone while i'm doing it, and reappear after dropping it back on any position, making it much harder to place them around

Honest question : Was that supposed to happen...?  ._.

**Comment by morevnaproject** [comment]
Fixed. See https://github.com/synfig/synfig/issues/536#issuecomment-615878955 for details.
