### ISSUE TITLE
Future onionskins show at full opacity

### ISSUE THREAD

**Issue by Codebreakerblue** [synfig/synfig#377]
**Synfig version & platform**: Synfig Studio v1.2.0, Mac OS X v10.9.5
(we're more likely to help if you're using latest development builds)

**Issue description**: Future onionskins make the current frame invisible while showing the onionskin of the keyframe at full opacity, but only while there are one or more past onionskins showing.

**Comment by morevnaproject** [comment]
Fixed in master branch by @blackwarthog.

**Comment by morevnaproject** [comment]
The fix is available for testing in Synfig Studio 1.3.11 - https://www.synfig.org/2019/02/16/synfig-studio-1-3-11-released/
