### ISSUE TITLE
Option in drop down menu removed all drop down menus.

### ISSUE THREAD

**Issue by Peachea** [synfig/synfig#378]
Synfig Studio (Latest version for Mac)
Just installed the program yesterday and was going through menu options. Accidentally click on a drop menu option and the entire bar went blank. I have no "File, Edit, View...etc." options on my top bar.

Tried uninstalling and reinstalling the program, no solution. It reinstalled without the menu.

**Comment by morevnaproject** [comment]
Please right-click at empty space on the canvas and select "View" -> "Show Menubar".
