### ISSUE TITLE
UTF-8/national chars not supported for Text layers

### ISSUE THREAD

**Issue by alivedsn** [synfig/synfig#379]
Version: Windows 1.2.0 32bit, 64bit

Dear collegues,

Synfig is a great instrument I'd like to recommend to the users of my system (creation of animated logos, subtitiles, ads, etc). I just found a big disgrace inside Synfig, that can prevent it from using inside Russia (and other countries, too). In the forum, I found the discussion on Spanish characters in the Text layers. For Russian, the things are the same, and even worse.

I'm entering the Russian text. Using Arial font (that definitely has cyrillic characters) - I also tried other fonts with the same result. The preview animation looks awful. As Russian is UTF-8-encoded, every cyrillic letter is presented with 2 bytes (UTF-8). At the preview, each of these bytes are printed separately. 

Please see the screenshot. At the back, under the Synfig window, there's a UTF-8 encoded file in HEX editor with the same text (first 3 bytes are BOM). They are completely the same as at the Synfig preview. This means the Synfig doesn't receive the text in UTF-8 at all, but renders it in ASCII/ANSI. Meanwile, the SIF files are in UTF-8, so it is a disaster.

This is a severe bug that will prevent any national languages from using with Synfig. Would you please study this.
![bug_utf-8](https://user-images.githubusercontent.com/29565737/27322269-30af536a-55a6-11e7-9ba0-d03f8a68e17c.jpg)

**Comment by morevnaproject** [comment]
Yes, this is a known problem of Windows version. Unfortunately, we haven't had time to fix it yet. Consider that with Linux version international text works fine.

**Comment by alivedsn** [comment]
Dear Konstantin,

Thanks a lot for your prompt reply (продолжаю по-английски на всякий случай). Sorry to consume your time, but I'm trying to show the importance of this.

Synfig is a great instrument that could be successfully used for many serious applications (other than amateur cartoons):
- commercial ads
- logotypes
- announcements
- captions, moving subtitiles
- alerts
- public messages
- many others

I mean the use at any public screens in conjunction with our Digital Labeling technology (based on Kramer VCO / DL machines). See attached brochures.
https://www.kramerav.com/news/Press_Releases/Kramer_Introduces_First_Complete_Video_Content_Overlay_Solution_at_InfoComm_2016

This is a brand new idea, and now it starts to spread around the world. Why not to let Synfig be a useful tool for another application? This can only make it more popular (I don't mean it to become a paid application, but some benefit to the development is possible).

For now, the animated overlays are made within Adobe Photoshop - with Animation palette. We have a limited support for PSD format (awful by itself), and imagine the price of this solution for an end user.

Most of the users are small (like tiny shops, fitness centres, sport bars, etc) with very limited budget, and zero knowledge of Photoshop. They will need a free (or low-cost) tool to use; I can't find anything in this world compared to Synfig that precisely fits the task. Moreover, these customers are mostly unable to create a fine design - so they will need an external support. All freelance amateurs for Synfig could help them, and to earn some money from this job (do you want to help your poor students?).

The Synfig file format is very easy to use with VCO Setup application; the Synfig command-line renderer is just what is needed; the PNG animated sequence is completely intistic for our VCO Setup. So everything works well - except the UTF-8 support (and lack of font selection dialogue). 

The templates created in Synfig MUST comprise Text Layers with variables (like {TEXT}). These variables may be substitued with user values by VCO Setup application (user will type-in his/her text, and VCO Setup will replace the variables with this text ("{TEXT}" will be replaced by "my message") in the Synfig file. Then Synfig will render the result. This is the minimum requirements for variables (we can apply variables to other properties; this is the thing to think).

Nobody at this market will need Linux; please consider Windows as a basis (as long as we don't have MacOS version). I see no reason why not to fix this bug in Synfig. As a temporary workaround, you could convert UTF-8 to ANSI (using the OS locales), and then render ANSI - this will support national characters at least for the Windows version installed.

A font selection dialogue is a very basic Win API thing, could be implemented within an hour, I guess.

Best regards
Serge Dmitrenko
Technical Support Service
Kramer Electronics Ltd., Russia | CIS | Baltic | Eastern Europe
dsn@kramer.ru
www.kramer.ru


  ----- Original Message -----

**Comment by caryoscelus** [comment]
@alivedsn 
If you have business interest in this, i'm sure you won't have a problem hiring a developer to fix these issue for you.

**Comment by alivedsn** [comment]
My project is freeware (though not open source), and I have no budget for this. I guess these are Synfig programmers who are interested in making the project more serious (and less cartoonish). And, who (if not the creators) can do this with ease? Or, you are so neutral to your own project, that even the obviuos bugs mean nothing? Or, nobody cares?

**Comment by caryoscelus** [comment]
Do you realize that these issues (among many others) were known for years? That "the creators" have left the project some 10 years ago? That manipulative comments from someone who is unwilling neither to share source nor to spend money nor to help project in other way are at best not very motivating?

**Comment by morevnaproject** [comment]
Hello again, @alivedsn! 
Apologies for not responding earlier - at the moment my (small) team is busy at other frontiers.
We can try to fix this bug (when we have time), but (unfortunately) this is not the only problem with Text Layer. The current implementation of Text Layer snaps all lines to pixels (!) which makes any animation of text jagged. Another problem is that Text Layer is slow, which makes it hard to use (when you have multiple layers of text). Those problems should also be fixed, to allow use Synfig for circumstances you described. 

Personally, I am waiting for a good moment to re-write the whole Text Layer from scratch, but unfortunately we got distracted by other small tasks right now.

**Comment by alivedsn** [comment]
Sorry if my posts seemed to be abusive or manipulative. The only puprose is to prove the importance of the above - and to further promote the software. As I'm new to Synfig, I knew nothing about it to be 10 years orphan, or these bugs to exist for years. Sorry for this.

**Comment by alivedsn** [comment]
Yes, I have no budget to directly support the project. Yes, my project is not open source - and believe me, my sources are not of great interest to anyone, as they are tied with a very specific hardware. The only advantage I can offer - is the promotion, and possible earnings for those designers that use Synfig. Got nothing more motivating yet...

**Comment by alivedsn** [comment]
Konstantin, pixelization of the text is not a big problem for my application - as I need small resolutions in fact (something between 50x50 and 1920x1080 pixels). I experimented with text warping in Synfig, and the results seems to be absolutely fine for this. So, of course, re-writing and upgrading will be great, but even some temporary workaround for UTF-8 would help us just now. Anyway, thank you for your reply; I will keep hope...

**Comment by morevnaproject** [comment]
> pixelization of the text is not a big problem for my application

Just to mention: The problem is a bit different than pixelization. Here is a simple example of animated text:
![text-problem](https://user-images.githubusercontent.com/332868/27965875-5b9f8896-6367-11e7-9244-3d728ff97c1b.gif)
Source file - 
[text-problem.sifz.zip](https://github.com/synfig/synfig/files/1131539/text-problem.sifz.zip)

The text layer makes simple movement, but you can see the letters are "dancing". :(

**Comment by alivedsn** [comment]
Thanks a lot for illustration. Yes I see that there's no some kind of anti-aliasing to avoid this effect.  I loaded your project to my device, and yes, it is visible. But - it is not a big problem yet - because in most cases the text will be static (while other elements like pictures, animated characters, etc will move around) - and in many other cases, the text will move only horizontally or vertically (not diagonally), so this effect will also be less visible. With bigger font size, it also becomes invisible (for the same resolution). 

So - in most cases Synfig will fit the task today. Some small (quality) limitations may exist - and this also is not a big trouble (especially remembering that this is a free tool).

**Comment by Svarov-RZM** [comment]
I am also interested in this issue to be solved.
So I posted a $15 bounty for this, maybe it'll motivate someone.
https://www.bountysource.com/issues/46390853-utf-8-national-chars-not-supported-for-text-layers

**Comment by morevnaproject** [comment]
The fix is shipped with Synfig Studio 1.3.4 - https://morevnaproject.org/2017/08/10/synfig-studio-1-3-4-released/

**Comment by morevnaproject** [comment]
@Svarov-RZM Thank you so much for posting a boutny on this! Please check if the solution works for you. ^__^
