### ISSUE TITLE
Parameters panel collapses items on edit

### ISSUE THREAD

**Issue by CoryAlbrecht** [synfig/synfig#386]
When Animation Mode is enabled, then editing any sub-parameter, which wasn't animated previously will collapse all items in Parameters Panel.

Steps to reproduce:
1. Create Group Layer
2. Turn on Animation Mode
3. Expand Transformation Parameter
4. Edit Angle Parameter
5. -> Transformation parameter collapsing

Original post:

> When editing vertices in a spline, the parameters panel will unpredictably collapse everything after you edit an item, like the tangent values. This doesn't happen all the time, but it does happen more the 75% of the time, and is very frustrating when you're trying to edit a spline with multiple vertices.

See also:
- https://forums.synfig.org/t/weekly-reports-2022/12854/4?u=konstantindmitriev
- https://github.com/synfig/synfig/issues/466
- https://github.com/synfig/synfig/issues/573

**Comment by morevnaproject** [comment]
It is hard to understand the problem from description. Can you please record a video illustrating your problem?

Also, please clarify the version of Synfig you use - there is no such version as 1.0.3 available. Thank you.

**Comment by CoryAlbrecht** [comment]
Typo, that should be 1.0.2, what gets installed by apt-get on Ubuntu.

Also, I'm not sure how much clearer I am make it.

It goes from this 
![image](https://user-images.githubusercontent.com/8172909/29277370-7134854a-80df-11e7-8ba1-562f12bb6d16.png)

to this
![image](https://user-images.githubusercontent.com/8172909/29277404-8fbcc900-80df-11e7-81af-5f0be5f73beb.png)

That's very annoying when you're trying to edit a line to get it to look just right and more often than not you have to go an re-expand everything in the parameters panel.

**Comment by CoryAlbrecht** [comment]
Here is a video of it happening the 1.2 AppImage as well. Notice how the expanded items fro vertices disappear after pressing enter on the Y coordinate for a vertex and how the entire list of vertices is then collapsed.

[synfig-annoying.mp4.zip](https://github.com/synfig/synfig/files/1268718/synfig-annoying.mp4.zip)

**Comment by Keyikedalube** [comment]
Is this reproducible on latest stable release v1.4.2?

I tried to replicate your video demonstration by changing the Vertex value, and Tangent value too. The Vertices tree didn't collapse.

**Comment by morevnaproject** [comment]
@Keyikedalube The tree collapsing if those 2 conditions apply:
1. You have Animation Mode enabled
2. You are editing parameter, which wasn't previously animated.

Can we do something about this issue?

**Comment by morevnaproject** [comment]
I have edited the original post at the top.

Can we do something about this issue?

**Comment by rodolforg** [comment]
> The tree collapsing if those 2 conditions apply:
> 
>     1. You have Animation Mode enabled
> 
>     2. You are editing parameter, which wasn't previously animated.

My guess is that's what is causing this issue #2390 (after ice0 investigation).

There is a `rebuild()` call when it  should be a `queue_refresh()`, but there is old comment 'explaining' why it was changed.
https://github.com/synfig/synfig/blob/ad03efe3b70e507a4632fe14a55acd149be60477/synfig-studio/src/gui/trees/layerparamtreestore.cpp#L591-L602
