### ISSUE TITLE
Volume parameter does not actually change audio clip's volume

### ISSUE THREAD

**Issue by CoryAlbrecht** [synfig/synfig#388]
Synfig Studio 1.0.3 on Ubuntu 16.04.2 GNOME

If you change the "Volume" parameter in the Parameters panel for an audio clip, there is no discernible change in volume when playing the project, up or down.

**Comment by morevnaproject** [comment]
Please clarify the version of Synfig you use - there is no such version as 1.0.3 available. Thank you.

**Comment by CoryAlbrecht** [comment]
A typo on my part. 1.0.2, what gets installed with apt-get in Ubuntu.

**Comment by morevnaproject** [comment]
Should be fixed by 1f4abf1812809da6b2a61d7702b4f41a81d6920e

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
