### ISSUE TITLE
Synfig Studio cannot open files it has just recently saved

### ISSUE THREAD

**Issue by CoryAlbrecht** [synfig/synfig#402]
Synfig Studio 1.0.2 on Ubuntu GNOME 16.04.2

Saved as a *.sif file then later tried to reload and continue working on the project.

![image](https://user-images.githubusercontent.com/8172909/29289348-13065dc4-810a-11e7-9147-a2cbe3802122.png)

The .sif file that produces the error along with the referenced PNG files.
[synfig-error.zip](https://github.com/synfig/synfig/files/1223326/synfig-error.zip)

**Comment by rodolforg** [comment]
This issue is fixed in v1.4.1.
