### ISSUE TITLE
Home, End keys do not work as one would intuitvely expect 

### ISSUE THREAD

**Issue by CoryAlbrecht** [synfig/synfig#403]
Synfig 1.0.2 on Ubuntu GNOME 16.04.2

When editing the name field of a layer or any of the text fields in the properties panel, the Home and End keys do not work as one would intuitively expect.

When a text field is active and has focus, pressing the Home key should go to the beginning of that focused field and not jump you to the first key frame. Similarly, pressing the End key should not take you to the last key frame but instead to the end of the text field that you are editing.

UI focus and context and how that affects the actions a program takes based on user input is important for making a piece of software both usable and user friendly. Violating common UI/UX standards which require the user to essentially relearn how to interact with the computer do not make it easier to use.

**Comment by morevnaproject** [comment]
Related with #257

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
