### ISSUE TITLE
synfigstudio.desktop does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [synfig/synfig#406]
`synfigstudio.desktop: error: value "Graphics" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character`

This prevents it from being addded to https://github.com/AppImage/AppImageHub.

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266243433#L538

**Comment by morevnaproject** [comment]
Hello! Please test the latest appimage from sourceforge - https://sourceforge.net/projects/synfig/files/snapshots/1.3.4-20170810/

**Comment by probonopd** [comment]
Hi @morevnaproject using https://sourceforge.net/projects/synfig/files/snapshots/1.3.4-20170810/SynfigStudio-1.3.4-testing-17.08.10-linux64-9fecd.appimage/download I still get `synfigstudio.desktop: error: value "Graphics" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character`.

Did you test it with `desktop-file-validate`?

**Comment by blackwarthog** [comment]
Fixed here: https://github.com/morevnaproject/morevna-builds/commit/6d5482445daf5c1265bce1ec7d98eb5963404aac

You may check new appimages here:
https://dev.icystar.com/downloads/SynfigStudio-1.3.4-testing-17.08.25-linux32-9fecd.appimage
https://dev.icystar.com/downloads/SynfigStudio-1.3.4-testing-17.08.25-linux64-9fecd.appimage

**Comment by probonopd** [comment]
Thank you. Would there be any chance that this might get uploaded to https://github.com/synfig/synfig/releases eventually?

**Comment by morevnaproject** [comment]
Fix will be shipped with 1.3.5.
