### ISSUE TITLE
Localization broken since 1.3.3

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#408]
**Synfig version & platform**:
Synfig 1.3.3 and 1.3.4

**Issue description**:
Since Synfig 1.3.3 layer parameters are always displayed in English (while locale settings is not English).

**Comment by blackwarthog** [comment]
I cannot reproduce

![2017-08-25 15-39-11](https://user-images.githubusercontent.com/5143743/29706296-95152710-89ab-11e7-9973-814bb4a93ff9.png)

**Comment by blackwarthog** [comment]
I've reproduced :) and fixed this bug
