### ISSUE TITLE
Draft rendering mode

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#409]
Add Draft Rendering mode.

In this mode Synfig will render only the limited set of layers with necessary approximations, to achieve the proper (real-time) performance.

The Draft rendering mode will have following layers disabled:
- Motion Blur
- Radial Blur
- Curve Warp
- Inside Out
- Noise Distort
- Spherize
- Twirl
- Warp
- Metaballs
- Clamp
- Color Correct
- Halftone 2
- Halftone 3
- Luma Key
- Julia Set
- Mandelbrot Set
- Conical Gradient
- Curve Gradient
- Noise Gradient
- Spiral Gradient
- Duplicate
- Plant
- Super Sample
- Text (will enable after this layer will get ported to Cobra)
- XOR pattern

The following layers will render with simplifications:
- Images
  - resampling forced to nearest neighbor (?)
- Vectors (Region, Outline, Advanced Outline, Solid Color, Rectangle, Star, Circle, etc.):
  - without anti-aliasing
  - with approximated triangulation (?)
  - with Feather Type parameter forced to Box Blur
- Blur, Bevel, Shade:
  - forced Box Blur method

**Comment by morevnaproject** [comment]
Updated description.

**Comment by blackwarthog** [comment]
Done
