### ISSUE TITLE
Pressing "Delete" key should remove selected element

### ISSUE THREAD

**Issue by alexandervrs** [synfig/synfig#413]
**Synfig version & platform**:
1.3.4 / Windows 10 64bit

**Issue description**:
Pressing the Delete key with an object selected does not seem to do anything. Usually you'd want the Delete key to quick remove any selected keyframes, layers, vertices etc.

**Comment by rodolforg** [comment]
@ice0  is this fixed?

**Comment by ice0** [comment]
Yes, now it works as planned.
