### ISSUE TITLE
Pressing "Space" key should Play/Pause the animation preview

### ISSUE THREAD

**Issue by alexandervrs** [synfig/synfig#414]
**Synfig version & platform**:
1.3.4 / Windows 10 64bit

**Issue description**:
Pressing the "Space" key while a frame is selected on the timeline should play/pause the animation. This behavior is seen in Flash and is very useful for quick preview using the keyboard

**Comment by morevnaproject** [comment]
Some people ask to use Space for canvas pan/rotate operations.

**Comment by alexandervrs** [comment]
I think it should be an editable Preference, some programs use Space to quickly pause/play while others use Enter.

**Comment by morevnaproject** [comment]
Yes, editing shortcuts in preferences would be nice. Requested in #422.
At the moment you can check a file called "accelrc" in the configuration directory of Synfig.

Though, you might hit some issues related with current system of handling shortcuts - #303 #257 #403.

**Comment by rodolforg** [comment]
@Keyikedalube  is this done?

**Comment by Keyikedalube** [comment]
I didn't notice this issue existed.

Yes, this requested feature is already implemented in #1776 :)
