### ISSUE TITLE
Clicking on the timeline while the animation is playing should stop the playback

### ISSUE THREAD

**Issue by alexandervrs** [synfig/synfig#415]
**Synfig version & platform**:
1.3.4 / Windows 10 64bit

**Issue description**:
Clicking on the timeline while the animation is playing should stop the playback and show the clicked frame. This is common behavior in Flash, as this gesture means that you want the playback to stop and edit that particular frame. Currently in Synfig it does nothing.

**Comment by morevnaproject** [comment]
The fix is merged now, will be shipped with version 1.3.11.
