### ISSUE TITLE
Warp layer not working correctly (Synfig 1.3.3 ----> 1.3.4)

### ISSUE THREAD

**Issue by boubouh** [synfig/synfig#418]
**Synfig version & platform**:
Synfig 1.3.3 and 1.3.4 (Linux and Windows)

**Issue description**:
Warp layer not working correctly in Synfig 1.3.3 and 1.3.4...as you can see in the picture:

![bug](https://user-images.githubusercontent.com/5199504/30168957-d99f6a76-93e2-11e7-9831-c678902e570f.png)

**# i make a video for explaining this** : https://youtu.be/meeCfkcfRWA

**Comment by boubouh** [comment]
**Has anyone run into the same problem ??**

**Comment by morevnaproject** [comment]
Yes I can reproduce this problem. Thank you for reporting!

**Comment by rodolforg** [comment]
I try it and can reproduce also.
However, changing "Horizon" parameter can make it appear again.

**Comment by morevnaproject** [comment]
Can anyone check if this still a problem with the latest commit? - 6b433d2503ed81bd6577c17748d2ae59ce0573c6

**Comment by morevnaproject** [comment]
Fixed in latest master
![screenshot_003](https://user-images.githubusercontent.com/332868/75607006-50753e80-5b25-11ea-91fb-d416582bf00c.png)
