### ISSUE TITLE
Can't render except in png

### ISSUE THREAD

**Issue by alienCY** [synfig/synfig#419]
**synfigstudio-1.2.0-64bit-r2 in a Debian based linux distro**:

**Can't render the video**:
So I've just started learning how to use synfig today. I'm not good at it yet but I got the basics down. When it comes to rendering I can only render .png pictures of each frame. When target is "Auto" and I change the ending from .png to .avi or .mpg it says that it renders the video but nothing is created in the output file.

**Comment by alienCY** [comment]
After downloading the developer build it's fixed! No more stable >.<

**Comment by morevnaproject** [comment]
Yes, this fix landed to our dev builds just recently. ^__^ Now it is also included in stable! - https://morevnaproject.org/2017/09/11/synfig-1-2-1-released/
