### ISSUE TITLE
Feature request: Shortcut editing in preferences

### ISSUE THREAD

**Issue by lehtis** [synfig/synfig#422]
**Synfig version & platform**: Synfig 1.2.0 Win10
(we're more likely to help if you're using latest development builds)

**Issue description**:
Feature request:
Chance to edit shortcuts in preferences. Also which mouse/pen buttons used.

**Comment by morevnaproject** [comment]
The fix is shipped in Synfig Studio version 1.4.2 - https://www.synfig.org/2021/07/29/synfig-studio-1-4-2-released/
