### ISSUE TITLE
 Synfig 1.2.1 AppImage isn't working.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#429]
**Synfig version & platform**:
Synfig Studio 1.2.1 Linux AppImage (64-bit)
Manjaro Linux KDE Edition (17.0.4)
**Issue description**:
[Appimage doesn't work.  Video.](https://www.dropbox.com/s/px3j8904461z0n4/Synfigbugappimage.mp4?dl=0)

**Comment by morevnaproject** [comment]
Hello! I have noticed from the video that you are trying to start appimage version **1.2.0**. Can you please check version 1.2.1?

**Comment by ebarranco** [comment]
You right! @morevnaproject I don't even notice that both are in the same page. Wrong version. Sorry about that.
