### ISSUE TITLE
Make it possible to create new workspace and save it .

### ISSUE THREAD

**Issue by boubouh** [synfig/synfig#430]
**Synfig version & platform**:
Linux, windows and Mac

**Issue description**:
Hi Dev
please make it possible to **create new workspace and save it** in **Synfig**.... just like **Blender** or **Opentoonz**.

![fr](https://user-images.githubusercontent.com/5199504/30297992-af476cee-9741-11e7-91f3-0fc9be0a56c0.png)

**Comment by rodolforg** [comment]
Should this issue be closed due to #916 ?

**Comment by morevnaproject** [comment]
The feature now shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
