### ISSUE TITLE
Crash when entering a round amount where "linked to spline" is looped

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#432]
**Synfig version & platform**:
linux 1.3.4

**Issue description**:
When something is "linked to spline" and "loop" is set, manually entering a round value for "amount" will crash synfig.

**Comment by morevnaproject** [comment]
Confirmed. Any round value other than 0.0 and 1.0 is crashing Synfig. Sample file attached.
[link-to-spline-loop.sifz.zip](https://github.com/synfig/synfig/files/1352757/link-to-spline-loop.sifz.zip)

**Comment by ice0** [comment]
Hi! I can't reproduce this bug on latest version (both windows and linux builds checked). Can you check it again? I try to set amount to 2 and 4 and 2.0 and 3 on every layer and nothing happens.
