### ISSUE TITLE
freeze on non root user

### ISSUE THREAD

**Issue by freemandune** [synfig/synfig#435]
**Synfig version & platform**:
Version 1.21 - Ubuntu 16.04

**Issue description**:
The program freezes after a few minutes of using it, opening it from console appears the message "error: synfig :: save_canvas (): Unable to open file for write", with root user does not happen

**Comment by morevnaproject** [comment]
Hello! Can you please check if your user have sufficient write permissions for "/tmp" directory?

**Comment by freemandune** [comment]
root owner but full /tmp permissions for any user

**Comment by morevnaproject** [comment]
Thank you for checking. We have made modifications for saving operations in current development tree. Can I ask you to build current source code to test if the issue still here?

**Comment by morevnaproject** [comment]
Ugh, wait. There is an issue with file saving in current source code - #441. Please wait until we fix it.

**Comment by ice0** [comment]
#441 is fixed, so i close this too.
