### ISSUE TITLE
Cannot disconnect transformations

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#438]
**Synfig version & platform**:
linux 1.3.4

**Issue description**:
Once linked, there is no way(?) to disconnect the transformations of two group layers.

**Comment by caryoscelus** [comment]
I figure it happens because of poorly implemented protection against making uneditable transformation value: disconnect doesn't work at all when it should disconnect to a fresh composite node, if that user protection is even that important.

**Comment by caryoscelus** [comment]
Well, i guess lack of documentation makes it very easy to make a mistake like using ValueNodeReplace on https://github.com/synfig/synfig/blob/master/synfig-studio/src/synfigapp/actions/valuedescdisconnect.cpp#L175

**Comment by caryoscelus** [comment]
Workaround: use "convert->composite" to disconnect.

**Comment by morevnaproject** [comment]
@caryoscelus Thank you very much for taking care about this! ^__^
