### ISSUE TITLE
Unable to save new file (current master)

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#441]
Steps to reproduce:
1. Create new file.
2. Create a circle.
3. Save it. -> no file saved.

Happens in current master branch.

**Comment by bobbybee** [comment]
I can confirm (I lost work due to this and promptly switched back to stable).

**Comment by zeograd** [comment]
If it can help, it seems like this bug was introduced in https://github.com/synfig/synfig/commit/0dde7211f277353f80d6cfc99ebca5d4fd056989 (via bisecting)

**Comment by blackwarthog** [comment]
I've fixed this bug. Apologies for long delay.
