### ISSUE TITLE
Synfig Studios Not Downloading

### ISSUE THREAD

**Issue by Acting2** [synfig/synfig#445]
**Synfig version & platform**:
Mac

**Issue description**:
Hi. I am trying to download Synfig Studios to my computer. I get all the way through the download. It says Verifying and then the loading bar will not move at all. I do not know what is wrong with it. If you guys could help that would be great!
-Acting2

**Comment by morevnaproject** [comment]
Hello! Please take a look at the instructions here - http://support.morevnaproject.org/topics/417-osx-version-not-starts/
