### ISSUE TITLE
Mouse wheel should scroll on time track panel

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#446]
**Synfig version & platform**:
linux 1.3.4

**Issue description**:
Mouse wheel seems to scroll everywhere except on the time track panel.

**Comment by caryoscelus** [comment]
It scrolls for me. Vertically, that is; when there is something to scroll (i.e. a layer with enough parameters is selected). I don't have horizontal scrolling enabled, but since you're talking about wheel it's probably not what your issue is about.

**Comment by zozorg** [comment]
Wheel does scroll if I point at the scroll bar ^^
I have KDE desktop, it doesn't scroll no matter what GTK_THEME I use.

**Comment by zozorg** [comment]
I'm willing to put some small bounty ( $10 ) on this one, but I'm not sure if the fix is on your side or mine.
- If I put the mouse over the parameter panel, and use the wheel, the parameter and time track panel scroll simultaneously.
- if I put the mouse over the time track panel, the wheel has no effect.

Can you confirm it's NOT the behavior you get?

**Comment by caryoscelus** [comment]
>Can you confirm it's NOT the behavior you get?

Yeah, see attached video: wheel scroll vertically whenever there's something to scroll (and zooms horizontally when cursor is placed on time ruler).

![scroll](https://user-images.githubusercontent.com/1758893/31965588-7d3f73b8-b910-11e7-9445-f5d31c80d1c5.gif)

**Comment by zozorg** [comment]
Thanks.
I get the correct behavior with version 1.0.2 ; not with 1.3.4 nor 1.2.1
Does that give any clue?

**Comment by caryoscelus** [comment]
Are you using binaries? If so, it could be Gtk version issue.

**Comment by morevnaproject** [comment]
@caryoscelus thank you for the hint!

I can confirm the following (for Linux platform):
- When compiled from source (with Gtk 3.18.9) the scroll works as expected.
- When using binary AppImage (it uses Gtk 3.14) the scroll not works.

@blackwarthog Let's try to bump Gtk version for AppImage and see what happens. ^__^

**Comment by zozorg** [comment]
Posted [https://www.bountysource.com/issues/50265000-mouse-wheel-should-scroll-on-time-track-panel]($10) as promised

**Comment by morevnaproject** [comment]
Thank you for backing this issue! Sorry it takes longer than I expected. There are build errors that I have to resolve.

**Comment by morevnaproject** [comment]
@zozorg Please check this testing package - https://dev.icystar.com/downloads/SynfigStudio-1.3.4-testing-17.11.12-linux64-38c38.appimage

Note: The final fix is made by @blackwarthog.

**Comment by zozorg** [comment]
Works for me! Thanks!

**Comment by morevnaproject** [comment]
Will be shipped with version 1.3.5.
