### ISSUE TITLE
Color wheel stuck to red when saturation=0

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#452]
**Synfig version & platform**:
linux 1.3.4

**Issue description**:
When moving the cursor of the color wheel to the grey area ( saturation=0 ), it automatically locks itself to hue=0 ( leaving you mouse hanging over a random color ), and it is not possible to move the hue cursor as long as saturation=0, so you have to slightly move the cursor before you select the hue you need.
This doesn't prevent you from selecting anything, but it can get a bit annoying.

**Comment by caryoscelus** [comment]
Yeah, i remember that one. Pretty annoying.

**Comment by zozorg** [comment]
Posted a [$15 bounty](https://www.bountysource.com/issues/51060128-color-wheel-stuck-to-red-when-saturation-0)

**Comment by caryoscelus** [comment]
Thx for the bounty, i'll look into it. Shouldn't be especially hard to fix.

Btw, i'm not sure if bountysource works atm (see https://github.com/bountysource/core/issues/1147)

**Comment by morevnaproject** [comment]
Thank you for the fix, works like a charm! Merged now.

P.S. Yes, I also have problems authorizing into bountysource. :-/

**Comment by caryoscelus** [comment]
NP :)

> P.S. Yes, I also have problems authorizing into bountysource. :-/

It actually works for me, if i login directly with email/password (i.e. not via github). I don't recall how i registered there in the first place, though.

**Comment by zozorg** [comment]
Bounty awarded! Thanks!
