### ISSUE TITLE
Time loop layer "local time" doesn't work

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#479]
This is apparently an old bug
http://synfig.org/forums/viewtopic.php?f=12&t=3526#p14986

**Comment by morevnaproject** [comment]
Added to our queue.

**Comment by flicker-free** [comment]
I think there may be a problem around line 211 as well. 

please note, additional minor spelling error in line 151 "length" spelt incorrectly, 

the issue with this bug is that the loop begins looping at 0f rather than t the time defined as the local time. 

most annoying.

**Comment by morevnaproject** [comment]
Updated link to forum thread - https://forums.synfig.org/t/time-loop-can-it-do-this/1906#p14986
