### ISSUE TITLE
Synfig's Interface "Hides" Mouse Cursor or Taskbar in Certain Conditions

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#487]
**Synfig version & platform**:
Dev Version 1.3.5 in Win 10 64-bit
and 1.3.6 as well
I'm using two-screen stretched display mode, just in case if that matters ._.

**Issue description**:
Some certain actions makes the mouse cursor invisible, like when i do these : 
1. Dragging Synfig's changeable interface (Dockers, layer content, sets, tabs, etc.)

![uibug](https://user-images.githubusercontent.com/25135159/34908348-8782c43e-f8c0-11e7-9e0c-e4f5d4682606.png)

the cursor turns invisible, but it still works fine 
for example, the green outlines for docker's placement got highlighted in the process
oh, and the docker's icon shows up at the top left of my screen

here's another evidence of that top left icon when dragging a group layer
![snip_20180418194325](https://user-images.githubusercontent.com/25135159/38932691-2c03639a-4341-11e8-9771-df02289dedc8.jpg)

2. Clicking the Color Select tool IN HSV Color Wheel

![uibug2](https://user-images.githubusercontent.com/25135159/34908409-eb0db9c2-f8c1-11e7-8954-c1611c431b06.png)

The Cursor is also gone, but still works. This indicated by a color change after clicking somewhere
The Eyedrop Tool from toolbox didn't get affected by this issue though, it works fine

Although the cursor can be seen if moved out of synfig's window

3. Another thing is i'm using Auto Hide as the taskbar setting. And when i maximized Synfig's window, i can't call it out, this ONLY happens in Maximized Window Mode  ._.

**Comment by FadhilKwan** [comment]
@ice0 this might also GUI related...

**Comment by morevnaproject** [comment]
> Dragging Synfig's changeable interface (Dockers)

If we can find which cursor is missing, then we will be able to fix this issue in the same way as done here - https://github.com/synfig/synfig/issues/536#issuecomment-615878955

@rodolforg @ice0 Any ideas how to find the name of missing cursor? ^__^

**Comment by rodolforg** [comment]
I think it's fixed - at least for 1.3.13 : the "dnd-" cursors are there in the Windows package.

**Comment by rodolforg** [comment]
@FadhilKwan could you check if this issue is solved in latest development version (1.3.13)?

**Comment by FadhilKwan** [comment]
> @FadhilKwan could you check if this issue is solved in latest development version (1.3.13)?

Hi @rodolforg . First of all, i'm really sorry for replying this late (almost like a month; oof). I didn't look through my mailboxes properly, and github didn't send any notification to my account dashboard. ._.v

Anyway, i checked and tried to replicate the bugs on v1.3.13. And it seems that the disappearing cursor while dragging Dockers bug (no. 1) has been resolved!
Oh yeah, also the part where synfig's window blocking the bottom part of my screen and not letting me to call my auto hide taskbar (no.3) also got resolved as well, which is really nice! :D

Some of the others are still persist, though. Such as missing color dropper cursor (no. 2).
Another one that also still persists is in which dragged items would show up on the top left of the screen (right at the end no. 1). But honestly, i think that one is more of a cosmetic bug since it doesn't break anything, which is fine by me.

That's all that i can find so far. Oh yeah, i'm using the portable version, just in case if that does affect anything in particular.
Once again, i'm really sorry for the late response, and thank you very much for the bug fixing! ^-^

**Comment by rodolforg** [comment]
Version 1.3.14 will solve the missing cursor for eyedropper.

That dragging oeoblem is too weird, but I can't reproduce because I don't use OSX.
It seems a GTK issue anyway (but the missing cursor was too...)

**Comment by FadhilKwan** [comment]
> Version 1.3.14 will solve the missing cursor for eyedropper.

Yup, just found it a few minutes later on #536 and tried it right off the bat. And i'm happy to say that i can confirm that as well.

> That dragging oeoblem is too weird, but I can't reproduce because I don't use Windows.
> It seems a GTK issue anyway (but the missing cursor was too...)

hmmm~, i'm not entirely sure how it's still there either. ._.

But now that the major bugs on the list has been solved, i think i can close this issue now.
Or maybe should i just wait until all of them gets fixed?
