### ISSUE TITLE
Cannot download the dmg file setup

### ISSUE THREAD

**Issue by vivbravo** [synfig/synfig#488]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:

I came across this app as a suggestion that looked promising to what I am currently seeking.  I paid using my paypal account to download this app for my mac book pro, but the dmg file never finishes to install.

Need help.

Thanks,
Vivek

**Comment by morevnaproject** [comment]
Hello Vivek!

Apologies for delayed reply.
Please double-click on downloaded DMG file - it will show "Verification in progress" window. You can skip verification process.

Also, please make sure to check the instructions here - http://morevnaproject.userecho.com/forums/15-synfig/topics/417-osx-version-not-starts/
