### ISSUE TITLE
Second download of Synfig won't tutorial files

### ISSUE THREAD

**Issue by iowaplayer** [synfig/synfig#490]
Synfig Version: 1.2.1
Operating System: Window 7, 64 bit

i downloaded synfig 1.2.1 and discovered that any open, save or import operation resulted in an error where i would have to click the cancel button between 15 and 20 times before the program would allow me to continue.

after trying everything i could think of i decided to try a development version of synfig to see if it worked any better.  it didn't.  if anything, it was worse.

so then i tried downloading 1.2.1 again and running the install program.   the install program uninstalled the previous (development) version and reinstalled 1.2.1.  i also deleted the tutorial files including the .png files.

now when i try to open one of the tutorial files (boy.png or background.png) synfig gives the following error:

Unable to load “C”\Users\Karen\Desktop\SYNFIG TUTORIALS\How_to_create_animation_in_Synfig_Studio\workshop\first-animation\boy.png”

Document not well-formed.
Line 1, column 1 (fatal):
Extra content at the end of the document

i was able to load and use boy.png and background.png last night with the first download of 1.2.1, but i can't now.
what the hell is going on with this software?  i had hopes of using this thing!

karen

**Comment by morevnaproject** [comment]
For loading png files please use "File" - "Import" command (do not use "File" - "Open").

Отправлено с iPhone

**Comment by iowaplayer** [comment]
oh DUH!  i haven't made that kind of mistake in years!  my most abject apologies!
i would still like to find out how to fix the file open, save and import "no disk in drive" problem.  it really makes using this thing a nuisance.

btw, as i go through the tutorials i find i really enjoy using synfig.   cool proggie! :)

**Comment by morevnaproject** [comment]
I am happy you  like it! I am closing this then. ^__^
