### ISSUE TITLE
[Question] Is there a up-to-date Roadmap?

### ISSUE THREAD

**Issue by stothew** [synfig/synfig#497]
Synfig is by far the best open source 2D Animation program! Keep up good work!
but is there any up-to-date Roadmap?
I was on forum and on wiki but the information seems to be pretty old. 

Would be really interested in it.

Thanks.

**Comment by caryoscelus** [comment]
On Thu, 22 Feb 2018 09:08:23 -0800
stothew <notifications@github.com> wrote:

> Synfig is by far the best open sorce 2D Animation program! Keep up
> good work! but is there any up-to-date Roadmap?
> I was on forum and on wiki but the information seems to be pretty
> old. 
> 
> Would be really interested in it.
> 
> Thanks.
> 
> 

Last time i checked there were no developers willing to put efforts into
strategic Synfig development. Personally, after working with its
codebase for a while i found it easier to write entire thing from
scratch rather than patching Synfig. Some others choose to use/develop
OTZ or perhaps Krita.

**Comment by morevnaproject** [comment]
Hello @stothew!

Thank you for the kind words!

My name is Konstantin Dmitriev, I am maintainer of Synfig.
We have one hired developer (@blackwarthog) who is contributing to Synfig on regular basis. Also, in March 2018 (which is almost here) we are going to hire a second developer to address most critical issues.

You can see our current roadmap here - https://github.com/synfig/synfig/projects
The information on wiki/forums is outdated, yes.

**Comment by morevnaproject** [comment]
Public announcement - https://morevnaproject.org/2018/02/27/new-developer-will-join-synfig-development-since-march-2018/

**Comment by elthea** [comment]
Hi guys, I also think you are doing great job with synfig and it is really great that such open source project exists. Unfortunately I can't programme in c++ - only java, javascript, php, perl etc. But I'm happy to help you in any way, in my free time.

Best regards:)

**Comment by Keyikedalube** [comment]
@libreartist linked the answer to this above. I'm closing this since I feel the question has been answered.
