### ISSUE TITLE
Google summer of code 2019?

### ISSUE THREAD

**Issue by WPFilmmaker** [synfig/synfig#499]
The deadline for this year was January...Knowing that Morevna Project is always looking to get better financially wise and improve the code, why not applying to Gsoc next year? Has this ever been considered?It would be beneficial for Synfig and reduce the costs for the project (at the least for the duration of the event)

**Comment by morevnaproject** [comment]
I have carefully studied this opportunity back in 2012. There are several reasons why we not apply. One (most important) of them is that in order to get accepted we MUST have at least one student on our radar, who are:  
1)  proven to be committed to the project, 
2) proven to deliver results within 3 months

This is something that we do not have now.

**Comment by WPFilmmaker** [comment]
@morevnaproject Thanks for the answer! Would it be feasible looking for one student for next gsoc? There is a year for attracting new students. I read the post about the new developer. I wish Moverna Project all the luck!

**Comment by morevnaproject** [comment]
Thank you for the kind wishes. I am regularly doing some efforts on attracting students, but no luck so far. In any case, our project is always open for new contributors. ^__^

**Comment by reSHARMA** [comment]
> I have carefully studied this opportunity back in 2012. There are several reasons why we not apply. One (most important) of them is that in order to get accepted we MUST have at least one student on our radar, who are:
> 
> 1. proven to be committed to the project,
> 2. proven to deliver results within 3 months
> 
> This is something that we do not have now.

Are you still looking for someone :) I've just completed my GSoC'18 project with LLVM https://summerofcode.withgoogle.com/projects/#6751970149269504

**Comment by raniaamina** [comment]
Pada tanggal Kam, 20 Sep 2018 01.03, Reshabh Sharma <
notifications@github.com> menulis:

**Comment by morevnaproject** [comment]
Hello @reSHARMA! Thank you fro the proposal! Yes, we are still interested. Do you have any particular idea where you want to apply your efforts? ^__^

**Comment by reSHARMA** [comment]
@morevnaproject Sounds like a great idea, I'm in. We can use the same for automatic testing of our deb binaries at ci.debian.net.

**Comment by morevnaproject** [comment]
@reSHARMA Awesome! I suggest to continue further discussion in separate thread - https://github.com/synfig/synfig/issues/634

**Comment by shubhsherl** [comment]
@morevnaproject , I have prior experience in App development and I am currently developing an app as my internship project(in react-native). But I am open to other areas as well, to learn and apply. Let me know if there is any project open to work on.

**Comment by morevnaproject** [comment]
@shubhsherl I see. ^__^ Do you have any experience with C++?

**Comment by shubhsherl** [comment]
@morevnaproject C++ was my first language, and I am comfortable in it. I have a school project in C++03, if it counts ;P

**Comment by shubhsherl** [comment]
@morevnaproject Do let me know if there is anything I can try my hands on.

**Comment by morevnaproject** [comment]
@shubhsherl  Oh, my apologies - I've got distracted by other tasks and didn't responded in time. ^__^"

We have a list of "good first issues", so you can choose which one you would like to start with - https://github.com/synfig/synfig/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by reSHARMA** [comment]
I think we should start preparation from our side for gsoc 2019 org application. After some random browsing I see the "idea page" as a great first step.

"Keep in mind that this page is often the first view of your organization by Google and potential student applicants." [1]

I think we can have the idea page on synfig wiki, and meanwhile can ask for potential mentors and projects on github or synfig forum (or both).

"As a first year organization you will probably receive fewer than 3 students" [2]

We should atleast have 3-4 projects with potential mentors listed.

1 https://google.github.io/gsocguides/mentor/making-your-ideas-page
2 https://google.github.io/gsocguides/mentor/notes-for-first-year-organizations

**Comment by morevnaproject** [comment]
Yes, it's time for preparations!

As we planning to go away from MediaWiki in favor to Sphinx/ReadTheDocs, I suggest to include Ideas Page into developer's documentation - https://synfig-docs-dev.readthedocs.io/en/latest/index.html

Editable here - https://github.com/synfig/synfig-docs-dev

**Comment by reSHARMA** [comment]
Track the update and suggest changes for synfig project ideas page here (https://github.com/synfig/synfig-docs-dev/pull/3) and for gsoc'19 application draft [here](https://github.com/synfig/synfig-docs-dev/blob/8aedf831230958b8fce0f554ec189ed321c251a0/docs/common/application.md)!

**Comment by ankit-kumar-dwivedi** [comment]
I would like to be part of gsoc19 as a student at synfig :)
what are the prerequisites?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi I am happy to see your interest! We need some code-related contribution from you before GSoC starts. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> @ankit-kumar-dwivedi I am happy to see your interest! We need some code-related contribution from you before GSoC starts. ^__^

thanks @morevnaproject. I guess solving few code related issues will do the job !

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Yes, exactly! We have a list of good simple issues to start with - https://github.com/synfig/synfig/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
(please ignore pinned issue, though). ^__^

**Comment by morevnaproject** [comment]
Registration for GSoC now open for organizations - https://summerofcode.withgoogle.com/
We're starting to work on application.

**Comment by morevnaproject** [comment]
Okay, I have registered an organization, now working on Organization Application and Organization Profile. BTW, every organization must have at least 2 and at most 5 Organization Administrators.
@ice0, I propose you to become second administrator. Opinions?

**Comment by morevnaproject** [comment]
While I am in the process of preparing application, I suggest to start thinking on possible project ideas. ^__^

**Comment by ice0** [comment]
Hi guys! Sure i am in.

Project ideas:

**Infrastructure**
- complete our CI build chain by adding Windows build (i suggest MSYS2 on Microsoft platform);
- add static code checks and possible code coverage. I suggest https://scan.coverity.com/ and PVS-Studio (as for now PVS-Studio is free for open-source projects);
- move to CMake build system (most of tools prefer CMake's compile_commands.json for work);
- also we can add code-style checks for newly committed code;

**Code improvements**
- Move ETL to Synfig Core;
- Remove unused libraries;

**Big improvements**
- Bones;

**Comment by ThobyV** [comment]
Hi Everyone, I'm also an aspiring GSOC 19 student and my area of specialization is UX Engineering.

While I really love the current interface and experience of the current Synfig version, I feel as if a lot of porweful features are hidden from the user and makes working in Synfig a difficulty for beginners.

I do not know how difficult the task is to propose a work with a team on the UX of some parts of Synfig most especially the Timeline. But it's a task I don't even need GSOC to wish to accomplish.

What are the reasons for the current Interface?

**Comment by morevnaproject** [comment]
Hello @ThobyV! Happy to see your interest. ^__^

Many UI decisions came from original developers, who created Synfig and opensourced it back in 2006. After that, many improvements were made by community contributors. A big work done by Yu Chen (@jcome), who has made a lot of good rework on UI and also brainstormed other improvements (you might want to take a look at topics here - https://forums.synfig.org/search?q=UI%20Redesign%20-%20).

Of course, Synfig's UI is still far from perfect and contributions are welcome. 

I suggest to open new issue here (on GitHub) to start discussion on possible improvements.

**Comment by ThobyV** [comment]
Thank you so Much @morevnaproject for your time replying. 

I will make sure to open a seperate discussion as soon as I have enough insights on this Topic. I look towards creating some revolutionary user experience with the team for this awesome project.

**Comment by morevnaproject** [comment]
> May I ask what Tool/Platform the Synfig UI Is written in?

It is written in C++ with GTK3 libraries as GUI toolkit.

Currently all UI layout is written in plain code. It would be nice to utilize some UI builder (Glade3). In this case modifications to UI will be very simple.

**Comment by morevnaproject** [comment]
P.S. @ThobyV Can you please drop me a mail via https://www.synfig.org/contact/? ^__^

**Comment by ThobyV** [comment]
@Morevnaproject I am really sorry for the delay! I will be communicating more frequnetly and timely from now. I have sent an email to the Address you shared.

Also, I woull love to ask if the UI builder is more flexible to the users and developers alike if it is implemented?

**Comment by ThobyV** [comment]
@morevnaproject I am really sorry for the delay! I will be communicating more frequnetly and timely from now. I have sent an email to the Address you shared.

**Comment by morevnaproject** [comment]
@ThobyV Got your letter and mailed a response to you. Please check your mailbox. ^__^

**Comment by morevnaproject** [comment]
Dear friends, I have finalized our application test - https://synfig-docs-dev.readthedocs.io/en/latest/gsoc/2019/application.html
Your comments are welcome (but remember that the deadline is tomorrow ^__^).

**Comment by WPFilmmaker** [comment]
@morevnaproject looks good to me! Finger crossed for you! And please let us know if you get accepted <3

**Comment by morevnaproject** [comment]
@WPFilmmaker Thank you for the kind words! Even if we will not get accepted, we will keep moving. The project gets a good traction lately, so good times ahead! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> The project gets a good traction lately, so good times ahead! ^__^

Yes @morevnaproject synfig is getting famous :smiley: . 
PS: I am planning to conduct a workshop about synfig in my college.

**Comment by morevnaproject** [comment]
> I see there is no mention about the synfig forum. Can't that be used as a Communication medium for gsoc?

I just haven't found a suitable place to mention that in application form. Also, currently all of our development team is hanging out here, at GitHub.

Of course, ideally it would be nice to get all devs registered on the forum and ask everyone to subscribe for "Development" category (https://forums.synfig.org/c/development). This way it can act as mailing list for us (with a cool emojis and likes). And then I can mention it in "Mailing List" section.

@blackwarthog @ice0  @reSHARMA @ankit-kumar-dwivedi @ThaFireDragonOfDeath @ThobyV  what do you think about this idea?

**Comment by morevnaproject** [comment]
(I am not pinging @BobSynfig, since he is already there ^__^).

**Comment by blackwarthog** [comment]
I dislike google and github and discourse.

But summer is good, and code and mailing list

**Comment by morevnaproject** [comment]
@blackwarthog Calm down. ^__^ Since you are already on GitHub, I suppose you don't mind Discourse and Google. ^__^

**Comment by blackwarthog** [comment]
![OK](https://i.kym-cdn.com/entries/icons/original/000/003/617/OkayGuy.jpg)

**Comment by ankit-kumar-dwivedi** [comment]
Congratualations 

:tada:
--




![](https://i.ibb.co/N7tSCMh/Capture.png)

 @morevnaproject @WPFilmmaker and everyone at synfig :100: 
**Synfig is now a mentoring Organization at GSOC'19**

**Comment by Jose-Moreno** [comment]
Congrats guys! Hopefully this will push Synfig development and recognition further! Keep up the great work!

**Comment by morevnaproject** [comment]
Congratulations to everyone! 

In the meantime, I have started to write documentation about Synfig's code structure, which will help newcomers to understand how everything works. By this moment I have finished documenting "synfig-core" - https://synfig-docs-dev.readthedocs.io/en/latest/common/structure.html

**Comment by WPFilmmaker** [comment]
@morevnaproject and all, congratulations! What's the next step? By when do you have to make a list of mentored students?

**Comment by reSHARMA** [comment]
@WPFilmmaker interested students will submit their application by 9th April, and you will have a quite a good time to decide :)

Congratulations to all, I remember after last gsoc when I was bored, I googled "gsoc 2019" and got the link to this thread. It's been half a year and I'm elated that we got this issue right <3. Though I've not contributed much in synfig and just been in conversation with Konstantin but this place feels like home.

Thank you and congratulations again!

**Comment by AnishGG** [comment]
[Suggestion]
Hello everyone,
The Student Application Period is over and it marks the beginning of Application Review Period. This will take approximately a month. 
It would be nice if someone could share the statistics of the proposals. 😃 
I am attaching a screenshot as an example of how an organization did it this time: 
![statistics](https://user-images.githubusercontent.com/30872212/55890656-bd5fad00-5bd0-11e9-8482-200028653929.png)
@morevnaproject @ice0 attaching you guys here being the org admins. 🙂

**Comment by morevnaproject** [comment]
Hi @AnishGG!
Just a quick info: we've got 14 proposals in total. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Thank you so much @morevnaproject for this opportunity. I am overwhelmed 
and congratulations to @AnishGG 🎉

**Comment by AnishGG** [comment]
Congratulations to you too @ankit-kumar-dwivedi!! And thank you for this opportunity @morevnaproject!

**Comment by morevnaproject** [comment]
Congratulations to @ankit-kumar-dwivedi  and @AnishGG! Welcome to the project. ^__^

**Comment by morevnaproject** [comment]
So, the coding period is starting next week!

@ankit-kumar-dwivedi @AnishGG every week I will need a short weekly summary from you.

It shouldn't be a long report, just a quick summary answering those questions:
*  How was the last week? What did you accomplish?
* What is the top thing slowing you down?
* What do you want to have done by the end of next week?

I can see @ankit-kumar-dwivedi is already started at https://forums.synfig.org/t/gsoc19-vectorization-of-bitmaps/9815/2

@AnishGG you can post reports at https://github.com/synfig/synfig/pull/756, or on forums (choose which is more convenient to you).

Thanks to all for your efforts! ^__^

**Comment by AnishGG** [comment]
> @ankit-kumar-dwivedi @AnishGG every week I will need a short weekly summary from you.

Will start working on the report on the Synfig forums it selves
Thank you!

**Comment by morevnaproject** [comment]
So, GSoC 2019 is over. Congratulations and much thanks to everyone who participated to make this happen! ^__^
