### ISSUE TITLE
Allow to edit keyframes in Graphs Panel

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#505]
**Synfig version & platform**:
All versions.

**Issue description**:
Add keyframes editing widget, same as the one in TimeTrack panel.

Time Track Panel:
![screenshot_014](https://user-images.githubusercontent.com/332868/37865593-3edfe81a-2fb1-11e8-8bbe-2c5fcfeeafef.png)

Graphs Panel:
![screenshot_015](https://user-images.githubusercontent.com/332868/37865594-456d8b6a-2fb1-11e8-9984-b398a419d78f.png)

**Comment by blackwarthog** [comment]
close?

**Comment by morevnaproject** [comment]
Shipped with version 1.3.9 - https://www.synfig.org/2018/06/25/synfig-studio-1-3-9-released/
