### ISSUE TITLE
RTL support for Text Layer

### ISSUE THREAD

**Issue by libreartist** [synfig/synfig#507]
**Synfig version & platform**: 1.31, AppImage version on Debian(Sid)

**Issue description**: I had trouble implementing Arabic titles for one of my friends while doing a animated promotional clip. It was stalled, just because I know only Synfig for animation and Synfig didn't well with bi-directional language such as Arabic. (I could have done it with GIMP and imported it as static raster layer, but I wanted to morph every single letter transformed into a person :-()  Is there a possibility for implementing Complex Text Layout with the use of library called HarfBuzz? (I'm sorry if it has been already implemented) If it has been done already, could you tell me how to do it?

**Comment by Fahad-Alsaidi** [comment]
As I understand from the code, the freetype layer uses pango which is using HarfBuzz and does RTL stuff.

**Comment by Fahad-Alsaidi** [comment]
@libreartist Why do you close this? Even freetype layer uses pango but RTL support is broken and need to be fixed.

**Comment by morevnaproject** [comment]
I am renaming and re-opening this bug, as RTL is demanded feature.

**Comment by morevnaproject** [comment]
Linking this to #1621
