### ISSUE TITLE
Automatically update image if its source file is changed

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#513]
**Synfig version & platform**:
All versions.

**Issue description**:

Suppose you have image A.png imported into Synfig file.

If file A.png is changed (using some external image editor), then the old version is still displayed in Synfig, until you close and re-open animation file.

It would be nice to monitor changes in imported file and re-load it automatically.

**Comment by ice0** [comment]
Should Synfig ask to reload file? Or do that silently?

**Comment by morevnaproject** [comment]
Silently (if image is not changed inside of Synfig).

**Comment by morevnaproject** [comment]
Shipped with version 1.3.9 - https://www.synfig.org/2018/06/25/synfig-studio-1-3-9-released/

**Comment by alancnet** [comment]
This doesn't work anymore (v1.4.5)

**Comment by ice0** [comment]
> This doesn't work anymore (v1.4.5)

Hi! Which OS are you using? 
If it’s Linux, are you using a snap, flatpak, or deb package?

**Comment by rodolforg** [comment]
It works for me Linux AppImage 1.4.5 and 1.5.3

**Comment by ice0** [comment]
> It works for me Linux AppImage 1.4.5 and 1.5.3

Maybe the file was opened from a network drive or something? If so, I think the file monitoring might not have worked.
