### ISSUE TITLE
Make this Repository Easier to be Searched in Github

### ISSUE THREAD

**Issue by libreartist** [synfig/synfig#517]
**Synfig version & platform**: 1.31, Debian (Sid)

**Issue description**: As I was searching through Github, I couldn't find this repository in search results, searched with keywords like "C++, 2D, Animation". All I could see in the results were other popular animation repos. Synfig is awesome and it exists for good reason. So, can you make this repo (search-engine friendly) to be tagged with words like " 2D, gtkmm, C++, Animation, ..." and whatever that is necessary to be in the eyes of even more githubbers?

**Comment by morevnaproject** [comment]
Hello! Thank you for suggestion! "animation" tag is already there. "C++" is forbidden by GitHub, because it contains "+" symbol. Added "gtkmm" and "2d" tags.
