### ISSUE TITLE
AlphaChannel Videos Export and FFMPEG Profiles (OBS Stinger Compatible)???

### ISSUE THREAD

**Issue by cyberpunkbln** [synfig/synfig#519]
**Synfig version & platform**:
1.2.1 Windows 10 64Bit

Hello,

i try to export my animation as an video file that preserve the alpha channel webm(vp8/vp9) or mov for an obs trigger video directly.

But it does not work. What must i do.

My second Idea was to export the alpha channel as an extra video an use ffmpeg to make an .webm file with yuv402p, to bring together the normal video an the alpha channel video. Knows anybody the correct ffmpeg params for this situation, when synfig cannot export webm alpha channel videos?

How can i setup an new ffmpeg profile for synfig? Hopefully to combine the output yuv402p to webm, when synfig deliver correctly the raw frames with an alpha channel: 
fmpeg.exe -c:v libvpx-vp9 -b:v 2M -vf "format=yuva420p" test.webm

thx

**Comment by caryoscelus** [comment]
You can export it as png sequence and then run convert frames to any video format using ffmpeg.

**Comment by cyberpunkbln** [comment]
Would be a possibility that i use but at the moment seems the only possibility. I hope this feature will come in the future. Synfig has all features built in. Yuva420p, an alphachannel in the editingcanvas and an output to ffmpeg.

I thought i can finetune ffmpeg parameters and write new ffmpeg presets/profiles, it looks like synfig has the internal profiles for ffmpeg static compiled.

I hope in the future i can give ffmpeg directly the raw-picture data and let ffmpeg write with -pix_fmt yuva420 an webm (vp8,vp9) video that i can use as an alphachannel video.

I think synfig has all build in why raw-picture-data with alpchachannel must only be directed to ffmpeg and not only to alphachannel-pngs.

**Comment by morevnaproject** [comment]
You can use "Extract alpha" option for rendering - 
![screenshot_002](https://user-images.githubusercontent.com/332868/38855063-a090c8d8-424c-11e8-8d9c-c7e5eb9d3dec.png)

This will produce two video files - one with color and other with alpha.

In general, having a new profile for encoding into WebM with alpha channel looks like awesome idea. I wasn't aware that WebM supports that.

The profiles are hardcoded at the moment. 

Here is how "h264-lossless" encoding profile defined:
https://github.com/synfig/synfig/blob/master/synfig-core/src/tool/optionsprocessor.cpp#L76
https://github.com/synfig/synfig/blob/master/synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp#L222
https://github.com/synfig/synfig/blob/master/synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp#L244
https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/dialogs/dialog_ffmpegparam.cpp#L61
https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/dialogs/dialog_ffmpegparam.cpp#L77

You can use this as reference for adding a new profile.

**Comment by morevnaproject** [comment]
This feature is implemented in #2563 and will be shipped in version 1.5.2.

**Comment by IcedQuinn** [comment]
Might be able to close this. Looks like the feature was added?

**Comment by ice0** [comment]
> Might be able to close this. Looks like the feature was added?

Yes. Available starting from 1.5.2 release.

**Comment by t1u1** [comment]
I am using version 1.5.3 from flatpak.

The video exported using ffmpeg Webm VP9 doesn't have alpha channel.

The output from `ffplay` on the rendered video is:
```
Stream #0:0: Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv), 483x272, 24 fps, 24 tbr, 24 tbn
```

So it is using the `yuv` profile not `yuva`.

Is it only me, or has there been a regression?

Thanks for looking.

**Comment by rodolforg** [comment]
What was the exact codec name you used?

**Comment by t1u1** [comment]
> What was the exact codec name you used?

<img width="425" height="253" alt="Image" src="https://github.com/user-attachments/assets/d7b89237-e251-49a4-9c62-a16ea25adeec" />

**Comment by rodolforg** [comment]
Ok. The problem is the AppImage that doesn't ship the codecs for ffmpeg 😞.

@morevnaproject @ice0 @BobSynfig

**Comment by BobSynfig** [comment]
It should be possible to do it with the current build system (based on stretch) adding :
- adding `libvpx-dev`, `libopus-dev` and `libvorbis-dev` in the Dockerfile
- in `/env-builder-data/build/script/packet/ffmpeg-3.1.5.sh`:
 ```
--enable-libvorbis \
 --enable-libopus \
 --enable-libvpx"
```

- rebuilding ffmpeg
- Copying some libs (to be check)

I will do the test

**Comment by t1u1** [comment]
Thanks for looking. Please reopen the issue, so that it doesn't fall off your radar.

**Comment by BobSynfig** [comment]
I was able to integrate libvpx and make ffmpeg compatible in the AppImage, but still, like in Flatpak version, it produces only WEBM (VP8 and VP9) without transparency (grey background in VP8, black in VP9).
Anyway I was able to make it work with libwebp/libwebp_anim already in December 2022 (see https://github.com/synfig/synfig/pull/2933).
I should integrate it in one of my unofficial versions of Synfig :P

**Comment by rodolforg** [comment]
> The output from `ffplay` on the rendered video is:

I tested the flatpak and it works fine.
If you play the movie in the browser, you can "see" the transparency...
