### ISSUE TITLE
Some Parameters' Cannot be Set Back to Zero (Scrolling Issue)

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#520]
**Synfig version & platform**:
1.3.6

**Issue description**:
**Note :
Some parameters have this issue while most of them are not
Oddly enough this makes it almost impossible to set the value back to zero (if it has been set to any other value before), but at rare occasion it also can't be set to other values**

EDIT :
_At first it thought that if mouse cursor got moved before setting the value to zero OR cursor NOT moved after setting the value 0, the value won't be saved
So, by setting the value to zero while mouse is static, then moved the cursor and tap 'Enter' can overcome this issue Most of the time_

**But that's NOT the issue**

I saw the timeline panel slightly moving up bit after hovering my mouse to it, so i thought it has something to do with scrolling
![snip_20180418174437](https://user-images.githubusercontent.com/25135159/38927755-fb25c1ce-4330-11e8-9d2b-d5729ab7c8e9.jpg)

Then i try to put the parameter at the tip of the bottom of the panel, click on it so it autoscrolls and then change the value, this always works
Another solution that is 100% works is to click the parameter name, scroll the parameter panel up until the focused parameter is nowhere inside that panel, tap 'Enter', set the value, then 'Enter' or just click out of focus.
or other way around, click the value box, scroll it up, out of panel's sight, set the value, then 'Enter' or click out of focus

**Affected Parameters**:
- Link Time in Time Loop Layer
- Z Range Depth and Z Range Position in Group Layer

Sometimes there's a small chance that parameters other than the ones mentioned above got caught with this issue

**To Reproduce**:
- Create a mentioned layer
- Set the Value in that mentioned parameter to any number
- then try to set it back to zero, no changes at all...

Unless the method mentioned in description above is used

**Comment by morevnaproject** [comment]
Much thanks to @BobSynfig  - looks like it is fixed now! Will be shipped with version 1.3.11. Please test and confirm if the issue is fixed.

**Comment by FadhilKwan** [comment]
Apologies for my late response ._.v
Yes, tried to reset the problematic parameters back to zero, and it did the job very well, with no problems at all~ :)
