### ISSUE TITLE
Windows crash when closed file is re-loaded

### ISSUE THREAD

**Issue by keithnbrowncarlisle** [synfig/synfig#521]
**Synfig version & platform**:
version 1.3.6 Windows 10 64-bit

**Issue description**:
Open a file in synfig, doesn't matter how (from explorer or within synfig).
Close the tab.
Open the same file from within synfig
Crash

Notably when you attempt to open an already open file, it doesn't crash and simply focuses the tab it's in. This would lead me to beleive that whatever mechanism is focusing tabs is still expecting closed files to still be there and is crashing as the file is no longer present.

I did say i'd find more for you @ice0

**Comment by ice0** [comment]
Got it!

**Comment by keithnbrowncarlisle** [comment]
Sorry, this bug is still present on that build. I would try capturing a video of it occuring, but i can't show my full desktop due to broadcasting company info

**Comment by morevnaproject** [comment]
Thank you for testing! Please check this one - https://dev.icystar.com/downloads/SynfigStudio-1.3.7-testing-18.05.07-win64-7ad82.exe

**Comment by ice0** [comment]
Yeah, confirmed.

**Comment by morevnaproject** [comment]
Shipped with version 1.3.9 - https://www.synfig.org/2018/06/25/synfig-studio-1-3-9-released/
