### ISSUE TITLE
Window position not remembered and default is in an odd place

### ISSUE THREAD

**Issue by keithnbrown** [synfig/synfig#523]
**Synfig version & platform**:
version 1.3.6 Windows 10 64-bit

**Issue description**:

The window never remembers last position, or maximised-ness. The initial postion also seems to be ever-so-slightly offset from the corner.

It may be notable that i have 2 monitors.

This screenshot shows my desktop and synfig's initial postition. my monitor divide is the red line
![synfig](https://user-images.githubusercontent.com/4905753/38862089-f3904ebc-422b-11e8-8430-2e07d6ceff7e.PNG)

It may be worth noting that the handles for resizing the windows (that is the area where the cursor changes) are also very far away from the edges of the window, so this would suggest a skinning issue

**Comment by FadhilKwan** [comment]
Does this also have anything to do with skin issue? #487 

This happened to my Synfig, and i'm also using dual stretched display mode

And look what i've found when the synfig got frozen
![snip_20180418194714](https://user-images.githubusercontent.com/25135159/38933084-380c057e-4342-11e8-80bb-7c75e76c2d89.jpg)

why that box is bigger than the actual window...?

does it have anything to do with the drop shadow of the window...?
![snip_20180418195401](https://user-images.githubusercontent.com/25135159/38933211-97659206-4342-11e8-9b8f-c883e7271f99.jpg)

**Comment by ice0** [comment]
> The initial postion also seems to be ever-so-slightly offset from the corner.
I will check this. Possible this is theme related problem.

> does it have anything to do with the drop shadow of the window...?
Yeah, i think so.

**Comment by FadhilKwan** [comment]
> Can you make a screenshot showing how far away cursor is?

All sides or only these three sides would do...?

here's the **maximum** distance for the cursor to change
![snip_20180421115124](https://user-images.githubusercontent.com/25135159/39080527-b9f36fcc-455a-11e8-971b-4b99c40989de.jpg)
![snip_20180421115103](https://user-images.githubusercontent.com/25135159/39080528-c0ee28d0-455a-11e8-990a-4c3d7187cf19.jpg)
![snip_20180421115022](https://user-images.githubusercontent.com/25135159/39080532-c5a5559c-455a-11e8-95bb-7f15399aecd9.jpg)


But oddly enough, the **minimum** distance for these cursors is actually its window (and slight off a tiny amount of pixels...?)
![snip_20180421115725](https://user-images.githubusercontent.com/25135159/39080577-838402a2-455b-11e8-973b-2f7c26f36e37.jpg)
![snip_20180421115701](https://user-images.githubusercontent.com/25135159/39080578-86042cb4-455b-11e8-835b-38a11c05554c.jpg)
![snip_20180421115630](https://user-images.githubusercontent.com/25135159/39080579-88e94630-455b-11e8-84cf-5ca988dcb9ae.jpg)


sorry if it doesn't look that great, i can't snapshot the cursor so i have to use the OBS preview window instead
Also, i put it in front of white BG (it was notepad window) to compare it with the drop shadow

**Comment by BobSynfig** [comment]
This is due to a bug of implementation of shadows in GTK3 for Windows
See 2. of [Suboptimal window drawing on Windows](https://gitlab.gnome.org/GNOME/gtk/issues/105)

**Comment by morevnaproject** [comment]
Okay, so we can solve this by applying this patch when doing our own build of GTK for windows - https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gtk3/0001-gtkwindow-Don-t-force-enable-CSD-under-Windows.patch

This can be done as part of #666.

**Comment by morevnaproject** [comment]
> This can be done as part of #666.

...also, this is already patched if we use MSYS2 for building - https://gitlab.gnome.org/GNOME/gtk/issues/105#note_82344
The support for MSYS2 can be added as part of #694.

**Comment by BobSynfig** [comment]
For now it can be solved by editing synfigstudio.bat (in Synfig's folder)
add <b><code> set GTK_CSD=0</code></b>
before
```
cd "%~dp0\"
start "" "%~dp0\bin\synfigstudio.exe"
```
then start SynfigStudio from synfigstudio.bat (you can modify your desktop shortcut)
@morevnaproject it could be included in the distributed packages ;)

**Comment by morevnaproject** [comment]
>  can be solved by editing synfigstudio.bat (in Synfig's folder)

@BobSynfig Awesome! This is such a simple solution! I will do the fix. ^__^

**Comment by morevnaproject** [comment]
So, I have applied CSD patch from MSYS2 (https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gtk3/0001-gtkwindow-Don-t-force-enable-CSD-under-Windows.patch) and made a test build - https://downloads.synfig.org/almost-1.3.11/SynfigStudio-1.3.11-pre4-64bit-4b7e5.zip

@keithnbrown @FadhilKwan Please test.

![screenshot_003](https://user-images.githubusercontent.com/332868/51429845-c2eace00-1c45-11e9-8c69-92d0e13936b9.png)


(please ignore missing icons, this is going to be fixed soon).

**Comment by morevnaproject** [comment]
Here is a fixed build with icons and CSD patch - https://downloads.synfig.org/almost-1.3.11/SynfigStudio-1.3.11-pre5-64bit-2365f.zip

![screenshot_007](https://user-images.githubusercontent.com/332868/51791324-cd700f00-21d3-11e9-89d3-1af0316a8c9b.png)
