### ISSUE TITLE
Super Sample's Width and Height Often Cannot be set to the same Amount

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#526]
**Synfig version & platform**:
1.3.6

**Issue description**:
A follow-up to this issue : #520 , but it behaviors slightly different so i decided to put a new issue here

If you set the Super Sample Layer's height first, then try to set the same amount to its width, no changes will be made.
This problem occurs **less** often if width set first then height is next

**Comment by morevnaproject** [comment]
Confirmed - still appears on 1.2.2 and 1.3.10.

**Comment by morevnaproject** [comment]
Much thanks to @BobSynfig  - looks like it is fixed now! Will be shipped with version 1.3.11.
