### ISSUE TITLE
No minimize and restore window icons in color chooser

### ISSUE THREAD

**Issue by elthea** [synfig/synfig#533]
**Synfig version & platform**: 1.3.6 & Windows 10
(we're more likely to help if you're using latest development builds)

**Issue description**: I suddenly maximized color chooser window (have no idea what I pressed) and then there where no icons to restore window size or minimize it. So it would be good to have them on in this window to have a way to leave such a window status.

![image](https://user-images.githubusercontent.com/8844351/39277932-b3e402a6-48f0-11e8-9969-1107ca2b58cd.png)

PS. Synfig is the best!

**Comment by Keyikedalube** [comment]
Synfig GUI code is written in GTKMM so you get that GNOME flavor for dialogs where maximize and minimize buttons are not displayed on the title bar.

You can unmaximize it by clicking and dragging the dialog's title bar. That's what we GNOME users do.

Or... dialog resizability could be turned off through code @rodolforg?

**Comment by rodolforg** [comment]
IMO the solo benefit to be able to resize Color dialog would be about slider precision.
But user can fine-adjust by typing or clicking on 'plus'/'minus' buttons on each component value field.

I intend to create a new HSV plane to replace this (deprecated :( ) Gtk widget. Actually I did start to work months ago, but I stopped my work to focus on some bugs (like those from advanced outline width stuff and some crashes).
When I finish my current challenge (a rare crash, but easily 'triggable' by user), I was thinking about finish my old PRs. But maybe I do this color widget first. What I'm saying is: you can fix this problem, but don't invest much time on Color Dialog now :D

**Comment by Keyikedalube** [comment]
That's OK :)
Take your time with your old PRs and come back to this again. I'm not fixing this.
Didn't know this current color widget was already deprecated. Thanks for the heads up!

**Comment by rodolforg** [comment]
You can fix the resize in the meanwhile :)
But please don't try to make fancy changes ;)
