### ISSUE TITLE
Roadmap & Standardizing .SIF

### ISSUE THREAD

**Issue by libreartist** [synfig/synfig#537]
**Synfig version & platform**: 1.36, AV Linux 2018

**Issue description**: I'm sorry that this issue posting is a bit long, already-spoken and untimely, when the main focus is on bug-fixing and stability for Synfig. Yet, may consider it for Synfig's future.

Related to #471 & #497, I find that working document of Synfig's Roadmap and File Format (.sif) could be much needed (like a Polar Star) to direct its development in future. Because, I think, the documents would clearly give out the clear outline for anyone who's working on the project.

Based upon what I could find in the "Feature Request" Issues that are still open, I have made a proposal for Synfig's **Roadmap** as follows:

**Tools**
Fill Selection Tool for vector outlines; #534
"Edit in External Tool" option for updating the assets via external editors; #516 #513

**App Usability**
Improved Keyboard Shortcuts; #465 #421 #414
Create, Save, Delete & Copy-Paste between Custom Workspaces; #430 #245 #241
Improved Workflow between Multiple Timelines; #272
Parameter Filter Groups; #268 #250
New Resources Library: A new Library Panel to manage all (internal and external) resources of animation file - images, canvases, fonts, sounds, etc.; Ref: https://github.com/synfig/synfig/projects

**Layers**
Outline Effect Layer, to make the blur in the Shade Layer optional so that it becomes a colored outline around the underlying shapes instead of a blurred shadow; #340
Lockable Layers; #301
X-Sheet Layer; #278
Ability to convert spine-based layers to all spine-derived layers; #256

**Rendering**
Applying effects via G'MIC Integration; #477
GEGL Integration for improved raster operations; #326
Configurable Playback Speed; #259

**Editing**
Improved Text Editing; #302 #286
Improved Gradient Editing; #285

**Curves & Nodes**
Visual Node Editor; #315 #312
Bezier-Curve Values Interpolation; #295 #275 #272 #267
Generic Waypoint Editing Operations; #266

**Bones**
Improved Bones; Ref: https://github.com/synfig/synfig/projects

And this list of roadmap could be improved later by adding necessary improvements, once the current dev builds attain stable release. Also, I would love to see .sif format not to be as described in https://wiki.synfig.org/Sif_Format : "The .sif format is formidably complex and evolving. It is implementation-defined rather than spec-defined." I just wish, couldn't the .sif format be more of a spec-defined, like SVG, to make it roadmap-friendly? Also, this would make things clear. (I've also coined a expansion name for the format, out of curiosity. SIF = Synfig Interchange Format!)

Thank you:-)

**Comment by libreartist** [comment]
or, SIF = Scene Interchange Format (to give it more open-standard and general appeal)

**Comment by libreartist** [comment]
Also, necessary items to be added into **Roadmap,** in future can be taken from  https://www.synfig.org/forums/viewforum.php?f=14&sid=fb07b101ca55fbff7da97435b50e1e35

**Comment by elthea** [comment]
Hi I agree especially about SIF format. When somebody want to write plugin it takes a lot of time to have full sif understanding.

**Comment by morevnaproject** [comment]
Hello, @libreartist ! Yes, we are in the process of bug fixing, but this document is a good starting point to make a Big Picture Roadmap.

**Comment by Jose-Moreno** [comment]
@libreartist @morevnaproject I think this is a fantastic effort but I'd like to help organizing the roadmap for Synfig. Is there a particular platform we can use to collaborate for this?

**Comment by morevnaproject** [comment]
@Jose-Moreno My apologies, your message got lost in a pile of other messages and I didn't responded in time. ^__^"

We have a Roadmap document open for collaboration here - https://synfig-docs-dev.readthedocs.io/en/latest/common/roadmap.html
You can edit this page using GitHub here - https://github.com/synfig/synfig-docs-dev/blob/master/docs/common/roadmap.rst

**Comment by Keyikedalube** [comment]
For someone who wants to work on Synfig file format (SIF), a new doc page has been proposed by @rodolforg here https://github.com/synfig/synfig-docs-dev/pull/79

**Comment by Keyikedalube** [comment]
Closing this because dev doc is more suitable. And [@rodolforg's PR](https://github.com/synfig/synfig-docs-dev/pull/79) has been merged recently.
