### ISSUE TITLE
Save All Button disabled when on first tab regardless of other tabs

### ISSUE THREAD

**Issue by keithnbrown** [synfig/synfig#538]
**Synfig version & platform**:
Windows 10 64-bit using SynfigStudio-1.3.6-testing-18.04.22-win32-c71d0.exe supplied on ticket #521 
Issue has been spotted in earlier stable builds.

**Issue description**:
Regardless of the number of tabs open (and their respective "needing-saved-ness") the Save All button on the toolbar beneath the tabs is always disabled if you're on the first, leftmost tab.

The File Menu option remains enabled and usable under the same circumstances.

**Comment by elthea** [comment]
I confirm -  I have the same issue with Save All button.
