### ISSUE TITLE
I can't move multiple vertices.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#541]
**Synfig version & platform**:
Manjaro Linux KDE  (17.1.10)
Using:
Synfig 1.3.7
GTK+ 3.22.30
Built on May  9 2018
Built with:
ETL 1.3.7
Synfig API 01.02.00
Synfig library 50
GTK+ 3.22.30
GNU G++ 7.3.1

**Issue description**:
I can't move multiple vertices anymore with the transform tool.
1. Create a shape with the Spline tool.
2. Change to transform tool
3. Select more than one vertices an try to move them

**Comment by morevnaproject** [comment]
Confirmed, @ice0 will be working on that. 

As temporary workaround please use Smooth Move Tool with a big Radius value.
![screenshot_006](https://user-images.githubusercontent.com/332868/39963294-c900a37a-5691-11e8-999d-a663a5ad04de.png)

Apologies for inconvenience and thank you for reporting!

**Comment by ice0** [comment]
@morevnaproject please check

**Comment by morevnaproject** [comment]
Checking now. Thank you! ^__^

**Comment by ebarranco** [comment]
@ice0 It's wotkin for me, Thank you.

**Comment by morevnaproject** [comment]
@ice0 Works perfectly! #470 is also unaffected. Thank you!

@FadhilKwan Windows builds are coming! I am starting release preparations for 1.3.8. ^__^
