### ISSUE TITLE
Add keyframe on a exported canvas

### ISSUE THREAD

**Issue by Jengall** [synfig/synfig#542]
**Synfig version & platform**:
Synfig 1.2.1(stable) and 1.3.5(dev) & PC 64  Win10

**Issue description**:
Trying to do this:
https://wiki.synfig.org/Doc:Reuse_Animations

I am stuck when I try to add keyframe on my exported canvas, 
All is greyed, there is no timeline.

![image](https://user-images.githubusercontent.com/11194459/39843140-0d1533c8-53ea-11e8-8c4f-3084c2e0c2d5.png)

**Comment by caillette** [comment]
Same for me on Synfig 1.2.2, macOS 10.14.2.

**Comment by ice0** [comment]
Possible because nothing is selected in Layers panel?

**Comment by caillette** [comment]
In the main project, I jumped to a Keyframe and selected an item of the exported Canvas.
Then I selected the exported Canvas, and the button to add Keyframes is disabled, as the timeline is. This is the same situation as in Jengall's screenshot.
Does it work on Linux?

**Comment by caillette** [comment]
I installed Synfig 1.2.1 in an Ubuntu 18.04.1 LTS in VirtualBox 6.0.2 in macOS 10.14.2.

- Create a fresh project.
- Create a Rectangle.
- Create a Keyframe at 50f.
- Create a Keyframe at 100f.
- Animate the Rectangle from its initial position (0f) to Keyframe 100f.
- Turn off editing mode.
- Go to 0f.
- Create a Star.
- Put the Star in Group "Group 1".
- Go to Keyframe 50f.
- Animate Group 1 (so it "knows" about keyframes).
- Turn off editing mode.
- Select Group 1 and its Canvas, select "Export Canvas", name as "Group1".
- Select Group1 Animation.

Timeline doesn't show. "Add New Keyframe" button is disabled.

**Comment by caillette** [comment]
Maybe I misunderstood something. I downloaded the `Eyeblink.sifz` animation (attached to the documentation linked to by Jengall) and it seems to work. There are Keyframes in the reusable animation but the "Add New Keyframe" button is still disabled.

**Comment by ice0** [comment]
Please check Canvas->Properties->Time->Duration (on exported canvas).

**Comment by caillette** [comment]
Thanks ice0 it works! Exported Canvas lose all references to exporter's Keyframes, but that's quite logical after all.

I updated the procedure above, which couldn't work because I was adding a Keyframe before exporting the Canvas.

I suggest that you close this issue as "not a bug".

**Comment by ice0** [comment]
Also as a temporary workaround you need to save your work file and exported canvas, and after that close it and open again.
