### ISSUE TITLE
programa de merda 

### ISSUE THREAD

**Issue by dylandfd** [synfig/synfig#547]
estou farto deste programa, crasha por tudo e por nada nem uma animaçao da para fazer, se se considerem developers deveriam tirar novamante o curso que este programa ta uma merda

**Comment by ice0** [comment]
Olá! Agora estou corrigindo os erros que levaram à partida da Synfig. Se houver algum erro específico, você poderá criar uma solicitação separada para a correção. Porque Synfig agora em desenvolvimento ativo, então verifique a última versão de teste, talvez o bug já tenha sido corrigido. 
https://dev.icystar.com/downloads/SynfigStudio-1.3.6-testing-18.04.22-win64-c71d0.exe
