### ISSUE TITLE
Animated gif/apng import

### ISSUE THREAD

**Issue by hellocatfood** [synfig/synfig#552]
At the moment the only way to import animated gifs or animated pngs is to separate them out into their individual frames and then use the List Importer script https://wiki.synfig.org/Doc:ListImporter

Although it is a solution it would be more efficient if Synfig supported animated gifs and/or apng files.

**Comment by ice0** [comment]
@hellocatfood Sounds like a plan!

**Comment by maitreyi0505** [comment]
@morevnaproject 
In the lastest version of Synfig ( version 1.3.11) you can save gif animation by using .gif extension and target as gif (but it doesnt always work)
The application still crashes every time when saving a file using .gif extension and target as magick++(as demonstrated in udemy course)

**Comment by morevnaproject** [comment]
Hi @maitreyi0505!We have fixed that recently - https://github.com/synfig/synfig/commit/d1898cfe3351e3839a75ddb06e70c5e05569a91a

The fix will be shipped in the next development build (or you can build from source if you are on Linux).

**Comment by hellocatfood** [comment]
This works (albiet gifs can be slow to play) so should this be closed now?

**Comment by ice0** [comment]
@hellocatfood I think yes )
