### ISSUE TITLE
Uninstalling Synfig does not delete Start Menu shortcuts

### ISSUE THREAD

**Issue by gbaudic** [synfig/synfig#553]
**Synfig version & platform**:
Synfig Studio 1.2.1
Windows 8.1 64 bit

**Issue description**:

When uninstalling Synfig Studio on Windows, the uninstaller runs and completes just fine but the program shortcuts in the Start Menu remain. Although Windows suggests deleting them when clicking on them because their target can no longer be found, it would be better if this was handled by the uninstaller.

**Comment by ice0** [comment]
Hello, Gwilherm!
Thank you for the bug report. Confirmed, will be fixed soon.

**Comment by morevnaproject** [comment]
Fix shipped with 1.3.9 - https://www.synfig.org/2018/06/25/synfig-studio-1-3-9-released/
