### ISSUE TITLE
Backport compatibility with ImageMagick 7 to stable (1.2.x)

### ISSUE THREAD

**Issue by xHire** [synfig/synfig#556]
Synfig 1.2.1 with ImageMagick 7 installed doesn’t build. This has been addressed in PR #478. I suggest backporting both commits from the PR:

    git cherry-pick 3825a147ee4d0057716d185af43e7fe9b4418898 017eccd7a1086c5cf1749bbcc6f47f756b9dd297

There are no conflicts—the commits apply cleanly. Afterwards, the build is successful.

**Comment by morevnaproject** [comment]
The fix is now shipped with Synfig 1.2.2 (stable). Please check if everything alright. Thank you!

**Comment by xHire** [comment]
Yes, works perfectly, thanks! :·)
