### ISSUE TITLE
Top Bits of the UI are Messed Up in Bigger Window Resolutions

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#570]
**Synfig version & platform**:
1.3.9 in Windows 10 - 64-bit
with 2-screen and stretched display mode (if it's necessary)

**Issue description**:
it's just... broken...

![snip_20180626142510](https://user-images.githubusercontent.com/25135159/41927546-be726668-799c-11e8-9106-0ab31a9a5f37.jpg)
two options at different lines, the ones above does nothing when clicked, and the other ones won't appear unless i click at one of the options

![snip_20180626142556](https://user-images.githubusercontent.com/25135159/41927597-d8d18304-799c-11e8-8389-a00079b5701f.jpg)
i have to click one of the icon's location to make them all appear, then the buttons works properly (still messy though)

upon further inspection, i found out that this bug occurs when the window got resized at a certain resolution
[2018-06-27 00-08-20.zip](https://github.com/synfig/synfig/files/2138190/2018-06-27.00-08-20.zip)

in maximized window mode it happens all the time
![snip_20180626235519](https://user-images.githubusercontent.com/25135159/41927747-431f3a62-799d-11e8-9557-62e4a7770ca3.jpg)

**Comment by ice0** [comment]
Hi! I'm trying to reproduce the problem, but everything is working fine for me. Could you check that the problem is reproduced using one monitor?

**Comment by FadhilKwan** [comment]
so, i tried 3 things
1. Single Display test : Still Bugged
2. Normal Reinstall : Still Bugged

3. Fresh Reinstall (deleting app data and registries then reinstall)

now the last one fixes it.... at least what i thought.....
then when i tried to customize the layout to my liking, this happens...
[2018-06-29 23-57-01.zip](https://github.com/synfig/synfig/files/2150221/2018-06-29.23-57-01.zip)

the footage shows that this bug is not related to the screen setting... it's more of a layout error...
and notice on the second boot that suddenly an imagemagick error showed up, saying something like file not found or some sort....

so from here i decided to dig deeper
[2018-06-30 00-08-45.zip](https://github.com/synfig/synfig/files/2150257/2018-06-30.00-08-45.zip)
things get a bit weirder, especially for the left column that got stacked by several docks.
At one point it seems not having that issue even with that stack, but only once.
Also, its getting a bit stranger at around 1 minute clip, where i can't drag the window downward (also only for once).

**Comment by FadhilKwan** [comment]
oh, also for that weird behavior while dragging dockers and icons in the footages, i'll just refer this one
#487

**Comment by FadhilKwan** [comment]
umm... just want to ask
@ice0 please let me know if you can reproduce it

if not, i'll look for another factor that might cause the issue....

**Comment by morevnaproject** [comment]
It seems we have fixed issue when we disabled GTK custom decorations. Should work fine now. 
Can anyone confirm?

**Comment by FadhilKwan** [comment]
Yes, can confirm on dev ver1.3.13. It works properly now! ^-^
