### ISSUE TITLE
Highlight the timetrack row based on the selection in parameter panel

### ISSUE THREAD

**Issue by thekalinga** [synfig/synfig#575]
**Synfig version & platform**:
1.3.9
Ubuntu 14.04

**Issue description**:

Currently an objects parameter row is selected in the `parameters` panel, only the row in the `parameter` panel is highlighted (which includes some short form of `timetrack` panel) & user need to eyeball the corresponding row in the actual `timetrack` panel, where you see the actual time

If we highlight the row in the timetrack panel, the tool punishes the user little less just to see which timetrack row corresponds to which parameter (esp when user moves panels around for convenience like I do)

We should highlight the row in the timetrack panel corresponding to the currently selected paramater in the parameters panel

**Comment by Keyikedalube** [comment]
Closing this in favor of #246
