### ISSUE TITLE
Incorrect behaviour of Draft mode

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#582]
**Synfig version & platform**:
version 1.3.10

**Issue description**:
See sample file attached - 
[draft-mode.sifz.zip](https://github.com/synfig/synfig/files/2216267/draft-mode.sifz.zip)

Here is how it looks when Draft mode is off (everything okay):
![screenshot_007](https://user-images.githubusercontent.com/332868/43037046-9b2bf2ba-8d32-11e8-9ea5-f58ac3a33c06.png)

With Draft mode ON (also okay):
![screenshot_008](https://user-images.githubusercontent.com/332868/43037071-d6d657a6-8d32-11e8-9830-c84275506b7f.png)

But, If disable visibility for  "Circle2", then everything disappears (bug):
![screenshot_009](https://user-images.githubusercontent.com/332868/43037077-f4fabcd6-8d32-11e8-8fc7-b727590e5c00.png)

Expected behaviour: "Circle1" should be visible.

**Comment by FadhilKwan** [comment]
a bit of heads up @morevnaproject 
from what i've found, draft mode seems to also deletes waypoints as well (except for the ones at frame zero)

it happens when i switched to draft mode from the toolbar's button

i'll come back with a clip very soon...

**Comment by morevnaproject** [comment]
Tested on 12dbc2896a8 - the issue doesn't appear anymore.

**Comment by morevnaproject** [comment]
The fix is available for testing in Synfig Studio 1.3.11 - https://www.synfig.org/2019/02/16/synfig-studio-1-3-11-released/
