### ISSUE TITLE
Have a provision to allow user to open issue with crash/freeze info

### ISSUE THREAD

**Issue by thekalinga** [synfig/synfig#585]
**Synfig version & platform**:
1.3.9, Ubuntu 16.04

**Issue description**:

Synfig is notorious for the number of times it crashes during the life of a simple animation. Also when working on any serious project with decent resolution & decent number of objects, the number of times it freezes (even after selecting lowres) is notoriously high & we are forced to kill the process & restart it

Incase of crash, synfig should provide a provision to the user to report the crash with the actions user performed & have a provision to open an issue. This way the issues in synfig would be uncovered much sooner. Currently, despite 100s of crashes (I'm not exaggerating when I say this), I have not even opened a single crash related issue because I have to reproduce the issue on a small project & it takes effort.

If the tool can give a simple option to the user to open a github ticket with all the relevant data collected by the tool, it makes the real issues to be reported much sooner & so the chance to make the tool much better is quite high

Currently the issue reporting is left in the hands of extremely frustrated users like me (who is an extremely low percentage of users) to report the issues

**Comment by thekalinga** [comment]
There is a simple principle in software engineering. If you make it too hard to do, people will stop doing it. Currently crash reporting is one such area in Synfig

**Comment by Keyikedalube** [comment]
Closing this in favor of #391
