### ISSUE TITLE
Crash when exported value is set from parameters panel for the first time

### ISSUE THREAD

**Issue by thekalinga** [synfig/synfig#588]
**Synfig version & platform**:
1.3.10, Ubuntu 16.04

**Issue description**:

1. Export parameter of a object
2. Turn on animation mode
3. Move the timeline by few seconds
4. Go to the object parameter & change the value (Dont change the value from `Library -> ValueBaseNode` area as it does not crash from there)
5. See the crash

I have attached the example sif. In this example, switch to animate mode, move my few seconds & change the `amount` parameter value. Observe the crash

You can see the crash here
![crash](https://user-images.githubusercontent.com/452518/43064023-5738d272-8e7b-11e8-9f55-cfe47beaeec4.gif)

[test-export-value-crash.sif.zip](https://github.com/synfig/synfig/files/2218404/test-export-value-crash.sif.zip)

**Comment by morevnaproject** [comment]
Fixed in master branch.

**Comment by morevnaproject** [comment]
The fix is available for testing in Synfig Studio 1.3.11 - https://www.synfig.org/2019/02/16/synfig-studio-1-3-11-released/
