### ISSUE TITLE
No handles using different tools (circle, star, gradient...)

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#613]
**Synfig version & platform**:
Master
Linux
**Issue description**:
When you use circles, stars, rectangles, polygons and gradients tools, you can't see their initialisation handles.
[You can watch a video here.](https://www.dropbox.com/s/sjr2an5ysq3hgdj/2018-08-21%2016-32-42.mkv?dl=0)

**Comment by blackwarthog** [comment]
Fixed now in master branch. Much thanks for your feedback!
