### ISSUE TITLE
Synfig crash, decreasing resolution.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#614]
**Synfig version & platform**:
Master
Linux

**Issue description**:
Synfig crash, when you enable low resolution and decrease the resolution.
[You can see a video here.](https://www.dropbox.com/s/wrwchq8rqwqy96z/2018-08-21%2016-42-15.mkv?dl=0)

**Comment by ice0** [comment]
Hi! Can you please check testing build?
https://dev.icystar.com/downloads/SynfigStudio-1.3.10-testing-18.08.22-linux64-014b5.appimage

**Comment by ebarranco** [comment]
hi @ice0 it's crashing with the appimage too.
