### ISSUE TITLE
Build errors (ffmpeg4)

### ISSUE THREAD

**Issue by HotelBellaMuerte** [synfig/synfig#615]
ffmpeg: 4.0.2

Buildlog

trgt_av.cpp:633:30: error: ‘PIX_FMT_YUV420P’ no se declaró en este ámbito
   video_st->codec->pix_fmt = PIX_FMT_YUV420P;
                              ^~~~~~~~~~~~~~~
trgt_av.cpp:633:30: nota: suggested alternative: ‘AV_PIX_FMT_YUV420P’
   video_st->codec->pix_fmt = PIX_FMT_YUV420P;
                              ^~~~~~~~~~~~~~~
                              AV_PIX_FMT_YUV420P
trgt_av.cpp:636:3: error: ‘dump_format’ no se declaró en este ámbito
   dump_format(formatc, 0, filename, 1);
   ^~~~~~~~~~~
trgt_av.cpp:636:3: nota: suggested alternative: ‘av_dump_format’
   dump_format(formatc, 0, filename, 1);
   ^~~~~~~~~~~
   av_dump_format
trgt_av.cpp:660:41: error: ‘URL_WRONLY’ no se declaró en este ámbito
    if(url_fopen(&formatc->pb, filename, URL_WRONLY) < 0)
                                         ^~~~~~~~~~
trgt_av.cpp:660:41: nota: suggested alternative: ‘STA_RONLY’
    if(url_fopen(&formatc->pb, filename, URL_WRONLY) < 0)
                                         ^~~~~~~~~~
                                         STA_RONLY
trgt_av.cpp:660:7: error: ‘url_fopen’ no se declaró en este ámbito
    if(url_fopen(&formatc->pb, filename, URL_WRONLY) < 0)
       ^~~~~~~~~
trgt_av.cpp:660:7: nota: suggested alternative: ‘freopen’
    if(url_fopen(&formatc->pb, filename, URL_WRONLY) < 0)
       ^~~~~~~~~
       freopen
trgt_av.cpp:669:27: error: ‘PIX_FMT_RGB24’ no se declaró en este ámbito
   picture = alloc_picture(PIX_FMT_RGB24,vInfo.w,vInfo.h);//video_st->codec.width, video_st->codec.height);
                           ^~~~~~~~~~~~~
trgt_av.cpp:669:27: nota: suggested alternative: ‘AV_PIX_FMT_RGB24’
   picture = alloc_picture(PIX_FMT_RGB24,vInfo.w,vInfo.h);//video_st->codec.width, video_st->codec.height);
                           ^~~~~~~~~~~~~
                           AV_PIX_FMT_RGB24
trgt_av.cpp:681:3: error: ‘av_write_header’ no se declaró en este ámbito
   av_write_header(formatc);
   ^~~~~~~~~~~~~~~
trgt_av.cpp:681:3: nota: suggested alternative: ‘av_write_trailer’
   av_write_header(formatc);
   ^~~~~~~~~~~~~~~
   av_write_trailer
trgt_av.cpp: En la función miembro ‘void Target_LibAVCodec::LibAVEncoder::CleanUp()’:
trgt_av.cpp:721:5: error: ‘url_fclose’ no se declaró en este ámbito
     url_fclose(formatc->pb);
     ^~~~~~~~~~
trgt_av.cpp:721:5: nota: suggested alternative: ‘fclose’
     url_fclose(formatc->pb);
     ^~~~~~~~~~
     fclose
trgt_av.cpp: En la función miembro ‘AVStream* Target_LibAVCodec::LibAVEncoder::add_video_stream(int, const VideoInfo&)’:
trgt_av.cpp:753:8: error: ‘av_new_stream’ no se declaró en este ámbito
   st = av_new_stream(formatc, 0);
        ^~~~~~~~~~~~~
trgt_av.cpp:753:8: nota: suggested alternative: ‘av_new_program’
   st = av_new_stream(formatc, 0);
        ^~~~~~~~~~~~~
        av_new_program
trgt_av.cpp:760:17: aviso: ‘AVStream::codec’ es obsoleto [-Wdeprecated-declarations]
   context = st->codec;
                 ^~~~~
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:877:21: nota: se declara aquí
     AVCodecContext *codec;
                     ^~~~~
trgt_av.cpp:760:17: aviso: ‘AVStream::codec’ es obsoleto [-Wdeprecated-declarations]
   context = st->codec;
                 ^~~~~
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:877:21: nota: se declara aquí
     AVCodecContext *codec;
                     ^~~~~
trgt_av.cpp:760:17: aviso: ‘AVStream::codec’ es obsoleto [-Wdeprecated-declarations]
   context = st->codec;
                 ^~~~~
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:877:21: nota: se declara aquí
     AVCodecContext *codec;
                     ^~~~~
trgt_av.cpp:761:24: error: ‘CodecID’ no se declaró en este ámbito
   context->codec_id = (CodecID)codec_id;
                        ^~~~~~~
trgt_av.cpp:761:24: nota: suggested alternative: ‘AVCodecID’
   context->codec_id = (CodecID)codec_id;
                        ^~~~~~~
                        AVCodecID
trgt_av.cpp:762:25: error: ‘CODEC_TYPE_VIDEO’ no se declaró en este ámbito
   context->codec_type = CODEC_TYPE_VIDEO;
                         ^~~~~~~~~~~~~~~~
trgt_av.cpp:762:25: nota: suggested alternative: ‘AVMEDIA_TYPE_VIDEO’
   context->codec_type = CODEC_TYPE_VIDEO;
                         ^~~~~~~~~~~~~~~~
                         AVMEDIA_TYPE_VIDEO
trgt_av.cpp:784:28: error: ‘CODEC_ID_MPEG1VIDEO’ no se declaró en este ámbito
   if (context->codec_id == CODEC_ID_MPEG1VIDEO ||
                            ^~~~~~~~~~~~~~~~~~~
trgt_av.cpp:784:28: nota: suggested alternative: ‘AV_CODEC_ID_MPEG1VIDEO’
   if (context->codec_id == CODEC_ID_MPEG1VIDEO ||
                            ^~~~~~~~~~~~~~~~~~~
                            AV_CODEC_ID_MPEG1VIDEO
trgt_av.cpp:785:25: error: ‘CODEC_ID_MPEG2VIDEO’ no se declaró en este ámbito
    context->codec_id == CODEC_ID_MPEG2VIDEO)
                         ^~~~~~~~~~~~~~~~~~~
trgt_av.cpp:785:25: nota: suggested alternative: ‘AV_CODEC_ID_MPEG2VIDEO’
    context->codec_id == CODEC_ID_MPEG2VIDEO)
                         ^~~~~~~~~~~~~~~~~~~
                         AV_CODEC_ID_MPEG2VIDEO
trgt_av.cpp:748:33: aviso: parámetro ‘codec_id’ sin uso [-Wunused-parameter]
  AVStream *add_video_stream(int codec_id, const VideoInfo &info)
                             ~~~~^~~~~~~~
trgt_av.cpp: En la función miembro ‘AVStream* Target_LibAVCodec::LibAVEncoder::add_audio_stream(int, const AudioInfo&)’:
trgt_av.cpp:800:12: error: ‘av_new_stream’ no se declaró en este ámbito
   stream = av_new_stream(formatc, 1);
            ^~~~~~~~~~~~~
trgt_av.cpp:800:12: nota: suggested alternative: ‘av_new_program’
   stream = av_new_stream(formatc, 1);
            ^~~~~~~~~~~~~
            av_new_program
trgt_av.cpp:807:21: aviso: ‘AVStream::codec’ es obsoleto [-Wdeprecated-declarations]
   context = stream->codec;
                     ^~~~~
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:877:21: nota: se declara aquí
     AVCodecContext *codec;
                     ^~~~~
trgt_av.cpp:807:21: aviso: ‘AVStream::codec’ es obsoleto [-Wdeprecated-declarations]
   context = stream->codec;
                     ^~~~~
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:877:21: nota: se declara aquí
     AVCodecContext *codec;
                     ^~~~~
trgt_av.cpp:807:21: aviso: ‘AVStream::codec’ es obsoleto [-Wdeprecated-declarations]
   context = stream->codec;
                     ^~~~~
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:877:21: nota: se declara aquí
     AVCodecContext *codec;
                     ^~~~~
trgt_av.cpp:808:24: error: ‘CodecID’ no se declaró en este ámbito
   context->codec_id = (CodecID)codec_id;
                        ^~~~~~~
trgt_av.cpp:808:24: nota: suggested alternative: ‘AVCodecID’
   context->codec_id = (CodecID)codec_id;
                        ^~~~~~~
                        AVCodecID
trgt_av.cpp:809:25: error: ‘CODEC_TYPE_AUDIO’ no se declaró en este ámbito
   context->codec_type = CODEC_TYPE_AUDIO;
                         ^~~~~~~~~~~~~~~~
trgt_av.cpp:809:25: nota: suggested alternative: ‘AVMEDIA_TYPE_AUDIO’
   context->codec_type = CODEC_TYPE_AUDIO;
                         ^~~~~~~~~~~~~~~~
                         AVMEDIA_TYPE_AUDIO
trgt_av.cpp:795:33: aviso: parámetro ‘codec_id’ sin uso [-Wunused-parameter]
  AVStream *add_audio_stream(int codec_id,const AudioInfo &/*aInfo*/)
                             ~~~~^~~~~~~~
trgt_av.cpp: En el constructor ‘Target_LibAVCodec::Target_LibAVCodec(const char*, const synfig::TargetParam&)’:
trgt_av.cpp:829:19: aviso: ‘void av_register_all()’ es obsoleto [-Wdeprecated-declarations]
   av_register_all();
                   ^
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:2025:6: nota: se declara aquí
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
trgt_av.cpp:829:19: aviso: ‘void av_register_all()’ es obsoleto [-Wdeprecated-declarations]
   av_register_all();
                   ^
In file included from trgt_av.cpp:43:
/usr/include/libavformat/avformat.h:2025:6: nota: se declara aquí
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
trgt_av.cpp:831:2: error: ‘set_remove_alpha’ no se declaró en este ámbito
  set_remove_alpha();
  ^~~~~~~~~~~~~~~~
trgt_av.cpp: En la función miembro ‘virtual bool Target_LibAVCodec::init(synfig::ProgressCallback*)’:
trgt_av.cpp:978:56: aviso: parámetro ‘cb’ sin uso [-Wunused-parameter]
 bool Target_LibAVCodec::init(synfig::ProgressCallback *cb)
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~^~

**Comment by ice0** [comment]
Hi! Which OS/compiler you use for compilation?

**Comment by Keyikedalube** [comment]
Closed this due to inactivity.
