### ISSUE TITLE
Scale to fit canvas has opposite meaning

### ISSUE THREAD

**Issue by idealius** [synfig/synfig#618]
Synfig 1.2.1
Mac OS X Sierra (10.13.6) (latest):

Under Edit > Preferences > Editing
The scale to fit canvas option is set to default: "no", but "no" means "yes".
Toggling it consistently shows opposite function.

<img width="1269" alt="screen shot 2018-09-03 at 10 10 08 pm" src="https://user-images.githubusercontent.com/20410904/45008153-a6b40080-afc6-11e8-98f7-8160de5d1c47.png">

**Comment by morevnaproject** [comment]
Hello! The widget doesn't shows "no" text. It shows "on", which means "Enabled" (as opposite to "off" - "Disabled").

When "Scale to fit canvas" set to "on" then imported images are scaled to fit - just as expected. I cannot reproduce opposite behavior. Am I missing something?
