### ISSUE TITLE
Bug: Synfig window is transparent in places

### ISSUE THREAD

**Issue by RichardJECooke** [synfig/synfig#625]
**Synfig version & platform**:
- 1.2.2
- Windows 10 64

**Issue description**:
Synfig window is transparent in places. And also I can't click on the menu bar.  See screenshot.

![untitled](https://user-images.githubusercontent.com/5468805/45917927-37bc2000-be7f-11e8-91f7-a5c350c8344c.png)

**Comment by ice0** [comment]
Hi! Do you use windows theme patchers or something?

**Comment by ice0** [comment]
I am closing it because there is no answer here.
