### ISSUE TITLE
Feature request: Give feedback when rendering is happening and complete

### ISSUE THREAD

**Issue by RichardJECooke** [synfig/synfig#626]
**Synfig version & platform**:
Synfig 1.2.2.. Windows

**Issue description**:

File - Render - GIF - go.
Nothing seems to happen. But in my folder I can see a file is gradually getting bigger so it's working. But I have no idea when it's finished. Please add a a window or progress bar or toast or something to give user feedback here

**Comment by wstaelens** [comment]
Yea for mp4, you just see a cmd prompt and it is complete when cmd closes… just a console.writeline like in blender would be great!

**Comment by morevnaproject** [comment]
The fix is merged now! Will be shipped with next release of Synfig. Thank you!
