### ISSUE TITLE
Feature request: Rename file extension when rendering based on 'target'

### ISSUE THREAD

**Issue by RichardJECooke** [synfig/synfig#627]
**Synfig version & platform**:
1.2.2

**Issue description**:
As the title. Use case: I've saved as png. Now I want to render as gif. And it overwrites my png. When I change the target to gif my file extension in the textbox above should change to gif (or mpeg or whatever)

**Comment by ankit-kumar-dwivedi** [comment]
I would like to work on this @morevnaproject . Can you shed some light :)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Thant's great! I advice to start looking in https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/render.cpp - this is a code for Render Options window.

Render Options window is called through "File" -> "Render" menu command.

![screenshot_001](https://user-images.githubusercontent.com/332868/51802529-8f2f2a00-227d-11e9-8800-75ce4e4d3e35.png)

Changing value in "Target" dropdown (1) should automatically change extension in "Filename" field  to appropriate value (2).

![screenshot_003](https://user-images.githubusercontent.com/332868/51802564-f2b95780-227d-11e9-8b5d-58b09add54e0.png)

I.e. when user choosing "ffmpeg" target, the file extension in "Filename" field should change to ".avi"/

**Comment by morevnaproject** [comment]
Here is a list of targets and corresponding extensions:

* "Auto"  - don't change extension
* "bmp" -> ".bmp"
* "cairo_png" -> ".png"
* "dv" -> ".dv"
* "ffmpeg" -> ".avi"
* "gif" -> ".gif"
* imagemagick" -> ".png"
* "jpeg" -> ".jpg"
* magick++" -> ".gif"
* "null" -> don't change extension
* "null-tile" -> don't change extension
* "png" -> ".png"
* "png-spritesheet" -> ".png"
* "ppm" -> ".ppm"
* "yuv420p" -> ".yuv"

**Comment by ankit-kumar-dwivedi** [comment]
Sorry for responding late @morevnaproject I was busy with some college stuff. Have started looking the code. I wish [there](https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/render.cpp) to be more comments :(

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi As per request in #464, in recent version we have changed default format from ".png" to ".avi".

So, the format is set on line 227:
https://github.com/synfig/synfig/blob/4aa255f9ad852e3de5a64046f243a8b9dc34d143/synfig-studio/src/gui/render.cpp#L213-L228

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Any progress on this? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Will send a PR soon! 😁

**Comment by ankit-kumar-dwivedi** [comment]
Sorry for taking so long for solving this issue. I was having a busy week
at college. Will let you know the progress tomorrow.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject How can I check that the changes I made are correct? i.e after building the synfig

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi You can check by doing the following steps:
1. Start your compiled version of Synfig.
2. Choose "File" -> "Render..." from menu. 
3. In "Filename" text entry you will have something like "Synfig Animation 1.avi" (ends with ".avi").
![screenshot_002](https://user-images.githubusercontent.com/332868/52605219-61163080-2ea0-11e9-88f7-3b7810568ea5.png)

4. In "Target" dropdown choose "png". As result, the text in "Filename" entry should change to something with ".png" at the end. If it did, then your changes working correctly.
![screenshot_004](https://user-images.githubusercontent.com/332868/52605284-b18d8e00-2ea0-11e9-9b8b-24d0e4b7039f.png)

5. After that you can do one more check: from "Target" dropdown choose "ffmpeg" and as result the text in "Filename" entry should change to something with ".avi" at the end.

**Comment by ankit-kumar-dwivedi** [comment]
> Here is a list of targets and corresponding extensions:
> 
>     * "Auto"  - don't change extension
> 
>     * "bmp" -> ".bmp"
> 
>     * "cairo_png" -> ".png"
> 
>     * "dv" -> ".dv"
> 
>     * "ffmpeg" -> ".avi"
> 
>     * "gif" -> ".gif"
> 
>     * imagemagick" -> ".png"
> 
>     * "jpeg" -> ".jpg"
> 
>     * magick++" -> ".gif"
> 
>     * "null" -> don't change extension
> 
>     * "null-tile" -> don't change extension
> 
>     * "png" -> ".png"
> 
>     * "png-spritesheet" -> ".png"
> 
>     * "ppm" -> ".ppm"
> 
>     * "yuv420p" -> ".yuv"

I assume you missed for **openxer -> ".exr"** and adding this also

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Please review the PR 😃
