### ISSUE TITLE
Feature request: Make delete key delete layers when I select one and push delete

### ISSUE THREAD

**Issue by RichardJECooke** [synfig/synfig#629]
**Synfig version & platform**:
1.2.2

**Issue description**:
Make delete key delete layers when I select one and push delete.
Having to move my mouse all the way down to each layer individually and right click, then select delete, then click it, is insanely tedious.

**Comment by ebarranco** [comment]
@RichardJECooke Select first element, press shift then select the last element. Then Ctrl+Del key.

**Comment by 9inpachi** [comment]
Is there a specific reason why the delete key alone is not made to work?
It would obviously be better if only the delete button does the work. Thats the convention either way.

**Comment by morevnaproject** [comment]
@9inpachi The problem is with how Synfig handles keyboard shortcuts. Enabling Delete key will make layers deleted, when user press Delete in text entry fields (i.e. when editing parameters).

See related issue - https://github.com/synfig/synfig/issues/257

**Comment by 9inpachi** [comment]
I see. Thanks for the clarification.
