### ISSUE TITLE
Bug (or documentation bug):  Scale and rotate tools do nothing

### ISSUE THREAD

**Issue by RichardJECooke** [synfig/synfig#630]
**Synfig version & platform**:
1.2.2 Windows 10 64

**Issue description**:
The scale and rotate tools in the toolbox don't work. Or at least I can't get them to do anything after following the 'getting started' tutorial and asking for help in the forum. They're also pointless afaik because objects already have handles to do those functions anyway.

So either the tools should be removed from the app or the docs must be updated to explain how they work. See here for details: https://forums.synfig.org/t/scale-rotate-tools-in-tutorial-do-nothing/8940

**Comment by morevnaproject** [comment]
Solved in https://forums.synfig.org/t/scale-rotate-tools-in-tutorial-do-nothing/8940/12?u=konstantindmitriev
