### ISSUE TITLE
Userfriendly numbers

### ISSUE THREAD

**Issue by wstaelens** [synfig/synfig#635]
**Synfig version & platform**:
Synfig 1.2.2 - Windows 10 x64 Pro v1803 (build 17134.285)

**Issue description**:

![synfig numbers](https://user-images.githubusercontent.com/7447285/46341939-d55ede80-c639-11e8-9bbe-84daf9faa0a3.PNG)

as you can see in the image a value like **-2.027e-006px** is very very annoying to use...

**Comment by morevnaproject** [comment]
Sample file attached - [e-bug.sifz.zip](https://github.com/synfig/synfig/files/2461383/e-bug.sifz.zip)

![screenshot_001](https://user-images.githubusercontent.com/332868/46684938-76433000-cc1e-11e8-92b6-b856951c6632.png)

**Comment by subhani92** [comment]
> value like -2.027e-006px is very very annoying to use

what do you expect in place of this?

**Comment by wstaelens** [comment]
@subhani92 something like -2.02, just "normal" float or double numbers, no scientific 'e' formatted numbers. You don't see this in Blender either.

**Comment by morevnaproject** [comment]
If I understand correctly,  "-2.027e-006" stands for "−2,027×e^(−6)":

![screenshot_001](https://user-images.githubusercontent.com/332868/46747880-89b4d080-ccdc-11e8-9af6-d7621c4d3a64.png)

**Comment by genete** [comment]
https://en.m.wikipedia.org/wiki/Scientific_notation

**Comment by wstaelens** [comment]
yeah, i'm not calculating at this moment ☕️ 
just wanted to say that users are not used to enter scientific notations, we just use floats/doubles. 😄

**Comment by morevnaproject** [comment]
@subhani92 Any progress on this? ^__^

**Comment by morevnaproject** [comment]
@subhani92 You probably want to look at this file - https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/widgets/widget_coloredit.cpp ^__^

**Comment by remyabel** [comment]
@subhani92 I don't know if you still had plans on working on it, but I've created a PR for it. It was a simple fix.

**Comment by wstaelens** [comment]
Great!
You can find more info about the formatters used in the fix on http://www.cplusplus.com/reference/cstdio/printf/

**Comment by rodolforg** [comment]
> If I understand correctly, "-2.027e-006" stands for "−2,027×e^(−6)":
> 
> ![screenshot_001](https://user-images.githubusercontent.com/332868/46747880-89b4d080-ccdc-11e8-9af6-d7621c4d3a64.png)

Actually, 1e2 means 1 x 10²

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
