### ISSUE TITLE
Allow to set default canvas background

### ISSUE THREAD

**Issue by wstaelens** [synfig/synfig#636]
**Synfig version & platform**:
Synfig 1.2.2 - Windows 10 x64 Pro

**Issue description**:

It would be great to let us set a default background in the Canvas Properties.
Now you see by default a transparent checker background, and when previewing/rendering it is set to gray.

allow us to set a default "world" or "scene" background as in Blender.

**Comment by morevnaproject** [comment]
You can simply drag-n-drop any image file to Synfig workarea from file manager and then place it below all layers.

**Comment by wstaelens** [comment]
Yes I know, but this feels like a "hack" and clutters up the workspace layers.
Just setting a default background color for the canvas in the properties would be great. If you still want to use a background image or rectangle you would just set it as transparent...

**Comment by BobSynfig** [comment]
Hi,
I added some options for backgrounds:
**Selection of Preview Background Color (Render page)**
![image](https://user-images.githubusercontent.com/45494804/50448876-f9257e00-0923-11e9-9796-b7ffbd135db3.png)
![image](https://user-images.githubusercontent.com/45494804/50448879-004c8c00-0924-11e9-87f5-16314d952f52.png)

**Add automatically a default background layer on new animation (Document page)**
* None
* Solid Color
* Image - Scale to fit canvas depend on the option in Editing page

These layers will be named "Background"
![image](https://user-images.githubusercontent.com/45494804/50448865-e90d9e80-0923-11e9-9d18-d20913c27797.png)

Cheers :)

**Comment by Jose-Moreno** [comment]
@BobSynfig Hey that's awesome! Every contribution counts. I wish I knew how to properly develop software with C++ to help as well, but it's great to see more people adding more "quality-of-life" options :slightly_smiling_face:

**Comment by morevnaproject** [comment]
@BobSynfig Thank you very much for this improvement, I really like the solution!

#690 is merged now.
