### ISSUE TITLE
Preview options - quality value

### ISSUE THREAD

**Issue by wstaelens** [synfig/synfig#638]
**Synfig version & platform**:
Synfig 1.2.2 - Windows 10 Pro x64

**Issue description**:

Quality value is unclear: 1,00
would a slider not be better? what is maximum? 2? 10? 100? 1? what is minimum? 
it is not clear for a user!

![synfig quality](https://user-images.githubusercontent.com/7447285/46347027-6c339700-c64a-11e8-9a5b-0f14ae198d06.png)

Also add ':' after each label, like:  '**Quality:**'

**Comment by morevnaproject** [comment]
Quality is a size scale, comparing to current dimensions of your composition.
I.e., if you have composition at 480x270, then 1.0 means rendering at the same dimensions, 0.5 - twice smaller (240x135), 2.0 - twice bigger (960x540).

**Comment by Keyikedalube** [comment]
> would a slider not be better? what is maximum? 2? 10? 100? 1? what is minimum?

That'll break UI consistency. I like the current dialog.

> Also add ':' after each label, like: '**Quality:**'

Using colon is not really necessary but GNOME HIG provides a very good practical guideline on how UI can look better to end-users
https://developer-old.gnome.org/hig/stable/visual-layout.html.en

**Comment by rodolforg** [comment]
Anyway, "quality" parameter is for old renderer.
When we have all layers ported to Cobra, we can remove it.

**Comment by Keyikedalube** [comment]
Closing this. Explained above by @rodolforg.
