### ISSUE TITLE
Question about versioning policy

### ISSUE THREAD

**Issue by newbluemoon** [synfig/synfig#642]
The 1.3.* versions of synfigstudio are marked as development versions. My question is if the policy on this is uneven --> development, even --> stable or can a future 1.3.x version become the next stable one?

The reason I’m asking is because I packaged synfigstudio for Void Linux and the general policy there is to only update to stable versions. So I would like to know if I can ignore the 1.3.* versions when doing an automatic update-check or if this is a bad idea.

**Comment by morevnaproject** [comment]
Hello @newbluemoon! I am happy to hear you've got interested to package Synfig for Void Linux. ^__^

Yes, uneven numbers are development versions. So, 1.3.x (unstable) contains changes that will be shipped with 1.4.x (stable). Also, sometimes changes from unstable get backported to previous stable (1.2.x).

So, yes -  you can ignore 1.3.x versions.

**Comment by newbluemoon** [comment]
Thank you for the detailed explanation! :)
It’s a really nice piece of software, if I just had more time... ;)
