### ISSUE TITLE
Shortcut Keys + Click to Add New Vertex Point in Vector Shapes (Outlines and Regions)

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#643]
**Feature Requests for Future Versions**

**Feature description**:
Simple, just some shortcut keys for "Insert Item" and "Insert Item and keep shape"
So it's like holding certain keys and clicking on area's outlines (those faint dotted lines when selecting shapes) then the vertex point can be created

**Comment by morevnaproject** [comment]
Resolved in Synfig version 1.5.1 - https://www.synfig.org/2021/10/30/synfig-studio-1-5-1-released/
