### ISSUE TITLE
Feature to Select All Layers of the Whole Canvas Directly (Including Their Child Layers)

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#644]
**Feature Requests for Future Versions**

**Feature description:**:
As for now, this cannot be done unless the whole canvas content is grouped to a single group, and then use the "Select all child layers" option
Probably an option to do it without the grouping technique would be slightly better...

**Comment by Keyikedalube** [comment]
`Ctrl + Shift + A`?
