### ISSUE TITLE
GUI: Play a sound when rendering is done

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#648]
Feature request from user: It'll be great if @Synfig played a chime when the render is done (so you can mind something else while waiting).

**Comment by morevnaproject** [comment]
@BobSynfig Awesome! Can you please submit pull request for your changes? ^__^

**Comment by morevnaproject** [comment]
@BobSynfig  Tested and merged! Thank you!

**Comment by morevnaproject** [comment]
I think, we still need a GUI option to enable/disable that function.

**Comment by BobSynfig** [comment]
Ready ^_^
https://github.com/synfig/synfig/pull/688

**Comment by morevnaproject** [comment]
@BobSynfig Thank you! Congratulations with your first issue completed! ^__^
