### ISSUE TITLE
Combobox initial dropdown state

### ISSUE THREAD

**Issue by wstaelens** [synfig/synfig#650]
**Synfig version & platform**:
SF 1.2.2
Windows 10 x64 Pro

**Issue description**:

![synfig white combo](https://user-images.githubusercontent.com/7447285/47138669-5664d980-d2ba-11e8-982e-b37a4029e13f.png)

first time i see a lot of white when opening. the items should be starting on top...

**Comment by ice0** [comment]
This is a known GTK+ combobox problem (discussed here https://bugs.launchpad.net/ubuntu/+source/gtk+2.0/+bug/388633), so i am not sure it can be fixed at this time.

**Comment by wstaelens** [comment]
Time to move to .NET Standard/.NET Core ? ;-) ;-)
Hope to see it soon fixed, as this is really a basic control.... Not expecting to still see such bugs in GTK+...

**Comment by ice0** [comment]
As a workaround, we can move the default value to the bottom of the list. @morevnaproject, what do you think?

**Comment by wstaelens** [comment]
I think it would be better to bomb that gitlab bug ticket so that it gets some attention and hopefully a fix.

**Comment by morevnaproject** [comment]
Interesting information from http://libregraphicsworld.org/blog/entry/week-recap-23-december-2018 -

> Kevin Stoffler contributed a patch that works around the design decision of GTK+ developers regarding drop-down lists. Instead of always showing the currently selected item of a drop-down list under the cursor (at the cost of showing a lot of blank space above), GIMP now renders the whole list in a much nicer way (while losing the item selection). The patch was applied to both unit selection and blend mode selection. Smaller UX changes involve things like keeping aspect by default when scaling with the Unified Transform tool.

**Comment by morevnaproject** [comment]
https://twitter.com/GIMP_Official/status/1075541003468267520

**Comment by morevnaproject** [comment]
Related commit - https://gitlab.gnome.org/GNOME/gimp/commit/a9a979b2d0a9a3ef25d63c90a1401994cca2a818

**Comment by BobSynfig** [comment]
Test done ok

Add this line in _/synfig-studio/src/gui/widgets/widget_enum.cpp_ (line 65)
>this->set_wrap_width(1); //#650

As a result, depending the size and the position of the window, the default value may not be selected by default.

![650](https://user-images.githubusercontent.com/45494804/50453303-ee78e200-093f-11e9-8959-5286753e804d.png)

**Comment by morevnaproject** [comment]
The change is applied now. Thanks to everyone for participation!
