### ISSUE TITLE
APPCRASH

### ISSUE THREAD

**Issue by wstaelens** [synfig/synfig#651]
**Synfig version & platform**:
sf 1.2.2
windows 10 x64

**Issue description**:

several crashes while working. Synfig just closes. can't find log file of synfig.

Faulting application name: synfigstudio.exe, version: 0.0.0.0, time stamp: 0x5b9bace4
Faulting module name: KERNELBASE.dll, version: 10.0.17134.319, time stamp: 0x1e206b26
Exception code: 0x80000003
Fault offset: 0x00000000000ac5d2
Faulting process id: 0x43cc
Faulting application start time: 0x01d466c845a0c4bf
Faulting application path: C:\Program Files\Synfig\bin\synfigstudio.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 53b30066-3e79-4119-9dd3-88696d33d9db
Faulting package full name: 
Faulting package-relative application ID: 

The program synfigstudio.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 60a0
 Start Time: 01d466c4c5df489b
 Termination Time: 4294967295
 Application Path: C:\Program Files\Synfig\bin\synfigstudio.exe
 Report Id: 09c40e17-61c4-401e-818d-85f27b9aea40
 Faulting package full name: 
 Faulting package-relative application ID: 

Faulting application name: synfigstudio.exe, version: 0.0.0.0, time stamp: 0x5b9bace4
Faulting module name: libgdk-3-0.dll, version: 3.22.12.0, time stamp: 0x5a3cf875
Exception code: 0xc0000005
Fault offset: 0x000000000002a290
Faulting process id: 0x5478
Faulting application start time: 0x01d466bf0c9b9afd
Faulting application path: C:\Program Files\Synfig\bin\synfigstudio.exe
Faulting module path: C:\Program Files\Synfig\bin\libgdk-3-0.dll
Report Id: b1f10721-a87a-4692-a0fe-c1f44ee9a787
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: synfigstudio.exe, version: 0.0.0.0, time stamp: 0x5b9bace4
Faulting module name: libgdk-3-0.dll, version: 3.22.12.0, time stamp: 0x5a3cf875
Exception code: 0xc0000005
Fault offset: 0x000000000002a1de
Faulting process id: 0x6cec
Faulting application start time: 0x01d466b2a6f41799
Faulting application path: C:\Program Files\Synfig\bin\synfigstudio.exe
Faulting module path: C:\Program Files\Synfig\bin\libgdk-3-0.dll
Report Id: cfd6d306-cdf2-40cf-b5e3-227113c7c3e2
Faulting package full name: 
Faulting package-relative application ID:

**Comment by morevnaproject** [comment]
Can you please provide information which actions you did just before Synfig crashes, so we can reproduce this?

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by wstaelens** [comment]
I can't reproduce nor remember what exactly I did.
I was moving objects and animating them (alpha amount).

I remember I had an existing animation and removed a keyframe that had waypoints and that it crashed.

i'll try to see if I can find some more info on how to reproduce but till now it didn't happen.

**Comment by Keyikedalube** [comment]
Closing this because v1.2.2 is old and also due to inactivity.

Feel free to reopen if you guys need this resolved.
