### ISSUE TITLE
bool values inconvenient interpolation

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#658]
**Synfig version & platform**:
1.3.10

**Issue description**:
Values of type "bool" seem to be inconveniently interpolated, as in, to be "false" it takes BOTH the previous and the next waypoint to be false, forcing you to use 2 waypoints to switch value.
This could be interpreted as "false waypoint=0, true waypoint=1, anything > 0 is interpreted as true", but this behavior is retained even when "constant" interpolation is used.

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.
