### ISSUE TITLE
in "convert to time loop", link time cannot be set to zero

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#659]
**Synfig version & platform**:
1.3.10

**Issue description**:
Convert anything to "time loop", set "link time" to anything other than 0, then try to set it back to zero ; nothing happens, the old value is kept.
I'm pretty sure I have seen something like this happen with other values.

**Comment by BobSynfig** [comment]
Related to https://github.com/synfig/synfig/issues/520 and https://github.com/synfig/synfig/issues/526

According my tests,
when 2 or more parameters
of the same type
follow in the list
if you try to edit a parameter 
with the same value
as the one placed under,
it can't be changed.

For example:
* Time Loop has _Link Time_, _Local Time_ and _Duration_ as _Time_
* Circle has _Z Depth_ and _Amount_ as _Real_
* Star has 
_Z Depth_ and _Amount_ as _Real_
_Type of Feather_ and _Winding Style_ as _Integer_ (Combo Enum)
_Outer Radius_ and _Inner Radius_ as _Real_

It bugs in any case, red error messages appear in console.
Surely a missing reinitialisation in [cellrenderer_value.cpp](https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp) or [widget_value.cpp](https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/widgets/widget_value.cpp) in case of no change of type

_Also note that Synfig often crashes after such error!_

**Comment by BobSynfig** [comment]
So, when the edition of parameter has been done, the new value is compared with the former one.
For some reason, it uses _property_value()_ which doesn't give the original one, which was used in the beginning to define the content of the edit box!
I did a copy of these original data in a _synfig::ValueBase saved_data_ which I will use for the final compare ;)

Note that modify _Z Order_ will still lead to crash like in 1.2.2
For the rest, everything can be modified as expected now :)
https://github.com/synfig/synfig/pull/691

**Comment by morevnaproject** [comment]
Much thanks to @BobSynfig  - seems like it is fixed now! Will be shipped with version 1.3.11. Still we ask for your testing.
