### ISSUE TITLE
Incorrect GUI font rendering

### ISSUE THREAD

**Issue by diman8** [synfig/synfig#667]
**Synfig version & platform**:
1.2.2
Windows 10 Home (1803) (Default language: English)

**Issue description**:
After installing GUI font is rendering with strange symbols rather than letters.
![1](https://user-images.githubusercontent.com/18375462/48189187-a6324000-e350-11e8-9375-51e85776f8be.png)
![2](https://user-images.githubusercontent.com/18375462/48189188-a6324000-e350-11e8-9314-3f2f2d740c3e.png)

After switching language to English this issue is almost gone (only title name of the file is corrupt).
![3](https://user-images.githubusercontent.com/18375462/48189193-a9c5c700-e350-11e8-8d8d-8bb781780674.png)

**Comment by ice0** [comment]
Hi! Which version of Synfig you are using (32/64)?
Can you run Synfig Studio (Debug Console) and show it's output?

**Comment by Tiromh** [comment]
Hi ! Same issue !

Synfig Studio -- dÃ©marrage de l'application...

synfig(11004) [11:39:07] info: DÃ©marrage du sous systÃ¨me "Sound"
synfig(11004) [11:39:07] info: DÃ©marrage du sous systÃ¨me "Types"
synfig(11004) [11:39:07] info: Starting Subsystem "Rendering"
synfig(11004) [11:39:07] info: rendering threads 12
synfig(11004) [11:39:07] info: DÃ©marrage du sous-systÃ¨me "Modules"
synfig(11004) [11:39:07] info: DÃ©marrage du sous-systÃ¨me "Layers"
synfig(11004) [11:39:07] info: DÃ©marrage du sous-systÃ¨me "Targets"
synfig(11004) [11:39:08] info: DÃ©marrage du sous-systÃ¨me "Importers"
synfig(11004) [11:39:08] info: DÃ©marrage du sous systÃ¨me "Cairo Importers"
#[33msynfig(11004) [11:39:08] avertissement: Cannot open ./synfig_modules.cfg#[0m
#[33msynfig(11004) [11:39:08] avertissement: Cannot open /build/packet/win-64/synfigcore-master/install/etc/synfig_modules.cfg#[0m
synfig(11004) [11:39:08] info: Chargement des modules depuis C:\Program Files\Synfig/etc/synfig_modules.cfg
synfig(11004) [11:39:08] info: Chargement des modules depuis C:\Program Files\Synfig/etc/synfig_modules.cfg
synfig(11004) [11:39:08] info: Loading lyr_std..
synfig(11004) [11:39:08] info: Tentative d'enregistrement de "lyr_std"
synfig(11004) [11:39:08] info: Module "lyr_std" trouvÃ©
synfig(11004) [11:39:08] info: SuccÃ¨s pour "lyr_std"
synfig(11004) [11:39:08] info: Loading lyr_freetype..
synfig(11004) [11:39:08] info: Tentative d'enregistrement de "lyr_freetype"
synfig(11004) [11:39:08] info: Module "lyr_freetype" trouvÃ©
synfig(11004) [11:39:08] info: Initializing FreeType...
synfig(11004) [11:39:08] info: SuccÃ¨s pour "lyr_freetype"
synfig(11004) [11:39:08] info: Loading mod_geometry..
synfig(11004) [11:39:08] info: Tentative d'enregistrement de "mod_geometry"
synfig(11004) [11:39:08] info: Module "mod_geometry" trouvÃ©
synfig(11004) [11:39:08] info: SuccÃ¨s pour "mod_geometry"
synfig(11004) [11:39:08] info: Loading mod_gradient..
synfig(11004) [11:39:08] info: Tentative d'enregistrement de "mod_gradient"
synfig(11004) [11:39:08] info: Module "mod_gradient" trouvÃ©
synfig(11004) [11:39:08] info: SuccÃ¨s pour "mod_gradient"
synfig(11004) [11:39:08] info: Loading mod_particle..
synfig(11004) [11:39:08] info: Tentative d'enregistrement de "mod_particle"
synfig(11004) [11:39:08] info: Module "mod_particle" trouvÃ©
synfig(11004) [11:39:08] info: SuccÃ¨s pour "mod_particle"
synfig(11004) [11:39:08] info: Loading mod_example..
synfig(11004) [11:39:08] info: Tentative d'enregistrement de "mod_example"
synfig(11004) [11:39:08] info: Module "mod_example" trouvÃ©
synfig(11004) [11:39:08] info: SuccÃ¨s pour "mod_example"
synfig(11004) [11:39:08] info: Loading mod_gif..
synfig(11004) [11:39:08] info: Tentative d'enregistrement de "mod_gif"
synfig(11004) [11:39:08] info: Module "mod_gif" trouvÃ©
synfig(11004) [11:39:09] info: SuccÃ¨s pour "mod_gif"
synfig(11004) [11:39:09] info: Loading mod_imagemagick..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_imagemagick"
#[33msynfig(11004) [11:39:09] avertissement: Impossible de trouver le module "mod_imagemagick" (Le module spécifié est introuvable.)#[0m

(synfigstudio.exe:11004): Pango-#[1;33mWARNING#[0m **: Invalid UTF-8 string passed to pango_layout_set_text()
synfig(11004) [11:39:09] info: Loading mod_magickpp..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_magickpp"
synfig(11004) [11:39:09] info: Module "mod_magickpp" trouvÃ©
synfig(11004) [11:39:09] info: SuccÃ¨s pour "mod_magickpp"
synfig(11004) [11:39:09] info: Loading mod_mng..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_mng"
#[33msynfig(11004) [11:39:09] avertissement: Impossible de trouver le module "mod_mng" (Le module spécifié est introuvable.)#[0m

(synfigstudio.exe:11004): Pango-#[1;33mWARNING#[0m **: Invalid UTF-8 string passed to pango_layout_set_text()
synfig(11004) [11:39:09] info: Loading mod_noise..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_noise"
synfig(11004) [11:39:09] info: Module "mod_noise" trouvÃ©
synfig(11004) [11:39:09] info: SuccÃ¨s pour "mod_noise"
synfig(11004) [11:39:09] info: Loading mod_filter..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_filter"
synfig(11004) [11:39:09] info: Module "mod_filter" trouvÃ©
synfig(11004) [11:39:09] info: SuccÃ¨s pour "mod_filter"
synfig(11004) [11:39:09] info: Loading mod_ffmpeg..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_ffmpeg"
synfig(11004) [11:39:09] info: Module "mod_ffmpeg" trouvÃ©
synfig(11004) [11:39:09] info: SuccÃ¨s pour "mod_ffmpeg"
synfig(11004) [11:39:09] info: Loading mod_bmp..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_bmp"
synfig(11004) [11:39:09] info: Module "mod_bmp" trouvÃ©
synfig(11004) [11:39:09] info: SuccÃ¨s pour "mod_bmp"
synfig(11004) [11:39:09] info: Loading mod_dv..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_dv"
synfig(11004) [11:39:09] info: Module "mod_dv" trouvÃ©
synfig(11004) [11:39:09] info: SuccÃ¨s pour "mod_dv"
synfig(11004) [11:39:09] info: Loading mod_png..
synfig(11004) [11:39:09] info: Tentative d'enregistrement de "mod_png"
synfig(11004) [11:39:10] info: Module "mod_png" trouvÃ©
synfig(11004) [11:39:10] info: SuccÃ¨s pour "mod_png"
synfig(11004) [11:39:10] info: Loading mod_ppm..
synfig(11004) [11:39:10] info: Tentative d'enregistrement de "mod_ppm"
synfig(11004) [11:39:10] info: Module "mod_ppm" trouvÃ©
synfig(11004) [11:39:10] info: SuccÃ¨s pour "mod_ppm"
synfig(11004) [11:39:10] info: Loading mod_openexr..
synfig(11004) [11:39:10] info: Tentative d'enregistrement de "mod_openexr"
#[33msynfig(11004) [11:39:10] avertissement: Impossible de trouver le module "mod_openexr" (Le module spécifié est introuvable.)#[0m

(synfigstudio.exe:11004): Pango-#[1;33mWARNING#[0m **: Invalid UTF-8 string passed to pango_layout_set_text()
synfig(11004) [11:39:10] info: Loading mod_jpeg..
synfig(11004) [11:39:10] info: Tentative d'enregistrement de "mod_jpeg"
synfig(11004) [11:39:10] info: Module "mod_jpeg" trouvÃ©
synfig(11004) [11:39:10] info: SuccÃ¨s pour "mod_jpeg"
synfig(11004) [11:39:10] info: Loading mod_libavcodec..
synfig(11004) [11:39:10] info: Tentative d'enregistrement de "mod_libavcodec"
#[33msynfig(11004) [11:39:10] avertissement: Impossible de trouver le module "mod_libavcodec" (Le module spécifié est introuvable.)#[0m

(synfigstudio.exe:11004): Pango-#[1;33mWARNING#[0m **: Invalid UTF-8 string passed to pango_layout_set_text()
synfig(11004) [11:39:10] info: Loading mod_yuv420p..
synfig(11004) [11:39:10] info: Tentative d'enregistrement de "mod_yuv420p"
synfig(11004) [11:39:10] info: Module "mod_yuv420p" trouvÃ©
synfig(11004) [11:39:10] info: SuccÃ¨s pour "mod_yuv420p"
synfig(11004) [11:39:10] info: Loading mod_svg..
synfig(11004) [11:39:10] info: Tentative d'enregistrement de "mod_svg"
synfig(11004) [11:39:10] info: Module "mod_svg" trouvÃ©
synfig(11004) [11:39:10] info: SuccÃ¨s pour "mod_svg"
synfig(11004) [11:39:10] info: FINI
synfig(11004) [11:39:10] info: Chargement de la Configuration Basique...
synfig(11004) [11:39:10] info: Chargement des Modules...
synfig(11004) [11:39:10] info: Loading plugins from C:/Program Files/Synfig/share\synfig\plugins
synfig(11004) [11:39:10] info:    Loading plugin: add-skeleton-simple
synfig(11004) [11:39:10] info:    Loading plugin: view-unhide-all-layers
synfig(11004) [11:39:10] info: Loading plugins from C:\Users\romai/Synfig\plugins
synfig(11004) [11:39:10] info: Initialisation du Gestionnaire d'Interface..
synfig(11004) [11:39:11] info: Initialisation du Gestionnaire d'Onglet..
synfig(11004) [11:39:11] info: Initialisation du Gestionnaire d'Ã%tat...
synfig(11004) [11:39:11] info: Initialisation de la FenÃªtre Principale...
synfig(11004) [11:39:11] info: Initialisation de la BoÃ®te Ã  Outils...
synfig(11004) [11:39:11] info: Initialisation du Dialogue "Ã  propos"...
synfig(11004) [11:39:11] info: Initialisation des Options des Outils...
synfig(11004) [11:39:11] info: Initialisation de l'Historique...
synfig(11004) [11:39:11] info: Initialisation des Canevas...
synfig(11004) [11:39:11] info: Initialisation des Images ClÃ©s...
synfig(11004) [11:39:11] info: Initialisation des Calques...
synfig(11004) [11:39:11] info: Initialisation des ParamÃ¨tres...
synfig(11004) [11:39:11] info: Initialisation des MÃ©tadonnÃ©es...
synfig(11004) [11:39:11] info: Initialisation de la BibliothÃ¨que...
synfig(11004) [11:39:11] info: Initialisation du Dialogue d'Info...
synfig(11004) [11:39:11] info: Initialisation du Navigateur...
synfig(11004) [11:39:11] info: Initialisation de l'Axe de Temps...
synfig(11004) [11:39:11] info: Initialisation de l'Ã%diteur de Courbes...
synfig(11004) [11:39:11] info: Initialisation Lots de Calques....
synfig(11004) [11:39:11] info: Initialisation du Dialogue de Couleur...
synfig(11004) [11:39:11] info: Initialisation du Dialogue de DÃ©gradÃ©...
synfig(11004) [11:39:11] info: Initialisation du Traqueur de PÃ©riphÃ©riques...
synfig(11004) [11:39:11] info: Initialisation de ModPalette
synfig(11004) [11:39:11] info: Initialisation du Dialogue de Configuration...
synfig(11004) [11:39:11] info: Initialisation du Dialogue d'EntrÃ©e...
synfig(11004) [11:39:11] info: Initialisation de l'auto-restauration...
synfig(11004) [11:39:11] info: Chargement de la Configuration...
synfig(11004) [11:39:12] info: Initialisation des Outils...
synfig(11004) [11:39:12] info: VÃ©rification de l'auto-restauration...
synfig(11004) [11:39:13] info: Fini.

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: Could not find the icon 'missing-image-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: Allocating size to gtkmm__GtkNotebook 000000000CB45720 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: drawing failure for widget 'gtkmm__GtkWindow': cairo_restore() without matching cairo_save()

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: Allocating size to gtkmm__GtkNotebook 000000000CB45720 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: drawing failure for widget 'gtkmm__GtkWindow': cairo_restore() without matching cairo_save()

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: drawing failure for widget 'gtkmm__GtkWindow': cairo_restore() without matching cairo_save()

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: Allocating size to gtkmm__GtkNotebook 000000000CB45720 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: drawing failure for widget 'gtkmm__GtkWindow': cairo_restore() without matching cairo_save()

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: Allocating size to gtkmm__GtkNotebook 000000000CB45720 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(synfigstudio.exe:11004): Gtk-#[1;33mWARNING#[0m **: drawing failure for widget 'gtkmm__GtkWindow': cairo_restore() without matching cairo_save()

**Comment by Tiromh** [comment]
SynfigStudio-1.2.2-18.09.14-win64-286f1

**Comment by BobSynfig** [comment]
Just had the opportunity to install it on a Win10 Home french edition, same as @Tiromh.
Same version of Synfig setup (as .exe and .zip).
I don't have any display error in Synfig, the same artifacts in console nevertheless...
I also checked after install fonts [droid-sans](https://www.fontsquirrel.com/fonts/droid-sans) missing on the system.
But everything is fine!

**Comment by Tiromh** [comment]
Not for me :'(

**Comment by BobSynfig** [comment]
I found there are some incompatibilities with Droid font family (not available in all the languages).

Please edit _c:\Program Files\Synfig\etc\gtk-3.0\settings.ini_ with _Notepad++_ (the file has Linux LF end of lines)

Replace `gtk-font-name = Droid Sans 8`
with `gtk-font-name = Sans 8`

Also be sure of your settings in Control Panel / Region / Administration, button Modify:
Set the non-unicode support to your own language and UNCHECK beta support for unicode UTF-8
You will have to restart your computer after this operation

Then restart Synfig

Please test and report

**Comment by Tiromh** [comment]
Whouaaaa :)

it's work :)

just not : c:\Program Files\Synfig\etc\gtk-3.0\
but : C:\Program Files\Synfig\share\gtk-3.0\

Thanks a lot :)

**Comment by BobSynfig** [comment]
@Tiromh Thank you for your quick test!
@morevnaproject 
We should use a different font 
It was a bit my fault if it had been included in Synfig :smile: 
https://forums.synfig.org/t/change-synfig-gui-font-in-win-8-1-dpi-related/3730

**Comment by Tiromh** [comment]
Bravo!, Well done!, Attaboy! ;)

thanks for your quick tips and to have solved my problem

now i can get started :)

**Comment by BobSynfig** [comment]
@morevnaproject:
This should be modified in the build script
https://github.com/morevnaproject/morevna-builds/blob/master/docker-builder-data/build/script/packet/synfigstudio-master.files/settings.ini

**Comment by morevnaproject** [comment]
@BobSynfig Oh, I completely forgot that we have settings file duplicated in this repo. Fixed now. Thank you so much!

**Comment by morevnaproject** [comment]
Ok, I just have eliminated the duplication of settings.ini. Now it is in synfig's source only.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Closing this one!

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Thank you! ^__^

**Comment by jozsefk9** [comment]
How do you do this in Linux?

**Comment by rodolforg** [comment]
@jozsefk9  Are you using new stable version 1.4.0?
No fix was done for 1.2.x

**Comment by jozsefk9** [comment]
@rodolforg Now I got the stable version 1.4.0 and the fonts in the menu and everywhere is weird. System is Kubuntu 20.04 64bit. Can't find a way to change the interface font.
![synfig](https://user-images.githubusercontent.com/1645288/103446271-06497600-4c7e-11eb-9b77-4e16579fd0a3.png)

**Comment by rodolforg** [comment]
Actually, I don't know how to deal with appimage. =/
@morevnaproject @BobSynfig @ice0

**Comment by ice0** [comment]
@jozsefk9 can you check if problem exist in updated builds?

- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux64-a2ca6.appimage
- https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux32-a2ca6.appimage

**Comment by jozsefk9** [comment]
> @jozsefk9 can you check if problem exist in updated builds?
> 
> * https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux64-a2ca6.appimage
> * https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2020.12.01-linux32-a2ca6.appimage

@ice0 That worked! Thank you!
