### ISSUE TITLE
synfig-1.2.2 and openexr-2.3.0 --with-half

### ISSUE THREAD

**Issue by stumbles** [synfig/synfig#670]
**Synfig version & platform**:

synfig-1.2.2

**Issue description**:
First I spent way to much time trying to get synfig to just build with openexr-2.3.0. The I finally noticed configure was looking for OpenEXR.pc. Well, current openexr only has /usr/lib/pkgconfig/IlmBase.pc. Once I created a symlink, synfig finally used it during the build using --with-openexr.

Now to the problem.

When using --with-openexr and --enable-half the build fails with;

libtool: compile:  g++ -DHAVE_CONFIG_H -I../.. -I../../src -D_FORTIFY_SOURCE=2 -I/usr/include --std=c++11 -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread-I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid --std=c++11 -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/libxml++-2.6 -I/usr/lib/libxml++-2.6/include -I/usr/include/libxml2 --std=c++11 -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/ImageMagick-6 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=32 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1-I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/mlt++ -I/usr/include/mlt -D_REENTRANT-I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -DUSE_HALF_TYPE -DSYNFIG_NO_DEPRECATED -DLOCALEDIR=\"/usr/share/locale\" -DLIBDIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -march=x86-64 -pipe -std=c++11 -O2 -DNDEBUG -W -Wall -MT libsynfig_la-gradient.lo -MD -MP -MF .deps/libsynfig_la-gradient.Tpo -c gradient.cpp  -fPIC -DPIC -o .libs/libsynfig_la-gradient.o
In file included from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.h:104:21: error: 'ColorAccumulator' does not name a type
inline Color(const ColorAccumulator& c);
^~~~~~~~~~~~~~~~
In file included from ../../src/synfig/color/color.h:369,
from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.hpp:170:2: error: 'friend' used outside of class
friend class ColorAccumulator;
^~~~~~
------
../../src/synfig/color/color.hpp:172:8: error: expected unqualified-id before 'const'
Color(const ColorAccumulator& c);
^~~~~
../../src/synfig/color/color.hpp:172:8: error: expected ')' before 'const'
Color(const ColorAccumulator& c);
~^~~~~
)
In file included from color.h:59,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/coloraccumulator.h: In member function 'synfig::ColorAccumulator synfig::ColorAccumulator::operator+(const synfig::ColorAccumulator&) const':
../../src/synfig/color/coloraccumulator.h:87:22: error: no matching function for call to 'synfig::Color::Color(const synfig::ColorAccumulator&)'
{ return Color(*this)+=rhs; }
^
In file included from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.h:104:9: note: candidate: 'synfig::Color::Color(const int&)'
inline Color(const ColorAccumulator& c);
^~~~~
../../src/synfig/color/color.h:104:9: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'constint&'
In file included from gradient.h:32,
from gradient.cpp:33:
color.h:38:8: note: candidate: 'synfig::Color::Color(const synfig::CairoColor&)'
inline Color::Color(const CairoColor& c)
^~~~~
color.h:38:8: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::CairoColor&'
In file included from ../../src/synfig/color/color.h:369,
from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.hpp:163:1: note: candidate: 'synfig::Color::Color(const synfig::Color&)'
Color::Color(const Color& c):
^~~~~
../../src/synfig/color/color.hpp:163:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::Color&'
../../src/synfig/color/color.hpp:157:1: note: candidate: 'synfig::Color::Color(const synfig::Color&, const value_type&)'
Color::Color(const Color& c, const value_type& A):
^~~~~
../../src/synfig/color/color.hpp:157:1: note:   candidate expects 2 arguments, 1 provided
../../src/synfig/color/color.hpp:148:1: note: candidate: 'synfig::Color::Color(const value_type&, const value_type&, const value_type&, const value_type&)'
Color::Color(const value_type& R,
^~~~~
../../src/synfig/color/color.hpp:148:1: note:   candidate expects 4 arguments, 1 provided
../../src/synfig/color/color.hpp:146:1: note: candidate: 'synfig::Color::Color(int)'
Color::Color(int f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:146:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'int'
../../src/synfig/color/color.hpp:145:1: note: candidate: 'synfig::Color::Color(const value_type&)'
Color::Color(const value_type &f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:145:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const value_type&' {aka 'const half&'}
../../src/synfig/color/color.hpp:144:1: note: candidate: 'synfig::Color::Color()'
Color::Color() :r_(0), g_(0), b_(0),a_(0) { }
^~~~~
../../src/synfig/color/color.hpp:144:1: note:   candidate expects 0 arguments, 1 provided
In file included from color.h:59,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/coloraccumulator.h: In member function 'synfig::ColorAccumulator synfig::ColorAccumulator::operator-(const synfig::ColorAccumulator&) const':
../../src/synfig/color/coloraccumulator.h:91:22: error: no matching function for call to 'synfig::Color::Color(const synfig::ColorAccumulator&)'
{ return Color(*this)-=rhs; }
^
In file included from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.h:104:9: note: candidate: 'synfig::Color::Color(const int&)'
inline Color(const ColorAccumulator& c);
^~~~~
../../src/synfig/color/color.h:104:9: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'constint&'
In file included from gradient.h:32,
from gradient.cpp:33:
color.h:38:8: note: candidate: 'synfig::Color::Color(const synfig::CairoColor&)'
inline Color::Color(const CairoColor& c)
^~~~~
color.h:38:8: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::CairoColor&'
In file included from ../../src/synfig/color/color.h:369,
from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.hpp:163:1: note: candidate: 'synfig::Color::Color(const synfig::Color&)'
Color::Color(const Color& c):
^~~~~
../../src/synfig/color/color.hpp:163:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::Color&'
../../src/synfig/color/color.hpp:157:1: note: candidate: 'synfig::Color::Color(const synfig::Color&, const value_type&)'
Color::Color(const Color& c, const value_type& A):
^~~~~
../../src/synfig/color/color.hpp:157:1: note:   candidate expects 2 arguments, 1 provided
../../src/synfig/color/color.hpp:148:1: note: candidate: 'synfig::Color::Color(const value_type&, const value_type&, const value_type&, const value_type&)'
Color::Color(const value_type& R,
^~~~~
../../src/synfig/color/color.hpp:148:1: note:   candidate expects 4 arguments, 1 provided
../../src/synfig/color/color.hpp:146:1: note: candidate: 'synfig::Color::Color(int)'
Color::Color(int f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:146:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'int'
../../src/synfig/color/color.hpp:145:1: note: candidate: 'synfig::Color::Color(const value_type&)'
Color::Color(const value_type &f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:145:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const value_type&' {aka 'const half&'}
../../src/synfig/color/color.hpp:144:1: note: candidate: 'synfig::Color::Color()'
Color::Color() :r_(0), g_(0), b_(0),a_(0) { }
^~~~~
../../src/synfig/color/color.hpp:144:1: note:   candidate expects 0 arguments, 1 provided
In file included from color.h:59,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/coloraccumulator.h: In member function 'synfig::ColorAccumulator synfig::ColorAccumulator::operator*(const float&) const':
../../src/synfig/color/coloraccumulator.h:95:22: error: no matching function for call to 'synfig::Color::Color(const synfig::ColorAccumulator&)'
{ return Color(*this)*=rhs; }
^
In file included from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.h:104:9: note: candidate: 'synfig::Color::Color(const int&)'
inline Color(const ColorAccumulator& c);
^~~~~
../../src/synfig/color/color.h:104:9: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'constint&'
In file included from gradient.h:32,
from gradient.cpp:33:
color.h:38:8: note: candidate: 'synfig::Color::Color(const synfig::CairoColor&)'
inline Color::Color(const CairoColor& c)
^~~~~
color.h:38:8: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::CairoColor&'
In file included from ../../src/synfig/color/color.h:369,
from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.hpp:163:1: note: candidate: 'synfig::Color::Color(const synfig::Color&)'
Color::Color(const Color& c):
^~~~~
../../src/synfig/color/color.hpp:163:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::Color&'
../../src/synfig/color/color.hpp:157:1: note: candidate: 'synfig::Color::Color(const synfig::Color&, const value_type&)'
Color::Color(const Color& c, const value_type& A):
^~~~~
../../src/synfig/color/color.hpp:157:1: note:   candidate expects 2 arguments, 1 provided
../../src/synfig/color/color.hpp:148:1: note: candidate: 'synfig::Color::Color(const value_type&, const value_type&, const value_type&, const value_type&)'
Color::Color(const value_type& R,
^~~~~
../../src/synfig/color/color.hpp:148:1: note:   candidate expects 4 arguments, 1 provided
../../src/synfig/color/color.hpp:146:1: note: candidate: 'synfig::Color::Color(int)'
Color::Color(int f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:146:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'int'
../../src/synfig/color/color.hpp:145:1: note: candidate: 'synfig::Color::Color(const value_type&)'
Color::Color(const value_type &f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:145:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const value_type&' {aka 'const half&'}
../../src/synfig/color/color.hpp:144:1: note: candidate: 'synfig::Color::Color()'
Color::Color() :r_(0), g_(0), b_(0),a_(0) { }
^~~~~
../../src/synfig/color/color.hpp:144:1: note:   candidate expects 0 arguments, 1 provided
In file included from color.h:59,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/coloraccumulator.h: In member function 'synfig::ColorAccumulator synfig::ColorAccumulator::operator/(const float&) const':
../../src/synfig/color/coloraccumulator.h:99:22: error: no matching function for call to 'synfig::Color::Color(const synfig::ColorAccumulator&)'
{ return Color(*this)/=rhs; }
^
In file included from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.h:104:9: note: candidate: 'synfig::Color::Color(const int&)'
inline Color(const ColorAccumulator& c);
^~~~~
../../src/synfig/color/color.h:104:9: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'constint&'
In file included from gradient.h:32,
from gradient.cpp:33:
color.h:38:8: note: candidate: 'synfig::Color::Color(const synfig::CairoColor&)'
inline Color::Color(const CairoColor& c)
^~~~~
color.h:38:8: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::CairoColor&'
In file included from ../../src/synfig/color/color.h:369,
from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.hpp:163:1: note: candidate: 'synfig::Color::Color(const synfig::Color&)'
Color::Color(const Color& c):
^~~~~
../../src/synfig/color/color.hpp:163:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const synfig::Color&'
../../src/synfig/color/color.hpp:157:1: note: candidate: 'synfig::Color::Color(const synfig::Color&, const value_type&)'
Color::Color(const Color& c, const value_type& A):
^~~~~
../../src/synfig/color/color.hpp:157:1: note:   candidate expects 2 arguments, 1 provided
../../src/synfig/color/color.hpp:148:1: note: candidate: 'synfig::Color::Color(const value_type&, const value_type&, const value_type&, const value_type&)'
Color::Color(const value_type& R,
^~~~~
../../src/synfig/color/color.hpp:148:1: note:   candidate expects 4 arguments, 1 provided
../../src/synfig/color/color.hpp:146:1: note: candidate: 'synfig::Color::Color(int)'
Color::Color(int f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:146:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'int'
../../src/synfig/color/color.hpp:145:1: note: candidate: 'synfig::Color::Color(const value_type&)'
Color::Color(const value_type &f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:145:1: note:   no known conversion for argument 1 from 'const synfig::ColorAccumulator' to 'const value_type&' {aka 'const half&'}
../../src/synfig/color/color.hpp:144:1: note: candidate: 'synfig::Color::Color()'
Color::Color() :r_(0), g_(0), b_(0),a_(0) { }
^~~~~
../../src/synfig/color/color.hpp:144:1: note:   candidate expects 0 arguments, 1 provided
In file included from color.h:59,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/coloraccumulator.h: In member function 'synfig::Color synfig::ColorAccumulator::operator-() const':
../../src/synfig/color/coloraccumulator.h:111:11: error: could not convert 'synfig::ColorAccumulator((-((const synfig::ColorAccumulator*)this)->synfig::ColorAccumulator::r_), (-((const synfig::ColorAccumulator*)this)->synfig::ColorAccumulator::g_), (-((const synfig::ColorAccumulator*)this)->synfig::ColorAccumulator::b_), (-((const synfig::ColorAccumulator*)this)->synfig::ColorAccumulator::a_))' from 'synfig::ColorAccumulator' to 'synfig::Color'
{ return ColorAccumulator(-r_,-g_,-b_,-a_); }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gradient.h:32,
from gradient.cpp:33:
color.h: At global scope:
color.h:62:8: error: no declaration matches 'synfig::Color::Color(const synfig::ColorAccumulator&)'
inline Color::Color(const ColorAccumulator& c):
^~~~~
In file included from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.h:104:9: note: candidates are: 'synfig::Color::Color(const int&)'
inline Color(const ColorAccumulator& c);
^~~~~
In file included from gradient.h:32,
from gradient.cpp:33:
color.h:38:8: note:                 'synfig::Color::Color(const synfig::CairoColor&)'
inline Color::Color(const CairoColor& c)
^~~~~
In file included from ../../src/synfig/color/color.h:369,
from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.hpp:163:1: note:                 'synfig::Color::Color(const synfig::Color&)'
Color::Color(const Color& c):
^~~~~
../../src/synfig/color/color.hpp:157:1: note:                 'synfig::Color::Color(const synfig::Color&, const value_type&)'
Color::Color(const Color& c, const value_type& A):
^~~~~
../../src/synfig/color/color.hpp:148:1: note:                 'synfig::Color::Color(const value_type&, const value_type&, const value_type&, const value_type&)'
Color::Color(const value_type& R,
^~~~~
../../src/synfig/color/color.hpp:146:1: note:                 'synfig::Color::Color(int)'
Color::Color(int f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:145:1: note:                 'synfig::Color::Color(const value_type&)'
Color::Color(const value_type &f) :r_(f), g_(f), b_(f),a_(f) { }
^~~~~
../../src/synfig/color/color.hpp:144:1: note:                 'synfig::Color::Color()'
Color::Color() :r_(0), g_(0), b_(0),a_(0) { }
^~~~~
In file included from color.h:32,
from gradient.h:32,
from gradient.cpp:33:
../../src/synfig/color/color.h:39:7: note: 'class synfig::Color' defined here
class Color
^~~~~
gradient.cpp: In member function 'synfig::Color synfig::Gradient::operator()(const Real&, float) const':
gradient.cpp:459:41: error: 'class synfig::ColorAccumulator' has no member named 'premult_alpha'; did you mean 'get_alpha'?
pool+=ColorAccumulator(iter->color).premult_alpha()*weight;
^~~~~~~~~~~~~
get_alpha
gradient.cpp:470:44: error: 'class synfig::ColorAccumulator' has no member named 'premult_alpha'; did you mean 'get_alpha'?
pool+=ColorAccumulator(iter2->color).premult_alpha()*weight;
^~~~~~~~~~~~~
get_alpha
gradient.cpp:487:43: error: 'class synfig::ColorAccumulator' has no member named 'premult_alpha'; did you mean 'get_alpha'?
pool+=ColorAccumulator(iter2->color).premult_alpha()*weight;
^~~~~~~~~~~~~
get_alpha
gradient.cpp:509:13: error: could not convert 'pool' from 'synfig::ColorAccumulator' to 'synfig::Color'
return pool;
^~~~
make[3]: *** [Makefile:2975: libsynfig_la-gradient.lo] Error 1
make[3]: Leaving directory '/usr/src/synfig-1.2.2/src/synfig'
make[2]: *** [Makefile:484: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/synfig-1.2.2/src'
make[1]: *** [Makefile:709: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/synfig-1.2.2'
make: *** [Makefile:577: all] Error 2

**Comment by ice0** [comment]
Hi! Which OS you are using?
I am on Mint 19 and all compiled just fine.
Also can you show me the full command line you are using for compiling?

Here how i compile with OpenEXR:

```
cd ~/projects/synfig/
mkdir openexr
cd openexr
# first download and compile IlmBase 2.3.0
wget "https://github.com/openexr/openexr/releases/download/v2.3.0/ilmbase-2.3.0.tar.gz"
tar xzf ./ilmbase-2.3.0.tar.gz
cd ./ilmbase-2.3.0
./configure --prefix=/home/ice/synfig
# compile and install
make install -j4
cd ..

# next download and compile OpenEXR 2.3.0
wget "https://github.com/openexr/openexr/releases/download/v2.3.0/openexr-2.3.0.tar.gz"
tar xzf ./openexr-2.3.0.tar.gz
cd ./openexr-2.3.0
./configure --prefix=/home/ice/synfig PKG_CONFIG_PATH="/home/ice/synfig/lib/pkgconfig:$PKG_CONFIG_PATH"
make install -j4
cd ..

# now check /home/ice/synfig/lib/pkgconfig/ (both IlmBase.pc and OpenEXR.pc must be here)
ls -la /home/ice/synfig/lib/pkgconfig/
total 24
drwxrwxr-x 2 az az 4096 Nov 11 19:42 ./
drwxrwxr-x 4 az az 4096 Nov 11 19:42 ../
-rw-r--r-- 1 az az  227 Nov 11 19:15 ETL.pc
-rw-r--r-- 1 az az  333 Nov 11 19:42 IlmBase.pc
-rw-r--r-- 1 az az  306 Nov 11 19:35 OpenEXR.pc
-rw-r--r-- 1 az az  358 Nov 11 19:37 synfig.pc
```

**Comment by stumbles** [comment]
Figured it out. Was using the archive version instead of the release version.
