### ISSUE TITLE
Strange Cause of Crashes for Duplicating Layers from Multiple Groups

### ISSUE THREAD

**Issue by FadhilKwan** [synfig/synfig#675]
**Synfig version & platform**:
1.2.2

**Issue description**:
It's too complicated to explain but it's also interesting...

Duplicating these selected layers works fine...
![dupbug1](https://user-images.githubusercontent.com/25135159/48635966-2d8c4d00-e9fc-11e8-859f-adf8733ee43b.JPG)

But for some reason, duplicating these selected layers crashes synfig
![dupbug2](https://user-images.githubusercontent.com/25135159/48636075-70e6bb80-e9fc-11e8-802e-5d47108e6c3a.JPG)

upon further testings, i suspected that Z-Depth might be the main reason for this issue (still don't know how that would be related each other)
with more layers on the second group compare to the last test, duplicating these layers works fine
![dupbug3](https://user-images.githubusercontent.com/25135159/48636203-d6d34300-e9fc-11e8-8adc-e5348bbcd21a.JPG)

but adding some more in the first group layer and try this duplication again, synfig crashes
![dupbug4](https://user-images.githubusercontent.com/25135159/48636318-21ed5600-e9fd-11e8-8819-87fba3644d56.JPG)

Another strange thing to this bug is that the crash only occurs if the number of layers in the top group is more than the bottom group, NOT other way around
I also tried to change the second group's contents to just vector layers, and the bug still occurs

**Comment by ice0** [comment]
Can you share your test file?

**Comment by FadhilKwan** [comment]
Consider it done! :)

[DupliBug Tester.zip](https://github.com/synfig/synfig/files/2590470/DupliBug.Tester.zip)

**Comment by rodolforg** [comment]
Tested on 1.3.11 (linux) : crash
Tested on 1.3.12 (linux): it works
Tested on 1.3.13 (windows) : it works
Tested on master 2ed703e6 (linux) : it works :)

I think it can be closed. @ice0 @morevnaproject 

Test file : [675-bug.zip](https://github.com/synfig/synfig/files/4500682/675-bug.zip)

**Comment by FadhilKwan** [comment]
Tried to replicate this bug on v1.3.13 (Windows) as well, and i can confirm that the bug's not there anymore.
Yup, i think it's fixed now! 😄
