### ISSUE TITLE
Compilation error with missing gtest-all.cc in dependencies

### ISSUE THREAD

**Issue by zeograd** [synfig/synfig#676]
**Synfig version & platform**:
current HEAD ( 177ceb352f122c22f0ac326498805d001c20a52d )
on debian unstable

**Issue description**:
Following the building instructions, when running ./dev-env.sh several dependencies were fetched and built but then it stopped with the following error:

    make: *** No rule to make target '/nix/store/q2q3kq71ggd8w10rhca1qhab08gjj7m5-gtest-1.8.1/src/gtest-all.cc', needed by 'gtest-all.o'.  Stop.
    builder for '/nix/store/33x5107hyrxrli244s0slnfjla9lzwgq-movit-1.5.1.drv' failed with exit code 2
    cannot build derivation '/nix/store/2r4x0q5md3hrpc879jrg1wkh9r2n1i5w-mlt-6.10.0.drv': 1 dependencies couldn't be built
    error: build of '/nix/store/2r4x0q5md3hrpc879jrg1wkh9r2n1i5w-mlt-6.10.0.drv' failed

Can I provide more info to diagnose why the build is failing ?

**Comment by morevnaproject** [comment]
Hello Olivier! This was an issue with Nix build system and it got solved now - https://github.com/NixOS/nixpkgs/issues/49883
Please try to run ./dev-env.sh again - it should work now. ^__^

**Comment by zeograd** [comment]
Thanks Konstantin & BobSynfig, manually upgrading the default.nix for movit did the trick.
