### ISSUE TITLE
Windows: Cannot open file from explorer if filename contains non-latin characters

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#680]
**Synfig version & platform**:
1.2.2

**Issue description**:
If sifz file contains non-latin characters in any component of its path (including parent directories), then it is impossible to open it by double-clicking in Windows Explorer.

**Comment by BobSynfig** [comment]
Maybe this could be useful ;)
[Unable to open file with non-local and non-latin symbols in filenames [unicode] #278](https://github.com/mltframework/shotcut/issues/278)

**Comment by morevnaproject** [comment]
I did tested that on windows and, unfortunately, the fix didn't worked.

**Comment by BobSynfig** [comment]
That's why I added the link :)
For the moment I can't build a Windows version so I proposed the Glib::locale_from_utf8 to mimic the other formats in the source code.
But yes I expect mlt_open to do the trick

**Comment by ankit-kumar-dwivedi** [comment]
@BobSynfig are you currently working on this issue? if not then I would like to work on this issue :)
