### ISSUE TITLE
Allow set End Time for canvas directly from workarea

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#684]
Problem:
* People often ask how to set animation length.
* The End Time parameter is hidden deep in "Canvas" -> "Properties" dialog ( "Canvas" -> "Properties" -> "Time" tab -> "End Time").

![screenshot_003](https://user-images.githubusercontent.com/332868/49281137-5d3c5a00-f4be-11e8-963a-6afde5dac6c7.png)

Solution:
Add "End Time" text field to workarea -

![screenshot_005](https://user-images.githubusercontent.com/332868/49281336-de93ec80-f4be-11e8-968a-78b9317a7371.png)

**Comment by BobSynfig** [comment]
Don't forget to add a check and a warning in case of shrink of duration.
If keyframes/waypoints exist beyond the new limit, they are lost ;)

**Comment by unternehmen** [comment]
Yes, the program should protect waypoints/keyframes from being deleted like @BobSynfig says.

But I do like the idea of a text box there rather than a button.  The text box would eliminate having to go to a new window in order to change the length of the animation.  One way to protect keyframes would be to allow keyframes or waypoints to exist independently of the canvas duration, which is the way LMMS does song lengths:

![screenshot from 2019-01-07 19-50-18](https://user-images.githubusercontent.com/18196805/50802820-df027d00-12df-11e9-901c-9589ef1ad8e3.png)

In the song above, those green arrows that I circled in red show where the song begins and ends.  Users can put music notes after the end of the song; they just don't show up in rendered copies.

If Synfig supported placing waypoints past the endtime of the canvas like LMMS does, it would make it less dangerous to change the duration.

**Comment by morevnaproject** [comment]
> If keyframes/waypoints exist beyond the new limit, they are lost ;)

The behavior is different. If you change the duration, then waypoints beyound the new limit will continue to exist. Just try to change duration via "Canvas" -> "Properties" dialog and then revert it back. ^__^

**Comment by morevnaproject** [comment]
> If Synfig supported placing waypoints past the endtime of the canvas like LMMS does, it would make it less dangerous to change the duration.

This is exactly how Synfig works currently. ^__^

I also prefer input text box instead of button. Something similar to Blender:

![screenshot_003](https://user-images.githubusercontent.com/332868/50849487-c3fc3f80-13a9-11e9-9355-e21d87ad0617.png)

**Comment by unternehmen** [comment]
Oh, I did not check!  It's good to know it does not delete waypoints when the canvas duration changes. ':-D

I agree, Blender's way of doing it is nice and helps discoverability.  It would be a great benefit to Synfig learners. 👍

**Comment by rockyhandsome1** [comment]
@morevnaproject I would like to work on this issue.
If I get stuck anyware then will be informing the same.

**Comment by rockyhandsome1** [comment]
Hi @morevnaproject I have added the Set end time entry to the end. According to you this should be placed before repeat icon but all these icons fall under single group i.e.,framelist and are referenced with single pointer framelist. 
![screenshot from 2019-03-04 19-15-15](https://user-images.githubusercontent.com/43848518/53737510-bc8d7a00-3eb2-11e9-9116-ad35f435edba.png)
and now I am going through its core implementation (rendesc).
( "Canvas" -> "Properties" -> "Time" tab -> "End Time").
:)

**Comment by morevnaproject** [comment]
Hi @rockyhandsome1! Glad to see you started to work on this issue!
Can you please places the Set End Time entry before the "Loop" button? ^__^

![screenshot_003](https://user-images.githubusercontent.com/332868/53749624-51f03480-3eda-11e9-9982-6fd0fd061f7c.png)

**Comment by rockyhandsome1** [comment]
Hi @morevnaproject is there any way to call each framedial button seperately for there position adjustment in canvasview.cpp. If not then modifyng the framedial library is the way?

**Comment by morevnaproject** [comment]
Yes, you have to modify https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/dials/framedial.cpp

**Comment by rockyhandsome1** [comment]
Hi @morevnaproject  I placed it in the desired location and now I will work on its implementation.
I have to manage my college too so, will be bringing this feature in to effect soon.
![screenshot from 2019-03-06 19-45-44](https://user-images.githubusercontent.com/43848518/53887566-926dc080-4048-11e9-94c2-f4647a163efa.png)

**Comment by morevnaproject** [comment]
@rockyhandsome1 Looks good! Thanks for keeping me updated! ^__^

**Comment by rockyhandsome1** [comment]
Hi @morevnaproject I am stuck need your help.
I have submitted a message at: https://www.synfig.org/contact/
waiting for your reply.

**Comment by morevnaproject** [comment]
@rockyhandsome1 Yes, sorry for some delay. Duplicating answer here just in case ^__^ -

I think you need to create a signal in framedial.h, which is responsive for changing value of TextEntry.
Here you can see similar signals created for buttons in framedial.h - https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/dials/framedial.h#L76

Then, in canvasview.cpp you connect signal to an actual function, which is called when signal is emitted - https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/canvasview.cpp#L947

**Comment by morevnaproject** [comment]
Hi @rockyhandsome1! I have examined your code at https://github.com/rockyhandsome1/synfig/commits/endtimefeature and here are my recommendations:

It is not possible to access RendDesc from framedial.cpp. So, I recommend to set fps and initial values for end time widget from canvasview.cpp.

Please check the code for CurrentTimeWidget as an example:
https://github.com/synfig/synfig/blob/a6476f206374ef2ecc430f137d24c5bfdb354faf/synfig-studio/src/gui/canvasview.cpp#L934-L944

Obviously, you cannot set **value** and **fps** for EndTimeWIdget directly from CanvasView, because EndTimeWIdget belongs to FrameDial.

But you can create a public function in framedial.cpp, which sets values for EndTimeWidget. And then you can call this function from canvasview.cpp.

**Comment by rockyhandsome1** [comment]
Hi @morevnaproject sorry for the delay.
Feature is implemented.
will be generating the PR soon..
I have mailed you, regarding the same :)

**Comment by morevnaproject** [comment]
Hi @rockyhandsome1!
Great, please make sure to rebase your commits on the latest status of our master branch. Otherwise it is hard to see changes in your code. Thank you! ^__^

**Comment by rockyhandsome1** [comment]
Hi @morevnaproject I have rebased my commits:)

**Comment by morevnaproject** [comment]
Implemented by @rockyhandsome1 via #792
