### ISSUE TITLE
Rename Linux metadata

### ISSUE THREAD

**Issue by eszlari** [synfig/synfig#700]
Please, rename your metadata according to the AppStream spec:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
Desktop Entry Specification:
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html

This would mean:
`synfigstudio.appdata.xml` -> `org.synfig.SynfigStudio.appdata.xml`
`synfigstudio.desktop` -> `org.synfig.SynfigStudio.desktop`
`synfigstudio.xml` -> `org.synfig.SynfigStudio.xml` (mime)
`synfig_icon.svg` -> `org.synfig.SynfigStudio.svg`

**Comment by morevnaproject** [comment]
> through a search i found that renaming them will affect 50+ files it should be changed everywhere.

Please ignore all files ending with ".po" - they will be automatically re-generated. I hope that reduce the amount of affected files dramatically. ^__^

**Comment by morevnaproject** [comment]
> Can I refer https://wiki.synfig.org/Developer_Documentation ?(asking as I saw synfig is migrating to Cmake)

The https://wiki.synfig.org/Developer_Documentation can be quite outdated. The most recent documentation is here - https://synfig-docs-dev.readthedocs.io/en/latest/index.html
Although it is not that complete.

**Comment by morevnaproject** [comment]
> assign me this one :)

Great, I am keeping this issue for you. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> The https://wiki.synfig.org/Developer_Documentation can be quite outdated. The most recent documentation is here - https://synfig-docs-dev.readthedocs.io/en/latest/index.html
> Although it is not that complete.

Okay @morevnaproject I will be referring it most of the times but it's not as comprehensive as the one on wiki and I almost read all the docs(readthedoc) this one gradually becoming better.

**Comment by morevnaproject** [comment]
On wiki.synfig.org there are several cool fresh tutorials by @BobSynfig:
- https://wiki.synfig.org/Dev:Adding_a_Sound_notification
- https://wiki.synfig.org/Dev:Adding_a_Render_progress_bar
