### ISSUE TITLE
Preview is too slow

### ISSUE THREAD

**Issue by raniaamina** [synfig/synfig#710]
**1.3.10 dev & Debian 64bit**:
Hi, this morning i try to compile synfig. I follow wiki instruction and succesfull.
Yesterday i download the latest (dev version) appimage, but when i try change the amount value via parameter window, Synfig suddenly closed, that's why i try to compile directly from repository.

The problem is, Synfig (that i compile) running slow, it so far different with appimage version. Than, when i try to preview my work (by clicking preview button) it also wasting my times because to slow for render in qualituy 0.5 dan 12 fps :-(

What's the problem? Can it solved? Fyi, i use Lenovo X1 Carbon (Intel Core i7).

Thanks :")
Rania Amina

**Comment by ice0** [comment]
Hi! I think you build Debug version (it slow, yes), you need to build Release version.

**Comment by morevnaproject** [comment]
Yes, this is probably debug version. @raniaamina Can you please let us know which instructions you used for building?

**Comment by raniaamina** [comment]
No, i build release/production version

**Comment by raniaamina** [comment]
@morevnaproject, i follow this instruction https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html

**Comment by BobSynfig** [comment]
Do you use hi-res images and/or transforms like in the https://github.com/synfig/synfig/issues/712?
This could explain why it is so slow (Synfig is mainly vector-oriented)
Try to deactivate the render of the corresponding layer (the chechbox on the left of the name of the layer) and test again ;)

**Comment by ice0** [comment]
Can you say the size of the produced synfig binary?

**Comment by morevnaproject** [comment]
It seems like I know why this happens. In the latest version of Synfig we introduces image downsampling, which improves quality of scaling images, but requires more computations (especially for large images).

Appimage version (1.3.10) doesn't has this feature.

So, I guess this is why @raniaamina experiences slowdown.

You an easily check if my guess is right or not - just try to switch into Draft mode by clicking this button on toolbar:
![screenshot_004](https://user-images.githubusercontent.com/332868/51790080-68142200-21c3-11e9-9f11-d86b9c4c1fbf.png)

In Draft mode there are no downsampling and performance should be comparable to appimage (or faster).

@raniaamina can you please check that?

Also, it would be helpful if you attach the file you work with.

@raniaamina, can you please

**Comment by raniaamina** [comment]
Unfortunately i can't try this advice soon, coz my Thinkpad got an accident. I will try it soon after my laptop has been repaired.

**Comment by morevnaproject** [comment]
@raniaamina Hi! Have you had a chance to verify my theory? ^__^
