### ISSUE TITLE
Synfig render fails to render if height >= 782

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#711]
**Synfig version & platform**:
Master branch, commit 2365f6a67d9e09b1a428070e5e598739f16011d1

**Issue description**:
Synfig fails to render via CLI using FFmpeg target if height >= 780:

This works:
```
/home/konstantin/0-work/tools/bin/synfig -o /tmp/test.avi -w 1920 -h 779  -t ffmpeg  /tmp/test.sifz
```

This freezes:
```
/home/konstantin/0-work/tools/bin/synfig -o /tmp/test.avi -w 1920 -h 780  -t ffmpeg  /tmp/test.sifz
```

In this example ```/tmp/test.sifz``` is just an empty Synfig file.

**Comment by BobSynfig** [comment]
_synfig-core/src/synfig/target_scanline.cpp_, line 62:
 set
` #define USE_PIXELRENDERING_LIMIT` **0**
instead of
`#define USE_PIXELRENDERING_LIMIT` **1**

Above you can see
`#define PIXEL_RENDERING_LIMIT 1500000`
1500000/1920 = 781.25 (with your width of 1920)
ffmpeg renders files with increments of (h mod 4) + 4
779 -> 780
780 -> 784

784 > 781.25, more than the pixbuf surface

I don't know if it has a good reason to have broken up surfaces but you can see for example the logs of failed renders in the past here https://forums.synfig.org/t/how-do-you-run-synfig-on-mac-os-x/3855

**Comment by morevnaproject** [comment]
Yes, this is a good catch!

I also do not know if there is a reason  to break big frames into surfaces, but I remember this was available in Synfig for years. And that worked fine with Synfig 1.2.2.

@blackwarthog Can you please take a look?

**Comment by morevnaproject** [comment]
For png target it also freezes if height > 781:
```
/home/konstantin/0-work/tools/bin/synfig -o /tmp/test.png -w 1920 -h 782   /tmp/test.sifz
```

**Comment by morevnaproject** [comment]
As reported in #755, this also happens when doing GUI render.

**Comment by BobSynfig** [comment]
> I also do not know if there is a reason to break big frames into surfaces, but I remember this was available in Synfig for years. And that worked fine with Synfig 1.2.2.
This may help:
https://github.githistory.xyz/synfig/synfig/blob/master/synfig-core/src/synfig/target_scanline.cpp

**Comment by morevnaproject** [comment]
@blackwarthog Any progress on this? ^__^

**Comment by Domarius** [comment]
I noticed the featured movies on the Synfig home page are 1920x1080 so this resolution must have been possible at some point.

**Comment by BobSynfig** [comment]
I think the reason was to avoid to manipulate too much big pixbuf and consume huge amount of RAM, in "the old good time", and it has been changed during Cobra development.
When I did the test described above https://github.com/synfig/synfig/issues/711#issuecomment-456222617, it was working fine.
Or we could simply `#define PIXEL_RENDERING_LIMIT 2073600` to allow Full HD if we really need to set a limit :P

**Comment by morevnaproject** [comment]
I prefer @blackwarthog to do a real fix. ^__^

**Comment by morevnaproject** [comment]
@blackwarthog Testing changes in  ddba1d2 and attempt to render gives me "Render Failure" error now:

```
konstantin@master:~/sources/synfig$ LANG=C /home/konstantin/sources/synfig/_production/build/bin/synfig -o /tmp/test.png -w 1920 -h 1080   /tmp/test.sifz
synfig(21782) [17:11:25] info: rendering threads 8
synfig(21782) [17:11:25] warning: Cannot open ./synfig_modules.cfg
synfig(21782) [17:11:25] warning: Cannot open /home/konstantin/.local/share/synfig/synfig_modules.cfg
synfig(21782) [17:11:25] info: Loading modules from /home/konstantin/sources/synfig/_production/build/etc/synfig_modules.cfg
synfig(21782) [17:11:25] info: Loading lyr_std..
synfig(21782) [17:11:25] info: Loading lyr_freetype..
synfig(21782) [17:11:25] info: Loading mod_geometry..
synfig(21782) [17:11:25] info: Loading mod_gradient..
synfig(21782) [17:11:25] info: Loading mod_particle..
synfig(21782) [17:11:25] info: Loading mod_example..
synfig(21782) [17:11:25] info: Loading mod_gif..
synfig(21782) [17:11:25] info: Loading mod_imagemagick..
synfig(21782) [17:11:25] info: Loading mod_magickpp..
synfig(21782) [17:11:25] info: Loading mod_mng..
/home/konstantin/sources/synfig/_production/build/bin/synfig: warning: Unable to find module "mod_mng" (file not found)
synfig(21782) [17:11:25] info: Loading mod_noise..
synfig(21782) [17:11:25] info: Loading mod_filter..
synfig(21782) [17:11:25] info: Loading mod_ffmpeg..
synfig(21782) [17:11:25] info: Loading mod_bmp..
synfig(21782) [17:11:25] info: Loading mod_dv..
synfig(21782) [17:11:25] info: Loading mod_png..
synfig(21782) [17:11:25] info: Loading mod_ppm..
synfig(21782) [17:11:25] info: Loading mod_openexr..
/home/konstantin/sources/synfig/_production/build/bin/synfig: warning: Unable to find module "mod_openexr" (file not found)
synfig(21782) [17:11:25] info: Loading mod_jpeg..
synfig(21782) [17:11:25] info: Loading mod_libavcodec..
synfig(21782) [17:11:25] info: Loading mod_yuv420p..
synfig(21782) [17:11:25] info: Loading mod_svg..
synfig(21782) [17:11:25] info: Loading file: /tmp/test.sifz
synfig(21782) [17:11:25] warning: /tmp/test.sifz:<string>:139: Undefined value in <string>
synfig(21782) [17:11:25] info: target name not specified - using png
synfig(21782) [17:11:25] info: 	w: 1920, h: 1080, a: 1, pxaspect: 1.000000, imaspect: 1.777778, span: 9.178780
synfig(21782) [17:11:25] info: 	tl: [-4.000000,2.250000], br: [4.000000,-2.250000], focus: [0.000000,0.000000]
synfig(21782) [17:11:25] info: Render broken up into 1 block 781 pixels tall, and a final block 299 pixels tall
error: Accelerated Renderer Failure
Render Failure.
konstantin@master:~/sources/synfig$
```

**Comment by morevnaproject** [comment]
@blackwarthog Works perfectly, thank you! ^__^
