### ISSUE TITLE
PNG Image Color Changes when Image Resizes

### ISSUE THREAD

**Issue by raniaamina** [synfig/synfig#712]
**1.3.10 dev & Debian 64bit:**:
I import the PNG file to Synfig, the file is attached below, when I change the size of the object, the color becomes darker, while at a certain position and size the color returns to default. For more details, I also attach the results of rendering that object.

![PNG File](https://user-images.githubusercontent.com/22146607/51547775-82838e00-1e99-11e9-8fb0-c400646d6b88.png)

[Sample Render](https://github.com/synfig/synfig/files/2783571/SpreadLO.zip)

Thanks :")

**Comment by BobSynfig** [comment]
Are you sure it is not linked with another layer or a transition?
I could not reproduce this.
The change occurs between 5'0f and 5'1f, maybe with an intermediate waypoint or keyframe.
Could you please (on a copy of course) try to remove all the unneeded layers, transitions and waypoints and check the values?
And maybe post a .sifz with just the first part if it persists.

Good luck :)

**Comment by raniaamina** [comment]
I have try to use different image as background for this grid before, but i got same problem. 
Then, i try reproduce this case by create new file and set the navigator render as draft (before this = default), the problem is solved.

**Comment by BobSynfig** [comment]
Are you sure it was not the blend mode ?
I guess Light grid = Add, Dark = composite (the default one) or another

**Comment by raniaamina** [comment]
No, i'm very sure it's in default mode :")

**Comment by raniaamina** [comment]
@BobSynfig here my unfinished work (due my laptop problem) that can checked. But unfortunately i can't help to check soon if there any advice 

[spread-lo.zip](https://github.com/synfig/synfig/files/2820232/spread-lo.zip)
