### ISSUE TITLE
Conical Gradient fails to render

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#717]
**Synfig version & platform**:
Master branch, commit 4aa255f9ad852e3de5a64046f243a8b9dc34d143

**Issue description**:
See sample file:
https://github.com/synfig/synfig-tests-regressions/blob/master/sources/layers/gradient-conical/gradient-conical-strips.sif

This is how it looks in 1.0.2:
![screenshot_010](https://user-images.githubusercontent.com/332868/52030344-f7b22b80-2549-11e9-8937-c7356caba900.png)

...and this is how it looks in 4aa255f9ad852e3de5a64046f243a8b9dc34d143:
![screenshot_011](https://user-images.githubusercontent.com/332868/52030364-0a2c6500-254a-11e9-86d2-769f8fa55b2b.png)

**Comment by BobSynfig** [comment]
It seems it is also a problem of Gamma Transparency/Black Level  as in https://github.com/synfig/synfig/issues/717

**Comment by FadhilKwan** [comment]
> It seems it is also a problem of Gamma Transparency/Black Level as in #717

you mean, #716   ._. ?
