### ISSUE TITLE
Different versions of Synfig Studio use the same settings file. This renders an earlier version unusable.

### ISSUE THREAD

**Issue by Bill-Jobss** [synfig/synfig#718]
**SynfigStudio-1.3.11-pre5-64bit-2365f & Windows 7 (x64)**:

**Issue description**:
Say, a person has a stable version for work and wants to try a new release. After he launches the new release, the program changes the "settings-1.0" file and makes the stable version of Synfig Studio unusable, unless the "settings-1.0" file is deleted.

Normally this is solved by using different profiles for different versions of a program. For example, I can have many different versions of the Firefox browser installed on the same computer, and all of them can work simultaneously without interfering with one another, each using its own profile and settings. 

And also the place where Synfig Studio keeps its settings is not a proper place in Windows OS. In Windows it should be in the "C:\Users\\{User Name}\AppData\Roaming\Synfig" folder, not in the folder "C:\Users\\{User Name}\Synfig". Putting settings in improper places is a bad practice.

Hope, you guys maybe will fix these in a future release.

**Comment by Jose-Moreno** [comment]
@Bill-Jobss Hey. Good eye! While I agree that keeping separate profiles for different versions of Synfig on Windows and other OS would be benefical, particularly for development testing, I'm personally not having any issue with the preferences. I opened v 1.22 without any problem and can work as expected.

So aside from that the problem I'm seeing here is that this issue mixes two separate queries:
1) An enhancement request for Synfig to have different version profiles for settings.
2) A "bug" report which is not entirely outlined for possible testers to triage the bug.

I kindly suggest you expand the bug report in this issue, so myself and those who have windows can test, triage and confirm the bug, and also allow yourself to submit an additional issue to make the request for the settings profile separation you've outlined here.

**Comment by BobSynfig** [comment]
We could try to package with PortableApps
https://github.com/synfig/synfig/issues/716#issuecomment-459456640

**Comment by BobSynfig** [comment]
I'm on the way for the script for PortableApps packaging:
Not finished nor polished yet but using the .zip version (x64 only for now), package ok with persistence.
Only a few steps will be required ;)

**Comment by morevnaproject** [comment]
I've got another idea on this: we can use settings file with different name - i.e. "settings-1.3".

See here:

https://github.com/synfig/synfig/blob/4aa255f9ad852e3de5a64046f243a8b9dc34d143/synfig-studio/src/gui/app.cpp#L2035-L2037

and here:

https://github.com/synfig/synfig/blob/4aa255f9ad852e3de5a64046f243a8b9dc34d143/synfig-studio/src/gui/app.cpp#L2052-L2054

**Comment by BobSynfig** [comment]
I just published the script to create PortableApps portable version for Synfig x64 (1.2.2, 1.3.11-pre5 and 1.3.10-seterrormode currently)
See https://github.com/BobSynfig/synfig-portable-maker for details :)
Anyone can produce it at home from a .zip version

**Comment by morevnaproject** [comment]
@BobSynfig That's great! Any chances to get it submitted to portableapps.com?

**Comment by BobSynfig** [comment]
@morevnaproject It has to be tested by several people and fine-tuned.
For the moment, I made it for x64 only.
Normally a PA package carries both x86 and x64 binairies (but the other files like resources or locales can be shared), it would be huge (unless we could split  in 2 versions)
I think inclusion in portableapps.com distribution is submissed to some condition, I didn't check, but anyway an "independant" PA package can be added among the others at any time on a USB stck for example.

**Comment by Bill-Jobss** [comment]
Maybe it will be easier if you just to keep the settings files separately? The zip packages seemed pretty portable to me, as they were. Say, "Download Master Portable" has an "Application Data" folder inside its application folder where all program's settings are kept.

**Comment by morevnaproject** [comment]
From now on Synfig 1.3.11 will write settings to file with different name - "settings-1.3".

**Comment by Bill-Jobss** [comment]
That is a good progress. But what if a person has, say, the version 1.3.11 installed, and in a version 1.3.15 you decide to add a setting, that would make the settings file incompatible with the version 1.3.11? I have no experience with C++, it must be a very difficult language. Still, for the future it seems much more sustainable to keep settings files separately, in different profiles or in the application folder, like other programs do. You can just add an option for the user to choose which profile to use.

**Comment by morevnaproject** [comment]
@Bill-Jobss In future versions of 1.3.x branch we will try to add compatibility code, which workarounds the issue. Or, if not possible (or too much work) we will change to "settings-1.3.15".

In current solution we are separating settings of stable version from settings of development version.

If this solution is not fits you, then you can use portable  version of Synfig (ZIP file) - according to latest modifications, now it stores cpnfiguration in its own local directory (not touching any system-wide files). You can install many portable versions and each will use its own configuration.

**Comment by Bill-Jobss** [comment]
That's great news. I actually prefer portable versions.

**Comment by Bill-Jobss** [comment]
Just checked "SynfigStudio-1.3.11-testing-19.02.09-win64-9583a.zip". It still creates the folder "C:\Users\{User Name}\AppData\Roaming\Synfig" and the settings files within it.

> according to latest modifications, now it stores cpnfiguration in its own local directory (not touching any system-wide files). You can install many portable versions and each will use its own configuration.

Were you talking about a different version?

**Comment by morevnaproject** [comment]
"SynfigStudio-1.3.11-testing-19.02.09-win64-9583a.zip" is a correct version.

I cannot reproduce your issue - for me it creates settings in "config" subdirectory of portable installation.

Did you used "synfigstudio.bat" file to run Synfig?

![screenshot_001](https://user-images.githubusercontent.com/332868/52604222-902aa300-2e9c-11e9-89a7-a6e37d044b80.png)

**Comment by Bill-Jobss** [comment]
Oops! No, I just created a shortcut to the synfigstudio.exe and was launching from it. Now I changed it to the "bat" file and everything works. Thank you!
