### ISSUE TITLE
Render Issue in linear gradient

### ISSUE THREAD

**Issue by ThaFireDragonOfDeath** [synfig/synfig#720]
**Synfig version & platform**:
Affected version: Master (4aa255f9ad852e3de5a64046f243a8b9dc34d143) (compiled with 2-build-cmake.sh in debug mode)
Working version: 1.2.2 (Appimage-linux64)
Platform: Manjaro Linux 20190124-3

**Issue description**:
If a linear gradient has more then two color points --> the result is broken.
See the attachments for an example.
Maybe [this commit](https://github.com/synfig/synfig/commit/82aaf9b15cec4de9495cc5cfa3ab7923c527c484) caused it.

**Atachments**
Linear gradient in version 1.2.2 (expected result):
![lineargradientbug-v122](https://user-images.githubusercontent.com/10425127/52277879-050a5400-2956-11e9-9281-85c01940c5ac.png)

Linear gradient in master (broken result):
![lineargradientbug-vmaster](https://user-images.githubusercontent.com/10425127/52277880-050a5400-2956-11e9-917c-5ebc0d0929fa.png)

Source .sif file:
[LinearGradientBug.zip](https://github.com/synfig/synfig/files/2832335/LinearGradientBug.zip)

**Comment by morevnaproject** [comment]
Confirmed with a bit earlier commit (2365f6a67d9e09b1a428070e5e598739f16011d1). Ping @blackwarthog.

**Comment by morevnaproject** [comment]
Fixed in 9b3fe68. Thank you, @blackwarthog! ^__^

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
