### ISSUE TITLE
Add new workarea rendering mode: Preview

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#729]
This continues issue #409.

Long story short: 

In 17812bc2eaf88be30a6b57587bc55da71265ae2f we have added downsampling for images. This greatly improves quality if your scene uses big images scaled to smaller size. Unfortunately, this operation demands additional CPU resources and you will notice general application slowdown when working with such scenes.

You can enable Draft rendering mode (it disables downasampling), but this solution doesn't fits for all cases, as it is hides many layers, which could be important for you. 

So, we need one more rendering mode, which displays all possible layers, but with some simplifications - i.e. no downsampling (maybe some other simplifications can be added).

I suggest to call this new rendering mode "Preview".

So, we will have 3 rendering modes:

- "Draft" (simplifications + some layers hidden).
- "Preview" (some simplifications, not influencing image look very much).
- And the last one, which renders without any simplifications - I suggest to call it "Final".

**Comment by morevnaproject** [comment]
For solving this issue read about Synfig's render engines here - https://synfig-docs-dev.readthedocs.io/en/latest/common/structure.html#render-engine

**Comment by Gilraiser** [comment]
Good Morning,

Hi, I suggest that you create a rendering mode in which only the contours are visible. Not only the contour layer, but also the other types of layers, such as gradients, etc. It would be very useful and I think it could be very light.

Thanks, I hope it helps.

See you soon.

**Comment by morevnaproject** [comment]
@Gilraiser Yes, I understand - this is called "Outline" or "Wireframe" view in other apps. Can you please open a separate issue for that? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I would love to work on this one.
> For solving this issue read about Synfig's render engines here - https://synfig-docs-dev.readthedocs.io/en/latest/common/structure.html#render-engine

that's what I did but on reading multiple times I am still not able to get the exact meaning of following lines that would be appreciated if you shed some light, please.

```
i.e., if we have Stretch Layer on top of Shape Layer, then on first pass Synfig goes down and
 applies stretch to all vertices of Shape Layer, thus eliminating Stretch from operations.
 Then on rendering stage it renders Shape Layer only (as stretch is already applied on first pass).

On the other hand, if we have Blur Layer between Stretch Layer and Shape Layer,
 then it is not possible to apply Stretch (because Blur is a raster-based effect).
 So it doesn’t eliminates Stretch on first pass. On second pass it renders all 3 layers -
 Shape, then blurs it and finally stretches result.
```

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject can you tell me what do you mean by 

>  which displays all possible layers, but with some simplifications - i.e. no downsampling (maybe some other simplifications can be added).

As mentioned in https://github.com/synfig/synfig/issues/409#issue-252256398 some layers were disabled and rest were simplified. So do want each and every layer to be simplified in preview mode?

**Comment by morevnaproject** [comment]
In Preview mode we would like all layers to be displayed. So, it's more close to "Final" view mode, than "Draft" view mode.

Here's what I expect at first stage:

1. Create a copy of "Final" Renderer (it is a part of "Software" Sub-Engine), rename it to "Preview".
2. Take a look at "Draft" Renderer and see which Optimizers we can include into "Preview" Renderer. So far we need only one Optimizer, which modifies how images are displayed: it disables supersampling and forces NearestNeighbour interpolation scaling method.

This is generally enough to have #710 solved effectively.

**Comment by morevnaproject** [comment]
After you get done with changes above, the "Preview" Renderer will be available in Synfig Studio via Edit -> Preferences -> Render

![screenshot_002](https://user-images.githubusercontent.com/332868/53680780-9f21aa00-3d12-11e9-8383-ec9a83e6b93b.png)

At the second stage we need to do necessary UI tweaks:

3. Make "Preview" Renderer a default one for Synfig Studio.
4. Allow to easy switch Renderer for user. Currently we have two main Renderers - "Final" and "Draft". By default "Final" Renderer is used and user can switch to "Draft" Renderer by clicking this button on toolbar:
![screenshot_001](https://user-images.githubusercontent.com/332868/53680742-2f132400-3d12-11e9-86e5-06acf1e5d7ce.png)

After introducing  "Preview" Renderer, we will have more than 2 Renderers, so switch button for changing Renderer is not good anymore. So, my suggestion is to replace switch button with dropdown list (combo-box).

**Comment by Gilraiser** [comment]
> @Gilraiser Yes, I understand - this is called "Outline" or "Wireframe" view in other apps. Can you please open a separate issue for that? ^__^

Ok I will do it. Thank you.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I added the new rendering mode - "Cobra Preview" and made it the default renderer.
I verified it's working.

> `So far we need only one Optimizer, which modifies how images are displayed: it disables supersampling and forces NearestNeighbour interpolation scaling method.`

The above line Implied to NEAREST INTERPOLATION so I used the **OptimizerDraftTransformation**
Will be sending a PR after making the GUI changes.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Made a PR please review :)
