### ISSUE TITLE
Synfig studio does not render the .lst sequences when exporting to any video format.

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#730]
Synfig 1.3.11 & Archlinux 64x

Synfig studio does not render the .lst sequences when exporting to any video format.

In the work area it shows the animation of the imported .lst. But it does not show it when exporting it to a video or preview. Specifically with the .lst that contains images in PNG.

Thank you. I hope to be helpful.

**Comment by bluelavalamp** [comment]
I'm having the same issue.  It's only rendering a single image from the .lst sequence.

**Comment by bluelavalamp** [comment]
It would appear this is a bug only in 1.3.11.  When I run 1.2.2 and open the same project, it will render the .lst sequences correctly.

**Comment by morevnaproject** [comment]
Fixed now.

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/
