### ISSUE TITLE
Reference Issue to Discuss Proposals for Synfig User experience Improvements

### ISSUE THREAD

**Issue by ThobyV** [synfig/synfig#731]
**Synfig version 1.4x & platform Linux Fedora 64bit**:

**Issue description**:

In respect to the amazing upcoming build of *Synfig (v1.4.0)* I have decided to make a research about points that can be re-imagined to improve user experience in animating and rendering using synfig. 

I hope to make This issue serve as a kind of todo list and link to the UI/UX parts on Synfig we will be looking to work on. This is so that the community will discuss the relevance of the improvements and maybe create a dedicated issue for each. I think it will help the UX team and developers alike Since we will be using this as a general UX discussion and make sure to align the changes with upcoming features and full usabilty for the current feature set,

Currently, @morevnaproject  proposed a change for the rendering dialogue here. https://github.com/synfig/synfig/issues/721

**Current UI/UX changes list:**

`User-friendly rendering dialogue:` https://github.com/synfig/synfig/issues/721

*Question:* Would there be a need to also attach technical links of each changes proposal so to get communication and information between Design contributors and Code contributors more streamlined and exposed.

thanks for the great work making synfig better always. With respect and full praise for Complete team.

**Comment by BobSynfig** [comment]
Don't we already have a Roadmap issue ? https://github.com/synfig/synfig/issues/537
Also see the comment of @morevnaproject for more official roadmap here https://github.com/synfig/synfig/issues/537#issuecomment-460676161

**Comment by ThobyV** [comment]
Oh! I wasn't aware of that. I had just thought this would be an easy way to Reach the interfaces modifications exclusive of the official roadmap.

**Comment by morevnaproject** [comment]
I think it is fine to have this issue if we will make it concentrated on UI improvements (while #537 is more generic and includes feature requests as well). ^__^

**Comment by morevnaproject** [comment]
After thinking more on this, I've got an impression that it is not the best practice to use issues as a list to other issues. 

On GitHub we have Labels if we want to group issues together. Like this - https://github.com/synfig/synfig/issues?q=is%3Aopen+is%3Aissue+label%3AText

Sometimes it is important to have a list in specific order. For this purpose we can use GitHub's Project Boards - https://github.com/synfig/synfig/projects/5

Finally, if we want to describe some big, complex project (which is split into smaller issues/steps), then it is the best to create a community-editable page at Developer documentation - https://synfig-docs-dev.readthedocs.io/en/latest/

So, I suggest to decide which tool would fit best here to collect proposals for UI improvements. ^__^

**Comment by ThobyV** [comment]
I also agree with you @morevnaproject I have seen there is no serious need too and also it is best to use the first option which uses labels. That way It is easier for us to find UI features.

**Comment by ThobyV** [comment]
I guess this issue should be closed? :smile:

**Comment by morevnaproject** [comment]
Yes, let's close this for now. ^__^

**Comment by morevnaproject** [comment]
I have added GUI label for #721. Actually, we have too much stuff marked with this label, which is not relevant - https://github.com/synfig/synfig/issues?q=is%3Aopen+is%3Aissue+label%3AGUI
I think it needs cleanup.

**Comment by morevnaproject** [comment]
I think the problem that "GUI" label means "any issue in GUI (Synfig Studio). So, I think, we need a new label for UI/UX.

**Comment by morevnaproject** [comment]
Created label for UI/UX - https://github.com/synfig/synfig/labels/UI%2FUX
