### ISSUE TITLE
Too many options in <view> menu item

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#732]
**Synfig version & platform**:
1.3.11

**Issue description**: Too many options in the <view> menu item
![screenshot from 2019-03-01 16-20-43](https://user-images.githubusercontent.com/37617951/53633703-3e28a200-3c3e-11e9-905c-4b455a41686c.png)
the options are also not correctly aligned i.e due to more number of options in <view> menu item it goes above the menubar, which doesn't look professional.

**Comment by ankit-kumar-dwivedi** [comment]
one possible solution could be placing some related options say keyframes into a category.

**Comment by yshkp** [comment]
@ankit-kumar-dwivedi Its possible solution would be merging the options of relatively same kind into the single group.  
@morevnaproject PTAL at my suggestion. Shall I move forward towards it ?

**Comment by morevnaproject** [comment]
@yshkp I just want to point out that the following items are actually related to Timeline navigation, not View - 
![screenshot_004](https://user-images.githubusercontent.com/332868/53657089-b9fb0c80-3c87-11e9-9e9f-e337c8402d37.png)

So, my suggestion is to create a new menu right after "View" and place outlined items there.
We can call new menu "Navigation" or "Timeline".

**Comment by yshkp** [comment]
@morevnaproject Yup, I also wanted to mention the same. These options belong to another kind and can be placed to new menu. 
Now, As per your suggestion would start working on it.

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi are you okay if I assign that issue to @yshkp ? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Yes @morevnaproject that would be great!
What I think is: As long as no one working on an issue anyone can start working on it :) 
but letting people know can avoid situations like multiple people working on the same issue.
I think I should add this to contributing guidelines :thinking:

**Comment by morevnaproject** [comment]
Yes, I think it is mandatory to let other know who is working on the issue. This will help to avoid double-work. ^__^

**Comment by lenixlobo** [comment]
Is @yshkp  Working on this currently ? I was interested in this issue as well.

**Comment by ashutoshjv661** [comment]
@morevnaproject  Can I work on this issue ?
Creating a new menu named - Navigation or Timeline
containing -  options mentioned above 
+
merging available options 
1. Zoom in 
2. Zoom out
3. Best Fit
4. Normal Size 
into a single option named - "Resize"
If this works out the menu bar will increase by 1(one) menu whereas the options inside <view> would reduce by 13 options as stated above .

This would be my first contribution to synfig  : )

**Comment by morevnaproject** [comment]
Hi @ashutoshjv661! Sorry, but this issue already assigned to @yshkp. THank yo for your suggestions anyway! ^__^

**Comment by ashutoshjv661** [comment]
> Hi @ashutoshjv661! Sorry, but this issue already assigned to @yshkp. THank yo for your suggestions anyway! ^__^

No Problem . I'll find something new in issues. ^ __ ^

**Comment by morevnaproject** [comment]
Closed by #748.
