### ISSUE TITLE
"View" -> "Toolbar" menu item is not active

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#733]
"Toolbar" menu item in "View" menu is not active.

![screenshot_002](https://user-images.githubusercontent.com/332868/53656588-4d334280-3c86-11e9-85c0-18126e41f7b2.png)

**Comment by morevnaproject** [comment]
Possibly worth to take a look at https://github.com/synfig/synfig/commit/a19e5589b6710e8d8e97eeb4c7686c600bcca06f

**Comment by lenixlobo** [comment]
I would like to work on this issue.
@morevnaproject

**Comment by morevnaproject** [comment]
Great! It is yours now. ^__^

**Comment by bajajvinamr** [comment]
@morevnaproject  I would like to fix this issue

**Comment by ice0** [comment]
@bajajvinamr it's yours now :)

**Comment by kamal-kaur04** [comment]
Hii @morevnaproject, 
I would like to take this issue if it's not assigned already.
Thank you

**Comment by ankit-kumar-dwivedi** [comment]
Great @kamal-kaur04 assigning you this one.

**Comment by kamal-kaur04** [comment]
Hii @morevnaproject 
Can you please tell the expected behavior(purpose) of **Toolbar**?

**Comment by morevnaproject** [comment]
This command should show/hide this toolbar -

![screenshot_001](https://user-images.githubusercontent.com/332868/76145735-cbf36480-60be-11ea-9c0d-5f1a73602b90.png)

**Comment by kamal-kaur04** [comment]
@morevnaproject I have tried to do this but I am not able to find the key that binds this whole toolbar. Can you please help me out with this?

![Screenshot from 2020-03-09 12-29-09](https://user-images.githubusercontent.com/38219887/76189836-a28f2180-6201-11ea-8931-9f22364f4d59.png)
![image](https://user-images.githubusercontent.com/38219887/76189924-cce0df00-6201-11ea-8c48-c9a5db5331ff.png)

**Comment by ankit-kumar-dwivedi** [comment]
> @morevnaproject I have tried to do this but I am not able to find the key that binds this whole toolbar. Can you please help me out with this?
> 
> ![Screenshot from 2020-03-09 12-29-09](https://user-images.githubusercontent.com/38219887/76189836-a28f2180-6201-11ea-8931-9f22364f4d59.png)
> ![image](https://user-images.githubusercontent.com/38219887/76189924-cce0df00-6201-11ea-8c48-c9a5db5331ff.png)

AFAIK this uistring is defined in app.cpp and only for starting elements of toolbar viz save, save all, render etc. 

The only possible way I see is to define a getter for the widget(toolbar) and change it's property i.e hide/unhide accordingly. 

@ice0 However this doesn't sound like how other things are being handled. So is there a better way to do this?

**Comment by ice0** [comment]
@kamal-kaur04 you can start to dig from Edit->Preferences->Show file toolbar.

When you switch it off, and restart Synfig - you will see that part of the toolbar is hidden.
Try to search thru the code by the `App::show_file_toolbar` and this must lead you here:

https://github.com/synfig/synfig/blob/9e189c35d3167a71048f9b7fe4a16d86f58871b4/synfig-studio/src/gui/canvasview.cpp#L1135-L1141

The problem is a little bit harder, and you can't use approach used in `View->Show menubar` because `displaybar` is not unique for application, and every CanvasView has it's own `Toolbar/displaybar`.

But don't give up. This is a good way to better understand how Synfig works. You will learn a little bit about CanvasView and how to get active CanvasView.

Also i want to ask: did you have issues with compiling/testing? How long does it take? I have a few ideas on how to improve this, but I don’t know if this is necessary now.

@ankit-kumar-dwivedi 
> However this doesn't sound like how other things are being handled. So is there a better way to do this?

I think that would be good enough. If someone finds a better way, we can always refactor it later :)

**Comment by kamal-kaur04** [comment]
@ice0 @ankit-kumar-dwivedi when I tried the approach like menubar, was able to hide/show the icons referenced by the key(toolbar-main). But it doesn't show the required behavior for sure. Thank you for your take on the issue. 
No issues in the compilation. But it takes long time(5-10 mins).

![synfig_demo](https://user-images.githubusercontent.com/38219887/76206590-50aac380-6222-11ea-9f79-7da1d5d0665f.gif)

**Comment by rodolforg** [comment]
@kamal-kaur04 if your PC has more than 1 core, you can increase the number of jobs (threads) the build system uses. This should speed up your compilation. By default, autotools are set to 2 threads only. See `build.conf` file.

And if you're building via `2-build-debug.sh` script, and as your PR is just GUI stuff and without any file adding/removal, you could call `2-build-debug.sh studio make`.

**Comment by kamal-kaur04** [comment]
Okay. Thank you @rodolforg

**Comment by ice0** [comment]
Also you can run `make install -j <number_of_threads>` inside `_debug` directory.
For example if you are changed `synfig/synfig-studio/src/gui/canvasview.cpp` file, then go to 
`_debug/synfig/synfig-studio/src/gui/` and run `make install -j4`. If there is no Makefile in this directory, then go up to the parent directory.

**Comment by morevnaproject** [comment]
> when I tried the approach like menubar, was able to hide/show the icons referenced by the key(toolbar-main). But it doesn't show the required behavior for sure. Thank you for your take on the issue.

Yes, that's a different toolbar. ^__^
The code needs to look for active document and find it's UI (canvasview). Then it should call a function (you probably need to write this function), which hides a toolbar in canvasview.

**Comment by kamal-kaur04** [comment]
Thank you @ice0 @morevnaproject , I am trying to fix this. Will be able to do for sure. :)

**Comment by ankit-kumar-dwivedi** [comment]
@kamal-kaur04 any progress on this? Let us know if you are stuck.

**Comment by ankit-kumar-dwivedi** [comment]
> @kamal-kaur04 any progress on this? Let us know if you are stuck.

@kamal-kaur04 are you working on this any more?

**Comment by ARYA-BHARDWAJ** [comment]
@ice0  can I work on this issue ??

**Comment by ice0** [comment]
@ARYA-BHARDWAJ Sure, it's yours now )

**Comment by ARYA-BHARDWAJ** [comment]
@ice0  what do you think about the use of Gtk::CheckMenuItem instead of Gtk::Action for view toolbar

**Comment by ARYA-BHARDWAJ** [comment]
@ice0 what is your opinion about using new classes instead of deprecated ones e.g. Gtk::CheckMenuItem instead of Gtk::ToggleAction.

**Comment by ARYA-BHARDWAJ** [comment]
@ice0  I guess this can be solved by changing displaybar of canvasview  of current window. But I don't understand how to get canvasview of current window.

**Comment by ice0** [comment]
Please look at `App::get_selected_canvas_view()`. Sounds like something you are looking for :)

**Comment by ARYA-BHARDWAJ** [comment]
I am able to show and hide toolbar. But I have confusion that in case we have multiple documents opened. Then we want to hide/show the toolbar of current document or toolbar of all opened documents.

**Comment by morevnaproject** [comment]
Closed via #1386

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1.
