### ISSUE TITLE
Error While Building synfig

### ISSUE THREAD

**Issue by lenixlobo** [synfig/synfig#742]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)

**Issue description**:
Error :  reference to ‘AVPixelFormat’ is ambiguous

**Comment by lenixlobo** [comment]
@morevnaproject  Kindly refer the commit, and notify whether the issue is to be closed

**Comment by morevnaproject** [comment]
@lenixlobo Thanks for pushing the workaround!

Just want to mention that this is not a complete fix. With this change we lost support for video import (see #744). This should be solved at high priority.
