### ISSUE TITLE
Feature request: Rounded corners for Rectangle Layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#745]
We need an option to draw Rectangle Layer with rounded corners - http://mathworld.wolfram.com/RoundedRectangle.html

![roundedrectangle_1000](https://user-images.githubusercontent.com/332868/53724840-5fd39480-3e9d-11e9-93f0-14928d909277.gif)

Note: Synfig already has a special layer called  "Filled Rectangle" (can be created by choosing "Layer" -> "New Layer" -> "Examples" -> "Filled Rectangle" from menu). This is not the same as Rectangle Layer. The Filled Rectangle layer has an option for rounded corners, but it doesn't draw them correctly in two aspects:
- the rounded parts has no antialiasing.
- the corners are not circles.

![screenshot_001](https://user-images.githubusercontent.com/332868/53725351-66164080-3e9e-11e9-8340-a8d311f73c67.png)

**Comment by yshkp** [comment]
@morevnaproject Please allow me to have a look in this.

**Comment by morevnaproject** [comment]
@yshkp Awesome! This issue is yours now. ^__^

**Comment by yshkp** [comment]
@morevnaproject Its being great to work with you, enjoying it. ^_^ 
 Can I have your email address for any query or discussion?  
And one doubt related to the issue : Do we need to add a feature of rounded corner rectangle layer or just to improve the filled rectangle layer ?

**Comment by morevnaproject** [comment]
@yshkp You can contact me via https://www.synfig.org/contact/ ^__^

>  Do we need to add a feature of rounded corner rectangle layer or just to improve the filled rectangle layer ?

We need to add rounded corners to  Rectangle Layer.

**Comment by sagar-joshi** [comment]
@morevnaproject    I know this issue is assigned to yshkp , I am just asking as i am a bit confused about rounded circle thing.
You wrote:
 "The Filled Rectangle layer has an option for rounded corners, but it doesn't draw them correctly in two aspects:

    the rounded parts has no antialiasing.
    the corners are not circles.
"
In your picture Keep bevel circular was unchecked. So i tried to draw it with Keep bevel circular checked.On checking Keep bevel circular filledrectangle  draws circular corners.So what is the need of rectangle layer to do the same thing.

**Comment by morevnaproject** [comment]
@sagar-joshi OMG,  this option was there for all this time and I didn't noticed it. O___O
Thanks for pointing on this! Also, it looks like the result is also antialiased (probably got implemented as consequence of porting Shape Class to Cobra render engine).

**Comment by morevnaproject** [comment]
@yshkp  Okay, then the task narrows down to merging algorithm from FilledRectangle Layer to Rectangle Layer. You will also need to properly handle the Expand parameter of Rectangle Layer.

**Comment by yshkp** [comment]
@morevnaproject Yeah I also checked today only about bevel circular :P because of an exam I was offline so couldn't start working but now with full flow gonna start working. So now issue turns to be of merging the filled rectangle layer to rectangle layer, what is the difference basically between them?

**Comment by morevnaproject** [comment]
@yshkp 

Rectangle Layer has **Expand** and **Invert** features (parameters).

Filled Rectangle has **Bevel** and **Feather** features (parameters).

It would be cool to have best of both worlds in single Rectangle Layer. ^__^

**Comment by yshkp** [comment]
@morevnaproject Yup soon it will be done. 
Also, request you to check your mail sent via link you gave to me.

**Comment by yshkp** [comment]
@morevnaproject  And also after it is merged into single rectangle layer option of filled rectangle in `New Layer -> Example -> Filled Rectangle` is not required so I would also remove it from there.

**Comment by yshkp** [comment]
@morevnaproject  And also after it is merged into single rectangle layer option of `Filled Rectangle` in `New Layer -> Example -> Filled Rectangle` is not required so I would also remove it from there.

**Comment by morevnaproject** [comment]
> Also, request you to check your mail sent via link you gave to me.

Oh, just found it has gone to spam. Will respond soon! ^__^

> And also after it is merged into single rectangle layer option of Filled Rectangle is not required so I would also remove it from there.

Yes! ^__^

**Comment by yshkp** [comment]
@morevnaproject During building found an error like this : 
`make[4]: *** No rule to make target '/home/yash/synfig/synfig-core/src/modules/mod_example/filledrect.cpp', needed by 'libmod_example_la-filledrect.lo'.  Stop.
make[4]: Leaving directory '/home/yash/synfig/_debug/synfig-core/src/modules/mod_example'
Makefile:570: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/yash/synfig/_debug/synfig-core/src/modules'
Makefile:471: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/yash/synfig/_debug/synfig-core/src'
Makefile:696: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/yash/synfig/_debug/synfig-core'
Makefile:564: recipe for target 'all' failed
make: *** [all] Error 2`
What can be the reason of this ?

**Comment by morevnaproject** [comment]
I guess, this happened after you have removed filled_rectangle source?

**Comment by yshkp** [comment]
@morevnaproject Yup I removed as it is not required now because I have merged its features in rectangle layer.

**Comment by yshkp** [comment]
@morevnaproject I found the solution. Making PR please review. ^_^
