### ISSUE TITLE
Editable animation curves in Graphs Panel [GSOC Proposal]

### ISSUE THREAD

**Issue by lenixlobo** [synfig/synfig#746]
I am a undergrad student (Engineering) from India,
I'm interested in resolving the above issue,since it is a highly appreciated feature by animators.
Would really appreciate any important things to focus on , with regards to acceptance of my Proposal.

**Comment by morevnaproject** [comment]
Hi @lenixlobo! I happy to see you've got interested about this issue!
Please check my comment in this thread - https://github.com/synfig/synfig/issues/267#issuecomment-469740322
I suggest to continue discussion there. ^__^

**Comment by Keyikedalube** [comment]
Closing this because @morevnaproject already linked a related/duplicate issue to this.
