### ISSUE TITLE
Navigation -> Pause menu item doesn't works

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#750]
**Synfig version & platform**:
Master branch, commit a9430e306d4aff662bb5a4d329fdc8ab1cfa87f9

**Issue description**:
Choosing "Navigation" -> "Pause" does nothing. 

Steps to reproduce:
* Start Playback
* Choose  "Navigation" -> "Pause" from menu. Nothing happens (playback continues).

NOTE: In previous versions the command was at "View" -> "Pause", and it wasn't working as well.

**Comment by 9inpachi** [comment]
Hi @morevnaproject ,
I have been looking around for a fix of this issue and have gathered some data from my research.
A possible problem could be with
```
action_group->add( Gtk::Action::create("stop", Gtk::StockID("synfig-animate_pause")),
		SLOT_EVENT(EVENT_STOP)
	);
```
This part of the code does not seem to be working. Or is SLOT_EVENT a dummy event?

A possible solution could be to use the CanvasView::stop_async function to make it work.

I am not sure if this actually is the problem. Its actually a little too late here so I will fork and try to counter it tomorrow.

**Comment by 9inpachi** [comment]
This issue is fixed. I am submitting a PR now.
Please review the changes.

**Comment by morevnaproject** [comment]
@9inpachi Works perfectly! Thank you! ^__^
