### ISSUE TITLE
Problem time axe and keyframe

### ISSUE THREAD

**Issue by IwannaAnimate** [synfig/synfig#753]
So I am a noob at this program, and i wanna use it to animate longer videos. Now I've been trying to figure out how I can have a longer time-axis for the keyframes. Whatever I do it stays locked in 120f, and I can't seem to change it, nor when I create new keyframes that exceed 120f it plays them out when I try to look at the progress of the animation.

I hope someone can help me with this issue, and I'm sorry for not being able to help with programming or anything... never learned those skills :/

**Comment by Jose-Moreno** [comment]
@IwannaAnimate Hi. Normally this page is meant to report bugs and problems in the program. For usage it's better to use the forum at https://forums.synfig.org

Now to answer your query, it is possible to extend the duration of any given scene by going to:

**menu CANVAS > PROPERTIES ... > TIME tab > End Time [xxx] f**

Currently an implementation is being worked upon to allow users to extend the timeline length on the playback controls, but it will take some time to make it available to the userbase.

If you have any other question related to Synfig use please use the forum as it sometimes might be ignored in here if it's not related purely to it's development :wink:

**Comment by BobSynfig** [comment]
Thank you @Jose-Moreno, I would not have said better :)
I close this "issue"
