### ISSUE TITLE
Render locks up for HD 1920x1080 animation

### ISSUE THREAD

**Issue by Domarius** [synfig/synfig#755]
**Synfig version & platform**:
SynfigStudio-1.3.11-testing-19.02.09-linux64-9583a.appimage

**Issue description**:
In this zip [Animation files.zip](https://github.com/synfig/synfig/files/2944413/Animation.files.zip) are two files of a rotating rectangle.  This helps demonstrate the issue.

"Synfig Animation 1", this one is 480x270 (the default).  Click File, Render, and Render, the Render progress bar completes to 100% and you can open the resulting AVI file.

"Synfig Animation 1 HD", this one is 1920x1080. Click File, Render, and Render, the Render progress bar appears, but stays stuck at 0% and you cannot do any additional renders until you force quit the program.

UPDATE: I've done some more testing, I narrowed down the scale of the problem - a canvas size of 1280x720 still works, but a canvas size of 1650x928 does not, it locks up as in the 2nd example.

**Comment by BobSynfig** [comment]
Know issue: https://github.com/synfig/synfig/issues/711
This is due to the "number of pixels" in the reserved pixbuf.
Currently 1500000 pix
1289x720 works (921600 < 1500000)
1650x928 doesn't (1531200 > 1500000)
A solution has already been proposed in the mentionned issue to solve this "bug" and can therefore be closed.
Please check existing issues before to declare a new one ;)

**Comment by Domarius** [comment]
Thanks for letting me know :) I did look but I missed that one somehow.  In my defence it's refering to CLI but this happens in the GUI too, so it's not specific to the CLI.  Perhaps #711 title could be updated to be more general?

**Comment by morevnaproject** [comment]
@Domarius Thanks for letting us know! I have updated the issue. ^__^

**Comment by Domarius** [comment]
@morevnaproject You're welcome, happy to contribute.  It's the perfect successor to Flash IMO, free or not...
