### ISSUE TITLE
Remove Navigator Renderer option from Preferences

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#758]
Currently we have an option in Preferences to separately choose renderers for Navigator and Workarea.

I suggest to remove an option for Navigator renderer and always use same renderers forboth Workarea and Navigator.

![screenshot_007](https://user-images.githubusercontent.com/332868/54074192-1383bc80-42c2-11e9-9028-17d112b29651.png)

![screenshot_008](https://user-images.githubusercontent.com/332868/54074195-1bdbf780-42c2-11e9-8571-ddcaff622a6a.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject as I worked on renderer so I wish to work on this one if you assign this to me :)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Great! It is yours now. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I have removed it from the gui of preferences now Workarea render is the only option available and changing it also changes the navigator renderer.

> Currently we have an option in Preferences to separately choose renderers for Navigator and Workarea.
> 
> I suggest to remove an option for Navigator renderer and always use same renderers forboth Workarea and Navigator.

Just to make sure you mean to change both Navigator & Workarea render when we select any option which was implemented in https://github.com/synfig/synfig/pull/749 right?

> 
> ![screenshot_007](https://user-images.githubusercontent.com/332868/54074192-1383bc80-42c2-11e9-9028-17d112b29651.png)
>

**Comment by morevnaproject** [comment]
> Just to make sure you mean to change both Navigator & Workarea render when we select any option which was implemented in #749 right?

Exactly! ^__^
