### ISSUE TITLE
Disable Brush Tool

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#760]
As result of discussion here - https://forums.synfig.org/t/remove-brush-tool-from-synfig-studio-stable-release/9572:

> Brush tool is basically unusable at its current status. That confuses many users and makes a bad impact on user experience.

So, I am proposing the following:

- Add an option to Preferences, which enables and disables experimental features. Call it “Enable experimental features”.
-  This option should be disabled by default.
-  Add a code to hide Brush Tool icon from Toolbox if “Enable experimental features” option disabled.

**Comment by 9inpachi** [comment]
@morevnaproject I will start looking into this. Let me take care of it.

**Comment by morevnaproject** [comment]
@9inpachi Awesome! This issue is yours now. ^__^

**Comment by 9inpachi** [comment]
@morevnaproject I have setup the code for the "Enable experimental features" preference but can not fund the code where the tools are located.
If you can refer to some files, that would help a lot.
Thanks. :)

**Comment by morevnaproject** [comment]
In Synfig tools are called "states". Please take a look here: 

https://github.com/synfig/synfig/blob/59badba9e0c9eeed52176a7ce1fce08a6692f2c6/synfig-studio/src/gui/app.cpp#L1727

P.S. I am looking forward for your email. as mentioned in https://github.com/synfig/synfig/issues/759#issuecomment-471425914 ^__^

**Comment by 9inpachi** [comment]
@morevnaproject 
Looking forward to your email. :)

**Comment by morevnaproject** [comment]
@9inpachi I cannot find your message. Did you mailed to me via https://www.synfig.org/contact/ ? ^__^

**Comment by 9inpachi** [comment]
I did receive a confirmation email suggesting that my message has been sent.
I will try sending again.

**Comment by morevnaproject** [comment]
Got your mail, thank you! ^__^
