### ISSUE TITLE
Support for 'pacman' package manger  

### ISSUE THREAD

**Issue by Rathod-Sahaab** [synfig/synfig#765]
Hi I am Abhay Raj Singh GSoc 2019 aspirant. I was trying to build **synfig** on my system and encountered this problem, that pacman isn't supported. I would like to work on it.

I would also like to know about any previous efforts or problems and they would be of great help.

I am also proficient in c++,  python, bash and vector graphics can anyone help me with a good first issue.

**Comment by morevnaproject** [comment]
Hello @Rathod-Sahaab and welcome to the project! 

This issue is yours now! ^__^

For good first issues, please take a look here - https://github.com/synfig/synfig/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

I also encourage you to introduce yourself with a mention of your interests/projects here - https://forums.synfig.org/t/google-summer-of-code-2019/9487 ^__^

**Comment by Rathod-Sahaab** [comment]
Some packages are only imported for apt-get and not for yum/dnf etc. is it intentional or it's better to add them also?

**Comment by Rathod-Sahaab** [comment]
#768 Reviews would be helpful

**Comment by Rathod-Sahaab** [comment]
#770 
Related MR Reviews will be helpful.

**Comment by BobSynfig** [comment]
"Duplicate" https://github.com/synfig/synfig/issues/725

**Comment by Rathod-Sahaab** [comment]
Any progress on solutions of this as I have successfully built Synfig using my modifications in my MR mentioned above

**Comment by morevnaproject** [comment]
The changes are merged now, thank you!

@ebarranco can you please check if build instructions (https://synfig-docs-dev.readthedocs.io/en/latest/common/building.html) are working for your system now?

**Comment by BobSynfig** [comment]
Just installed a clean Manjaro 18 KDE in VirtualBox (with Guest Additions)
I had to add intltool to the script

**Comment by morevnaproject** [comment]
Thank you @BobSynfig!

**Comment by ebarranco** [comment]
Hi @morevnaproject I have this error using ./2-build-production.sh:

`checking LIBPANGO_CFLAGS... -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid 
checking LIBPANGO_LIBS... -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lcairo 
checking for mlt++... configure: error:  ** You need to install mlt++.
`

**Comment by BobSynfig** [comment]
Compilation successfull :)
@ebarranco please update your source, my last commits fixed this error ;)

**Comment by ebarranco** [comment]
Yeah it's working now! thanks @BobSynfig.

**Comment by Rathod-Sahaab** [comment]
Thanks for fixing my mistakes 😅 @BobSynfig

**Comment by BobSynfig** [comment]
@Rathod-Sahaab not mistakes, just the classical "it was working on my machine but it doesn't on someone's else" ;)
That's the good point with virtualization, you can check the validity of environment without to destroy your own machine ^^

**Comment by morevnaproject** [comment]
Closing this then. ^__^
