### ISSUE TITLE
Should ask for File when import image/sound layer is invoked

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#773]
**Synfig version & platform**:
Development Build

**Issue description**:
Linux Mint OS

How to recreate?
**layer->new layer->other->import image**
**layer->new layer->other->sound**

**Comment by ankit-kumar-dwivedi** [comment]
**I am already working on a fix :)**

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I am very strongly willing to remove the multiple code file present for the same work.
There is a dedicated file for only image import but also there is more general import function written which makes the "image import" redundant So I would like to tell you that I am willing to delete the dedicated code for only "sound" and only "image import" and use the function from general import for these two layers. Would love to hear your opinion on this (^_^)
Thank you !

**Comment by morevnaproject** [comment]
Can you please be more specific which functions you are referencing (and in which files)? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Ah my bad I though 
https://github.com/synfig/synfig/blob/6b3c81c2fb73a7a96cfddb0e43de54fe7a61da2e/synfig-studio/src/gui/canvasview.cpp#L3381 
this to be only for images. Which created all this confusion sorry for that!

**Comment by morevnaproject** [comment]
No problem! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject do we really need these 2 options? when there is "import" which can import any file

**Comment by morevnaproject** [comment]
Do you mean those two options? -

> layer->new layer->other->import image
> layer->new layer->other->sound

**Comment by ankit-kumar-dwivedi** [comment]
Yes aren't these two options redundant @morvenaproject

**Comment by morevnaproject** [comment]
Each option produces different type of layer - Image Layer and Sound Layer.

**Comment by ankit-kumar-dwivedi** [comment]
> @morevnaproject do we really need these 2 options? when there is "import" which can import any file



> Yes aren't these two options redundant @morvenaproject
> […](#)

@morevnaproject I am sorry for my confusing comment  ¯\\_(⊙︿⊙)_/¯
I wanted to explain 2 points:

1.  The two options "Import image" and "sound" are meant to import image and sound files. 
![Screenshot from 2019-03-27 19-59-58](https://user-images.githubusercontent.com/37617951/55085447-b44ce700-50cc-11e9-8c5d-1a1fb6cdce55.png)
but when the same work can be done using the "File->import.."
![Screenshot from 2019-03-27 19-57-58](https://user-images.githubusercontent.com/37617951/55085589-ec542a00-50cc-11e9-8f56-13c2c9fe13a2.png)
![Screenshot from 2019-03-27 20-10-20](https://user-images.githubusercontent.com/37617951/55085600-efe7b100-50cc-11e9-87cf-02e1496f2b89.png)
**as we can see it can import any supported file type including image and sound.**
then do we  really need two extra option that are doing the same work?

1.  The second point is **File->Import** is clearly visible and **layer->new layer->other->import image
layer->new layer->other->sound** are kind of not visible in one glance and are hidden.

**Comment by morevnaproject** [comment]
1. "File" -> "Import" is just an overlay, which creates particular type of layer depending on chosen filetype. "Image Layer" and "Sound Layer" are two completely different types of layers, which do different functions. First draws an image on workarea. Second draws nothing, but instructs Synfig to play sound at particular moment.

2. Those layers are displayed in **layer->new layer->other** menu because **layer->new layer** menu displays every layer available in Synfig. We can add a hack to hide them, but I see no reason for that as there are no harm if they are present there. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
I just forgot about this issue. :sweat:
@morevnaproject I remember last time when I was trying to work on this issue I was not able to find the function which is called with **layer->new layer->other->import image**
So I ended up with
 ```
	//! Creates a new layer, of type \c id at the top of the layer stack
	synfig::Layer::Handle add_layer_to(const synfig::String &id, const synfig::Canvas::Handle &canvas, int depth = 0);
```
from [canvasinterface.h](https://github.com/synfig/synfig/blob/master/synfig-studio/src/synfigapp/canvasinterface.h)
Can you let me know if there is a specific function called for **layer->new layer->other->import image** and **layer->new layer->other->sound**

**Comment by morevnaproject** [comment]
As far as I know, there are no special function for **layer->new layer->other->import image**. This menu is constructed dynamically from the list of all available layers.

**Comment by ankit-kumar-dwivedi** [comment]
Thanks for quick reply. So I guess it simply means I need to check whenever a new image/sound layer is created it should not have an empty filename param

**Comment by morevnaproject** [comment]
That's good idea! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Added a PR please review when you have time [^_^]
@morevnaproject
