### ISSUE TITLE
Create a new Panel which displays sound waveform

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#783]
Many people request to have an ability to load a sound file and display its waveform in sync with animation.

Synfig already can import sounds, but can't display waveform.

I suggest to add a new panel, similar to Graphs Panel, but instead of displaying parameter graphs it will display a waveform of given file.

Example mockup:

![screenshot_003](https://user-images.githubusercontent.com/332868/54692684-f8356e80-4b57-11e9-86fe-0491187676fc.png)

1 - Waveform
2 - Button to load file. 
3 - Timeline
4 - Current time cursor

Expected workflow:
User click the button and choosing a file. After that waveform for selected file is displayed in this panel. At the top of the panel you can see a timeline (just like in Graphs Panel), and waveform should be synchronized to it. Just like in Graphs Panel, user can hover cursor over timeline and change scale by scrolling mouse wheel. This also changes scale of waveform view.

Related links:
- https://wiki.synfig.org/Graphs_Panel
- https://wiki.synfig.org/Dev:Adding_a_Panel_-_Part_I
- Waveform generation code in "rainynite-studio" app by @caryoscelus - https://github.com/caryoscelus/rainynite-studio/blob/master/studio/canvas/editors/waveform.cpp

**Comment by maitreyi0505** [comment]
I tried to compile codes from the graphs panel and the waveform source code .I made changes in studio/src/gui file. I created 4 files namely: docks_sound.h and docks_sound.cpp in docs folder, widget_sound.cpp & widget_sound.h where I added the code of the rainynite waveform generation with few changes according to synfig code but the new panel isn't still visible, are there any other files I need to make changes in?

**Comment by morevnaproject** [comment]
@maitreyi0505 Can you please push your current code to GitHub, so I can look at it? ^__^

**Comment by maitreyi0505** [comment]
i made a pull request according to files created and the changes made by me, but the code isn't complete though i tried doing whatever i understood  :)

**Comment by morevnaproject** [comment]
@maitreyi0505 Apologies for delay with response. Please check my comment on PR. ^__^

**Comment by maitreyi0505** [comment]
No worries, I will be working on it!

**Comment by maitreyi0505** [comment]
For the panel to be shown, I think is it necessary to create an sound.sif and integrating it; also I couln't find any folder where icons are stored, may I get some help on it? ^_^

**Comment by morevnaproject** [comment]
All icons are stored here - https://github.com/synfig/synfig/tree/master/synfig-studio/images

**Comment by rodolforg** [comment]
@morevnaproject , should this panel be canvas-specific? I mean, for a given open file.
If I change to another SynfigStudio tab, it would have another parameters (ie., another loaded sound).

**Comment by morevnaproject** [comment]
Yes, we need it canvas-specific. ^__^

**Comment by rodolforg** [comment]
So, if @maitreyi0505 doesn't care, I'd like to solve this issue.

**Comment by morevnaproject** [comment]
@rodolforg Awesome! It is yours now! ^__^
