### ISSUE TITLE
Flatpak builder fails to compile Synfig Studio 1.2.2

### ISSUE THREAD

**Issue by eszlari** [synfig/synfig#784]
build log:
https://flathub.org/builds/#/builders/28/builds/181

**Comment by morevnaproject** [comment]
I can see following error in build log (https://flathub.org/builds/#/builders/28/builds/181/steps/6/logs/stdio):

```
/usr/include/c++/8.2.0/bits/basic_string.h:1058: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
synfig(9709) [11:35:43 PM] warning: Time(): No unit provided in time code and frame rate is unknown! Assuming SECONDS
```

Could that be related with use of gcc version 8?

**Comment by eszlari** [comment]
But Debian seems to have no problem compiling it with gcc8:
https://packages.debian.org/sid/synfigstudio

**Comment by morevnaproject** [comment]
But which version of GCC Debian has? Does it uses 8.2.0? (numbers after dot matter)

**Comment by ice0** [comment]
synfig(9764) [01:01:17 PM] warning: Time(): No unit provided in time code and frame rate is unknown! Assuming SECONDS
synfig(9764) [01:01:17 PM] info: target name not specified - using png
echo " Delete \"\$INSTDIR\\share\\pixmaps\\animate_loop_icon.png\"" >>./unimages.nsh
echo " File \"images\\animate_seek_next_frame_icon.png\"" >>./images.nsh
synfig(9770) [01:01:17 PM] warning: Time(): No unit provided in time code, assuming FRAMES ("4")
synfig(9770) [01:01:17 PM] info: target name not specified - using png
echo " File \"images\\animate_play_icon.png\"" >>./images.nsh
**synfig(9774) [01:01:17 PM] error: -1 layers not yet deleted!**
echo " Delete \"\$INSTDIR\\share\\pixmaps\\animate_seek_next_frame_icon.png\"" >>./unimages.nsh
echo " File \"images\\animate_pause_icon.png\"" >>./images.nsh
echo " File \"images\\animate_seek_prev_frame_icon.png\"" >>./images.nsh
echo " Delete \"\$INSTDIR\\share\\pixmaps\\animate_play_icon.png\"" >>./unimages.nsh


https://flathub.org/builds/#/builders/12/builds/829

**Comment by eszlari** [comment]
This was fixed by @ice0 (https://github.com/flathub/org.synfig.SynfigStudio/commit/889bde68f0c877635f9e90ad54687c27913060a9), so I'm closing the issue.
