### ISSUE TITLE
sifz-file broken (cannot open old project) after adding sceleton

### ISSUE THREAD

**Issue by hansoskar** [synfig/synfig#786]
SynfigStudio-1.2.2 & linux64: (tried to open it also with version 1.3.11 with the same result)

**Issue description**:
After the last change I cannot open my project anymore.
Instead I get the following errormessage:

Unable to load "projectpath/name.sifz":

* projectpath/name:<bone>:12652:
error:<bone> is missing link 0 (name)

The last two lines appear for a whole bunch of bones.
Beforehand I just added my first skeleton-layer and linked the bones to some advanced-outline layers.

Is there any way to fix this problem or rescue the previous progress?

Best and thanks for this amazing tool

hansoskar

**Comment by morevnaproject** [comment]
Hi! I guess you copied your skeleton layer from another file, right?

**Comment by morevnaproject** [comment]
P.S. As a quick hint for rescue: 
You can rename your file by replacing ".sifz" at the end to ".sif.gz". After that you can decompress it (as GZ archive) - you will get a .sif file, shich is editable XML (can be opened and edited in any text editor).

After editing it is not necessary to pack file again into .gz - SYnfig can read .sif files without a problems.

**Comment by hansoskar** [comment]
Hey,
thanks for the quick response. No I've build the skeleton layer directly. Thanks for the rescuing Tip, I will try it out!

Best
hansoskar

**Comment by hansoskar** [comment]
Thanks the rescuing was successful.

First I didn't delete the whole layer with all interactions and the program was crushing without an error message - but now it's working again (without the broken layer).

Best
hansoskar

**Comment by morevnaproject** [comment]
Great to hear that! ^__^

**Comment by Neimed** [comment]
Hi, thank so much for the tip !
how can i fix it when i open the xml ? my .sif doesn't open either
thanks

**Comment by morevnaproject** [comment]
@Neimed Can you please attach file here?

**Comment by Neimed** [comment]
Of course !
[seq 3.sif.zip](https://github.com/synfig/synfig/files/4547063/seq.3.sif.zip)
thx

**Comment by Neimed** [comment]
i finally found de problem, some group was linked with deleted bones or bones in other files. I just replaced ```
<bone_link type="transformation">
                    <bone>
                      <bone_valuenode type="bone_object" guid="7F6DD599F38515A8733C1AFB759FBD77"/>
                    </bone>
                    <base_value>
                      <composite type="transformation">
                        <offset>
                          <vector>
                            <x>-0.0994623452</x>
                            <y>-0.0016387985</y>
                          </vector>
                        </offset>
                        <angle>
                          <angle value="117.906601"/>
                        </angle>
                        <skew_angle>
                          <angle value="-382.488831"/>
                        </skew_angle>
                        <scale>
                          <vector>
                            <x>1.1055349112</x>
                            <y>2.2411241531</y>
                          </vector>
                        </scale>
                      </composite>
                    </base_value>
                    <translate>
                      <bool value="true"/>
                    </translate>
                    <rotate>
                      <bool value="true"/>
                    </rotate>
                    <skew>
                      <bool value="true"/>
                    </skew>
                    <scale_x>
                      <bool value="true"/>
                    </scale_x>
                    <scale_y>
                      <bool value="true"/>
                    </scale_y>
                  </bone_link> 
```
with 
```
<composite type="transformation">
                              <offset>
                                <vector>
                                  <x>2.7220680714</x>
                                  <y>3.1222674847</y>
                                </vector>
                              </offset>
                              <angle>
                                <angle value="90.818924"/>
                              </angle>
                              <skew_angle>
                                <angle value="-358.544250"/>
                              </skew_angle>
                              <scale>
                                <vector>
                                  <x>0.9998183846</x>
                                  <y>0.6001843810</y>
                                </vector>
                              </scale>
                            </composite> 
``` 
when the "guid" did not match any bone present in the file

thank you SO MUCH for this magic software and have a nice day

**Comment by morevnaproject** [comment]
Hi! Sorry, I wasn't able to help earlier. ^__^" Happy to hear you've got this solved!
