### ISSUE TITLE
Synfig forums not working

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#789]
I don't know if this is the right place for this but I don't know where else to ask this. 
Till when can we expect the Synfig [forums](https://forums.synfig.org/) to be back up and running?

![synfig_forums](https://user-images.githubusercontent.com/30872212/54897463-84e08380-4eee-11e9-88cb-4b3c01865582.jpg)

**Comment by morevnaproject** [comment]
Fixed now. Thank you! ^__^
