### ISSUE TITLE
Animate rope/snake/cable effectively

### ISSUE THREAD

**Issue by hansoskar** [synfig/synfig#791]
Hi,

I have a project in my mind with a tightening rope.
I've tried out different ways but failed with all of them.

What makes it difficult:
 - two colored structure
 - item is flexible in one direction but restricted in the second direction
 - all parts are anyway strictly connected

Maybe there is already a good solution but I didn't figure it out (It's my first project with synfig).

Functions that might be helpful to solve the problem but I was not able to find:
 - define (fixed) distance of two nodes (perfect would be a minimum and maximum distance for animations)
 - a "spline deformation layer" you can connect to a group of geometric layer to transfer the motion of the simple spline to the group of layers (compression and rotation might still be difficult to implement)
 - a pattern-fill option for outline layer (e.g. striped with variable angle and with frame)

Best
hansoskar

**Comment by Jose-Moreno** [comment]
Hi, I feel you're asking about too many things in a single issue. If you want help for creating tension dynamics you should try the forum, but would probably be told that the only way would be to have a physics system in the program. 

If you want to request a certain feature it's better for the project maintainers that you submit a single feature per issue so developers can keep track of and discuss in detail.

I Personally would like a spline-controlled deformation layer, or the possibility to apply a shape & angle aware pattern overlay to a vector path, but right now you'd probably have to use a chain of bones and animate each one separately (I know, not ideal) to deform a bitmap layer to get what you want.

Still those three ideas are not mutually exclusive so I heartily suggest you to file two more reports, one for the spline-controlled deformation layer and one for the shape aware pattern fill and modify the current one to ask only for a physics system to be included into Synfig so other devs can consider it and make drafts for such features.

Either way good luck, although if you need a quick solution try out doing a rope simulation of a subdivided plane with a rope texture in Blender and export the final image sequence into Synfig to continue your work meanwhile. :ok_hand:

**Comment by morevnaproject** [comment]
Yes, such topics are better suited for discussion on forums - https://forums.synfig.org/

I encourage to open discussion there and submit separated feature requests here. ^__^
