### ISSUE TITLE
Image renders wrong at high resolution (3840x2160)

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#796]
**Synfig version & platform**:
Latest master branch, commit 7ef36d286be8a83e4415670835b6b62456e21b1a

**Issue description**:
I have a sample file - 
[poster-bug.zip](https://github.com/synfig/synfig/files/3017940/poster-bug.zip)

When I open it in Synfig Studio here is how it looks (notice Preview mode is enabled):
![screenshot_002](https://user-images.githubusercontent.com/332868/55158507-b2009080-5191-11e9-8bb1-66e760e73c32.png)

That's OK.

Now, if I enable "Final" preview mode, then it looks like this:

![screenshot_003](https://user-images.githubusercontent.com/332868/55158556-d0ff2280-5191-11e9-803f-882765290a2d.png)

That's also OK.

Now, I am trying to render it to resolution 1920x1080. Got the following result:

![poster-youtube-alt10-ru-bug-1920](https://user-images.githubusercontent.com/332868/55158629-f0964b00-5191-11e9-84f0-f4d0f92b4627.png)

That's also ok.

But when I try to render it in resolution 3860x2160, I get the following (notice the white glow around his head, like in Preview rendering mode):

![poster-youtube-alt10-ru-bug-3840](https://user-images.githubusercontent.com/332868/55158743-318e5f80-5192-11e9-9965-c7dbd9d25d8d.png)

That result is not correct.

**Comment by blackwarthog** [comment]
In latest master synfig always render a second picture (a lot of glowing)

and also GIMP has the same bug:

![poster-v0-layer-3-bg](https://user-images.githubusercontent.com/5143743/62410814-cd195c00-b5da-11e9-9649-99f061f21130.png)

[poster-v0-layer-3-xcf.zip](https://github.com/synfig/synfig/files/3463717/poster-v0-layer-3-xcf.zip)

seems this glowing was painted in picture

**Comment by morevnaproject** [comment]
> In latest master synfig always render a second picture (a lot of glowing)

Yes, I can confirm that. This is incorrect result.

Here's how it looks when PNG file is mixed wiht black background in Krita:

![screenshot_002](https://user-images.githubusercontent.com/332868/62463472-50da7080-b7b4-11e9-9bdd-f64577fd257f.png)

Same image, 1:1 scale -

![screenshot_003](https://user-images.githubusercontent.com/332868/62463487-5932ab80-b7b4-11e9-9e75-b75effeeb194.png)

This is what I've got in gimp (2.8.22) -

![screenshot_005](https://user-images.githubusercontent.com/332868/62463531-7bc4c480-b7b4-11e9-8a36-79865607f41e.png)

> and also GIMP has the same bug:

I wasn't able to  open the file you provided. Probably you are using newer version of GIMP?

![screenshot_006](https://user-images.githubusercontent.com/332868/62463604-a020a100-b7b4-11e9-8a66-06fffeb3d309.png)

**Comment by morevnaproject** [comment]
@blackwarthog Can you please take a look at this?

**Comment by blackwarthog** [comment]
> @blackwarthog Can you please take a look at this?

Okaaay....

By historical reason Synfig applies gamma 2.2 to result image.
This have no matter in common case - we just see colors at the screen and don't think about internal digital color values.

But then we import image we already can see the difference. We can compare the look of image in siynfig and in any other  editor. And more - we can import image rendered by Synfig and see that it becomes much brighter.

To avoid this problem Synfig just applies anti-gamma (1/2.2) to all imported images.
Seems problems solved... but

gamma of 2.2 is a color^(1/2.2)
so antigamma is a color^2.2


Look how it works with alpha blending over the solid black background channel and gamma 2:
   gamma is color^2
   antigamma is sqrt(color)

   we have a color RGBA:
       1, 1, 0.5, 0.5
   with blending without alpha we expect result:
       1, 1, 0.25, 1

   apply antigamma:
       1, 1, 0.25, 0.5
   apply alpha blending :
       1, 1, 0.125, 1
   finally apply gamma:
       1, 1, 0.354, 1 - not ideal result

**Comment by blackwarthog** [comment]
to avoid this problem i've implemented gamma for alpha channel

but i'm afraid that this may affect a looking of previous synfig movies
need some testing

**Comment by morevnaproject** [comment]
Confirmed - it is fixed now.  Thank you!

Before fix:
![155-2](https://user-images.githubusercontent.com/332868/64907579-a6dcf500-d71e-11e9-9459-93f40820d10e.png)

After fix (correct result):
![155-1](https://user-images.githubusercontent.com/332868/64907601-e277bf00-d71e-11e9-8d1a-059588362bf0.png)

Thanks again!
