### ISSUE TITLE
separate views aka "personas" for different process  (UX)

### ISSUE THREAD

**Issue by corbeeresearch** [synfig/synfig#798]
Just a suggestion: Separate views for different process such as drawing, animation, frame-by-frame, bone rigging to make it less busy.

This would make the app less intimidating for beginners and may allow other creative ideas to flow out much easier in future developments...

**Comment by morevnaproject** [comment]
This is already implemented -
![screenshot_001](https://user-images.githubusercontent.com/332868/55278666-f9c61a00-5341-11e9-8ba4-c6f326e4762f.png)
