### ISSUE TITLE
Import info should be Attempting to import FILE from DIR

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#801]
**Synfig version & platform**
 latest development builds

**Issue description**:
In debug mode I get info
**synfig(23888) [11:55:32  IST] info: Attempting to import /home/allievo/Pictures/Screenshot from 2019-01-04 22-03-22.png**

Should be
 **synfig(23888) [11:55:32  IST] info: Attempting to import 2019-01-04 22-03-22.png from /home/allievo/Pictures/Screenshot**

**Comment by igordsm** [comment]
It seems this was fixed since the report. Clicking `Layer -> New Layer -> Other -> Import Image` now prints

`synfig(2604) [22:36:51] info: Attempting to import /home/igor/Documents/curso_gimp/pikachu.png
`

**Comment by ankit-kumar-dwivedi** [comment]
@igordsm thanks.
Closing as I cannot reproduce it now
