### ISSUE TITLE
Synfig freezes when "Edit image in external tool" command activated

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#806]
@ankit-kumar-dwivedi I've just found one more issue in implementation of  #516.
After I choose "Edit image in external tool" command editor application gets opened, but Synfig gets unresponsive until I close the editor app. It would be better to allow user work in Synfig while editor app open.

**Comment by ankit-kumar-dwivedi** [comment]
Oh my my is this happening in debug? or in production build too
the reason could be they are using the same terminal process

**Comment by ankit-kumar-dwivedi** [comment]
I guess if I open a new terminal process for opening in external tool then it should work

**Comment by morevnaproject** [comment]
This happens in production build. I think, this is because you use ```Glib::spawn_command_line_sync()```. There should be something like ```spawn_command_line_async``` (for asynchronous execution). ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Or i can use system as I used in case of _APPLE_
Can you please confirm is the problem there in apple too?

**Comment by ankit-kumar-dwivedi** [comment]
PR sent! [^_^]
