### ISSUE TITLE
Improve Synfig Usability and UX

### ISSUE THREAD

**Issue by mikecohen12** [synfig/synfig#809]
Someone just gave synfig a bad review.

https://www.youtube.com/watch?v=-2iRm1PC2Jw

I think the best way to prevent users for getting discouraged is to create a separate experimental workspace that's designed for user's ease of use. If you watch the review, the artist didn't have trouble knowing what to do on pencil2d and blender grease pencil, but struggled using synfig.

I also think it may have something to do with how the other animation software's brush engine functions as expected. Maybe there's also a need to refine the brush engine?

**Comment by BobSynfig** [comment]
In this very review video, she is trying to use Synfig as a 2D/Drawing like Pencil2D and Blender (2D anim functionnalities)...
This is not the point of Synfig which is dedicated to vector animation (with some bitmap support added lately)
The 2D "classical" animation software work only as layers of bitmap, with frames flipped one after the other.
They are a lot easier to make evoluate (and to use) than a vectorial animation software.
On the other hand, Synfig relies on a lot of calculations for any of its parameters (only values at waypoints/keyframes are defined), blending modes and so on.
She could have compared with Krita also, which would have been more appropriate than Synfig.
Not surprising she was lost, how to compare a flipbook with a "morphing" software :P
Synfig deserves a bit of invest of time before to master it!

P.S.: There are already several requests like this (forums+issues), no need to create multiple issues...

**Comment by morevnaproject** [comment]
Closing issue as this is more like a discussion topic for forums.
