### ISSUE TITLE
"Edit image in external tool" does not works correctly when called from workarea

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#810]
@ankit-kumar-dwivedi When I right-click image on workarea I see "Open file" menu entry, which is expected to behave the same as "Edit image in external tool" command. But when I click it, Synfig opens associated image viewer, not the editor app specified in preferences.

![screenshot_001](https://user-images.githubusercontent.com/332868/55900218-e2fcae80-5bf0-11e9-8c8a-2264905fdd9b.png)

**Comment by ankit-kumar-dwivedi** [comment]
I see.. Will fix that (^_^).
