### ISSUE TITLE
Build broken due to Travis 4MB log size limit

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#812]
**Synfig version & platform**:
Synfig version: second last commit ([4738a94](https://github.com/synfig/synfig/commit/4738a94ea9fbebe1c225b2b61ae0dfb116afe2a7))
platform: Travis build

**Issue description**: Travis build fails on the OS X High Sierra, giving error : 
`The job exceeded the maximum log length, and has been terminated`

**Possible Fixes**: I was reading the possible fixes here travis-ci/travis-ci#1382. And this hack([link](https://stackoverflow.com/questions/26082444/how-to-work-around-travis-cis-4mb-output-limit/26082445#26082445)) seems reasonable. 
Another solution could be to use `make --quiet` instead.

**Comment by AnishGG** [comment]
The above mentioned hack seems to have worked for osmdroid/osmdroid#288

**Comment by AnishGG** [comment]
@morevnaproject, If the given fix seems appropriate, I would like to work on this. ^_^
Please let me know.

**Comment by morevnaproject** [comment]
@AnishGG That would be awesome! The fix looks good, your help is much appreciated here. ^__^
