### ISSUE TITLE
Some custom fonts use wrong glyphs

### ISSUE THREAD

**Issue by Domarius** [synfig/synfig#815]
**Synfig version & platform**:
SynfigStudio-1.3.11-testing-19.02.09-linux64-9583a.appimage

**Issue description**:

- Make a new project, place the attached font "ARCO.ttf" in the same folder. 
[ARCO.ttf.tar.gz](https://github.com/synfig/synfig/files/3088549/ARCO.ttf.tar.gz)
- Create a new text object on the stage, set the test to something like "Test text".
- In the object properties, change the "Font Family" property to the name of the font file "ARCO.ttf" (as per the [instructions here](https://morevnaproject.org/2016/09/08/set-font-style-synfig/)) 
- Note the text is displayed as "AAAAAAAAAAAAA" but the correct font is used.  See below screenshot.
![image](https://user-images.githubusercontent.com/7411541/56272390-f6060600-613d-11e9-927b-5b2a48354802.png)
![image](https://user-images.githubusercontent.com/7411541/56272422-03bb8b80-613e-11e9-83e3-3492152c1ace.png)

**Comment by BobSynfig** [comment]
This ttf file is surely bugging, using other .ttf files it works.
I tried to download it from https://www.dafont.com/arco.font to see if it was your copy which was bugged but I faced the same problem.
Note that the included "ARCO for OSX.otf" works perfectly ;)

**Comment by Domarius** [comment]
Ohh, that's interesting!  Yes I did notice other TTF files are fine, I just figured this one had something particular about it that needed to be accounted for.  I'll just use the OSX version for now!

**Comment by Domarius** [comment]
I guess we can close this, the creator of the font file did mention that a separate version had to be created for OSX, so perhaps it's a strange way they created the TTF.
