### ISSUE TITLE
Virustotal.com detected a trojan @ Win64 1.2.2 build

### ISSUE THREAD

**Issue by cdr8H** [synfig/synfig#827]
**Synfig version & platform**: 1.2.2 Win64

**Issue description**: virustotal.com -> trojan detected at Win64 1.2.2 build

Download from https://downloads.synfig.org/stable/SynfigStudio-1.2.2-18.09.14-win64-286f1.exe ->Ikarus + Trapmine = https://www.virustotal.com/gui/file/8976eecc273e3c22c299c0a7c4aced53a1e032acb67b76479cccfd2e472c8515/detection

**Comment by BobSynfig** [comment]
False positive...
2 "antiviruses" on 61...
It's open-source, the toolchain script (docker image) is available...
You can compile yourself, or... change for a real OS ;)

**Comment by morevnaproject** [comment]
Hi @cdr8H! Please check this article in our knowledge base - https://desk.zoho.com/portal/morevnaproject/kb/articles/synfig-studio-installer-reported-as-malicious-file-by-virustotal-com

We have reported this issue to Ikarus and Trapmine developers.
Waiting for their response. ^__^

Relevant links:
- Ikarus contact email for false-positives taken from https://www.opswat.com/blog/what-do-i-do-if-engine-detects-my-safe-file-threat
- Trapmine contacted via support email from https://trapmine.com/company/contact-us/

Text sent to them:
```
Dear developers of Ikarus/Trapmine antivirus!

My name is Konstantin Dmitriev, I am maintainer of Synfig opensource animation software.

Recently we've got a claims that binaries of our software are treated by your antivirus as malware.
See link at ViruaTotal online scanner - https://www.virustotal.com/gui/file/8976eecc273e3c22c299c0a7c4aced53a1e032acb67b76479cccfd2e472c8515/detection

This is definitely a false-positive - our binaries are cross-compiled in a secured Linux environment, so there are no possibilities they can be infected. I would appreciate if you will make investigation about this issue.

Here is a pubic link to our installer file that is detected as problematic - https://downloads.synfig.org/stable/SynfigStudio-1.2.2-18.09.14-win64-286f1.exe

Any assistance is appreciated.

Best Regards,
Konstantin
```

**Comment by morevnaproject** [comment]
Got a reply from Ikarus team:

```
Many thanks for the delivered file.

***** false-positive *****

The false positive was removed and should not occur any more after our next database update. 
```

The email to Trapmine returned with an error saying "failed to deliver for this mailbox". I have re-sent same email to their general info address (found at https://trapmine.com/company/contact-us/).

**Comment by BobSynfig** [comment]
I just returned "by curiosity" on the link given on the top.
The status didn't change.
But there is a "refresh" button on the right.
Pushing it rescans the file using the current signatures of antiviruses...
Guess what?
0/68 :innocent:
"Issue solved" ^__^

**Comment by ice0** [comment]
Awesome!

**Comment by morevnaproject** [comment]
@BobSynfig Thank you for taking care on checking! ^__^
