### ISSUE TITLE
Sound doesn't play when rendering is done

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#829]
**Synfig version & platform**:
Latest development build, commit 3234bc04e6441f843e79f832923448a7a8d09edc

**Issue description**:
As per #648, when rendering is done the chime sound should be playing.
This only happens when you render for the first time.

Steps to reproduce:
1. Start Synfig.
2. Render file - sound plays after completion.
3. Render file again - no sound plays after completion.

**Comment by morevnaproject** [comment]
Ping @BobSynfig ^__^

**Comment by BobSynfig** [comment]
I recompiled my branch (using SDL2) to be sure, everything was fine.
It seems it is a consequence of the commit "remove SDL, use synfig::SoundProcessor instead" https://github.com/synfig/synfig/commit/32d01dd21605f024e96f6e9094597e075750935f
Probably a failing reinitialization of the position in the sample before replay in synfig-studio/src/gui/render.cpp (bottom of the commit page)

**Comment by morevnaproject** [comment]
@BobSynfig Oh, thanks for looking at this! 

@blackwarthog any ideas? ^__^

**Comment by morevnaproject** [comment]
@blackwarthog can you take a look, please? ^__^
