### ISSUE TITLE
Automatic assigment of extension when rendering gets messed up after saving

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#830]
**Synfig version & platform**:
Latest development build - 3234bc04e6441f843e79f832923448a7a8d09edc

**Issue description**:
As per #627: when user chooses rendering target. Synfig should automatically change extension for output filename.
But the extension gets messed after user saves Synfig document.

Steps to reproduce:

1. Open Synfig and create new empty file. Save the file somewhere.
2. Choose "File" -> "Render" from menu.
3. Choose "png" from "Target" dropdown -> the output filename extension will change to ".png"
4. Close Render Settings window (no need to render anything, just close it).
5. Choose "File" -> "Render" from menu again -> the output filename extension is still ".png", that's expected behavior, all good.
6. Close Render Settings window again.
7. Choose "File" -> "Save" from menu.
8. Choose "File" -> "Render" from menu again.
9. You can see the output filename extension is changed to ".avi" (while target remains "png").

![screenshot_005](https://user-images.githubusercontent.com/332868/57759118-73b03800-7723-11e9-867f-65c4056b97a4.png)

**Comment by morevnaproject** [comment]
Ping @ankit-kumar-dwivedi ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> Ping @ankit-kumar-dwivedi ^__^

Will be back on development after 17 ! Finally exams are going to end! 
Saving the extension state at the time of saving look good at first sight. Well look into it further :-)

**Comment by morevnaproject** [comment]
Got it. Good luck with the exams! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject can you tell me what is the expected behavior after

>     1. Open Synfig and create new empty file. Save the file somewhere.
> 
>     2. Choose "File" -> "Render" from menu.
> 
>     3. Choose "png" from "Target" dropdown -> the output filename extension will change to ".png"
> 
>     4. Close Render Settings window (no need to render anything, just close it).
> 
>     5. Choose "File" -> "Render" from menu again -> the output filename extension is still ".png", that's expected behavior, all good.
> 
>     6. Close Render Settings window again.
> 
>     7. Choose "File" -> "Save" from menu.

now when we Choose "File" -> "Render" from the menu again what should actually be there?

Also according to my understanding saving the file somehow reset the target to .avi and the target was selected as png this brings us to the current situation!

I am thinking to tackle this as follow:
```
do check( that selected target and filename extension match)
if yes then do nothing
else change the extension according to selected target in dropdown
```
Your views on this? (^_^)

**Comment by morevnaproject** [comment]
> now when we Choose "File" -> "Render" from the menu again what should actually be there?

The extension should be corresponding to selected target.

> I am thinking to tackle this as follow:
>> do check( that selected target and filename extension match)
>> if yes then do nothing
>> else change the extension according to selected target in dropdown

This will work, as a workaround. But it's better to search for the real case why this happens. ^__^

In our situation we can see the code is inserting ".avi" at the end of filename. 
So, you can start by searching ".avi" string in "synfig-studio" directory. This can give you some clues.

```
cd synfig-studio/
git grep "\.avi"
```

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject after we click "save" then save_as(), is called which contain the following line
https://github.com/synfig/synfig/blob/ecdee91a6c1795edf4b5b99a524b1b491090808e/synfig-studio/src/gui/instance.cpp#L291
this line responsible for extension mismatch.

This is calling set_entry_filename() which is appending the filename with .avi extension
So each time **we save a file the set_entry_filename is called. Which by default will add .avi as the new file is loaded.**
_To fix this_ we can add a check before appending the extension in set_entry_filename() 
- which file type was selected in the combobox and if it is "auto" which is when a fresh animation is being created then append .avi 
- otherwise check for the corresponding selection and modify filename according.

else we can do what I said earlier

> I am thinking to tackle this as follow:
> 
> ```
> do check( that selected target and filename extension match)
> if yes then do nothing
> else change the extension according to selected target in dropdown
> ```

**Comment by morevnaproject** [comment]
> after we click "save" then save_as(), is called which contain the following line ...

Good catch! ^__^

> To fix this we can add a check before appending the extension in set_entry_filename() ...

This is the right way to go!

I also think, it is possible to merge `set_entry_filename()` with `on_comboboxtext_target_changed()` function - they actually do the same thing. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> This is the right way to go!
> 
> I also think, it is possible to merge `set_entry_filename()` with `on_comboboxtext_target_changed()` function - they actually do the same thing. ^__^

working on this

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Thank you for PR!
I tested it and found that I was wrong when suggested to merge `set_entry_filename()` with `on_comboboxtext_target_changed()`.

Let me describe what's wrong with behavior after applying PR #830:

1. Open Synfig, create new file and save it as `/tmp/file.sifz`
2. Choose `File - Render`. You will see the `Filename` text is set to `/tmp/file.avi`
3. Change value `Filename` text entry to `/tmp/file-2.avi`
4. From `Target` dropdown select `png`. -> You will see the `Filename` text will change to `/tmp/file.png` (while it should be `/tmp/file-2.png`).

So, I was wrong when said that `set_entry_filename()` and `on_comboboxtext_target_changed()` doing same thing. Sorry for that.

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Thank you for PR!
I tested it and found that I was wrong when suggested to merge `set_entry_filename()` with `on_comboboxtext_target_changed()`.

Let me describe what's wrong with behavior after applying PR #832:

1. Open Synfig, create new file and save it as `/tmp/file.sifz`
2. Choose `File - Render`. You will see the `Filename` text is set to `/tmp/file.avi`
3. Change value `Filename` text entry to `/tmp/file-2.avi`
4. From `Target` dropdown select `png`. -> You will see the `Filename` text will change to `/tmp/file.png` (while it should be `/tmp/file-2.png`).

So, I was wrong when said that `set_entry_filename()` and `on_comboboxtext_target_changed()` doing same thing. Sorry for that.

**Comment by morevnaproject** [comment]
> To fix this we can add a check before appending the extension in set_entry_filename() ...

As a solution we can call `on_comboboxtext_target_changed()` at the end of `set_entry_filename()`.

**Comment by ankit-kumar-dwivedi** [comment]
> As a solution we can call `on_comboboxtext_target_changed()` at the end of `set_entry_filename()`.

Okay @morevnaproject will fix the PR ASAP!
