### ISSUE TITLE
Is the godot code salvageable?

### ISSUE THREAD

**Issue by corbeeresearch** [synfig/synfig#846]
Godot Engine has codes for animation. Would it be able to help Synfig in anyway?
https://github.com/godotengine/godot

https://docs.godotengine.org/en/3.1/getting_started/step_by_step/animations.html
https://www.youtube.com/watch?v=YxEfZQeySGQ

It also has shader and particle systems that might be worth incorporating to synfig
https://www.youtube.com/watch?v=awBfTnmgn7k&list=PLsk-HSGFjnaE4k-X3l6dZAPIoB2QB4eYg&index=2&t=0s
https://docs.godotengine.org/en/3.1/tutorials/2d/particle_systems_2d.html

**Comment by WPFilmmaker** [comment]
shader and particle system look really cool!

**Comment by corbeeresearch** [comment]
yup! definitely ;)

**Comment by morevnaproject** [comment]
@corbeeresearch 
I think this topic is more suitable for discussing on [Synfig Forums](https://forums.synfig.org/) rather than here in GitHub bugtracker. So, please re-submit this topic to forums. Thank you! ^__^

**Comment by zaynopenapp** [comment]
Semoga ada yang bisa menkonvert synfig ke godot. Sehingga lebih cepat tampilannya seperti enve2d/friction2d
