### ISSUE TITLE
[Lottie exporter] Add support for "Invert" parameter

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#859]
We actually should consider adding support for "Invert" parameter in geometric figures, as this feature seems to be used quite often.

List of layers requiring support for `Invert` parameter:
- [x] Star Layer
- [x] Circle Layer
- [x] Polygon Layer
- [x] Rectangle Layer
- [x] Region Layer
- [x] Outline Layer

I think there is no need to implement support animation for `Invert` parameter.

I am not sure if it worth to implement support for `Invert` parameter for those layers:
- Outline Layer
- Advanced Outline Layer

**Comment by AnishGG** [comment]
I tried finding any similar property in lottie during the `Student Application period` for GSoC, but could not find any such property. 
I will give it a try again and search in `effects` provided by Lottie. 
Any suggestions on how to implement this are most welcome. :slightly_smiling_face:

**Comment by morevnaproject** [comment]
I strongly suspect this is not supported by Lottie. I think it is possible to construct a polygon that represents an area with a hole. Something like this:

![screenshot_008](https://user-images.githubusercontent.com/332868/59929602-5cbfdc80-946b-11e9-8298-6ecfcd67656b.png)

(Vertices at top should be close together, so the are no space between them. But I left them separated there to keep idea clear.)

**Comment by morevnaproject** [comment]
Sample file - 
[region with a hole.sifz.zip](https://github.com/synfig/synfig/files/3314848/region.with.a.hole.sifz.zip)

![screenshot_009](https://user-images.githubusercontent.com/332868/59929812-ccce6280-946b-11e9-9cb3-52bbc720f186.png)

**Comment by AnishGG** [comment]
> I strongly suspect this is not supported by Lottie.

There is an invert mask property in lottie, but it's working is different than that of Synfig. I will explore it more and get back to you.


>  I think it is possible to construct a polygon that represents an area with a hole.

Yes, this seems to be a nice suggestion. I will explore this option. But this might require converting all these geometric layers to region layers.

**Comment by morevnaproject** [comment]
> But this might require converting all these geometric layers to region layers.

Yes.

**Comment by AnishGG** [comment]
Invert parameter is not working with `rotate`, `scale` and `translate` layer due to a bug in `Lottie` rendering of pre-composition. I have filed this bug on the Lottie-web github repo.
https://github.com/airbnb/lottie-web/issues/1705

**Comment by morevnaproject** [comment]
Okay, thanks for informing about this! ^__^

**Comment by AnishGG** [comment]
@morevnaproject all the layers mentioned above now support invert parameter. I guess this closes the issue. ^__^

**Comment by AnishGG** [comment]
Closing now. ^_^

**Comment by morevnaproject** [comment]
Awesome!
