### ISSUE TITLE
[Vectorization] Incorrect Output from skeletonizer

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#862]
### This issue is a part of [Vectorization of bitmaps [GSoC 2019]](https://github.com/synfig/synfig/issues/735)

**Issue description**: Different Output from Synfig Skeletonizer -> [see this](https://forums.synfig.org/t/gsoc19-vectorization-of-bitmaps/9815/11?u=ankit)
After further investigating and after the output is passed to Toonz the output was not desirable this means there is somewhere values being changes or incorrect function is used for replacing Tpoint function so this needs to be fixed ASAP

Track the progress here -> https://github.com/synfig/synfig/milestone/5

**Comment by ankit-kumar-dwivedi** [comment]
https://pastebin.com/pR0drUkr @morevnaproject 
The output of synfig and Toonz polygonizer are identical now.
Fixed the error Closing the issue now :)

**Comment by morevnaproject** [comment]
Awesome! ^__^
