### ISSUE TITLE
Sound layer doesn't play.

### ISSUE THREAD

**Issue by limburgher** [synfig/synfig#863]
1.2.2

Steps to Reproduce:
1. Launch synfigstudio
2. Import an audio file (in my case I used ogg file)
3. Play or preview

**Comment by limburgher** [comment]
From reporter:
Pulled the updates from master, built it, but the sound is not playing.

**Comment by morevnaproject** [comment]
@limburgher Can you please provide a sound file you are trying to play?

**Comment by Keyikedalube** [comment]
@limburgher notified me to upload the sound file here:
https://drive.google.com/open?id=1IgnOK4WRb3tQtC4kRJjU7AlWl5AkeGmz

**Comment by blackwarthog** [comment]
this file works fine in synfig master at debian 9

**Comment by limburgher** [comment]
Would mod_libavcodec not being present cause this? libavcodec isn't in Fedora for licensing reasons.

**Comment by blackwarthog** [comment]
> Would mod_libavcodec not being present cause this? libavcodec isn't in Fedora for licensing reasons.

try `melt` commandline utility to check how MLT library works:

    melt Hello.ogg

**Comment by Keyikedalube** [comment]
> Would mod_libavcodec not being present cause this? libavcodec isn't in Fedora for licensing reasons.
> try `melt` commandline utility to check how MLT library works: melt Hello.ogg

melt Hello.ogg 
Hello.ogg.F: No such file or directory

**Comment by limburgher** [comment]
On Fedora, that's been renamed mlt-melt to avoid a conflict with a binary from the freeze package.

mlt-melt music.ogg 
Failed to load "music.ogg"
Failed to load "music.ogg"

**Comment by Keyikedalube** [comment]
> On Fedora, that's been renamed mlt-melt to avoid a conflict with a binary from the freeze package.
> 
> mlt-melt music.ogg
> Failed to load "music.ogg"
> Failed to load "music.ogg"

Same output confirmed.

**Comment by morevnaproject** [comment]
@limburgher @Keyikedalube  Do you use Appimage version or compiled from source?

I have tested the file you provided with the latest commit of master branch (compile d from source) - it works fine on Linux Mint 19.

**Comment by limburgher** [comment]
I see this on the Fedora version and compiled from source.

**Comment by Keyikedalube** [comment]
> Would mod_libavcodec not being present cause this? libavcodec isn't in Fedora for licensing reasons.

Switched to Debian recently...
noticed mod_libavcodec isn't present on this distro too but the sounds are playing alright
*BTW compiled from source*

**Comment by morevnaproject** [comment]
Thanks for responding!

@limburgher  I think this is related with MLT package shipped with Fedora.

@Keyikedalube `mod_libavcodec` is not used for sound playback, so it's ok if it is not compiled.

**Comment by morevnaproject** [comment]
@limburgher Please try AppImage version, which uses its own version of MLT - https://downloads.synfig.org/stable/SynfigStudio-1.2.2-18.09.14-linux64-286f1.appimage

**Comment by limburgher** [comment]
Yeah, that worked. Do you know what mlt it uses?

**Comment by ice0** [comment]
If I remember correctly, we use MLT 6.6 for AppImage. But, in my opinion, the reason it doesn't work on Fedora is because of the supported codecs and compilation options used to build MLT. What version of Fedora are you using? I want to reproduce this problem locally.

**Comment by morevnaproject** [comment]
> in my opinion, the reason it doesn't work on Fedora is because of the supported codecs and compilation options used to build MLT.

Exactly. Fedora is always picky about multimedia-related stuff and codecs.

**Comment by limburgher** [comment]
Fedora 31. Yes, Fedora is US-based and must comply with US patent law.

**Comment by rodolforg** [comment]
But what would be the trouble with ogg files?

**Comment by limburgher** [comment]
That's an excellent question. I can't imagine it's patent-related. :)

**Comment by morevnaproject** [comment]
@limburgher Can you please check if this sound file will work in your version which compiled from source? - 
[sound-48000.wav.zip](https://github.com/synfig/synfig/files/3851090/sound-48000.wav.zip)

**Comment by limburgher** [comment]
Not on 1.2.2.

**Comment by morevnaproject** [comment]
That's really weird. The file I provided is a raw WAV file, without any codecs. So, the problem is in Fedora's MLT package itself...

**Comment by limburgher** [comment]
Fedora has now updated to 6.18.0, which doesn't help. mlt-melt still won't play the file. I've filed a Fedora bug against mlt. https://bugzilla.redhat.com/show_bug.cgi?id=1772924

**Comment by ice0** [comment]
Here is a short conversation with MLT developers (https://github.com/mltframework/mlt/issues/504)

**Comment by limburgher** [comment]
So essentially because mlt relies so strongly on ffmpeg, it's effectively useless in Fedora, where we cannot ship ffmpeg?

**Comment by ice0** [comment]
We decided to see if we could update libvorbis support in MLT. If yes, then problem will be solved.

**Comment by Keyikedalube** [comment]
At the mean time, this same issue was reported for Synfig flatpak version.

https://github.com/flathub/org.synfig.SynfigStudio/issues/5

That issue was closed with a fix two days ago. Collaborators confirmed the sound layer works.
Fedora users can switch to the flatpak version.

**Comment by limburgher** [comment]
So you're saying I can't fix the Fedora version, and should retire synfigstudio from Fedora?

**Comment by ice0** [comment]
We can resolve this issue by using MLT compiled with libvorbis support. I think Dan can reanimate it in the next MLT release. If not, i will try to do it myself.

**Comment by limburgher** [comment]
I attempted this locally using the --enable-vorbis flag and removing src/modules/vorbis/deprecated. That built the module but it didn't seem to work. I may be missing something.

**Comment by blackwarthog** [comment]
> I attempted this locally using the --enable-vorbis flag and removing
> src/modules/vorbis/deprecated. That built the module but it didn't seem to work. I may be missing something.

Can you try to call `melt tone` or `melt noise` to check the own MLT functionality?

**Comment by limburgher** [comment]
Picture appears, and sound plays.

**Comment by morevnaproject** [comment]
The commit 1f4abf1812809da6b2a61d7702b4f41a81d6920e adds support for libvorbis backend when playing sound in Synfig via MLT. 

@limburgher @Keyikedalube  Can you please check if ogg file plays on Fedora in the latest version compiled from source?

**Comment by Keyikedalube** [comment]
@morevnaproject I don't use Fedora now. Needed synfig sound support so badly (because of project deadline schedule) I had to switch to Debian.
@limburgher can help. He's the synfig maintainer on Fedora.

**Comment by limburgher** [comment]
@Keyikedalube She, actually. :)
No, oggs to not play.

**Comment by sergiomb2** [comment]
@Keyikedalube , you just need enable rpmfusion repos and install mlt-freeworld, and today I enabled also vorbis plugin in MLT of Fedora which may play sound without mlt-freeworld 

https://bodhi.fedoraproject.org/updates/FEDORA-2019-a0fab69cfd
https://bodhi.fedoraproject.org/updates/FEDORA-2019-dea9e2907e

**Comment by blackwarthog** [comment]
@limburgher you need to build MLT with vorbis producer, Dan said that this functionality may be broken, but you can try.

I've changed Synfig code, and now Synfig tries to create producer named "vorbis" when producer "avformat" does not present.
List of of MLT producers can be shown by command:
  mtl-melt -query "producers"

**Comment by Keyikedalube** [comment]
@sergiomb2 I just installed Fedora 31 fresh on my notebook computer and
- enabled rpmfusion
- installed mlt-freeworld
- then pulled mlt from updates-testing
- and tried playing the same Hello.ogg sound file again. It works!

Thanks for the fix!!

> I enabled also vorbis plugin in MLT of Fedora which may play sound without mlt-freeworld

At first, I tried running the sample Hello.ogg file after installing mlt-6.18.0-2.fc31 *without installing mlt-freeword*
The sound fails to play.

**Comment by blackwarthog** [comment]
i've checked latest master of MLT, vorbis functiontality is already reanimated and enabled by default

https://github.com/mltframework/mlt
https://github.com/mltframework/mlt/issues/505

@limburgher can you add changes into MLT fedora package to build it with vorbis support?

**Comment by sergiomb2** [comment]
Hi, 

> At first, I tried running the sample Hello.ogg file after installing mlt-6.18.0-2.fc31 _without installing mlt-freeword_
> The sound fails to play.

in mlt-6.18.0-2.fc31 I added vorbis support , so it should work without mlt-freeworld , I will investigate more , thanks for the report .
