### ISSUE TITLE
Basic tasks

### ISSUE THREAD

**Issue by IbanRothschild** [synfig/synfig#869]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)
1.13.11 in Manjaro as appimage

**Issue description**:

Its so big amount of things:

- I can't compile from git so i needed to use the appimage, thing i don't like because it cannot be attached to the KDE panel properly.
- I can't import Inkscape files properly, either SVGs or SIFs. I forgot the idea to import a gradient and i can't either import a simple text.

So i decided to try to recreate my job inside Synfig but...

- I cant create a text without writing the filename of the font manually but it doesn't works either in the appimage builds.
- Fonts haven't got stroke so i can't do what i've done in inkscape
- Everything seems to be rasterized ¿Why this would be a good idea in profesional animation?
- Everything that overflows the document just simply doesn't appears so you cant know if the import failed because its big or wrong. There is no border or spinner identifying the object.
- When you import a file, it uses the main file, not a copy and it doesn't ask if you want that.
- Alerts are shown in the bottom bar but i needed two days to see it, no sound or popup
- Its unable to import any kind of vectorial files from the unsuccessful svgs or sifs

The experience has been unlimited frustrating and i just done a few effects for video templates in the past... It seems to be easier to animate in a video editor than this animator program. Sorry.

**Comment by BobSynfig** [comment]
Most of what you complain about is already known, in Wiki/manual/forums.
If you can't compile, it meeans there are some missing libs.
A few months ago, I tested Manjaro as virtual machine and I succeded to compile.
Without logs, we can't guess what is happening on an "exotic" distro

"Everything seems to be rasterized": Draft mode enabled?
For the import, it is known, the external file is linked.
Synfig is developped mostly by volunteers and may not fit the needs of everyone.
No one forces you to use it, there are plenty of paid alternatives

For the alerts, we could implement [singing telegrams](https://www.youtube.com/watch?v=VnGzpoDK_xQ) if you want ;)

**Comment by IbanRothschild** [comment]
Can you, please, step out of this program and let other people with more interest in the business and industry of animation make money with it while we spread the open source ideology and not the capitalistic point of view of software? It smell to Bill Gates here... You just wrote 9 lines of unuseful code there...

**Comment by morevnaproject** [comment]
@IbanRothschild @BobSynfig Please make sure to read Code of Conduct document and follow its guidelines in discussion - https://synfig-docs-dev.readthedocs.io/en/latest/community/code%20of%20conduct.html

@IbanRothschild Please make sure to submit each issue as a separate bugreport. Also, please make sure to read this guide on how to report bugs effectively - https://www.chiark.greenend.org.uk/~sgtatham/bugs
