### ISSUE TITLE
Zoom makes Synfig crash.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#870]
**Synfig version & platform**:
Master
Linux

**Issue description**:
Simple navigation using zoom makes Synfig crash, everywhere every time, with artwork or empty canvas, with prerender activated or without doesn't matter. 

[Video Demostration.](https://youtu.be/JYSEYNWSm4Y)

**Comment by BobSynfig** [comment]
Please see my remark here: https://github.com/synfig/synfig/issues/674

**Comment by blackwarthog** [comment]
fixed in 717751e

**Comment by morevnaproject** [comment]
Reopening because of ee269a82d9200 and https://github.com/synfig/synfig/issues/896#issuecomment-518352110

**Comment by ebarranco** [comment]
This is back, it is less often but still happening.

**Comment by blackwarthog** [comment]
i've fixed some bugs by the commit 82ffbee5a24576138a7d3bfb7abd84dd4988182a
please recheck

**Comment by ebarranco** [comment]
Hi @blackwarthog  I checked this issue again and it is totally back and I can reproduce the crashing every time.
[Video.](https://youtu.be/1vnWFtLLxMY)

**Comment by blackwarthog** [comment]
> Hi @blackwarthog  I checked this issue again and it is totally back and I can reproduce the crashing every time.
> [Video.](https://youtu.be/1vnWFtLLxMY)

Thanks for your help, for me it reproduces after a several munutes of zoomming and scrolling. I've catch and fixed one more bug in this commit: 5fc8322664e53a2a139384d42f3444c8f0806883. May you check?

**Comment by ebarranco** [comment]
Hey @blackwarthog !  I've been trying to crash Synfig and I can't do it now.  :smiley:

**Comment by ebarranco** [comment]
Thank's!
