### ISSUE TITLE
Remove unused parameter "loopyness" from outline layer

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#871]
**Synfig version & platform**:
Master branch, commit id: https://github.com/synfig/synfig/commit/678cc3a7b1208fcca18c8b54a29a20576c499927

**Issue description**:
https://github.com/synfig/synfig/blob/678cc3a7b1208fcca18c8b54a29a20576c499927/synfig-core/src/modules/mod_geometry/outline.cpp#L149
The parameter `loopyness` is not used in the outline layer code anywhere. So it is safe to remove it(https://github.com/synfig/synfig/pull/756#issuecomment-507354490)

I guess this will include removing this parameter from Synfig core as well as gui.

**Comment by BobSynfig** [comment]
I think this parameter was supposed to permit to "close" an outline (to make it as a loop between the 2 ends) but never implemented.
It should have been Boolean instead of Real also, the fact it has not been converted could mean it is a lot old in the source code.
Maybe it would be more wise to keep it and develop the expected behavior?

Also it would change the format of Synfig file and could lead to errors when the users will load their artwork woth another version:

```
Warning
* /home/myuser/siffile.sif:<real>:214:Layer 'outline' rejected value for parameter 'loopyness'
```

**Comment by AnishGG** [comment]
> I think this parameter was supposed to permit to "close" an outline

Oh I see.


> It should have been Boolean instead of Real also, the fact it has not been converted could mean it is a lot old in the source code.

May be it was meant to be Real only. Because we might want to give user the independence of how he chooses to "close" the outline. Meaning should it be a straight line, or should it be convex loop or concave loop depending on the values of `loopyness`.

> Maybe it would be more wise to keep it and develop the expected behavior?

This would be great.

> Also it would change the format of Synfig file and could lead to errors when the users will load their artwork woth another version:

If the `type` is not changed to Boolean, then we won't face this error. ^_^

**Comment by AnishGG** [comment]
> May be it was meant to be Real only. Because we might want to give user the independence of how he chooses to "close" the outline. Meaning should it be a straight line, or should it be convex loop or concave loop depending on the values of `loopyness`.

It just got into my mind that this can be supported using the tangents of first and last vertices. So Boolean seems to be a good idea.

**Comment by AnishGG** [comment]
> Maybe it would be more wise to keep it and develop the expected behavior?

@morevnaproject your views regarding this? ^__^

**Comment by morevnaproject** [comment]
> Maybe it would be more wise to keep it and develop the expected behavior?

I think as long as no one is willing to implement this feature then it is better to remove that param.
It is just a few lines of code anyway. ^__^

In any case, implementing it will take some time on discussing/implementing/testing. So, it's best to remove and then implement feature (if such need) without a hurry.

**Comment by AnishGG** [comment]
> I think this parameter was supposed to permit to "close" an outline (to make it as a loop between the 2 ends) but never implemented.

@BobSynfig I guess this feature already exists. Outline layer can be "closed" by right clicking on the spline and checking the `loop` tool. Here I am attaching both unlooped and looped outline layer example.
[outline_layers.zip](https://github.com/synfig/synfig/files/3356419/outline_layers.zip)

> So, it's best to remove this.

Hence, in my views this will be the best choice.

**Comment by blackwarthog** [comment]
Then all sif/sifz files will show a lot of warnings: "Layer outline rejected value for parameter loopyness".
Until re-save.

Is it ok?

**Comment by morevnaproject** [comment]
Yes, this is fine. We've had worse things earlier. ^__^

**Comment by blackwarthog** [comment]
done
