### ISSUE TITLE
[Lottie exporter] Adjust positions of layers in group layer according to Pre Composition in Lottie

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#872]
### This issue is a part [Feature request: Add Lottie export format](https://github.com/synfig/synfig/issues/704)
**Issue description**:

To export `group` layer to `Lottie` format, `pre composition` layers from `Lottie` are used. Consider recursive `group` layers involved, if one of that `group` layer has child layers which are going out of the canvas, then those parts are cut off and ignored. 
To tackle this, the width and height(in 'Lottie' format) of this group layer will be increased and the positions of layers inside will change by some `offset`. `-offset` needs to be applied to the position transformation of this group layer.
I will be devising an algorithm to calculate this `offset`. If time given away in this calculation is much more, then a rough approximation might be taken.

**Comment by AnishGG** [comment]
In some cases the `offset` can be animated. Also the `position` transformation of that group layer might also be animated.
This case becomes tricky then. Is there any algorithm inside Synfig which helps combine two animations?
This can be achieved by frame-by-frame `offset` addtion, but again this can consume more space of the final `JSoN` file.
@morevnaproject any help regarding this? ^__^

**Comment by AnishGG** [comment]
Worked out without the need of combining two animations. :smile: 

>  Is there any algorithm inside Synfig which helps combine two animations?

I am still curious about this.

**Comment by morevnaproject** [comment]
> Is there any algorithm inside Synfig which helps combine two animations?

Yes, it is possible to use Converters to mix animation of two parameters. Here is an example video which demonstrates use of Add Converter to mix two animations - https://www.youtube.com/watch?v=ECXpa1UgX74

More about converters in Synfig:
- https://www.youtube.com/watch?v=odlPI6hfnDM
- https://wiki.synfig.org/Convert

It looks like Lottie also supports something like that via AE expressions - https://github.com/airbnb/lottie-web/wiki/Expressions ^__^
