### ISSUE TITLE
Exported canvases don't preserve its resolution

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#874]
**Synfig version & platform**:
Master and Stable
linux and windows

**Issue description**:

Exported canvases change its resolution in any canvas size different to the default one. (480x270).

If you have a canvas of 1920x1080 the subcanvas is 480x270
If you have a canvas of 1280x720 the subcanvas is 480x270
...and so on.

This cause a lot and painful problems to all artist that don't used the default resolution from the beginning of a project.

**Comment by ebarranco** [comment]
Directly related with **Exporting canvas should set proper length for created sub-canvas** #715 issue.

**Comment by morevnaproject** [comment]
Done! Thank you for reporting. ^__^
