### ISSUE TITLE
[Vec]

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#875]
### This issue is a part of [Vectorization of bitmaps [GSoC 2019]](https://github.com/synfig/synfig/issues/735)

**Issue description**: We do not need `frame` as an input to centerline configuration and `conf.m_thicknessRatio = 1.0`
As mentioned by @morevnaproject here https://github.com/synfig/synfig/issues/735#issuecomment-503549116
>So, after we understood the meaning of this functionality, let's answer the question - do we need that in Synfig?
>No.

>In Synfig we can control (and animate) outline thickness using Outline Grow parameter of group - https://wiki.synfig.org/Group_Layer#Outline_Grow_Parameter
>So, it' is ok to assume that conf.m_thicknessRatio variable always = 1.0 (at https://github.com/morevnaproject/opentoonz/blob/ac3067fb0cdbdcbc4f7fca959cf0d6c212586fb4/toonz/sources/toonzlib/vectorizerparameters.cpp#L233-L234 ).

So as to make `conf.m_thicknessRatio = 1.0` after that adjustment_tcalibration_start and adjustment_tcalibration_end are of no use so they should be removed from GUI as well
Track the progress here -> https://github.com/synfig/synfig/milestone/5

**Comment by ankit-kumar-dwivedi** [comment]
I have removed the code and also the GUI part @morevnaproject 
![image](https://user-images.githubusercontent.com/37617951/60670223-c5f11800-9e8d-11e9-985a-63b2d1a580cc.png)

**Comment by morevnaproject** [comment]
Great!
