### ISSUE TITLE
[Vectorization] Wrap Vectorization to an action

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#881]
### This issue is a part of [Vectorization of bitmaps [GSoC 2019]](https://github.com/synfig/synfig/issues/735)

**Issue description**: Wrap Vectorization process into an action 

> Actually, you might notice that Synfig uses a [system of actions ](https://github.com/synfig/synfig/tree/master/synfig-studio/src/synfigapp/actions) to perform operations. This allows having a history to perform undo/redo.
> 
> ![screenshot_001](https://user-images.githubusercontent.com/332868/61025409-d39d2500-a3da-11e9-9ad8-3f52ed5c7c8e.png)
> 
> So, I think in the future the vectorization should be wrapped into action. ^__^

Track the progress here -> https://github.com/synfig/synfig/milestone/5

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject can I use layerencapsulate action in my vectorization action to create the group? I am asking this as the https://wiki.synfig.org/Dev:Action_System says I can call action inside action if I inherit super

**Comment by ankit-kumar-dwivedi** [comment]
@blackwarthog a little help neede. How do I get the interface or instance here?
https://github.com/ankit-kumar-dwivedi/synfig/blob/51cf3ee1afc592212adb47b936424e76ea229fc9/synfig-studio/src/gui/dialogs/vectorizersettings.cpp#L317

**Comment by blackwarthog** [comment]
> @blackwarthog a little help neede. How do I get the interface or instance here?
> https://github.com/ankit-kumar-dwivedi/synfig/blob/51cf3ee1afc592212adb47b936424e76ea229fc9/synfig-studio/src/gui/dialogs/vectorizersettings.cpp#L317

i think the best way is to pass it to constructor of VectorizerSettings

**Comment by ankit-kumar-dwivedi** [comment]
> i think the best way is to pass it to constructor of VectorizerSettings

I passed the `selected_instance` from app.cpp. The code compiled however crashed with following error
```
synfigstudio: /home/allievo/gsoc/synfig/synfig-studio/src/gui/dialogs/vectorizersettings.cpp:299: void studio::VectorizerSettings::on_convert_pressed(): Assertion `action' failed.
```

**Comment by blackwarthog** [comment]
what assertion at vectorizersettings.cpp:299 ?

**Comment by ankit-kumar-dwivedi** [comment]
@blackwarthog that is assert(action)
The action I created (i.e Vectorization)
Do we have to add the action name somewhere other than make files?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi You have to add Vectorizer action here - https://github.com/synfig/synfig/blob/master/synfig-studio/src/synfigapp/action.cpp#L190

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Also, I found that Vectorizer action is referencing `.h` file from `gui` directory - https://github.com/ankit-kumar-dwivedi/synfig/blob/21cafcc2ba70cafbc879741a5442a0ffcc8cd305/synfig-studio/src/synfigapp/actions/vectorization.h#L32

This is not good if code at `synfig-studio/src/synfigapp` is referencing code from `synfig-studio/src/gui`, because there is a dependency "gui" module depends on "synfigapp"   (see ["Overview" section of developer documentation](https://synfig-docs-dev.readthedocs.io/en/latest/common/structure.html#overview)).

So, it's better to move `centerlinevectorizer.h` and all related files to `synfigapp` (maybe create a `vectorizer` subdir?). ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> @ankit-kumar-dwivedi You have to add Vectorizer action here - https://github.com/synfig/synfig/blob/master/synfig-studio/src/synfigapp/action.cpp#L190

Okay thanks!

> So, it's better to move centerlinevectorizer.h and all related files to synfigapp (maybe create a vectorizer subdir?). ^__^

Working on that now 👍

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject done moving vectorizer files [^_^]
The code https://github.com/ankit-kumar-dwivedi/synfig/commit/8ca93aac197fbd58ee74468ef1bd0dd4ea26a419 compiled succesfully 
 I get the following output while running the program.
```
Action Created 
Action Asserted 
Action param passed 
Action is ready 
inside perform
after image layer cast perform
newOutlineVectorize called/nafter result is here perform
after inline canvas perform
after new_layer perform
after get_canvas()->parent()->push_front(new_layer) perform
after layers created perform
after get_canvas_interface perform
synfigstudio: /home/allievo/gsoc/synfig/ETL/ETL/_handle.h:268: T* etl::handle<T>::operator->() const [with T = synfig::Canvas; etl::handle<T>::pointer = synfig::Canvas*]: Assertion `obj' failed.
Aborted (core dumped)

```
as all the debug lines are getting printed so I am confused what is causing the error :confused: 
https://github.com/ankit-kumar-dwivedi/synfig/blob/8ca93aac197fbd58ee74468ef1bd0dd4ea26a419/synfig-studio/src/synfigapp/actions/vectorization.cpp#L221-L251

**Comment by morevnaproject** [comment]
Hmmm... @blackwarthog any ideas?

**Comment by blackwarthog** [comment]
may be add:

new_layer->set_canvas( layer->get_canvas()->parent() );

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi 

1. We need to check what is really causing the troubles - the vectorizer action itself, or code outside of it. So, try the following: instead of calling Vectorizer action, try to call some other Synfig action - LayerAdd or Encapsulate. If you will make it work without crash, then the problem is inside of Vectorizer action. Otherwise the problem is outside.

2. If the problem is inside of Vectorizer action then do the following - try commenting out lines one by one (from bottom to top) and see at which point it will stop crashing.

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Did anything of above worked for you? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> * We need to check what is really causing the troubles - the vectorizer action itself, or code outside of it. So, try the following: instead of calling Vectorizer action, try to call some other Synfig action - LayerAdd or Encapsulate. If you will make it work without crash, then the problem is inside of Vectorizer action. Otherwise the problem is outside.
> 
> *

@morevnaproject I tried this with LayerAdd and the action worked fine. So now finding what is causing an error in the vectorizer.

**Comment by ankit-kumar-dwivedi** [comment]
``` 
synfigstudio: /home/allievo/gsoc/synfig/ETL/ETL/_handle.h:268: T* etl::handle<T>::operator->() const [with T = synfig::Canvas; etl::handle<T>::pointer = synfig::Canvas*]: Assertion `obj' failed.```

Also from the error line, it feels this is related to canvas::Handle

**Comment by ankit-kumar-dwivedi** [comment]
Well... even after I comment all the lines in `Action::Vectorization::perform()`  it still crashed.
@blackwarthog any ideas?

**Comment by blackwarthog** [comment]
you (still) need to add following line into perform():

new_layer->set_canvas( layer->get_canvas()->parent() );

**Comment by morevnaproject** [comment]
> Well... even after I comment all the lines in `Action::Vectorization::perform()` it still crashed.

I tested and it doesn't crash when `instance->perform_action(action)` is commented out in `vectorizersettings.cpp`.

**Comment by morevnaproject** [comment]
In such situation I suggest to  use a debugger and see what exactly riggers the crash.

**Comment by ankit-kumar-dwivedi** [comment]
> In such situation I suggest to use a debugger and see what exactly riggers the crash.

Thanks to @morevnaproject I used the debugger and found this:
![67403241_871615289884328_7696820233268363264_n](https://user-images.githubusercontent.com/37617951/62306540-b4585b80-b49f-11e9-95d1-8f545aafcf61.png)

So i needed to do two things:

- set `canvas` param
- set `canvas_interface` param

after this the error was fixed and the vectorizer works great!

**Have a look at the output**

![image](https://user-images.githubusercontent.com/37617951/62306780-15802f00-b4a0-11e9-9513-f9ae7e3058e8.png)

This will look far better after shifing (^_^)

**Comment by ankit-kumar-dwivedi** [comment]
Closing the issue as I have wrapped the vectorizer to action now

**Comment by morevnaproject** [comment]
> Have a look at the output

This is absolutely exciting! Congratulations! :1st_place_medal:

**Comment by blackwarthog** [comment]
in function Action::Vectorization::is_ready() do following:

```
 return get_param_vocab().size() >= 8
     && synfig::Layer_Bitmap::Handle::cast_dynamic(layer)
     && Action::CanvasSpecific::is_ready(); // ask ready status from base class
```


in VectorizerSettings::on_convert_pressed() add lines:

```
etl::handle<Canvas> canvas = layer_bitmap_->get_canvas()->parent();
etl::handle<CanvasInterface> canvas_interface = instance->find_canvas_interface( canvas->get_non_inline_ancestor() );
action->set_param("canvas", canvas);
action->set_param("canvas_interface", canvas_interface);
```

**Comment by blackwarthog** [comment]
we need to check what happens when Layer_Import will outside any group at root level - seems will be a crash.

i think we need to get parent canvas only if parent layer exists and it is Layer_Switch.
also in action we should not to decide where put the result - just add it to canvas that passed as parameter
target canvas will find by VectorizerSettings dialog.


but better we should not to get the parent canvas and do following:
- when user select the switch or group (any child of Layer_PasteCanvas) with a single image layer, then we will to vectorize the image and place result group at the same level with the *selected group*
- when user select image layer directly (placed inside aby switch/group or not) then we will place result group at the same level with the *image*

**Comment by blackwarthog** [comment]
vectorizer as an action is a bad idea

in synfig api actions does not decide where put the result, target comes from GUI,
but in this case we should to create action which do no changes with any opened canvases, and we have no place where we can store this action in history, and we cannot to bring any sence to 'undo action' command

actions is the records in the changelog (history)
it's is not the set of commands that we can run
but we need abstraction of such commands in future for api and scripting system


so for now in our case we need:
 - run vectorization command and wait
 - command returns the *canvas independant* not linked layer
 - select the place where we need to put the result
 - and the next we should to create two actions (merged to one group):
	LayerAdd and LayerMove (see alse CanvasInterface::layer_add_action(), layer_move_action)
	to add layer into specified canvas and set valid depth for it

**Comment by morevnaproject** [comment]
> I think we need to get parent canvas only if parent layer exists and it is Layer_Switch.

Agree.

> also in action we should not to decide where put the result - just add it to canvas that passed as parameter target canvas will find by VectorizerSettings dialog

That makes sense.

> in synfig api actions does not decide where put the result, target comes from GUI,
but in this case we should to create action which do no changes with any opened canvases, and we have no place where we can store this action in history, and we cannot to bring any sense to 'undo action' command

I'll answer one-by-one below ^__^ -

> but in this case we should to create action which do no changes

It does changes - it does vectorization and places result (outlines) in canvas.

> we cannot to bring any sense to 'undo action' command

Undo action will remove a group, which contains all outlines made after vectorization  (this group is created by vectorization action).

**Comment by ankit-kumar-dwivedi** [comment]
> Undo action will remove a group, which contains all outlines made after vectorization (this group is created by vectorization action).

please note I have not written undo() yet and writing it currently using this logic

**Comment by morevnaproject** [comment]
I am re-opening this issue to address following:

- [ ] Write undo
- [ ] `vectorizersettings.cpp` should check if LayerBitmap is inside of LayerSwitch or not and set "canvas" param accordingly ("canvas" param is set to `bitmap_layer->get_canvas()->parent()` if LayerBitmap is inside of LayerSwitch; "canvas" param is set to `bitmap_layer->get_canvas()` otherwise ).
- [ ] In `vectorization.cpp` change [line 236](https://github.com/ankit-kumar-dwivedi/synfig/blob/vectorization/synfig-studio/src/synfigapp/actions/vectorization.cpp#L236) -  replace `layer->get_canvas()->parent()->push_front(new_layer);` to `get_canvas()->push_front(new_layer);`
- [ ] Follow recommendations given in [this comment](https://github.com/synfig/synfig/issues/881#issuecomment-517074655) (set canvas for new group layer) - `new_layer->set_canvas(get_canvas() );`
- [ ] Implement recommendations given [here](https://github.com/synfig/synfig/issues/881#issuecomment-517348604).

**Comment by ankit-kumar-dwivedi** [comment]
Doing them now

**Comment by ankit-kumar-dwivedi** [comment]
>     * `layer->get_canvas()->parent()->push_front(new_layer);` to `get_canvas()->push_front(new_layer);`

this will create the group inside switch do we really want that? @blackwarthog

**Comment by ankit-kumar-dwivedi** [comment]
My bad this will not let that happen
> check if LayerBitmap is inside of LayerSwitch or not and set "canvas" param accordingly ("canvas" param is set to bitmap_layer->get_canvas()->parent() if LayerBitmap is inside of LayerSwitch; "canvas" param is set to bitmap_layer->get_canvas() otherwise ).

**Comment by blackwarthog** [comment]
>> in synfig api actions does not decide where put the result, target comes from GUI,
> but in this case we should to create action which do no changes with any opened canvases, and we
> have no place where we can store this action in history, and we cannot to bring any sense to 'undo action' command

>> but in this case we should to create action which do no changes

> It does changes - it does vectorization and places result (outlines) in canvas.

action should not decide where to place the result layer
in common we use two actions - LayerAdd and LayerMove to do this
but here we have three actions in one - vectorize+layeradd+layermove

(part of layermove actually not implemented yet in vectorize action, and it will be a next hack)

so pure vectorization action should not to change canvas - just returns new not liked to any canvas Layer_Group with vectorized data. This behavior has a sense in potential API and script system, but "vectorize a layer and put result to selected place in selected canvas" is a strange.

for pure vectorization we cannot call 'undo'


undo usable only for layeradd, and:
> Undo action will remove a group, which contains all outlines made after vectorization  (this group is created by vectorization action).

and 'redo' will not and should not to revectorize the image just put back already vectorized layer group from internal variable - we only simulate an action but actually it should be another abstraction.

in any case in synfig we make layer creation outside of action system, and just use layeradd action at the end


we must to think about architecture, but it's a long process. for now i suggest a stable and easy solution - do vectorization outside of action system in GUI. in this case we takes more abilities to user interaction - progressbar, cancel button, preview - etc.

**Comment by ankit-kumar-dwivedi** [comment]
but @blackwarthog calling vectorization on same will actually give same result until and unless the layer is a different image because it directly use RGBA values which will not change when the user rerun vectorizer.
The possibilty is that he/she wants to run the process with some new configuration paramters. in this undo() is not what should be use you have to revectorize the image.

That's what I can think of.

> we must to think about architecture, but it's a long process. for now i suggest a stable and easy solution - do vectorization outside of action system in GUI. in this case we takes more abilities to user interaction - progressbar, cancel button, preview - etc.

this is a topic in discussion from what I think @morevnaproject suggested to do this because `
synfig uses system of actions to perform operation` as in the issue comment. I am ready to go with any approach but scripting architecture is more robust approach.

**Comment by ankit-kumar-dwivedi** [comment]
> * `vectorizersettings.cpp` should check if LayerBitmap is inside of LayerSwitch or not and set "canvas" param accordingly ("canvas" param is set to `bitmap_layer->get_canvas()->parent()` if LayerBitmap is inside of LayerSwitch; "canvas" param is set to `bitmap_layer->get_canvas()` otherwise ).
> 

I have a little hack in mind for this.
we have two different right click options for inside switch and on switch right click. So why not utilize it? I can pass a variable from there that can simply tell if layer is inside of switch or not 
@blackwarthog @morevnaproject thoughts?

**Comment by morevnaproject** [comment]
> we have two different right click options for inside switch and on switch right click. So why not utilize it? I can pass a variable from there that can simply tell if layer is inside of switch or not

I like this idea!

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I have implemented all the given recommendations.
please review

**Comment by ankit-kumar-dwivedi** [comment]
Closing now!
