### ISSUE TITLE
[Lottie exporter] Lottie animations not getting rendered locally

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#883]
### This issue is a part of [Feature request: Add Lottie export format](https://github.com/synfig/synfig/issues/704)
**Issue description**:

Lottie animations are not getting rendered on local browser(without a local server). This is due to recent changes in lottie.js file that we were [referencing](https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.3/lottie.js). They seem to have changed the way to load JSoN files via Cross-origin requests.
For more explaination, refer: [link](https://github.com/synfig/synfig/pull/756#issuecomment-511127184) and [link](https://github.com/synfig/synfig/pull/756#issuecomment-511128117)

**Comment by AnishGG** [comment]
Suggestion: Instead of fetching the file(lottie.js) from the server, we can keep a local copy of it and run lottie animations via that.
@morevnaproject what do you think about this?

**Comment by morevnaproject** [comment]
> Instead of fetching the file(lottie.js) from the server, we can keep a local copy of it and run lottie animations via that.

@AnishGG I tried that and it doesn't works. I suggest to submit an issue to https://github.com/airbnb/lottie-web/

As a temporary workaround we can rollback to an older version of lottie player - https://cdnjs.com/libraries/bodymovin (needs to investigate which version will work with local files)

**Comment by AnishGG** [comment]
> As a temporary workaround we can rollback to an older version of lottie player - https://cdnjs.com/libraries/bodymovin (needs to investigate which version will work with local files)

I tried many of them, even `5.5.3` version(it was last updated 2 months ago) and it still did not work. Here is the link for it: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/bodymovin/5.5.3/lottie.js
Maybe the problem is not the changes in the file, but some function calls inside the file might have changed there methods.

**Comment by AnishGG** [comment]
>  I suggest to submit an issue to https://github.com/airbnb/lottie-web/

https://github.com/airbnb/lottie-web/issues/1719

**Comment by AnishGG** [comment]
Resolved ^__^

**Comment by morevnaproject** [comment]
Awesome!
