### ISSUE TITLE
Vertices disapear closing polygons

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#885]
**Synfig version & platform**:
Master
Linux

**Issue description**:
Vertices disappear using the polygon tool, when you're editing the position of vertices or closing polygons.

1.Open Synfig
2.Select the polygon tool
3. Try to close a polygon with a tablet. (With a mouse this doesn't happen, so don't close de polygon and try to edit a vertex)
4. The vertices are not visible.
[
Video demostration.](https://youtu.be/Z4jk0Wh8Aks)

**Comment by morevnaproject** [comment]
@blackwarthog Can you take a look, please? ^__^

**Comment by blackwarthog** [comment]
Vertices was disappeared any time when you moving it. This behavior is fixed now.

When you touch first vertex by tablet stylus have a jittering and the gesture determines as a drag instead of click.
