### ISSUE TITLE
[Vectorization] Fix outline issues after centerline vectorization

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#891]
### This issue is a part of [Vectorization of bitmaps [GSoC 2019]](https://github.com/synfig/synfig/issues/735)

**Issue description**: The outline layers are being created, however [some things need to be fixed.](https://github.com/synfig/synfig/issues/853#issuecomment-513554516)

- [x] Origin shifting of the outline to fit into draw area, Currently outlines contain only +ve points

- [x] Set outline width according to segment array

- [x] Fix distortion due to point (0,0)

- [x] Copy transformation parameters from Yellow Switch group

Track the progress here -> https://github.com/synfig/synfig/milestone/5

**Comment by ankit-kumar-dwivedi** [comment]
![image](https://user-images.githubusercontent.com/37617951/62407804-1e761b00-b5dc-11e9-9989-1e5fbce7930d.png)

Fixed (0,0) addition in https://github.com/ankit-kumar-dwivedi/synfig/commit/c6a6aca162bdda2554efa5d20f03e01c4c48245c

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject even the bottom-left point being origin is incorrect as from the image above shifting will shift the origin to this point itself so I guess this won't work.

Also how to set a variable width of the outline? I mean different width at different points?

**Comment by morevnaproject** [comment]
> even the bottom-left point being origin is incorrect as from the image above shifting will shift the origin to this point itself so I guess this won't work.

Please check transformation of yellow group (the one which contains an image). It is possible you shifted/scaled it after importing image.

> Also how to set a variable width of the outline? I mean different width at different points?

You can set width for each BlinePoint - https://github.com/ankit-kumar-dwivedi/synfig/blob/vectorization/synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp#L69

**Comment by ankit-kumar-dwivedi** [comment]
> Please check transformation of yellow group (the one which contains an image). It is possible you shifted/scaled it after importing image.

@morevnaproject no perform no transformation. However I just realized I need to align outline with image and not the canvas. This could be the reason of origin mismatch.

**Comment by morevnaproject** [comment]
BTW, it would be nice to copy transformation parameters from Yellow Switch group (vectorization source) to Green Group (vectorization result). Of course only in case if Bitmap Layer is wrapped into Yellow Group. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Now the outline is closed compared to above so we can use the fill colour option too.
![image](https://user-images.githubusercontent.com/37617951/62415170-1dc49f80-b643-11e9-913e-44cff2611e8c.png)

See the gaps in the result outline

> ![image](https://user-images.githubusercontent.com/37617951/62407804-1e761b00-b5dc-11e9-9989-1e5fbce7930d.png)
> 
> Fixed (0,0) addition in [ankit-kumar-dwivedi@c6a6aca](https://github.com/ankit-kumar-dwivedi/synfig/commit/c6a6aca162bdda2554efa5d20f03e01c4c48245c)

This was the vertex which was being initialized to (0,0) instead so now we get better results [^__^]

**Comment by ankit-kumar-dwivedi** [comment]
Origin shiting to overlap the original curve is also done now. https://github.com/ankit-kumar-dwivedi/synfig/commit/9bb79ce6a64ffdc8fa8347b2642738159f47817e

**Comment by ankit-kumar-dwivedi** [comment]
> BTW, it would be nice to copy transformation parameters from Yellow Switch group (vectorization source) to Green Group (vectorization result). Of course only in case if Bitmap Layer is wrapped into Yellow Group. ^__^

Yes I can add some code to pass param here https://github.com/ankit-kumar-dwivedi/synfig/blob/9bb79ce6a64ffdc8fa8347b2642738159f47817e/synfig-studio/src/gui/dialogs/vectorizersettings.cpp#L319-L321

**Comment by morevnaproject** [comment]
> Yes I can add some code to pass param here ...

I am not sure how to properly achieve that...

The only way I see is to pass the layer (the one that user clicked on) to VectorizerSettings dialog. Let's say it will be stored in variable called `reference_layer`.
Then in `on_convert_pressed()` function, pass `reference_layer` as param to action (let's assume the param will be called the same - "reference_layer").

Then add code to action's `perform()` - check if `reference_layer` is a group. And if true, then copy its transformation to newly created group.

**Comment by ankit-kumar-dwivedi** [comment]
> The only way I see is to pass the layer (the one that user clicked on) to VectorizerSettings dialog. Let's say it will be stored in variable called `reference_layer`.
> Then in `on_convert_pressed()` function, pass `reference_layer` as param to action (let's assume the param will be called the same - "reference_layer").

@morevnaproject after that we know there is a variable bool insideswitch that tells if the image is inside switch or not.
So if (insideswitch) then pass the param refernce_layer else do not pass i,e make it an optional param. then in perform if refernce_layer is passed simply copy the transformation

**Comment by morevnaproject** [comment]
> after that we know there is a variable bool insideswitch that tells if the image is inside switch or not.

I think `insideswitch` variable is redundant. Checking type of `reference_layer` (is it switch group or not) can tell if user clicked on Switch Layer or Bitmap Layer.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Yes that was I was thinking so i replaced it with
`	if (etl::handle<Layer_PasteCanvas> paste = etl::handle<Layer_PasteCanvas>::cast_dynamic(reference_layer)) 
`

**Comment by morevnaproject** [comment]
Great! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject 
![image](https://user-images.githubusercontent.com/37617951/62711154-2b4ca180-ba16-11e9-8da3-046686103175.png)
Transformation copy working now [^_^]

**Comment by morevnaproject** [comment]
Hi! After reviewing code I found a declaration of `insideSwitch` remaining - https://github.com/ankit-kumar-dwivedi/synfig/blob/vectorization/synfig-studio/src/gui/instance.cpp#L93

Also, something makes me feel that declaring `my_layer_bitmap` and `reference_layer` as globals in `instance.cpp` is not a good practice. Can you try to implement it some other way? ^__^

**Comment by morevnaproject** [comment]
> Also, something makes me feel that declaring `my_layer_bitmap` and `reference_layer` as globals in `instance.cpp` is not a good practice. Can you try to implement it some other way? ^__^

I have added a separate issue about that - #908 
This is not a top priority at the moment, but will need a fix. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject outline width is working but is there a multiplier I need to take care of?
![image](https://user-images.githubusercontent.com/37617951/62817846-eaaa7080-bb5a-11e9-9744-b7b48399eb4e.png)
The previous width(default) was set to 1.0 and it was looking fine now the average width is 5.0 but it looks like this is greater than the original image.

**Comment by morevnaproject** [comment]
Awesome! 
Yes, I think you should try to find multiplier. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
This is how another image look
![image](https://user-images.githubusercontent.com/37617951/62817899-fb0f1b00-bb5b-11e9-8315-d0e15642e2fb.png)

**Comment by ankit-kumar-dwivedi** [comment]
pushed a possible fix https://github.com/ankit-kumar-dwivedi/synfig/commit/a6490014eb26ce8daa9c04f34fcc50e1a6e6755c

**Comment by morevnaproject** [comment]
This looks much better now!

**Comment by ankit-kumar-dwivedi** [comment]
Should I consider this solved?

**Comment by morevnaproject** [comment]
Yes, good work! ^__^
