### ISSUE TITLE
Support to know progress of action using GUI

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#895]
**Issue description**: While working on vectorization I am creating an action that will wrap the vectorization code. The problem is to display the progress I need to know the progress of action and if cancel is pressed in between vectorization then action should stop and delete temporary data.
In general, how do we communicate GUI and action system?

ping @blackwarthog @ice0

**Comment by blackwarthog** [comment]
> **Issue description**: While working on vectorization I am creating an action that will wrap the vectorization code. The problem is to display the progress I need to know the progress of action and if cancel is pressed in between vectorization then action should stop and delete temporary data.
> In general, how do we communicate GUI and action system?
> 
> ping @blackwarthog @ice0 

1. Make your vectorizer dialog modal (see Gtk::Window::set_modal()). To lock all other synfig GUI while vectorizer dialog visible.

2. Add any progressbar widget

3. Add code into work cycle to update progressbar value and repaint it. Some pseudocode:
        x += 1;
	progressbar.set_progress(x);
	studio::App::process_all_events();
	// ^ by this method you can process all pending gtk events
	// without exiting from your function
	// and make application alive

	// also you need to check job cancellation flag here
	if (cancelled) { return; }


To make it easier in synfig we use synfig::ProgressCallback and SuperCallback class
Your shoud to make your own class based on synfig::ProgressCallback
See studio::SplashProgress in gui/splash.cpp
   
Example callback class:

	class MyProgress: public synfig::ProgressCallback {
		VectorizationDialog &dialog;
		MyProgress(VectorizationDialog &dialog): dialog(dialog) { }

		virtual bool task(const std::string &task) {
			dialog.set_status("Task: " + task);
			App::process_all_events();
			return !dialog.cancel_pressed; // cancel_pressed should be set when 'cancel' button pressed
		}
		virtual bool error(const std::string &task) {
			dialog.set_status("Error: " + task);
			App::process_all_events();
			return !dialog.cancel_pressed;
		}
		virtual bool warning(const std::string &task) {
			dialog.set_status("Warning: " + task);
			App::process_all_events();
			return !dialog.cancel_pressed;
		}
		virtual bool amount_complete(int current, int total) {
			dialog.progressbar->set_fraction((float)current/(float)total);
			App::process_all_events();
			return !dialog.cancel_pressed;
		}
	};

Example process function:

	Layer::Handle do_something_great(synfig::ProgressCallback *cb) {
		assert(cb);

		Layer::Handle layer;
		{ 
			if (!cb->task("Do first part of the great thing"))
				return Layer::Handle();
			// guess that this part will take 20% of time (from 0% to 20%)
			SuperCallback scb(cb, 0, 20, 100);
			for(int i = 0; i < N; ++i) {
				// ...
				// some code
				// ...
				if (!cb1->amount_complete(i, N))
					return Layer::Handle();
			}
		}
		
		{
			if (!cb->task("Do second part of the great thing"))
				return Layer::Handle();
			// guess that this part will take 30% of time (from 20% to 50%)
			SuperCallback scb(cb, 20, 50, 100);
			for(int i = 0; i < N; ++i) {
				// ...
				// some code
				// ...
				if (!scb->amount_complete(i, N))
					return Layer::Handle();
			}
		}
		if (!cb->task("Do third part of the great thing"))
			return Layer::Handle();
		// guess that this part will take 50% of time (from 50% to 100%)
		SuperCallback scb(cb, 50, 100, 100);
		// call dedicated function, for example, and pass pointer to callback instance
		if (!some_func(layer, &scb))
			return Layer::Handle();
		
		return layer;
	}

Example calling of process function:
	
	MyProgress cb(*this); // here i assumed `this` is the dialog window
	
	if (Layer::Handle prepared_layer = do_something_great(&cb)) {
		// create an action to insert prepared_layer into canvas
		...
		...
	} else {
		show_message(
			"Oops... All was broken, but i have good news"
			" - you always can draw this image in vector by hands!" );
	}

**Comment by morevnaproject** [comment]
@blackwarthog The problem is that all vectorization process will be done inside of Synfig Action (which is a part of synfigapp). And `synfigapp` doesn't know anything about gui.

**Comment by morevnaproject** [comment]
...so, in fact, the solution would be to add ProgressCallback to Action class.

**Comment by blackwarthog** [comment]
I thing we do not need in a vectorizer action.
We need a dialog, with several settings, and, may be preview (in future). This seems unusable as an action.
Just use one action "add layer", layer will be prepared by vectorization module.

**Comment by ankit-kumar-dwivedi** [comment]
> @blackwarthog The problem is that all vectorization process will be done inside of Synfig Action (which is a part of synfigapp). And `synfigapp` doesn't know anything about gui.

Throwing in more info:
Actually, the action will act as a wrapper it will take layer and all other necessary params as input.
Then in perform() method I will pass the image and configuration just like this and in return will get the outline layer list
```
    studio::VectorizerCore vCore;
    std::vector< etl::handle<synfig::Layer> > result = vCore.vectorize(layer_bitmap_, conf);
```
so vCore is actually performing the task and not the action. Can't we just write some code in vCore to open a progress bar and control it's progress?

**Comment by morevnaproject** [comment]
> I thing we do not need in a vectorizer action.
> We need a dialog, with several settings, and, may be preview (in future). This seems unusable as an action.

And what if we will write a scripting system (in the future)? I am sure the scripting system will be based on actions. And vectorization will be useful for scripting. ^__^

> Just use one action "add layer", layer will be prepared by vectorization module.

This can be done, but looks hacky in my opinion. ^__^

**Comment by blackwarthog** [comment]
> ...so, in fact, the solution would be to add ProgressCallback to Action class.

hm.. yes, `canvas_interface()->get_ui_interface()` is also the implementation of ProgressCallback

but...

**Comment by ankit-kumar-dwivedi** [comment]
>  Just use one action "add layer", layer will be prepared by vectorization module.

@morevnaproject 
This seems feasible at present... and if user press `cancel` in between the process then no layer will be created. But in this case, vectorization will not actually be an action.

**Comment by blackwarthog** [comment]
We never used long time actions (UI can show 'One moment' window, but it looks like a hack). But actually we have abilities to change messages in a statusbar, and we can add the progress bar. Also we need to check is our UI locking while action is performing, and we need to add 'cancel' button in UI.

Hm... we need to reset cancel-status sometimes, but ProgressCallback does not provide this functionality... may be we can reset it any time then callback returns false...

And other. If action called by context menu - action parameters always sets by common UI, UI can provide selected layers, ducks and other things, action cannot ask parameters that not provided by UI. Also action with any set of parameters may be called by the tool, but vectorizer is not looks like a tool. So to call vectorizer action we always need a special dialog and some other code in gui.

We still have no API to use actions directly without GUI, so it is not necessery for now to make them dedicated.

So. Will be good to wait for the second of third such 'actions' (or for the implementation of API or a script system), and in future we can to extend the architecture for these type of actions and dedicate them from GUI, but for now i suggest to use an simple "add layer".

**Comment by morevnaproject** [comment]
>  Also action with any set of parameters may be called by the tool, but vectorizer is not looks like a tool.

Grouping/duplicating layers also not looks like a tool. ^__^ There are also a bunch of other actions, like exporting canvas, exporting valuenodes - they all do not look like a tool.

> So to call vectorizer action we always need a special dialog and some other code in gui.

No. The action will have all parameters relevant to GUI dialog. 

Here is a GUI dialog for vectorization:

![66486396_459704011475855_2251478008965627904_n](https://user-images.githubusercontent.com/332868/61988479-0a667280-b04c-11e9-8f36-7619bef5b037.png)

And the Vectorizer action will have following parameters:

- "layer" - `Param::TYPE_LAYER` (image layer that is going to be vectorized)
- "mode" - `TYPE_STRING` (vectorization mode)
- "threshold" - `TYPE_INTEGER`
- "accuracy" - `TYPE_INTEGER`
- "despeckling" - `TYPE_INTEGER`
- "max-thickness" - `TYPE_INTEGER`
- "preserve-painted-areas" - `TYPE_BOOL`
- "border" - `TYPE_BOOL`

So, it is enough to create this action and set appropriate parameters to execute it from anywhere.

Considering all above, I expecting @ankit-kumar-dwivedi to implement vectorization process inside of action.

Also, I am really support the idea of creating scripting system based on actions. I an see that creating vectorization as action will push development of action system, which in turn can create foundation for introducing scripting system. ^__^

**Comment by blackwarthog** [comment]
> > We never used long time actions bla-bla-bla... bla-bla... bla... bla-bla...


> >  Also action with any set of parameters may be called by the tool, but vectorizer is not looks like a tool.

Yes we have one hack - action can require one string.
And provide a default value to this string is a second hack - we should to break an action internal structure and bring input parameters checks to get_param function and keep duplicate in is_ready().

> > So to call vectorizer action we always need a special dialog and some other code in gui.
> No. The action will have all parameters relevant to GUI dialog. 
> Here is a GUI dialog for vectorization:
> 
> ![66486396_459704011475855_2251478008965627904_n](https://user-images.githubusercontent.com/332868/61988479-0a667280-b04c-11e9-8f36-7619bef5b037.png)

Here this code:
https://github.com/ankit-kumar-dwivedi/synfig/blob/vectorization/synfig-studio/src/gui/dialogs/vectorizersettings.cpp
And we always need it. Without this code in gui, special code for this single action, we cannot use vectorization. Why should we to split this code? And why need we to implement currently unusable abstraction of action for longtime vectorization process when gui architecture does not support longtime actions?


> And the Vectorizer action will have following parameters:

> - "layer" - `Param::TYPE_LAYER` (image layer that is going to be vectorized)
we can take it from selection

> - "mode" - `TYPE_STRING` (vectorization mode)
we can ask a single string via hack with Action::ParamDesc::set_user_supplied

> - "threshold" - `TYPE_INTEGER`
> - "accuracy" - `TYPE_INTEGER`
> - "despeckling" - `TYPE_INTEGER`
> - "max-thickness" - `TYPE_INTEGER`
> - "preserve-painted-areas" - `TYPE_BOOL`
> - "border" - `TYPE_BOOL`
action cannot ask these params without special for this action code in GUI


> So, it is enough to create this action and set appropriate parameters to execute it from anywhere.

"Anywhere" is special for this action c++ code in gui only. We have no abilities to do it by other way for now.

> Considering all above, I expecting @ankit-kumar-dwivedi to implement vectorization process inside of action.

It will be cheat with implementation of three features by cost of one:
1. implement vectorization
2. present set of extra action parameters of any type in autogenerated dialog box.
3. rewrite synfig gui to implement of ability to execute longtime actions
	- interface lock
	- redable statusbar
	- progressbar
	- cancel button
	- internal cancellation interface

> Also, I am really support the idea of creating scripting system based on actions. I an see that creating vectorization as action will push development of action system, which in turn can create foundation for introducing scripting system. ^__^

When it will implemented then will a good time to think about the best way to integrate vectorization functionality into synfigapp::Action
