### ISSUE TITLE
Dragging on canvas makes Synfig crash

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#896]
**Synfig version & platform**:
Master
Linux
**Issue description**:
Click dragging on canvas while the timeline is buffering makes Synfig crash every time even with an empty canvas. [I show you how here.](https://youtu.be/R4UtUTzmnB8)

**Comment by blackwarthog** [comment]
seems to be fixed in ee269a82d
need to recheck

**Comment by ebarranco** [comment]
Yes @blackwarthog this is working now and #617 seems fixed too! But we have this #870  back again...

**Comment by ebarranco** [comment]
This is fixed, thanks.
