### ISSUE TITLE
CMAKE BUILD: Synfig Studio crashes at start (.ui files not found)

### ISSUE THREAD

**Issue by ThaFireDragonOfDeath** [synfig/synfig#905]
**Synfig version & platform**:
Plattform: Manjaro Linux
Synfig version: Master (9bf1b3778b34790904d9c241b8da62e31ef103e4)

**Issue description**:
When Synfig Studio is build with 2-build-cmake.sh and the build result is started with the run-portable.sh Synfig Studio crashes with the following error output on the command line:
"synfig(18626) [12:08:25] error: FileError: Failed to open file “/home/voldracarno/Schreibtisch/Git/synfig/_debug/out/share/synfig/ui/canvas_options.ui”: Datei oder Verzeichnis nicht gefunden"

--> The .ui files are not installed by the cmake build system.

**Workaround:**
After the build you can the content of the folder "synfig-studio/ui/" to "_debug/out/share/synfig/ui/" after that Synfig Studio starts without problems.

**Comment by BobSynfig** [comment]
I added the missing informations in the corresponding CMakeLists.txt files.
Commited directly as it is minor modifications but of course compiled, verified and executed on my machine first ;)
Please try again

**Comment by ThaFireDragonOfDeath** [comment]
> Please try again

Thanks, the problem is solved. Synfig Studio is now building and starting without problems.
