### ISSUE TITLE
[Vectorization] Crash on vectorizing image "test-3-2017-08-04-yaga-tea-orig.png"

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#908]
Image - 
![test-3-2017-08-04-yaga-tea-orig](https://user-images.githubusercontent.com/332868/62460854-4f597a00-b7ad-11e9-80d6-8151ee0daebc.png)

Call stack -

![screenshot_001](https://user-images.githubusercontent.com/332868/62460899-7b74fb00-b7ad-11e9-902d-f7178c14b88b.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject no crash for me **however, took a very long time to render (155 outlines)** 
![image](https://user-images.githubusercontent.com/37617951/62476249-3c9e6f80-b7c4-11e9-87a7-12c6386a43d8.png)
PS: sorry my canvas settings made it look like this

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject what is your system configuration in which crash happened?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi I have tested it with latest version of "vectorization" branch (the one which is after rebasing on top of master, commit 5f206ecf077) and it worked for me. ^__^

![screenshot_001](https://user-images.githubusercontent.com/332868/62559530-5ebbee80-b8a5-11e9-972d-e870ff105a94.png)

**Comment by morevnaproject** [comment]
Woops, just tried second time and it is crashed. ^__^"

**Comment by morevnaproject** [comment]
The crash is not always reproducible, but after several attempts it can be triggered. Here is a video showing crash (at 1:14 ) - https://www.youtube.com/watch?v=XvIkrIhXHjM

**Comment by morevnaproject** [comment]
@blackwarthog any ideas?

**Comment by ankit-kumar-dwivedi** [comment]
seems to be fixed after https://github.com/ankit-kumar-dwivedi/synfig/commit/c2e1e98308fe1302b84d439b6c4a9f59d2923654
, please check

**Comment by morevnaproject** [comment]
I cannot trigger the crash now. It is interesting to see for case where `maxThickness` has non-zero value. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject in toonz code it is written that if we replace `maxThickness=0.0` then the result is not centerline but outline. Things are getting and now I am building morevna toonz to do a thorough comparison.

**Comment by morevnaproject** [comment]
Hmmm.... So, I have another question: does it returns widthpoints for outline if `maxThickness=0.0`? Or outline width is constant in this case?

The question is related to this point of #891:
![screenshot_006](https://user-images.githubusercontent.com/332868/62783565-e5134300-bae6-11e9-87fd-24847dccd67c.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject the outline width is set 0 if we set maxThickness=0.0 because the output of skeletonizer is fed to next step.

So far we know following things:
- No crash happens and output(which is actually outline as width =0) is correct.
- **The logic inside the if(maxThickness>0.0)** is the only difference between zero and non zero width so this is the place where logical error is happening

I have a long weekend till tuesday So I will be working on fix. I do want a bug free and accurate feature in the end other things can be fixed alongside this. [^_^] hope I will soon fix this

**Comment by morevnaproject** [comment]
Confirmed: this is fixed in https://github.com/ankit-kumar-dwivedi/synfig/commit/999212779a5eda163abfa8fa4e6bdb8071e7e35d
