### ISSUE TITLE
[Vectorization] Distorted result after vectorizing image "test-3-2017-08-04-yaga-tea.png"

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#909]
This is the same image as #908, but smaller size.
![test-3-2017-08-04-yaga-tea](https://user-images.githubusercontent.com/332868/62464007-b1b67880-b7b5-11e9-9567-e98f8b843e6f.png)

On running the vectorization process the result is not always correct. There is a bad result as well for example in the below image.
 
Vectorization completes successfully, but the result is the following (lots of extra lines):
![screenshot_008](https://user-images.githubusercontent.com/332868/62464090-e7f3f800-b7b5-11e9-9341-d66a4ff80381.png)

This is needed to be fixed.

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I suspect this to be related with "2 result error" which I mentioned on the forum. I am building synfig now. Will update about what is causing this. AFAIK this is front the first step, i.e polygonize it create 2 output which further creates two output. I need some time to find the exact point of error

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject seems like I was correct.
When I run the vectorizer I got this initially
![image](https://user-images.githubusercontent.com/37617951/62475116-019b3c80-b7c2-11e9-86d4-10b795dc6de6.png)

and on 2nd run, I got the same result as your
![image](https://user-images.githubusercontent.com/37617951/62475008-c00a9180-b7c1-11e9-9f4b-c6d322ab7c25.png)

So, changing the issue description now for more clarity [^_^]

**Comment by ankit-kumar-dwivedi** [comment]
@blackwarthog I found the line causing error
https://github.com/ankit-kumar-dwivedi/synfig/blob/8c16a17053a5f477b0880ae6313ca0e640f2fae8/synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp#L446

maxThickness is getting garbage value. Any Ideas what could be wrong?

**Comment by ankit-kumar-dwivedi** [comment]
seems to be fixed https://github.com/ankit-kumar-dwivedi/synfig/commit/c2e1e98308fe1302b84d439b6c4a9f59d2923654

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject is this class skippable?
https://github.com/morevnaproject/opentoonz/blob/ac3067fb0cdbdcbc4f7fca959cf0d6c212586fb4/toonz/sources/toonzlib/tcenterlineskeletonizer.cpp#L46

**Comment by ankit-kumar-dwivedi** [comment]
Finally Fixed [^_^]

**Comment by morevnaproject** [comment]
Confirmed! Great work! ^__^
