### ISSUE TITLE
[Vectorization] Fix placement of vectorization result

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#912]
At the moment vectorization result is placed at the very top of layer's stack.

Here's a sample file - 
[test-5.zip](https://github.com/synfig/synfig/files/3486575/test-5.zip)
(notice the Translate layer on top of image layer).

![screenshot_002](https://user-images.githubusercontent.com/332868/62782839-433f2680-bae5-11e9-9954-036cb0359389.png)

After vectorization it looks like this:
(notice the result is on top of layer stack and so it is shifted)

![screenshot_003](https://user-images.githubusercontent.com/332868/62782932-75508880-bae5-11e9-8277-21f850d8529c.png)

How it should be:
(resulting group right on top of image layer)
![screenshot_004](https://user-images.githubusercontent.com/332868/62782956-88fbef00-bae5-11e9-9edd-ca90aa3bb327.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject this is fixed in https://github.com/ankit-kumar-dwivedi/synfig/commit/cd0f9b9c04f10f0df420d9bd22322bf962067a1c
![image](https://user-images.githubusercontent.com/37617951/62818773-a377ac00-bb69-11e9-9b46-dc2af80134dc.png)
The panel shows correct z depth but not order. 
However, the result is always created outside of the switch can you please have a look when you are free. [^_^]

**Comment by morevnaproject** [comment]
> The panel shows correct z depth but not order.

I suggest to take a look at code of `layermove" action - https://github.com/ankit-kumar-dwivedi/synfig/blob/master/synfig-studio/src/synfigapp/actions/layermove.cpp#L149 ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject this is fixed now

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi For some reason this is not working correctly for me.

When I have the following setup:

![screenshot_001](https://user-images.githubusercontent.com/332868/63078116-ac4ef000-bf64-11e9-9f54-a2e4345b7908.png)

..the result is:

![screenshot_002](https://user-images.githubusercontent.com/332868/63078126-b375fe00-bf64-11e9-946c-71bf0333f76c.png)

(layer is displayed incorrectly in Layers Panel).

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject fixed in https://github.com/ankit-kumar-dwivedi/synfig/commit/20a3ae6f1ccf3adf670b6a9bda972652db6f7656

![image](https://user-images.githubusercontent.com/37617951/63090498-17a2bd00-bf79-11e9-894e-d0df0034abee.png)


> To-do: When inside the switch we select an image and call Vectorizer results are created outside of the switch

This is also fixed

**Comment by morevnaproject** [comment]
Works perfectly now! ^__^
