### ISSUE TITLE
[Vectorization] Do not use globals for "my_layer_bitmap" and "reference_layer" in "instance.cpp"

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#913]
See here:

https://github.com/ankit-kumar-dwivedi/synfig/blob/c2e1e98308fe1302b84d439b6c4a9f59d2923654/synfig-studio/src/gui/instance.cpp#L92-L94

**Comment by morevnaproject** [comment]
I think "insideSwitch" variable can be removed, because you can check type of `reference_layer` (LayerBitmap or not).

**Comment by morevnaproject** [comment]
Also, I think it is not good to use `gather_uri()` functions to add "Convert to vector" command.

I think it would be better to add separate code at the end of `add_special_layer_actions_to_menu()` and `add_special_layer_actions_to_group()` functions. The code should do the following:

1. Check if selection list and if only one layer is selected, then...
2. Check type of selected layer.
* 3a. If type of selected layer is LayerBitmap, then use it as `reference _layer` and `my_bitmap_layer`, add "Convert to Vector" entry to menu.
* 3b. If type of selected layer is SwitchGroup, then get its active layer and check its type. If it is BitmapLayer, then use it as `my_bitmap_layer` and SwitchGroup will be `reference _layer`. Add "Convert to Vector" entry to menu.

**Comment by morevnaproject** [comment]
In this case you will not need to declare `reference_layer` and `my_bitmap_layer` as global variables.

**Comment by ankit-kumar-dwivedi** [comment]
working on it!

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject please have a look at https://github.com/ankit-kumar-dwivedi/synfig/commit/97f25f6e88ffde3fae297eec57e7052787c2c48a
[^_^]

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi It works for me now! ^__^

Just one thing: the `Instance::layer_inside_switch()` function gets **first** layer from Switch Group. In common case, Switch Group can contain more than one layer. And active layer is not neccessary the first one. So, I suggest, instead of doing a `break;` on first layer - do a check for layer name and compare it with value of "Active Layer" parameter of Switch group.

![Выделение_001](https://user-images.githubusercontent.com/332868/64060384-ffc46d80-cbf5-11e9-85f2-9ea7aa3668b6.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Just to confirm!
So this means even if there are multiple layers inside switch "convert to Vector" Option should show up. 
And it should convert the active layer?

**Comment by morevnaproject** [comment]
Yes. ^__^
