### ISSUE TITLE
[Lottie exporter] 005-vectors.sif exports, but playback fails

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#918]
**Synfig version & platform**:
Commit id: 394aeea

**Issue description**:
Test file - https://github.com/synfig/synfig-tests-regressions/blob/master/export/lottie/005-vectors.sif

The export completes successfully, but  when I opening html file in browser it plays till the middle of animation and then stops.

**Comment by AnishGG** [comment]
I am looking into this now.
Will come up with a fix, once I find the mistake

**Comment by AnishGG** [comment]
It seems like I missed a `if` condition while calculating the tangents in a `radial_composite`.
Here it is: https://github.com/synfig/synfig/blob/6c97aa58ab0e4abbc916d2ca8bbf0c305c002c01/synfig-core/src/synfig/blinepoint.cpp#L85

It is fixed now. ^__^
@morevnaproject have a look please.

**Comment by morevnaproject** [comment]
@AnishGG Works like a charm! Thank you!
