### ISSUE TITLE
[Vectorization] Remove references to non-implemented features in GUI

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#920]
Coding period of GSOC is coming to an end, so let's start preparing Vectorization feature for merging into master branch.

For that I propose to temporary hide all GUI parameters that are not implemented yet:
![screenshot_001](https://user-images.githubusercontent.com/332868/63102042-88130380-bfa4-11e9-9032-c5057a9af9c7.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I think tooltip text should also be implemented so I am adding that now [^_^]

**Comment by ankit-kumar-dwivedi** [comment]
fixed in https://github.com/ankit-kumar-dwivedi/synfig/commit/fb91cf5760fd2ce061a21407025341894e0d0e8d
added tootltip text in https://github.com/ankit-kumar-dwivedi/synfig/commit/ffae6d06281ad02afb907c748c5fba1014dd142b
ping @morevnaproject

**Comment by ankit-kumar-dwivedi** [comment]
Closing as changes done

**Comment by morevnaproject** [comment]
Looks good, thank you! ^__^
