### ISSUE TITLE
[Vectorization] Incorrect size/location of vectorization result

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#923]
Sample file - 
[sticker-ivan-hq.zip](https://github.com/synfig/synfig/files/3512737/sticker-ivan-hq.zip)

Before vectorization:
![screenshot_003](https://user-images.githubusercontent.com/332868/63221061-5b860400-c1bd-11e9-9e70-606d1aca2885.png)

After vectorization:
![screenshot_004](https://user-images.githubusercontent.com/332868/63221062-60e34e80-c1bd-11e9-9b2f-608581228ca4.png)

Possibly this is related with non-standard canvas dimensions:
![screenshot_005](https://user-images.githubusercontent.com/332868/63221066-7d7f8680-c1bd-11e9-9481-c9c35d87634e.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject By size/location you mean it should be in center? I guess location here does not mean location in layer panel. Looking into it (^_^)

**Comment by morevnaproject** [comment]
Yes, this time it's location/size on workarea. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject so do I have to align it to image size? and not the image area? or both?

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject the same settings produce correct output but the file you sent does now so i am confused why this is happening. Do let me know if I am missing anything

**Comment by morevnaproject** [comment]
Please make sure to set canvas settings *before* you import image. ^__^

**Comment by morevnaproject** [comment]
Please see this video showing two cases - https://youtu.be/hy2boWxfVbE

In first case canvas settings set **after** image imported  (no bug).
In second case canvas settings set **before** image imported (bug exists).

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject this is what I used
```
synfig::Point q = (canvas->rend_desc().get_br() - canvas->rend_desc().get_tl());
  float p = canvas->rend_desc().get_w();
  
  float unit_size = p/q[0];

  // here fitting and shifting happen
  for(int i=0;i<segment_size;i++)
  {
    segment[i][0] = segment[i][0]/unit_size + topleft[0];//x from TL;
    segment[i][1] = segment[i][1]/unit_size + bottomright[1];// y from BR;
    segment[i][2] = segment[i][2]/2;
  }
```
here topleft and bottomright is for shifting origin.

**Comment by morevnaproject** [comment]
I think the problem happens because you do not take into account coordinates of ppints in Bitmap Layer. 

Here is a video showing an example - https://youtu.be/7jwaOGa5_KM

In the video I use default canvas settings. But I changing points of Bitmap Layer and that makes vectorization result misaligned. If you will take into account points of Bitmap Layer then issue will be solved. ^__^

**Comment by morevnaproject** [comment]
I suggest apply that transformation (the one you've got from Bitmap Layer's TL and BR) by adding a Scale and Translate layers inside of green group:
![screenshot_001](https://user-images.githubusercontent.com/332868/63279833-ed803080-c2d3-11e9-88d3-86be01cf409e.png)

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject 
few observations: (I removed scaling to see the size variation clearly.)

In this screenshot, the canvas size is changed to custom
![image](https://user-images.githubusercontent.com/37617951/63286758-65e7f100-c2d6-11e9-9557-90a93b8450fa.png)

Now in this one with default canvas properties, the size of the vectorized result is same as the custom one
![image](https://user-images.githubusercontent.com/37617951/63286971-d8f16780-c2d6-11e9-869e-a55756c0e844.png)

Steps needed to resolve:
- Scale the result as the canvas vary from default to other sizes

However, the one you mentioned here is the case when the image itself is manipulated using corner points. So they are two different issues but as both result size-related I think it is okay to keep both here


> I suggest apply that transformation (the one you've got from Bitmap Layer's TL and BR) by adding a Scale and Translate layers inside of green group:
> ![screenshot_001](https://user-images.githubusercontent.com/332868/63279833-ed803080-c2d3-11e9-88d3-86be01cf409e.png)

**Comment by ankit-kumar-dwivedi** [comment]
Issue related to file fixed in https://github.com/ankit-kumar-dwivedi/synfig/commit/708397e054fca212804c2c1409e3b7cfd463edfa
> Sample file -
> [sticker-ivan-hq.zip](https://github.com/synfig/synfig/files/3512737/sticker-ivan-hq.zip)
> 

> After vectorization:
> ![screenshot_004](https://user-images.githubusercontent.com/332868/63221062-60e34e80-c1bd-11e9-9b2f-608581228ca4.png)

![image](https://user-images.githubusercontent.com/37617951/63288349-17d4ec80-c2da-11e9-9b73-c652cdd198ef.png)

This was related to scaling and is solved. [^_^]
Now working to deal if image is manupulated using point

**Comment by ankit-kumar-dwivedi** [comment]
![diff](https://user-images.githubusercontent.com/37617951/63289613-296bc380-c2dd-11e9-8f0c-493fa158ded9.png)
@morevnaproject Which values should I consider to find resize param?

**Comment by morevnaproject** [comment]
> @morevnaproject Which values should I consider to find resize param?

Just check the code, which calculates initial placement of TL and BR points (when image is imported). Get those values. Then, compare them with current TL/BR values of BitmapLayer and you'll get the transformation. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Is this issue still unresolved?@morevnaproject

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject, please let me know if anything is left here

**Comment by morevnaproject** [comment]
Here is an illustration of a problem - https://www.youtube.com/watch?v=1qRBZHV-O5M

The problem happens if user manipulates points of Image Layer (inside of yellow Switch group).

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject got it!
So here is my plan:
- Take the image transformation
- Take the group transformation
- Merge them and apply to outline group

**Comment by ankit-kumar-dwivedi** [comment]
Please confirm if this would be a good way or not.
I am thinking to make tranformation for image layer using
**offset - change of origin
scale - (scaling x, scaling y)
angle(Angle::rad(0.0)),
skew_angle(Angle::rad(0.0)**
```
Transformation():
		offset(0.0, 0.0),
		angle(Angle::rad(0.0)),
		skew_angle(Angle::rad(0.0)),
		scale(1.0, 1.0)
	{ }
```
After that get the transformation from image group and add the attributes to get resultant which will be applied on output.

**Comment by morevnaproject** [comment]
Yes, you can create a new Transformation object (T1) with the code above. Then, you can get transformation from Group Layer (T2) and use `transform` method to apply transformation of T1 to it.
https://github.com/synfig/synfig/blob/107230cdb451d698b7de4cf99bfcbb6337f31f54/synfig-core/src/synfig/transformation.h#L177

**Comment by morevnaproject** [comment]
There is alternative solution, that you suggested in chat - it looks cool I think. Quoting:

> determine the
> - new origin 
> - TL
> - BR
> - x transformation and y transformation
> And apply it to the vectors that are being created

In fact I found that this approach is better! I mean it is better than changing transformation parameter of Group. In this case both groups (Yellow one with image and Green one with vectors) will have same transformation and this looks logical. And transformation of image layer is applied directly to vectors. That's cool.

@ice0 @blackwarthog Opinions?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi  For scaling beziers, I think it is enough to multiply each vertex, each tangent and width point to the same value.

**Comment by ankit-kumar-dwivedi** [comment]
> @ankit-kumar-dwivedi For scaling beziers, I think it is enough to multiply each vertex, each tangent and width point to the same value.
@morevnaproject Okay then, for now I am proceeding with this one will let you know what results I am getting :)

**Comment by ankit-kumar-dwivedi** [comment]
@ice0 @blackwarthog I am stuck with this thing... It does not seem logical to me can you please help.

when I drag the image layer using TL and BR points then Height and Width of image is changed but then why do I get the original image h and w with the following code? 
```
rendering::SurfaceResource::LockRead<rendering::SurfaceSW> lock( ras->rendering_surface );
	const Surface &surface = lock->get_surface(); 
	int width = surface.get_w(); 
	int height = surface.get_h(); 
```
@morevnaproject I think the change in dimension should be reflected in image layer itself don't you think? I might be wrong what do you guys think?
Currently, I am using the above code and 
```
  topleft = image->param_tl.get(synfig::Point());
  bottomright = image->param_br.get(synfig::Point());
```
and after that manually calculate the x diff and y diff to track the difference in dimensions is there any better way?

**Comment by blackwarthog** [comment]
here is the size of image raster in pixels, it significant when you access to pixels.

```
    rendering::SurfaceResource::LockRead<rendering::SurfaceSW> lock( ras->rendering_surface );
    const Surface &surface = lock->get_surface(); 
    int width = surface.get_w(); 
    int height = surface.get_h(); 
```


and here the position of this raster at canvas in synfig geometry abstract units of canvas:

```
    Point topleft = image->get_param("tl").get(Point());
    Point bottomright = image->get_param("br").get(Point());
```

they both is reqired.



As i understand you have a vectorization code which operates with pixels only and gives result in pixels. And after vectorization you need to recalculate coordinates, but there is no simple way to disproportional scaling of outlines widths.

So the best way is encapsulate all vectorization data in a group and inside this group represent coordinates in pixels of source images. And to set a valid visual size apply trasformation to a whole group using parameter "transformation" of Layer_Group.

You should calculate a fields of synfig::Trasformation structure using maths, size of surface in pixels and position at canvas in canvas units.
