### ISSUE TITLE
[Vectorization] Remember settings in vectorizer dialog

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#925]
When user  enters custom values in Vectorizer Settings Dialog, those values should be remembered. Currently, every time when Vectorizer Settings Dialog is opened all values are reset to defaults.

I think it's okay to remember settings until program closes. When programs closed it's okay to forget them (use default values when program started next time).

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Fixed in https://github.com/ankit-kumar-dwivedi/synfig/commit/a5a16442af5bc11f5823c814126e3a5a0e104d86
Closing now :)
