### ISSUE TITLE
[Lottie exporter] 072-skeleton-animated-pos.sif - animation inverted for Y axis

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#926]
**Synfig version & platform**:
Commit id: 7cadfbf1f

**Issue description**:
Test file - https://github.com/synfig/synfig-tests-regressions/blob/master/export/lottie/072-skeleton-animated-pos.sif

In original file bone is moving up.

When exported to Lottie and opened in browser you can see the bone is moving down.

**Comment by AnishGG** [comment]
This is happening because the `y-axis` in Synfig and Lottie are opposite to each other and 2 convert methods(bone link, composite) are stacked on each other.
I will push a patch soon.

**Comment by AnishGG** [comment]
This is fixed now. ^__^
@morevnaproject please have a look.

**Comment by morevnaproject** [comment]
Works perfectly now, thank you! ^__^
