### ISSUE TITLE
 [Lottie exporter] 077-groups-cutout.sif appears cropped

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#931]
**Synfig version & platform**:
Commit id: d298820567dfc8e

**Issue description**:
Test file - https://github.com/synfig/synfig-tests-regressions/blob/master/export/lottie/077-groups-cutout.sif

Here is the file opened in Synfig -
![screenshot_001](https://user-images.githubusercontent.com/332868/63504482-dcb20380-c4fb-11e9-8ccb-350f7d7a375c.png)

After exporting to Lottie the character's head appears cropped -
![screenshot_002](https://user-images.githubusercontent.com/332868/63504529-f6534b00-c4fb-11e9-9a90-def157218b2a.png)

**Comment by AnishGG** [comment]
I have pushed a commit fixing this.
@morevnaproject please have a look.

**Comment by morevnaproject** [comment]
Works perfectly now! Thank you! ^__^
