### ISSUE TITLE
[Lottie exporter] Add support for Gradients

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#934]
Make possible to export Gradient Layers.

**Comment by saurabh-ramola** [comment]
@morevnaproject Can I take this up?

**Comment by AnishGG** [comment]
Sure!
Assigning this to you.

**Comment by saurabh-ramola** [comment]
As gradient_ramp from adobe AE is not directly supported, @AnishGG  and me discussed this offline that we will use a rectangle layer of the same size of the composition and fill it with 'gradient fill' .

**Comment by AnishGG** [comment]
We are facing a difficulty in the gradient fill mapping of Lottie and hence I have created an issue(https://github.com/airbnb/lottie-web/issues/2055) at the lottie-web repository.
Waiting for a reply from their side. ^__^
@saurabh-ramola you can continue with some other issue till then.

**Comment by AnishGG** [comment]
Marking this issue as closed. Linear and Radial gradient layer are now supported. ^__^
