### ISSUE TITLE
How to import image without scaling to canvas (manually)

### ISSUE THREAD

**Issue by BarbzYHOOL** [synfig/synfig#938]
**Synfig version & platform**:
(we're more likely to help if you're using latest development builds)
1.21

**Issue description**:
How do I import an image with or without scaling to canvas WITHOUT changing it in preferences?? seriously this is so unpractical

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject @ice0 Is it really an issue?

**Comment by morevnaproject** [comment]
It would be nice to add a "Fit to canvas" checkbox into Image Import Dialog. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
Go to issue https://github.com/synfig/synfig/issues/1126 for more info

> It would be nice to add a "Fit to canvas" checkbox into Image Import Dialog. ^__^

Closing this one now.
