### ISSUE TITLE
[Lottie exporter] Add support for exporting Stretch Layer

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#939]
Add support for exporting Stretch Layer.

**Comment by AnishGG** [comment]
Could you provide this clarification: the main difference between [scale](https://wiki.synfig.org/Scale_Layer) layer and [stretch](https://wiki.synfig.org/Stretch_Layer) layer is that we can provide different scaling in both the axis in stretch layer. There is a unit difference also.
Am I correct here?

**Comment by AnishGG** [comment]
@morevnaproject could you please look at the above clarification. ^__^
I will be able to start with stretch layer after this.

**Comment by morevnaproject** [comment]
> the main difference between scale layer and stretch layer is that we can provide different scaling in both the axis in stretch layer.

Exactly!

> There is a unit difference also.

Yes, the units are different. ^__^

**Comment by morevnaproject** [comment]
Closed via 79febec2722b8bb6600e3ef6c4f1d5291d3bf12a
