### ISSUE TITLE
2-build-debug.sh don't work if any path directory contain space

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig#942]
**Synfig version & platform**:
version: latest master
platform: Debian 10

**Issue description**:
I had my synfig local repo inside `ankit/synfig master/synfig` and following output I get
```
ankit@debian:~/synfig master/synfig$ ./2-build-debug.sh
bash: /home/ankit/synfig: No such file or directory

```
after changing `ankit/synfig master/synfig` -> `ankit/synfig_master/synfig` it worked. 
I think it should work even if directory name contain space

**Comment by igordsm** [comment]
I can reproduce this and the same occurs with `2-build-cmake.sh`. Regarding `2-build-debug.sh`, I have escaped the source directory in many places and have got this far:

    Going to configure...
    running autoreconf...
    Done! Please run ./configure now.
    ~/Documents/synfig with spaces/_debug/ETL
    /home/igor/Documents/synfig with spaces/_debug/build
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking target system type... x86_64-pc-linux-gnu
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... configure: error: unsafe srcdir value: '/home/igor/Documents/synfig with spaces/ETL'

Apparently, `autoconf` does not like directories with spaces and refuses to continue. This has been reported in other places as well [1](https://trac.osgeo.org/grass/ticket/682)[2](https://stackoverflow.com/questions/16194124/autoconf-spaces-in-path?answertab=active#tab-top). 

However, CMake should be able to handle this. I propose changing the focus of the issue to get `2-build-cmake.sh` working with directories with spaces.

**Comment by morevnaproject** [comment]
@igordsm You right, it doesn't works even after fixing build scripts. Autotools just do not like directories with spaces.
