### ISSUE TITLE
[CMake build] Update documentation in README-CMake.md

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#961]
We need to update documentation in https://github.com/synfig/synfig/blob/master/README-CMake.md

See build instructions given here - https://github.com/synfig/synfig/issues/928#issuecomment-523350608

**Comment by AYESDIE** [comment]
Do we really need this file now? It'll be redundant to update this file and keep it updated with the actual documentation [here](https://synfig-docs-dev.readthedocs.io/en/latest/common/cmake.html) whenever any change is made in the future.

Maybe we can add a link to CMake's documentation in README.md over [here](https://github.com/synfig/synfig/blob/master/README.md#building-from-source).

**Comment by morevnaproject** [comment]
Good point.
