### ISSUE TITLE
Bad closing transitions with Draw Tool

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#963]
**Synfig version & platform**:
Master
Linux

**Issue description**:
Bad line transitions and change of width closing shapes using advanced outline with the draw tool.
[I show you here.](https://youtu.be/ackNN1zYOM4)

**Comment by ebarranco** [comment]
Graat! thank you.

**Comment by rodolforg** [comment]
@ebarranco do you remember what was your problem here?
We have to fix another issue that probably affects/changes the related code for this issue.

**Comment by ebarranco** [comment]
Yeah @rodolforg  Closing shapes gave me circular cuts and big weight values in advanced outlines.

**Comment by rodolforg** [comment]
And is it solved, right?

**Comment by ebarranco** [comment]
Yes it is solve. I did download the file from that issue and I had the same result.

**Comment by rodolforg** [comment]
Thank you.
