### ISSUE TITLE
Wrong Amount values in outlines and regions

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#964]
**Synfig version & platform**:
Master
Linux

**Issue description**:

Wrong Amount values in outlines and regions, using the Spline Tool.
[I show you here.](https://youtu.be/sVK4uTPaaCY)

**Comment by ice0** [comment]
Hi, Enrique!
Please check on the video [0:13](https://youtu.be/sVK4uTPaaCY?t=13) you have an opacity value of 0.87 in the Tool options (middle window on the right side)

**Comment by ebarranco** [comment]
You're absolutely right @ice0  I was unaware that I made this change, maybe drag my pen just enough and moved the value. Maybe the point is, should this value need to be preserve even tough I don't save any file, close the program and the value is still there when you start a completely new project.

**Comment by ice0** [comment]
@morevnaproject what do you think?

**Comment by Jose-Moreno** [comment]
Hi, I think new synfig files should always be created with predetermined values that the user can expect, unless of course there are plans for a template system in which case saving specific values to be used in future new files would make sense instead, but even then such changes should always be clearly communicated to the user.

@ebarranco If you change the opacity Amount to 1.0 and save the file. Do new files start with 1.0 opacity or do they keep showing with 0.87?

**Comment by ebarranco** [comment]
@Jose-Moreno  Yes, if you save your file your values are save too. I understand now how it works. I'm closing this issue.

**Comment by morevnaproject** [comment]
> @morevnaproject what do you think?

I think that many tool settings should NOT be remembered.

For example, here is a very frequent mistake of users from my experience:
User sets a tool blending mode from "Composite" (default) to "Onto" (accidentally or without knowledge of its meaning).
As result, tool draws nothing.
User restarts application, but Blend Method is remembered, so nothing changes.
Then angry user records a video about "bad application that refuses to work". 
(Real story, happened more than once).

So, I think some tool settings should not be remembred.

Question: which ones? We have to define a list.

> Hi, I think new synfig files should always be created with predetermined values

Please consider that tool options are saved in application settings, they are not specific for particular files. ^__^

**Comment by morevnaproject** [comment]
Okay, I realized that it's better to submit new issue instead of re-opening this one.
Discussions are welcome here - #980. ^__^
