### ISSUE TITLE
Crash when trying to change "Gamma correction" for canvas

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#975]
**Synfig version & platform**:
Commit id: 82ffbee5a24576138a7d3bfb7abd84dd4988182a

**Issue description**:
Synfig crashes when I try to switch to "Gamma correction" tab in canvas properties.

![screenshot_001](https://user-images.githubusercontent.com/332868/66709928-39ad9580-ed98-11e9-9799-482c7d083452.png)

**Comment by blackwarthog** [comment]
i cannot reproduce

**Comment by blackwarthog** [comment]
bug does not apperas on debug build, but exists in release.

**Comment by blackwarthog** [comment]
fixed
