### ISSUE TITLE
Ctrl + A in Parameters editor

### ISSUE THREAD

**Issue by hellocatfood** [synfig/synfig#981]
In the parameters editor I want to be able to press Ctrl + A to easily select the value and then delete it. Currently this is not possible and I have to manual delete each character or highlight it manually with my mouse. Can the use of Ctrl + A in the parameter editor be made possible?

**Comment by hellocatfood** [comment]
Possibly related to #628

**Comment by Keyikedalube** [comment]
@hellocatfood This is fixed in v1.4.0 :)
