### ISSUE TITLE
The outlines are distorted like extensive stripes

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#985]
**Synfig version & platform**:
Github version compiled on October 21, 2019 on Archlinux 64

**Issue description**:
the contours are distorted like extensive stripes in parts where there are nodes very close together. The problem is removed from the image when the sharp corner parameter is deactivated but I report this anomaly because I think it could cause unexpected results in more complex compositions. As always, I hope the information is helpful. Thank you very much for the great effort.

file with the anomaly

[OutlineError.sifz.zip](https://github.com/synfig/synfig/files/3774566/OutlineError.sifz.zip)

Some screenshots.

In Synfig studio 1.2.2

![BugOutline221](https://user-images.githubusercontent.com/45057390/67616057-bc235580-f799-11e9-9c96-74e6a63f9627.png)

When the file is opened in the development version, the following warning appears:

![BugOutline311-10212019](https://user-images.githubusercontent.com/45057390/67616099-39e76100-f79a-11e9-8140-a8980bff6b76.png)

In Synfig 1.3.11 compiled on October 21, 2019:
![BugOutline311-10212019-2](https://user-images.githubusercontent.com/45057390/67616119-7e72fc80-f79a-11e9-9533-b0f1190b53c6.png)

![BugOutline311-10212019-v](https://user-images.githubusercontent.com/45057390/67616143-cdb92d00-f79a-11e9-8206-779e945805aa.png)

**Comment by morevnaproject** [comment]
I have added this test to https://gitlab.com/synfig/synfig-tests
