### ISSUE TITLE
[Lottie exporter] Add automatic testing of code

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#989]
It would be nice to have a Travis CI job, which will automatically test new commits/PRs against a set of test files.

Test files are located here - https://gitlab.com/synfig/synfig-tests/tree/master/export/lottie

This could be just a simple call of lottie exporter python script. And it should detect export fails, like this one - #917. This way we can easily detect problems with exporter at early stages.

**Comment by AnishGG** [comment]
I will have a look at this.

**Comment by AnishGG** [comment]
For this issue, should the changes be made in this file? : https://github.com/synfig/synfig/blob/master/travis.sh
OR
should I make a different file whose execution will be called inside `travis.sh`

**Comment by ice0** [comment]
@AnishGG if i understand correctly lottie-plugin doesn't need builded Synfig for work. 

So i suggest to do some sort of testing script on Python (with PyTest or something like it) which can be executed locally, and add it to .travis.yml as a new job later.
