### ISSUE TITLE
libgomp.so.1

### ISSUE THREAD

**Issue by KyleMaas** [synfig/synfig#990]
**Synfig version & platform**:
SynfigStudio-1.3.11-testing-19.02.09-linux64-9583a.appimage
Gentoo Linux (amd64) current and up-to-date.
GCC version 8.3.0-r1
glibc version 2.29-r2

**Issue description**:
When attempting to launch SynfigStudio 1.3.11 from AppImage, I get the following errors:

/tmp/.mount_EM3kBo/usr/bin/synfigstudio: /usr/lib64/libgomp.so.1: version `GOMP_4.0' not found (required by /tmp/.mount_EM3kBo/usr/lib/libMagickWand-6.Q16.so.1)
/tmp/.mount_EM3kBo/usr/bin/synfigstudio: /usr/lib64/libgomp.so.1: version `GOMP_4.0' not found (required by /tmp/.mount_EM3kBo/usr/lib/libMagickCore-6.Q16.so.1)

I'm no AppImage expert, but this makes me think that the image is missing the libgomp.so.1 library.  I do not have openmp enabled system-wide, and am currently recompiling gcc to include support for it in the hopes that that fixes the problem, but I'd think that since it's tied to the GCC version, it would need to match the version used to compile the binary in the AppImage, and because of that the library should probably be included in the AppImage.

**Comment by KyleMaas** [comment]
I will note that recompiling gcc with openmp support enabled allows me to run the AppImage, but going that route might not be the most obvious fix for other Linux users.

**Comment by BobSynfig** [comment]
See also here: https://forums.synfig.org/t/solved-gomp-4-0-not-found-ubuntu-14-04-derivated-distros-related/9137/3

**Comment by KyleMaas** [comment]
Just wondering why this was closed?  I have not had a chance to retest this.  Was the AppImage fixed?  Or were too few people having problems with it to merit fixing it?

**Comment by rodolforg** [comment]
I don't know exactly why it was closed, but:
1. You can always reopen
2. You didn't commented the Bob answer for more than a year
3. 1.3.11 version is not the last version, but 1.4.0 : it's the new stable version (based on 1.3.x releases)

**Comment by ice0** [comment]
Hi, guys!
Looks like I closed it by accident, sorry. 

By the way, can you test flatpak build too?

**Comment by KyleMaas** [comment]
Thank you for revisiting this - happy to retest.  Just needed to recompile my system without OpenMP.

The problem still exists with the "SynfigStudio-1.4.0-stable-2020.11.14-linux64-b9862" AppImage.

The Flatpak works fine without system-wide OpenMP support.

**Comment by KyleMaas** [comment]
I should note that the message is now slightly different:

`/tmp/.mount_94GaOf/usr/bin/synfigstudio: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory`

**Comment by ice0** [comment]
@KyleMaas Please check updated AppImage:

x64 (https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2021.01.04-linux64-9089e.appimage)
x32 (https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.4.1-testing-2021.01.04-linux32-9089e.appimage)

**Comment by KyleMaas** [comment]
Only tested the x86_64 version, but that seems to work.  Thanks!

**Comment by ice0** [comment]
Awesome! Thank you!
