### ISSUE TITLE
Render window unresizable

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#997]
**Synfig version & platform**:
1.3.11
*Development version:
Revision: 20191027
Branch: master
Revision ID: d0285b*

**Issue description**:
Can't resize render dialog window on my Debian (XFCE) system. The window is too large, buttons like Cancel and Render are not accessible

![Screenshot_2019-11-06_08-43-00](https://user-images.githubusercontent.com/24214509/68265319-b408c700-0071-11ea-9efc-6e67f90a9ccd.png)

**Comment by rodolforg** [comment]
What's your screen resolution?

**Comment by Keyikedalube** [comment]
1366x768

**Comment by morevnaproject** [comment]
I think this is because Gamma widgets on "Gamma correction" tab.
![screenshot_005](https://user-images.githubusercontent.com/332868/68478916-969b4f00-0263-11ea-9dc7-aedd91a99bec.png)

They were moved here recently.

Time to tweak layout?

**Comment by Keyikedalube** [comment]
Don't you think those slider (scale) widgets are redundant? Anyway, I love the UI concept since it suits different users.

But if those scale widgets are removed I assume the render and canvas properties (noticed gamma widgets tab is there too) window would fit on a lower resolution monitor screen... at least on my 1366x768 screen.

**Comment by morevnaproject** [comment]
@Keyikedalube It would be nice to kee sliders, as they give idea about value range.

How about this layout? -
![1234](https://user-images.githubusercontent.com/332868/68598831-1890af80-04d2-11ea-8121-b7e8c234eb43.png)

**Comment by Keyikedalube** [comment]
Yes that layout looks much better.
Knowing value range visually is easier than trying to change numeric value randomly.

**Comment by Keyikedalube** [comment]
I tried implementing the same one above. And here's a sample screenshot of mine aligning slider buttons and GammaPattern on 2nd column (*Intended to center align second column*):

![Screenshot_2019-11-12_19-48-03](https://user-images.githubusercontent.com/24214509/68679360-bb563600-0585-11ea-81a5-a535d55dc927.png)

The window is still big but render and cancel buttons are visible at least.

Why isn't this layout designed using Glade? Coding UI is not very intuitive and productive. Had to compile every time with new padding values. It's so hard to visualize UI staring at code :(

**Comment by rodolforg** [comment]
This may help you:
https://developer.gnome.org/gtk3/stable/ch30s02.html

Try to make use of vexpand property

**Comment by Keyikedalube** [comment]
> This may help you:
> https://developer.gnome.org/gtk3/stable/ch30s02.html
> 
> Try to make use of vexpand property

Tried setting vexpand to false. No noticeable changes to the layout.

However I found this [gkmm scale class reference](https://developer.gnome.org/gtkmm/stable/classGtk_1_1Scale.html#a28473a3dead4c2a29bfe1399234266e2)
What if the draw value (the number above the slider) is removed since the spin buttons already indicates the number.
That way I feel the layout would be much more simpler and beautiful too

**Comment by Keyikedalube** [comment]
Here's the updated layout with set_draw_value set to false

![Screenshot_2019-11-13_20-27-34](https://user-images.githubusercontent.com/24214509/68775336-50bffb80-0654-11ea-9551-c09ee74ed273.png)

This fixes the render window too large issue.

But there is a slight change in the slider behavior too. The slider handle doesn't snap by .1 anymore ie., previously dragging the handle up snaps to 1.1, 1.2, 1.3,... from 1.0 and so on.
Now it's behavior is similar to scrolling up and down over the spin button and seeing somewhat accurate floating numbers.

**Comment by ice0** [comment]
> Why isn't this layout designed using Glade? Coding UI is not very intuitive and productive. Had to compile every time with new padding values. It's so hard to visualize UI staring at code :(

We are doing some steps in this direction, thanks to @rodolforg (https://github.com/synfig/synfig/commit/9207c07d523e93766aef84b210dc66319087be68), but still more work in progress.

If you do PR, i can look why the snapping doesn't work.

**Comment by morevnaproject** [comment]
Closed via #1006.
