### ISSUE TITLE
Set preview video zoom to "Fit" by default

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#998]
**Synfig version & platform**:
1.3.11
*Development version:
Revision: 20191027
Branch: master
Revision ID: d0285b*

**Issue description**:
When previewing video the actual preview window is always floating. I have to manually change zoom from *100%* to *Fit* every time I preview my animation.
Won't it be better to set the default zoom to *Fit* for better UX?

**Comment by morevnaproject** [comment]
Closed via #999
